### ISSUE TITLE
Case for empty usages

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1001]
I propose to forbid creation of textures and buffers with empty `GPUTextureUsage` or `GPUBufferUsage`.

**Comment by Kangz** [comment]
Do we have concerns that applications deciding texture/buffer usages programmatically might get an error?

I think it is less an issue as 0-sized buffers because a resource with no usage can never be used without triggering a validation error (except technically `GPUBufferDescriptor.mappedAtCreation`)

**Comment by kvark** [comment]
Yeah, I did consider the data-driven scenarios, and internally concluded that it's not useful there either.

**Comment by kainino0x** [comment]
Agree it would be fine to disallow this since you can never use it without an error anyway.

**Comment by GabrielMajeri** [comment]
This is what Vulkan says on buffer/texture empty usages:

> VALIDATION [VUID-VkBufferCreateInfo-usage-requiredbitmask (0)] : vkCreateBuffer: value of pCreateInfo->usage must not be 0. The Vulkan spec states: usage must not be 0 (khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-usage-requiredbitmask)
object info: (type: UNKNOWN, hndl: 0)

It would be consistent to disallow this in WebGPU.

**Comment by kainino0x** [comment]
Resolution: Disallow zero usages in buffer/texture creation.
