### ISSUE TITLE
Reusable command encoders

### ISSUE THREAD

**Issue by ottoville** [gpuweb/gpuweb#1003]
An update was just committed to Chromium [(link)](https://dawn.googlesource.com/dawn/+/76d9e34bbcb2353b9644add8e6bbbe61faee41c7%5E%21) which broke ability to reuse command buffers.

The reason behind this is that current spec does not specify command buffers re-usability. In section 12.1.1, there is just a comment " // TODO: reusability flag?"

I think that being a low level api, an implementation should have possibility to keep command buffers alive after first usage.

**Comment by kvark** [comment]
There is currently no specified behavior of command buffer re-use, and no extensions drafted even. So Chromium breakage is not releted to WebGPU proper.
Earlier, the group decided to not expose re-usable command buffers because Metal doesn't have this.
To some extent, `GPURenderBundle` can cover these needs.
Alternatively, you may describe a use case that would be improved by this feature, and somebody may post an investigation on how this could be implemented, likely as an extension.

**Comment by magcius** [comment]
I have been unaware of use case in Vulkan that reusable command buffers makes easier. They come with lots of restrictions.

**Comment by Kangz** [comment]
@ottoville this was actually a Chromium bug that it allowed command reuse: the group decided to not allow it for the MVP (maybe later, but maybe not). Sorry for the silent breakage.

**Comment by kainino0x** [comment]
Closing this as it was decided a long time ago that we would not have reusable command buffers, since the underlying reusable command buffers in Vulkan are so restricted and difficult to make useful.

GPURenderBundle (similar to a reusable secondary command buffer) largely takes care of the need.
