### ISSUE TITLE
Clarify the attachments state semantics

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#103]
We need to make a decision on what the attachments state is, and how it should be used. It's not obvious, and it may set a precedent for other states to follow (e.g. bind groups).

## Proposals

**Approach A**: strictly unique handles. The user creates an attachments state via `WebGPUDevice`, this handle has to be specified for both the render pipeline creation and the beginning of a render pass. This is implemented in #92.

**Approach B**: non-unique handles. The user still creates an attachments state via the device, but it can use different handles for render pipeline creation, and it's not provided at the beginning of a render pass. The workload is valid as long as the descriptors used for the `WebGPUAttachmensState` handles, which were used for the render pipeline creation, match the data provided at the beginning of a render pass. Also can be called "by-value" semantics (as opposed to "by-pointer").

**Approach C**: no handles. The user provides all the data (that defines Vulkan render pass compatibility) in-place when creating a render pipeline, and when beginning a render pass. The workload is valid if the attachments are compatible between that pass and pipelines used in it. This is implemented in #102.

**Comment by kvark** [comment]
Here comes a bit of analysis on the listed approaches.

**A** is appealing to me because it's very easy to write valid code: just make sure that the pieces responsible for pipeline creation and render pass recording agree with each other and use the same handle for attachments state. The errors are triggered early (mostly at initialization time). The downside is - it requires more coordination between the layers of code, e.g. between the end user and some middle-ware.

Approach **B** makes it less restrictive, at the cost of potentially delaying the triggered errors by invalid code, since it requires doing more validation (by value) at the recording time. Approach **C** moves the triggered error a little bit further (by arguably making it more difficult to write valid code from the start), but it has the benefit of lighter API (for no concept of an attachments state handle).

**Comment by kvark** [comment]
@Kangz Thanks for the quick response!

> Unfortunately we agree on the pros and cons but just give different weights to each side :/

At this point, I'm tired of arguing and just want any decision to be reached (as indicated by my own PR #102 for **C**), so that we can advance with implementation.

@litherum do I understand correctly that **C** is also your preference for Apple?

@RafaelCintron do you have a strong opinion on which one is the best (sorry if I missed it!)?

**Comment by RafaelCintron** [comment]
I would prefer **C** but in #102, you do not require the web developer to pass the render attachment state to beginRenderPass as separate data.  The web developer is only required to pass `WebGPURenderPassColorAttachmentDescriptor` to beginRenderPass.  Is that by design?  

If this is by design, I agree with the design because I was confused by the need to pass render attachment state as separate data to the render pass object in the first place.

**Comment by litherum** [comment]
I don't quite understand the difference between **B** and **C**. In both of them, metadata about the textures is provided to the pipeline creation function, and no metadata is supplied to render pass creation. It seems the only difference between them is whether or not the metadata is collected into an object or not. Is that true?

(If it is true, I prefer either **B** or **C**, and have no preference between them. Reusability of objects doesn't seem to matter much because the implementation can reuse them under the hood, and all the pipeline objects are usually created together at the beginning of time and are long-lived.)

To distinguish the 3 cases, maybe it would be helpful to include snippets of the code that you expect users would end up writing.

**Comment by kvark** [comment]
@RafaelCintron yes, this is by design.
@litherum yes, the **B** and **C** are rather close, and the only reason I included **B** is because during the last call there was a suggestion to have the attachments state handle to be treated "by-value". I think we'll get back to this topic in the context of resource group layouts, but for this question I agree that **B** doesn't appear to be a sound approach.

With this in, it looks like the group has converged into **C**.
