### ISSUE TITLE
Determine how errors during createReady*Pipeline are exposed

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1049]
- Do they go to the error scope, and propagate out to `onuncapturederror`? y/n
- Do they reject the promise (or just return an internally-invalid object)? y/n

I left this open in [ErrorConventions.md](https://github.com/gpuweb/gpuweb/blob/main/design/ErrorConventions.md), and it became irrelevant for a while because we didn't these entry points. Now we've re-added them and we need to figure it out.

The spec currently says yes and no, respectively.

One thing to keep in mind is that `onuncapturederror` is intended to work as a single point of contact [telemetry and bug reports](https://github.com/gpuweb/gpuweb/blob/main/design/ErrorHandling.md#telemetry). If we don't raise createReady errors there then devs have to pipe that through.

Another thing to consider is that there are two types of pipeline creation failure:
- deterministic errors/programmer error
- hardware-specific failure (couldn't allocate memory/registers, or whatever)

**Comment by Kangz** [comment]
I thought we had agreed to make erroring `createReadyPipeline` just reject the promise and not put anything in the error scope. I can't find anything about that in the [meeting minutes](https://docs.google.com/document/d/1eiDkPsGbrrYjoiHKBTSH_KspYmqJj3ZWbjXuoMAk_rk) where we discussed `createReadyPipeline`. However we briefly touched on this for promise ordering in #962.

Why it should reject and not return an error object: the error monad (or CIN) is used so the application can push WebGPU commands without needed roundtrips to know if something was an error. `createReadyPipeline` is an explicit roundtrip so it doesn't have this constraint. Since it is possible and efficient, and application would rather know directly if the pipeline compilation worked instead of looking into the error scope (that could end even later).

Why it shouldn't be in error scopes: it would break the ordering guarantees of error scopes, or potentially make error scopes take much longer to resolve.

Why it shouldn't be in `onuncapturederror`: the error is captured since the application waited for the pipeline compilation. Applications can still fire the `oncapturederror` callback directly if they want to push telemetry.

**Comment by kainino0x** [comment]
> Why it shouldn't be in error scopes: it would break the ordering guarantees of error scopes, or potentially make error scopes take much longer to resolve.

This is a very good point. I think this was probably the reason. Every createReady should act like it happens on a totally independent timeline or OS thread.

**Comment by kainino0x** [comment]
I want to say it would be nice if createReady validation errors could still go to `onuncapturederror` bypassing error scopes, to maintain the centralization for telemetry. But then there's no way to stop validation errors from going there (unless we add a flag, or an event with preventDefault, or something) which is a pain.

There's also onCompletion and mapAsync that return promises. Probably okay to have them reject but not send an error to the scope, too. But they could do both.

**Comment by kainino0x** [comment]
Resolved that errors here reject the promise and do not affect the error scope. This makes sense with the direction that createReady*Pipeline is a very independent operation from the rest of the API - just sends work off to the ether and gets a result back when it's done (doesn't happen on a particular timeline or anything).
