### ISSUE TITLE
[WGSL] Validate the grammar is unambiguous

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#1063]
I've done some initial work porting WGSL's grammar to Bison so we can determine whether its ambiguous or not. Here's the work-in-progress, as of 3c633ea8d2c331e41e40c8e003f82758bc95ff58:

[wgsl.y.zip](https://github.com/gpuweb/gpuweb/files/5198267/wgsl.y.zip)

A few observations:

1. The grammar is ambiguous today because of `type_decl argument_expression_list` casts. See the discussion about this in https://github.com/gpuweb/gpuweb/pull/1047 and https://docs.google.com/document/d/1LN-L9UEtLPFKfou7jrpiSLH42xGp5ybvKaBHFTc4VKg/edit#heading=h.hp3f2zbslxr9
1. The grammar isn't LALR(1) today because of `func_call_statement`. For example, in `foo(...) = 5;` vs `foo(...);`, the differentiator (`=` vs `;`) is many tokens *after* the point where we have to pick a path. I think this is fixable by rejiggering the grammar because `foo(...) = 5;` is illegal in WGSL (for now) anyway.
1. Bison doesn't support the `*` and `+` and `?` operators that are in the spec's grammar, so I had to replace them with additional helper rules. (Which is fine.)

In https://docs.google.com/document/d/1LN-L9UEtLPFKfou7jrpiSLH42xGp5ybvKaBHFTc4VKg/edit#heading=h.hp3f2zbslxr9 we decided to try to rejigger the grammar to be LALR(1) and see if it's possible without too much trouble, so we'll investigate doing that.

I don't think there was a resolution about what to do about casts. I expect we'll discuss this in the coming meeting.

**Comment by dneto0** [comment]
The  3c633ea commit  is from https://github.com/gpuweb/gpuweb/pull/1027 and seems unrelated. 

Thanks for summarizing the state.
Yes, I think it's well within reach to refactor rules to be right-recursive (waving my hands here).

FYI.  As a warmup exercise, I hacked together a script toward extracting a grammar from the current spec text.  It's most of the way there: https://github.com/gpuweb/gpuweb/pull/1062 
It's very hacky because of the irregularities that should be removed.

**Comment by dneto0** [comment]
I've pushed my hacky script a lot further. It's at the point where it would be useful.

**Comment by dj2** [comment]
I'd like the grammar to remain parsable by recursive descent. Currently it requires 2 or maybe 3 tokens of lookahead to do the parsing in Tint (it was 3, but we may have changed that bit since).

The current grammar is order dependant, so it would try to parse `func_call_statement ;` before the assignment. It would then attempt the assignment, so there should be no ambiguity in there at the moment (or maybe it comes from the translation to LALR?).

**Comment by dneto0** [comment]
My intuition is that refactoring the grammar would remove that order-dependency, and remove the apparent ambiguity when mapping to LALR.

A refactoring keeps the language the same but set of reduced productions for a valid string in the language would be different. But that would be to no semantic difference (my intuition again).

(FYI:   
- Each LL(k) language is also LR(k)
- Bison can generate parsers for LALR(1) and LR(1) languages.  https://www.gnu.org/software/bison/manual/html_node/LR-Table-Construction.html
)

My understanding that recursive descent is often preferred; e.g. Clang and other production compilers use it.

**Comment by johnkslang** [comment]
Recursive decent can certainly save some time and headaches:

- it avoids situations where, "if I could only look one more token ahead, I'd know exactly what to do, but instead, I have to go through tool contortions, and maybe make the language a bit less natural than what I want"
- it is easier to deal with in an implementation: just using the same language as the rest of the compiler, no extra legal issues with at extra tool, no extra cognitive load of having to understand how a parser parser works and why it's giving an error, etc.

**Comment by grorg** [comment]
I wonder if this can be closed now. We've resolved to validate.

@dj2 said:
> Technically the grammar isn’t LL(1), it is close. It isn’t recursive descent, but is trivially convertible to that. I want it to remain that way.

**Comment by dj2** [comment]
I think this should stay open until we've got the validation up and running, unless there was already another issue for that?

**Comment by dneto0** [comment]
In side discussion:

* @mehmetoguzderin suggested looking at https://tree-sitter.github.io to process the grammar and generate various kinds of backend parser generators
* @jimblandy suggested https://github.com/lalrpop/lalrpop because it has very nice diagnostics. It's written in Rust.

* About integrating into CI. @mehmetoguzderin said GitHub actions can easily get a Rust toolchain for use in actions.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-vf2f-2022-02-08,09-minutes#burndown-of-httpsgithubcomorgsgpuwebprojects2">WGSL meeting minutes 2022-02-08</a></summary>



    * KG: We have this now, from MOD, yes? (yes)
    * RM: There’s one ambiguity but we can close this.
    * See: [https://github.com/gpuweb/gpuweb/pull/2539](https://github.com/gpuweb/gpuweb/pull/2539)
</details>
