### ISSUE TITLE
Should clear values for integers lose precision, or be emulated on D3D12?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1085]
Spinoff from #965 for a specific question.

From https://github.com/gpuweb/gpuweb/issues/965#issuecomment-675078918, D3D12 only allows `float` values for ClearRenderTargetView and D3D12_RENDER_PASS_BEGINNING_ACCESS_CLEAR_PARAMETERS. In order to make the behavior portable we have two options:

- Round the clear value to float in all backends before passing the value in (makes it possible, e.g., to clear to `0xffff_ff00` but not any value greater than that).
- Emulate the clear with a fullscreen quad in D3D12 ([suggested here](https://bugs.chromium.org/p/dawn/issues/detail?id=528#c5)).

**Comment by kvark** [comment]
I don't think there is enough incentive for us here to implement the workaround. D3D12 is a widely used API, and if it doesn't have this ability, means users are OK to live with it. So I think we should go (1) and enforce the loss of precision on all backends.

**Comment by kainino0x** [comment]
Then there's also additional questions of:
- Should we change the API to take `float` so the loss of precision is less confusing?
- Should we restrict the API to only allow clear values up to 2**24 (i.e. MAX_SAFE_INTEGER but for f32) for integer textures to just avoid the "weird" domain entirely?

I think the workaround should be lightweight (we only have to do it if the clear value isn't representable as float) and avoids forcing developers to draw that quad themselves if they need it, so I'm leaning slightly toward it right now.

**Comment by kainino0x** [comment]
On second thought, restricting the API to only allow clear values up to 2**24 allows us to choose either direction (emulate or round) in the future, and is easy, so I like that.

**Comment by jdashg** [comment]
I'm shocked that D3D12 doesn't support clearing to 0xffff_ffff?

**Comment by kainino0x** [comment]
Rereading the linked D3D spec text, it may support (U)INT32_MAX/INT32_MIN (but not any other integer value not representable by a float), if it clamps the float value to the (u)int32_t range. I'm not totally clear on that: it says "the closest value is chosen" which possibly implies clamping, but then "the least significant bits of the destination are to be filled with 0's for _UINT" which implies no clamping.

Either way I don't think it should impact the decision on this issue.

**Comment by kvark** [comment]
Talked about this on the editors meeting. We don't see a clearly good future-proof decision supporting all the clear values here, other than disallowing anything above 2^24 for now. As @kainino0x noted, we'll be able to come back to that later and reconsider.

**Comment by kainino0x** [comment]
Resolution: Polyfilling this on D3D12 would require pipeline creation and probably could cause occasional hitches at render pass creation time, but should be minimal as render target state changes rarely. I think we ~agreed to just polyfill especially since this is a very rare case for most content so they wouldn't see the hitches. Also Rafael said we can get clearing to 0xffffffff by passing -1, so we should be able to avoid hitches for the most common case >2^24.

**Comment by RafaelCintron** [comment]
A bit more information about the topic from a D3D12 perspective: 

Below are a ways to clear UINT textures in D3D12:

* Draw a quad the covers the area to be cleared and write the clear value to the texture in a shader.  This will work on all hardware but is not as fast as using one of the 'clear' APIs.
* Add the `ALLOW_UNORDERED_ACCESS` flag on create and use the [ClearUnorderedAccessViewUint](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-clearunorderedaccessviewuint) function which accepts four unsigned integer clearing values. 
* If you want to just clear to UINT_MAX, you can either:
   * Create the texture using one of the 'typeless' formats and use a SINT32 render target view to clear the texture to -1.0.  
   * Check the `CastingFullyTypedFormatSupported` field of [D3D12_FEATURE_DATA_D3D12_OPTIONS3](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_feature_data_d3d12_options3).  If it is true, no need to make the texture as typeless.  

I’d advise using ClearRenderTargetView for clear values where that is possible, reinterpreting as SINT32 for clearing to UINT32_MAX. Otherwise, draw a quad.  We shouldn't use the ClearUnorderedAccessViewUint, because that will cost GPU perf even for apps that never actually use the problematic clear values.

**Comment by kainino0x** [comment]
> If you want to just clear to UINT_MAX, you can either:

Awesome, you answered the question I forgot to follow up with! Thanks! :)

**Comment by kainino0x** [comment]
I made some notes on implementation strategy on a [Dawn bug](https://bugs.chromium.org/p/dawn/issues/detail?id=537), in case it interests anyone.

**Comment by kainino0x** [comment]
Closing since the question is answered, and the task is tracked in #965.

**Comment by redorav** [comment]
Super late to the party but someone else is bound to see this: If you want to clear a UINT texture to 0xffffffff using ClearRenderTargetView, the D3D spec says: "INF in a higher range format must get converted to INF in the lower range format if available. If the lower format does not have an INF representation, it must be converted to the maximum value representable. The sign must be preserved if available in the target format." So basically, clear to inf works
