### ISSUE TITLE
Is Input/Output access one-way?

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1113]
Basically, if something is "input" storage class, do we want to allow mutating it? Same for "output" - do we allow shader to read the value?

I vaguely recall hitting OpenGL driver bugs back in the day related to this behavior, but I don't have any references by hand. Also, it's rather useless from the user perspective.

At the same time, it could be well supported by our target shading languages.

**Comment by dj2** [comment]
I think they should be. We should validate that input variables are not written too, and that output variables are not read from.

**Comment by Kangz** [comment]
What about an output variable being used as an accumulator, does this means developers will need to introduce an extra variable? It's a bit curious that read operations would be disallowed on them.

**Comment by kvark** [comment]
@dj2 great!

I guess I can see the case where at least mutating an input would be tricky for the driver. Say, you have a flat-interpolated integer. AMD would put it into a scalar register, accessible by all threads in the wave. If you try to mutate it, the shader compiler has to detect that and prevent the use of scalar registers.

For accumulating the output, I could also see how this would be confusing to the driver (although much less sure). The pipeline knows about the format of the outputs. If there is any conversion that's done by the shim inserted by the driver on assigning an output, then it's not trivial to read it back. Would love to hear any confirmation/refutal of this :)

**Comment by dj2** [comment]
Hm, for output doing accumulation would make sense. I was thinking from the input side where I'm not sure what writing to it would mean. Does it just change the current invocation? Are you somehow changing the input's source value?

For, output, since we don't have `+=` or anything along those lines, being able to read the value out and write back could be useful.

**Comment by dneto0** [comment]
On input:
*  variables in input storage class cannot be written to by the shader.
* By design, the features in WGSL and WebGPU are such that the system sets the value before the shader starts, and it stays steady for the duration of the invocation

On output:
* the variables are read-write for the shader.  (OpenGL/Vulkan tessellation shaders can cooperate to produce an output value. They may have to use control barriers to do so.  But this is beyond WGSL/WebGPU)
* The value of the variable at the end of the invocation is then taken downstream for further processing.   That may include format conversion, loss of precision or whatever.

**Comment by grorg** [comment]
Discussed at the [2020-10-19 Virtual F2F](https://docs.google.com/document/d/1NejOIbytIBVw_fgMmGdX6ZL7Owz_X72xzZf9nZ-0aaE/).

**Comment by grorg** [comment]
Resolution: As written in the comment above from @dneto0.
