### ISSUE TITLE
Operator Precedence

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1146]
Determine the operator precedence.

Existing PRs: #1111, #1136

**Comment by mehmetoguzderin** [comment]
@kainino0x should there also be an issue specifically for associativity? I think mixing precedence and associativity discussion can be a bit stepping on toes.

**Comment by kainino0x** [comment]
Hm, I think it would be hard to think about them separately. Decisions in one could affect the other. Also, associativity can be thought of as an aspect of precedence: in `x+y+z`, which `+` gets precedence?

**Comment by kainino0x** [comment]
Here's a proposal for a partially-ordered precedence (i.e. formalized "requires parentheses"):
It is a strict subset of both C's total ordering and Rust's partial ordering.

![partially_ordered_precedence](https://user-images.githubusercontent.com/606355/95907722-d52d6980-0d50-11eb-8e40-fbd8544d6280.png)

**Comment by kvark** [comment]
@kainino0x isn't this essentially https://github.com/gpuweb/gpuweb/pull/1111#issuecomment-705039742 ?

**Comment by kainino0x** [comment]
No, the order is copied from there (and C and Rust), but with strictly weaker ordering.

**Comment by mehmetoguzderin** [comment]
cc: @RobinMorisset

**Comment by kainino0x** [comment]
Some expressions that would be invalid with both (due to "Require parentheses" in #1111, due to "No assoc" in my proposal):

`a == b == c`
`a == b != c`
`a < b < c`

Some expressions would be valid with #1111 but would become invalid with my proposal:

`a & b == c`
`a & b && c`
`a & b ^ c`

Looking at this I would probably amend the proposal to disallow things like this because they're confusing:

`a & b << c`

**Comment by mehmetoguzderin** [comment]
> Some expressions would be valid with #1111 but would become invalid with my proposal:
> `a & b == c`

Wasn't allowing expressions like this one of the main motivations of reordering in the first place?

**Comment by kainino0x** [comment]
It wasn't to allow such expressions, but instead to make sure they didn't have surprising results (if you're coming from GLSL, for example). In this proposal there are no surprising results (regardless of whether you're coming from GLSL, C, JS, Rust), because it's a compile error.

**Comment by RobinMorisset** [comment]
Thank you for this graphical representation of the partial order, I find it very readable, and I generally like it.

To address your point that "a & b << c" is kinda ambiguous, I would ideally put << and >> at the same level as & and | (thus making both, and comparison operators, one step below x+y and x-y). I don't know how it would compare with Rust, but since it would only force parentheses in a couple of cases, and never have a non-intuitive result it seems safe to me.

Also I'd like to add that making the order more total (i.e. adding arrows in the graph you provided) is something we can do retroactively, but making it more partial (i.e. removing arrows) is not. So if we hesitate between two proposals, picking the one with a more partial order would make sense.

**Comment by kainino0x** [comment]
> Also I'd like to add that making the order more total (i.e. adding arrows in the graph you provided) is something we can do retroactively, but making it more partial (i.e. removing arrows) is not.

Yes! I do like this property a lot.

**Comment by kainino0x** [comment]
Tried to document some existing languages and some alternative proposals.
https://docs.google.com/presentation/d/12O2bAB1FqjMx7BnM5uE7P48Xd4sHE3qq6MhXGwJuaG4/edit?usp=sharing

Swift, as it happens, already has partial operator precedence, but I didn't find a good reference on what the exact partial-ordering is. (Also didn't want to spend even more time on this.)

(Aside: There's also a strong argument that the ordering for the left and right sides of `/` should be different. But I didn't find any languages that disagree on this so I kept the normal rule.)

**Comment by dneto0** [comment]
I like the V2 proposals better than v1.

I very much like:
-  having comparisons at lower priority than arithmetic.
- having short-circuiting operations && and || at even lower precedence.
- Aside from that, I usually write and expect lots of parentheses, so I can go with the group opinion otherwise.

I hope I'm understanding correctly about associativity:  That operators in the same green box associate with each other, and "left-to-right" means left-associative?  That is    a * b * c  really means (a*b)*c  ?

**Comment by kainino0x** [comment]
> I hope I'm understanding correctly about associativity: That operators in the same green box associate with each other, and "left-to-right" means left-associative? That is a * b * c really means (a*b)*c ?

Yes, I'll change the wording.

**Comment by kainino0x** [comment]
Resolution: Tweaked v2b to create v3; accept it. E.g. it allows a non-breaking change to v2b later.

![Operator Precedence Partial Orderings v3](https://user-images.githubusercontent.com/606355/96922283-7d83b200-1464-11eb-9e9b-724d9d7fb4ed.png)
