### ISSUE TITLE
There are too many combinations of texture bind point type and sampler bind point type

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#1164]
From https://github.com/gpuweb/gpuweb/pull/1076

We now have 5 texture bind point type and 3 sampler bind point type. Now that the matrix has grown so much, the claim "people just know what bind point to pick" is more difficult too justify. In particular, our matrix is now significantly larger than it is for any native API.

We should investigate just how costly deferring certain kinds of validation is.

I think there could be three different results from this analysis:
1. Deferred validation is too expensive, we shouldn't allow authors to trigger it, no way no how.
2. Deferred validation can get expensive, but for simple cases it's not, and the benefit of allowing authors to specify less information up front is sometimes larger than the runtime cost of deferred validation, for some apps
3. Deferred validation is somehow super cheap, and we can just always defer it and not require any of this complicated stuff up front

**Comment by kainino0x** [comment]
I don't think 3 is possible without significant engineering effort (dirty bits/caching). My intuition is that without that effort we're in bucket 2 and there's good value in allowing both early and drawtime checking.

**Comment by kainino0x** [comment]
Note that dirty bits/caching add a pretty significant security surface because any minor error in the logic could result in executing invalid draws.

**Comment by kvark** [comment]
@litherum this is not *just* about validation. It also goes hand to hand with the property of API portability. If we defer the validation of texture-sampler combinations to draw time, then we drastically increase the chances for users to experience application breakage, just because some pipeline and a bind group layout that worked 99% suddenly fail at draw time because:
  - a texture or a sampler that was dynamically created doesn't match the pipeline expectations
  - the shader got minor edits that affects which textures are used with with samplers

So this is a situation I'd like WebGPU to minimize, if possible. Coincidentally, fighting this also pays out in more predictable performance.

If that helps, we can move the "multisampled-texture" and "filtered-texture" into the `GPUTextureComponentType` variants, in line with https://github.com/gpuweb/gpuweb/pull/1076#issuecomment-713888180

**Comment by Kangz** [comment]
It's true that `GPUBindGroupLayout` has become a monster, and requiring the full detail will make it harder for developer to start using WebGPU (and will make the API less "a joy" to use). However @kvark's concern is valid (although not a portability but a predictability thing?). It is an ugly tradeoff and I don't know what solution is best.

If we decide to go with optional draw-time validation, I think we should restructure the `GPUBindGroupLayoutDescriptor` to help make it easy to see what's required and optional, and easy to know what's opt-in for a specific binding type:

```webidl
enum GPUBindingType {
    "uniform-buffer",
    "storage-buffer",
    "readonly-storage-buffer",
    "sampler",
    "sampled-texture",
    "readonly-storage-texture",
    "writeonly-storage-texture"
};

// Renamed GPUTextureComponentType
enum GPUSamplingOperationType {
    "float",
    "sint",
    "uint",
    "depth-comparison"
};

enum GPUSamplerKind {
    "non-filtering",
    "filtering",
    "depth",
};

enum GPUTextureKind {
    "multisample",
    "filterable",
    "non-filterable",
};

dictionary GPUBindGroupLayoutEntry {
    // doesn't change
    required GPUIndex32 binding;
    required GPUShaderStageFlags visibility;
    required GPUBindingType type;
    boolean hasDynamicOffset;

    // Optional data for samplers
    GPUSamplerKind samplerKind;

    // Optional data for buffers.
    GPUSize64 minBufferBindingSize;

    // Optional data for all texture binding types
    GPUTextureViewDimension viewDimension;

    // Optional data for sampled textures
    GPUSamplingOperationType samplingResultType;
    GPUSampledTextureKind textureKind; // Might be used in the future for multisample storage?

    // Optional data for storage texture types
    GPUTextureFormat storageTextureFormat;
};
```

It looks even more like a monster, and it is if you want to pass all the information to avoid all draw-time validation. However things in the simple case look much simpler (for developers getting started with the API this isn't super scary):

```js
device.createBindGroupLayout({
    entries: [
        {binding: 0, visibility, type: "sampler"},
        {binding: 1, visibility, type: "sampled-texture"},
    ]
})
```

Also I think it should be made clear in developer guidelines that not specifying on piece of data might result in draw-time validation of all the pieces of data.

**Comment by kainino0x** [comment]
Overall I think that looks nicer. Not sure about the details.

Every time this gets more complicated it reminds me that I would love if this could be an algebraic data type (tagged union). It can't, because dictionary types can't be unioned (they're not considered distinguishable by WebIDL), but we could consider doing either of the following:

```webidl
dictionary GPUBindGroupLayoutEntry {
    required GPUIndex32 binding;
    required GPUShaderStageFlags visibility;
    required GPUBindingType type;

    AdditionalStuffForUniformBuffer additionalStuffForUniformBuffer;
    AdditionalStuffForSampledTexture additionalStuffForSampledTexture;
    ...
};
```

or

```webidl
dictionary GPUBindGroupLayoutEntry {
    required GPUIndex32 binding;
    required GPUShaderStageFlags visibility;
    required GPUBindingType type;

    object additionalStuffForBindingType;
};
```
(with spec text that says "if type is `"uniform-buffer"`, create an `AdditionalStuffForUniformBuffer` from `additionalStuffForBindingType`, ...")

Looking at it now, the first one is actually kind of a nice middle ground.

**Comment by Kangz** [comment]
> Looking at it now, the first one is actually kind of a nice middle ground.

IDK, it looks easier to use internally in the specification, but I don't know that Javascript developers will find it better to type an extra nesting with the name of the binding type (which is redundant info). I agree it would have been nicer in a language with algebraic data types because you'd have a sum-type, but JS doesn't have that.

**Comment by kainino0x** [comment]
I think it's easier because the binding type tells you exactly one of those additional fields is required and the rest must be undefined. However we can write prose in the spec that probably makes that almost as clear.

**Comment by kainino0x** [comment]
btw it should be possible to express any of these options somewhat nicely in typescript. I haven't done this in gpuweb/types, but if the type system has knowledge of the actual value of `type: GPUBindingType` then it can restrict the other fields. Part of the reason I haven't done anything like this is because it would actually make the TypeScript more restrictive than the IDL, and I try to keep it only to the IDL rules because anything more strict could cause us to miss validation test cases by making them uncompilable-by-default (without `as` type assertions)

**Comment by kainino0x** [comment]
Resolution: Someone should build off of GPUSamplerKind/GPUTextureKind to try to come up with a proposal that reduces the number of binding types, provides good defaults for the sampler kind and texture kind, and still avoids runtime validation.

**Comment by Kangz** [comment]
I'll take a stab at this based on the previous suggestion:

```webidl
enum GPUBindingType {
    "uniform-buffer",
    "storage-buffer",
    "readonly-storage-buffer",
    "sampler",
    "sampled-texture",
    "readonly-storage-texture",
    "writeonly-storage-texture"
};

// Renamed GPUTextureComponentType
enum GPUSamplingOperationType {
    "float",
    "sint",
    "uint",
    "depth-comparison"
};

enum GPUSamplerKind {
    "addressing-only",
    "filtering",
    "comparison",
};

enum GPUTextureKind {
    "multisample",
    "filterable",
    "non-filterable",
};

dictionary GPUBindGroupLayoutEntry {
    // doesn't change
    required GPUIndex32 binding;
    required GPUShaderStageFlags visibility;
    required GPUBindingType type;

    // Optional data for buffers
    boolean hasDynamicOffset = false;
    GPUSize64 minBufferBindingSize = 0; // This causes draw-time validation by default.

    // Optional data for samplers
    GPUSamplerKind samplerKind = "filtering";

    // Optional data for all texture binding types
    GPUTextureViewDimension viewDimension = "2d";

    // Optional data for sampled textures
    GPUSamplingOperationType samplingResultType = "float";
    GPUSampledTextureKind textureKind = "filterable"; // Might be used in the future for multisample storage?

    // Optional data for storage texture types
    GPUTextureFormat storageTextureFormat; // This one is required if you're going to use storage textures.
};
```

This is what it looks like to make a BGL for a shader that samples a texture with a uniform buffer.

```js
device.createBindGroupLayout({
    entries: [
        // minBufferSize=0, non-dynamic uniform buffer.
        {binding: 0, visibility: GPUShaderStage.FRAGMENT, type: "uniform-buffer"}, 
        // filtering sampler.
        {binding: 1, visibility: GPUShaderStage.FRAGMENT, type: "sampler"},
        // 2D, float, filtered, sampled texture.
        {binding: 2, visibility: GPUShaderStage.FRAGMENT, type: "sampled-texture"},
    ],
});
```

I'm happy to bikeshed more to get to something even nicer, and we could choose to have some of the value be truly undefined and result in draw-time validation if we want to use the learning curve past this simplest example.

**Comment by kvark** [comment]
I don't believe in defaults here. Binding types is one of the core topics of the API, they need to be understood in order to use the API for anything beyond trivial. And beginners can follow the tutorials for selecting the proper binding type.

Having defaults incurs a cognitive cost to all intermediate and advanced users to the API: now, when somebody is reviewing the code, they'd have to always ask themselves "is there something I don't see in the code that's implied"? I'd argue that this code should cater single-write to multiple-read scenario rather than the opposite.
Then they'd write internal guidelines for people to always explicitly specify the binding types, then they'd write python linters, employ them on CI, etc. So much churn, so much work and attention just wasted.

**Comment by kainino0x** [comment]
I think it's okay to make these details of these binding types secondary. Most importantly, as soon as they become important to an application, they'll start seeing error messages. I think a reviewer should be able to rely on testing to show that the code runs without errors at least in basic cases.

I am also fine with the suggested renames, but I currently like the "kinds" proposal.

**Comment by Kangz** [comment]
I have a preference for having good defaults and more expert applications using WebGPU can enforce that the defaults are spelled out. IMHO I think it makes sense to use the defaults in applications because for a sampler the most common operation if "filter sampling". If I see a `samplerKind: ...` I'll know I need to pay extra attention because it isn't the usual type of samplers. Same thing for `textureKind`, `textureComponentType` or `hasDynamicOffset`.

Based on discussions with @kvark offline, another possibility is to extend the "kind" for textures:

```webidl
enum GPUBindingType {
    "uniform-buffer",
    "storage-buffer",
    "readonly-storage-buffer",
    "sampler",
    "texture", // OMG there's a single texture binding type!
};

// Renamed GPUTextureComponentType
enum GPUSamplingOperationType {
    "float",
    "sint",
    "uint",
    "depth-comparison"
};

enum GPUSamplerKind {
    "comparison",
    "filter-sampling",
    "point-sampling",
};

enum GPUTextureKind {
    "multisample",
    "filter-sampled",
    "point-sampled",
    "readonly-storage",
    "writeonly-storage",
    "storage", // in the future
};

dictionary GPUBindGroupLayoutEntry {
    // doesn't change
    required GPUIndex32 binding;
    required GPUShaderStageFlags visibility;
    required GPUBindingType type;

    // Optional data for buffers
    boolean hasDynamicOffset = false;
    GPUSize64 minBufferBindingSize = 0; // This causes draw-time validation by default.

    // Optional data for samplers
    GPUSamplerKind samplerKind = "filter-sampling";

    // Optional data for all texture binding types
    GPUTextureViewDimension viewDimension = "2d";

    // Optional data for sampled textures
    GPUSamplingOperationType samplingResultType = "float";
    GPUSampledTextureKind textureKind = "filter-sampled";

    // Optional data for storage texture types
    GPUTextureFormat storageTextureFormat; // This one is required if you're going to use storage textures.
};
```

Then making the BGL looks like this:

```js
device.createBindGroupLayout({
    entries: [
        // minBufferSize=0, non-dynamic uniform buffer.
        {binding: 0, visibility: GPUShaderStage.FRAGMENT, type: "uniform-buffer"}, 
        // filtering sampler.
        {binding: 1, visibility: GPUShaderStage.FRAGMENT, type: "sampler"},
        // 2D, float, filtered, sampled texture.
        {binding: 2, visibility: GPUShaderStage.FRAGMENT, type: "texture"},
    ],
});
```

**Comment by Kangz** [comment]
In a discussion offline, @jdashg suggested that it would help to see the BGL without the defaults, here it is:

```js
device.createBindGroupLayout({
    entries: [{
         binding: 0,
         visibility: GPUShaderStage.FRAGMENT,
         type: "uniform-buffer",
         hasDynamicOffset: false,
     }, {
        binding: 1,
        visibility: GPUShaderStage.FRAGMENT,
        type: "sampler",
        samplerKind: "filter-sampling",
    }, {
        binding: 2,
        visibility: GPUShaderStage.FRAGMENT,
        type: "texture",
        viewDimension: "2d",
        samplingResultType: "float",
        textureKind: "filter-sampled",
    }],
});
```

It's pretty big and scary.

**Comment by Kangz** [comment]
If we have a big dictionary with default values like outlined above, a concern was that both options to handle defaults have drawbacks:

 - If the default are true value (like `viewDimension: "2d"`) then it also gets set for buffer bindings so the validation for buffer bindings should ignore these default values. This is bad because it lets developers write non-sensical `GPUBindGroupLayoutEntries`.
 - If the defaults are done with the values being undefined, then we need to add in various places in the spec text like the following: "if this is a texture binding, if the viewDimension is undefined, then replace it with 2d". This is difficult to discover for developers as it is not in the WebIDL.

An option would be to have sub-descriptors per large class of bindings:

```webidl
enum GPUBufferKind {
    "uniform",
    "storage",
    "readonly-storage",
};

dictionary GPUBufferLayoutEntry {
    GPUBufferKind kind = "uniform";
    boolean hasDynamicOffset = false;
    GPUSize64 minBufferBindingSize = 0;
};

enum GPUSamplerKind {
    "comparison",
    "filter-sampling",
    "point-sampling",
};

dictionary GPUSamplerLayoutEntry {
    GPUSamplerKind kind = "filter-sampling";
};

enum GPUTextureKind {
    "multisample",
    "filter-sampled",
    "point-sampled",
    "readonly-storage",
    "writeonly-storage",
    "storage", // in the future
};

enum GPUSamplingOperationType {
    "float",
    "sint",
    "uint",
    "depth-comparison"
};

dictionary GPUTextureLayoutEntry {
    GPUSampledTextureKind kind = "filter-sampled";

    GPUTextureViewDimension viewDimension = "2d";
    GPUSamplingOperationType samplingResultType = "float";
    GPUTextureFormat storageTextureFormat;
};

dictionary GPUBindGroupLayoutEntry {
    required GPUIndex32 binding;
    required GPUShaderStageFlags visibility;

    GPUBufferLayoutEntry buffer;
    GPUSamplerLayoutEntry sampler;
    GPUTextureLayoutEntry texture;
};
```

Then the simple BGL creation code would look like the following:

```js
device.createBindGroupLayout({
    entries: [
        {binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: {kind: "uniform"}},  // or just {}?
        {binding: 1, visibility: GPUShaderStage.FRAGMENT, sampler: {}},
        {binding: 2, visibility: GPUShaderStage.FRAGMENT, texture: {}},
    ],
});
```

**Comment by kvark** [comment]
I think it could work :) @toji volunteered to write a draft for this API (as agreed on the editors meeting)
