### ISSUE TITLE
texture sampling with integer offset - portability concern

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1206]
HLSL documentation says:
> [in] An optional texture coordinate offset, which can be used for any texture-object types. The offset is applied to the location before sampling. Use an offset only at an integer miplevel; otherwise, you may get results that do not translate well to hardware. The argument type is dependent on the texture-object type. For more info, see "Applying Integer Offsets".

I'm worried about "do not translate well to hardware" part. #1024 adds a whole ton of offset-enabled texture sampling functions, generally with non-integer mipmap levels.

**Comment by grorg** [comment]
Discussed at the [2020-11-10 meeting](https://docs.google.com/document/d/1QFWUKpCcoLCMGHfJQWJurSPk-9PDcJ1Gc51FSg3_Fr8/).

**Comment by grorg** [comment]
Reference for the above: https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Fdirect3dhlsl%2Fdx-graphics-hlsl-to-sample

**Comment by jdashg** [comment]
It sounds like the warning here is about perf not portability.

--

On the call there was a proposal to forbid this anyway, since "this is probably not what you want to do", but I think that's going too far.

Even though it's not recommended to use is this particular way, it's fully supported by existing APIs, just with a usage caveat.
A shader many choose to use explicit float lod with (int) offset because while they normally supply an int-valued (float) lod, they may rarely or exceptionally use a non-int lod, perhaps transiently across a couple frames during scene transitions.

Lacking this functionality, which otherwise appears to have universal support in native APIs, the shader would need to be rewritten/de-optimized to do a userland implementation of this built-in. Certain uses of this built-in may be pessimal but the built-in should be at least as fast as the userland implementation.

I would recommend concerned UAs emit warnings here rather than second-guess all the native APIs here. We may want to include a non-normative warning similar to the HLSL warning in our documentation too, but my instinct is to keep this functionality.

**Comment by kvark** [comment]
The action items from the call were to ask Microsoft and Apple for clarification about the behavior on D3D and Metal correspondingly. It's not clear yet if "it's fully supported by existing APIs" to begin with.
Frankly, I am surprised SPIR-V tries to define that. It could just say "undefined result". Arguably, the same offset in different mips doesn't make much sense.

**Comment by pow2clk** [comment]
We have determined that the phrase in question is in reference to the complications with using an explicit texel-wise offset on two different mip levels for whom the scale of a set number of texels is drastically different. This issue was discussed in the last meeting. It is meant to refer to nothing more than that.

Given the differences in how different hardware determine exactly how to blend mip levels, it might work in the intended way on one device only to do something completely different on another. It's a warning to users that should probably be worded better.

**Comment by kvark** [comment]
@pow2clk your clarification is confusing me even more.

Given that you are talking about "the scale of a set number of texels is drastically different", would it be right to assume that D3D hardware follows the Vulkan-described behavior and applies the same texel offset to both mipmaps? Why would this be any more a subject to hardware differences than any other inter-mip sampling?

**Comment by pow2clk** [comment]
The documentation cited does not mention hardware differences. They aren't involved.

Not surprisingly, it does match the behavior of Vulkan.

The number of texels between two mip levels is different but the offset is the same because what else would it be? Most inter-mip sampling is done based on a 0.0-1.0 float value that translates to a percentage into the miplevel irrespective of specific dimensions so it doesn't run into this problem unless you provide an offset, which is in texels unlike the position which represents a percentage.

Is that clearer?

**Comment by pow2clk** [comment]
The hardware differences I mentioned in my comment are more to do with to what degree one miplevel gets blended with another and how an explicit offset exacerbates the difficulties of that. It is speculative. The meaning of the documentation is just what I said about the explicit offsets into differently sized images.

**Comment by pow2clk** [comment]
More specifically, imagine that you are using standard sample method with nearest (or point) mipmap filtering and you run it on hardware that never switches to the next miplevel down so your offset works perfectly and you think everything is peachy. 

Then you run it on hardware that uses different determinations to decide when to switch miplevels and this one does switch to the next level and suddenly your textures look like a stygian monstrosity, but only when you rotate it just right.

That's why it's a bad idea.

**Comment by kvark** [comment]
Thank you @pow2clk , that's clear now!
@grorg any information about how this behaves on Metal?

**Comment by grorg** [comment]
Discussed at the [2020-11-17 meeting](https://docs.google.com/document/d/1JMqCbDXyuEvjH8GalT8_bEJ9vfejMo4GMIsAVaXnKvI/edit#)

**Comment by jdashg** [comment]
Consensus is to support float-mip-with-integer-offset, and continue in the tradition of providing a warning against misusing this in our spec too.
