### ISSUE TITLE
Unable to use [SameObject] on "readonly attribute GPUError error"

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1225]
See the spec - https://heycam.github.io/webidl/#SameObject
`[SameObject]` is only valid on properties that are interfaces or objects. In our case, it's:
```
typedef (GPUOutOfMemoryError or GPUValidationError) GPUError;
```

**Comment by kainino0x** [comment]
In principle this ought to be allowed, and we want to keep [SameObject]. Technically we could make GPUError a base class but it doesn't make any sense as there's no shared functionality.

**Comment by kainino0x** [comment]
https://github.com/heycam/webidl/issues/71#issuecomment-169371603
Incidentally the original topic of this issue is Promises. We want that too: `[SameObject]` for `GPUCommandBuffer.executionTime` and `GPUDevice.lost`.

However apparently according to https://github.com/heycam/webidl/issues/212, `[SameObject]` is purely documentation and doesn't actually do anything, so we can just remove it for now.

**Comment by kvark** [comment]
Editor resolution:
  - remove `[SameObject]` here
  - file an issue to WebIDL
  - link to this issue from our spec

**Comment by kainino0x** [comment]
FYI I looked at ExtendableMessageEvent.source in mozilla-central and it kind of seems like Gecko is just out of spec wrt `[SameObject]`.
[ExtendableMessageEvent.webidl#34](https://searchfox.org/mozilla-central/rev/ff82c973f8ccb0475ec32439e9ec07014b3a681f/dom/webidl/ExtendableMessageEvent.webidl#34)
[ServiceWorkerEvents.cpp#1201](https://searchfox.org/mozilla-central/rev/ff82c973f8ccb0475ec32439e9ec07014b3a681f/dom/serviceworkers/ServiceWorkerEvents.cpp#1201)

**Comment by kainino0x** [comment]
Note this could be obsoleted by #1884 which could result in `GPUError` becoming a base class.
