### ISSUE TITLE
WGSL: Use `let` instead of `var`?

### ISSUE THREAD

**Issue by mrdoob** [gpuweb/gpuweb#1234]
Talking with @Kangz today I learnt that WGSL is using `var` and `const` for declaring variables and I thought the JavaScript ecosystem would find it confusing.

[`let` and `const` were introduced in JavaScript in 2015](http://www.ecma-international.org/ecma-262/6.0/#sec-let-and-const-declarations) and at this point most of the browsers support them. Over the last few years JavaScript developers have been moving their code from `var` everywhere to `let` and `const` to the point that when they see a `var` they think the code is old and/or unmaintained.

Would it be a good idea to align with JavaScript and use `let` and `const` too?

**Comment by Kangz** [comment]
+1, also I think in Javascript `var` doesn't have lexical scoping while `let` does. WGSL has lexical scoping so `let` would make that much clearer to Javascript developers.

**Comment by lachlansneff** [comment]
Why not go all the way and use `let` and `let mut`? :P

**Comment by kainino0x** [comment]
I suggested this a long time ago (due to the scoping similarity) but I don't remember the outcome of the discussion.

**Comment by dneto0** [comment]
Regardless of the name, `var` implies storage, and you can form a pointer to that storage.   `const` is a (mathematical) value only.
Some values can be in const that can't be in var.

I don't care that much about names, but would like the names to be short.

**Comment by kvark** [comment]
There is a different discussion to be made wrt the global variables versus locals. Globals are often uninitialized, and they don't have a scope, so `var` for them seems most appropriate (since in my mind `let` assumes initialization, even though JS doesn't require it).
For locals, `let` indeed could be nicer, but then there is a price of reducing consistency (between locals and global).

**Comment by frzi** [comment]
There's also Swift's `var/let` and Kotlin's `var/val` to take inspiration from. There are probably developers who appreciate the nice alignment of both keywords being 3 characters long.

FWIW I'm a proponent for WGSL using the Javascript-esque `let/const` as well.

**Comment by grorg** [comment]
Discussed at the [2020-12-01 meeting](https://docs.google.com/document/d/1BGljZlq1ZY1DTZS_MHxTxfu6rF0j87uUrPL7RHArpLA/). 

Resolution: stick with `var`

There was a lot of sympathy for the `let` proposal to match JS as the host language, but also confusion due to JS's `let` being different from most other languages. Since `var` is still valid JS, we figured that keeping that isn't a huge deviation from the host language.
