### ISSUE TITLE
spell out when an implementation must reject a shader module

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1241]
Many WGSL rules are statically checkable, i.e. by solely inspecting the WGSL source.

Do we want to spell out:
- The distinction between statically checkable vs. only checkable at runtime (if at all).  (Part of WGSL spec)
- That an implementation must check all statically checkable rules. My understanding is yes. (Part of WebGPU spec?)
- That when a statically checked rule fails, that the WebGPU createShaderModule call must fail:  by rejecting the promise on the GPUCompilationInfo and that the compilation info *should* contain an error message.

**Comment by kvark** [comment]
Heavily related to #974

**Comment by dneto0** [comment]
Another case popped up internally.

We intend to ensure array accesses are never allowed out of bounds.  What obligation is placed on the implementation to statically detect that this is the case and reject the shader:

        var x : array<i32,10>;
        x[0] = 1; // ok

        // This one is out of bounds. Implementation ensures something sensible, TBD (elsewhere).
        // But is the shader module rejected?  When?
        x[100] = 2; 

        var i : i32 = 100;
        x[i] = 3;  // what about now?  Statically reject?

**Comment by kvark** [comment]
That's an interesting case, @dneto0 !
In Naga, when taking a component of a composite type, we separate two types of accesses *statically*: 
  1. when the index is known at compile time
  2. when index is not known

By *statically* I mean that every kind of operation only goes to one of these, regardless of the exact index value:
  - struct member access is always (1): `mystruct.member`
  - matrix/vector access by letter is always (1): `myvec.y`
  - matrix/vector access by number is always (2): `myvec[1]`
  - array access is always (2): `myarray[x + 5]`

So it is natural to our implementation to error on `createShaderModule` if the (1) is failing. But all (2) are handled internally via out-of-bound checks, and they do not cause an error. I would suggest that the WGSL spec follows that rule, since otherwise we'd be stepping into a weird territory of trying to be "sufficiently smart" to reject something, i.e. handling expressions of constants, named variables, and other things.

**Comment by kainino0x** [comment]
I think WGSL should never error in this case (though it could warn). Except if it can be clearly detected that the index expression is a constexpr (e.g. if the grammar can tell, once it has constexprs), then an error would make sense.

**Comment by dneto0** [comment]
+1 to the comments above.
I'm not too worried about the details of when, and I can see refining in the face of a concrete const-expr rule).  

Mostly I would like agreement on the principle of classes of errors that cause rejection at specific stages.  Then we can put that concept in the spec, and tie specific rules (TBD) to which kind of error they incur.

**Comment by dneto0** [comment]
Discussed in [2021-02-09](https://docs.google.com/document/d/1gDaPdTVrZLht9PY4G3VADkaK3Cw2-OJUFzzNBFE2BvM/edit#heading=h.hp3f2zbslxr9)
