### ISSUE TITLE
First WebGPU Stable Release / Prognosis ?

### ISSUE THREAD

**Issue by enkicoma** [gpuweb/gpuweb#1276]
Hi there

I have a couple of questions, we are close to 2021 and back in 2018 we heard that WebGL is dead (will be soon). Well since 2015-2020 now WebGL is massively supported across mixed platforms: https://caniuse.com/webgl

Where WebGPU, isn't: https://caniuse.com/webgpu

My question will be when approximately WebGPU has in plan to go LIVE/the first release / supported by default on all major Browser Engines?

Any visibility will be much appreciated!

**Comment by kvark** [comment]
The next milestone is [MVP](https://github.com/gpuweb/gpuweb/issues?q=is%3Aopen+is%3Aissue+milestone%3AMVP), which is not a final API but one users can try out and give us feedback before we can settle on Version 1. Practically speaking, an API that's supported on all major browser engines by default may come around 2022.

**Comment by kainino0x** [comment]
> back in 2018 we heard that WebGL is dead (will be soon)

Importantly: WebGL is not dead. It only won't be receiving major new features such as compute shaders. Browsers will continue supporting it and making sure the quality and performance is reliable.

**Comment by jdashg** [comment]
WebGL is here to stay. We expect to support it forever, just as we still support Canvas2d.

An important caveat is that while WebGL 1 support is universal, and WebGL 2 support will be universal soon, WebGPU will not be universal for many years yet, even after release. It will continue to be a trade-off between functionality and availability, just like WebGL has (eventually) worked through.

**Comment by grorg** [comment]
Discussed at the [2020-12-07 meeting](https://docs.google.com/document/d/11VNsaOHObp5zmQ6E4DIZrQmYZdSJnwQ_JHhqEkYeFUg/edit).

**Comment by pjmlp** [comment]
Regarding WebGL's "death", it doesn't help that Khronos slides mention it is in maintenance mode and people should have a go at WebGPU.

https://www.khronos.org/assets/uploads/developers/library/2020-virtual-webgl-meetup/01%20WebGL%20WG%20Updates.pdf

There are similar slides regarding OpenGL vs Vulkan by the way.

**Comment by kainino0x** [comment]
"Maintenance mode" is exactly what we said above: WebGL 1 and 2 will continue to be supported for the foreseeable future, and will definitely continue to have significantly higher availability (especially WebGL 1) than WebGPU (which requires newer hardware and newer drivers). Maintenance mode (which we haven't even reached yet) **does not** constitute death or impending death. This is the web platform - removing existing technologies is difficult and very rarely done, and there's no reason to do remove WebGL (unlike Flash).

**Comment by v-fox** [comment]
Heh, I wouldn't be too [optimistic](https://github.com/immersive-web/webxr/issues/918#issuecomment-554467399), considering that Khronos has ended up [removing WebGPU support](https://github.com/KhronosGroup/SPIRV-Tools/projects/5#card-52774103) after years of fiddling about with it and there is [some kind of conflict of interests](https://github.com/gpuweb/gpuweb/issues/1475) between Khronos and "the Web community", both sides that are world-infamous for… questionable development decisions and practices. The major driving forces of Web are [Google](https://github.com/google/shaderc) & Mozilla, the latter being like a prosthesis-less one-legged cripple in a marathon race in relation to multimedia support, especially on Linux, and the former having quality control & basic practices [on par with Khronos](https://github.com/KhronosGroup/SPIRV-Tools/issues/3909).

That after GLES & WebGL have died down without going anywhere and gaining any interest for "normal users". Just like what happened with supposed replacements for [Flash](https://en.wikipedia.org/wiki/Adobe_Flash) (do we see any proliferation of multimedia-rich net-content of comparable quality and latency ? no, we do not). And just what happened with Khronos' [OpenCL](https://en.wikipedia.org/wiki/OpenCL) supposed nice & open replacement for Nvidia's proprietary scourge of CUDA (that similarly dominates in its industry) which [Intel now also tries to get replaced](https://en.wikipedia.org/wiki/OneAPI_(programming_model)), similarly, before the original has gone anywhere.

[We just can't have nice things in this world](https://www.google.com/search?q="That's+really+how+it+is+on+this+bitch+of+an+earth").

**Comment by kainino0x** [comment]
@v-fox this information is incorrect and your comparisons are unwarranted. Additionally, your attitude and language around Mozilla, WebGL, and this group's work violate our [code of conduct](https://www.w3.org/Consortium/cepc/).

WebGL is widely used, portable, well-maintained, and has a long future.

> Khronos has ended up [removing WebGPU support](https://github.com/KhronosGroup/SPIRV-Tools/projects/5#card-52774103)

That is simply a link to the SPIRV-Tools repository. WebGPU decided to use WGSL instead of SPIR-V, so the experimental work for a WebGPU target environment for SPIR-V became obsolete and was removed.

WebGPU is not a Khronos standard, and its success has nothing to do with Khronos. However, Khronos _is_ supportive of the effort.

> there is [some kind of conflict of interests](https://github.com/gpuweb/gpuweb/issues/1475) between Khronos and "the Web community",

We simply have different goals. Nothing in that issue or the linked issue is meant to imply a conflict of interest.

**Comment by jespertheend** [comment]
Keep up the great work everyone! Technology like this is super complex and you can't expect it to be finished within a few days.

**Comment by v-fox** [comment]
> this information is incorrect and your comparisons are unwarranted. Additionally, your attitude and language around Mozilla, WebGL, and this group's work violate our code of conduct.

@kainino0x Right, everything that goes against your agenda and/or marketing campaign is "a violation of CoC", very nice. Didn't take long for it to be used "as intended", as nothing increases productivity and clarity more than censorship and building echo-chambers. Good thing that I don't work for you or with you.

And should I even elaborate how a blanket statement of "this information is incorrect and your comparisons are unwarranted" (basically "It's my way, not yours, just cuz") is not an argument ? Although, I'm starting to think that comparison to Google Stadia or some other famous vaporware might have been more apt.

I'm only here because I've decided to investigate that SPIR-V announcement after being baffled by seeing it in the update changelog and not seeing WebGPU even starting to roll out after all the repeated hubbub. Your words and attitude do not inspire confidence.

> We simply have different goals. Nothing in that issue or the linked issue is meant to imply a conflict of interest.

Goals are interests and they are conflicting by [your own reasoning](https://kvark.github.io/webgpu-debate/SPIR-V.html) against using popular de facto standards. Using nicer euphemisms and wishful thinking doesn't change facts.

> WebGL is widely used, portable, well-maintained, and has a long future.

Is it now ? A thing that newer got outside of playground projects ? You could remove WebGL from Chrome & Firefox right now and >99% of users on the planet would not even notice. That's after 10 years of supposed development. 

> That is simply a link to the SPIRV-Tools repository. WebGPU decided to use WGSL instead of SPIR-V, so the experimental work for a WebGPU target environment for SPIR-V became obsolete and was removed.
> WebGPU is not a Khronos standard, and its success has nothing to do with Khronos. However, Khronos is supportive of the effort.

Which is why I've mentioned conflict of interest between Khronos and whoever is behind WebGPU. Because to have actual proliferation the standards needs to be practical and decrease unnecessary hassle for most developers, especially those who could use it to make something beneficial for most users.

With all of its problems, Khronos still makes the only 3D rendering standards with world-wide proliferation. Maybe you can count Microsoft & Sony and their proprietary console APIs as its competitors. Either way, that means that pretty much all developers connected to 3D rendering learn and operate on Khronos' standards. Meaning that if you're going to deviate then you better have really-really good reason that most developers on the planet would agree on.

If WebGPU is going the same way as WebGL then neither users nor developers, that hope to bring rich multimedia back into Web past the death of Flash, have anything to look forward to. Not anytime soon, not in 5-to-10 years from now - that is my point. Not unless you would replace marketing speeches and internal justifications with enticing practical tools.

**Comment by kainino0x** [comment]
We will not engage in discussion with you if you will not engage respectfully with us.
