### ISSUE TITLE
Define WebGPURenderingContext contextType DomString

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#131]
It is not clear to me what is the DOMString value for WebGPU contextType. As we've renamed namespace `webgpu` to `gpu` in the IDL file, I was wondering if we could simply have `gpu` as well for contextType:

```js
const gpuContext = canvas.getContext('gpu');
```

**Comment by kvark** [comment]
`webgpu` would be more consistent with `webgl`. I wonder if there is another precedent in similarly queried web APIs.

**Comment by beaufortfrancois** [comment]
Exhaustive list below (from Chromium) shows that only WebGL has the `web` prefix. I would be in favor of removing for `gpu`:

- `canvas.getContext('2d')`
- `canvas.getContext('experimental-webgl')`
- `canvas.getContext('webgl')`
- `canvas.getContext('webgl2')`
- `canvas.getContext('webgl2-compute')`
- `canvas.getContext('bitmaprenderer')`
- `canvas.getContext('xrpresent')` - **WebXR** Device API

**Comment by kvark** [comment]
I don't think `2d` and `bitmaprenderer` are representative here, since there are no `Web2D` and `WebBitmapRenderer` APIs, AFAIK. But the `xrpresent` case is interesting. I wonder if they have traces of discussion about how this decision was made, and if it's final.

**Comment by othermaciej** [comment]
I think it should be `'webgpu'` or `'web-gpu'` if you want to emphasize it being two words. Just `'gpu'` is not very distinctive, because it is a generic term, not the name of a specific technology. It raises the question, "isn't every type of context a GPU context?"

**Comment by Kangz** [comment]
@Toji on `xrpresent`

> No real specific reasons. Web felt redundant in this case, and it seemed like our usage was closer to the bitmaprenderer, which was not "web" prefixed.
> We also wanted a name that didn't suggest that it was the context used to do the rendering, and it seemed like "WebXR" or "xr" might imply that, which is why "present" got appended.
> That said the name is still open to bikeshedding

**Comment by kainino0x** [comment]
@othermaciej I think that's also an equally good argument to have `window.webgpu` instead of `window.gpu`. I do think they should match, but I am honestly fine with either option.

re: toji: I'm also fine with something like `window.webgpu`+`webgpuswapchain` or `window.gpu`+`gpuswapchain`

**Comment by Kangz** [comment]
Or just like WebXR we could go with `gpupresent`.

**Comment by beaufortfrancois** [comment]
FWIW, I'm fine with either `gpu`, `gpupresent` or `gpuswapchain`.

**Comment by kvark** [comment]
I'm leaning towards `gpupresent` to follow `WebXR` steps. After all, there are many uses of WebGPU without a swapchain, so it's not a rendering context. Having "present" there stresses on the particular aspect/capability it provides to the API.

**Comment by RafaelCintron** [comment]
I am fine with `gpupresent` or `gpuswapchain`.  Unlike WebGL, WebGPU begins its life outside of the canvas element.  As @kvark says, swap chains are just one aspect of the API.

**Comment by Kangz** [comment]
Alright, let's go with `gpupresent` for consistency with WebXR.

**Comment by beaufortfrancois** [comment]
FYI @JusSn, you may want to use `gpupresent` in Safari.

**Comment by jdashg** [comment]
`gpu-present` is better than `gpupresent`

**Comment by jdashg** [comment]
(we did `experimental-webgl` not `experimentalwebgl`)

**Comment by kainino0x** [comment]
I think we picked it for consistency with xrpresent and bitmaprenderer. Similarly with the IDL enums in the API.

**Comment by othermaciej** [comment]
"xrpresent" does not exists in [the latest WebXR draft](https://immersive-web.github.io/webxr/#contextcompatibility). XR does not appear to have a canvas context type at all any more. So being consistent with it is no longer a sound reason to use "gpupresent".

**Comment by othermaciej** [comment]
Reopening because:
- This was never reflected in the spec draft, issues probably shouldn't be closed until an appropriate PR to the spec lands.
- Not clear if this was ever a real CG decision.
- The original lease for using "gpupresent" is no longer valid as cited in the above comment.

I think at least the first point is a valid reason to have this still open, but perhaps this gives us the opportunity to reconsider.

**Comment by kainino0x** [comment]
Thanks for reopening. I had a brief conversation with someone about this recently (was it @toji?). I'm still very much in favor of "gpupresent" as it is a very descriptive and precise identifier for the context type. ("webgpu" or "gpu" would be confusing since the context type is only for presentation unlike the others.)

**Comment by othermaciej** [comment]
It's true that this context does not hold the actual graphics API, as in some other cases. It doesn't seem necessary or helpful to point this out in the context name. The value of the names is to distinguish context from each other, not to be descriptive and precise. "2d" isn't named "sortoflikecoregraphics". "gpu" or "webgpu" is enough to identify the context intended, since there won't ever be a second gpu-named context to distinguish from. And it on't be confusing to anyone who read docs. Anyone who didn't read docs won't he helped in using the API by the "present" in the name

That said, if it is necessary to highlight the lack of drawing operations, we don't have to use run-together words in a strange order, since the precedent that led to that is gone. Might be better to use something like "gpu-present" or "present-gpu" or "gpu-swap-chain".

(I still think the plainer names are best, and the current name isn't the worst possible, but it was chosen partly based on an obsolete precedent.)

**Comment by jdashg** [comment]
Weak vote from me for 'gpu-present' or 'gpu-swap-chain'.

**Comment by toji** [comment]
It's true that WebXR is no longer using a context ID in the shipping spec. We may add one back again in the future, but naming is flexible. For what it's worth "xrpresent" was previously selected without a dash to try and follow precedent set by "bitmaprenderer", which is still alive and well.

It is worth noting that platform conventions indicate that enums should be hyphenated. While this particular value isn't a proper enum it seems that's largely due to WebIDL technicalities, and it's actual use is very enum-like.

**Comment by kainino0x** [comment]
fwiw, the run-on casing also matches the case rules for event names in html. I don't know how canvas contexts ought to be cased, but I think we should just stick with it since we have "bitmaprenderer".

-1 for 'gpu-swap-chain' because it does not return a GPUSwapChain object, but rather a GPUCanvasContext which can create a GPUSwapChain (multiple times).

**Comment by jdashg** [comment]
That's fair. 'gpu' or 'gpu-present' from me.

**Comment by toji** [comment]
Put up a PR to the HTML spec to discuss this issue further: https://github.com/whatwg/html/pull/6804

**Comment by domenic** [comment]
Coming from https://github.com/whatwg/html/pull/6804 and trying to put my HTML editor hat on:

- I think trying to add dashes like other enums is a lost cause here due to `bitmaprenderer`, so I'd prefer `smooshedtogetherwords` instead of `lots-o-dashes`. Of course we can sidestep this question if we come up with a single-word version like `gpu` or (arguably) `webgpu`.

- I don't understand what "present" means and why people like the idea of putting it after some names. Is there some sense in which WebGPU "presents" things but 2D canvas and Web GL do not? (Similarly, in retrospect `bitmaprenderer` instead of `bitmap` feels a bit strange. But at least there I understand that we're rendering something; is there some sense in which Web GPU "presents" things instead of "rendering" them?)

- On `webgpu` vs. `gpu`, I'm not sure. `webgpu` aligns better with the `webgl` and `webgl2` precedent. But I see that maybe WebGPU is a marketing name that doesn't actually show up in the APIs, so maybe that's different from WebGL where there's a bunch of WebGLX classes floating around. I'm not sure whether developers are better served by these strings matching the marketing name they might've heard about, or better served by them matching the class names and other API entry points.

**Comment by toji** [comment]
I hinted at the reasoning behind the current name in https://github.com/whatwg/html/pull/6804 but I'l try to dive a bit deeper here.

I think the only reason we would want to avoid `"webgpu"` or `"gpu"` is to prevent confusion that the canvas context is the primary WebGPU interface (as is the case with WebGL), or that using WebGPU in any capacity requires a context from a canvas (you may be using the API only for compute).  That said, there is some support for it voiced above . As @othermaciej said in a previous comment:
> "gpu" or "webgpu" is enough to identify the context intended, since there won't ever be a second gpu-named context to distinguish from. And it won't be confusing to anyone who read docs.

Regarding the use of "present", there's an unfortunate overloading of terms at play here that we're trying to sidestep. "Rendering" could mean several different things. In the case of `"bitmaprenderer"` it refers to drawing the image to the page, which is typically what you would think of when talking about "rendering" an HTML element. In the case of a GPU API, however, we tend to think of "rendering" as the processing of commands to produce a rasterized image.  Because of this a name of `"gpurenderer"` may suggest that this context is this interface that "rendering" commands (in the 3D content sense) are issued through, when for WebGPU that's handled elsewhere. 

In equivalent native APIs displaying a rasterized image on the screen is done with a call such as [IDXGISwapChain::Present()](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgiswapchain-present) or [MTLDrawable present()](https://developer.apple.com/documentation/metal/mtldrawable/1470284-present), which is where I believe the term was pulled from when we originally used it in the WebXR spec. (That usage was eventually dropped and WebXR no longer has a unique canvas context.) The name `"gpupresent"` was intended to evoke the same concept: that this context is the mechanism that "presents" the rasterized content produced by the API to the page.

In the end I personally am mostly interested in conforming to web platform conventions where it makes sense, and helping define those conventions where they currently are absent or loosely defined. Given the small number of context types and diversity of context names, this has felt like the latter case so far.

**Comment by metaeaux** [comment]
The concept first evoked when I read "gpupresent" was not "present" meaning "exhibit" but present meaning "exists". This seemed odd, which is why I've found this thread. In my opinion, "swapchain" is less ambiguous than "present".

**Comment by toji** [comment]
> not "present" meaning "exhibit" but present meaning "exists".

Ah! I hadn't considered that reading of it. Thanks for bringing that up.

The term "swapchain" has been suggested a few times in the past, and I'm personally in favor of using it here, but I know other members of the group would prefer to avoid it because this context doesn't strictly match the native definition of a swap chain (as in: a fixed-length, rotating list of textures) and for various reasons is unlikely to ever be backed by one of the native swap chain objects.

**Comment by metaeaux** [comment]
> this context doesn't strictly match the native definition of a swap chain (as in: a fixed-length, rotating list of textures) and for various reasons is unlikely to ever be backed by one of the native swap chain objects.

That makes sense. I think `.getContext("gpupresentation")` be unambiguous and have a direct relationship to returning a [GPUPresentationContext](https://gpuweb.github.io/gpuweb/#presentation-context).

**Comment by Kaiido** [comment]
Also coming from whatwg/html#6804, with just a web-dev hat on.

Fast-reading about the [GPUPresentationContext](https://gpuweb.github.io/gpuweb/#presentation-context), it seems its lone purpose it to render a GPUTexture to a canvas (btw the specs currently states HTMLCanvasElement, but in [html](https://github.com/whatwg/html/pull/6804) it says it could also be an OffscreenCanvas).

Is this reading correct? In that case, wouldn't a name like `"gputexture"` or `"gputexturerenderer"` to make it more consistent with `"bitmaprenderer"` be more appropriate?  

The first time I read `"gpupresent"` I also completely missed the  *presentation* sense and I was more into the time sense... 

I also have a bit of trouble with "presentation" over "rendering", since as has been said elsewhere, the output canvas may not be presented to the screen (sounds even more weird for me when it's called from an OffscreenCanvas).

**Comment by kainino0x** [comment]
> the output canvas may not be presented to the screen

I've had this thought about the name `GPUPresentationContext`, as well possibly about `compositingAlphaMode` depending on whether it ends up affecting only presentation (#1847). Perhaps something slightly more generic is in order, like "output". `gpuoutput`/`webgpuoutput`...? Just a thought.

**Comment by kainino0x** [comment]
meeting: @toji and I are leaning toward `"webgpu"`. There isn't really a great need for it to be more specific than that, but `"gpu"` by itself sounds way too generic - we primarily use `GPU` to qualify identifier names (like GPUDevice), not by itself (except it `navigator.gpu`).

**Comment by kvark** [comment]
Didn't we have an action item to ask HTML WG about the choice of the context type here?

**Comment by toji** [comment]
Yes, which was done in the form of a PR: https://github.com/whatwg/html/pull/6804

**Comment by kainino0x** [comment]
Discussed and @kvark was also happy with `"webgpu"`
