### ISSUE TITLE
does textureSampleCompare assume level-of-detail 0 in non-fragment shaders?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1319]
In Vulkan SPIR-V, sampling operations in shaders other than fragment shaders must provide an explicit level-of-detail.

For example, a compute shader that does a depth-compare would have to provide an explicit Lod.

I presume that we intend level-of-detail 0 to be used.

That's what happens when compiling GLSL to SPIR-V.
For this input:
```
#version 450
layout(set = 0, binding = 0) uniform samplerShadow samp;
layout(set = 0, binding = 1) uniform texture2D tex;
layout(set = 0, binding = 2) uniform Uniforms {
    float compareRef;
};
layout(set = 0, binding = 3) writeonly buffer SamplerResult {
    float samplerResult;
};

void main() {
    samplerResult = texture(sampler2DShadow(tex, samp), vec3(0.5, 0.5, compareRef));
}
```
We produce a sampling instruction with explicit level-of-detail 0.

```
         %33 = OpImageSampleDrefExplicitLod %float %21 %30 %31 Lod %float_0
```

**Comment by dneto0** [comment]
From the MSL manual:

> The texture sample and sample_compare functions that do not take an explicit LOD or
gradients have a default LOD of 0. The gather and gather_compare functions called from
kernel or vertex functions also have a default LOD of 0.

Also:
> On macOS, for sample_compare functions, bias and gradient* are not supported, and lod
must be a zero constant.

So I think my assumption is correct.

I think WGSL should say it's using Lod 0.

**Comment by dneto0** [comment]
Think about this more, I think there is a subtle difference between MSL/Metal and SPIR-V/Vulkan.

In MSL/Metal, quoted above:

> The texture sample and sample_compare functions that do not take an explicit LOD or
gradients have a default LOD of 0. The gather and gather_compare functions called from
kernel or vertex functions also have a default LOD of 0.

In SPIR-V / Vulkan [16.1 Image Operations Overview](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_image_operations_overview)

> * Instructions with ImplicitLod in the name determine the LOD used in the sampling operation based on the coordinates used in neighboring fragments.

> * Instructions with ExplicitLod in the name determine the LOD used in the sampling operation based on additional coordinates.

In a fragment shader, if I write the depth compare GLSL expression:  `  texture(sampler2DShadow(tex, samp), vec3(0.5, 0.5, compareRef))`
then I get SPIR-V instruction:

 > %result = OpImageSampleDrefImplicitLod %float %21 %30 %31

That is, the level of detail is computed from the implicit derivative with neighbouring fragments.

In non-fragment shaders I get something like:

>   %33 = OpImageSampleDrefExplicitLod %float %21 %30 %31 Lod %float_0

So it uses level-of-detail 0.



With the PR #1320 as it is today, we're forcing depth compares to always use level-of-detail 0.  

I'm concerned that in future we'll add functionality to use the implicit derivative in the fragment shader, but would have already used up the good name for it, i.e. `textureSampleCompare`.  That would be the good name because it would be consistent with the textureSample which does use implicitly computed level of detail.

**Comment by kvark** [comment]
Good point to raise!
Interestingly, this problem also affects regular sampling from "depth" textures (not just comparison sampling).
We now have a slight of a problem that sampling depth textures doesn't work the same way as for regular textures, and that's subtle. Although, it may be less of a problem if WebGPU host API disallows mipmaps on depth (I don't recall if it does).

**Comment by jdashg** [comment]
I think forcing writing explicit lod of 0 is best for readability and forward compat.

**Comment by dneto0** [comment]
> I think forcing writing explicit lod of 0 is best for readability and forward compat.

Mechanically I think the compiler needs to *know* that it's a 0.  We could require a literal zero (easiest), or a constexpr 0 (once we define what that is.)

**Comment by ben-clayton** [comment]
> I'm concerned that in future we'll add functionality to use the implicit derivative in the fragment shader, but would have already used up the good name for it, i.e. textureSampleCompare

As I've mentioned on other issues - I'd like us to reconsider adding `Level` suffixes to *all* built-ins that take a level parameter. This would keep consistency with `textureSampleLevel` and avoids overload collisions with future parameters.

**Comment by kvark** [comment]
> As I've mentioned on other issues - I'd like us to reconsider adding Level suffixes to all built-ins that take a level parameter. This would keep consistency with `textureSampleLevel `and avoids overload collisions with future parameters.

This is a bit tangential to the problem. Regardless of whether we have `XxxLevel` or `Xxx(..., level)`, it's still a different command from the possible implicit-derivative version of the function.

I think the ergonomic cost here is not that high. Adding `, 0` for comparison sampling would have a minor impact on a few people. But it would allow the spec to be more consistent, and us to grow the spec if needed.

**Comment by ben-clayton** [comment]
> I think the ergonomic cost here is not that high. Adding , 0 for comparison sampling would have a minor impact on a few people. But it would allow the spec to be more consistent, and us to grow the spec if needed.

I agree, and in this case I'm not against requiring an explicit level to be passed. I'm simply suggesting that if we're going to add a mandatory level parameter, we should add the `Level` suffix to the function name.

That way, we'd be consistent, reduce overload collisions, and if one day we do support an implicit LOD version, we can call that `textureSampleCompare()`.
With different names it would be a lot simpler / clearer to say that `textureSampleCompare()` can only be used in fragment shaders, and `textureSampleCompareLevel()` is only permitted in non-fragment shaders, than bundling the two together in a pool of overloads and trying to describe which can be used by what stage.

**Comment by ben-clayton** [comment]
> Mechanically I think the compiler needs to know that it's a 0. We could require a literal zero (easiest), or a constexpr 0 (once we define what that is.)

I suspect we're going to have to do robustness bounds checking for the `level` parameter of `textureSampleLevel()`. Wouldn't this follow the same sanitisation logic?

**Comment by dneto0** [comment]
I think the summary is:

- change textureSampleCompare to textureSampleCompareLevel, and it always takes a level parameter which must be 0 (however constrained syntactically)

**Comment by ben-clayton** [comment]
This would be my preferred resolution here.

**Comment by pow2clk** [comment]
This might be more consistent, but a parameter that can only be one value requires more typing from the user and inviting errors. 

Support for a non-zero LOD would require a new version of HLSL for that support. That might push out the practicality of allowing a non-zero value for a while.

**Comment by kvark** [comment]
Right, `textureSampleCompareLevel` is definitely more clear and future-compatible, but it's way too far from where we are now...
I still like the original proposal by @dneto0 to specify the `textureSampleCompare` as taking the LOD=0 always. Then, once we get to implicit LOD, or explicit LOD, we'd have to make it an extension, and we'll introduce either additional functions, or additional overloads.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-01-26-Minutes#does-texturesamplecompare-assume-level-of-detail-0-in-non-fragment-shaders--issue-1319--gpuwebgpuweb">WGSL meeting minutes 2021-01-26</a></summary>


* DM: Why only about compare. Regular texture simple can’t do other mipmaps outside frag shaders.
* MM: So options are not having an arg and assuming 0 or having an argument and making the programmer type 0. Validation rules would say in a non-frag shader it has to be 0. Possibly as a constexpr?
* DN: I think that’s what I understand
* MM: Think we’re going to need the second one, regardless of if we have the first. Should have a function that takes an argument. Reason is we have these shader modules with entry points and helper functions, legit for someone to want the same sample call inside a helper and call that helper from 2 different entry points. Another question, should we also have an overload that doesn’t take this argument. The overload would work in both frag and non-frag shaders. For frag shaders it would be level = 0.
* JG: That’s what I don’t want. Want it obvious where it won't happen. In cases where the SPIR-V compiler takes GLSL and you said texture but we’re going to set level == 0, and would be nicer if that was explicit.
* DM: Have machinery with derivatives to fill out the level. Machinery shouldn't be randomly used. Function doesn't need to be ImplicitLOD like SPIR-V, but we need the params clear that it’s an implicitLOD instead of being magical.
* JG: Prefer explicit first
* BC: Problem is texture sample, most common case is implicit. Texture sample compare most commonly is explicit. Either pattern will feel clunky on one side.
* JG: Good point.
* DM: Does it matter if we just call texture implicit. If common to call from the frag shader like that?
* GR: Not a lot of support for derivatives in compute shaders.
* JG: Will come back next week. Wil try to make a concrete proposal to talk about next call.
</details>

**Comment by dneto0** [comment]
I'm revisiting this for other reasons.

Reading the MSL docs, it appears that there is no way to do a `sample` operation using the implicit derivative to choose the level of detail.

Reasoning is that, again from p156:

> The texture sample and sample_compare functions that do not take an explicit LOD or
gradients have a default LOD of 0. 

That statement is not qualified by what shader stage is being executed.  And there seems to be _no other way to sample with the implicitly computed derivative_.  But that's the most basic fundamental sampling operation in fragment shaders.

I suspect this is a documentation bug.  And now I doubt a lot of the above reasoning.

Hey @litherum please raise this with the Metal team.

**Comment by kvark** [comment]
@dneto0 I'm not sure I understand. This quote you posted was one of the starting point of this very discussion (see [comment](https://github.com/gpuweb/gpuweb/issues/1319#issuecomment-747769599)).
What has changed since then? Are you asking Apple if this is really the semantics MSL exposes?

**Comment by dneto0** [comment]
Yes, I'm asking Apple if this is really the semantics MSL exposes.

I think that instead, when no level of detail is provided, that in fragment shaders a level of detail is computed from the implicit derivative of the fragment and 3 of its neighbours.

Basically, that matches GLSL.

An experiment with GLSL -> SPIR-V (via Glslang) -> MSL (via SPIRV-Cross) bears this out.

```
$ cat dr.frag
#version 450

layout(set=0, binding=0) uniform texture2D t;
layout(set=0, binding=1) uniform sampler s;
layout(location=0) in vec2 coords;
layout(location=0) out vec4 o;

void main() {
  o = texture(sampler2D(t,s), coords);
}

$ glslc dr.frag -o dr.spv

$ spirv-dis dr.spv |grep Sample
         %14 = OpTypeSampler
         %18 = OpTypeSampledImage %10
         %19 = OpSampledImage %18 %13 %17
         %24 = OpImageSampleImplicitLod %v4float %19 %23

$ spirv-cross --msl dr.spv
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 o [[color(0)]];
};

struct main0_in
{
    float2 coords [[user(locn0)]];
};

fragment main0_out main0(main0_in in [[stage_in]], texture2d<float> t [[texture(0)]], sampler s [[sampler(0)]])
{
    main0_out out = {};
    out.o = t.sample(s, in.coords);
    return out;
}
```

A lot of real things use spirv-cross on Mac.   I very much think this is a documentation bug.

**Comment by kvark** [comment]
So this is a bug in the general documentation for sampling. I thought we were talking about depth textures specifically, not all the textures.

**Comment by dneto0** [comment]
I'll pull together the pieces more explicitly here.  I'm referencing the MSL 2.3 spec.  https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf 


In " 6.10 Texture functions"  it says (p 156.):

>  The texture `sample` and `sample_compare` functions that do not take an explicit LOD or
gradients have a default LOD of 0.

That's not qualified in any way.

I would have expected that when sampling from a mipmap texture:

- When used in a fragment shader, a `sample` overload without a LOD option will use the implicitly computed local derivative to determine the LOD.
- When used in a different stage (e.g. vertex, kernel), a `sample` overload without LOD option will use an effective LOD of 0.

That would match GLSL. It's the default behaviour usually want to have because it tends to save memory bandwidth because it localizes fetches, and the higher mip levels may yield a more visually pleasing result.

The way it's documented right now is certainly internally consistent, but surprising.

**Comment by litherum** [comment]
When using the sample or sample_compare, there is a required sampler argument. When creating a sampler, there are 2 ways of doing it:
1. A MTLSamplerDescriptor from the API: One of the fields in MTLSamplerDescriptor is [`mipFilter`](https://developer.apple.com/documentation/metal/mtlsamplerdescriptor/1515553-mipfilter) which indicates how different mipmaps are selected inside sampling operations. The default value for this field is [`notMipmapped`](https://developer.apple.com/documentation/metal/mtlsamplermipfilter/notmipmapped) which means "The texture is sampled from mipmap level 0, and other mipmap levels are ignored.”
2. As a literal within the source code. In section 2.9 on page 35 of the same spec you link to, it describes how `none` is the default value of the `mip_filter` field in the sampler.

This is the sense the spec uses when it says “default LOD of 0:” the default sampler configuration will ignore all but the 0th mipmap by default.

If you set the mipFilter field of the sampler to “nearest” or “linear” then the thing you would expect to happen happens. (And I also wrote a test program to verify this.)

**Comment by kvark** [comment]
@litherum thank you for the clarification! The situation with depth textures is still unclear to me. The spec says that LOD and BIAS versions of `sample_compare` functions don't exist on macOS. Does this mean `sample_compare` has to always choose the implicit LOD based on the derivatives?

**Comment by litherum** [comment]
My guess is that this line in the documentation is stale, because the header has

```C++
class depth2d ... {
}

**Comment by litherum** [comment]
<rdar://problem/74436824> is for tracking the documentation update.

**Comment by dneto0** [comment]
Thanks for the update (and patience for my reply).

* I guess I can summarize my confusion in that the "defaulting" is about the sampler state, rather than defaulting occuring because the builtin lacks parameters that would otherwise determine the level-of-detail.
* I assume we want WebGPU to cover Intel macs.  So is there a suggestion that we should remove textureSampleLevel and textureSampleBias ?  I guess I'm now confused about the support matrix.  Also, we need to keep in mind fragment shader vs. not-fragment-shader (because of the presence or lack of implicit derivatives)

**Comment by litherum** [comment]
Here's the story on Metal:

These are the axes:

- The set of texture sampling functions. The set that’s listed in the WGSL spec is:
  - Regular normal sample
  - Sample with bias
  - Sample with compare
  - Sample with gradient
  - Sample with level
- The set of texture types. The set that’s listed in the WGSL spec is:
  - 1D texture
  - 2D texture
  - 2D texture array
  - 3D texture
  - Cube texture
  - Cube texture array
  - 2D multisampled texture
  - 1D storage texture
  - 2D storage texture
  - 2D storage texture array
  - 3D storage texture
  - 2D depth texture
  - 2D depth texture array
  - 2D depth cube texture
  - 2D depth cube texture array
- The set of shader types. The set for WGSL is:
  - Vertex shader
  - Fragment shader
  - Compute shader
- The set of machines / GPUs.

Luckily, the only thing that is machine specific is a configuration that is not present above (Sample with both compare and bias/gradient/level). So, the last axis isn’t relevant.

Since we’re only interested in sampling, the storage textures are not relevant.

Multisampled textures don’t support sampling in Metal.

1D textures don’t have mipmaps in Metal. So the only sampling operation that works on them is the regular normal sample.

Sample with compare is only valid on depth textures.

Inside a vertex shader or a compute shader, regular normal sample and sample with compare use mipmap 0, and sample with bias applies the bias to 0 (so bias(1) will give you the 1th mipmap). Sampling with gradient or level works naturally.

So, the chart looks like this, where ✅ means “works in all shader stages” and ❌ means “doesn’t work”:

  | Regular normal sample | Bias | Gradient | Level | Compare
-- | -- | -- | -- | -- | --
1D | ✅ | ❌ | ❌ | ❌ | ❌
2D | ✅ | ✅ | ✅ | ✅ | ❌
2D Array | ✅ | ✅ | ✅ | ✅ | ❌
3D | ✅ | ✅ | ✅ | ✅ | ❌
Cube | ✅ | ✅ | ✅ | ✅ | ❌
Cube Array | ✅ | ✅ | ✅ | ✅ | ❌
2D Multisampled | ❌ | ❌ | ❌ | ❌ | ❌
1D Storage | ❌ | ❌ | ❌ | ❌ | ❌
2D Storage | ❌ | ❌ | ❌ | ❌ | ❌
2D Storage Array | ❌ | ❌ | ❌ | ❌ | ❌
3D Storage | ❌ | ❌ | ❌ | ❌ | ❌
2D Depth | ✅ | ✅ | ✅ | ✅ | ✅
2D Depth Array | ✅ | ✅ | ✅ | ✅ | ✅
2D Depth Cube | ✅ | ✅ | ✅ | ✅ | ✅
2D Depth Cube Array | ✅ | ✅ | ✅ | ✅ | ✅

From the above analysis, you might notice that there’s no way to make sampleCompare read from the non-0th mipmap if you’re calling it from a compute/vertex shader. If authors want to sampleCompare from the non-0th mipmap in a compute/vertex shader, authors achieve this by either using the lodMinClamp field in the sampler, or by calling sampleCompare on a texture view which actually targets a non-0th mipmap of some other texture.

Hopefully all this can answer the questions definitively.

**Comment by dneto0** [comment]
Thanks very much. That's very clarifying.

WGSL limits textureSample and textureSampleBias to only fragment shaders.
So the MSL behaviour of defaulting-to-Lod-0 of for non-fragment shaders is not material to WGSL.

What remains is that textureSampleCompare is usable in fragment and non-fragment shaders.
But it behaves differently for the two contexts, even when spelled the same. That's problematic, particularly when the operation occurs in a helper function.

For distinct behaviour we should have distinct spellings.

A perfectly clear but maybe ugly thing to do is:
- textureSampleCompare:  uses an implicit derivative to compute level-of-detail, and is only usable in fragment shader
- textureSampleCompareLevel0 : uses level-of-detail 0, and usable in any stage.

In other contexts we've discussed enforcing certain parameters to be compile time constants, but if I recall correctly those were cases where more than one value was permitted.  This is different.  But I'm open to suggestions.

**Comment by kainino0x** [comment]
In case depth textures get mipmapping (not sure how unlikely this is), maybe it would be best to use `textureSampleCompareLevel` with an implicit level 0, rather than `textureSampleCompareLevel0`. It could be overloaded later with a version that takes a level.

There would be precedent in `textureSampleLevel(t : texture_external, s : sampler, coords : vec2<f32>) -> vec4<f32>` (also non-mipmappable). Although we could also call that `textureSampleLevel0` to match.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-05-11-Minutes#does-texturesamplecompare-assume-level-of-detail-0-in-non-fragment-shaders--issue-1319--gpuwebgpuweb">WGSL meeting minutes 2021-05-11</a></summary>



*   DN: Thanks Myles for the summary. Comparison textures can be sampled in vert and frag, but they have different behaviors, which is worrisome when the builtin is spelled the same. Would be nice to have a different builtin for the different behaviors
*   TR: +1
*   JG: +1
*   DM: Final proposal is `textureCompareLevel` (uses level 0)
*   AB: Add restriction `textureSampleCompare` to be frag-only
*   TR: So then could we add a param later? (yes) So we support that style of overloading (yes, for builtins)
*   DN: I volunteered to write the PR


</details>
