### ISSUE TITLE
Missing limits in GPULimits

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1343]
WebGPU has a small amount of limits defined in the spec and we should add a LOT more to be complete. As a first pass I took a look at the `VkPhysicalDeviceLimits` Vulkan limits descriptor to see what we're obviously missing. After filtering for limits WebGPU already has, or that are inapplicable, we have the following missing limits. (all member names below are the name of members in `VkPhysicalDeviceLimits`)

- [ ] Additional binding model limits
  - [ ] per-`GPUBindGroupLayout` limits in the number of resources. We can decide that they are not applicable after looking at the guarantees in Vulkan. `maxDescriptorSetSamplers `, `maxDescriptorSetSamplers`, `maxDescriptorSetUniformBuffersDynamic`, `maxDescriptorSetStorageBuffers`, `maxDescriptorSetStorageBuffersDynamic`, `maxDescriptorSetSampledImages`, `maxDescriptorSetStorageImages`
  - [ ] per-stage limit on the number of resources: `maxPerStageResources`. We can decide it is not applicable.
- [x] `minUniformBufferOffsetAlignment`, `minStorageBufferOffsetAlignment`
- [ ] Limits for fragment outputs / render targets
  - [ ] `maxFramebufferWidth`, `maxFramebufferHeight`. We can decide to not have it and use `maxTextureDimension2D` instead.
  - [ ] `maxColorAttachments` - currently hardcoded at 8, needs a limit
  - [ ] `framebufferColorSampleCounts`, `framebufferDepthSampleCounts`, `framebufferStencilSampleCounts`, `framebufferNoAttachmentsSampleCounts` depending on what we decide for multisampling limits.
  - [ ] `maxFragmentOutputAttachments`, `maxFragmentDualSrcAttachments`, `maxFragmentCombinedOutputResources` if we want to have them, or just use `maxColorAttachments` or not.
- [x] `maxVertexOutputComponents` and `maxFragmentInputComponents`
- [x] `maxComputeSharedMemorySize`, `maxComputeWorkGroupCount`, `maxComputeWorkGroupInvocations`, `maxComputeWorkGroupSize`
- [ ] `minTexelOffset`, `maxTexelOffset`, `minTexelGatherOffset`, `maxTexelGatherOffset` which define the valid range for the compile-time constant offset for some texture WGSL functions.
- [ ] `maxClipDistances`, `maxCullDistances`, `maxCombinedClipAndCullDistances` if we have the equivalent of `gl_ClipPlane` and friends in WGSL.
- [x] `maxVertexInputAttributeOffset` if it is not just `maxVertexInputBufferStride`
- [x] `maxDrawIndexedIndexValue` - [not needed](https://github.com/gpuweb/gpuweb/issues/1343#issuecomment-895571063)
- [x] `maxDrawIndirectCount`
- [ ] Information about the system if we want to expose it:
  - [ ] `subPixelPrecisionBits`, `subTexelPrecisionBits`, `viewportSubPixelBits`, `mipmapPrecisionBits`
  - [ ] `maxSamplerLodBias` that clamps the sum of the sampler's lod bias and the bias set in the shader.
  - [ ] `strictLines` which describes wether parallelogram lines or Bresenham lines are used.
  - [ ] `standardSampleLocations` which we might require in WebGPU.
- [ ] More multisampled limits depending one the multisample limits discussion
  - [ ] `sampledImageColorSampleCounts`, `sampledImageIntegerSampleCounts`, `sampledImageDepthSampleCounts`, `sampledImageStencilSampleCounts`, `storageImageSampleCounts`
  - [ ] `maxSampleMaskWords`

I think we also want a limit that's WebGPU-specific:

- [ ] `maxBufferTextureCopyRowPitchAlignment` that encodes the 256 constraint we have.

**Comment by kvark** [comment]
Spec editors discussion:
  - "per-GPUBindGroupLayout limits" - need more investigation. One possibility is to only have per-pipeline limits, and these are tighter.
  - "minUniformBufferOffsetAlignment, minStorageBufferOffsetAlignment" - worth looking into. The case is creating a million bindings off a buffer. If each binding is 16 bytes long, but you have to align it to 256, that's a lot of waste.
  - "maxFramebufferWidth, maxFramebufferHeight" - we shouldn't expose these
  - "maxColorAttachments" - needs to be exposed
  - "framebufferColorSampleCounts" - we discussed it a bit, and need to keep looking into it.
  - "maxFragmentOutputAttachments" - let's not bother with it, `maxColorAttachments` is good
  - "maxFragmentDualSrcAttachments"  - needs investigation
  - "maxFragmentCombinedOutputResources" - we'd require 12+ there today. Needs more investigation.
  - "maxVertexOutputComponents and maxFragmentInputComponents" - would be nice to expose a single "max varying locations" kind of limit covering these
  - to be continued

**Comment by kainino0x** [comment]
We also discussed the breaking nature of certain changes. Using a Vulkan backend as an example, if we started with:

- `maxTextureDimension2D` is vulkan `min(max framebuffer size, max 2d texture size)`

and then later decided we wanted to split them:

- `maxTextureDimension2D` is vulkan `max 2d texture size`
- `maxFramebufferSize` is vulkan `max framebuffer size`

Then this would be a breaking change. This is because any application requesting a higher `maxTextureDimension2D` would go from seeing that value for max framebuffer size, to seeing the default value.

So instead we would have to introduce TWO new limits, for a total of three:

- `maxTextureDimension2D` is vulkan `min(max framebuffer size, max 2d texture size)`
- `maxTextureDimension2DNonFramebuffer` is vulkan `max 2d texture size`
- `maxFramebufferSize` is vulkan `max framebuffer size`

OR we would have to introduce major versioning for the limits structures, e.g. by passing a version number into `requestAdapter`.

**Comment by jdashg** [comment]
I prefer versioning, because I think narrowing our set of limits is extremely valuable on multiple fronts.

**Comment by kvark** [comment]
Editors discussion: when adding limits, we need users consent before enforcing them. It can be obtained with either a new feature (that has to be enabled for the new limits to be enforced), or with this hypothetical limits version. Between these choices, the mechanism for features sounds more feasible, since it's already there.

**Comment by Kangz** [comment]
Bumping this issue, we should make progress on adding all the limits to WebGPU :)

**Comment by Kangz** [comment]
I think `maxComputeWorkGroupInvocations` is sufficient to take care of `maxComputeWorkGroupSize` by injecting a small prelude in the shader if the shape isn't something that's supported by the underlying Vulkan driver.

**Comment by kainino0x** [comment]
The maximum GPUQuerySet size (8192) should be upgraded from a hardcoded value to a (non-configurable) limit.
(There are probably other hardcoded items too.)

**Comment by kainino0x** [comment]
> * maxDrawIndexedIndexValue

Editors: are quite distressed by the existence of this limit 😅

**Comment by toji** [comment]
Editors are relieved to learn that `maxDrawIndexedIndexValue` may only be less than 2^32-1 on devices without the `fullDrawIndexUint32` feature, which appears to be a [very small number of Android devices](https://vulkan.gpuinfo.org/listdevicescoverage.php?feature=fullDrawIndexUint32&platform=android&option=not) that are already excluded from WebGPU support due to the same set of devices also lacking atomics. Therefore we can safely require `fullDrawIndexUint32` for WebGPU.

**Comment by Kangz** [comment]
Closing this. Looking at the list above we seem to have WebGPU equivalent of all Vulkan limits that could affect WebGPU. The only somewhat open question is how to spec the limits for sample counts, be we can figure that out later.
