### ISSUE TITLE
[wgsl]: textureDimensions() returns vec3 for cube textures 

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#1345]
Cube textures for all backends currently require each face to be a square (width == height).
As each cube face is square, all cube textures are guaranteed to be 'square' (width == height == depth).

The WGSL spec currently has the return type of `textureDimensions()` as a `vec3<i32>`, to describe the cube width, height and depth (due to the square requirement, all three components will always be equal).
All backend shader languages support querying a cube texture's dimensions, and return just width and height (again, always equal).

I just want to highlight this discrepancy and make sure that we're happy with this difference between WGSL and the other shader languages.

**Comment by kvark** [comment]
> All backend shader languages support querying a cube texture's dimensions, and return just width and height (again, always equal).

This is not exactly true:
  - SPIR-V does indeed return 2 dimesnons.
  - Metal has separate `get_width` and `get_height` methods
  - HLSL [doesn't seem to have](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texturecube) `GetDimensions` at all on the cube (!). Am I missing it? If not, we should consider not having this function for now.

**Comment by ben-clayton** [comment]
> HLSL doesn't seem to have GetDimensions at all on the cube (!). Am I missing it? If not, we should consider not having this function for now.

I think that's just broken docs. [It's listed here](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-getdimensions#overloaded-methods).

And DXC certainly implements it:
http://shader-playground.timjones.io/5b35fb56004323afbc8e0bb7c145a037

Note that adding a 3rd argument results in a compile failure.

**Comment by kvark** [comment]
ok, good. I tend to agree then that all the backend APIs treat the dimensions as 2D.
I think we should follow.

**Comment by ben-clayton** [comment]
I'm not massively opinionated here, but I'd lean towards keeping `vec3<i32>` (or switching to `i32`):

`vec2` for a 3-dimensional object is just odd. I understand that this probably stems from cubes being internally treated as a 6-element 2d-array, but if the dimensions must match, I'm unsure why the APIs don't use a single scalar.

If the original design decision for specifying width **and** height was for future non-square support, then wouldn't it make far more sense to have 3 dimensions, as a cuboid has 3 axes?

If there's never going to be hardware support for non-square cuboids, then `i32` seems a generally saner thing to return.

<sub>Also: I just spent most of today implementing this with `vec3` 😃 </sub>

**Comment by jdashg** [comment]
(Cube textures are `w == h && d == 6`, not `w == h == d`)

APIs don't use a single scalar probably because non-square cubes sort of sit on the "plausible if people wanted them" frontier.

Cube should not have higher dimensionality than texture_2d_array, which currently is vec2.

Is there a way to get the number of layers for a texture? I was definitely expecting textureDimensions(2d_array) -> vec3...

**Comment by jdashg** [comment]
Oh they're sort of cubes for sampling coordinates, is what you're saying? I definitely feel like vec2 is safest in this case, as scalar feels too clever/new to me, but I could survive it. cube -> vec3 is most ambiguous since I was expecting d == 6, though I see why w==h==d on the shader side.

**Comment by ben-clayton** [comment]
> APIs don't use a single scalar probably because non-square cubes sort of sit on the "plausible if people wanted them" frontier.

Cubes have three dimensions, and you can't build a cube out of 6 rectangles with identically shaped, but non-square rectangles. Two of those faces would have to be WxW or HxH in size.

> cube -> vec3 is most ambiguous since I was expecting d == 6

We've intentionally tried to keep array index out of coordinates. Sampling a `texture_2d_array` takes a vec2 for coordinate and a separate array index. 

> though I see why w==h==d on the shader side.

Right.
When sampling a cube, you pass in a 3d normalized vector to project on to one of the cube faces. In a hypothetical world of non-square cubemaps, it would follow that a you'd need scale that normalized coordinate with a vec3 dimension to get the unnormalized texel coordinate for a given face. 

> Is there a way to get the number of layers for a texture?

Yes - [`textureNumLayers()`](https://gpuweb.github.io/gpuweb/wgsl.html#texturenumlayers)

**Comment by dneto0** [comment]
Just now I hit this independently.
I think we should follow existing shader languages, and have textureDimensions() return vec2&lt;i32&gt;, being the w and h values.

**Comment by dneto0** [comment]
Discussed in [2021-05-18 meeting](https://docs.google.com/document/d/1A_NOHjqHGTQryVqZEPoIWJLSqBa_JVwhyutJJ9206aY/edit#heading=h.8q5g8xs729no)

Consensus:  change result type to vec3<i32>, meaning width x width

**Comment by ben-clayton** [comment]
> Discussed in [2021-05-18 meeting](https://docs.google.com/document/d/1A_NOHjqHGTQryVqZEPoIWJLSqBa_JVwhyutJJ9206aY/edit#heading=h.8q5g8xs729no)
> 
> Consensus: change result type to vec3, meaning width x width

You meant `vec2`, right?

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-05-18-Minutes#wgsl-texturedimensions-returns-vec3-for-cube-textures--issue-1345--gpuwebgpuweb">WGSL meeting minutes 2021-05-18</a></summary>



*   BC: Not strong feeling, but vec2 might be the worst of the possibilities, since w=h and 6 layers. It seems sort of optimistic to have separate width and height. I think we should either have it take a face id, or instead just return a scalar. However, that’s not what other APIs do.
*   JG: Why vec2 is a little bit nice. It’s forward compatible a little bit, at least more than a scalar.  If you swizzle out of vec2, the swizzle works.  But scaling up out of a scalar is not so compatible. Changing size of the vector would be breaking change (necessitating something different)
*   BC: Would be nice to take a face ID param to get select which face you’re getting the dimensions for.
*   BC: .. more ideas …  in the realm of very hypothetical here.
*   KN: If we had weirdo squashed cubes it would be a new type, not “cube”.
*   JG: I expected it to return width x width x 6.  But it’s actually width x width x width. Which is not obvious.
*   KN: Native apis return vec2 width x width. Should just follow.  … Hm. It’s not obvious. Cube_arrays
*   BC: we have separate call to return the array size. 
*   _Resolved: vec2, width x width_


</details>
