### ISSUE TITLE
Require storeOp when resolveTarget is specified?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1376]
Today, storeOp defaults to `"store"`. This is a clear default for cases when resolveTarget is not specified.

However, when resolveTarget is specified, it's very common that you want the storeOp to be `"clear"` (which discards the multisampled data, and only keeps the resolved data). Maybe we should make storeOp required when resolveTarget is specified?

**Comment by kainino0x** [comment]
Probably small enough to do in the editors meeting, but also small enough that we could have a 1 minute section about it in a meeting.

**Comment by kvark** [comment]
It's a bit unfortunate to have `storeOp == null` equivalent to `storeOp == "store"` tbh... I don't see a nice solution here.
Perhaps, it's a call to make `storeOp` simply required without a default? After all, the `clearOp` is required.

**Comment by kainino0x** [comment]
I'd be OK with that.

**Comment by jdashg** [comment]
@litherum might have thoughs here?

**Comment by litherum** [comment]
The option of "always unconditionally make `storeOp` required just in case the author wants to resolve something sometime" seems like too big a hammer. I like that less than having `storeOp == null` mean different things depending on whether `resolveTarget` is specified." However, having `storeOp == null` mean different things in different situations seems like it would be an arbitrary rule that programmers would just have to memorize for no good reason, so that's not great either.

Is there a third option of "make `storeOp` required, but only when `resolveTarget` is specified?" This would be better, I think. It would require handwritten modification to bindings code, which isn't terrible... and is probably worth it in this case...

**Comment by kainino0x** [comment]
> Is there a third option of "make `storeOp` required, but only when `resolveTarget` is specified?" This would be better, I think. It would require browser developers to make handwritten modifications to bindings code, which isn't _terrible_... and is probably worth it in this case...

That was the original proposal in this thread.

**Comment by kvark** [comment]
@litherum I could live with this.
My concern was that it's sort of an arbitrary line between the cases where we require the store op and the cases we don't. Having a resolve operation is not the only place where the user should strongly consider the "clear" operation. Other such case would be a render pass with one or more color attachments, and a depth attachment. In popular scenarios, like forward rendering, the depth is only needed within the render pass, and should be discarded at the end. So it seems more consistent (between the use cases, and also comparing to load op) and simpler to say that one always needs to specify this.

If we go the "required always" route, we can also at any point reconsider this and make it optional in some cases, but not the other way around. I.e. if we find out another performance pitfall after V1, we wouldn't be able to guide the users around it any more.

**Comment by kainino0x** [comment]
> If we go the "required always" route, we can also at any point reconsider this and make it optional in some cases, but not the other way around.

Always a winning argument for me.
