### ISSUE TITLE
Mechanism for opting into shading language extensions

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#1404]
In https://github.com/gpuweb/gpuweb/issues/600 it seems we've coalesced around the first line of the shader being something like `#version foobar` (like GLSL). Will we use a similar mechanism for opting into shading language extensions?

If the answer is "yes," that means that extensions will be per-shader-module. However, there might be appetite for enabling/disabling extensions on a per-entry-point level.

If extensions are per-entry-point, we'd have to figure out what happens when a vertex shader with one set of extensions gets linked to a fragment shader with a different set of extensions. (Maybe the answer to this is extension-specific?)

If extensions are per-entry-point, how will extensions modify "what it means to be an entry point," like a possible ray tracing extension?

**Comment by litherum** [comment]
Alternatively, these extensions could be enabled on the `GPUDevice` API object, or as arguments to `createShaderModule()`.

**Comment by kvark** [comment]
The use case I'm thinking about when we talk about extensions is this:
```rust
[[block]]
struct UniformStruct {
  // huge structure shared by all vertex and fragment points
}
[[group(0), binding(0)]]
var buf<uniform>: UniformStruct;

[[stage(vertex)]]
fn main() {...}

[[stage(fragment)]]
fn main_alpha_test() {..}

[[stage(fragment)]]
fn main_fallback() {..} // slow but portable

[[stage(fragment)]]
fn main_output_coverage() {..} // fast, but requires an "output coverage" extension

[[stage(fragment)]]
fn main_dual_source_blend() {..} // fast, but requires "dual-source blending" extension

[[stage(fragment)]]
fn main_tile_storage() {..} // fast, but requires "tile storage" extension
```

Presumably the authors would want able to group things into modules according what the logic needs (so that they can share the structures and get the related code together), not what the device capabilities are.

**Comment by litherum** [comment]
Good point.

**Comment by dneto0** [comment]
> In #600 it seems we've coalesced around the first line of the shader being something like #version foobar (like GLSL). Will we use a similar mechanism for opting into shading language extensions?

I don't see that, but have commented on #600 itself about it.

**Comment by dneto0** [comment]
> Will we use a similar mechanism for opting into shading language extensions?

I'd say definitely yes, and the pattern in #600 should be designed to naturally extend to language extensions.

**Comment by dneto0** [comment]
> However, there might be appetite for enabling/disabling extensions on a per-entry-point level.

Good topic.

I think this is not something we should solve at the WGSL level.

My reasoning:

* Principle: If a language processor ABC only knows about language LANG and extensions E1, E2, then it should only have to deal with source code using LANG and possibly E1 and E2.  It shouldn't have to deal with some new extension E3.  That would be asking for trouble.

* An extension should not change the meaning of an existing valid use of a noun or verb or operator.  Doing otherwise (related to extensions) invites confusion.  This is a "different meaning requires different spelling" rule.

* Given the different spelling rule, there is no point in turning _off_ a language extension after you've enabled it for a source file.  Extensions should normally only be additive. (Otherwise you've irrevocably forked the language.)

So I would advise enabling an extension as soon as you see fit, or as late as is needed before the feature is actually used.

If you want to have alternate implementations conditioned on presence of extensions, then take care of that in a templating/preprocessing system outside the scope of WGSL itself.


This also ties into #1241 to better spell out when a shader can be or is required to be rejected.

**Comment by dneto0** [comment]
> Presumably the authors would want able to group things into modules according what the logic needs (so that they can share the structures and get the related code together), not what the device capabilities are.

But the opposite force is at work too.  On a given device, you're only going to use shaders that actually work on the device.  So there's a natural grouping of sets of shaders that go together.   For larger systems, device features is one of the high order bit when grouping assets (including shaders).

**Comment by kvark** [comment]
> Principle: If a language processor ABC only knows about language LANG and extensions E1, E2, then it should only have to deal with source code using LANG and possibly E1 and E2. It shouldn't have to deal with some new extension E3. That would be asking for trouble.

In the [comment above](https://github.com/gpuweb/gpuweb/issues/1404#issuecomment-771987050) I was talking about a situation where the language processor knows about extensions used in the code, but the actual logical device may not have the relevant features enabled. So it can fully validate everything, other than the pipeline interface, since pipelines are not meant to be constructed.

> But the opposite force is at work too. On a given device, you're only going to use shaders that actually work on the device. So there's a natural grouping of sets of shaders that go together. For larger systems, device features is one of the high order bit when grouping assets (including shaders).

Writing shaders != using them. When writing, we want to share structures, type definitions, etc. This means, it's natural to group that VS with all those multiple FS in the same module.
Asset grouping is also not a thing people write, it's a processing step done by a machine.

**Comment by dneto0** [comment]
Mixing code for different target functionality, and putting it into the same WGSL source module means you can't (?) validate or generate code until pipeline creation time. (Either that or you generate/validate the power set of possible feature sets?)

That's contrary to the direction I thought we had agreed on, for good reasons.  E.g. see #1064

**Comment by dneto0** [comment]
> Writing shaders != using them. When writing, we want to share structures, type definitions, etc. This means, it's natural to group that VS with all those multiple FS in the same module.

That's the "I have shared definitions" pattern, well solved by preprocessing. That should be solved before getting to the WebGPU API.

**Comment by kvark** [comment]
> Mixing code for different target functionality, and putting it into the same WGSL source module means you can't (?) validate or generate code until pipeline creation time. (Either that or you generate/validate the power set of possible feature sets?)

I don't think that's true. The WGSL validator task would be to figure out what each of the entry point requires, but within each it still checks that everything is valid. Which `createShaderModule` checks are you thinking about when saying that we can't validate them?

> That's the "I have shared definitions" pattern, well solved by preprocessing.

When you have a preprocessor, everything looks like a macro substitution.
Seriously though, this may be what the user needs indeed. I'm just worried about a possible future where WGSL will be not practical without a preprocessor.

**Comment by litherum** [comment]
Seems to be a dup of https://github.com/gpuweb/gpuweb/issues/600
