### ISSUE TITLE
Zero initializing textures can not be done efficiently

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1422]
Previously, we discussed how to prevent the use of uninitialized resources. The main postulate of that discussion was: if it takes as much effort to identify uninitialized resources as to zero them out, then we should just zero them out.
It took us a while before we actually started thinking about how to implement this, and I'm coming to conclusion that this postulate was wrong. Here is why.

When we record commands in `GPUCommandEncoder` we don't know when they are going to be submitted, so we have to assume everything is initialized at that point (and handle the zero initialization at the `GPUQueue` level). Let's consider user doing `LoadOp::Load` on a large texture. Then the relevant `GPUCommandBuffer` reaches the queue and it turns out that the texture was never initialized. What should we do?

It's too late to change `LoadOp::Load` into `LoadOp::Clear`, since all the commands are already recorded. If we try to zero it out by other means, we are going to waste a whole ton of bandwidth filling it up, only for the render pass to do `Load` after that.

So we have a problem that actually doing zero-initialization can't be done as efficiently as the user would do it.
Issuing warnings is something the group tried to avoid as well. So perhaps we could reconsider making this an error?

**Comment by Kangz** [comment]
I remember we discussed this case precisely when talking about zero-initialization and the suggestion was that wgpu could record the inside of render passes separately from the outside of render passes. Then on `GPUQueue.submit` it can produce the correct render pass load operations, and weave in the render pass's content. With wgpu's architecture as always going through the Vulkan API, that approach is implementable using secondary command buffers.

Note that there is a potentially perf issue (or a command buffer split) only when there is a render pass with load ops being "load" which is a fraction of the cases where texture zero init needs to happen. Given the direction @cwfitzgerald is looking at for barriers in wgpu, it seems like it seems like it should eventually be easy for wgpu to do what I suggested. We'd also be fine with a warning (even if it's not necessary for Dawn).

In general forcing errors for missed initialization of textures adds more state to the API and more changes that under-tested code paths in applications will break so I think it is better to do zero-init on behalf of the application (it's also one more thing the developer doesn't have to worry about).

**Comment by kvark** [comment]
> I remember we discussed this case precisely when talking about zero-initialization and the suggestion was that wgpu could record the inside of render passes separately from the outside of render passes.

I'm not a fan of this suggestion. We don't want to use secondary command buffers for the majority of cases. It has implementation complexity, and it may affect performance on various platforms. In addition, it would force us to defer `vkCmdBeginRenderPass`/`vkCmdEndRenderPass` to the queue, and these are fairly heavy operations, especially on Metal. So it compromises the idea of recording commands in worker threads.

> Note that there is a potentially perf issue (or a command buffer split) only when there is a render pass with load ops being "load" which is a fraction of the cases where texture zero init needs to happen.

Splitting this code path would only increase the amount of code involved, will make testing more difficult.

> In general forcing errors for missed initialization of textures adds more state to the API

I understand this. Trade-offs are clearly involved.
I think we should first acknowledge that no currently shipping applications in native APIs rely on initialized state of textures. All the user code in the wild initializes them anyway, so it may be reasonable from our side to expect this mindset.

**Comment by Kangz** [comment]
> I think we should first acknowledge that no currently shipping applications in native APIs rely on initialized state of textures.  All the user code in the wild initializes them anyway, so it may be reasonable from our side to expect this mindset.

What does this entail? I wouldn't assume that native application initialize texture data correctly and instead I believe it is more likely they forget to initialize textures sometimes but that it happens to work for them (maybe flickers one frame and isn't seen afterwards, or is only in less used codepaths so less visible). In general talking to IHVs about barriers they expressed that ISVs do get barriers wrong, but happen to work anyway on the hardware they target. That idea transfers to texture initialization.

**Comment by Kangz** [comment]
(note, I agree that the implementation complexity or performance is a concern)

**Comment by kvark** [comment]
> I wouldn't assume that native application initialize texture data correctly and instead I believe it is more likely they forget to initialize textures sometimes but that it happens to work for them

Perhaps some aren't doing this correctly. My point is that it's the application *intent* at all times to initialize correctly. So if we have this restriction, it will be aligned with their intent.

> In general talking to IHVs about barriers they expressed that ISVs do get barriers wrong, but happen to work anyway on the hardware they target. That idea transfers to texture initialization.

I don't think this transfers well. The barriers are definitely more nuanced and complicated than just considering if the contents are initialized.

**Comment by Kangz** [comment]
> Perhaps some aren't doing this correctly. My point is that it's the application intent at all times to initialize correctly. So if we have this restriction, it will be aligned with their intent.

In Vulkan would use `LoadOp::DontCare` for my opaque pass on a previously discarded `RenderAttachment` texture if I know I'll write all pixels. Granted the developer's intent is to initialize things, but that's something that's not expressible in WeBGPU today.

Taking a step back, what I'm arguing is that it is hard for developers to ensure they initialize things correctly, especially in code paths that are taken more rarely. Making missing initialization an error would make the API much more fragile to use and the only performance problem for `wgpu` seems to be for discarded attachment reused in following frames. I think this is a great place for a warning, and we could consider putting the same warning (it could simplify our logic a bunch, or just guide people to best practices).

**Comment by greggman** [comment]
I'm so far out the loop I have no idea if these comments are useful but.....

The most common place in OpenGL/WebGL to not initialize is when creating a texture to render to. It's the norm not to initialize.

Worse, Firefox used to complain (warn). "Hey, you didn't init this texture so we had to init which is slow" which was a nonsense warning since it's faster for WebGL's implementation to clear the texture than it is for JavaScript to make a typedarray big enough to clear, clear that typed array to 0 (well, the JS engine will do that), then transfer that say, 16meg of zeros over the process boundaries so that those zeros can then be passed to the drivers.

**Comment by Wumpf** [comment]
Another case against a warning / deliberate slow path would be that this enshrines portability issues: One implementation may actually be significantly slower when hitting the non-init path whereas another one is faster, so users may be hit by surprise when an implementation actually performs worse. On top of that it depends on the GPU type (forward/tiled) how bad the hit is.

Sidenote on other zero init situations:
While it's natural to assume that a user would usually explicitly init data for textures and render targets for rendering purposes, I believe it's less clear for storage textures/buffers and compute usecases in general.
Apart from renderpass-clear, the API doesn't expose a convenient way of clearing memory before first use, meaning that in order to zero out e.g. a particle system velocity buffer/texture one would need to either have a dedicated clear pass or upload a large zero memory block (inefficient). For buffers this always requires a clear shader, for storage textures either a clear shader or making the texture a render target to clear.
So being able to assume that freshly allocated memory gpu is already efficiently (!) cleared is very convenient in these cases.

**Comment by Wumpf** [comment]
I agree with what @juj wrote, but isn't the original motivation to have zero initialized textures a security concern of reading out old data from previous applications? Or is this (assumed to be) handled already differently?

**Comment by kvark** [comment]
The idea is that, if we aren't auto-zeroing textures, and we expose helper methods that @juj suggested (especially with sub-rectangles!), then the WebGPU implementation would just make it a validation error to try using any uninitialized textures. So the security concern is addressed.

Here are some general use cases:
  - I created a renderable texture, and I want to render into it - I have to use the "clear" load operation
  - I created a texture, and I uploaded some data into it, and I want to bind it for shaders to sample - I have to call `clearTexture(texture, [region1, region2, ...])` specifying all the sub-rectangles that I left uninitialized.
  - I created a storage texture, and I want to fill it in compute shaders - I still need to call `clearTexture(texture)` since there isn't any gaurantee that a compute shader will fully initialize it.

One of the tricky points here is algorithmic - given a list of sub-rectangles we'll need to determine if they add up to the whole subresource rectangle. It seems solvable, although some research may be needed here.

**Comment by Kangz** [comment]
Hold on, `fillTexture` could be a thing (although I'd argue after MVP because we need to stop adding stuff to the API if we want to ship it). However making missed zero-init an error and asking developers to correctly init, in part using `fillTexture` doesn't help anybody.

 - It doesn't help the browser avoid uninitialized data because they still have to check that textures are correctly initialized by walking all subresources. Even worse if there's sub-rectangles per subresources (we had code like this in Chromium for WebGL but AFAIK the general consensus for Chromium was that it was too complicated and should track only per-subresources).
 - It doesn't help developers because they have to spend more efforts making sure textures are initialized otherwise whole `GPUQueue.submits` will be no-ops because of errors. With zero-init they just need to know what the content of the texture is.
 - It doesn't help developers because the initialization becomes state modified by `GPUQueue.submit` so if you fail a submit because of an uninitialized texture, it's likely to keep happening the next frames because the submit in the current frame that could have initialized the texture didn't. At that point your application just stops rendering at all because all submits are errors.
 - It barely helps `wgpu` because it avoids them having to do a command buffer split before each render pass (to insert a clear if needed) and emit a warning.

We should keep zero-init. Maybe `wgpu` makes implementation choices that make zero-init a bit complicated in some cases but the same implementation choices gives `wgpu` advantages in other areas.

> So I am not sure how "it is likely native developers forget to initialize textures and it will lead to one frame flicker" could happen.

Native developers are fallible like all developers and there will be under-tested code paths that forget to initialize textures. Examples of one-frame flickers are if you expand the texture view for a streamed texture before it is written, same thing for light probes, maybe some TAA accumulation buffer (because of the exponential decay), ...

That was the point of my comment about memory barriers: a lot of time when discussing WebGPU or other standard GPU APIs is that "game engine developers can do it better". That's not the feedback we've had from HIVs that say they often need to hold developers' hands to get them to ship correct code. What's more developers using WebGPU won't all be AAA / huge game engine developers that supposedly write perfect code, and they are in the audience for WebGPU.

**Comment by kvark** [comment]
@Kangz here is what's going to happen, and what I'm worried about:
  1. we are forced to insert `VkClearImage` on uninitialized texture subresources prior to invoking a render passes. On Metal, that translates to a whole dummy render pass with a clear operation.
  2. developers develop & test on Android with mostly Chrome
  3. users run on Android with Firefox, they observe significantly slower performance, because `VkClearImage` does the VRAM writes, which are followed by VRAM reads by the render pass that user encoded (with `LoadOp` == "load"). So we are paying 2x fully subresource data transfer (one to VRAM, one from VRAM), which can be devastating.

Imagine a program that just... clears the screen. Ideally, it writes every texel out. In our case, if the user specified `LoadOp` == "load" on this render pass, it would write every texel, then read every texel, then write every texel back. So it's 3x slower. I think this is serious enough to question the API choices of WebGPU.

And to re-iterate, I don't think using `VkSecondaryCommandBuffer` is an answer for us. It's a huge complexity increase, more code paths, worse threading (since `vkBeginRenderPass` would have to be done at `submit()` time), and an invitation to meet driver bugs.

There is also a question to @litherum on what Apple is going to do. Are you going to be deferring all the render pass recording like Dawn does? I'd expect your implementation to not do this, but I'd like to know more about your approach.

**Comment by litherum** [comment]
I don’t think I can comment on the general issue yet (it’s a lot to try to fit into my tiny head). But some specific points:

> native game engines or graphics renderers certainly don't rely on newly created textures being zero-filled, since no native API provides such guarantee.

I believe Metal actually _does_ make this guarantee, for some creator routines, though it may not be documented.

malloc() : MTLHeap.makeBuffer() :: mmap() : MTLDevice.makeBuffer()

> Are you going to be deferring all the render pass recording like Dawn does?

Our plan is not to do this. We feel that if there was a design of WebGPU that requires deferred recording for most commands, that design would be a bug and would need to be fixed.

**Comment by Kangz** [comment]
> Our current implementation doesn’t do this, and we would prefer to not do this in the future. We feel that if there was a design of WebGPU that requires deferred recording for most commands (at least on Metal), that design would be a bug and would need to be fixed.

To be clear, this issue doesn't require that you defer the recording of commands at `GPUQueue.submit()` time. At worst you'll need to split your `MTLCommandBuffer` before some of the `beginRenderPass`. In general I think WebGPU should make sure it is implementable in the immediate vs. deferred recording approaches. However it shouldn't be a design constraint that it is 100% efficient or easy to implement on both designs because each have their tradeoff, and that's ok.

However since this @kvark has performance portability concerns, I think we'd be ok to add a performance warning in Chromium that tells you that `load` on uninitialized textures could be slower "on some configurations" even if it isn't in Chromium. This way if a developer happens to test only on Chromium (they really shouldn't) then they'll get the warning and fix their code.

**Comment by jdashg** [comment]
> 
> 
> I'm so far out the loop I have no idea if these comments are useful but.....
> 
> The most common place in OpenGL/WebGL to not initialize is when creating a texture to render to. It's the norm not to initialize.
> 
> Worse, Firefox used to complain (warn). "Hey, you didn't init this texture so we had to init which is slow" which was a nonsense warning since it's faster for WebGL's implementation to clear the texture than it is for JavaScript to make a typedarray big enough to clear, clear that typed array to 0 (well, the JS engine will do that), then transfer that say, 16meg of zeros over the process boundaries so that those zeros can then be passed to the drivers.

We detect when lazy-init isn't needed, like for most texImage+texSubImage cases, and for using clear on framebuffer attachments. If the app wants stuff cleared to zeros, the app is best positioned to choose how this happens. (For webgl2, upload from your own zeroed PBO!)

---

I am more afraid of validation-portability than I am of performance-portability for this case. That is, I think it's probably better for users if an app janks sometimes in order to late-lazy-init, rather than failing to draw sometimes when a StoreOp.Clear got interleaved with a LoadOp.Load wrong. (e.g. from scheduling/event differences)
It's best for users if apps fix themselves, of course!

I don't mean to undersell the pain of having to do these janky late clears, but in contrast, for users it's almost always better to be slow than broken.

I think the only riposte to this is that apps will definitely see validation-portability as their responsibility to fix, whereas performance-portability often turns into an Enhancement Request bug report. Will they fix it though? :) Worst case scenario is that the app puts up a "best in X browser", but c'est la vie.

Should we spec a warning in this case? ("SHOULD" not "MUST")

**Comment by kainino0x** [comment]
If we can come up with a satisfactory simple rule for issuing warnings, I think it would be a good idea to mention it in the spec.

**Comment by kvark** [comment]
I may be remembering it wrong, but I think we had a consensus at some point (very early on) that the API should be "good" without the user paying attention to the warnings. And by "good" I mean the major properties of the API should be fulfilled: security and portability, including performance portability.
If we are to spec a warning in this case, this would be the first case of a kind.

**Comment by kainino0x** [comment]
Here we have a tradeoff between potential flaky _performance_ and potential flaky _validation errors_. I'm not sure there's a solution that avoids both. The warnings would give some developers some information if they've written performance-flaky code (which we suspect they won't have intended to do).

**Comment by kvark** [comment]
I'm not sure about the validation errors being flaky. This might be right, but in this thread we haven't gotten a case described which would show that users would legitimately hit this validation errors without expecting it.

**Comment by frguthmann** [comment]
Quoting @jdashg 
>I don't mean to undersell the pain of having to do these janky late clears, but in contrast, for users it's almost always better to be slow than broken.

As a user, I strongly disagree. It is immensely difficult to figure out what is efficient and what is not when building 3D applications for the web. There is no way of knowing whether I'm using the API wrong, or the UA got the implementation wrong, or the UA had no choice but to implement it that way because of security reasons and so on. I'm sure there are lots of quick fixes I could do in my current WebGL engine to avoid hitting slow paths but there's just no way for me to figure this out.

If you know something is slow, please tell us. A crash is fine by me.

**Comment by kvark** [comment]
The group has actually resolved this to: do lazy clears, but also Chrome will have warnings for going the slow path, even if it's not slow in Chrome in particular.

@frguthmann you provide a good explanation of the "validate everything" approach, thank you! I largely share this view, but I concede that there isn't a good consistent solution to this.

For texture transfers, it's not always easy for either the user or the implementation to ensure the full subresource is initialized. I.e. if I have an atlas, do I need to clear it? If so, why? What if I just copy 100 small subrectangles covering the subresource, should the implementation be smart enough to not error on this? And so forth... So doing a lazy clear is at least giving us more freedom to make this tracking an implementation detail.

**Comment by frguthmann** [comment]
> For texture transfers, it's not always easy for either the user or the implementation to ensure the full subresource is initialized. I.e. if I have an atlas, do I need to clear it? If so, why? What if I just copy 100 small subrectangles covering the subresource, should the implementation be smart enough to not error on this? And so forth... So doing a lazy clear is at least giving us more freedom to make this tracking an implementation detail.

That makes a lot of sense. A warning is fine by me too. I just thought the group ruled it out early in the process.

**Comment by kainino0x** [comment]
Editors should discuss speccing a warning for this. I think it's not too hard. (Since it's just a "should warn", we don't need formal tracking of the "isInitialized" state in order to describe the warning case.)
