### ISSUE TITLE
allow array size that is a pipeline-overrideable constant

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1431]
Compute shaders are often parameterized by key sizing knobs:  workgroup size, and internal shared storage sizes.

It's important to be able to parameterize the size of an array in workgroup storage.  A good pattern for this is to use a pipeline-overridable constant as the size of the array.
(Also following #1272, to allow certain expressions over pipeline-overrideable constants).

FYI, for other environments the resizable workgroup array is supported like this:
- OpenCL C supports this idiom via a pointer-to-local kernel argument, and on the API side the dispatch specifies the size of the underlying array.  (The contents are uninitialized
- MSL supports this via pointer-to-threadgroup (buffer) kernel argument.  On the API side (if I understand it correctly), you supply a regular buffer object, which has a max length (e.g. see [here](https://developer.apple.com/documentation/metal/mtldevice/2966563-maxbufferlength?language=objc))
- SPIR-V for Vulkan:  Use a specialization constant to size the array.  
- HLSL: I haven't looked.   I think we agreed the normal pattern would be to use a #define

**Comment by litherum** [comment]
> MSL supports this via pointer-to-threadgroup

You might be thinking of [`MTLRenderPassDescriptor.threadgroupMemoryLength()`](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/2866527-threadgroupmemorylength). If you want to have a variable-length threadgroup buffer, you don't actually create a `MTLBuffer` - instead, you just set this field and the pointer in the shader will just point to space that's the right size.

If you want regular normal arrays that are variable length, that's not really a problem in Metal, because arrays are just represented by pointers, which don't have an associated size. Unsafe languages are awesome.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-06-01-Minutes#allow-array-size-that-is-a-pipeline-overrideable-constant--issue-1431">WGSL meeting minutes 2021-06-01</a></summary>



*   DN: Want to size arrays based of workgroup-size. Right now arrays can’t be spec-constants, though workgroup-size is. This would be what spir-v allows.\
*   JB: Can we allow for some static checks? E.g. if it can tell that the access will always be OOB?
*   DN: Usually we stay away from that here, so that we don’t snowball required complexity. Because you can’t do it in general, we don’t want to have divergent implementations.
*   (needs spec)


</details>

**Comment by dneto0** [comment]
The feature was narrowed to #2024, which was fixed by #2347
