### ISSUE TITLE
copyToTexture for color-managed image sources

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1483]
We agreed upon a `copyToTexture` (aka `copyFromTextureSource`/`copyImageBitmapToTexture`) for various image sources (`ImageBitmap`, `HTMLCanvasElement`, `HTMLVideoElement`, `OffscreenCanvas` in #1154). Of note, all of these image sources are _color-managed_ - that is, they represent colors. (IIUC `ImageData` should be treated as color-managed as well.)

GPUTextures are _not_ color-managed - they represent raw float/int/norm numbers (with optional srgb conversions). This means colorspace conversions can/should occur inside `copyToTexture`. In order to do this, we need to know (and specify) the destination colorspace and encoding.

- An easy starting point is to specify that the destination colorspace/encoding are always well-known defaults. This lets us add optional dictionary options later on that allow changing the defaults - but this would require feature detection, so it's best if we add a member earlier, even if it has only one legal value and it's the default.
- It's important to get the encoding conversions right - that is, srgb vs non-srgb. We allow both srgb and non-srgb formats as copy destinations, and we need to make sure applications can achieve the managed-image-upload semantics they need. (Note they can also get exact behavior by uploading using writeTexture instead, which involves no color management.)

See also #1482 about high-bit-depth sources.
See https://github.com/WICG/canvas-color-space about _output_ colorspace/encoding.

**Comment by kenrussell** [comment]
A concrete improvement that @ccameron-chromium has proposed in the W3C's ColorWeb CG relates to the WebGL versions of these upload paths. These provide control over whether to premultiply the alpha channel, and whether to perform color management (UNPACK_PREMULTIPLY_ALPHA_WEBGL and UNPACK_COLORSPACE_CONVERSION_WEBGL). Applications need these knobs in order to use images as normal maps, for example.

These parameters found their way into ImageBitmap's creation options. Chris [has proposed](https://docs.google.com/presentation/d/1rvCYKq6T4koS0yRd_C91se6v1h2YJF32pPHtPtBo-R8/edit#slide=id.gb879bc1582_0_23) to generalize the boolean "do colorspace conversion or not", and allow the user to specify the destination colorspace / use the image's built-in one / ignore it completely.

Those knobs sound good to me and WebGPU's copyToTexture probably should have the same controls, where they apply to the input sources.

The goal of ImageBitmap is to allow all of this conversion work to be done up front, avoiding synchronous transformations or image re-decodes - so these parameters should ideally not be supported, or be ignored, in the ImageBitmap -> GPUTexture upload path. WebGL ignores them per spec in this case.

**Comment by kainino0x** [comment]
I think there are two reasonable defaults to consider:

- default destination colorspace/encoding are fixed, to something like "whatever colorspace/encoding the browser uses for untagged content"
- default destination colorspace/encoding to "whatever the source image has", i.e. don't do a conversion
    - If this option is allowed for non-RGB videos, or hypothetical future non-RGB canvases/ImageBitmaps, this is impossible, so it has to have a different meaning, like defaulting to a specific colorspace/encoding.
    - I assume that for untagged content (without color metadata) the browser would pick a default for us (same as what it uses for `<img>`), and we can use that as the source colorspace/encoding.

And either way it should be possible to achieve

**Comment by kainino0x** [comment]
I spoke with @ccameron-chromium about this and here is my understanding about the current direction of canvas/webgl color:

There is no unspecified "whatever colorspace/encoding the browser uses for untagged content". The default is always the sRGB color space. This makes life easy because we can simply add `colorSpace` dictionary options in various places that default to `"srgb"`.

For image sources, this explicit control makes it easy to ensure that color conversions are done ahead of time in `createImageBitmap` - there will be no conversion in `copyExternalImageToTexture` as long as the `ImageBitmap` color space and the copy destination color space match. `ImageBitmap` would also default to "srgb", so if you don't specify anything, this happens by default. But if you do specify color spaces, `ImageBitmap` and WebGPU will use the same `PredefinedColorSpaceEnum` so it's easy to _make_ them match.

It's TBD whether the CSS color level 4 [`srgb`](https://www.w3.org/TR/css-color-4/#valdef-color-srgb) means extended-srgb or clamped-srgb. This matters to us in the following ways:
- Does `copyExternalImageToTexture` clamp to 1 when converting to float texture formats? (Does not matter for normalized texture formats; in that case it must always clamp to 1 anyway.)
- Does a clamp to 1 need to be done before returning a value from textureSample/textureLoad on `texture_external`?

#1666 has been updated accordingly, and includes new surface for tagging these color spaces. I'll have follow-up PRs to use that in `copyExternalImageToTexture` and `configureSwapChain`.

**Comment by kainino0x** [comment]
Update: This is resolved in the spec except for the clamped vs extended issue.

**Comment by Kangz** [comment]
This seems very similar to https://github.com/gpuweb/gpuweb/issues/1715 and https://github.com/gpuweb/gpuweb/issues/1847

Can the issues be deduplicated somehow?

**Comment by Kangz** [comment]
and https://github.com/gpuweb/gpuweb/issues/1482 too

**Comment by kainino0x** [comment]
There's only one remaining thing here (clamped vs extended) and it's at the top of my todo list to actually resolve that which will close this issue.
The other three are for very specific issues (and #1847 gets intertwined with other canvas presentation stuff too).

**Comment by shaoboyan** [comment]
>There's only one remaining thing here (clamped vs extended)

One quick thoughts, it seems that extended mode could support scRGB.

**Comment by kainino0x** [comment]
The CSS Color Module Level 4 spec defines the `srgb` colorspace (and others) outside of the 0-1 range. I think this was a somewhat recent change. I don't know whether its definition matches scRGB or not, but it does something similar.
https://www.w3.org/TR/css-color-4/#predefined

**Comment by svgeesus** [comment]
> The CSS Color Module Level 4 spec defines the srgb colorspace (and others) outside of the 0-1 range. 

Yes. This is now true for all the predefined colorspaces. This helps with Canvas, it will help with HDR, it may give a better mapping onto hardware and hopefully, helps WebGPU as well.

> I think this was a somewhat recent change

It was a gradual process, starting with updating the sample code, then the prose, and finally tracking down all the old text which claimed only values in [0,1] or [0,255] (as appropriate) were valid. For example [this one from May 2020](https://github.com/w3c/csswg-drafts/commit/0503cf1e2043a07b2caef924ad12baa574cc7080#diff-e1ef1cfacc6b46c293a73dc844f094d931e45a06d078ca40ff09b61570bc16c2)

> I don't know whether its definition matches scRGB or not

It matches scRGB-nl (i.e. the non-linear form) with the same transfer curve, reflected at the origin. However instead of packing the result into 12bits like scRGB-nl does, the values are expressed in CSS syntax textually as floats. The minimum precision is also different in CSS Color 4 (more lax than scRGB-nl).

CSS Color 4 also exports a [`linear-light srgb` term](https://drafts.csswg.org/css-color-4/#linear-light-sRGB) but currently does not expose this as CSS syntax. Although [there is an open issue about that.](https://github.com/w3c/csswg-drafts/issues/6087#issuecomment-939972995)

**Comment by kainino0x** [comment]
Thanks @svgeesus! Nice that the definition lines up with scRGB-nl.

> However instead of packing the result into 12bits like scRGB-nl does, the values are expressed in CSS syntax textually as floats. The minimum precision is also different in CSS Color 4 (more lax than scRGB-nl).

I think this shouldn't be a problem for us, as we always have concrete formats like rgba16float or rgba8unorm which specify exactly how the data is represented.

#1715 is the issue where we track linear-light srgb, which we will benefit from.

**Comment by kainino0x** [comment]
> There's only one remaining thing here (clamped vs extended) and it's at the top of my todo list to actually resolve that which will close this issue.

Oops, #2142 should have closed this issue!
