### ISSUE TITLE
Should objects have pointers back to their parents?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1497]
Today (post-#1478), no objects have attributes that point back to their parents, i.e.:
- device -> adapter
- {queue, buffer, texture, pipeline, command encoder, etc} -> device
- texture view -> texture

Should we add these back-pointers?

Non-blocking because adding them is a non-breaking change.

See also: #1498

**Comment by Kangz** [comment]
Probably want to discuss this for v1.

**Comment by jdashg** [comment]
I want these though. :)

**Comment by Kangz** [comment]
Please describe why you want them back, otherwise conversation is not really moving forward. As discussed in the last meeting there are three types of pointers to parent objects:

 - Pointers to `GPUAdapter`: all of the information is replicated on the device (in terms of what features / limits are actually available on the device) so this pointer back seems unnecessary.
 - Pointers to `GPUDevice`: it is important that middleware / helper libs etc have access to the device that created various resources. But really the device is the root object of WebGPU so it makes sense to pass it to the initialization of these things instead of taking it from a back-pointer of a child object. So I don't think we need it.
 - Pointer to `GPUTexture` from the `GPUTextureView` that's kind of the only one that feels like it might be useful because it's more than one parent object, but do we want to special case textures? People can pass a `GPUTecture` + `GPUTextureViewDescriptor` around.

That's why I don't think back pointers are unnecessary, and folks seemed to agree in the last call.

**Comment by litherum** [comment]
(Just because this doesn't seem to be already written down in this issue) The benefit of having them in Javascript is significantly smaller than the benefit of having them in native code, because they can be polyfilled in javascript with a single fairly-trivial line at object creation.

**Comment by Kangz** [comment]
I think we should close this issue. If we get feedback that back-pointers are critical, it will be a non-breaking change to add them later.

**Comment by toji** [comment]
I recognize that it's still a (contentious) proposal, but it seems likely that if we add any [identifying information about the adapter](https://github.com/gpuweb/gpuweb/issues/2195#issuecomment-992739992) we'll want a back-pointer to it from the device as well. Unless we want to duplicate that same information on the device, which feels awkward.

Also the difference between the features/limits the device was created with and the ones the adapter supports does seem like something that may be of interest to certain libraries. IE: Should the library raise a warning that the developer needs to create the device with a given feature or should it fall back silently because the device in question doesn't support it in the first place.

And a huge +1 to @litherum's comment. I _can_ create libraries in JavaScript that monkey-patch their way around this but that's not an option for C++, Rust, etc.

**Comment by kainino0x** [comment]
The longer this issue sits, the more I think we should just go ahead and do it. The implementation cost is minimal and I'm not worried about cost of keeping extra JS wrappers alive. There are many clear cases where it would be _convenient_ to have this even if it's not strictly necessary.

**Comment by toji** [comment]
Put together a PR (#2484) to speculatively show how this could be added, in case it helps inform this decision one way or the other.

**Comment by kvark** [comment]
I don't have a strong position against this feature. It may be useful, although from https://github.com/gpuweb/gpuweb/issues/1497#issuecomment-992192654 that's not entirely clear. It would help to have a good list of use-cases here.

One concern I have is that this change would encourage people to write potentially unsound code. In JS there is no immutable references to objects, as far as I understand. So we'll end up with users writing functions like this:
```js
function myHarmlessFunction(textureView) {
  textureView.parent.destroy();
  // or even
  textureView.parent.device.destroy(); // let the world burn!
}
```

I.e. since all links in JS are mutable, parent links mean there is no scope of change associated with each object. If I pass a texture view into a function, it may destroy the whole device, and I wouldn't know that without reviewing that function (i.e. not visible from the function signature).
I'd much rather have users write it explicitly all the time:
```js
function myReallyHarmlessFunction(textureView, texture, device) {
  texture.destroy();
  device.destroy(); // let the world burn!
}
```

**Comment by toji** [comment]
That's fairly dependent on personal coding style, and how well the developer enforces it.

In my experience it's far more common in small projects to see developers simply store the context/device/etc as a global variable, in which case any function could access it without it being apparent. In larger projects/libraries it typically becomes part of a monolithic "Renderer" object that gets passed into every function anyway. After all, there's very little that you can do with just a textureView unless you have the corresponding device. So I don't see that this makes a lot of difference one way or the other in that specific respect.

**Comment by jdashg** [comment]
Same as in #1498:
Having written a bunch of wrapping layers myself, I wish I didn't have to do so in order to retain this sort of data.

I have multiple projects where I use this info:
* https://github.com/jdashg/canvas-rr
* https://github.com/jdashg/webgl-2022 

I think the trick (and where this differs from #1498) might be whether we want to retain a strong-ref to the parent or not. If we offer this back-link, we *have* to, because we can't give any more information up than an author would get with a JS WeakMap.

If, however, we keep the parent alive while the child is alive, that might hold open `parent` longer than strictly needed. In wrapping libraries, this is generally an acceptable sacrifice, though it's one corner of handling that they can't perfectly deal with.

Perhaps that's even a good reason to have the strong-ref behavior, so that there aren't generally-unwrappable apps. (or unemulatable apps! Imagine if you wanted to polyfill a subset of [webgpu on top of webgl2](https://github.com/jdashg/webgpu-js), or something ;))

Devtools would *not* have this constraint, but it's worth considering whether the trade-off is worth it for non-devtools cases.

**Comment by kdashg** [comment]
I'm assuming that e.g. Buffers don't keep-alive their Device.
In this case, we probably can't have this without introducing real weak-ref behavior that would be more capable than WeakMap. (which keeps weak-refs to keys, but strong-refs to values)
We don't want to keep-alive e.g. a Device because someone attached e.g. a Buffer to e.g. an input element somewhere.

Thus unless we can offer weak-ref queries of parent from child objects, I guess we should shelve this.

**Comment by toji** [comment]
> I'm assuming that e.g. Buffers don't keep-alive their Device.

Resources keeping the device alive is the [current behavior in Chrome.](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webgpu/dawn_object.h;l=124;drc=20aad063bc0434f1d89ccfb023efe427afd3a96c) I don't think the spec is opinionated on the matter currently, though right now the behavior is undetectable. (If your JS has lost all it's references to the Device you can't do anything meaningful with a Buffer.)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-07-06#should-objects-have-pointers-back-to-their-parents-1497">WGSL meeting minutes 2022-07-06</a></summary>

* KG: device->adapter, queue->device, view->texture.
* KG: closed this because I felt this wasn't implementable - to keep the back-reference and not introduce real weakref behavior we'd have to keep strong refs from children->parents. Feels intolerable to me. Kai reopened it, said it might be valuable. Accurate?
* KN: more or less. I didn't think the conclusion was foregone, wanted to discuss.
* KN: I agree with the problem you posed. Might be technically possible to avoid it, but not easy. Don't think we should pursue it. So I agree we should close the issue.
* JB: why's it difficult? Many of these objects we can't even use if we don't have a pointer to the device.
* KN: difficult to guarantee that if you drop the ref to the GPUDevice, but holding on to random thing like BindGroupLayout in your app, the device is reachable. Therefore have to keep context alive. Yes, you should destroy the device, but GC should work better than that.
* KG: concretely - uploading texture based on image. If you say HTMLImageElement.webGPUVersion = webGPUTexture; and then forget about it, the img will keep alive GPUTexture, GPUDevice, and we can't GC it.
* JB: so we have unexpected forgotten references to API objects. No device, can't use them anyway.
* KN: we would have the device.
* JB: if don't have the links - we can clean up the device and clean up subsidiary objects as well, and that's the behavior you're trying to preserve. If people want to use expando properties, they can. I see.
* KG: FWIW in Firefox WebGL children do not keep their parent alive. Don't know what we do in WebGPU.
* BJ: was going to ask that. Currently, in Chrome, whether we have the parent backpointer, we keep device pointer in each resource we create. Valid to say, we should fix this problem and use weak-refs everywhere. We could. Does Firefox have this problem?
* KG: I plead the fifth. :)
* JB: right now we have a strong-ref to the parent.
* BJ: very similar pattern to what we do in Chrome.
* JB: if collecting parents is desirable - spec it, try to implement? We'll discover problems for V1.
* MM: there are a few cases where we must keep parent pointers alive. Operations on default queue, and from object, can't get to the default queue.
* BJ: example of those? createview?
* KG: mapBuffer.
* MM: mapBuffer's a good one. Discrete GPU, have to copy in/out.
* JB: mapAsync?
* BJ: yes.
* MM: there are 2-3 such operations.
* BJ: if behavior of assets not keeping parent alive is desirable - should have spec text saying this. But we can't guarantee that, based on tests?
* KN: what prevents us from doing this?
* …
* KN: you can just keep the shadow copy alive - don't need to keep the device alive. Possible.
* KG: if you don't have the means to keep it alive … nice to collect the device if you don't have a reference to it nor a way to use it.
* KN: thought about this already because - have another open issue, when device's lost, doesn't interrupt app flow. Want to make mapping always work, even with lost / destroyed device. Give you an ArrayBuffer. Does it have right data in it or not?
* MM: tricky. Timing of when Promise gets resolved is based on other work in the context.
* KN: yes, tricky. Would like to not constrain the API, and not have strong refs. Weakrefs, maybe. Should punt on them if we consider them at all.
* BJ: we should definitely not add API-visible parent refs. Should not mandate that you can't have strong refs. Impls might need them. We should try to operate off more a weakref model.
* **Come back next week**

</details>
