### ISSUE TITLE
Restrict where entry point IO types can be used

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#1526]
The WGSL spec lists a small number of places where entry point IO types can be used (entry point parameters and return values, and as struct members), but does not say where they *cannot* be used.

Can they be used as parameters on non-entry point functions?

Can they be used as return values for non-entry point functions?

Can they be used as the type of a variable?

Allowing these things can result in implementation complexity, particularly when a non-entry point function that uses an entry point IO type is called from both vertex and fragment shaders. I'd be in favor of disallowing all of the above cases, but I'd be interested to hear from others as to whether there are compelling use cases for allowing any of them.

For example, the kind of thing I'd rather not have to support is this:
```
struct Input {
  [[location(0)]] value : f32;
  [[location(1)]] mul : f32;
};

fn foo(x : Input) -> f32 {
  return x.value * x.mul;
}

[[stage(vertex)]]
fn vert_main(s : Input) -> f32 {
 var x : f32 = foo(s);
 ...
}

[[stage(fragment)]]
fn frag_main(s : Input) -> f32 {
  var x : f32 = foo(s);
  ...
}
```
I think MSL shader authors wouldn't be able to write this sort of code anyway (since vertex and fragment shaders use different attributes for user-defined inputs), and the situation for HLSL is similar for outputs (`TEXCOORD` vs `SV_Target`).

**Comment by kvark** [comment]
Right. Let's forbid all these cases for now and come back to this after MVP?

**Comment by jrprice** [comment]
> Can they be used as the type of a variable?

Thinking about this some more, we'd need to allow this for function-scope variables inside entry point functions, so that the user can create return values:
```
struct Output {
  [[location(0)]] a : f32;
  [[location(1)]] b : f32;
};

[[stage(vertex)]]
fn vert_main(s : S) -> f32 {
  var ret : Output; // Need to allow this
  ret.a = 1.0;
  ret.b = 2.0;
  return ret;
}
```

I think supporting this limited case should be fine.

**Comment by alan-baker** [comment]
Do we have to carve out an exception for function variables? Your example could just be:

```
struct Output {
  [[location(0)]] a : f32;
  [[location(1)]] b : f32;
};

struct S {
  // ...
};

[[stage(vertex)]]
fn vert_main(s : S) -> Output {
  return Output(1.0, 2.0);
}
```

Where should the tradeoff between user and tooling convenience be? If we allow function variables why not require implementation to create an internal unattributed version of the struct and take care of it for the user? The spec could ignore attributes in contexts they don't apply. I'm not actually proposing this as a way forward, but we should have a conscious justification for picking some point in the middle.

**Comment by jrprice** [comment]
That's certainly an option, and I'd also be fine with that if we feel that it's not a significant burden for users.

I'm not sure that allowing entry point function-scope variables would be much of an exception. I think it'd be a fairly straightforward rule: entry point IO types are allowed as parameters, return values and function variables for entry point functions only.

I don't have a strong opinion either way.

**Comment by dneto0** [comment]
Discussed in [2021-03-23 meeting](https://docs.google.com/document/d/19inX49uQBMkWx1lSuPkFWJ8fGRJUGMNXmkUj5TJWnwY/edit)

No resolution yet.    Encourage further discussion here on this issue.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-03-23-Minutes#restrict-where-entry-point-io-types-can-be-used-1526">WGSL meeting minutes 2021-03-23</a></summary>

*   Different rules per attribute?
*   RM: What’s the problem with allowing this and ignoring it when they aren’t being used as IO
*   AB: That’s the meta question about attributes: when should they matter
*   MM: They matter when it’s observable.
*   AB: It’s not obvious where it’s observable.  E.g. calling a function.  Do we need a bunch of individual rules? Or do we say ignore in all contexts except in certain situations
*   GR: Bad to have things being ignored silently.  You get superstitious folks adding things and then having no effect.
*   MM: example of offsets in struct returned from a helper, then stored into a buffer. That should work.
*   AB: Agree for certain cases, e.g. sharing structures. Not sure it applies everywhere.
*   MM: “When a location is specified in a particular place, then it has _this _ effect.” So that entails that if it’s used in a struct but is used in a different context, then it has no effect.  This is a convenience-for-authors argument.
*   GR: How does it help an author to be able to put this everywhere.
*   MM: Code reuse.  E.g. the first example in the issue seems perfectly fine. Not objectionable.
*   AB: If we say they’re ignored in certain places, then we may limit the future path of development because all of a sudden something that used to be ignored becomes meaningful, then it can break an already-shipped shader.
*   AB: Example adding auto-layout of locations, could lead to conflicts.
*   MM: If we change the language to auto-assign, where the author can currently assign value manually, then that change to the language must take into account the possibility that the author has assigned those fields.
*   AB: E.g. authors themselves could put conflicting locations that they expect to be ignored, and then later it becomes significant.
*   JG: Think that’s possible but low risk.
*   AB: Also ties to issue David raised about whether adding an attribute to the type if it forms a new type. 
*   MM: offsets internal to a struct, perforce is a different type.
*   DN: Agree.  The interesting case is when the attribute is on the outside of the type.
*   DM: Concern about confusion if allow things in too many places.  E.g structures with locations in them, but then used in a compute shader.  Think the test case in the issue should not be supported at launch.
*   MM:_  describes use-case of a thing (having sample mask) used both in fragment shader and compute shader._
    *   Using such a struct in a helper function doesn’t care about whether or not a particular sample mask was populated in an entry point (some other function)
*   _Timebox closed._
*   _Encourage: add comments to the bug_

</details>

**Comment by kvark** [comment]
Another more subtle sub-question: can we at least say that a structure field can't have both the layout attributes (`[[size]]`/`[[align]]`) and the bindings (`[[builtin]]`/`[[location]]`)? I'm finding it hard to imagine why somebody would want to use the I/O struct as host-shareable, and in any other context the size/align aren't relevant anyway.

**Comment by jrprice** [comment]
Contrary to what I wrote in the initial comment, implementation complexity is no longer a concern for us (the translations you have to do even if we restrict these attributes are also sufficient to handle the cases where we do not restrict these attributes).

Instead, we're considering cases where allowing these attributes everywhere may be potentially useful for shader authors, and other cases where it may be potentially confusing. Here are some examples of what you could write if we do not restrict these attributes.

**Sample 1**
Module-scope private variable, type is a struct with pipeline output attributes.
Potential confusion: looks like this is writing to a pipeline output, but it isn't.
```
struct VertexOutput {
  [[builtin(position)]] position : vec4<f32>;
};

var<private> outputs : VertexOutput;

[[stage(vertex)]]
fn main() -> void {
  outputs.position = vec4<f32>(1.0, 1.0, 1.0, 0.0);
}
```

**Sample 2**
Module-scope private variable, type is a struct with pipeline input attributes.
Potential confusion: looks like this is reading from a pipeline input, but it isn't.
```
struct FragmentInput {
  [[builtin(sample_index)]] index : u32;
  [[location(0)] color : f32;
};

var<private> inputs : FragmentInput;

[[stage(fragment)]]
fn main() -> void {
  const idx = inputs.index;
  const col = inputs.color;
}
```

**Sample 3**
Non entry point function with entry point IO struct parameter, called by multiple entry points.
Seems potentially useful, with low possibility of confusion.
```
struct Input {
  [[location(0)]] value : float;
  [[location(1)]] mul : float;
};

fn foo(x : Input) -> f32 {
  return x.value * x.mul;
}

[[stage(fragment)]]
fn frag_main1(s : Input) -> f32 {
 var x : f32 = foo(s);
 ...
}

[[stage(fragment)]]
fn frag_main2(s : Input) -> f32 {
  var x : f32 = foo(s);
  ...
}
```

**Sample 4**
Non entry point function with entry point IO struct return value, called by multiple entry points.
Seems potentially useful, with low possibility of confusion.
```
struct Output {
  [[location(0)]] col1 : f32;
  [[location(1)]] col2 : f32;
};

fn foo(x : f32) -> Output {
  var retval : Output;
  retval.col1 = ...
  retval.col2 = ...
  return retval;
}

[[stage(vertex)]]
fn vert_main1() -> Output {
  return foo(1.0);
}

[[stage(vertex)]]
fn vert_main2() -> Output {
  return foo(2.0);
}
```

**Sample 5**
Module-scope private variable, type is a struct with pipeline input attributes.
Variable is assigned from entry point, and read by multiple user-defined functions.
Seems potentially useful.
```
struct FragmentInput {
  [[location(0)]] col1 : f32;
  [[location(1)]] col2 : f32;
};

var<private> inputs : FragmentInput;

fn foo() -> f32 {
  return inputs.col1 * 0.5;
}

fn bar() -> f32 {
  return inputs.col2 * 2.0;
}

[[stage(fragment)]]
fn frag_main1(x : Input) -> f32 {
 inputs = x;
 var r : f32 = foo();
 var g : f32 = bar();
 ...
}
```

On balance, we feel that the usefulness of allowing Samples 3, 4, and 5 outweighs the potential confusion caused by allowing Samples 1 and 2, and so we are proposing that WGSL should _not_ restrict entry point IO structures from being used in non entry point functions.

**Comment by dneto0** [comment]
Discussed in meeting of [2021-03-29](https://docs.google.com/document/d/173UCbLQC0kUESMaZ-1dB8jZQdglRWSGy98pJXWdakHE/edit#heading=h.rfn35q9cjmbl)

**Comment by dneto0** [comment]
Consensus is to not add any restrictions to the spec.

Perhaps a note could be added to indicate that IO locations and builtins do not have meaning in any context other than when considered as entry point arguments or return values.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-03-29-(Monday!)-Minutes#restrict-where-entry-point-io-types-can-be-used-1526">WGSL meeting minutes 2021-03-29</a></summary>

*   JP: We looked at a bunch of cases, concluded the best spot is to not restrict; ignore the locationIO/builtin when not used in that context.
*   MM: Sounds good.
*   DM: Feel like we should forbid structs from being host-sharable and for input/output
*   AB: Argument against that is we have default layouts to apply to host-shared.
*   BC: Rule is simple: interpret the annotation only when used in a meaningful context. 
*   MM: Consider comparing a type between a uniform and an input. In order to assign them, they need to be actually the same type.
*   DM: Ok that’s compelling
*   AB: Can’t actually do == on struct.
*   MM: Sure… will propose.
*   KN: can’t do == on struct in C++, unless you overload the equality operator.
*   MM: Ah, you’re right.
*   GR: Confirm HLSL can’t do == on structs.
*   [https://github.com/gpuweb/gpuweb/issues/1572](https://github.com/gpuweb/gpuweb/issues/1572) re equality on structs
</details>
