### ISSUE TITLE
when does applying an attribute to a type result in a different type

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1534]
It's unclear whether applying an attribute to a type forms a different type.

Example:
- stride on array type A vs. unstrided array type A
- stride(16) on array type A vs. stride(32) on array type A
     - as a clarifier, certainly     ptr<storage, [[stride(16)]] A>  should be different from ptr<storage, [[stride(32)]] A>  because address calculations are different for the two kinds of pointers
- access control for buffers.  Currently we put [[access(read_write)]] on the *type* side of the buffer variable declaration.
- access control for storage textures. Again, we put [[access(read)]] as decorating the type.

**Comment by alan-baker** [comment]
I think access control is simply in the wrong place. Is it too late to change that?

**Comment by kvark** [comment]
@dneto0
Let's say that these attributes are a part of the type, at least for MVP, since it's a more restricted approach.
Any issues you foresee with this?

@alan-baker 
It may equally be equally argued that the array stride is simply in the wrong place - see #1502

**Comment by dneto0** [comment]
> Let's say that these attributes are a part of the type, at least for MVP, since it's a more restricted approach.
Any issues you foresee with this?

I think we can't switch tracks after the fact because it probably breaks backward compatibility.  So I think we need  a more thorough resolution before we hit MVP.

For example, assignment will say something like "the type of the RHS must be the same as the store type of the LHS".  Where "the same" is identity, modulo aliases (probably).   I don't want to end up with a fuzzy concept of "matching" types.

We may end up with different answers for different attributes. But that needs investigation.

**Comment by dneto0** [comment]
In passing, Go's definition of a 'type' is amazingly clear and parsimonious:

> A type determines a set of values together with operations and methods specific to those values. 

https://golang.org/ref/spec#Types

I wish I had written that.

Right now WGSL has:

> Programs calculate values. Each value in WGSL belongs to exactly one type. A type is a set of (mathematical) values.

That misses the fact that a type _determines set of associated operations and methods_ for a value.   That goes to the heart of why I think the access attribute on storage types is _intrinsically part of the type_, not an adornment.  The _only_ thing you can do with a storage texture is to _call a builtin function_ on it, which is 100% determined by "the type".
(I'm recycling my previous arguments somewhat, but with new reference to existing art, and maybe phrasing it better.)

**Comment by kvark** [comment]
> I think we can't switch tracks after the fact because it probably breaks backward compatibility.

Could you elaborate please? If we consider the 2 types (which happen to be the same type with different attributes) to be incompatible today, but the change our minds, I don't see how this would break compatibility.

**Comment by alan-baker** [comment]
>It may equally be equally argued that the array stride is simply in the wrong place - see #1502

I'm not sure why the stride of an array is relevant to whether or not the memory backing a variable is able to read/written. What is the property of a type that prevents it from being written? Is this due to textures? 

Separately, if attributes make a different type then the following is shader is illegal. That may be ok, but it has an odd "smell".

```
struct Data {
  // ...
};

struct Output {
  arr : array<Data>;
};

[[group(0), binding(0)]] var<storage> in : [[access(read)]] Data;
[[group(0), binding(1)]] var<storage> out : [[access(read_write)]] Output;

[[constant_id(0)]] const x_size : u32 = 1;

[[stage(compute)]] [[workgroup_size(x_size, 1, 1)]]
fn amplify([[builtin(global_invocation_id)]] gid : vec3<u32>) -> void {
  // This is invalid as the two Data types are not the same.
  // Instead users would have to do a manual member-wise copy.
  out[gid.x] = in;
}
```

**Comment by dneto0** [comment]
The access attribute has been removed. 

Looking at https://gpuweb.github.io/gpuweb/wgsl/#attributes , the only cases are `block` (on struct) and `stride` on arrays.
Structs are always named, so structure types are already distinguished by name.

So all that remains is the stride on array:

Example copied from above:
- stride on array type A vs. unstrided array type A
- stride(16) on array type A vs. stride(32) on array type A
     - as a clarifier, certainly     ptr<storage, [[stride(16)]] A>  should be different from ptr<storage, [[stride(32)]] A>  because address calculations are different for the two kinds of pointers

**Comment by ben-clayton** [comment]
I'm sure this has been suggested before, but I have to ask - would it make more sense for us to fold the `[[stride]]` into the array declaration?

```
array<T> - runtime sized array of type T
array<T, N> - array of size N of type T, with inferred stride
array<S, T, N> - array of size N of type T, with explicit stride of S
```

The most icky aspect of this is that we'd likely want `array<T, N>` and `array<S, T, N>` to resolve to the same type if `S` were the implicit stride - but it certainly cleans up all the ambiguity of where we can put the `[[stride]]` decoration.

**Comment by kvark** [comment]
How would you declare an unsized array with explict stride then? :)

**Comment by ben-clayton** [comment]
> How would you declare an unsized array with explicit stride then? :)

`array<S, T>`

**Comment by kvark** [comment]
It's very weird to have the first parameter of an array being the stride, given that it's the last thing people generally think about when declaring an array.

**Comment by dneto0** [comment]
We've had a pattern where optional things only go on the end.
Maybe this is a good place for named-parameters.

array<T> - runtime sized array
array<T,N> - fixed-size array
array<T,stride=4> runtime sized array with stride
array<T,N,stride=8> fixed-size array with stride

And the rule proposed in #1943 would make an array type without explicit stride the same as an array type with explicit stride where the explicit stride equals what would have been the implicit element stride.

**Comment by dneto0** [comment]
... and I'd be fine with syntax other than the equals.

**Comment by kvark** [comment]
Yep, interestingly, just like #1480 this one requires novel syntax in order to be solved the best way.
I'm a bit worried that this would open up a can of worms (i.e. can we reorder parameters? can we mix named/unnamed? can users declare it?, etc), but overall would probably be fine if we agree on this.

@jimblandy any thoughts about named generic arguments for this? Maybe there is a solution we overlooked, which doesn't involve novel syntax.

**Comment by dneto0** [comment]
This is for writing down a type, so it's more constrained. The shader author can't make new cases of this: the "template" forms are baked into / enumerated by the WGSL spec.

Even then, Python keyword arguments are a useful precedent.  I'd say: keyword arguments are always at the end.  Everything else is as before.

**Comment by jrprice** [comment]
> Maybe there is a solution we overlooked, which doesn't involve novel syntax.

A solution that doesn't involve novel syntax would be to spell "array" and "runtime array" differently. They are different types after all, and (aside from brevity) there's no benefit to the shader author in having them spelled the same. There's nowhere that you can use them interchangeably for example, since the presence or absence of the array size means they are already spelled differently.

**Comment by ben-clayton** [comment]
> A solution that doesn't involve novel syntax would be to spell "array" and "runtime array" differently.

I like this. So something like:

```
array<T, N>
array<T, N, S>
rarray<T>
rarray<T, S>
```

Where `T` is element type, `N` is array length and `S` is array stride.

**Comment by kvark** [comment]
This sounds good to me, but please let's not call it "runtime array". It's a hell of confusing.
Let's look for a better name. Something like `unsized_array<T>`?

**Comment by ben-clayton** [comment]
A bit verbose, but works for me.

**Comment by dneto0** [comment]
The current terms are:
- "sized array"   (but #1792 proposes to rename this to "fixed-size array")
- "runtime-sized array".

I'm fine with `unsized_array`.  The group has preferred fully spelled out words over abbreviations.  It's good on that front.

My only quibble with 'unsized_array' is that it *has* a size but you just don't know it in the shader source.  The better way to think about it is that the shader source does not size it, so it is _unsized by the shader source_.  And that's close enough for me.  So +1 to `unsized_array`

And I think this is significantly better than using an attribute. Thanks @jrprice for the clear argument.

**Comment by kainino0x** [comment]
`dynamic_array`?

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-07-27-Minutes#when-does-applying-an-attribute-to-a-type-result-in-a-different-type-1534">WGSL meeting minutes 2021-07-27</a></summary>



* AB: Me and DN discussed this offline. We should leave the tooling cost of dealing with complexity, when you try to assign an array with one stride to an array with another stride. DN has a nice way of phrasing it, so if the load rule is invoked, you’re stripping the array stride. You’re loading it into registers, and that has no stride. If you’re doing an assignment, if that assigned thing ends up having a stride, then you convert the stride …???
* AB: So, the attribute doesn’t change the type. The user can write a helper function of an array of 16 uints that can be passed to 
* MM: If an author writes a function taking an array, as you described.  And call it twice, with two different strided arrays, doesn’t the function have to know the stride (to codgen)  and therefore you couldn’t write it generically over strides.
* AB: Values vs. memory views.  It matters only when the type is a pointer or ref.  
* AB: Within a function you could take the pointer to something, and access an element. But the compiler will know what the stride is
* AB: the implementation decides how to lay out workgroup memory. I have seen implementations that can support other features because there is no specified layout. So workgroup layout doesn’t have, the implementation will choose to stride things to make perf increase.
* DM: I thought we have a limit for WG storage size, and the user has to fit
* AB: But the compiler can fail anyway
* DM: Fun.
* AB: This came up in the discussion of pipeline creation spuriously fail
* JG: We might want to actually call this out in the spec. People will actually hit this.
* JG: An author will look at their max size, craft their shader so they’re within that limit, and assume that because they’re under the limit, it will work.
* AB: The API already has a limit on workgroup storage used, right?
* JG: Ok.
* DM: I’m fine with this. IIRC right now, the tooling doesn’t need work for this. In the future, we’ll carry around the stride as data inside the pointer.
* AB: Right now the tooling needs to know whether it can do an element-wise pointer. Say, in SPIR-V, I could OpCopyLogical between two different arrays of different strides. Or I could do it element-wise. In other APIs, I could use memcpy() or something like that.
* DN: This is a pretty tough discussion to have. I would probably want to write a speculative PR. In our discussion offline, AB reversed my leaning. It’s subtle
* AB: DN came up with good spec language
* MM: It seems like a layering violation for a pointer to hold the stride instead of an array
* JG: We’re not even there yet. You can’t even hit this problem in the first place just yet.
* AB: SPIR-V does it this way because it wants to support getElementPtr. The first index in getelementptr acts like an array index, but you don’t have the array in hand.  But the address calculation needs to know the stride to multiply that index by to get the address offset.  It’s purely a representational issue.
* KN: My understanding was that array strides would be attached to the type, and they would only apply if you used them in certain ways. Sure you could have a pointer to an array, but what if you have a typedef of an array, or a struct containing an array? Is this disallowed?
* AB: You can put it on an array element. It only applies in a small subset of places.
* DN: I’d like to stop this conversation and have a written thing before we go further. What Kai just raised and what Myles raised will be written down.
* JG: Okay.
* ACTION: DN to write proposed spec text.


</details>
