### ISSUE TITLE
Specify what happens to mappings when the buffer is GCed.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1544]
Right not the spec doesn't have any text to explain what happens to a buffer's mappings when the buffer is GCed. Because the GC is unobservable, the mappings should not change but that's not written down.

**Comment by kvark** [comment]
Another question is what happens to mapped buffers. Are `ArrayBuffer` objects getting detached (i.e. implicitly unmapped) on GC sweep? This would potentially be observable by the user.

**Comment by Kangz** [comment]
Oh yeah that was for mapped buffers. I think we already agreed it shouldn't be visible but we need to put it in the spec somehow.

**Comment by kvark** [comment]
How is this not going to be visible? Anything we do by the time the buffer is GC-ed is a way to expose GC. And if we don't do anything, we can't properly unmap this buffer...

**Comment by austinEng** [comment]
There may be at least two options here: 
 1. An `ArrayBuffer` keeps its backing store from a mapped `GPUBuffer` alive. Note: this doesn't have to keep the `GPUBuffer` JS wrapper object alive - it just needs to not detach the backing store. I don't know how other JS engines work, but in Chrome we can attach a finalizer to the ArrayBuffer "contents" which would release a reference to the mapped allocation.
 2. We spec this in terms of JS [WeakRefs](https://github.com/tc39/proposal-weakrefs) though that is still a proposal, now in stage 4. From what I understand, this does make GC observable, but it tries to make things less fragile because WeakRefs aren't detached within a task. I don't see the need to use weak refs here though. The README seems to say the intended use is for caches or to avoid excess memory growth. Buffer mapping is not a cache, and for memory management we have `GPUBuffer.destroy`.

**Comment by kvark** [comment]
For (1), we also have a finalizer - https://searchfox.org/mozilla-central/rev/be906232eedb22c064b78f3806b38964c04f1fbc/js/src/vm/ArrayBufferObject.cpp#923 , so in theory it would be ok.

**Comment by kainino0x** [comment]
I think the spec should just say the ArrayBuffer keeps the `[=buffer=]` alive (option 1).

**Comment by kainino0x** [comment]
Resolution: The buffer can never be used again after this (will stay in the mapped state forever), so all we need to make sure is the ArrayBuffer's state and contents don't change due to GC, it doesn't matter how we achieve this. Myles says it works in WebKit, AI for Chromium to make sure it works for us and doesn't have a perf impact (cc @austinEng)

**Comment by Kangz** [comment]
I just implemented that logic in Chromium and the perf impact looks minimal. (just an extra allocation and ref/release calls).
