### ISSUE TITLE
What is the toDataURL behavior for GPUCanvasContext?

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#1548]
WebGL does this:
1. If there has been a draw call to the drawing buffer since last Present, snapshot the current contents of the drawing buffer.
2. Otherwise, snapshot the contents of the most-recently-Presented frame.

In a sense, toDataURL gives the contents that the page can expect to see next frame, if no other calls are made before next Present.

WebGPU absolutely wants number 2, but while WebGL just has a built-in default framebuffer, WebGPU has more parts: `GPUCanvasContext`, `GPUSwapChain`, and `GPUTexture getCurrentTexture()`.

I suppose a potential solution would be:
1. If there has been a call to getCurrentTexture() since last Present, snapshot the current contents of getCurrentTexture.
2. Otherwise, snapshot the contents of the most-recently-Presented frame.

This came up in the context of #1474 where we want to also know, for alphaMode:opaque, when/whether we're requiring that toDataURL clears alpha to 1.0.

@kenrussell @RafaelCintron 

[edit -KN] Related discussion: https://github.com/gpuweb/gpuweb/pull/1408#discussion_r570394799

**Comment by kenrussell** [comment]
One question is whether, if WebGPU is rendering to a real swap chain on Windows, whether the contents of that swap chain can be recovered after the fact. I think the answer is no.

If that's the case then WebGPU might be in the same situation as WebGL of needing a `preserveDrawingBuffer` flag on the swap chain in order to make `toDataURL` work predictably. Setting that to `true` would necessarily incur a full-canvas blit at the end of each frame.

There are other web APIs that need the canvas's contents after the fact, like canvas capture to MediaStream. Both Chrome and Safari currently silently "upgrade" WebGL-rendered canvases to `preserveDrawingBuffer:true` behind the scenes when capturing such canvases, because otherwise depending on when the browser's compositor runs, the rendering results are no longer accessible and the result is flickering to black in the captured stream.

**Comment by RafaelCintron** [comment]
For Windows, you can readback the contents of previous swap chain buffers if you use sequential swap chains. The documentation for the [DXGI_SWAP_EFFECT](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/ne-dxgi-dxgi_swap_effect) and [IDXGISwapChain::GetBuffer](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgiswapchain-getbuffer) has additional details. 

Here is an excerpt from the latter doc:
> If the swap chain's swap effect is either DXGI_SWAP_EFFECT_SEQUENTIAL or DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL, only the swap chain's zero-index buffer can be read from and written to. The swap chain's buffers with indexes greater than zero can only be read from; so if you call the IDXGIResource::GetUsage method for such buffers, they have the DXGI_USAGE_READ_ONLY flag set.

**Comment by kenrussell** [comment]
Thanks Rafael for the information. Is there a performance cost associated with using `DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL` instead of `DXGI_SWAP_EFFECT_FLIP_DISCARD` in D3D12?

More concretely, would you feel comfortable with using `DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL` all the time in WebGPU implementations on Windows? If not, then we need to consider specification-level changes for WebGPU.

**Comment by RafaelCintron** [comment]
@kenrussell, the first article I linked to discusses the tradeoffs between the two enums.  Here's what it has to say: 

> The difference between DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL and DXGI_SWAP_EFFECT_FLIP_DISCARD is that DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL forces DXGI to guarantee that the contents of each back buffer is preserved across IDXGISwapChain::Present calls, whereas DXGI_SWAP_EFFECT_FLIP_DISCARD doesn't provide this guarantee. The compositor, under certain scenarios, can use DirectFlip, where it uses the application's back buffer as the entire display back buffer, which elides the cost of copying the application's back buffer into the final desktop back buffer. With DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL and DXGI_SWAP_EFFECT_FLIP_DISCARD, this optimization can occur when the application is the only item visible on the screen. However, even when the application is not the only visible item on the screen, if the flip model is DXGI_SWAP_EFFECT_FLIP_DISCARD, the compositor can in some scenarios still perform this optimization, by drawing other content onto the application's back buffer.

In summary, yes "discard" swap chains can light up some optimizations but, in general, the differences are relatively minor.  

Having `toDataUrl` work anytime seems desirable so I don't think we have any other choice but to use "sequential" swapchains.

**Comment by kenrussell** [comment]
Great. Let's investigate whether the Vulkan and Metal APIs on top of which WebGPU's swap chains will be implemented can offer the same semantic. If they do, then WebGPU won't need WebGL's `preserveDrawingBuffer` toggle at all.

**Comment by kainino0x** [comment]
It has been a long time since I investigated this, but in conversations I had with @sunnyps a few years ago, I think we concluded that Chromium should never use DXGI swap chains for WebGPU canvases. IIRC they are really most useful for video, and there are more flexible ways to get access to overlays/underlays.

**Comment by sunnyps** [comment]
Chrome uses DXGI swap chains for "low latency" (desynchronized: true) webgl canvases.  As Rafael suggested, we copy from the swap chain's front buffer to its back buffer to implement preserveDrawingBuffer semantics.  We could do the same for webgpu - copy from front buffer to an intermediate texture, but only when toDataUrl is called instead of every present.  All this assumes using DXGI swap chains for webgpu canvases which is not the case right now.

Also, there are benefits to using swap chains other than hardware overlays - we can decouple rendering to the canvas swap chain from rendering rest of the page and get lower latency - the "desynchronized" context attribute is an explicit signal from the client page that it's ok to do so.

**Comment by kainino0x** [comment]
Ah yes, thanks Sunny! I totally forgot that we can (and can only) use them for `desynchronized: true` `<canvas>`es (and, I think, `OffscreenCanvas`es from `transferControlToOffscreen`).

**Comment by jdashg** [comment]
I was wrong about current behavior in WebGL, but now I wonder what part I was misremembering from!
Example: https://jsfiddle.net/kjsygxbm/

**Comment by kainino0x** [comment]
Added a link to https://github.com/gpuweb/gpuweb/pull/1408#discussion_r570394799 in the issue summary.

**Comment by kainino0x** [comment]
I have a sketch of a proposal that covers this and all other cases of using a webgpu canvas as a source (shared with @toji). I should file it.

**Comment by kainino0x** [comment]
I've filed #1781 as a proposal to address this.
