### ISSUE TITLE
Consider having rich math rendering in the spec

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1573]
@kainino0x mentioned https://katex.org/
It could be very helpful to display the equations of #1564

**Comment by dneto0** [comment]
I'm all in for TeX math markup.  But it must be fast fast fast.

**Comment by Kangz** [comment]
Got burnt with the Vulkan spec ? :) Maybe the TeX markup could be processed at build time. KaTeX seems to support that.

**Comment by jdashg** [comment]
Honestly I prefer plain text for these, since plain text is better for copy/paste, comments, and otherwise remixing and referencing.
When I'm transcribing GL spec details into comments in our implementation code, there's friction and ambiguity because I can't transcribe e.g. level-sub-base directly. It's pretty, but struggles during translation and reuse in non-rich-math contexts.

For complicated equations, I feel we're better off using our field's lingua franca, which is (pseudo)code, not math notation.

Text is also nicely wysiwyg.

**Comment by litherum** [comment]
Why not MathML?

**Comment by kainino0x** [comment]
MathML is not a particularly authorable format, so we would probably need something else on top of it, and afaik Chromium still doesn't support it.

**Comment by Kangz** [comment]
@mehmetoguzderin I think you did this already and that this issue can be closed right?

**Comment by mehmetoguzderin** [comment]
@Kangz We've fixed some typos in the display of mathematical expressions, but we can close this issue because there are not many outstanding equations for such reformatting.
