### ISSUE TITLE
Need a proposal for specialization constants on the API side.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1608]
WGSL has some support for specialization constants but the WebGPU API doesn't allow setting them at all so they are unusable. We should have an investigation of how specialization constants work in D3D12, Metal and Vulkan and a proposal for what it should be in WebGPU.

**Comment by alan-baker** [comment]
I can take a look at this.

**Comment by alan-baker** [comment]
# Proposal

Add the specification of overridable constants to GPUProgrammableStage. The new member should be a dictionary mapping the constant id to a pair of type enum (“bool”, “sint”, “uint”, or “float”) and value (specified as a double, boolean values use 0 for false and non-zero for true). It is an error if the entry point statically uses a pipeline overridable constant without an initializer and the value is not specified in the dictionary. Otherwise, specifying the values for pipeline overridable constants is optional.

```
dictionary GPUProgrammableStage {
  required GPUShaderModule module;
  required USVString entry;
  sequence<ShaderConstant> constants = [];
};

enum ShaderConstantType {
  "bool",
  "float",
  "sint",
  "uint"
};

dictionary ShaderConstants {
  required unsigned int id;
  required double value;
  required ShaderConstantType type;
};
```

A potentially simpler interface would avoid the type requirement and effectively require implementations to get that data via reflection. The reflection requirement may be annoying for native versions of the API, but I don't see much of a drawback for the web.

```dictionary GPUProgrammableStage {
  required GPUShaderModule module;
  required USVString entry;
  sequence<GPUShaderConstant> constants = [];
};

dictionary GPUShaderConstant {
  required unsigned int id;
  required double value;
};
```

# Survey

WGSL exposes pipeline overridable constants for values that are specified at pipeline creation time. They must be a scalar value (f32, i32, u32, or bool) and are associated with an id assigned by the shader author.

WebGPU needs a way to specify the values of these constants in a way that is compatible with underlying implementations.

## Vulkan

Vulkan specifies specialization constant values at pipeline creation time. Specialization constants are specified per shader in the `VkPipelineShaderStageCreateInfo` through the use of a `VkSpecializationInfo` structure. The specialization info consists of two lists, one specifying the constants’ ids, sizes and offsets into the other list, and the other specifying the data values for those constants as raw bytes.


## Metal
Metal specifies the value of function constants when creating the `MTLFunction` using a `MTLFunctionConstantValues` object. To specify the constant values, the API must be provided with the id, type and value for the constant.

A single `MTLFunctionConstantValues` object can be reused (and, optionally, reset) for multiple `MTLFunctions`.


## D3D

D3D does not expose the concept of pipeline overridable constants. WebGPU implementations will have to instead defer generating finalized shader sources until the values are provided. If an implementation is generating HLSL shaders, the generated shaders can use defines to set the values for constants and specify the correct values for the defines to the compiler. If an implementation generates DXIL, it could generate uninitialized global variables to hold the constants and patch the initializers once the values are known. One caveat would be that workgroup size is specified in DXIL via metadata. Implementations should avoid optimizing the shader module until the values are available if the workgroup size is overridable to avoid optimizing on the value that is later overridden.

**Comment by kainino0x** [comment]
Meeting resolutions:
- No type
- Discuss in WGSL group: should specialization constants be identified by name instead of by numeric ID?
- TBD represent as something like `record<USVString, GPUShaderConstant>`?

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-20-Minutes#need-a-proposal-for-specialization-constants-on-the-api-side-1608">WGSL meeting minutes 2021-04-20</a></summary>



*   [Discuss in WGSL group: should specialization constants be identified by name instead of by numeric ID?]
*   MM: Because these are per-entrypoint, the compiler can generate ids e.g. for spir-v.
*   DN: Concern: Both MTL and spir-v, spec-consts are identified by id not names, so we’d be moving away from prior art. Worried that e.g. and engine will then need to adapt to names instead of spec-const-ids. When round-tripping between shading langs, we’d need to preserve the mappings too.
*   DM: Moving away from prior art as undesirable is convincing to me
*   MM: Metal supports both ids and idents
    *   [https://developer.apple.com/documentation/metal/mtlfunctionconstantvalues?language=objc](https://developer.apple.com/documentation/metal/mtlfunctionconstantvalues?language=objc)
*   MM: Argument for using strings: JS gets more readable, don’t have some arbitrary number.
*   JG: Do we want both then?
*   DN: I want to talk to customers about it, see how they feel about it.
*   MM: I could see a language translator being able to provide the mapping it uses
*   DN: Yeah, though translator isn’t being used in isolation, but rather within context of an engine.
*   MM: Let’s continue next week.


</details>

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-27-Minutes#need-a-proposal-for-specialization-constants-on-the-api-side-1608">WGSL meeting minutes 2021-04-27</a></summary>



*   DN: Proposal from email:
    *   In writing the above, there may be a path to "why not both", if we want it.
    *   Thinking out loud, here's an example:
    *   
    *   [[override]] let loopIteraitons: i32;                    // Must be set by name "loopIterations"  in the API
    *   [[override(foobar)]] let myMangledName: i32; // Must be set by name "foobar" in the API
    *   [[override_id(0)]]    let blockSize: i32 ;             // May be set by ID 0 in the API, or by name "blockSize”
*   MM: If porting, probably use ints, if writing WGSL, probably want strings. Three different ways, I think they’re good and have value.
*   DM: Proposing allowing both? (either) Can we have less of design by committee and just pick one?
*   KN: This is what metal uses, right?
*   MM: Yes, though they all have ints, you just don’t have to use the int instead of the str
*   AB: Is there strong reason to allow renaming?
*   MM: A weaker one is that it’s an optional level of indirection.
*   AB: Already have indirection with ints?
*   MM: Yes, but the weak reason is that if you have a typo your shader is less likely to run.
*   JG: Describe typo?
*   MM: If you use e.g. 3 instead of 4 will run, but be wrong. Rather, “Myless” will more reliably be an error earlier.
*   JB: Similar to function args by position vs by name?
*   AB: But why allow renaming?
*   MM: We can compromise and drop `override(foobar)` for now
*   DM: Converging on just `[[override]]` and `[[override_id(n)]]`
*   KN: So we get a record where the key can either be the name or the number?
*   MM: Can the key be a non-string?
*   KN: JS record keys have to be strings. What this means is that `override_id(3)` is really a key of str(‘3’) anyways.
*   AB: let’s use [[override]] and [[override(0)]] (rather than [[override_id(0)]])
*   Everyone: ok


</details>
