### ISSUE TITLE
Should "mark adapters stale" be called more quickly?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1630]
In today's meeting discussion about #1523, @jdarpinian expressed concern that an arbitrary timeout on `adapter.[[current]]` could result in flaky applications. In particular, even though this looks similar to real device loss (`device.lost` resolves), device loss during device creation logic might not be handled as well as device loss at other times, e.g. if `.lost` resolves before they've finished doing some necessary setup logic (this would be a badly formed application, but it's also very hard to enforce applications don't do this).

James's suggestion was that adapters be marked stale very quickly, e.g. at the end of the frame, or at the end of the task/microtask. I seriously considered this design for a while before proposing the current API, and was concerned that it could be too limiting for applications that need to do other async work near requestAdapters. On the other hand, it would be safer to start out super strict, then get laxer based on user feedback.

See also #1629, which also reduces fragility here.

**Comment by kvark** [comment]
I find this unreasonably strict. For example, what if my application shows a boot menu and lists the available ways to run something: (1) would be WebGPU with adapter XXX, and (2) would be WebGL with adapter YY, and (3) would be WASM. Then this adapter name would either be deprecated every frame, or I would need to call `requestAdapter` each frame.

**Comment by kainino0x** [comment]
Perhaps we can say the browser "shouldn't" mark the adapter stale before a first device has been created from it.

**Comment by kvark** [comment]
@jdarpinian right, and I thought we are going to have an event like "adapterschanged" that would allow applications to react to this.

**Comment by jdarpinian** [comment]
Invalidating the adapter guarantees that all applications will be able to handle adapters becoming invalid, while an optional event doesn't. It is better for the exceptional case to work the same way as the common case.

**Comment by kvark** [comment]
If an application wants to keep an adapter for some time, I don't find it great that it would have to re-request the adapter each frame. Seems rather silly, doesn't it?

**Comment by jdarpinian** [comment]
You only need to request an adapter in frames where you create a device, which is hopefully not every frame.

I think this depends on whether we think the adapter object will grow more functionality, and how adapters are requested in the first place. In the current state of the spec honestly having requestDevice on the adapter object is not necessary. It would make more sense to have just have requestDevice on the gpu object which takes the adapter options too. requestDevice on the adapter object only makes sense if are going to have a list of adapters like in #1314. What's the status of that discussion?

**Comment by kainino0x** [comment]
Adapters are also how we expose the actual available features/limits, since we enforce requested features/limits strictly on the device.

**Comment by jdarpinian** [comment]
Sure, adapter objects would still hold the limits and features. You'd pass the same adapter options to requestAdapter and requestDevice. If you called requestDevice immediately after requestAdapter returns, with the same adapter options, you'd be guaranteed that the device would use that adapter. But if you called requestDevice later on a different frame, you wouldn't be guaranteed that the adapter is still available and might get a different one.

**Comment by kainino0x** [comment]
@toji and I discussed this, and came to a recommendation (thanks Brandon!). It took me a bit to finish writing this up, so hopefully I remembered all the stuff we discussed.

Proposal: simply expire the adapter object when you call requestDevice on it. It should still be possible to implement adapter pickers with this API, and in fact the adapter pickers will be more robust by default because they won't be writing special paths for recovering from adapters expiring while they're being picked.

- Since we don't have requestAdapters, there are a fixed number of possible adapter requests an app can make. Right now, there are essentially 4: default, high-performance, low-power, and forceFallbackAdapter.
- Any type of dialog showing a list of adapters would be aspirational in showing the adapter details anyway. Not all browsers will implement any adapter info, so the only thing they can rely on knowing is the GPURequestAdapterOptions. Any info from requestAdapterInfo will get out of date in rare situations, but could be kept up to date when we have an adapters-changed event.
- If no device is created from an adapter, the spec would never normatively expire it unless it actually becomes unavailable. This is fine because, worst case, we return a lost device and the application goes to recovery.
- It prevents applications from creating multiple devices from one adapter, but they can just requestAdapter once for each device they want. There isn't really anything meaningful you can do by forcing two devices to be on the same adapter.

We also considered having the adapter expire "immediately" just like canvas and external textures (#3295, #3324), but this was in conflict with requestAdapterInfo, which is async, so using it would introduce asynchrony between getting an adapter and calling requestDevice on it. We could extend the lifetime when you use requestAdapterInfo, but that gets complicated, and we didn't find any reason this was better than expiring on requestDevice.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-meeting-2022-11-09-10-apac-timed#should-mark-adapters-stale-be-called-more-quickly-1630">GPU Web meeting 2022-11-09/10 APAC-timed</a></summary>

* KN: Other one which Brandon and I discussed Monday. Thought through device creation cases. Gist: want to steer developers toward, when they need a new device, request an adapter first and create a device from it. Gives browser opportunity to select the best adapter. Right now the spec says, adapters may expire whenever, and browsers should do it often. But we couldn't find a case where you needed to be able to hold onto an adapter for a long time.
* KN: each adapter object will be one-time use. Create one device from it. If you don't do that, browser won't necessarily do anything with the adapter object (it can stay alive, or not). Unusual for an app to fetch an adapter and use it 3 days later. If that fails, should trigger retry logic in the app. We think this simple API, making the adapters one-shot, is best.
* BJ: little more context. Imp't: how this interacts with getAdapterInfo. Should we expire adapters with same cadence as canvas textures? At end of task? Discussed use cases. Developers, if they want to look at the adapter info for workarounds - that's potentially a long-running Promise. Browser UI may pop up dialogs, get user consent. Would need exception to expiration there. It got messy fast, and didn't seem to give much benefit - if you can postpone expiration by calling getAdapterInfo, would be awful, and developers might start doing it. Can achieve the result by making it one-shot for creating the device. Giving you a drop-down to select an adapter - would make that more practical, too, since the adapters would be kept alive until you did something with them.
* KR: any reason to have a close() or similar on GPUAdapter? To release GPU resources?
* Discussion.
* KN: don't think that being able to close the adapter would make that meaningfully easier - e.g. closing graphics drivers.
* KG: not sure it's a good idea to make it more difficult to create multiple GPUDevices against the same GPUAdapter.
* KN: agree, makes you pause. Think we should address needs for specific adapters to be "I need the adapter you give me to be compatible with this XR device." Use-case driven. When we find cases where this'll be useful, can make them work.
* KG: what pushed us in the direction to make adapters expire? To make people do the right thing?
* KN: when an app's reinitializing, we want to make sure they let the browser select an adapter at a recent point. If you get an adapter and write some code - if device is lost and you try again on the same adapter - OK if you ran out of memory, etc. But if the adapter was unplugged from the system - your recovery logic won't work. People should always request an adapter when you create a device.
* KG: need to think about this more.

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-meeting-2022-11-16-non-apac-timed#should-mark-adapters-stale-be-called-more-quickly-1630">GPU Web meeting 2022-11-16 non-APAC-timed</a></summary>

* KG: last proposal - adapters would go invalid immediately after requesting device from them.
* KN: yes. Idea - it's a one-use object. Thinking more - one use case where this could cause problems - relying on requestDevice to reject in order to test for capabilities, instead of testing what adapter exposes. Not an invalid use pattern right now - trying again over and over with different options. Have to get new adapter each time, which you can do.
* KN: think this is fine. People will do one of those things, will only take them 10 minutes to add another requestAdapter or similar; don't need to make that use case work.
* KG: worry that tradeoff of expiring adapters early isn't worth it. Reason why to do it - so people don't have the device explode, and go back to the adapter and make another device, and it'll work some of the time.
* KN: that's correct.
* KR: honestly we're seeing more customer use cases (in WebGL) with eGPUs and customers unplugging them. Think we should avoid race conditions by treating adapters as a one-use token.
* KG: maybe be able to ask devices, what adapter was this device? Different than, save the adapter & use it later.
* KN: we could add something to requestAdapter, "give me the same one as this other one."
* KG: don't like that design generally. Would rather expose the right primitives. Suppose I'm satisfied with asking the device for its adapter.
* KN: can also change it in the future so adapters live longer.
* KG: I'm satisfied if we do that.
* **Consensus:**
    * **After successful requestDevice…**
* KG: then wouldn't want people to make multiple devices and choose the one which succeeded.
* KN: not easy to see whether a device request succeeded. You'll get a Device object regardless, have to check if it's lost.
* BJ: maybe should be one-shot. Failure reasons during creating device: (1) bad parameters (like invalid limit), or (2) legitimate "something happened while making the request".
* KG: then we don't have adapters, we have one-shot device factories.
* KN: yes, they tell you what the adapter can do, and also create one.
* BJ: there's nothing you can do uniquely with multiple devices all pointing to the same adapter. Multiple canvases - better to have single device. When we get to multithreading - you'll want different interfaces for same device, but won't be handled at the adapter level.
* KG: only problematic use case - app wanting to configure based on adapter's functionality. Made some request to requestAdapters, and to get more devices, would have to replicate those requests. Might tell them, you should base this on per-adapter limits. Imagine something running compute, want to be able to use multiple devices - and use the same non-GPU structures / precomputed data across different devices.
* KG: easier sell - in disabling adapters immediately after requestDevice, also adding "getAdapter" to devices. Then I have no more concerns. If you want to make things based on that adapter, have to hold onto the device.
* KN: don't want people writing that code path. They'll already need the code path for requesting adapter, then device. Now writing new logic to get back the adapter from the device, and they'll still have to fall back.
* KG: value is shared constraints in the common system.
* KN: reality is you might end up with a different adapter. App will have to handle this. Precomputation will have to be invalidatable.
* KG: something like WebCuda factory, wants to bring up devices quickly, based on the same adapter. Ability to know certain limits ahead of time is valuable.
* KN: think they should detect that based on adapter parameters, rather than the object. They'll put together some structure of data - the best parameters they can do on that adapter - if they come up with a different result, they can recompute stuff.
* BJ: if this is about limits - would it make more sense to have something in adapter requests, supports the same limits as this device over here? Gives you back adapter if it can.
* KG: worry that we keep adding on new fixup APIs if we let people hold onto adapters. Penalty for holding onto adapters - we have device and adapter loss, and people may assume device loss when it's really adapter loss.
* KN: right now spec says browser "should" expire the adapter after long enough. Idea - enforce developers to get new adapter rather than using the same one. Already can't do this.
* KG: that's not intent I'd like to put into the spec. I would have voted against that.
* KN: discussed long ago, don't remember.
* KG: if intent were - requestAdapter, wait 3 hours/days, requestDevice - don't want to hold the adapter open.
* KN: I think we can make it feel more convenient, but you'll always need these fallback paths, so you should use them all the time and keep your code less complicated. Don't want separate convenient and robust code paths.
* KG: don't want to chip away at what's supported.
* KR: bit confused about the use case here. If you had a device and either it was lost or you wanted to get one that was identical to it, you wouldn’t be able to share any GPU objects across those devices anyway. So not sure what “structures / precomputed data” could be reused.
* KG: structures on the CPU.
* BJ: if my GPU supports workgroup sizes larger than the default for example. And I've made data structures larger than the default.
* KN: nothing about this proposal prevents apps from assuming they'll get the same adapter if they make the same request. Hopefully they check to make sure adapter they got is compatible with their precomputed data. Don't see how that's different from them assuming that they can keep using the adapter.
* KG: imagine you make a hardware change, adds a new adapter, which browser finds more preferential for a vanilla requestAdapter call. Keep calling that and we start giving you back an adapter with different limits/features - there's no way for the API to tell you, I wanted that other adapter you gave me before.
* KN: true. If app wants to assume it runs on a single adapter, it'll break more often. But not that much more often. Converse case: eGPU already plugged in when they started, and it got unplugged. Now they get different limits. Original adapter's gone. Have made the problem 2x as bad. Point is - I don't see how they're not going to handle this, or accept the fact that the page has to be reloaded, regardless of which API design we choose.
* KG: feels like putting too many guardrails on something. Wonder if there isn't more solution space. If you get device loss, maybe you can't create new things on that adapter. But violates the thing I'm fighting for.
* KN: I think it doesn't make anything simpler.
* KG: worry about edge cases we're making impossible, and a couple of people will be upset.
* JB: is there a risk we'll produce something we can't fix later? Can add more sophistication selection if we get customer requests. Trying to predict the future's hard.
* KG: current shape of API - with browser reluctant to expire adapters - there's a class of things we don't want to worry about. Concern with that is people will expect people can recreate something on the same adapter when the device is lost. No way to reconcile these.
* KN: don't want to over-index on the idea that we can make it work later, but don't think we're blocking ourselves from doing it later, and would like to know what people decide they can't build with the more limited API.
* KG: we already have the thing that mirrors what native APIs do. Adding stricter guardrails than native APIs have.
* KN: we can leave the spec as is, or leave it as a UA decision. Would like Chrome to implement those guardrails. Would be enough to make people aware this is a problem and guide them in a correct direction, even if they reuse adapters.
* JB: would it be helpful if requestDevice didn't create a device if it fails, but rejects the Promise instead?
* KN: used to be able to return null. We can change it again.
* JB: would that clean this up?
* KG: don't think it affects the adapter part.
* KN: related, but not the core issue.
* KG: will think about this more - close to thinking whatever we do is fine.
* KN: if we get feedback, I'm happy to reconsider.
* KR: somewhat in favor of providing synthetic device loss facilities, and start narrow, by making adapters one-time tokens.
* KG: think in WebGL, context loss should be in core.
* KN: we do have device.destroy(). That's core. It's not quite the same thing as synthesizing device loss, but geared at cleaning up a context. Close to synthesizing device loss. Only real difference is whether it sets a flag on the device loss event - destroyed or closed. Also, it unmaps buffers.
* KG: loss doesn't?
* KN: yes.
* KG: reason we can't make these the same? What if device.destroy -> device.lose()? If you wanted to not restore it, would add expando property.
* KN: need to double-check. Reason destroy() closes maps is to clean up. We can't close maps on other threads when we have multithreading. Don't want device loss to unmap buffers, might break the app. Want that cleanup to be explicit. Intended pattern where you can watch for device loss. Then you unmap things if you can handle it. Maybe we should provide a way to synthesize device loss that isn't destroy(). Simple - maybe parameter to destroy(). Almost the same operation.
* KG: worth considering. If we have adapters which can stick around at all - maybe adapter loss should be something you can synthesize, too.
* KN: if we accept the proposal we're doing now, that wouldn't do much.
* KG: adapter.lose() could iterate through all devices it created and lose them too. That's what would happen if you remove the eGPU.
* KN: if we made them single-use that wouldn't work anymore.
* KG: maybe you can't use it to create devices, but can use it to destroy them. "close()" almost works well. Device might still be there, but we close the connection to it.
* KN: I'd think of "close" as "close this adapter handle without losing this device", but bikeshedding.

</details>

**Comment by kainino0x** [comment]
Was missing a needs-cts-issue tag, but now has a CTS issue: https://github.com/gpuweb/cts/issues/2380
