### ISSUE TITLE
Naming of vertex formats

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#164]
Currently the vertex format enum is a bit of a stub:

```
enum WebGPUVertexFormat {
    "floatR32G32B32A32",
    "floatR32G32B32",
    "floatR32G32",
    "floatR32"
    // TODO other vertex formats
};
```
Feedback we got internally is that first it is weird for vertex formats to use "RGBA" in their name instead of "XYZW". Also the names are very redundant. The suggestion is to use "Vec" + count + type + size + normalized giving names like `Vec4Float32`, `Vec4Uint8Norm`, `Vec2Int16Unorm` and (assume Vec1 is implicit) `Float32`, `Int8Norm`, etc.

Special vertex formats could use similar but longer naming: `Vec3Uint10Uint2` for the 32bit 10-10-10-2 unnormalized integer format.

**Comment by kvark** [comment]
Can we use the same enum for vertex and texture formats?

**Comment by Kangz** [comment]
We could though I personally dislike `DXGI_FORMAT` and `VkFormat` mixing both image and vertex formats:

 - It makes it less clear in the specs what is supported unconditionally for vertex and images
 - Normalized vs. unnormalized doesn't make sense for images
 - Compressed texture formats don't make sense for vertex formats

That's why I think they should be separate enums.

**Comment by magcius** [comment]
Why doesn't normalized vs. unnormalized make sense for images? Even *WebGL* has integer texture formats, e.g. GL_R8UI, which are greatly useful.

I don't like the Vec3Uint10Uint2 convention, since endianness and attribute ordering isn't clear -- is it A2R10G10B10, or A2B10G10R10, or R10G10B10A2, or B10G10R10A2? All four of those formats exist in other APIs.

Choosing "RGBA" vs "XYZW" as the names of vertex attributes is basically arbitrary, it's just a convention in shader code that a vec4 supports both labels.
