### ISSUE TITLE
What happens in configureSwapChain and on canvas resize?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1691]
We need to figure out what the semantics are of the following cases:

```ts
swapChain = ctx.configureSwapChain(...);
const t1 = swapChain.getCurrentTexture();
swapChain = ctx.configureSwapChain(...); // Is t1 destroyed?
const t2 = swapChain.getCurrentTexture(); // Same texture? New texture?
```

```ts
canvas.width++;
const t1 = swapChain.getCurrentTexture();
canvas.width++; // Is t1 destroyed? Or do we continue on pretending the canvas hasn't changed size?
const t2 = swapChain.getCurrentTexture(); // Same texture? New texture?
```

```ts
swapChain = ctx.configureSwapChain(...);
canvas.width++; // Is swapChain destroyed?
```

Somewhat related to #1548

**Comment by kainino0x** [comment]
cc @toji @jdashg

**Comment by austinEng** [comment]
Also this case. The spec says reconfiguring the swapchain destroys the previous one, but the behavior of `getCurrentTexture` on a destroyed swapchain is unclear.

```javascript
const swapChain1 = ctx.configureSwapChain(...);
const swapChain2 = ctx.configureSwapChain(...);
const t1 = swapChain1.getCurrentTexture(); // Null? "Destroyed" texture? exception?
const t2 = swapChain2.getCurrentTexture();
```

**Comment by toji** [comment]
Regarding canvas resize, I don't think it's terrible if a resize that occurs after `getCurrentTexture()` doesn't take effect until the next frame. Canvas size and css size can be mismatched anyway, so handling the stretch-blit isn't a problem, and if developers find it to be an objectionable artifact it's easy enough to avoid.

`configureSwapChain()` on the other hand feels more drastic and like it ought to take effect more immediately. Implicitly destroying an outstanding current texture seems appropriate in that case.

**Comment by Juanmihd** [comment]
Hey folks (Juanmi here, from Canvas team).
Once thing that it's done in canvas2d (and WebGL AFAIK) is to discard the internal resource once there is a resize. 
I am aware that could need a change in the spec, but I think it would make some of these issues easier to solve if the texture can be discarded once a new size is required. 
https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-context-mode
> Whenever the width and height content attributes are set, removed, changed, or redundantly set to the value they already have, then the user agent must perform the action from the row of the following table that corresponds to the canvas element's context mode.
If any resize operation in WebGPU follows the same logic currently in Canvas2D and WebGL this could become easier to fix?

**Comment by kainino0x** [comment]
Thanks Juanmi for the context! I think this would align with that:

```ts
swapChain = ctx.configureSwapChain(...);
const t1 = swapChain.getCurrentTexture();
swapChain = ctx.configureSwapChain(...); // destroys t1, clears canvas so t1 is never displayed
const t2 = swapChain.getCurrentTexture(); // new texture
```

```ts
canvas.width++;
const t1 = swapChain.getCurrentTexture();
canvas.width++; // destroys t1, clears canvas so t1 is never displayed
const t2 = swapChain.getCurrentTexture(); // new texture
```

```ts
swapChain = ctx.configureSwapChain(...);
canvas.width++; // does not destroy swap chain
```

**Comment by kainino0x** [comment]
Note this would make configureSwapChain clear a canvas without any other calls (like getCurrentTexture does today). I think this is reasonable. The alternatives are:
1. As described above
2. it "cancels" the previous clear that would have been caused by _previous_ getCurrentTexture - weird retroactive behavior
3. t1 stays valid through configureSwapChain *as long as* getCurrentTexture isn't called again.

Both 1 and 3 are reasonable. Perhaps 3 even moreso now that I've thought about it.

**Comment by kainino0x** [comment]
@jdashg would you be able to provide some more WebGL perspective on this issue?

**Comment by jdashg** [comment]
Ok I have a very interesting example: https://jsfiddle.net/f3rkdyvh/3/
This has different behavior in Chrome and Firefox right now.

* HTMLCanvasElement.set width
  * if new_width == current_width:
    * if webgl, no-op and return. (However, `canvas2d.width = canvas2d.width` causes a clear)
  * discard old default framebuffer, recreate with the new size
  * In Firefox we mark canvas as 'drawn to' here, but maybe we shouldn't

* \<paint document>
  * for each canvas
    * if canvas has been drawn to
      * publish default framebuffer to frontbuffer

**Comment by Kangz** [comment]
An additional corner case is what happens if we set with multiple times and finish by setting it to the original value. From quick testing it seems to do the same thing as just changing the width.

**Comment by Kangz** [comment]
The new direction looks good but we should maybe talk to more canvas folks before settling on it, since it is a new concept in HTML / JS land.

**Comment by kainino0x** [comment]
> * Probably we should define exact guaranteed minimum-maximum-values in the spec, and issue warnings above those limits.

I realized that since the swap chain returns GPUTextures anyway, we can have to enforce the exact maxTextureDimension2D from the GPUDevice (8192x8192 by default) anyway. So if we can always support canvases of size maxTextureDimension2D (I bet we can), then there is no need for any warnings or unreliable implementation-defined limits.

**Comment by kainino0x** [comment]
JG points out we'll need to account for the possibility of OOM on swap chain textures. (Maybe GPUOutOfMemoryError in getCurrentTexture?)

**Comment by magcius** [comment]
From a pedagogical standpoint:

```js
const sc1 = ctx.configureSwapChain({ device, format: 'bgra8unorm', usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_DST });
canvas.width++;
// sc1 silently invalidated
const sc2 = ctx.configureSwapChain({ device, format: 'bgra8unorm', usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_DST });
```

Given that sc1 and sc2 were created from the same exact line of code and same exact values, there's no clear reason why you should have to re-configure it. Even if it does nothing, I wonder if we should mandate the user passing a width and height in there:

```ts
const sc1 = ctx.configureSwapChain({ device, format: 'bgra8unorm', usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_DST, width: canvas.width, height: canvas.height });
canvas.width++;
// much more clear that the old swap chain was created for a given width and height and is now invalid.
const sc2 = ctx.configureSwapChain({ device, format: 'bgra8unorm', usage: GPUTextureUsage.RENDER_ATTACHMENT | GPUTextureUsage.COPY_DST, width: canvas.width, height: canvas.height });
```

I wonder if it also makes sense to have a `swapChain.resize(width, height)` entry point if the other details are not changing.

**Comment by kainino0x** [comment]
The latest plan is the one written down in https://github.com/gpuweb/gpuweb/issues/1691#issuecomment-837290595, where swap chains won't get invalidated, but also won't change size, upon canvas.width/height change. Instead, we keep displaying a surface whose resolution no longer matches the canvas.width/height. This is itself a bit weird, but there is precedent for the canvas drawing buffer size not matching the canvas size.

Thinking about `swapChain.resize()` though, TBH I'm not sure whether we _really_ need a separate swap chain object. We could just make the "current swap chain" be internal state of the canvas context object, and have configureSwapChain change that state. I haven't thought this through, though, so maybe it's a bad idea.

**Comment by magcius** [comment]
So GPUCanvasContext would gain a `getCurrentTexture()` method?

**Comment by toji** [comment]
Thinking back to discussing the concept of swap chains with @Kangz (I think) a while back, I remember one of the motivations for them being that they could presumably come from multiple different sources, not just a canvas. WebXR was specifically called out as an example of a place where the XRSession could surface a new GPUSwapChain for content to be rendered to, which felt like a good path forward at the time.

Since then we've done [more investigation on that topic](https://github.com/immersive-web/proposals/issues/58) and come up with [a proposal](https://github.com/immersive-web/WebXR-WebGPU-Binding/blob/main/explainer.md), and it seems like we won't want to use the `GPUSwapChain` concept specifically for a variety of reasons. For example: In WebXR there are benefits to having the depth/stencil buffer be managed by the XR session so that it can be used for certain reprojection and compositing techniques. Since `GPUSwapChain` doesn't (and shouldn't) manage depth buffers a purpose-built interface seems more appropriate. (There's other details to consider here too: XR swap chains will need to support 2D array textures, mip levels, multiple textures per-frame, and more.)

I don't recall if there were other similar scenarios that were being considered as a reason for supporting swap chains as a separate interface, but I'm reasonably confident at this point in saying that WebXR won't be using them.

Aside from that, one thing to keep in mind is that if you don't have a separate context and swap chain concept you'll end up in a scenario where you'll get a context that has a `getCurrentTexture()` method, but you won't be able to call it until you configure the object that you just got, which feels awkward. Either that or you front-load the context creation options with things like the `device`, which starts to imply that you could never change that.

**Comment by kainino0x** [comment]
> So GPUCanvasContext would gain a `getCurrentTexture()` method?

Yeah, it would move there.

> it seems like [WebXR] won't want to use the `GPUSwapChain` concept specifically for a variety of reasons.

These reasons definitely make sense and I agree.

> you'll get a context that has a `getCurrentTexture()` method, but you won't be able to call it until you configure the object that you just got, which feels awkward

IMO that would be okay. It's a simple state check, and for an obvious reason (no GPUDevice has been provided yet).

**Comment by toji** [comment]
> IMO that would be okay. It's a simple state check, and for an obvious reason (no GPUDevice has been provided yet).

If we do want to collapse swap chains and the context into one, I'd suggest retaining the `GPUSwapChain` name as the thing that `canvas.getContext()` returns. (Or `GPUSwapChainContext` if you really want to have the word "context" in there.) I really like having an interface that's a clear parallel to the native swap chain concept. As a bonus, you could make the context ID `gpuswapchain`, since dislike for `gpupresent` keeps coming up. 😁

Sketching it out real quick, it could look like this. Biggest questions become where errors get surfaced since the device that the swap chain is associated with is mutable and may be `null`.

```webidl
dictionary GPUSwapChainCreationArgs {
  GPUSwapChainDescriptor initialConfiguration;
}

interface GPUSwapChainContext {
  GPUTextureFormat getPreferredFormat(GPUAdapter adapter);

  // Need a way to surface errors here?
  undefined reconfigure(GPUSwapChainDescriptor descriptor);

  GPUTexture getCurrentTexture();
};
```

Usage then looks something like this:

```js
const swapChain = canvas.getContext('gpuswapchain');

// Would Error: Not configured yet.
//let texture = swapChain.getCurrentTexture();

swapChain.reconfigure({
  device,
  format: swapChain.getPreferredFormat(device.adpter)
  // width, height still defaults to canvas attributes?
});

// Now this works.
let texture = swapChain.getCurrentTexture();
```

Alternately, to allow it to be used immediately upon creation, you can do the following
BUT you don't have any way of querying the preferred format first, so you just have to go with a known good format.

```js
const swapChain = canvas.getContext('gpuswapchain', {
  initialConfiguration: {
    device,
    format: 'bgra8unorm'
  }
});

// Works immediately after creation.
let texture = swapChain.getCurrentTexture();
```

And of course I'd prefer that we keep the previously discussed property of the swap chain not resizing unless explicitly reconfigured.

```js
window.addEventListener('resize', () => {
  // Must explicitly reconfigure swap chain if you want to keep it in sync with
  // canvas resizes.
  swapChain.reconfigure({
    device,
    format: swapChain.getPreferredFormat(device.adpter),
    width: canvas.offsetWidth * devicePixelRatio,
    height: canvas.offsetHeight * devicePixelRatio
  });
});
```

(This is the reason I used `reconfigure` rather than `configure` as the method name, because it seems like the majority of the time it'll be changing the configuration rather than establishing an initial one.)

**Comment by kainino0x** [comment]
This design seems good to me. I prefer the version without initialConfiguration. We should raise it to the meeting (maybe someone will have a good reason to keep the separation).
