### ISSUE TITLE
Are padding bytes of structures intialized with zero value expressions?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1747]
The spec currently states: `The zero value for a storable structure type S is the structure value S with zero-valued members.`. If I have a struct like the layout example given later:

```rust
[[block]] struct B {                           //             align(16) size(160)
    a: vec2<f32>;                              // offset(0)   align(8)  size(8)
    // -- implicit member alignment padding -- // offset(8)             size(8)
    b: vec3<f32>;                              // offset(16)  align(16) size(12)
    c: f32;                                    // offset(28)  align(4)  size(4)
    d: f32;                                    // offset(32)  align(4)  size(4)
    // -- implicit member alignment padding -- // offset(36)            size(12)
    e: A;                                      // offset(40)  align(8)  size(24)
    f: vec3<f32>;                              // offset(64)  align(16) size(12)
    // -- implicit member alignment padding -- // offset(76)            size(4)
    g: array<A, 3>;                            // offset(80)  align(8)  size(72) stride(24)
    h: i32;                                    // offset(152) align(4)  size(4)
    // -- implicit struct size padding --      // offset(156)           size(4)
};
```

Is the 8 bytes of memory after `a`, 12 bytes after `d`, 4 bytes after `f` and 4 bytes after `h` initialized to zero as well, or are they random memory?

**Comment by alan-baker** [comment]
I don't think the spec needs to define that. Those bytes are not accessible by the shader.

**Comment by alan-baker** [comment]
Perhaps worth a clarification that we don't need this as long as we don't have arbitrary type mutations.

**Comment by dneto0** [comment]
> I don't think the spec needs to define that. Those bytes are not accessible by the shader.

It's literally unspecified: no promises are made.
But an explanatory note could be useful.

**Comment by litherum** [comment]
I think I agree that we shouldn’t be defining the values of padding bits.

Note, though, that they are observable if you have a buffer of structs.

**Comment by litherum** [comment]
After the call today I consulted with my team, and we came to a different conclusion. The contents of padding bytes are important to be portable, because they will be so common and so easy to observe.

There is a natural way to achieve this - we can have all of our compilers emit structs which have all their padding fields named. If we name all the padding fields in the generated code, we can then either:
1. Avoid clobbering the padding bytes by deconstructing buffer writes into sequences of scalar writes. Because the padding bytes are named, SPIR-V can't clobber them.
2. OR, we could enforce all padding fields to be 0 by setting the padding fields at buffer loads. If you do this, you don't have to deconstruct writes.

Either way, whatever we choose, it's important that the contents of padding bytes are portable across APIs / machines.

**Comment by alan-baker** [comment]
I brought this up internally at Khronos. For those with access there are two issues:
https://gitlab.khronos.org/cross-api/memory-model/-/issues/154
https://gitlab.khronos.org/vulkan/vulkan/-/issues/3093

To summarize, no desire for a spec change around padding bytes, but the consensus is that users could control this if they want by choosing how the structures are emitted. The important consideration is the layout of device memory since that is the place where the padding will be visible. So the same struct in WGSL could be emitted differently depending on the address space. There are some potential performance implications around breaking a single store into multiple memory operations, but those are not likely to be very large in most cases. The VK_KHR_zero_initialize_workgroup_memory extension is only guaranteed to zero initialize data members of a structure.

That still leaves open the option of speccing this in a few different ways. We could guarantee zero initialization of on-chip memory, but not specify that padding is untouched. If both device and on-chip use the same representation it would still allow optimizations to use more efficient memory operations. Alternatively we could specify that padding is not touched and generate code that forbids those sorts of optimizations.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-17-minutes#are-padding-bytes-of-structures-intialized-with-zero-value-expressions-1747">WGSL meeting minutes 2022-05-17</a></summary>



* Offline
    * MM: After the [2202-05-10] call today I consulted with my team, and we came to a different conclusion: [https://github.com/gpuweb/gpuweb/issues/1747#issuecomment-1123121829](https://github.com/gpuweb/gpuweb/issues/1747#issuecomment-1123121829)
* AB: Took action to talk to Khronos. The vulkan spec is how it is, and won’t change. Agree with us that if we want to emit a different struct it would be sufficient if we initialized those members by adding padding fields. Tint does in metal backend. Talked about workgroup memory safety concerns. Important thing is whether padding exists in global memory or not. How can you observe the effects, have to bring back via global memory. So important to not have padding fields in that memory. Or if in workgroup memory, initialize to zero and copy the zero. Feels like adding the padding instead of relying on not coping to zero initialize and then it’s safe. We can say it’s zero initialized and leave in it could or could not be touched as implementation defined. Think that’s portable enough. However, Apple may have different opinion.
* KG: Sounds like could we have it not trample on byes, no. Have a path forward as if they didn’t trample the bytes.
* JB: Can we get that written down somewhere?
* KG: Or in Khronos issue would be ok
* AB: **Will add links and summary**.


</details>

**Comment by litherum** [comment]
Resolution: Write operations to buffers do not touch padding bytes. (The padding bytes are preserved from whatever they were before the write.)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-31-minutes#are-padding-bytes-of-structures-intialized-with-zero-value-expressions-1747">WGSL meeting minutes 2022-05-31</a></summary>



* MM: No comments since last week.
* KG: Any thoughts? From notes last time, one of ideas from JB was forbid structs with padding and just say if you want padding you have to put in the fields (for v1). 
* Ab: Does that mean any vec3 has to be followed by 32bit scalar? (or 16 bit if half)
* KG: Yup, or call it vec4.
* MM: What happens if you have array&lt;vec3&lt;f32>>, is that illegal?
* JB: Would forbid that.
* KG: Type check as vec3 and implement as vec4
* JB: Talking about forbidding in wgsl, that suggest is to accommodate in compiler.
* BC: Pretty late in day to be making this breaking change. Not a lot of shaders, but this would break a lot of them.
* JB: Drastic move. The array of vec3 makes me uncomfortable.
* KG: One other proposal was to say that padding is all zeros all the time and make sure to read/write zero when we have to and then have optimization later for a type that says don’t care. That’s optimization opportunity and if user doesn’t care, they annotate. Some type of of vec3x type to make arrays like this but fairly tolerable. Or have struct that contains vec3 and  don't care scalar and you have array of that instead of array of vec3. Little clunky but add authoring complexity to squeeze out perf. Gradual complexity for performance.
* MM: Solves this by having different family of types like packedVec3 which is vec3 with stride 12 instead of 16. Think proposal just made would be acceptable. More concerned about defaults.
* JB: Setting aside optimization for don’t care type, the implementation technique that would work for the 0’s is that the wgsl translator always translates wgsl structs to fully packed structs in backend language and would expand initializers or other expressions  that create those to types which provide zeros. Is that correct?
* KG: Yes
* MM: Have to handle case where you do read and then store back over thing you just read. In this world that would have side effect of filling padding bytes with zeros.
* KG: Little satisfying as the default c version is just let padding bytes be trampled and if you wanted zeros put in a real type. We want to try harder to have things accidentally work on different systems with different behaviours. Accidental portability.
* AB: If we say you have to 0 init and use same representation on host and if it’s copy or trampled it’s 0 initialized. Free to do that optimization. Breaks down if on host initialize with other data. If you choose to do that, why do we care if we write zeros? Let us trample us or not, if doing in nice way we can guarantee 0’s on GPU side and host is up to person writing wgsl program.
* MM: Struggling to understand point. One response is the way data gets into the padding spots isn’t just filled in on host, run 2 shaders which treat buffer data as different types. Imagine sandwich of shaders type A, type B, type A. 
* KG: Or vec4, then vec3, then vec4.
* MM: Right. If the middle shader clobbers or not then the last part of sandwich can easily see it.
* AB: Why scared about that? Don’t see that as a problem when free to reinterpret data
* MM: Scared about portability
* KG: Concern is the problem of the instinct of people using smaller types. If reading vec3 is faster then vec4 but if they want to make sure no trample we would be saying have to read as vec4. Part is dealing with programmer intuition. Can spec it as will trample on data (read as vec3 and write as vec4) might have changed it on some systems, others we wont. Worry about it being accidentally breaking and if making different choice would always work
* aB: Vulkan says trample padding between struct members but not at end. If just vec3 then not trampling 4 bytes.So, if vec3, vec3 then can trample 4 bytes between the two. Distinction between end and in between bytes.
* MM: Either way, real important bytes are precious. Can’t just let get trampled willy nilly.
* AB: Disagree with that statement.
* TR: One issue haven’t heard discussed, struct side should be aligned by the largest alignment member. 64 bit value can effect ending and size of struct. If we trample would depend on if we have expanded or cut down versions with same prefixed elements. Could know stride of struct and reads from all locations that way. Can do this in structured or byte address buffer in hlsl. If you write subset of structure could be trampling what looks like padding but is part of larger structure. Could be a problem too.
* KG: SOunds like what vulkan is trying to solve. Intra padding is fair, outside struct is sacred. Good to hear why that’s the case.
* BC: For better or worse, tint doesn't’ use HLSL structures for buffers. Use big array of vec4’s and take structures and manually pack and unpack. Doing the 0’ing of the padding is more work and produces more code then just doing the loads/stores of the bits. Don’t know perf hit on compiler or ISV instructions but would be trivial to do loading /storign of fields of structure/array elements based on how we’re doing. That would be the easiest implementation
* JB: Promising to preserve padding
* BC: Only load and store what is declared in that structure
* MM: Ok with me.
* JB: So, if I load a struct from a buffer and the struct has holes and then write struct to another buffer then the bytes in the dest that are padding are left unchanged.
* BC: Correct
* JB: So, this forbids write widening. Even with 64 bit stores and the structure fits in 64 bits the optimizer is not permitted to widen to a 64 bit store has to do individual pieces
* BC: Based on our impl, yes, we do field assignments using 32 bit scalars and vectors. That’s how it would work. If wanted to get clever with a contiguous aligned range could use wider range. Have received comments output shaders are unreadable but removes a lot of complexity to make sure layouts match WGSL rules. The dxbc is identical to what FXC was producing. 
* KG: So output code was the same
* BC: For FXC, DXC might have difference
* JB: Feels like rule that writes don’t touch padding is easier on optimizer then writing 0’s
* AB: I think zeros are worse.
* KG: Could get other behavior if you wanted. Satisfied with that. Can manually widden types to carry along. Could tightly pack struct to keep bytes but you don’t have to. One of the concerns was complexity but tint already does this.
* TR: Like this approach. HLSL does this, doesn’t write padding for structure. Just disallow vulkan behaviour of widening interior of struct to write padding. Only allow that if there is no padding.
* MM: Possible to emit spirv program that the later program that consume buffer doesn’t touch padding
* JB: Thinking what SPIRV would look like. IR says store struct. Then spirv says, can’t use SPIR-V store anymore in order to protect padding. SO, break store into access chain to get value out and store pairs.
* BC: No, if to do for get element pointer then optimizer could go and reformat that thing. The thing that guarantees the optimizer does not remerge is the final reads and writes to storage buffer are not using compound type. It’s decayed down to a vector.
* JB: Each store pair is basically the struct store decomposed to stores of primitive types.
* AB: The important part is you can’t represent the type the same as WGSL. Have to pack in spirv.
* BC: Storage buffer in Tint is never a struct type as declared in wgsl. It’s an array of vec4 and we generate read/write function stubs which do packing to and from the array. Load and store function with offset param. Load given structure pulls apart and writes those things.
* JB: So, can’t do pointer arith in the dialect of spirv restricted to, so created spirv struct types that are fully packed with no holes and assigning to certina values?
* MM: 2 ways, WGSL struct as struct in SPIR-V and cover all holes. Or, WGSL struct never appears in SPIRV ever.
* BC: We do either. Don’t do this for spirv but would be trivial. Storage buffer becomes array&lt;uint32> and then structures from WGSL are handled around when writing functions but when load/store storage buffer. Instead of loading/storing type we call helper which pulls apart that struct and does vecto reads/writes.
* JB: K, so as far as psirv is concerned, in memory it’s arrays of vectors. Would like to discuss more in the office hours.
* MM: With saying struct never appears, is probably possible but having it for register types makes sense. For memory types doesn’t have to be there
* KG: **So consensus is to spec so we never touch padding**.


</details>
