### ISSUE TITLE
wgsl: can hex floats explicitly represent infinity and NaN as float literals?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1769]
WGSL has hex floats.  The nice thing about hex floats is the author can specify the exact bits in the binary floating point representation.   But we run into corner cases.

## Question 1:  Can hex floats represent infinity and NaN?

IEEE 754 binary32 has bit patterns for infinities, and (many) for NaNs:
- infinity:  biased exponent is 0, and mantissa is 0
- NaN: biased exponent is 0, and mantissa is non-zero. (With machine-specific convention for quiet and signalling NaN).

I looked up how to formatted input of floats works for C11 and C++:
* C++11 and later:  formatted stream input of floats  delegates to C11's strtof.
* C11 strtof allows optional + or - followed by
   * `INF` or `INFINITY', ignoring case, to indicate infinity
   * `NAN` or `NAN(`char-sequence`)` to indicate a NaN, where char-sequence is one or more digit, letter, or underscore (ignoring letter case).  The interpretation of the char-sequence is implementation-determined.

In source code, for:
*  C and C++ have INFINITY as a macro that expands to a constant expression that is infinity or overflows at translation time.
* C has NAN as a macro if the implementation supports NaNs, and which expands to a constant expression that is a quiet NaN.

However,   #1743 says implementations can assume infinities and NaNs "are not present".  

So maybe it's a non-issue because then any computations or tests on those weird values would have varying behaviour.

Option 1a: WGSL has no float literal representation for infinity or NaN.
Option 1b: Make up a convention:   0x1p+128  maps to infinity.  (And make a convention for NaN.. can follow up here.)
Option 1c: Make a special token for INFINITY and NAN.

Proposal: 1b for infinity.  1a for NaN.

## Question 2: What happens if a hex float literal overflows?
Option 2a:  result is an infinity
Option 2b:  static error, i.e. reject the shader

Proposal:  (weak preference)   2a  (goes with 1b)

## Question 3:  what happens if a hex float literal has lower-significance fractional bits that would be lost?
Option 2a:  truncate
Option 2b:  may round or truncate
Option 2c:  static error, i.e. reject the shader

Proposal:  2b
Rationale: This seems the least fussy.  
Maybe this is related to decimal literals.  I assume they are silently rounded or truncated.

I think underflow is a special case of Question 3.

**Comment by dneto0** [comment]
I haven't looked at underlying APIs.
If WGSL is more permissive in these edge cases it may be that testing for distinct behaviours will be muddled by the looseness in underlying floating point anyway.
So it may be mostly a matter of whether shaders are rejected statically.

**Comment by litherum** [comment]
For question 1, you can already pass in these bit patterns in buffers from the API, so I’m not sure we would really be saving people if they go through the trouble of typing in the arcane voodoo to specify every bit of a NaN literal.

But we probably shouldn’t treat “NaN” or “inf” in the program as float literals though. They would be footguns.

**Comment by dneto0** [comment]
Ok, modified proposal:

- 1a:  for NaN:  No hex float maps to a NaN
    - If the programmer really wants an explicit NaN they can do a bitcast from a u32 bit pattern.  It's not a const_expr (right now), but I assert they can live with that.
- 2a: a hex float that overflows the target type is mapped to the infinity of that type, with the same sign.   This is as if there's an interpretation as an idealized infinite-precision value, and then normal floating point conversion rules apply.
- Question 3: loss of significant bits.  2b (whoops should have called this 3b): may round or truncate.  Again, this appeals to normal floating point conversion rules we've already decided on.

**Comment by jimblandy** [comment]
Today's WGSL meeting notes:

(Updated proposal based on feedback)
AB: We like DN’s proposal
JG: Do we have NaNs?
AB: not currently for hex floats
AB: C++ has macros for generating nans and infinities
JG: I think I’d like more time to look at this PR
RM: Question: when a hex literal overflows the target type, it maps to infinity. But if a developer is going to bother to use the hex representation of a float, don’t we want to assume that they know what they’re doing and should use the right size?
AB: Do you think that should be an error?
RM: If the programmer cares enough to write in hex, then it seems like it would be safer to make it an error instead of mapping to infinity.
AB: We don’t have a strong opinion about this. Conversion seems slightly more usable.
RM: I put a comment on the issue, we can review when DN is here

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-07-20-Minutes#wgsl-can-hex-floats-explicitly-represent-infinity-and-nan-as-float-literals-1769-">WGSL meeting minutes 2021-07-20</a></summary>



* (Updated proposal based on feedback)
* AB: We like DN’s proposal
* JG: Do we have NaNs?
* AB: not currently for hex floats
* AB: C++ has macros for generating nans and infinities
* JG: I think I’d like more time to look at this PR
* RM: Question: when a hex literal overflows the target type, it maps to infinity. But if a developer is going to bother to use the hex representation of a float, don’t we want to assume that they know what they’re doing and should use the right size?
* AB: Do you think that should be an error?
* RM: If the programmer cares enough to write in hex, then it seems like it would be safer to make it an error instead of mapping to infinity.
* AB: We don’t have a strong opinion about this. Conversion seems slightly more usable.
* RM: I put a comment on the issue, we can review when DN is here


</details>

**Comment by RobinMorisset** [comment]
Sorry for forgetting to comment on this during the last two weeks.
My view of this is that if a programmer cares enough about precision to use a hex representation, we probably should not silently modify the float that he entered. In particular:
- If we would have loss of significant bits, I'd make that an error
- If we overflow, I'd make that an error

@litherum mentioned that rejecting shaders with loss of precision was painful in WSL and had to be changed, but from discussing it with him, this was for all float literals, not specifically for hex notation.

I don't have a strong opinion on NaN, I don't see a reason to forbid explicitly having them through hex notation, but a bit cast from u32 is a reasonable work-around.

**Comment by litherum** [comment]
After today's call, I thought we were in a good place with this, but now after some further investigation, I'm now more confused than I was when we started.

The overall question is: **Who is this feature for?**

Background: The grammar for `HEX_FLOAT_LITERAL` in the spec today is:
```
-?0x([0-9a-fA-F]*.?[0-9a-fA-F]+ | [0-9a-fA-F]+.[0-9a-fA-F]*)(p|P)(+|-)?[0-9]+`
```

More background: Today we resolved:
> RESOLVED: When writing hex float literals, it is impossible to spell infinity or nan, or values larger than the max float, or values between representable floats [and doing so would be a compile error]

### Audience A

If this feature is for regular people (authors) to write, because we feel that counting fractional parts of things in hex is something that people do, then that casts doubt on the resolutions we made today. The current grammar above seems to be for this audience - compared to decimal floats, it's convenient to be able to write either `120.` or `1.2e2`, and the current `HEX_FLOAT_LITERAL` allows this same kind of redundancy. However, if this is something that we expect humans to write, it seems a bit hostile to allow an author to write `0x1000000.0` but not `0x1000001.0`, when they just as easily could have written `16777217.0` successfully. After all, they were just counting fractional parts of things in hex themselves. As another example, they could also choose to write either `0x50.0` or `0x5.0p4` - whichever is convenient for them at the time.

### Audience B

If this feature is for compilers to generate WGSL code from a source SPIR-V program, the resolutions we made today make perfect sense - the compiler knows exactly what bit pattern they want to put into the float, and if we put any other bit pattern in, that would be wrong and probably would hide a bug. In this case, the current grammar seems like it doesn't fit this situation, and instead should be something like

```
HEX_DIGIT: [0-9a-fA-F]
HEX_FLOAT_LITERAL: -?0x1. HEX_DIGIT{6} (p|P) HEX_DIGIT{2}
```

Or maybe even

```
HEX_DIGIT: [0-9a-fA-F]
SEPT_DIGIT: [0-7]
HEX_FLOAT_LITERAL: -?0x1. SEPT_DIGIT HEX_DIGIT{5} (p|P) -? SEPT_DIGIT HEX_DIGIT
```

Doing this would have the exact same fidelity as the source SPIR-V program, and there would be no duplicate representations for the same value. We would also preserve the requirement that it's a compiler error if this grammar is used to spell a NaN or INF value.

### Conclusion

Before the discussion today, I actually thought the audience for this feature was Audience B, but now I'm not too sure after more investigation. Either way, where we seem to be now is a sort of halfway point, which doesn't serve the needs of either audience very well.

**Comment by jimblandy** [comment]
I see this as the core of your concern:

> However, if this is something that we expect humans to write, it seems a bit hostile to allow an author to write 0x1000000.0 but not 0x1000001.0, when they just as easily could have written 16777217.0 successfully.

If I understand correctly, the inconsistency you're pointing out is that decimal float literals silently round to the nearest representable value (16777216 being the value closest to 16777217 that a 32-bit float can represent), whereas hex float literals refuse to round and cause a compilation error. You say, if it is not only acceptable but _preferred_ for decimal floats to round, why wouldn't the same be true for hex floats?

I think we're trying to serve both audiences A and B.

Audience B is an easier customer, since legibility is a secondary concern, and their tolerance for complexity is higher.

I think Robin's observation is that Audience A is not simply people who like fractions whose denominators are powers of 16: it's people who know exactly which value they want, and are wary of the long history of floating point input and output routines not getting it quite right. This might be:

- people using polynomials to approximate more unruly things, who have carefully chosen their coefficients to minimize error

- people doing stuff like the [fast inverse square root](https://en.wikipedia.org/wiki/Fast_inverse_square_root). WGSL can't do that particular hack, because it doesn't have `reinterpret_cast` (and apparently it isn't valuable any more on modern hardware? dunno), but surely there is maverick numerical magic like that still in circulation.

In both of these cases, people want the exact bits they write; but they still want human conveniences like non-normalized forms, optional exponents, and implicit trailing zeros.

**Comment by jimblandy** [comment]
It might be worth pointing out that the decimal forms of the values floats actually represent can get pretty unwieldy: every _bit_ of precision you want requires an entire decimal _digit_. For example, the exact decimal form of 1/65536 is `0.0000152587890625`: sixteen digits. So even if your goal is just to avoid rounding, and write out the actual number you want, decimal is awkward.

I see avoiding rounding as a key goal of hex float literals - and that's why we want an error if rounding does happen.

**Comment by dneto0** [comment]
Resolution from [2021-08-03](https://docs.google.com/document/d/1uNbcsP2YxIHWaqcEnMiMfm8Uym7Y6hIaBNk6scUtVYY/edit)


> RESOLVED: When writing hex float literals, it is impossible to spell infinity or nan, or values larger than the max float, or values between representable floats (and doing so would be a compile error)

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-08-03-Minutes#wgsl-can-hex-floats-explicitly-represent-infinity-and-nan-as-float-literals-1769">WGSL meeting minutes 2021-08-03</a></summary>



*  RM: Sorry for commenting so late. The shorter version is: If the programmer goes through the trouble of using the hex notation, they know what they’re doing, they want to control every bit on the float. Ignoring half those bits is not what they want. We’d recommend that if the type doesn’t match the number of bits, it should be an error
* JG: for hex floats, is 0.A, is that 1/10th?
* JB: 0.A is 10/16ths
* JG: We can reliably tell how many bits of precision are being handed to us.
* JB: you’re writing out the bits that will appear in the mantissa
* JG: What if you supply 24 bits instead of 24 bits in the mantissa?
* JB: Robin is proposing that’s illegal
* AB: Our floating point rules say denormals may be flushed. Is that converted? It’s not a bigger problem if too much precision is thrown out as a static error
* JG: It sounds tempting to do this for extra precision, because it’s possible.
* JG: I’m not convinced you can do this validation. We’re writing out the number that will be decoded into the mantissa
* MM: What if someone just happens to write the value for a NaN?
* [general discussion]
* Everyone: It ends up being an error
* E.g. `0x1ffp10, 0X0p-1, 0x1.p0, 0xf.p-1, 0x0.123p-1, 0xa.bp10l`
* JG: Errors are a good value add because people are reaching from floats
* AB: In the future we can discuss making the as_bits() function constexpr, so it can be used at module scope
* RESOLVED: When writing hex float literals, it is impossible to spell infinity or nan, or values larger than the max float, or values between representable floats [and doing so would be a compile error]
* BC: fxc is weird around inf and nan. We’re seeing broken behavior, which some flags can partly work around it. We see things like optimization assuming finite values.
* AB: You can’t use infinity as a sentinel value, because the compiler might just delete it.
* JG: That’s bad
* AB: you can load it, but once you start doing math, the implementation can assume it doesn’t exist
* JG: Can we recategorize things as “respects” vs “doesn’t respect”?
* AB: I’d have to check
* AB: isinf() and isnan() might not work how you think they’re going to work. FYI. These may not work.
* JG: If they may not work, we should just not have them.
* AB: That is open to debate.
* MM: They work on metal
* JG: We don’t want to be in a situation where a class of algorithm just doesn’t work on a class of devices.
* AB: You’d have to use precision in HLSL on everything, and on Vulkan you’d have to have a special execution mode. I don’t know how well that’s tested.


</details>

**Comment by dneto0** [comment]
FYI.  Some interesting test cases include:
- non-zero mantissa, but very large magnitude binary exponent: https://bugs.chromium.org/p/tint/issues/detail?id=1150 
- zero mantissa and arbitrarily large magnitude binary exponent: The infinitely precise result is still zero. (Currently not handled by Tint.)

**Comment by dneto0** [comment]
This is fully addressed:

* #2227 captured that:
    * any kind of float literal with 'f' suffix can't overflow the target type
    * hex float literals with 'f' suffix must be exactly represented
* #2696 added f16 and extended the rules to 'h' suffix as well
* #2227 , with further clarification in #3225, specifies that AbstractFloat must not produce infinite or NaN

Closing.

**Comment by cybersoulK** [comment]
We need Nan and Infinity, this is a fundamental Compute representation.
For example, rust-gpu project compiles rust to spirv, and we need Nan and Inifinity representations for spirv to work correctly.
https://github.com/gfx-rs/wgpu/issues/5128

**Comment by ben-clayton** [comment]
https://github.com/gpuweb/gpuweb/issues/3749 covers why these are not currently part of WGSL.

Repeating what I wrote there:

We will likely expose non-finites with a future extension, which will be available for drivers and hardware that correctly support it (i.e. pass thorough CTS).
