### ISSUE TITLE
wgsl: compute shaders should have a workgroup_size attribute

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1777]
Currently in the spec, workgroup_size is optional.  It defaults to (1,1,1).

Using (1,1,1) is usually a terrible choice, for performance.
It will always work but almost always the worst choice (except for the ones where you'd exceed a register budget).

I understand this has already caused some pain in bringing up some applications. cc: @kainino0x 

So the proposal is:  A compute shader must have a workgroup_size attribute.
(Don't default the size in the x dimension. Still allow defaulting to 1 for the y and z dimensions.)

A rejected alternative is to have the implementation pick a workgroup size.  The thinking is that drivers probably don't have a great idea of what will work best.  Instead, pull the application into the decision loop.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-06-01-Minutes#wgsl-compute-shaders-should-have-a-workgroup_size-attribute--issue-1777">WGSL meeting minutes 2021-06-01</a></summary>



*   DN: Compute shaders default to workgroup_size=1, which is the worst. We want to force the programmer to think about *at least* the x-dimension, lest people think our perf is bad because they used the bad default. So let’s stop having a default for x. (at least)
*   DM: Ship it
*   KN: Would be ideal if we could have an ‘auto’ mode, where UA can pick for us.
*   AB: OpenCL will make up a default for you, guessing.  But you may pay for multiple compiles. Don’t think you want to do that.
*   RM: I generally like this proposal, and we can expand this later.
*   KN: +1
*   (consensus)
*   


</details>

**Comment by Kangz** [comment]
Sorry to come after this has been discussion. If the workgroup size is required, would it make sense to put it as part of the stage(compute) annotation?

```rust
[[stage(compute), workgroup_size(1)]] fn main () {}

// Could become any of
[[stage(compute(1))]]
[[compute(1)]]
[[kernel(1)]]
```

**Comment by dneto0** [comment]
That's a possibility.  It's less explicit but also less typing.
