### ISSUE TITLE
WGSL requires dynamic matrix indexing, which requires surprising SPIR-V

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#1782]
The section "Matrix Access Expression" mentions `OpCompositeExtract`, but that instruction only accepts literal indices, not expressions, so it's not sufficient to do the job described. The reference to `OpCompositeExtract` should be removed or at least qualified.

WGSL says that matrices that are not behind a pointer or reference can be dynamically indexed, but this requires surprising SPIR-V to implement.

- Function parameters may be matrices.
- Formal parameter expressions do not evaluate to references.
-  §6.6.2, "Matrix Access Expression", suggests that `e[i]` indexes a matrix if `e: matNxM<T>` and `i: i32 or u32`. There is no requirement that `i` be a constant, or that `e` be behind a pointer or reference.

But as far as I know, SPIR-V has no instruction that can dynamically index a matrix that is not behind a pointer. Naga handles the similar restriction on arrays by copying the entire array into a generated temporary variable, getting a pointer to that, and then using `OpAccessChain`. A [bit of investigation](https://github.com/gfx-rs/naga/pull/723#issuecomment-820889481) showed that some drivers will optimize out the temporary. We could do this for matrices as well.

But one of the goals of WGSL (as discussed in #692) is to have a trustworthy translation to and from SPIR-V. Transformations like this seem like a step away from that, but there's no other way to implement what WGSL requires.

**Comment by ben-clayton** [comment]
> But as far as I know, SPIR-V has no instruction that can dynamically index a matrix that is not behind a pointer. Naga handles the similar restriction on arrays by copying the entire array into a generated temporary variable, getting a pointer to that, and then using `OpAccessChain`. A [bit of investigation](https://github.com/gfx-rs/naga/pull/723#issuecomment-820889481) showed that some drivers will optimize out the temporary. We could do this for matrices as well.

I can confirm this is how [Tint also tackles this](https://dawn.googlesource.com/tint/+/refs/heads/main/src/transform/var_for_dynamic_index.h) (and like naga, we do the same for arrays).

> But one of the goals of WGSL (as discussed in #692) is to have a trustworthy translation to and from SPIR-V. Transformations like this seem like a step away from that, but there's no other way to implement what WGSL requires.

FWIW, we now have a bunch of things that are subtly different between WGSL and SPIR-V. To name a few:
* Entry point IO is declared almost entirely differently between WGSL and SPIR-V.
* `[[builtin(sample_mask)]]` is a `u32` in WGSL, but needs to be transformed into `array<u32, 1>` for Vulkan.
* Vertex point size needs to be emitted from vertex shaders in SPIR-V, not WGSL.
* Most texture intrinsics are not direct translations between WGSL / SPIR-V (e.g. `textureDimensions`, array counts being packed in coordinates in SPIR-V, not WGSL, etc)

Most of these could have  _"a trustworthy translation to and from SPIR-V"_, but the number of them are building up.

**Comment by krogovin** [comment]
I suggest removing from WGSL the feature that the elements of a matrix are dynamically indexable. For most things, as soon as it is dynamically indexable, then that something cannot live in a register and needs to be loaded from memory which will always dramatically harm performance. Hoping for a driver compiler to undo the temporary when the feature is not used puts too much faith in the compilers of drivers.

**Comment by dneto0** [comment]
Adding to the list:

* SPIR-V (and LLVM) have Phi, WGSL has lexical scoping. This requires variable hoisting.
* Dominance is different from lexical scoping.  In SPIR-V (and LLVM) you can have a value inside a structured construct that escapes and is used way outside (and after) the construct.  A workaround is to hoist that value into a variable declared in a spot so that all uses are in scope.  The easy cases are storable values (like i32), the hard cases are pointers (which can be in a 'let' but not in a 'var').   My judgement is that easy cases are relatively localized, and something that backend compilers are likely to melt away.  The pointer cases can be handled (haven't done it in Tint's spirv-reader yet, but the design is "straightforward"), and involve some more bookkeeping, again relatively localized.

**Comment by dneto0** [comment]
I'm much more concerned about the workaround for arrays than for matrices.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-06-01-Minutes#wgsl-requires-dynamic-matrix-indexing-which-requires-surprising-spir-v-1782">WGSL meeting minutes 2021-06-01</a></summary>



*   RM: GLSL can be compiled to SPIR-V (and also from HLSL), so do these source langs allow this? What SPIR-V is generated?
*   DN: GLSL does allow this, and the style of code generate is very variable-heavy, and so it does store to a var and load from that. This is kind of gross, but I’m less concerned about the (small) matrices problem, but arrays are more problematic. We definitely need to fix the OpCompositeExtract bug. For philosophy, we sort of avoid hashing that out because we’ve found it generally unhelpful for forward progress.
*   … One option is to delete the references, but it’s useful for authors. Maybe we want an implementor’s guide, but we don’t want to specify that. Philosophically we’ve definitely strayed from our earlier stated goals, but here we are.
*   GR: Which goal specifically?
*   DN: Like, 4 or so of them
*   GR: Should we fix those then?
*   DN: Some of them are still good, but &lt;lists some>. We’re ~50% false now.
*   (we can touch on this more later)
*   RM: DN mentioned the nuclear option of removing the refs to spir-v, but I think it’s good to keep them, even if they are only approximate. For this issue specifically, I’m concerned that if we forbid it, it would be painful for our authors. Especially if we can optimize many cases.
*   DM: A middle ground: Can only index if in memory, e.g. if they are references.
*   JB: I think if I were an author and got this error message, I would just store it in a var, which is exactly our workaround.
*   DM: If they are doing it, they take responsibility for it, which is good for some of the worst cases, e.g. 1000-len arrays.
*   JG: Maybe it’s good to surface the underlying constraints, and have author choose their workaround.
*   DN: For the matrix case, I think DM proposed adding matrix.x/y/z/w, which would help here. 
*   AB: What about just requiring the subscript be a literal?
*   JB: Could even have two rules: Arbitrary subscripts for references, but be strict for non-references.
*   RM: What produces by value? Func argos and intermediates? (also let vars)
*   DN: Should make the same choice for matrices and arrays, yes? (yes)
*   JP: Do authors have an option for making a read-only that has dynamic indexing?
*   DN: Not right now, NonWritable variables in Function/Private (?) storage class was only added to spir-v in 1.4. Maybe later?
*   (consensus for the two rule solution)
*   (JB to draft)


</details>

**Comment by kvark** [comment]
The unexpected outcome from the meeting was to try restricting dynamic array/matrix accesses to references only. This would ensure direct translation to and from SPIR-V (preserving developer trust ftw!).

**Comment by krogovin** [comment]
*thankyou*

**Comment by munrocket** [comment]
I like pure WGSL and still learning it. Just wanted to get rid of magic literal
```rs
ptr<function, array<vec2<f32>, 3>>
                              ^^^
```
through `constexpr` or pipeline-overrideable constant. Sorry for off-topic.

**Comment by kvark** [comment]
Ok, this is indeed off-topic for this issue. Instead, should be in #1272

**Comment by litherum** [comment]
Reopening.

### SPIR-V

We can understand why SPIR-V presumably doesn't have a direct opcode for dynamic indexing into SSA arrays. SSA IDs are intended to be able to be held in registers (as we understand it), and registers are not dynamically indexable.

For example, imagine in CPU code you had an array of 3 ints, and these 3 ints were held in `%rax`, `%rbx`, and `%rcx`. If you wanted to select the `i`th value from this array, there is no way to do it with a single operation.

Indeed, there are 2 ways of implementing this operation:
1. Switch statement:
```
switch (index) {
case 0:
    read %rax
    break;
case 1:
    read %rbx
    break;
case 2:
    read %rcx
    break;
}
```
2. Flush to memory
```
store %rax to (pointer + 0)
store %rbx to (pointer + 4)
store %rcx to (pointer + 8)
load pointer + 4 * index
```

SPIR-V has constructs for both of these operations, so it's understandable why they didn't want to add the higher-level operation. SPIR-V was not intended to be written by hand.

### WGSL

WGSL is, however, intended to be written by hand. It's totally natural to want to write code like:
```
let myArray = helper();
let item = myArray[index];
```

This is particularly true because the CG will likely be advertising `let` variables as preferred over `var`. Code like the above will _seem_ idiomatic. 

In every popular human-writable shading language, there is no way to write code like this that _doesn't_ work.

### Proposal

Adding the ability to dynamically index into a `let` array doesn't reduce the language's precision or explicitness. If an author wants to be precise about which of the two strategies is used (either a switch or a flush), they can explicitly either write a switch statement or they can use a `var` variable. Indeed, allowing dynamic indexing into `let` arrays only _increases_ expressiveness. Compilers compiling code from SPIR-V to WGSL would just no use these facilities. Humans could choose to use them or not, depending on the needs of their application. Therefore, adding these facilities is not harmful.

It's also actually beneficial. Knowing whether or not to use a switch or spill to memory involves knowing the device-specific performance characteristics of memory latency compared to program size increase. The author who writes code that runs on the web doesn't know these subtle performance tradeoffs of the device their code is running on. Indeed; implementations running on MSL and HLSL (and probably even SPIR-V, given mem2reg) get this benefit naturally - it's the compiler's responsibility to determine when/if/how variables get spilled, and the application just gets the benefit of that analysis without even having to opt-in.

**Comment by jimblandy** [comment]
Naga's prior strategy for indexing by-value arrays introduced spills at indexing operations, but spilling arrays as soon as they appear would probably have performed better. This seems to be what glslangValidator does when translating to SPIR-V. For the source code:

```
#version 460

layout (location = 0) out float fragColor;
layout (location = 1) in flat int index;

float[5] return_array(float v) {
  float a[5] = { v, v, v, v, v };
  return a;
}

void main()
{
  fragColor = return_array(1.0)[index];
}
```

we get this SPIR-V:

```
  %indexable = OpVariable %_ptr_Function__arr_float_uint_5 Function
               OpStore %param %float_1
         %30 = OpFunctionCall %_arr_float_uint_5 %return_array_f1_ %param
         %34 = OpLoad %int %index
               OpStore %indexable %30
         %36 = OpAccessChain %_ptr_Function_float %indexable %34
         %37 = OpLoad %float %36
               OpStore %fragColor %37
```

**Comment by jimblandy** [comment]
Oops. I don't want to pull this issue off on a tangent considering the details of our user's difficulties. They were using Naga for shader translation in a non-WebGPU context, and switched to a different shader translator, which does work for them. As I said, we know how to fix this particular problem: just do whatever the other translator does. See gfx-rs/naga#1461 for more.

> It was my belief that most IHVs take the SPIR-V and then heavily optimize that down as part of the lowering to their ISA. Part of this I would have assumed would be mem2reg type optimizations, where most let arrays would be flattened down to registers anyway.

This had been our assumption, too, but apparently these optimizations are not applied consistently. Our user encountered problems on iOS: some devices would apparently optimize it out, while others did not.

**Comment by litherum** [comment]
If we are talking specifically about large arrays (as opposed to small arrays) then they presumably wouldn't fit into registers in the first place, and the array would always live in memory regardless of whether it's a var or a let.

**Comment by ben-clayton** [comment]
To my knowledge, Naga and Tint are the only 'mature' WGSL compilers in existence right now. Tint does not change code paths based on architecture, with exception to customisable transforms - e.g. software robustness may soon be relaxed if it is known the device provides faster robustness via hardware.

Tint has so far tried to not be an optimizing compiler, but we have had bug reports that some drivers perform badly with certain patterns of emission (not related to this topic). We may, eventually, want to adjust our codegen for these cases, but we'd prefer to have a single codepath instead of the slippery slope to permutation explosion.

**Comment by kvark** [comment]
I see this depending on the following factors:
  1. how easy it is for us to polyfill. Our previous approach in Naga wasn't very nice at all, and I'm glad it's scraped. @jimblandy has ideas on how to do it differently, so it may become more feasible.
  2. how likely is the driver to optimize our SPIR-V output (as opposed to just giving up and letting it be slow). We can check the produced AMD ISA, at least, via https://shader-playground.timjones.io/ and such.
  3. if we proceed with this, what would be the point of "let" (re #2207)? For example, can `let` serve as a read-only reference, e.g. for taking a pointer to something? Aligning with SPIR-V at least was giving us a strict and clear guideline on what "let" is. Dropping this would mean a bit of an existential crisis for it.

**Comment by dneto0** [comment]
On 3.   I don't see a crisis.  A 'let' is a lexically scoped name for a _value_, which can be constructible, or a pointer.  (the latter case only for those declared inside a function).  A pointer is not storable, and so can't be put into a var.

**Comment by kvark** [comment]
Now that you spelled it like this, it sounds good :)
So `let` is a named value, while `var` is a named memory reference.

**Comment by litherum** [comment]
Does this require more CG discussion?

**Comment by dneto0** [comment]
I don't think so.  I plan to proceed to PR to re-allow dynamic indexing of array and matrix values.
