### ISSUE TITLE
WebGL - WebGPU interoperability

### ISSUE THREAD

**Issue by astojilj** [gpuweb/gpuweb#18]
This would enable incremental porting of WebGL apps to WebGPU and access to specific WebGPU features from WebGL apps (e.g. #17).

Related material:

- [Direct3D 11 on 12 (Windows) - MSDN - Microsoft](https://msdn.microsoft.com/en-us/library/windows/desktop/dn913195(v=vs.85).aspx)
- https://www.khronos.org/registry/OpenGL/extensions/NV/NV_draw_vulkan_image.txt
- [OpenGL with Metal](https://forums.developer.apple.com/thread/4828)

Cost of transferring the data could be reduced using shared graphics memory (IOSurface, libdrm GBM...)

**Comment by dmikis** [comment]
I think, we can expose as a WebGL 1.0/2.0 extension with bunch of functions that return aliases for WebGPU object, like, `WebGLTexture` for WebGPU texture descriptor.

**Comment by Kangz** [comment]
Some sort of interoperability with WebGL is important, but like @dmikis pointed out, the lifetime and synchronization will be hard to specify if the shared objects are at the same time in WebGL and WebGPU.

Another problem is that it might not be possible to share the underlying object without copies on all combinations of WebGL backend API and WebGPU backend API and it isn't clear. Because of this, it seems that copy or ownership transfer semantics are necessary.

Also it isn't clear how much can be shared across all backend combinations. Single-level textures with standard formats seem like safe bets but what about mip-complete textures and buffers?

**Comment by litherum** [comment]
Aliasing objects between APIs is only possible if the underlying platform supports it, and I don't believe that all three implementation API's (and all platforms they run on) support it.

Copying textures and buffers seems reasonable as long as a conformant implementation is allowed to copy the data to the CPU and back again (but this definitely shouldn't be required if the underlying platform can copy them without them leaving the GPU).

Not sure if this should make it into the minimum viable product.

**Comment by Kangz** [comment]
Closing. We discussed this with the group previously and added copy-interop through canvas. Further proposals can be in new issues.
