### ISSUE TITLE
WGSL code containing \0

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1816]
Implementations may want to pass WGSL code around as null-terminated strings. If we want to allow that, we need to be able to validate out null characters `\0` before doing so. However we could also choose to allow it, in which case WGSL code must be passed around in a std::string-like form (raw bytes with length).

Tests for a similar issue, `\0` in entryPoint, were recently added:
https://github.com/gpuweb/cts/pull/569/files#diff-95d8e237db97202689ef603356ec65a9fd67a11264568fb8067a8fd5ca61464eR149
This is an easier problem since `\0` is never valid in `entryPoint` so it can be validated out early. And searching for `\0` in an `entryPoint` string is cheap since they are very short.

**Comment by kainino0x** [comment]
Discussed in the meeting and I think there is no particular desire to disallow null characters for the sake of allowing implementations to use null-terminated strings. The pre-scan step to discover null characters in the passed `USVString` is not an appealing implementation choice.

TBD whether comments do, or should, allow null characters. By default, I would assume they do since comments should be allowed to include "any" character.

For some background: anecdotally, I tried compiling this C program

```c
int main() {
    // 
}
```

with `clang -Weverything -Wno-poison-system-directories -Wall -Wpedantic -Werror main.c -o main`,
and it succeeded.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-06-08-Minutes#httpsgithubcomgpuwebgpuwebissues1816">WGSL meeting minutes 2021-06-08</a></summary>



*   KN: If null-char can exist inside the source, we need to hold (data,size), and not just (null-term-data,).
*   MM: And this comes up because of a C-api?
*   KN: Yes, for Dawn.
*   MM: Not that sympathetic to constrain ourselves because of this.
*   BC: Does unicode allow this?
*   MM: Null bytes are valid but not null code points.
*   KN: Pretty sure zero is a code point?
*   MM: No.
*   KN: So utf-8 has a non-zero alternative to allow zeros without null-term problems.
*   JG: USVStrings allow zero scalars, so we do accept that today at least.
*   MM: Well, I think our grammar forbids zero chars.
*   KN: Maybe not in comments though.


</details>

**Comment by Kangz** [comment]
+1 the C API of Dawn shouldn't matter (plus we can easily add a size to the API where 0 mean "use strlen").
