### ISSUE TITLE
Questions about copyExternalImageToTexture

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#1821]
I'd like to ask 2 questions about ```copyExternalImageToTexture()``` in current WebGPU SPEC:

1. In WebGL we can directly pass an ```HTMLImageElement``` into ```texImage2D()``` to upload the image data into a 2D texture, while with ```copyExternalImageToTexture()``` I cannot. Do you think it better to also allow copying from an ```HTMLImageElement``` with ```copyExternalImageToTexture()``` in WebGPU?

2. It may be a bit hard to understand that although ```copyExternalImageToTexture()``` looks like a "copy" API, we are also required to pass a texture with a ```TextureUsage.RenderAttachment```. Shall we introduce a new usage (maybe something like ```TextureUsage.COPY_FROM_EXTERNAL```) for the textures that will be used in ```copyExternalImageToTexture()```, so that we can better hide some implementation details and provide some opportunities for optimization?

**Comment by Kangz** [comment]
> Do you think it better to also allow copying from an HTMLImageElement with copyExternalImageToTexture() in WebGPU?

I think the reason why it's not allowed is that passing an `HTMLImageElement` directly could be a "blocking" operation that forces an image decode plus GPU upload right there. Instead application should use the asynchronous `createImageBitmap` to be non-blocking.

> Shall we introduce a new usage (maybe something like TextureUsage.COPY_FROM_EXTERNAL) for the textures that will be used in copyExternalImageToTexture(), so that we can better hide some implementation details and provide some opportunities for optimization?

My understanding is that the addition of the two usage flags is to make sure developers are aware of the additional cost that `copyExternalImageToTexture` has. If you are ok having your image as `RENDER_ATTACHMENT` as well, then you can do it directly, otherwise if it is a big issue to you, you can do the extra copy into a non-attachment texture yourself. This is to make the API very explicit.

**Comment by kainino0x** [comment]
Some thoughts I have about COPY_FROM_EXTERNAL:

- If there are any applicable rules about which usages can be used together, validation would be equivalent to passing `COPY_DST | RENDER_ATTACHMENT`.
- Which usage actually gets used is dependent not only on the implementation but also on the source image. So the implementation would translate this to `COPY_DST | RENDER_ATTACHMENT` anyway unless they have *no* paths that use one of them.

**Comment by Jiawei-Shao** [comment]
All right. Thanks for your explanations!
