### ISSUE TITLE
Web IDL hiccup in GPUPresentationContext: Dictionary arguments cannot be nullable

### ISSUE THREAD

**Issue by tidoust** [gpuweb/gpuweb#1822]
@toji, #1810 introduced the [`GPUPresentationContext`](https://gpuweb.github.io/gpuweb/#presentation-context) with a `configure` method that takes a nullable dictionary as argument:
```
undefined configure(GPUPresentationConfiguration? configuration);
```

Nullable dictionary arguments are [not allowed in Web IDL](https://heycam.github.io/webidl/#idl-nullable-type): "Although dictionary types can in general be nullable, they cannot when used as the type of an operation argument or a dictionary member". This makes the Web IDL checker sad.

**Comment by toji** [comment]
Ah, that's too bad. So the alternatives to this that I can think of would be:

 1. Have an explicit `unconfigure()` or similar method.
 2. Allow `device` and `format` to be optional, and if `device` isn't specified then we unconfigure.
 3. If the configured device calls `device.destroy()` unconfigure any contexts using that device. (Not really a full replacement, but it prevents garbage collection issues in the worst case)

**Comment by toji** [comment]
Fourth option, after some internal discussion:

4. Don't have any explicit way to unconfigure, but ensure that the behavior is specced such that developers can't observe whether the `device` is GC or not when the context is the only thing keeping it alive. (Neither the context nor the returned textures will give you a direct reference to the `device`, and the textures can be returned as invalid and without the device to use them with you'll never know the difference.) That way implementations can choose to use a weak reference to the device as an implementation detail.

**Comment by kainino0x** [comment]
I brought up 4 again because I wasn't convinced whether it's possible or not. Thinking back to the conversations we had Monday again, `invalid_texture.createView()` is supposed to send an error to the texture's device. In order to do that, the texture still needs a reference to the device, and device holds the error scope and `uncapturederror` event handlers. This means a weak reference wouldn't work.

**However,** error scopes stop working once the device is lost for any reason (including destroyed), and `uncapturederror` is not guaranteed to always fire anyway, especially after the device is lost. So this only presents a problem for GPUDevices that are dropped without being destroyed/lost. If the GPUDevice is dropped, then it's impossible to `popErrorScope()`, so that state doesn't matter. Since `uncapturederror` is not guaranteed to fire, it would probably be okay for GC to be pseudo-observable by effectively saying "before GPUDevice is GCed, `uncapturederror` _may_ be fired (iff there were no active error scopes); afterward, it _won't_ be fired."

So I think it is possible for GPUPresentationContext to hold a weak reference to the device, and when necessary vend some kind of empty-shell invalid GPUTexture from thin air in `getCurrentTexture()`.
Of course, this is nontrivial to implement, but implementations don't actually have to do this (it's just an implementation detail for cleaning up memory for non-lost dropped devices). We can add the API surface later if we find out it's not implementable.

**Comment by tidoust** [comment]
Calling `configure` with `null` to un-configure seems a bit counter-intuitive to me but, if you wanted to do something like that, couldn't you just make the parameter `optional`?

```
undefined configure(optional GPUPresentationConfiguration configuration);
```

From a spec perspective, you'd get an `undefined` instead of a `null` in step 5: "If configuration is **undefined** return."

**Comment by toji** [comment]
That works too! Although I have to say I'm honestly surprised that `optional Dictionary foo` is allowed while `Dictionary? foo` is problematic? They seem like effectively equivalent cases to me in terms of disambiguation, so much so that I didn't even consider it as an alternative till you mentioned it just now.

**Comment by tidoust** [comment]
I do not know :) And I now realize that my suggestion is not valid WebIDL either because of a relatively recent change (https://github.com/w3c/webidl2.js/pull/571) that also rejects an optional dictionary argument without a default value (I don't yet see that clause in the WebIDL spec though).

Having a default value of `{}` seems to please the WebIDL checker, but given the `required` members in `GPUPresentationConfiguration`, I don't believe that `{}` can be a valid default value...

Perhaps @saschanaz can shed some light on the ins and outs of nullable and optional dictionaries?

**Comment by saschanaz** [comment]
>while `Dictionary? foo` is problematic?

That's because `null` can be converted to dictionary and thus dictionaries are implicitly nullable (see also https://github.com/heycam/webidl/issues/967). Passing `null` for a dictionary param is just like passing `{}`.

Making it optional doesn't seem to be an option here either, as @tidoust noted.

**Comment by kainino0x** [comment]
Thanks for the help!

I think we should just make it a separate `.unconfigure()` method, if we decide we need it at all.

**Comment by toji** [comment]
> I think we should just make it a separate `.unconfigure()` method, if we decide we need it at all.

Agreed, though I'm definitely leaning towards not needing a way to explicitly unconfigure at this point. (I question how many people will think to use it even if it's available.)

**Comment by kainino0x** [comment]
Editors: Turns out unconfigure still has utility: it allows releasing handles to any resources held by the canvas (similar to buffer.destroy) without destroying the whole device.

configure() to stay as is but not nullable.
