### ISSUE TITLE
Out of bounds behaviour and atomics

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#1868]
```
[[block]] struct S {
  x : array<atomic<u32>, 4>;
};

[[set(0), binding(0)]] var<storage, read_write> v : S;

[[workgroup_size(1,1,1)]]
[[stage(compute)]]
fn foo() {
  let x = atomicExchange(v.x[4], 1);
}
```

The example contains an invalid memory reference to an atomic. The spec currently deals with invalid memory references for providing a range of behaviours for out of bounds accesses. Should atomics be treated the same way? Or should be just say behaviour is undefined for an invalid memory reference used with an atomic?

**Comment by jdashg** [comment]
I feel like we don't need to say anything in particular about atomics here: It's a question of what you get indexing off the end of an array for a non-trivial type (here `atomic`). I think we guarantee that you get something safe-but-unreliable: clamp/wrap/zero/drop

**Comment by pow2clk** [comment]
Regarding HLSL atomic OOB functionality, see [this example](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#22.17.24%20imm_atomic_iadd%20(Immediate%20Atomic%20Integer%20Add%20To/From%20Memory)) Where u# is a UAV buffer and g# is groupshared memory.

                Out of bounds addressing on u#
                causes nothing to be written to memory, except:
                If the u# is structured, and byte offset into
                the struct (second component of the address)
                is causing the out of bounds access, then the
                entire contents of the UAV become undefined.

                Out of bounds addressing on g#
                (the bounds of that particular g#, as
                opposed to all shared memory) causes
                the entire contents of all shared memory
                to become undefined.

                Out of bounds addressing on u# or g#
                causes an undefined result to be returned
                to the shader in dst0.

A lot of undefined behavior up there I know. Worth noting is that the worst case for UAVs is limited to when it's a raw buffer

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-08-03-Minutes#out-of-bounds-behaviour-and-atomics-1868">WGSL meeting minutes 2021-08-03</a></summary>



*  JG: I’m not convinced by what I wrote
* AB: The spec has a problem. It only talks about loads and stores. Maybe it at least needs something saying atomic operations are atomic. The way it describes stores, the store may not occur… it would be bad if half the atomic occurs. It should say the atomic operates on a single address and is atomic
* JG: We should aim for that
* JG: If you access out of bounds, fundamentally you’re getting the address of something, and you do the operation on that address. 
* AB: That would be a good conception
* AB: You might have to clamp atomics, so that you get an address
* AB: The spec only describes what happens with OOB loads and stores. Which load/store behavior occurs for atomics? Do they occur independently?
* AB: Vulkan, without robust buffer acces 2 says atomics are undefined.
* AB: We’d want to make sure that an atomic will hit some address in range.
* MM: What does this disallow?
* AB: I wouldn’t want you to be able to get a 0 out of it, but write a real value into it. If the old value wasn’t 0, just returning 0 makes a lot of sense, if you’re going to write what’s at the atomic
* AB: Right now, the spec says atomics do a load and a store. If it’s OOB, I could load to some random address that’s in bounds, and could store to some other random address that’s in bounds. Something is missing.
* AB: Depending on how you would describe +=, it may work like a load/store
* JG: In terms of conceptually, a += would have the same, it’s a load and a store, and the spec allows them to come from different places
* JG: This should be true on all operations that involve a load and a store. Not just atomics
* AB: That’s fine
* MM: += is kind of different
* JG: We’ve postponed +=
* MM: What if the atomic straddles the end of the buffer?
* JG: Loads/stores that straddle the end of a buffer are considered fully OOB.


</details>

**Comment by kdashg** [comment]
@alan-baker Was this handled by #2016?
