### ISSUE TITLE
[wgsl] functions with return values + return + control flow

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#1897]
Currently, [the spec says](https://gpuweb.github.io/gpuweb/wgsl/#function-declaration-sec):

> If the return type is specified, then:
>   * The return type must be constructible.
>   * The last statement in the function body must be a return statement.

However, this can be non-obvious to programmers of other languages. What about cases like this?

```wgsl
fn GetFloat(v: uint) -> float {
    if (v == 0u) {
        return 3.0f;
    } else {
        return 5.0f;
    }
}
```

Or:

```wgsl
fn GetFloat(v: float) -> float {
    while (true) {
        return v;
    }
}
```

Should we consider relaxing this rule and just make sure that any control flow has a valid return?

**Comment by dneto0** [comment]
That's a good point.

We used to have a rule that every function body had to end with a return statement. But we took that out for functions without a return type.  What we have left here might be a leftover from that original thinking.

There may be utility in trying to ensure that, assuming there are no infinite loops, all control paths end at a return statement.  But the stated condition is not precise, as both your examples show.  

Maybe I/we were thinking of a static approximation to ensuring all control paths ended in a return.  For example, "ignoring the condition on each branch, all control paths must reach a return". (that is, assume all branches are eventually taken).
Your first example would satisfy the static condition, but the second would not (because we ignore fact the condition on the loop is 'true').

The group should consider this.

**Comment by dneto0** [comment]
(Fortunately, the programmer can always easily write a return to statisfy the condition, because the return type is constructible, and hence has an easy syntax for a zero value: the type followed by empty parentheses.)

**Comment by Kangz** [comment]
I think the behavior analysis in the spec correctly handles this now. https://gpuweb.github.io/gpuweb/wgsl/#behaviors however there is still this constraint in the spec: "The last statement in the function body must be a return statement." @dneto0 or @RobinMorisset can it be removed and used the behavior analysis instead?

**Comment by RobinMorisset** [comment]
I agree that this is subsumed by the behavior analysis, and the sentence you quoted is obsolete and should be removed.
