### ISSUE TITLE
WGSL: Allow global let-declarations initialized with constant expressions

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#1911]
Current WGSL SPEC only [allow global let-declarations initialized with `const_expr`, and `const_expr` only accepts `const_literal`](https://gpuweb.github.io/gpuweb/wgsl/#module-constants).

It would be convenient for developers to support initializing global `let`-declarations with "constant expressions" not just "constant numbers". For example, the following WGSL expressions will become valid after WGSL supports initializing global `let`-declarations with "constant expressions":

```
let size: u32 = 4u * 5u;

let a: u32 = 4u;
let b: u32 = a;
```

**Comment by dneto0** [comment]
This would actually help SPIR-V compatibility.   SPIR-V allows certain "compile"-time expressions via [OpSpecConstantOp](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpSpecConstantOp), covering:
- negation, 4 binary arithmetic operations
- bitwise operations
- most comparisons
- select
- shifts
- vector shuffle
- composite insert and extract
See the explicit list at the instruction description.

We've held off proposing this because of engineering workload, both for implementing and also CTS-testing the feature.

There are interactions with other things, e.g. pipeline-overridable constants, and proposed array-sizing (#1792).
Some validation might only be possible at pipeline-creation time, and that would require an expression evaluator.

**Comment by dneto0** [comment]
This overlaps a lot with #1272

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-07-13-Minutes#wgsl-allow-global-let-declarations-initialized-with-constant-expressions-1911">WGSL meeting minutes 2021-07-13</a></summary>



*  MM: We sort of need to spec constant expressions first
* JG: Don’t we have some hacked version of this?
* MM: Something like “just literals”. I think we should postpone after mvp
* JB: What about just allowing constant idents too?
* DM: Constants or spec-constants
* JB: Probably just constants for now?
* DN: Happy to push off to mvp. Worth noting, SPIR-V has a description of const-expr that we can work from. 
* (push to mvp)


</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-03-minutes#wgsl-allow-global-let-declarations-initialized-with-constant-expressions--issue-1911">WGSL meeting minutes 2022-05-03</a></summary>



* KG: Post v1 thing, maybe?
* MOD: No global let
* AB: Have const instead of global let. Closed as worked out a different way


</details>
