### ISSUE TITLE
MSL does not support address-of vector component

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#1931]
WGSL currently allows address-of vector component, e.g.:
```
{
  var v = vec4<f32>();
  let vp = &v.w;
  ...
  *vp = 1.0;
}
```

MSL does not support an equivalent syntax using either component accessors or array indexes:
```
foo.metal:6:22: error: address of vector element requested
  thread float* vp = &v.w;
```
```
foo.metal:6:22: error: address of vector element requested
  thread float* vp = &v[3];
```

The only wording around this that I could find in the MSL spec was "A pointer or reference to a vector with swizzles is an error".  I'm not sure that `&v[3]` is classed as a swizzle, but the MSL compiler rejects that code anyway.

You can workaround this with pointer casting:
```
float4 v;
thread float* vp = ((thread float*)&v) + 3;
```
But it's unclear whether this is supposed to be valid or not, and therefore we might not be able to rely on this approach.

So, I think we should consider whether WGSL should drop support for address-of vector component. I struggle to think of any use cases for this given all the other restrictions we have around pointers (you cannot pass a pointer-to-vector-component to a user-defined function, for example).

**Comment by alan-baker** [comment]
If we do want to prevent this, it should be as simple removing the reference version of vector access expressions.

**Comment by kvark** [comment]
@alan-baker that would mean we can't do `vector.y = 1.0` any more.

**Comment by dneto0** [comment]
Slightly related #2152 which says that when you write to a vector component, the other components may be written too.

**Comment by litherum** [comment]
Some notes from today's discussion:

1. The relevant spec change would be something like "you can have a ref of a member of a vector but not a pointer to a member of a vector"
2. We have to determine what to do with matrices (which may or may not match what we're doing with vectors)
3. Two potential implementation strategies:
  a. Model a pointer to a member of a vector as a pointer to the vector and a field to tell you which member it references
  b. Don't use vectors and instead use arrays (where necessary)

**Comment by litherum** [comment]
The 3a. strategy would mean we might have to duplicate functions if they have a parameter of `ptr<float>` if it was called twice, one with a regular float pointer and one with a pointer into a vector.

**Comment by litherum** [comment]
I'm discussing this with the Metal team.

**Comment by dneto0** [comment]
That case won't be needed because there's a [restriction](https://gpuweb.github.io/gpuweb/wgsl/#function-restriction) on pointer parameters:

> Each argument of pointer type to a user-defined function must be one of:

> * An address-of expression of a variable identifier expression

> * A function parameter

So, for example, this is invalid:

```rust
fn foo() {
   var a: vec4<f32>;
   bar(&a.x); // invalid
}
```

**Comment by dneto0** [comment]
There is also another mitigation strategy which is:
 3c.  Sink the pointer calculation to its uses.  This is what Tint does (example below).  

This relies on the fact that you can do very few things with a pointer.   All essential uses are either immediately surrounded in an expression (conversion back to a reference), saved into a let-declaration, or passed as a function formal parameter. 

Conversion back to a reference: This is uninteresting, because then you don't have a pointer anymore.

Passed as a function formal parameter:  The bad case is banned by a function parameter restriction.

Saving into a let-declaration with identifier, say, *P*.  This is the interesting case.  Then any use of the pointer is in scope of that declaration of *P*.  The let-declaration's initializer expression is either:
-  an identifier, *Q* (yet another let-declaration, or a function parameter).  Now replace uses of *P*'s in scope with *Q*, while renaming any shadowed *Q*s.  (*Q*'s scope is a superset of the scope of *P*).
- an address-of expression.  Recurse. Otherwise, the remaining interesting case is where it's address-of a single-letter swizzle, or an array-like subscript.  
     - if it's a single-letter swizzle, then sink the address-of the single-letter swizzle to uses.
     - if it's an array-like subscript, then save the index in a hoisted variable, and sink the address-of array-like subscript to the uses.

So that's the transform that requires no changes in underlying data representation, either of the vector or of the pointer type.


This is essentially what Tint does.

Here's the case where it sinks let-declared pointer of address-of a .x swizzle:

```rust
[[block]] struct B {
  cond: i32;
  a: vec4<f32>;
};

[[group(0), binding(0)]]
var<storage,read_write> b: B;


[[stage(fragment)]]
fn main() -> [[location(0)]] vec4<f32> {
   let p = &b.a.x;           ////////////// address of a .x reference
   if (b.cond < 0) {
     *p = 12.0;
   } else {
     *p = 0x1.0p20;
   }
   return vec4<f32>();
}

```

`tint --format msl c.wgsl` yields:
```c
#include <metal_stdlib>

using namespace metal;
struct B {
  /* 0x0000 */ int cond;
  /* 0x0004 */ int8_t tint_pad[12];
  /* 0x0010 */ float4 a;
};
struct tint_symbol_1 {
  float4 value [[color(0)]];
};

float4 tint_symbol_inner(device B& b) {
  if ((b.cond < 0)) {
    b.a.x = 12.0f;
  } else {
    b.a.x = 1048576.0f;
  }
  return float4();
}

fragment tint_symbol_1 tint_symbol(device B& b [[buffer(0)]]) {
  float4 const inner_result = tint_symbol_inner(b);
  tint_symbol_1 wrapper_result = {};
  wrapper_result.value = inner_result;
  return wrapper_result;
}
```


This shows sinking of a subscripted array:
```rust
[[block]] struct B {
  cond: i32;
  a: vec4<f32>;
};

[[group(0), binding(0)]]
var<storage,read_write> b: B;


[[stage(fragment)]]
fn main() -> [[location(0)]] vec4<f32> {
   var i: i32;
   let p = &b.a[i]; //////////  subscripted component selection
   if (b.cond < 0) {
     i = 1;  // intentionally overwrite the index.
     *p = 12.0;
   } else {
     i = 2;
     *p = 0x1.0p20;
   }
   return vec4<f32>();
}
```

and the result
```c
#include <metal_stdlib>

using namespace metal;
struct B {
  /* 0x0000 */ int cond;
  /* 0x0004 */ int8_t tint_pad[12];
  /* 0x0010 */ float4 a;
};
struct tint_symbol_1 {
  float4 value [[color(0)]];
};

float4 tint_symbol_inner(device B& b) {
  int i = 0;
  int const p_save = i;
  if ((b.cond < 0)) {
    i = 1;
    b.a[p_save] = 12.0f;
  } else {
    i = 2;
    b.a[p_save] = 1048576.0f;
  }
  return float4();
}

fragment tint_symbol_1 tint_symbol(device B& b [[buffer(0)]]) {
  float4 const inner_result = tint_symbol_inner(b);
  tint_symbol_1 wrapper_result = {};
  wrapper_result.value = inner_result;
  return wrapper_result;
}


```

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-10-05-Minutes#msl-does-not-support-address-of-vector-component-1931">WGSL meeting minutes 2021-10-05</a></summary>



* MM: Haven’t heard anyone complain about MSL not supporting this. Would rather forbid in the language than try to emulate somehow.
* DN: One approach would be to translate vec4 as float[4], which would work in MTL. There could be a perf cliff, but that’s up to the user to run into and solve if needed. 
* MM: Seems scary. E.g. builtins would need to handle both? Go in and out?
* DN: Yeah, but that’s probably ok? I think we’re investigating it. I’m pretty aggressive about this one, and we’re not at-consensus within Google yet.
* MM: So you may have already paid the implementation cost, and you are evaluating the perf cost. How do you feel about my assertion about usefulness?
* DN: I feel like removing this adds an orthogonality to the language, which I would like to avoid.
* DM: Maybe could have reference to the element of vector, but not a pointer to the element of the vector?
* JB: So we’d have a carve-out to forbid converting certain refs into pointers?
* JB: Maybe we should ask MSL people, if they were to support this, how would they do it?
* MM: Can’t speak for them, but I expect them to say “drivers don’t have that functionality”.
* **Check back next meeting, but no promises**


</details>

**Comment by dneto0** [comment]
(Reminder: the "sink the pointer calculation" is a fine implementation, just as performant as what a user would write.)

Meanwhile, let me revisit this:

> https://llvm.org/docs/GetElementPtr.html#can-gep-index-into-vector-elements

I traced this back through history, to this, from February 2010:

https://github.com/llvm/llvm-project/commit/f51af9d2017ab7062c77dd9c6073d082b668854c#diff-d1467b767ede3f08a4d7183a6f0ca51749960b5efd8bb09ca775ec64c61e5ca5R276 

Where it says:

> Instead, you should cast your pointer types and use arrays instead of
     vectors for addressing. Arrays have the same in-memory representation
     as vectors, so the addressing is interchangeable.

That's mitigation strategy 3b.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-02-Minutes#msl-does-not-support-address-of-vector-component-1931">WGSL meeting minutes 2021-11-02</a></summary>



* See also [PR #2225: Disallow taking the address of a vector component](https://github.com/gpuweb/gpuweb/pull/2225)
* DN: There’s a PR based on what we decided. It’s not type-based, but it does the thing we need. I think we can land.
* MM: +1
* **Resolved: Merge**


</details>

**Comment by dneto0** [comment]
@ben-clayton has implemented source-to-source transforms which can sink pointer calculations into its uses. The intra-procedural form of it is part of Tint's production flow for the HLSL backend. The inter-procedural form is prototyped (with tests) and described here: https://github.com/gpuweb/gpuweb/issues/3276#issuecomment-1267798197 

You might think that applying that transform here would allow us to circumvent this limitation in MSL.
It would, but it would break semantics because it could transform a program that does not race into one that does race.
That is, a program that has two invocations writing to components 0 and 1 respectively, would be transformed into one where both MSL threads write to the whole vector (non-atomically), and therefore race against each other.

**Comment by jrprice** [comment]
@dneto0 
>  a program that has two invocations writing to components 0 and 1 respectively

This is already considered to be a race in WGSL. See [Component Reference from Vector Reference](https://gpuweb.github.io/gpuweb/wgsl/#component-reference-from-vector-reference):

> A write access to component of a vector may access all of the memory locations associated with that vector.
> > Note: This means accesses to different components of a vector by different invocations must be synchronized if at least one access is a write access.
