### ISSUE TITLE
builtin attributes on struct members

### ISSUE THREAD

**Issue by sarahM0** [gpuweb/gpuweb#1981]
Based on https://www.w3.org/TR/WGSL/#builtin-variables, is this example valid? My understanding is that the builtin attribute on struct members is ignored when used in a wrong stage (to facilitate data movement between different stages).

> struct S {
>   [[builtin(frag_depth)]] depth: f32;
>   [[builtin(front_facing)]] face: bool;
> };
> [[stage(fragment)]]
> fn fs_main() -> [[location(0)]] f32 {
>   var s : S;
>   s.face = true; // builtin(front_facing) is only valid in vertex stage. Also it's an input.
>   return 1.0;
> }
> [[stage(vertex)]]
> fn main() -> [[builtin(position)]] vec4<f32> {
>   var s : S;
>   s.depth = 1.0; // builtin(frag_depth) is only valid in fragment stage.
>   return vec4<f32>();
> }
> 

How about this case?

> struct MyInputs {
>   [[builtin(frag_depth)]] ff: f32;
> };
> [[stage(fragment)]]
> fn fragShader(arg: MyInputs) -> [[location(0)]] f32 { return 1.0; } // builtin(frag_depth) is an output of a fragment stage.

**Comment by kvark** [comment]
I believe the spec allows all of them. Do you see particular issues with translating this WGSL code into backends?

**Comment by sarahM0** [comment]
Is this also allowed?

> struct MyInputs {
>   [[location(0)]] ff: f32;
> };
> [[stage(compute), workgroup_size(1)]]
> fn main(arg: MyInputs) {}

**Comment by alan-baker** [comment]
The struct is ok, but `main` is not because compute shaders do not accept user-defined inputs (or outputs).

**Comment by sarahM0** [comment]
> struct MyInputs {
> [[location(0)]] ff: mat2x2<f32>;
> };
> fn main(arg: MyInputs) {}

Do we need to check the type of struct member with location attribute if it's not used in entry-points? Spec says: Must only be applied to declarations of numeric scalar or numeric vector type.

I find rules of applying attributes to struct members confusing. Like in this case we are ignoring [[location(0)]] and using this struct as parameter type of a non-entry point function. However we need to check the type. Same with builtin attributes.

**Comment by alan-baker** [comment]
I think this is an error because you should check the type. The spec is trying to strike a balance between usability and specificity. We ignore the attribute in some cases to increase usability, but I don't think that extends to this struct because the matrix could never be used as a user-defined IO. 

Which part of the spec is unclear to you? Where the attribute is ignored or the restrictions on where it can be applied?

**Comment by sarahM0** [comment]
Restriction are well-defined.

Where the attribute is ignored, ie. where in spec I can look to find my very first example is valid because builtins are ignored?

**Comment by dneto0** [comment]
> Where the attribute is ignored, ie. where in spec I can look to find my very first example is valid because builtins are ignored?

I think it's a consequence of _not_ having a "must" rule to disallow it.

The only "must" rule about which stage applies to a builtin is at the end of [built-in inputs and outputs](https://gpuweb.github.io/gpuweb/wgsl/index.html#builtin-inputs-outputs):

> Each built-in variable has an associated shader stage, as described in § 15 Built-in variables. If a built-in variable has stage S and is used by a function F, as either an argument or the result type, then F must be a function in a shader for stage S.

So it's the phrase "as either an argument or the result type" that limits the effect of the rule.  Outside the use as entry point parameter or return, the rule does not take effect.

That's the technicality as to why the stage limitation can be ignored.

The wider question is:  Is that confusing, or good enough for users.  I think it's subtle, and potentially confusing to users, and also potentially confusing to implementors. It may be worth thinking about restricting further (without much complexity) to avoid confusions.

Short of that: we may want to add an example to the spec showing that these kinds of cases will be ignored. They are not recommended (because they are confusing), but they are valid, and to explain why.

(nitpick. builtin(front_facing) is a fragment input builtin; but the overall point of the example holds by using the vertex_index vertex builtin input instead.)


For the second example, you show a fragment output builtin used as a fragment input.
That's a great example!   Technically, I think the example is allowed but seems like we *should* disallow it:  I can't think of a good use case for mixing like that, and it's very confusing.
I think we should expand that rule I quoted above, to say that directionality (input vs. output) matters also.

Lastly, the whole discussion of builtin-inputs and outputs uses the term "variable" which is wrong, i.e. inconsistent with what should be the one and only definition of [variable](https://gpuweb.github.io/gpuweb/wgsl/index.html#variable), i.e. a named reference to typed storage, distinct from all other memory allocations.  Editorially we should fix that or people will be confused forever.

So my takeaways:
- for first example, at very least show an example in the spec of what is valid but not recommended (except to facilitate sharing)
- for second example:  make directionality matter for validity of builtin inputs and outputs
- find a term other than "variable" for builtin inputs and outputs.

Assigning to myself to propose something.

**Comment by dneto0** [comment]
Another thing comes to mind.
Can I use the same builtin-and-direction multiple times in the same entry point.  I think that's silly, and should be disallowed.


      [[stage(fragment)]] fn main(
          [[builtin(position)]] apos: vec4<f32>,
          [[builtin(position)]] bpos: vec4<f32>  // Silly and useless.
      )   -> [[location(0)]] vec4<f32> {  return vec4<f32>(); }


That might mess up location slot accounting too. So I think it should be banned.

Direction is significant because sample_mask is used as a fragment input and output.  That's still ok, just like location allocation is distinct between inputs and outputs.

**Comment by kvark** [comment]
Agreed, @dneto0 , no need to allow this multiple usages thing (in one direction).

**Comment by kdashg** [comment]
We think this is done and tested now.
