### ISSUE TITLE
Require loops to terminate

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#1987]
The DXC and FXC HLSL compilers will error if they detect a loop does not exit.
Examples:

[`while(true) {}`](http://shader-playground.timjones.io/b83876045a232ce4d8cebc6c8f87a8c3)
[`for(;;) {}`](http://shader-playground.timjones.io/1f0322390f11d2f2d13a35c5eda83c1a)

Inserting a `if(false) { break; }` is enough to trick FXC into accepting the shader, but DXC is smarter and sees through this.

Ideally, we'd have the WGSL compiler catch these patterns instead of having backend-compilers produce errors, as this is an easy way to produce non-portable code. If we did want to add rules to the spec, I don't know how far we'd want to go with the analysis here.

Related to uniformity analysis (#264, #340, #669).

**Comment by kvark** [comment]
Doesn't the uniformity analysis need to know what kind of exits exist for each statement (like the loop), already? In this case, we'd just piggy-back on it.

**Comment by hujiajie** [comment]
Hello! We have a probably related question while optimizing TensorFlow.js (details linked right above). Our loop looks like this:

```
var success = 0;
for (; success == 0;) {
    ...
    let resValue = atomicCompareExchangeWeak(...);
    success = resValue[1];
}
```

As human developers, we are pretty sure the algorithm can be finished in finite steps, but will the WGSL compiler be clever enough to tell the effect of `atomicCompareExchangeWeak()`? Or is there any risk of being unable to prove the uniformity here (and therefore this shader will be rejected)?

**Comment by jdashg** [comment]
Probably no uniformity issues, probably don't expect compilers to figure out that this will terminate.
We probably want to try to reject shaders that anyone (e.g. DXC) rejects, but also if they get real heroic about it, I don't want to sign us up for trying too hard.

**Comment by hujiajie** [comment]
@jdashg Thanks! Will "shaders that anyone rejects" be spec-ed, or browser implementation defined?

**Comment by amaiorano** [comment]
Hello, I've done a bunch of investigation into this issue with FXC/DXC, and have even come up with a [possible workaround](https://bugs.chromium.org/p/tint/issues/detail?id=1038#c13). However, the fact that FXC/DXC can detect infinite loops is actually useful to the user. So instead of trying to make FXC/DXC compile code with infinite loops, I would like to propose that we add to the WGSL spec that **loops that do not terminate are undefined behaviour**.

**Comment by alan-baker** [comment]
I'd suggest putting a line in the API side that says something to the effect of "shaders must terminate".

**Comment by dneto0** [comment]
> I'd suggest putting a line in the API side that says something to the effect of "shaders must terminate".

Yes, that covers the dynamic case.  That's needed because static analysis can't be perfect, and we still need to tell developers that non-termination is their bug.  Typically a watchdog timer will expire and the OS will kill the process; details vary by platform

The original issue is about static analysis.  The behaviour analysis rules include:

> Behavior analysis [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) be able to determine a non-empty [behavior](https://gpuweb.github.io/gpuweb/wgsl/#behavior) for each statement, expression, and function.

In the case of a loop,  the loop body (not the continue construct) must include a break, return or discard, effectively.  And a continue construct may include a break right at its end.

So I think the static analysis aspect is covered.

I'll keep this open for the dynamic case.
