### ISSUE TITLE
Consider limiting buffer sizes to multiples of 4 bytes

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1999]
Buffers can currently be any size, but there are many places where there are 4 byte limitations anyway:
- mapAsync size (which means mapAsync with default args fails on such buffers)
- size of mappedAtCreation buffers
- copyBufferToBuffer sizes

Additionally it can add complexity in initialization because it's required for those last 1-3 bytes to be initialized, but copyBufferToBuffer can't be used to initialize them.

So, they're of pretty minimal use. Why not just disallow unaligned sizes?

**Comment by Kangz** [comment]
The only concern I have is if applications size buffers dynamically, they might size them depending on content, see that it works and ship, but then break when the content changes to have a size that's not a multiple of 4.

**Comment by kainino0x** [comment]
I think they'd most likely run into one of the other limitations (like copyBufferToBuffer) anyway in that case.

FWIW I don't think copyBufferToTexture/copyTextureToBuffer have size alignments.

**Comment by litherum** [comment]
Do any of the native APIs have this restriction? Does WebGL?

**Comment by kainino0x** [comment]
Meeting:
- No appetite to add this limitation.
- Implementations probably will have padding at the end of odd-sized buffers anyway (either for clearing, for robustness, or because the buffer is suballocated from a native API's allocations)
- Consider rounding buffer mappings up to 4 bytes instead of validating. That way it's actually possible to access those last 1-3 bytes using mapAsync or mappedAtCreation. No change to copyBufferToBuffer. #2010

**Comment by austinEng** [comment]
Related: 
Dawn's Metal and Vulkan backends pad **all** buffers to 4 bytes because we use vkCmdFillBuffer and [MTLDevice fillBuffer] to lazily zero initialize the contents. Both these APIs require the size/offset to be multiples of 4**.

One consequence of internal padding is that it's not possible for the developer to initialize the entire buffer themselves. Without padding, a copy which touches all of the buffer contents could set the `initialized` bit in the implementation and avoid a lazy clear. But with padding, lazy zero init is more complicated, and the implementation has to issue a separate copy to clear out the last 1-3 bytes.

** Technically, Vulkan has VK_WHOLE_SIZE which we could use to avoid the 4-byte restriction, but it's buggy on some drivers, so we always explicitly pass the size instead.

**Comment by kainino0x** [comment]
Reopening as I think there's a bit more discussion needed here to figure out what we expect implementations to do to clear out those 1-3 padding bytes - which need to be cleared because they could be visible to robust access.

**Comment by kvark** [comment]
They are only visible with RBA on Vulkan, which has `VK_WHOLE_SIZE` as you mentioned. So there is a vendor, or a driver version, that fails to properly handle `vkCmdFillBuffer`, right? It seems strange to try adjusting our API for one case of a driver bug on one target API.

**Comment by Kangz** [comment]
Closing unless we find blocking issues for implementations.
