### ISSUE TITLE
Is a clean break from WebGL really necessary?

### ISSUE THREAD

**Issue by bobajeff** [gpuweb/gpuweb#2]
In the other thread I think @grovesNL [brought up a good point:](https://github.com/gpuweb/admin/issues/1#issuecomment-278367718)

> I agree, WebGL1/2 is tied to OpenGL ES today, but there doesn't seem to be a reason concepts like command queues couldn't be brought into future versions of WebGL or even WebGL2 behind extensions depending on the API changes required. The example of WebGPU provided was essentially equivalent to WebGL today except for the command queue functionality. I'd be surprised if OpenGL ES is not considering some of these concepts for future versions.
>
> Perhaps the discussion should be around which low level features should be exposed to the web as a starting point. I'm slightly skeptical that a common abstraction would significantly vary from WebGL2's existing API, given that Vulkan appears to be out of the picture because it's too low level. If the goal is to provide a slightly more object-oriented API with some additional functionality then it's a quite a large investment for the benefits it provides.

It seems to me from discussions elsewhere that WebGPU choose for whatever reasons to start with a brand new API. But I don't see a good reason to break from the existing WebGL API just yet.

**Comment by grorg** [comment]
This is an interesting suggestion. Some things come to mind:

- For whatever reason, the native APIs (mostly) chose to make a break. Vulkan looks nothing like OpenGL. D3D12 and D3D11 are closer, but still different.

- This suggestion could be made to the [WebGL Working Group](https://github.com/KhronosGroup/WebGL) (or their email list). That group is still very active, and has a lot of important work to do. Not only that, you're talking to a very similar group of people than you are here.

- One thing that might be fairly easy is coming up with a specification for how to write WebGL in order to minimize overhead, like AZDO for OpenGL. A problem is that browsers will still have to assume that the API can be used in any manner. It's worth investigating if an AZDO approach for WebGL as it stands today would give performance benefits.

**Comment by kainino0x** [comment]
> For whatever reason, the native APIs (mostly) chose to make a break. Vulkan looks nothing like OpenGL. D3D12 and D3D11 are closer, but still different.

This is my answer as well. We want to implement on top of these new, backward-incompatible APIs, so our design is likely to follow them.

In addition to grorg's comments, I'd also like to point out that the 'gpuweb' work is quite a long while off. The working group has just reached WebGL 2.0.0 and WebGL 2 support has only just started making it out onto the web - development is very active. WebGL 1 and 2 will be supported indefinitely despite the creation of gpuweb, just like OpenGL will be supported despite the creation of Vulkan.

**Comment by bobajeff** [comment]
My concern is that WebGPU might be prematurely adding a extra API that will have to be maintained and supported.

Vulkan, DX12 and Metal are still too new. They don't have a big installed base yet. Not too many developers are using it yet. We don't know the direction these APIs going since they just started. We don't know what the common use cases are going to be yet. 

It just seems way too early to invest in making, let alone supporting, a brand new web API based on them. Not when we can just port features to WebGL.

**Comment by othermaciej** [comment]
The reason the native APIs chose to make a clean break is that OpenGL has significant overhead, much of it in the driver. Ultimately, you can't remove overhead by adding features. You can selectively add more efficient ways to do things, but the driver has to be prepared for all the old slow things too.

It's likely going to be a year or more before a WebGPU spec is at all close to ready to shipping in production. Over that time we'll see whether Metal, Vulkan and DX12 are continuing to gain traction and increasing the installed base.

I also very much agree with what @kainino0x said. WebGL will be supported for a long time. Some of the likely direct users of WebGPU, such as game engines, may well have both WebGL and WebGPU back ends for an extended period. Indeed, WebGL 1.x and WebGL 2 have enough differences that you may need multiple back ends to truly support both.

**Comment by bobajeff** [comment]
I don't think a year is long enough. Many folks keep their PC/Laptops for 4 years or longer and a typical upgrade cycle for phones is 2 years. Plus, manufacturers are still going to be putting out entry-level or midrange devices/computers with chips that don't support Vulkan/DX12 for at least a year. Then you got the second-hand ('used') market for older phones which will likely not get updated to Nougat (Vulkan support) even if the chip is capable. I also don't think a year long is enough for developers to build up strategies and best practices for using these APIs.

How much do you know about the future plans of OpenGL ES and WebGL? What if GLES 4 is equivalent to Metal?

**Comment by grovesNL** [comment]
> For whatever reason, the native APIs (mostly) chose to make a break. Vulkan looks nothing like OpenGL. D3D12 and D3D11 are closer, but still different.

@grorg / @kainino0x : I agree with this, however the concern has been raised several times that Vulkan is considered too low level for this new API.

If the proposed API is higher level (closer to the Metal-like API proposed by Apple), it would be very similar to WebGL's existing API (with the exception of new functionality, i.e. SPIR-V/command queue). We would end up with new ways to setup descriptors and a slightly more object-oriented API, but for the most part there is not a large change.

If the proposed API is lower level (closer to Vulkan, perhaps slightly closer to Google's proposal) then I'd agree that a new API is required. In that case there may be no way to easily represent the low level concepts in the existing WebGL API without many breaking changes.

> One thing that might be fairly easy is coming up with a specification for how to write WebGL in order to minimize overhead, like AZDO for OpenGL.

This is a great idea, AZDO-like functionality in WebGL could potentially provide performance gains similar to what we might expect from the proposed API. I'd love to know whether anybody has experimented with these ideas in OpenGL ES already.

> WebGL 1 and 2 will be supported indefinitely despite the creation of gpuweb, just like OpenGL will be supported despite the creation of Vulkan.

I think the concern is that development would most likely shift focus towards WebGPU, which means WebGL moves into (mostly) maintenance mode. At that point everyone will probably prefer to migrate to WebGPU anyway, regardless of whether they need the extra performance or not.

It may be beneficial to create a list of the desired functionality that is missing from WebGL today that would become possible with the proposed API. If we can define these features, then we can try to understand whether it's possible to integrate into the existing WebGL API. For example, SPIR-V, command queues, and some of the AZDO functionality from OpenGL extensions, are all likely possible but would need further investigation. Would there be any showstopper functionality or other concerns about this approach?

**Comment by thokra1** [comment]
I'd argue that perpetuating three different specs for three different kinds of platforms (Desktop, Mobile, Web) is the actual problem - not that WebGL currently is not on par with any modern API. 

You want AZDO? Want SPIR-V? Want DSA? Want compute? Get the mobile and web people to implement core GL 4.5 and keep WebGL/2 and corresponding GLES implementations as legacy APIs.

If robustness of GL implementations is a problem, introduce extensions akin to GL_ARB_robustness. It shouldn't be impossible to eliminate a of the possible termination cases from the current spec. And can't state anything as to security issues other than what is already handled by the above extension. 

I get that you have to be able to run on an immense range of devices. However, the differences in hardware caps are shrinking with every new generation - today, you can have Vulkan conformance on most devices and someone has yet to explain to me the technical hurdles that would prevent vendors from exposing core GL 4.5 across the board.

**Comment by grorg** [comment]
It is definitely possible that this work, after examining the existing low-level platform APIs, concludes that a tweak/upgrade to WebGL is a more appropriate direction. I would be surprised, because each of platform APIs chose *not* to do that, despite them being at slightly different levels of abstraction. Also, as @othermaciej said, one of the main goals is to reduce the overhead in OpenGL.

Any improvements to WebGL would happen within the WebGL Working Group at Khronos. That work is still very active and, as others have said, will be supported for a long time (browsers basically have to support things forever, since content rarely disappears).

**Comment by bhack** [comment]
What about the new  [3d portability initative](https://www.khronos.org/3dportability)?

**Comment by thokra1** [comment]
Finally! :) Sounds like the right direction, but it could also mean that WebGPU would be obsolete right out the gate, right?

**Comment by kainino0x** [comment]
Not necessarily. Note that the 3D Portability group's goal is to create a native (C/C++) API implemented atop Metal/D3D12/Vulkan. These goals are very similar but not identical (esp. security). As suggested in that article, though, it could become possible to lift 3D Portability into the web.

**Comment by bhack** [comment]
But they have talked also specifically of wasm.

**Comment by kainino0x** [comment]
> This portability solution *could* also be a solid foundation for the next generation of WebGL – that can leverage this technology into JavaScript and WebAssembly.

(emphasis mine.) I think this is in line with what I said; my point is that Web is most certainly a _possible_ but not a _necessary_ goal of the 3D Portability group.

**Comment by bhack** [comment]
This will depend also on the overlap of the membership between Kronos and gpuwenb that we have already discussed in another issue.

**Comment by kainino0x** [comment]
Yeah, that's correct.

**Comment by thokra1** [comment]
@kainino0x: A little off topic, but my most notable knowledge gap here is the one about security issues which I assume arise primarily from browser-driver interaction through some platform/vendor specific API. Is there any public documentation on this topic?

**Comment by kainino0x** [comment]
There is some documentation in the [WebGL 1.0 spec](https://www.khronos.org/registry/webgl/specs/latest/1.0/#4)

**Comment by Maksims** [comment]
Does the Vulkan and underlying APIs that will power WebGPU have bigger coverage than what powers WebGL 2.0?
The problem is apparent, we have now WebGL 1.0, and WebGL 2.0. Most of things are conceptually compatible between, but there are things you cannot do in WebGL 1.0, leading to some challenges for users to design their apps remembering that. As it is pointless to develop apps that only support WebGL 2.0, as you will miss more than half of the market that way.

Remember, WebGL 2.0 has been released in major browsers, but it's support world wide is no more than half of platforms that provide support for WebGL 1.0.
Will it be even worse for WebGPU.

And then will engine developers will have to deal with all three API's since then? A lot of branching, JS code will grow bigger and more complex to maintain, and engine decisions regarding features will have to consider another extra thing. This all does not sound good for the web.
Branching in logic of engines is unavoidable, but it can be dramatically minimized when APIs provide some conceptual compatibility. Or even approach that WebGL 2.0 used with WebGL 1.0 which is great.

And then there is another thing - Khronos and community had tons of experience implementing 3D for the web, and using it, learning all the hard bits, establishing discussion with relevant developers and much more. Why we don't build on top of that experience, why choosing totally new group that has no experience in that (W3C), and not building on top of vast experience gained through years of developing and using real-world applications made with 3D web stuff?

**Comment by bhack** [comment]
Also, this new repository was opened https://github.com/KhronosGroup/WebGLNext-Proposals

**Comment by Maksims** [comment]
Looks like W3C and Khronos having sort of a "war" for who will be leading next 3D web API?

**Comment by Brynyard** [comment]
Not really, the "war" seem to have been started by Apple who wanted to come back to relevancy. The "web" promptly responded (in this case in the form of Mozilla) with a thorough walkthrough of what would be required of such an API, in addition to some comments on where the different API stand when it comes to "modern" feature support.

We'll see how the threadstarters respond, but for now there's been 5 days of crickets.

**Comment by Maksims** [comment]
So Apple been the slowest guy always to do things, and then decided to step out, but instead to join into the party, the just hosted new party in neighbourhood and inviting people to go to their house? That's just weird.

And history can show, that if Apple takes action on something, it is surely will be very biased - benefiting Apple as much as possible without consideration to everybody else. When Mozilla together with Google through many examples showed how they can tackle a big APIs and collaborate with W3C and Khronos to design something that is universal and great for user, regardless of vendor who implements it.

It is important to keep the web open and unbiased, and there are doubts regarding current approach with moving away from vast experience and having one company to be leading R&D for it, that showed not that a great examples in history in the web space.

**Comment by dmikis** [comment]
> Looks like W3C and Khronos having sort of a "war" for who will be leading next 3D web API?

> Not really, the "war" seem to have been started by Apple who wanted to come back to **relevancy.**

I don't know motivations behind Apple's initiative to move discussions of next-gen graphics APIs for Web to w3c, and, quite frankly, don't care much. The byproduct is that web-community can have more influence on the new standard (whatever form it'll take at the end) through w3c. On the other hand, Khronos experience in designing graphics APIs is valuable for this effort. Thus, I think, a joint group should be formed at some point to get the API standardised.
