### ISSUE TITLE
atomicCompareExchangeWeak is not idiomatic

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2021]
Following #1448 and #1973, it seems quite strange to return a vector where one of the elements is 0/1.
Wouldn't it be cleaner and more idiomatic to return a struct?
```rust
struct AtomicCompareResult<T> {
  old_value: T,
  replaced: bool,
};
```

I'm not seeing any of the backends returning `vec2`, so returning a struct isn't going to increase the amount of work for us. But it will make the API cleaner.

**Comment by kvark** [comment]
Actually, why does it need to return the old value at all? Could it just return `bool` instead?

**Comment by ben-clayton** [comment]
Alan put together the spec changes here, so should be able to answer your questions, but I assumed this was trying to mirror metal's:

```C
bool atomic_compare_exchange_weak_explicit(volatile threadgroup A* object,
 C *expected, C desired, memory_order success,
 memory_order failure) 
```

> These compare-and-exchange functions atomically compare the value in `*object` with the
value in `*expected`. If those values are equal, the compare-and-exchange function performs a
read-modify-write operation to replace `*object` with `desired`. Otherwise if those values are
not equal, the compare-and-exchange function loads the actual value from `*object` into
`*expected`. If the underlying atomic value in `*object` was successfully changed, the compareand-exchange function returns `true`; otherwise it returns `false`.

**Comment by ben-clayton** [comment]
> Wouldn't it be cleaner and more idiomatic to return a struct?

Yes, I agree it would.

**Comment by dneto0** [comment]
The aim is to mirror the C++ https://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange which, on failure of the exchange, gives the caller the existing value (i.e. does an atomic load).
Same thing in C11 is https://en.cppreference.com/w/c/atomic/atomic_compare_exchange :

```C
_Bool atomic_compare_exchange_weak( volatile A *obj,
                                    C* expected, C desired );
```

**Comment by kvark** [comment]
Yes, I see why it's returning a value now. So @dneto0 let's make it a struct with a real boolean in it.
