### ISSUE TITLE
texture_2d_depth for loading depth values might be unnecessary?

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#2094]
We currently have a special requirement that all depth textures must use a special `texture_2d_depth` type in the WGSL shader. While it's common to have special shadow sampler types for doing comparison tests, it's not common for shaders just loading depth values to require it. This is somewhat of an annoying requirement for engines, though not an impossible one; I'd like to see if it is strictly necessary.

This requirement seems to originate from the Metal Shading Language Specification, [which says](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#page=35):

> You must declare textures with depth formats as one of the following texture data types: 
> depth2d<T, access a = access::sample> 
> depth2d_array<T, access a = access::sample> 
> depthcube<T, access a = access::sample> 
> depthcube_array<T, access a = access::sample> 
> depth2d_ms<T, access a = access::read> 
> depth2d_ms_array<T, access a = access::read>

However, I looked at the common shader tools for Metal, and found:

* glsl-optimizer only outputs depth2d for comparison samplers: <https://github.com/aras-p/glsl-optimizer/blob/d78c3d2f249aa870368ad320905bc954c47704f6/src/glsl/ir_print_metal_visitor.cpp#L471-L474>
* SPIRV-Cross only outputs depth2d if comparison operations were used on the samplers: <https://github.com/KhronosGroup/SPIRV-Cross/blob/c2500e504d2b823d73d2f129e4f4f050e9618ecb/spirv_msl.cpp#L13498-L13540>

These two tools cover a substantial amount of games shipping on Unity and Unreal. So, it seems that these operations are "de facto" spec'd to work.

I think this could be evidence that we could drop the texture_2d_depth requirement for simply loading depth textures, though it could still be required for doing comparison sampling.

The second issue is that loading from a depth texture seems to have undefined values for the second, third and fourth components in loads, as seen in the [Metal Shading Language Specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#page=170):

> For a texture with the MTLPixelFormatR8Unorm pixel format, the default values for unspecified normalized components are G = 0.0, B = 0.0, and A = 1.0. For a texture with depth or stencil pixel format (such as MTLPixelFormatDepth24Unorm_Stencil8 or MTLPixelFormatStencil8), the default value for an unspecified component is undefined.

(This is a bizarre contradiction in the spec. depth2d's special load function only returns one component, there are no "unspecified components", so how could they even be undefined? This gives me some confidence that the texture loads are actually spec'd.)

On new enough devices, we could use texture swizzles, but that doesn't work for all platforms we want to support. However, given that I expect loading the G/B/A channels from a depth texture to be relatively rare in content, I think it could be solved by compiling an extra shader at pipeline creation time on these devices only *if* they access G/B/A of a depth texture load. But others can respond with the difficulty of such an approach.

**Comment by magcius** [comment]
See also: #1198 , 82500965

**Comment by kvark** [comment]
Thank you for the investigation work!
I'd split this question in 2:
  1. should we be able to have a regular `GPUTextureSampleType == "float"` binding for depth textures in the bind group layout? 
  2. if not, should we consider "texture_2d" in WGSL to be compatible with the `GPUTextureSampleType == "depth"` binding in the layout? In this case, the shader generator can see the BGL and put `depth2d` in the resulting MSL. So we can do this even without assuming anything extra about Metal valid usage.

**Comment by magcius** [comment]
Good question. I would clearly prefer if `GPUTextureSampleType == "depth"` could go away as well, but a simple step 1 might just be just removing texture_2d_depth from WGSL.

Are there any other requirements that mandate `GPUTextureSampleType == "depth"`?

**Comment by kvark** [comment]
No other requirements. It's only a separate type on MSL.
As a small side bonus to either of these choices, `texture_depth_multisampled_2d` will be terminated :)

**Comment by Kangz** [comment]
I think we still need `GPUTextureSampleType == "depth"` for comparison sampling, as that can only be done with `depth2d`. 1) would be nice. This way you only need to care about the `"depth"` sample type for comparison sampling. FYI @litherum

**Comment by magcius** [comment]
Yeah, I am definitely OK with keeping "depth" for comparison sampling.

**Comment by kainino0x** [comment]
re: OP / question 1: @litherum would it be possible to get input from the Metal team on why this restriction exists? (that depth-format textures must be bound as `depth*` in MSL even if they're sampled as color - especially given the contradiction of the "second issue" above - and the lack of this restriction in other APIs)

**Comment by magcius** [comment]
FYI, from more porting experience: because you already are forced to specify viewDimension in the pipeline layout, I don't think it's too onerous to require specifying depth at the same time.

I'd be OK with moving forward with removing texture_2d_depth and just using the pipeline layout to write the correct texture type in the shader, which sounds like it wouldn't require correspondence with the Metal team. But it would be a nice future to allow float as well.

**Comment by kvark** [comment]
@magcius I agree, having this outcome would be totally fine. The reason @kainino0x tries to dig the Metal behavior is that - if it turns out to be valid, then we wouldn't need to do any of the extra implementation work to glue the BGL that disagrees with the shader. So if we can get this answer soon-ish, it would help for sure.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-09-14-Minutes#texture_2d_depth-for-loading-depth-values-might-be-unnecessary-2094">WGSL meeting minutes 2021-09-14</a></summary>



* DM: Previously we decided all depth textures had to be bound as depth bindings. This is inconvenient. Not how it’s done anywhere except Metal. Metal doesn’t have the binding types that we have.  Observed by @magicus that the porting paths on Metal, in the cases when comparison is not use, will map to regular texture, and not using depth-texture. Seems to work for everyone for now.
* AB: But that’s not documented as the valid behaviour.
* DM: Want to layout the options
    * 1. Ask clarification from Metal: is the desired pattern supportable?
    * 2. Allow the shader to see regular texture 2D, provided the binding is the regular depth binding.  (Does not require input from Metal.  Solution is in the shader compiler only.)
* JG: On Metal the compilation needs the pipeline layout, to say which samplers are dept samplers. **We probably want to wait for MM for both**.
* RM: **I’ll ask the Metal team**, try to get feedback.


</details>

**Comment by magicus** [comment]
@kvark I think you meant to ping @magcius, not me ;)

**Comment by kainino0x** [comment]
Whoops, sorry! I fixed the typo in the wiki page and jdashg's post above.

**Comment by kainino0x** [comment]
We also need to decide whether to return `vec4<f32>(D, X, X, X)` like for stencil or specify more tightly. I think we would keep the `X`s because otherwise we would need to do pipeline-time compilation on *all* backends, not just Metal.

Technically with the pipeline-time compilation being proposed above I think we could precisely specify behavior for both depth *and* stencil, but it doesn't seem necessary.

**Comment by kvark** [comment]
Thoughts from the meeting:
If gather() is a problem for depth seen as `f32`, then it's also a problem for stencil, which has to be viewed as `u32`. So we have to figure out how valid is this gather() anyway. If it's valid to do, we have an option to expose depth as a regular `f32` texture (in both the shader and the pipeline layout). If gather() is invalid, we may need to consider having a "stencil" binding type in the pipeline layout, so that we can at least forbid gather() on Y,Z,W, and we can initialize those to (0, 0, 1) when loading data.

**Comment by kainino0x** [comment]
Meeting: overall agreement on the pipeline-creation-time code generation being an acceptable approach, the open question is whether we should instead just take advantage of the de-facto behavior of Metal and just allow depth textures to be bound to regular "float" binding points.

IIUC:

1. (Current) Require depth textures to be bound to `"depth"` type bind points. Require shader to use `texture_depth_2d*` for `"depth"` type bind points.
2. (Pipeline-creation-time code generation) Require depth textures to be bound to `"depth"` type bind points. Allow shader to use `texture_depth_2d*` OR `texture_2d*` for `"depth"` type bind points.
3. (De-facto) Allow depth textures to be bound to `"float"`/`"unfilterable-float"` type bind points. Allow shader to use `texture_depth_2d*` OR `texture_2d*` for `"depth"` type bind points. (3b: Instead require shader to use `texture_depth_2d*` for `"depth"` type bind points.)

action item @litherum: determine whether we need to guard against users using gather() on the wrong component (need to know for both depth AND stencil, I think). If so, that prevents option 3 and we have to do option 1/2 (and same for stencil).

**Comment by kainino0x** [comment]
> 3\. Allow depth textures to be bound to `"float"`/`"unfilterable-float"` type bind points.

Based on https://github.com/gpuweb/gpuweb/issues/744#issuecomment-638104768 I think actually we would only be able to bind depth textures to `"unfilterable-float"` type bind points.

**Comment by Kangz** [comment]
From the last meeting we have general agreement to remove allow binding `depth` textures to `texture_2d<f32>`, the only difficult is the gather operation on components that are not the first one. And we uncovered the same issue for stencil. Things we need to figure out are:

 - For depth do we still allow using them as `texture_2d<f32>`? (the discussion is leaning yes I think)
 - Do we allow gather operations on depth texture bindings? (that's dependent on @litherum's investigation)
 - Do we need to add a `stencil` sample type to prevent stencil textures to be gathered on incorrectly?

@litherum have you been able to check if it is a problem on Metal to use stencil / depth with gather operations not on the first component?

I'm hoping that it may be ok on stencil, so we can keep it the way it currently is. For depth textures turned `texture_2d<f32>`, we know that at pipeline compilation time, and so do we know the `component` of the `textureGather` call (it has to be a constant or pipeline constant), so we can emit an error.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-02-16#texture_2d_depth-for-loading-depth-values-might-be-unnecessary-2094">WebGPU meeting minutes 2022-02-16</a></summary>



* MM: idea here - think we had consensus on this months ago but didn't write resolution - only one popular human writable shading language has a type for depth textures. Others don't. When transliterating shaders, source shader likely won't have types for depth textures. Ease-of-use concern. Want to produce WGSL, but source shader doesn't' have depth texture type.
* MM: general consensus - allow color texture types in the shader to be bound to depth textures, can then sample from them. In API, continue to have bind point be depth_texture bind point.
* MM: 1) In WGSL-to-Metal you'll have info about what are depth textures at the API level. Can produce valid MSL.
* 2) Not needed when translating to HLSL.
* 3) Doesn't delete the depth_texture type from WGSL; you just don't need to use it when binding a depth texture. Methods on depth texture types are different than color texture types. Don't have to use the type if you don't need the extra methods.
* MM: think this satisfies everyone's concerns.
* DM: it was the gather operations where we stopped. DOn't know how Metal will handle gather + stencil textures.
* MM: stencil textures are just textures. Wrote test app, they do work.
* DM: they also work on depth textures seen as depth32 textures?
* MM: don't remember.
* DM: depth textures also have combined formats. Shader does the gather - still need to do it as a gather on a depth+stencil format.
* KG: so you want to make sure this works by law rather than de facto?
* MM: it's valid ot bind stencil texture to color attachment.
* KG: for depth though. You're not supposed to use those as color. Should we double check, or are you pretty confident?
* MM: I think we should assume it works.
* KN: concern with stencil - not that it's not allowed - but that G,B color channels might not be defined.
* MM: it's not defined. I ran test on different hardware, they produced different results. Don't remember 100%.
* KN: if depth works the same way - legal, but not defined results for G,B,A channels - we need to at pipeline creation time transform these in some way so that we hide the undefined results.
* KG: same thing we need to do for stencil.
* DM: we don't have a stencil binding type.
* KG: thought we decided that.
* KN: right.
* MM: not a security concern. "sample this" is something the compiler can see, and expect all the results are defined.
* KN: wanted to ensure it's legal with depth so we can define it the same way.
* MM: we should do that.
* DM: so - do we have to have a depth binding used for all the depth textures? or can i use f32 binding type?
* KG: if just sampling - can use f32 type. depth comparisons -> need depth binding type.
* KN: that's distinction between options (2) and (3). can the mismatch be between the pipeline and the shader? or texture and pipeline?
* DM: that question has been in the air for months. If pipeline knows about depth - we can polyfill everything.
* KG: so this would require pipeline time compilation on Metal.
* MM: would require producing MSL when you have the pipeline layout. Already true.
* KG: should we just ditch depth and see how far we get?
* KN: option (2) then. Fine choice; concern that it's still annoying. Have to get pipeline layout correct.
* MM: Kai's comment from Dec 15 2021 (?). OK. DM's asking whether option (3) is acceptable, should follow up on that.
* KN: I'm happy to do option (2) and consider (3) post-V1.
* KG: I thought we were focusing on (3).
* DM: thought we had all the info we need.
* MM: info missing - if you write MSL program that doesn't use depth texture type, and bind depth texture to it, and call gather() - what happens? I don't know.
* KG: we suspect it behaves like an R32F texture.
* MM: not necessarily. Program I described, if you bind stencil texture - behaves differently.
* KN: only on the other channels?
* MM: yes.
* KN: I strongly suspect depth would be the same. Don't know whether it's legal / spec'd as not legal.
* MM: spec's clear here. Depth texture requires depth type in shader. Option (3)'s against Metal's spec.
* KN: I agree
* KG: but we know it works.
* MM: we know it works for sample operations. No evidence that gather() operations de facto work. The combination is rare.
* DM: concern - if we decide option (3) is fine, all the work going into option (2) is wasted.
* MM: will anyone implement this in next couple weeks?
* DM: option (3) doesn't require impl - just allowing it.
* KN: if you can come back with an answer in a couple of weeks, we can leave this open.


</details>

**Comment by litherum** [comment]
I just wrote the simplest little test program I could - all it does is fill a 2D depth texture with data, bind it to a `texture2d` in MSL, and call `gather()` on it in a compute shader. I then ran it on the 2 devices I have in front of me: and AMD GPU and an M1 machine.

Running `texture.gather(mySampler, float2(0.5, 0.5), 0, component::????)`:

(assume the 4 relevant samples in the depth texture are named "cell1", "cell2", "cell3", and "cell4"):

GPU | `component::x` | `component::y` | `component::z` | `component::w`
-- | -- | -- | -- | --
AMD Radeon Pro Vega 56 | [cell1, cell2, cell3, cell4] | [cell1, cell2, cell3, cell4] | [cell1, cell2, cell3, cell4] | [cell1, cell2, cell3, cell4]
Apple M1 GPU | [cell1, cell2, cell3, cell4] | [cell1, cell2, cell3, cell4] | [cell1, cell2, cell3, cell4] | [1.0, 1.0, 1.0, 1.0]

Note how [cell1, cell1, cell1, 1.0] is not either of the [acceptable formats](https://gpuweb.github.io/gpuweb/#reading-depth-stencil) for either sampling stencil textures or sampling depth textures. Given that I found this edge case literally immediately after starting investigating this, I don't think we should expect `gather()` on a depth texture bound as a non-depth type to give any sensible results in practice in the y, z, and w components.

**Comment by kainino0x** [comment]
> Note how [cell1, cell1, cell1, 1.0] is not either

This doesn't match any of the items in your table, is there a typo?

> I don't think we should expect `gather()` on a depth texture bound as a non-depth type to give any sensible results in the y, z, and w components in practice.

The premise is that it's OK if we don't have portable behavior - the spec already makes loose guarantees for stencil with `S, X, X, X`.
We can expand this section to describe some partially-defined behavior for depth and gather operations as well (e.g. gather works on component::x, but implementation-defined results for anything else).

I think the question we want to answer is whether it's safe, i.e. won't return uninitialized data or cause undefined behavior. The Metal shading language spec just says it's undefined, but there are unlikely to be more than a few behaviors.

**Comment by litherum** [comment]
> > Note how [cell1, cell1, cell1, 1.0] is not either
> 
> This doesn't match any of the items in your table, is there a typo?

Not a typo. The idea is:

```
float4(
    texture.gather(component::x).x,
    texture.gather(component::y).x,
    texture.gather(component::z).x,
    texture.gather(component::w).x
)
```

is supposed to produce one of the samples in the texture.

> I think the question we want to answer is whether it's safe, i.e. won't return uninitialized data or cause undefined behavior. The Metal shading language spec just says it's undefined. But it seems unlikely there are more than a few fixed behaviors.

The spec currently says:

> When doing so, the value is returned as vec4<u32>(S, X, X, X), where S is the stencil value and each X is an implementation-defined unspecified value.

Gather operations on depth textures bound to `texture2d` abide by this same rule. However, the rule for gathers would have to be rephrased to say something like "the entire return value is an implementation-defined unspecified value if the component channel is not `x`."

**Comment by kainino0x** [comment]
OK, I think the disconnect was just that I'm reading our current WebGPU spec as completely unspecified when it comes to gathers (though agreed the text does kind of make it sound like gather would lean on the text currently there - please treat our spec text here as being in an interstitial/unintentional state).

If I understand the situation correctly then, it seems we could go ahead with option 3 (de facto).

**Comment by kainino0x** [comment]
<details><summary>2022-06-01 discussion:</summary>

- CW: on Metal we can do this.
- MM: recap: in shading language Metal has depth_texture type. Spec says, you can't attach any depth texture to a type that's not depth_texture. But, Metal's the only SL that has this requirement. De facto true that if you have a depth texture, you can sample from it. Contrary to the spec, but de facto true. Should WGSL have a depth texture type?
- MM: if you allow depth textures to be bound to non-depth-texture types, every non-depth-texture operation needs to work. We know sampling works. Not the only operation that color textures have on them. Can also gather. Think that's it. Other things like getting dimensions, but shouldn't be a problem.
- MM: months ago did some research. With gather, can get the w component - depth texture doesn't have this. Well defined for non-depth textures, but not for depth textures. "Gather w component from depth texture" - tested on 2 devices, pretty different results, the values didn't match my intuition.
- MM: is that OK? Garbage coming out from gather operation? Just say it in the WGSL spec? Gather from depth texture bound to color type, you get garbage? Not sure if it's safe though. Could texture unit return stuff from registers before? Not a lot of confidence this would actually be safe. But no evidence it wouldn't be.
- CW: great summary, thank you.
- CW: do you know if - maybe ask on the issue - are texture swizzles possible?
- MM: swizzles don't solve this - any texture compatible with texture swizzles can't be used as render target. Depth textures useless if can't be used as render target.
- KN: wouldn't it be two views, one with swizzle applied you use to read, and another used to render?
- MM: no, it's the texture itself.
- KN: I don't fully understand but that's not important.
- KR: think it'd be fine to leave the w gather values undefined. Had similar issue with depth textures in WebGL - only guaranteed channel is R, and it's worked fine.
- ~KN: iirc we also have a workaround, could recompile at use time. Pipeline would know it's a depth texture bound as color channel.~
- MM: options: 1) type in SL. 2) no type in SL, but annotation in BGL. Valuable because we know at pipeline creation time. 3) neither of those.
- KN: oh right, we're discussing 3). workaround only works in option 2).
- MM: right, deciding between 2) and 3).
- CW: maybe revisit this. Ideally option 3) is best. As Ken said, web has evidence that this is safe, so probably just do that. If you don't mind offline could you send Metal doc that you can't swizzle renderable texture?
- MM: don't know if it's written down. Wrote test program, it failed validaiton.

</details>

**Comment by litherum** [comment]
RESOLVED: option 2

**Comment by kainino0x** [comment]
OK, here's the proposal, which you can also find in graphical/table form in the link above. This should be a non-breaking enhancement that we can do after option 2, and after v1.

Add a new texture binding sampleType `"float-or-depth"`. It is used with `texture_2d<f32>`. On the color-depth axis it lies between `"unfilterable-float"` and `"depth"`:
- `float` - `unfilterable-float` - **`float-or-depth`** - `depth`

Compared to `"unfilterable-float", it has two differences:
- A bind group created against this BGL can bind a depth-format texture here.
- A pipeline created against this BGL must not use certain ops on the corresponding texture in its shader. An example of such an op *could* be `textureGather(1, ...)` (`1` here is a compile-time constant according to WGSL)

The benefit of this is that, unlike `"depth"`, `"float-or-depth"` **is** compatible with color textures. Therefore, you can use this when you can't determine far enough ahead of time which it is going to be used with, but don't happen to use it with operations forbidden on depth textures (which probably aren't too common).

---

FWIW, I think this idea could be extended to a `"uint-or-stencil"` type if we really wanted it, but we don't even have a `"stencil"` binding type right now, and adding one would be a breaking change. I do have a small concern about new ops being added which don't support stencil textures, but I suspect the reason this is fine (and Metal doesn't have any distinction) is that stencil8 is fundamentally identical to uint8 whereas depth gets much funkier (with depth24unorm and restricted-range depth32float).

**Comment by kainino0x** [comment]
Moving to Post-v1 for possible enhancement above. (will track the V1 thing in #3038)

**Comment by litherum** [comment]
Pretty surprising that we resolved on something, but the landed patch doesn’t implement that something, and AFAIK the landed patch wasn’t discussed in the group

**Comment by Kangz** [comment]
Can you detail the difference between the two somethings? Reading the minutes, it's not obvious what's different.

**Comment by kainino0x** [comment]
(Oops, didn't mean to close this, because I kept this open for the possible enhancement.)

**Comment by kainino0x** [comment]
@litherum I think we agreed on option 2 as described [above](https://github.com/gpuweb/gpuweb/issues/2094#issuecomment-995218279) and I was pretty sure what I implemented in the spec was that. If not then it was just an editorial mistake on my part.

> 2\. (Pipeline-creation-time code generation) Require depth textures to be bound to `"depth"` type bind points. Allow shader to use `texture_depth_2d*` OR `texture_2d*` for `"depth"` type bind points.

- [validating shader binding](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-shader-binding) allows `sampleType: "depth"` to be used with depth or non-depth texture types
- [the format table](https://gpuweb.github.io/gpuweb/#depth-formats) still requires depth formats to be used with `sampleType: "depth"`

BTW it also turns out I accidentally excluded the array, cube, cube_array, and multisampled_2d variants (thanks @mrshannon) so I need to add those. I also noticed that some existing text right next to that is missing all mention of depth texture types. Also there might be a spec problem that we don't allow texture_depth_multisampled_2d to be used at all, I need to figure out what's up with that.

**Comment by kainino0x** [comment]
Went ahead and filed the new proposal as #3115.

**Comment by litherum** [comment]
I'm not sure this argument has been made before, but option 2 has a problem. Consider a shader like this:

```
fn foo(tex: texture2d) {
    sample(tex, ...);
}
fn bar() {
    foo(texture1);
    foo(texture2);
}
```

Imagine that `texture1` has been bound with a `depth` bind point, and `texture2` has been bound with a `texture_2d` bind point. The shader itself typechecks successfully, but if we want to use Metal's internal depth types for the `texture2`, we'll end up having to duplicate the body of `foo`. In the worse case, we'll have to duplicate functions 2^n times, where n is the number of textures bound to the pipeline.

After some more discussion, we're now comfortable with option 3 instead of option 2, provided the spec indicates that operations which can observe/return the y/z/w channels will observe/return uninitialized and nonportable data.

**Comment by magcius** [comment]
Yes, you'll have to either inline or duplicate functions, however, the number of functions you'll need is the number of times called with different texture type arguments, not the number bound to the pipeline. You already require the pipeline layout at shader compilation time, which will tell you the texture type for a given binding.

**Comment by kainino0x** [comment]
Option 2 gives implementations the freedom to choose between rewriting the shader, and relying on de facto behavior, by adding validation that makes the first possible. It also means that, if we add texture operations in the future that aren't safe on depth textures, we can reject those at pipeline creation time (because we know whether they're used with depth textures or not). So far, feedback has been that the extra validation is acceptable from a developer standpoint.

For these reasons, I think we should keep the previous resolution of option 2.

**Comment by litherum** [comment]
> the number of functions you'll need is the number of times called with different texture type arguments, not the number bound to the pipeline

Right - that makes this worse, not better. In general, function calls are going to be more numerous than bindings.

Here's an example program which describes what I'm worried about:

```
fn foo(textureA : texture2d, textureB : texture2d, textureC : texture2d) {
    sample(textureA, ...);
    sample(textureB, ...);
    sample(textureC, ...);
}

fn bar() {
    foo(depthTexture, someTexture, someOtherTexture);
    foo(someTexture, depthTexture, someOtherTexture);
    foo(someTexture, someOtherTexture, depthTexture);
    foo(depthTexture, depthTexture, someTexture);
    ... etc etc etc ...
}
```

Above, we end up having to make a lot of copies of `foo()` (either by inlining or specializing). Every parameter might need to use the depth type or the non-depth type. I believe @dneto0 has historically expressed a desire to avoid this kind of blowup.

Here's another example of something else I'm worried about:

```
fn a(myTexture: texture2d) {
    sample(myTexture, ...);
}
fn b(myTexture: texture2d) {
    ...
    a(myTexture);
    ...
}
fn c(myTexture: texture2d) {
    ...
    b(myTexture);
    ...
}
fn d(myTexture: texture2d) {
    ...
    c(myTexture);
    c(myOtherTexture);
    ...
}
```

This describes how the blowup is global, rather than local - `a()` needs to be inlined/specialized, so that makes `b()` have to be inlined/specialized, so that makes `c()` have to be inlined/specialized. The bulk of the shader can be inside `b()` and `c()`, which means we can end up essentially multiplying the compiled size of the entire shader, just because someone added a single function call `c(myOtherTexture)` somewhere.

The conclusion that I'm coming to is that, if the information about what is bound to a depth texture is present in the bind group layout, but isn't present in the shader source, it's too easy for an author to accidentally create a binary size footgun.

> freedom to choose between rewriting the shader, and relying on de facto behavior

This decision seems false to me. If compilers are going to be relying on the de-facto behavior in any situation, then option 2 doesn't seem to have much value. If the de-facto behavior can be trusted, then option 3 is strictly better.

The value of option 2 is "the compiler will intentionally blow up the binary size of your program to generate code which we know to be correct."

I'm making a judgement call here: blowing up the binary size of the program is more harmful than relying on the de-facto behavior. And, if no compilers are _actually_ going to be blowing up the binary size of the program, then it seems unfortunate to require authors to supply information which won't actually be used.

Do Tint or Naga currently plan on blowing up the binary size of the program based on `GPUTextureSampleType.depth`?

**Comment by kainino0x** [comment]
> `GPUTextureSampleType.depth` could be re-added at the point that we add these new operations. Enforcing this is no worse than the existing texture analysis we have to do today.

This is a key observation. Given this I'm pretty sure I'm convinced it make sense to do option 3.
