### ISSUE TITLE
Implement "depth_clamp" on D3D12 

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#2100]
When I was implementing the WebGPU extension `depth_clamp` on D3D12, I found `D3D12_RASTERIZER_DESC.DepthClipEnable` doesn't have the same functionality as `VkPipelineRasterizationStateCreateInfo::depthClampEnable`, so we cannot implement `depth_clamping` with `D3D12_RASTERIZER_DESC.DepthClipEnable`.

- According to [Vulkan SPEC](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#_depth_clamping_and_range_adjustment), "if `VkPipelineRasterizationStateCreateInfo::depthClampEnable` is enabled, before the sample’s `zf` is compared to `za`,`zf` is clamped to `[min(n,f),max(n,f)]`, where `n` and `f` are the `minDepth` and `maxDepth` depth range values of the viewport used by this fragment, respectively", which implies in Vulkan "`depthClamp`" is done after fragment shader stage: clamp the depth value of the output fragment shader after the execution of fragment shader.

- According to [D3D12 document](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_rasterizer_desc), "the hardware always performs x and y clipping of rasterized coordinates. When `DepthClipEnable` is set to the default–`TRUE`, the hardware also clips the z value ", which means in D3D12 `depthClip` is executed before the pixel shader stage: discard the specific coordinates after rasterization.

I think the right way to implement `depth_clamp` is injecting the following at the end of fragment shaders, what do you think?
```
gl_FragDepth = clamp(0, 1, gl_FragDepth);
```

**Comment by kvark** [comment]
Thank you for raising this! A cursory search revealed similar notes in https://github.com/hrydgard/ppsspp/issues/11399

In Vulkan, depth clamping is a part of a larger "depth test" stage. It can happen before or after the fragment processing, depending on what's inside (whether or not discards are used, frag depth is modified, and other things).

injecting `gl_FragDepth` is a no-go from me because that would kill the early depth test.

If depth clamping is not portable, we should cut it out from the spec (similar to #2046) and return to the drawing board.
But it would be good to confirm it first. We need a simple test case that would show the difference in behavior.

**Comment by litherum** [comment]
+1 for a simple test case. From the description of the issue it sounds like it wouldn't be too difficult to create.

**Comment by Kangz** [comment]
> injecting gl_FragDepth is a no-go from me because that would kill the early depth test.

Injecting the clamping in the shader could be done only if the fragment entrypoint outputs `builtin(position)` so the early-Z would never be made worse.

**Comment by magcius** [comment]
Right, it seems like the two are only different if the fragment shader modifies gl_FragDepth already. But this might just be a spec inaccuracy in the D3D12 spec, which assumes SV_Depth is not modified?

**Comment by kainino0x** [comment]
For reference, here's the D3D11 functional spec section:
https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#15.1%20Rasterizer%20State

From further reading, Vulkan's depthClampEnable actually enables *two different things*:
> depthClampEnable controls whether to clamp the fragment’s depth values as described in Depth Test. Enabling depth clamp will also disable clipping primitives to the z planes of the frustrum as described in Primitive Clipping.
> https://www.khronos.org/registry/vulkan/specs/1.2/html/chap25.html#primsrast

Like D3D12 DepthClipEnable=false, Vulkan depthClampEnable=true unambiguously affects the pipeline's clipping stage:
> Depth clamping is enabled or disabled via the depthClampEnable enable of the VkPipelineRasterizationStateCreateInfo structure. Depth clipping is disabled when depthClampEnable is VK_TRUE. When depth clipping is disabled, the plane equation
> 0 ≤ zc ≤ wc
> (see the clip volume definition above) is ignored by view volume clipping (effectively, there is no near or far plane clipping).
> https://www.khronos.org/registry/vulkan/specs/1.2/html/chap24.html#vertexpostproc-clipping

**in addition to** the section quoted above, which it's not clear D3D12 DepthClipEnable does. I agree we should test it!

---

> Injecting the clamping in the shader could be done only if the fragment entrypoint outputs `builtin(position)` so the early-Z would never be made worse.

+1

**Comment by jenatali** [comment]
This isn't a spec problem in the D3D12 spec. Vulkan ties depth clamp to be the opposite of depth clip. If clamp is enabled, clip is disabled, and vice versa. D3D12 *always* enables depth clamping, and only allows toggling of clipping in isolation. Therefore as you say, it's only possible to achieve a difference if the fragment entrypoint outputs `builtin(position)`.

Note that there is a Vulkan extension for toggling these two bits independently, `VK_EXT_depth_clip_enable`, which makes it possible to achieve a matching implementation with D3D where clamp is always enabled, and clip is toggleable.

For OpenGLOn12, we implemented the exact approach you describe: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/gallium/drivers/d3d12/d3d12_context.cpp#L1991

```C
   /**
    * OpenGL Compatibility spec, section 15.2.3 (Shader Outputs) says
    * the following:
    *
    *    For fixed-point depth buffers, the final fragment depth written by
    *    a fragment shader is first clamped to [0, 1] and then converted to
    *    fixed-point as if it were a window z value (see section 13.8.1).
    *    For floating-point depth buffers, conversion is not performed but
    *    clamping is. Note that the depth range computation is not applied
    *    here, only the conversion to fixed-point.
    *
    * However, the D3D11.3 Functional Spec, section 17.10 (Depth Clamp) says
    * the following:
    *
    *    Depth values that reach the Output Merger, whether coming from
    *    interpolation or from Pixel Shader output (replacing the
    *    interpolated z), are always clamped:
    *    z = min(Viewport.MaxDepth,max(Viewport.MinDepth,z))
    *    following the D3D11 Floating Point Rules(3.1) for min/max.
    *
    * This means that we can't always use the fixed-function viewport-mapping
    * D3D provides.
    *
    * There's only one case where the difference matters: When the fragment
    * shader writes a non-implicit value to gl_FragDepth. In all other
    * cases, the fragment either shouldn't have been rasterized in the
    * first place, or the implicit gl_FragCoord.z-value should already have
    * been clamped to the depth-range.
    *
    * For simplicity, let's assume that an explicitly written frag-result
    * doesn't simply forward the value of gl_FragCoord.z. If it does, we'll
    * end up generating needless code, but the result will be correct.
    */
```

**Comment by kainino0x** [comment]
Thank you @jenatali! This is very useful background.

I'd like to write out exactly what all of the modes in Vulkan (with extension), D3D12, and Metal do:
- output of the rasterizer? (clipped, clamped, or neither)
- clamp depth before the depth test? (yes or no)
    - Anytime this is false we can change it to true with a shader transformation.
- clamp depth after the depth test? (yes or no)
   - I think this is always yes, at least by default?

but I don't have time right now to dive into it. (Took me quite a while just to figure out that list and I'm not even sure it's right.)

**Comment by jenatali** [comment]
I don't know anything about Metal, but I can comment on D3D12 and Vulkan.

* Output of the rasterizer (clipped or not):
  * In D3D12, this is controlled by `DepthClipEnable`.
  * In Vulkan without the `VK_EXT_depth_clip_enable` extension, this is the *opposite* of `VkPipelineRasterizationStateCreateInfo::depthClampEnable`.
  * In Vulkan with the `VK_EXT_depth_clip_enable` extension, this is controlled by `VkPipelineRasterizationDepthClipStateCreateInfoEXT::depthClipEnable`.
* Clamp depth before the depth test:
  * In D3D12, this is always true.
  * In Vulkan, this is controlled by `VkPipelineRasterizationStateCreateInfo::depthClampEnable`.
    * Note, if the value falls out of the \[0, 1\] range and `VK_EXT_depth_range_unrestricted` isn't enabled, or if the depth buffer format is fixed-point, behavior is undefined.
* Clamp depth after the depth test: This isn't a thing, as far as I know.

**Comment by kainino0x** [comment]
Thanks! The one detail I'm still wondering about is whether the fragment shader sees a clamped or unclamped value in each case/API. (what I meant by "clamped" output from the rasterizer, above)

**Comment by jenatali** [comment]
Per the D3D spec regarding the clipping stage, if depth clip is disabled:
> Primitives that fall outside of the depth range are thus still rendered, but are given the value of the nearest limit of the viewport depth range.

I was unable to find any similar wording in the Vulkan spec.

**Comment by Kangz** [comment]
From what I understand of the result of this conversation, since we have to design under the constraints of `VK_EXT_depth_range_unrestricted`, then WebGPU could follow the same behavior as D3D12 and say that the depth is always clamped. Then the extension would become `depth-clip-control` instead `depth-clamp`. In this case would we would just need to always clamp `builtin(position)` to [0, 1] if it is written to in the fragment shader.

**Comment by jenatali** [comment]
> In this case would we would just need to always clamp builtin(position) to [0, 1] if it is written to in the fragment shader.

You'd have to clamp to [minDepth, maxDepth] of the viewport, which is what D3D12 does after the fragment shader. Without `VK_EXT_depth_range_unrestricted`, those values must be a subset of the [0, 1] range.

**Comment by kvark** [comment]
Can we please please stop talking about `builtin(position)` as an output from the fragment shader? It's not an output of the FS. There are 3 comments in this thread repeating the same wrong thing. I assume it's meant to be `builtin(frag_depth)`.

**Comment by Kangz** [comment]
Ah yes, everybody got confused. Still the same comments apply.

**Comment by jenatali** [comment]
To be clear, there is one location where primitives can be clipped due to depth, and two locations where fragments can have their depth value clamped. Clipping means that the primitive is modified prior to rasterization.

So (1) is a clipping step, *disabled* in Vulkan by enabling `depthClampEnable`, or enabled independently of depth clamp via `VK_EXT_depth_clip_enable`, and enabled in D3D12 by enabling `DepthClipEnable`.

For what it's worth, I'd argue against calling anything in this space (except the extensions) a "feature." There's not really a "regular" case here, these are just configuration toggles on the pipeline, configuring whether depth clip is enabled, and/or whether depth clamp is enabled. Since neither Vulkan nor D3D12 lets you turn both of them off, you can't really call either one a feature IMO.

So WebGPU can get identical behavior between both APIs by disabling depth clip -- assuming that Vulkan also does a clamp on `position.z` input to the fragment shader. If it doesn't, then you can get un-clamped depth into the fragment shader for D3D12 by writing it separately from `position.z` in the vertex shader and letting it interpolate, or else can clamp it manually in the fragment shader in Vulkan. In both APIs then, depth clamp will be enabled, before the depth test - if it's possible, in the early depth test, but if it's not, then after the fragment shader.

If you would like to expose a toggle for depth *clip*, then you must also implement manual depth *clamp* in the fragment shader if the fragment shader writes depth in order to get identical behavior between APIs, because D3D12 cannot disable the automatic depth *clamp*.

**Comment by kvark** [comment]
> I'd argue against calling anything in this space (except the extensions) a "feature."
In WebGPU, "feature" is any functionality that's not available by default. It's exposed by `GPUAdapter` and has to be opted into.
Since the ability to control depth clamping/clipping isn't portable, we can't call it anything but a "feature".

First, we need to figure out what the "baseline" behavior is for WebGPU. It sounds like we have a problem here with regards to FS writing to `frag_depth`:
  - Vulkan doesn't clamp the output to viewport Z range (by default)
  - D3D12  does clamp
  - what does Metal do? (cc @litherum )

**Comment by jenatali** [comment]
If you treat Vulkan's `depthClampEnable` set to true as the "baseline" behavior, then both Vulkan and D3D12 will clamp prior to the depth test/write, and neither of them will clip before the rasterizer. This means you either need to clamp input `position.z` (to match D3D12 on Vulkan), or need to pass a separate unclamped `position.z` (to match Vulkan on D3D12).

Alternatively, if you treat Vulkan's `depthClampEnable` set to false as the "baseline" behavior, then you'd need to set D3D12's `DepthClipEnable` to true, and would need to manually clamp any writes to `frag_depth` in the fragment shader, to emulate the depth clip actually being enabled.

Lastly, if you treated `VK_EXT_depth_clip_enable` as the baseline (which I suspect you can't/won't do), then you could configure both D3D12 and Vulkan to turn on both depth clip and depth clamp and have identical behavior between the two.

**Comment by kvark** [comment]
@jenatali that's a good list of our options! I assume the second option is what we have to do ("treat Vulkan's depthClampEnable set to false") because neither Vulkan or [Metal](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1516267-setdepthclipmode?language=objc) require depth clamping to be supported.

**Comment by jenatali** [comment]
Note that the Metal link you pasted is about depth *clip*, not clamp. Depth *clip* is automatically enabled on Vulkan if you disable `depthClampEnable` - so if you're saying that Vulkan doesn't make depth *clamp* required, and Metal doesn't make depth *clip* required... there's no baseline that's universally supported. So you'll have to pick one and support emulation either way.

**Comment by kvark** [comment]
The default Metal value is `MTLDepthClipModeClip`, and that is what it does when `MTLDepthClipMode` isn't supported (otherwise things would make very little sense). So Metal default matches Vulkan default, and it's a natural baseline for us.

**Comment by kainino0x** [comment]
> The problem is regular behavior (without any features) when `frag_depth` is written: Vulkan by default doesn't clamp that depth output, but D3D12 does. So that's what we need to solve (not the feature).

Agree, this is one reason I wanted to write out the full table of what every mode in each API does. That way we can identify the modes that overlap between core apis (for the default) and between optional vulkan/metal features (for the webgpu feature).

> The default Metal value is `MTLDepthClipModeClip`, and that is what it does when `MTLDepthClipMode` isn't supported (otherwise things would make very little sense).

It's the Metal documentation that's misleading: "Depth clipping is supported on all macOS GPU families and iOS family 4 and later."
I think what it means is "setDepthClipMode is supported on all macOS GPU families and iOS family 4 and later."

**Comment by kvark** [comment]
I think we reached the resolution here, and the issue can be closed. The "depth-clamping" feature can be supported just fine.

Changes are needed for the "baseline" behavior on Vulkan, however. Potentially on Metal as well?
We need to try and implement these changes with appropriate tests, filing a separate issue (and referring this one) if see any complications.

**Comment by kainino0x** [comment]
I started trying to test this:
https://github.com/gpuweb/cts/pull/753

---

In rereading this issue, in particular the [Depth Clamping and Range Adjustment](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap26.html#_depth_clamping_and_range_adjustment) section, I figured out this is an important tidbit:

> If depth clamping is not enabled and zf is not in the range [0, 1] then zf is undefined following this step.

This seems to say in Vulkan we need to clamp depth to [0,1] (if it's written in the shader) anyway, to avoid UB. The only cost of clamping to the viewport depth range would be passing the range data into the shader.

---

> * Clamp depth after the depth test: This isn't a thing, as far as I know.

I finally understand this: it won't clamp **to the viewport**. The depth format / unrestricted mode are all that matter after this point(?), although it sounds like it there's no clamp, just undefined behavior.

---

As further reference, here is the relevant D3D11 functional spec section that actually specifies the "always clamping" behavior:
> Depth values that reach the Output Merger, whether coming from interpolation or from Pixel Shader output (replacing the interpolated z), are always clamped: z = min(Viewport.MaxDepth,max(Viewport.MinDepth,z)) following the D3D11 Floating Point Rules(3.1) for min/max. The MinDepth and MaxDepth values are defined by the Viewport(15.6).
https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#17.10%20Depth%20Clamp

I believe this matches the point in the pipeline where Vulkan does depth clamping when depthClampEnable=true.

---

I'm starting to make sense of the options. Metal and Vulkan most likely match because of their shared lineage in OpenGL. Here is a guess but I am still not 100% sure:

State | - | - | - | -
-- | -- | -- | -- | --
Clip stage clips primitives to viewport depth range? | yes | yes | no | no
Input to fragment stage is clamped to the viewport depth range? | ? | ? | ? | ?
Input to depth test is clamped to the viewport depth range? (regardless of whether frag_depth is written) | no | yes | no | yes
Vulkan | depthClamp=false (depthClip=true) | \* depthClamp=true depthClip=true<br>OR<br>depthClamp=false + shader transform | \* depthClamp=false depthClip=false | \* depthClamp=true (depthClip=false)
D3D12 |   | DepthClip=true |   | DepthClip=false
Metal | DepthClipModeClip | DepthClipModeClip + shader transform |   | * MTLDepthClipModeClamp

\* = not core

Something I'm still not clear on is, we were discussing a shader transform in D3D12 as well. I don't have a chance today to figure out how that was supposed to fit in.

**Comment by Jiawei-Shao** [comment]
I've also tried to ["implement" "depth_clamp" on D3D12 in Dawn](https://dawn-review.googlesource.com/c/dawn/+/63984). From the CL we can see all the tests will pass on D3D12 if we clamp `[[builtin(frag_depth)]]` into [0, 1] in the fragment shader and disable `depthClipEnable`.

**Comment by jenatali** [comment]
> Something I'm still not clear on is, we were discussing a shader transform in D3D12 as well. I don't have a chance today to figure out how that was supposed to fit in.

That fills out the other two columns for D3D12. If you clamp fragment shader writes to the viewport range, you can easily emulate depth clamp.

**Comment by kvark** [comment]
We established that Vulkan baseline requires clamping of `frag_depth` if it's written by the shader.
But @Jiawei-Shao mentions the same transform for D3D12. Why is it needed for D3D12?

**Comment by kainino0x** [comment]
> That fills out the other two columns for D3D12. If you clamp fragment shader writes to the viewport range, you can easily emulate depth clamp.

I thought D3D12 always clamps fragment shader writes to the viewport range? Unless I misunderstood the "Depth values that reach the Output Merger..." paragraph above.

In which case no shader transform _should_ ever be needed for D3D12, only Vulkan and probably Metal.

---

Results from my testing (through Dawn):

On D3D12 and Metal at least, the position.z input to the fragment shader is not clamped. I haven't tried DepthClipEnable=false on D3D12, but that shouldn't affect it.

In the default configuration both D3D12 (expectedly) and Metal (somewhat unexpectedly\*) seem to clamp the depth value to the viewport before writing it to the depth attachment. (e.g. if the viewport is 0.25 to 0.75, and I output frag_depth=0.0 or 0.25, I get 0.25 in the output.) I'm [running](https://chromium-review.googlesource.com/c/chromium/src/+/3174095) against Chromium automated testing to get multiple vendor coverage in case I've hit an undefined behavior (or bug), and to check the result on Vulkan.

\* unless Tint is clamping - haven't checked but unlikely

I also haven't verified yet whether the input to the depth test is clamped, I only checked the depth attachment result.

**Comment by kainino0x** [comment]
> I'm [running](https://chromium-review.googlesource.com/c/chromium/src/+/3174095) against Chromium automated testing to get multiple vendor coverage in case I've hit an undefined behavior (or bug), and to check the result on Vulkan.

Results are consistent across [macOS](https://ci.chromium.org/ui/p/chromium/builders/try/dawn-mac-x64-deps-rel/b8835321478259172865/test-results?q=depth_clip) intel/amd, [win10](https://ci.chromium.org/ui/p/chromium/builders/try/dawn-win10-x64-deps-rel/b8835321478259172881/test-results?q=depth_clip) intel/nvidia (clip=false untested). [Vulkan](https://ci.chromium.org/ui/p/chromium/builders/try/dawn-linux-x64-deps-rel/b8835321478259172897/test-results?q=depth_clip) (intel/nvidia) indeed doesn't clamp when depthClampEnable=false.

So on Metal it appears that MTLDepthClipModeClip still clamps, despite the naming.

**Comment by kainino0x** [comment]
> [Vulkan](https://ci.chromium.org/ui/p/chromium/builders/try/dawn-linux-x64-deps-rel/b8835321478259172897/test-results?q=depth_clip) (intel/nvidia) indeed doesn't clamp when depthClampEnable=false.

On NVIDIA, a depth32float attachment gets unclamped writes:
`-1.00 -0.50 0.00 0.25 0.75 1.00 1.50 2.00`
On Intel, the attachment writes get clamped to 0..1:
`0.00 0.00 0.00 0.25 0.75 1.00 1.00 1.00`

So that's the undefined behavior for writing values outside the 0..1 range.

**Comment by kainino0x** [comment]
> Clip stage clips primitives to viewport depth range?

This wording I was previously using is subtly inaccurate. Depth clipping actually clips primitives to NDC z range [0,1] (just like they are clipped to NDC x and y range [-1,1]). The NDC cuboid is then mapped into the viewport bounds (x/y/z) _after_ that.
