### ISSUE TITLE
Specify cube texture filtering as seamless

### ISSUE THREAD

**Issue by mrshannon** [gpuweb/gpuweb#2171]
All three major backends (DX12, Vulkan, Metal) require seamless cube map filtering, therefore WebGPU implicitly uses seamless cube maps (cannot support cubemaps with seams) but the spec does not explicitly require implementations to use seamless cubemaps. We should specify this to avoid any confusion.

**Comment by dneto0** [comment]
> All three major backends (DX12, Vulkan, Metal) require seamless cube map filtering

While doing background research for texture gather #2327, 
I've found the reference info for D3D and Vulkan:

*DX12: inherits from D3D11 [7.8.12 TextureCube Edge and Corner Handling](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#7.18.12%20TextureCube%20Edge%20and%20Corner%20Handling)
* Vulkan: [Cube Map Edge Handling](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#textures-cubemapedge), part of [16.3.1 Texel Input Validation Operations](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#textures-input-validation)

I've looked but I can't find authoritative reference info for Metal.  The closest I found is in the MSL section for the gather methods.  But it doesn't describe what happens when sampling texels over the edge or at a corner.

He @litherum can you point me in the right direction?
