### ISSUE TITLE
Consider replacing elseif with else if

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2212]
GLSL, HLSL, and MSL all use `else if` instead of `elseif`.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-02-Minutes#consider-replacing-elseif-with-else-if-2212">WGSL meeting minutes 2021-11-02</a></summary>



* RM: PR if we go that way: [https://github.com/gpuweb/gpuweb/pull/2239](https://github.com/gpuweb/gpuweb/pull/2239)
* AB: It’s in conflict with removing braces (which was proposed elsewhere).  Ok with this if we don’t remove the requirement for braces.
* GR: Does requiring braces make this harder?
* RM: It makes it easier to require, rather than if it were optional.
* MM: Do we have to pick just one of “required braces” or “else if”?
* JG: Yes, we pick one of the two. If you make both changes, you have the dangling else problem.
* KN: another solution is to only allow removing braces for some specific statements, not including if statements


</details>

**Comment by dneto0** [comment]
The resolution from 2021-11-09 was to approve this and keep on requiring braces for 'if' statement bodies.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-09-Minutes#consider-replacing-elseif-with-else-if-2212">WGSL meeting minutes 2021-11-09</a></summary>



* (David: request to approve this and close “consider not requiring braces in some situations [#2211](https://github.com/gpuweb/gpuweb/issues/2211))
* MM: If Apple had to choose between optional-curly-braces or else-space-if, we choose else-space-if.
* DN: Fine by me.
* RM: If we keep the curly-braces, we have some paths forward, like omitting parens around conditionals, and also the potential for if-expressions.
* JB: For Rust, there is an ambiguity when a construction expression like `Type{...}` appears in an `if` condition: is `if S {` a simple condition `S`, or the beginning of a construction expression in the condition?
* JG: If I choose between optional-curly-braces or else-space-if, I would choose  optional-curly-braces, but I don’t think the consensus is with me.
* **Resolved: Change to else-space-if**
* PR for review: [https://github.com/gpuweb/gpuweb/pull/2239](https://github.com/gpuweb/gpuweb/pull/2239)
* 


</details>
