### ISSUE TITLE
How to measure the shader compilation time in js

### ISSUE THREAD

**Issue by qjia7** [gpuweb/gpuweb#2236]
When we tried to measure the time spent on CreateShaderModule() and Create*Pipeline() on Chromium, we found these APIs were returned immediately without doing validations and calling native APIs to create pipelines on the GPU process, and we found the shader and pipeline creations would always be delayed until we met some points that may trigger Chromium to handle all of the current callback tasks, for example when MapAsync() is called. This behavior makes it hard for us to investigate the performance issues brought by shader compilations and pipeline creations, which always cost quite a lot of time when dozens of compute pipelines need to be created in the first inference with a typical machine learning model. In addition, it may also bring some misunderstandings that when we measure the time cost with performance.now() from JS side, it shows it is MapAsync() that spends quite a lot of time instead of shader and pipeline creation.

Based on the above investigation, we think it helpful for the SPEC to do below clarifications:

- Point out that the return of CreateShaderModule() and Create*Pipeline() doesn't mean the completion of the creation of the related GPU resources.

- Provide an API to query the shader compilation and pipeline creation time in developer mode, which will be very useful for the developers to do automated testing.

- Point out that in both Create*Pipeline() and Create*PipelineAsync(), the shader compilation and pipeline creation may all be executed asynchronously in parallel for performance optimizations.

A related discussion in chromium can be found [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1265616).

**Comment by Kangz** [comment]
> we found the shader and pipeline creations would always be delayed until we met some points that may trigger Chromium to handle all of the current callback tasks, for example when MapAsync() is called.

Note that this is a Chromium issue that will be handled separately and nothing in the standard mandates that.

> In addition, it may also bring some misunderstandings that when we measure the time cost with performance.now() from JS side, it shows it is MapAsync() that spends quite a lot of time instead of shader and pipeline creation.

This is still Chromium specific, but also it's weird because the createShaderModule command should have already been serialized so its cost shouldn't appear in the `mapAsync` call.

+1 for adding more clarity to the specification regarding where the CPU cost of pipeline / shader module compilation will appear. However it seems it could be a bit difficult to expose the compilation times on the objects themselves in the spec because that's timing information that could be used in many bad ways :/ Would it be sufficient to ask pipeline / shader module creation costs to be surfaced in the devtools of various browsers?

**Comment by qjia7** [comment]
In my imagination, taking GPUComputePipeline as an example, the new interface is like below:
```
interface GPUComputePipeline {
  Promise<GPUPipelineInfo> pipelineInfo();
};

interface GPUPipelineInfo {
    readonly attribute unsigned long createPipelineTime;
};
```
For security concerns, we can just allow it under developer mode like timestamp query API. We can either
- make sure that `createPipelineTime` return a meaningful value only under developer mode. Otherwise, zero is shown. Or
- Make `Promise<GPUPipelineInfo> pipelineInfo();` as the part of an extension. Only if this extension controlled by browser is supported, the user can use it.

>Would it be sufficient to ask pipeline / shader module creation costs to be surfaced in the devtools of various browsers?

Our target is not only to collect the pipeline/shader module creation costs. We also want to automate the whole process so that we can get regular report that each operator's cost on compilation/dispatch in TFJS. If webgpu can directly expose this kind of interface, it will be convenient for us to integrate them to TFJS framework.

**Comment by litherum** [comment]
There is a WGSL compilation error that (would be? should be?) hooked up to the success/failure of the platform's compiler. I suppose this means that getting the compilation messages should force compilation to complete; thereby giving you a way of measuring how long it took.

**Comment by kainino0x** [comment]
Unfortunately we don't have a similar thing for pipeline creation, but we could. See also: https://github.com/gpuweb/gpuweb/issues/2119#issuecomment-953348485 in which an async "is this pipeline valid?" call could also help.

**Comment by kainino0x** [comment]
Useful discussion in today's CG meeting. Have more to think about, but I think we should consider an API specifically for timing shader/pipeline creation. This would make it possible to avoid scheduling "overhead" where e.g. if you issue 5 similar pipeline compilations at once on a 4 core machine, one of the pipelines will appear to take twice as long, because it started late.

An alternative idea is for the benchmark to run in a "detailed benchmarking" mode where it serializes all operations, e.g.: create shader, wait for error scope, create pipeline, wait for error scope, submit work, wait for completion. This would still avoid the scheduler overhead problem without a new API, but would also mean that finer-grained timing breakdowns can't be generated without affecting overall performance. Maybe this is at least sufficient for the short term (~1.0).

**Comment by Kangz** [comment]
IMHO this isn't something we should do for v1 because there are already proxy ways to measure the time it takes to compile, and that the data might not be super representative depending on browser optimizations. Macro benchmarks seem like they would be more stable, and if a developer needs more fine grained data, then it could use browser's internal tracing to get a better view. (we just added something like that to Chromium tracing and TF.js' request).

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-01-19#triage-the-issues-without-milestones-timebox-15m">WGSL meeting minutes 2022-01-19</a></summary>



* #2236 shader compilation time
    * JQ: can currently get shader compilation time using browser specific tools. Not that high priority for us.
    * MM: is it not high priority, or is it completely resolved?
    * JQ: we have a method to get the time. So it depends on whether you want to expose an API for developers.
    * KG: sounds like this is closed as far as you're concerned. If someone else wants to do it they can reopen it.


</details>
