### ISSUE TITLE
[proposal] Changes to overridable constants

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#2238]
After internal discussion, Google is proposing some changes to how overridable constants are declared and used in WGSL.

## Motivation
We anticipate a future in which WGSL has constexpr (#1272) so it is useful to address whether overridable constants would still have a useful role in WGSL at that point, and if so, should there be more meaningful disambiguation in the language.

There is value in a mechanism that allows early compilation of a shader module with values that can be updated at pipeline creation time (or later). Both SPIR-V and Metal expose similar (though slightly different) functionality in the form of specialization constants and function constants respectively. Facilitating early compilation is a good goal generally.

There are motivating use cases that map particularly well to overridable constants: sizing workgroups and workgroup memory. Sizing a workgroup can already be accomplished in WGSL today. #2024 is nearing consensus to introduce a feature for sizing workgroup memory based on overridable constants. To make that feature better WGSL needs some expanded functionality for overridable constants.

## Proposal

We propose changing how overridable constants are declared. Instead of attaching an attribute to a module-scope let declaration, we propose a new keyword to declare an overridable constant,`override`. The declaration would have generic-like parameter to specify the (optional) override id.

Simple examples:
```
// This overridable constant can only be referred to by name in the API.
override x : i32;

// This overridable constant uses the id 1 in the API.
override<1> y : f32;
```

The new syntax is beneficial to disambiguate between other constants and (potential) constexprs. We can utilize the grammar to allow different initializer and expression on overridable constants than other types of declarations.

The real major addition (requested by @litherum) is that we also propose to allow overridable constants composed of overridable constants and constexprs (when added). We would restrict which overridable constants can actually be overridden to scalar types with no initializer or a literal initializer (or constexpr). It would be a shader-creation error to specify a numeric id for an overridable constant initialized from other overridable constants. This feature allows users to perform computation based on the value of overridable constant and use that computation wherever an overridable constant can be used. The grammar can define the expressions useable by an overridable constants initializer. We propose literals, constexprs (if adopted) and operations supported by SPIR-V [OpSpecConstantOp](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpSpecConstantOp).

Examples:
```
override<1> z : u32 = 1;
override y : u32 = 2 * z;
override x : u32 = 2 * y;
override size = x * y * z;

// Sizing workgroup memory as in #2024 
var<workgroup> wg_var : array<f32, size>;

[[stage(compute), workgroup_size(x,y,z)]]
fn main([[builtin(local_invocation_id)]] lid : vec3<u32>) {
  // ...
}
```

Potential grammar:
```
override_decl : 
  | override id_decl ? ident colon type_decl override_initializer ?

id_decl : 
   // assuming constexprs are added
 | less_than const_expr greater_than

override_initializer :
 | equal override_expression

override_expression : 
 // allowable expressions
 | ident
 | ident plus ident
 // ...
```

The restriction that identifiers must be overridable declarations, module-scope lets or constexprs would need added. Also restrictions types would need to be spelled out (e.g. no add on f32 to allow translation to SPIR-V).

The current on restrictions on overridable constants would largely remain in place (e.g. module scope only).

**Comment by litherum** [comment]
Thanks for writing this up! A few thoughts:

1. 
> We propose literals, constexprs (if adopted) and operations supported by SPIR-V OpSpecConstantOp.

This should be broadened. Metal doesn't allow for the result of math on function constants to automatically become a function constant, so implementing this proposal on Metal will necessarily involve executing math on the program's behalf in the compiler. Restricting ourselves to just the ones that SPIR-V accepts doesn't mean that implementations will be able to avoid any implementation burden - they're going to have to write all that code to execute all the applicable math operations in the compiler anyway. The CG should decide which operations make sense to flow through `override`s, based on their merits, because being able to represent a particular operation in SPIR-V doesn't actually help any of us implement this feature.

My tentative proposal would be what I list in part 3 in https://github.com/gpuweb/gpuweb/issues/1272#issuecomment-900706631, along with all the math operators.

2. If we allow
override<1> x : u32;
override y : u32 = 2 * x;

[[stage(compute), workgroup_size(y)]] fn computeShader() {
    ...
}
then we should also allow
override<1> x : u32;

[[stage(compute), workgroup_size(2 * x)]] fn computeShader() {
    ...
}

**Comment by Kangz** [comment]
As a slight nit, I'm surprised we use the template/generic syntax to give an ID to an overridable constant, when it isn't a type system thing, and that all other numerical IDs for the interface of shaders use the `[[location(N)]]` type of syntax.

**Comment by dneto0** [comment]
> This proposal will make it really easy for authors to create lots and lots of specialization constants, perhaps even accidentally. I need to do some testing on Metal to make sure this won't be a problem. 

If Metal has a practical limit on the number of function constants (overrides), then that can already be hit with the existing overrides feature.  And if so, it should be added to the [limits section](https://gpuweb.github.io/gpuweb/wgsl/#limits).

**Comment by alan-baker** [comment]
@litherum 

We think this feature is orthogonal to `constexpr`. While we anticipate some form of `constexpr` ending up in WGSL, we don't think they need to be tied together. Certainly I think it would be backwards if `constexpr` could be formed from `override` constants. That force compiles to be delayed to pipeline creation. As a result, I am confused by your proposed layering. `constexpr` should be evaluated at shader creation time, but `override` definitely is not. Requiring that WGSL compilers evaluate `override` expressions is exactly the outcome I want to avoid.

I think there would be common cases (such as the one in the description), where Metal isn't required to evaluate anything on the GPU. A Metal implementation of the example in the description wouldn't materialize `size` in the shader at all. Instead it would turn into reflection data to size the local memory pointer used by the shader. There would be some cases where math might be done on the GPU, but SPIR-V also doesn't guarantee that `OpSpecConstantOp` won't be evaluated on the GPU. I don't think it is necessarily a mistake if some `override` expressions are evaluated on the device.

**Comment by litherum** [comment]
> We think this feature is orthogonal to `constexpr`.

Mechanically, yes. A language can support one without the other. The argument I'm making above is slightly different: if the WGSL -> backend compiler will be evaluating expressions on behalf of the program, you've already done more than half the implementation work of supporting `constexpr`. So, if it's 'sunk cost,' we might as well go all the way and give authors another language feature. (Another way of saying this: the "cost" side of the cost-benefit analysis of `constexpr` shrinks significantly.)

> `constexpr` should be evaluated at shader creation time

When you say "shader creation time" I assume you mean `createShaderModule()`, yes? If so, then I agree. `constexpr` values would be evaluated by the compiler on the CPU inside `createShaderModule()`; `override` values would be evaluated by the compiler on the CPU inside `create*Pipeline()`, and `let` values would be evaluated on the GPU in `draw*()`.

It would be illegal to say `constexpr x = myBuffer[0];` just as it would be illegal to say `override x = myBuffer[0];`, because `myBuffer` is neither `constexpr` nor `override`. The compiler doesn't know the contents of `myBuffer` at either `createShaderModule()` time or `create*Pipeline()` time.

When I said "of increasing power" I meant "increasing as you work from top to bottom of the table below." Another way of saying this: `override` values could be used anywhere `let` values could be used, plus a few more places (workgroup sizing and threadgroup array sizing). Also, `constexpr` values could be used anywhere `override` values could be used, plus a few more places (texture sample offsets and `case` statements). In that respect, `override` would be strictly more powerful than `let`, and `constexpr` would be strictly more powerful than `override`.

> Requiring that WGSL compilers evaluate override expressions is exactly the outcome I want to avoid.

I was trying to address this in my statement above:

> I think it would be a mistake to have a "specialization constant" feature in WGSL in which it was possible for an override expression to be evaluated on the GPU.

Consider the program you described originally, with a small elaboration:

```
override<1> z : u32 = 1;
override y : u32 = 2 * z;

[[stage(compute), workgroup_size(32)]] fn computeShader() {
    for (i = 0; i < y; i = i + 1) {
        ...
    }
}
```

It would be unfortunate if this got compiled to the following MSL:

```
constant uint32_t z [[function_constant(1)]];

kernel void computeShader(...) {
    uint32_t y = 2 * z;
    for (i = 0; i < y; i = i + 1) {
        ...
    }
}
```

Such a compilation would be misleading to the author - they explicitly used the word `override` in their source program. There's less chance the MSL compiler would be able to optimize it, compared to something like this:

```
constant uint32_t z [[function_constant(1)]];
constant uint32_t y [[function_constant(2)]]; // Automatically set by the WebGPU implementation

kernel void computeShader(...) {
    for (i = 0; i < y; i = i + 1) {
        ...
    }
}
```

If the author wanted to emit the former MSL program, they could achieve that by writing this WGSL instead:

```
override<1> z : u32 = 1;

[[stage(compute), workgroup_size(32)]] fn computeShader() {
    let y = 2 * x;
    for (i = 0; i < y; i = i + 1) {
        ...
    }
}
```

> I think there would be common cases (such as the one in the description), where Metal isn't required to evaluate anything on the GPU.

I'm sure that using specialization constants to set workgroup sizes and threadgroup array sizes will be common, but that's only 1/3 the benefit of the feature - the other two thirds are:

2. Hoisting computation that would be done by all threads on the GPU to instead be done on the CPU before draw-call-time (and not have to deal with buffer mapping / uploading to get these values into the shader)
3. Allowing backend compiler optimization passes to be run after specifying these values, for example to do dead code elimination or loop unrolling.

These second and third use cases shouldn't be overlooked. The example above that demotes a specialization computation to a runtime computation doesn't (necessarily) satisfy these desires.

It would be a mistake if we created a WGSL specialization constant feature, where the explicitly-denoted WGSL specialization constants didn't correspond to Metal function constants. The user told us to make something a specialization constant explicitly, and we should honor that request.

**Comment by alan-baker** [comment]
After more internal discussion, we're generally ok with the layering @litherum proposes. I think I misread it the first time which led to a different interpretation. We are ok expanding the possible operations to include more than SPIR-V spec constant ops and leaving up to the implementation to decide how best to deal with each case.

We're ok with `constexpr` being a different keyword as proposed (though on a personal level I'd also be ok with it being inferred as much as possible by the compiler).  In addition to what's proposed in #1272, we think it would be beneficial to declare function parameters as requiring `constexpr` (e.g. offset in texture builtins). This could be achieved by either declaring the parameter as `constexpr` or using an attribute on the parameter.

If `constexpr` becomes a separate keyword from `let`, then we're unsure whether module-scope `let`s should exist, though it would be potentially useful to define a global handle into a buffer (e.g. `let x = &buffer.some.deeper.element`), but that would require expanding the allowable expressions vs what is acceptable today.

Finally, on naming we might have a slight preference for `const` over `constexpr`.

**Comment by litherum** [comment]
> I'd also be ok with it being inferred as much as possible by the compiler from a `let` declaration

There's a third option: make `constexpr` (actually `const`, assuming we make the naming change you prefer) optional. It would work like type inference: If the programmer doesn't specify it, the compiler infers it, but if the programmer does specify it, it acts as a compile-time assertion.

**Comment by ben-clayton** [comment]
> I don't know whether this 3rd option is better than saying "a variable is constexpr iff it uses the `const` keyword", but I do think this 3rd option is better than forbidding authors from using the `const` keyword. The problem with forbidding authors from using the keyword is that there is action-at-a-distance: you make one change at the top of your program, and then you get an error hundreds of lines later and it appears to be unrelated, and there's nothing the author can do about the action-at-a-distance. If it's optional, they can at least decrease the distance.

A number of Googlers also share this concern (excluding Alan). This small group would much prefer to have the `const` / `constexpr` be *required* for compile-time constants, and would prefer to avoid the optional aspect entirely.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-09-Minutes#proposal-changes-to-overridable-constants--issue-2238">WGSL meeting minutes 2021-11-09</a></summary>



* MM: Previously we punted constexpr post-v1, but can we move that back to v1-target?
* DN: We’d like that too.
* DN: Do we need to litigate which of the standard lib builtins can be constexpr? (some, yes, probably)
* JB: **Can we defer until DM is back next week? (yes)**
* DN: There’s also some bikeshedding on attribute vs keyword for locations?
* MM: No opinion on that, but you wanted `const` rather than `constexpr` right?
* DN: Yes
* MM: There’s a choice whether constexpr-ness can be inferred by the compiler, or must be explicit. There seems to be general (but not universal) agreement to require explicit tagging.


</details>

**Comment by kvark** [comment]
That's one productive discussion here!

> override x : u32 = 2 * y;

I assume this is about providing the default value, but can still be overridden. I don't know if that's the semantics of `OpSpecConstantOp` though.

---
Trying to provide feedback on some of the points mentioned.

1) Using `override` as a separate keyword from `let` - seems reasonable, since we want some places to require constexpr (e.g. texture offsets) and other to be fine with overridable constants, so we'll be able to properly express this distinction in the grammar.
2) Using `<1>` as generic parameter is quite weird. It doesn't affect the type (as @Kangz noted), so it shouldn't be a generic parameter.
3) purpose of module-scope  `let` when we have constexpr - none, we wouldn't need it any more (agreeing with @alan-baker )
4) naming of constexpr - also have slight preference to just `const` (agreeing with @alan-baker)
5) 

> If the author wanted to emit the former MSL program, they could achieve that by writing this WGSL instead:

That's not the same though, since the former still had the constant overridable, but the replacement is hard-coded. I.e. if the former MSL program can be re-used with different specialization for `y`, but the rewritten program can't.

6) extending beyond `OpSpecConstantOp` - @litherum has a good point that it doesn't have a major impact on the implementation complexity, since we have to do the constant evaluation for other backends as well. Weakly agreeing with @litherum .

7) requiring `const`/`constexpr` :+1:  (agreeing with @ben-clayton )

8)

> Hoisting computation that would be done by all threads on the GPU to instead be done on the CPU

Targeting this would lead us to include all of the things in the world and write basically another execution environment of WGSL expressions. I'd honestly rather let people put these values in uniforms, at least for V1.

**Comment by litherum** [comment]
> `override x : u32 = 2 * y;`
> 
> I assume this is about providing the default value, but can still be overridden

You couldn't override it, because it doesn't have `override<17>` but is instead just `override`.

If you wanted to propose the ability to say `override<17> x : u32 = 2 * y;` (or perhaps `[[override(17)]] override x : u32 = 2 * y;`) then that's reasonable.

> Using `override` as a separate keyword from `let` - seems reasonable
> 
> Using <1> as generic parameter is quite weird.

Are you proposing `[[override(17)]] override x ...`? The duplication isn't wonderful.

**Comment by Kangz** [comment]
> Are you proposing [[override(17)]] override x ...? The duplication isn't wonderful.

`[[location(17)]] override x ...` but yeah it's not as terse because it doesn't use the "generic" syntax to put binding model information.

**Comment by kvark** [comment]
```
override z = 18;
override p = z;
```
this is particularly interesting: is `p` defaulting to whatever the actual value of `z` is? Or is it defaulting only to the default value of `z`?

**Comment by litherum** [comment]
> is `p` defaulting to whatever the actual value of `z` is?  Or is it defaulting only to the default value of `z`?

I don't have strong opinions, but I'd expect it to default to the actual value, just because of intuitive-ness.

**Comment by litherum** [comment]
re `[[location(17)]] override x` vs `override<17> x` we have a slight preference for the former, but only because of consistency with vertex attributes and stage-in-outs

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-12-07-non-APAC-30m-supplemental-Minutes#proposal-changes-to-overridable-constants--issue-2238">WGSL non-APAC 30m supplemental meeting minutes 2021-12-07</a></summary>


* Previously:
    * JB: Can we defer until DM is back next week? (yes)
    * Revisit next week
* DN: Some things will have their values finalized at pipeline creation, so that’s the purpose. Some things will need ids for bindings, but others are fine without. “Hey, if it’s overridable, it’s overridable”
* MM: Can you clarify?
* DN: Key idea is to make analogy to default parameters in C++ function calls.
    * override&lt;0> blockSize: i32 = 0; // can be overridden in API with id 0
    * override foo : f32;   // must be overridden by name.
    * override blah = foo;   // Question.  Can I override in teh API side? Yes.
    * override blitz = 2 *  blah;  /// Can i override this.  Yes, in analogy to default parameters
* BC: Override declares a thing that can be overridden.  If it has an initializer, then the implementation can compute the value, at pipeline creation time.  
* MM: Like DM asked in comment, above, if blah is overridden via API, what should blitz be.
* DN: It would be 2*blah_from_api
* DM: What I don’t like is the angle-brackets for the IDs.
* MM: Ok to change to [[/]] attribute.
* JB: So we’ll need to reserve some calculations/evaluations til pipeline compilation.
* BC: Yeah, have the expression tree carried into pipeline creation. And evaluated at that time.
* JB: This is probably okay implementation-wise, because we’ll probably have enough of an interpreter to do constant evaluation available for other reasons.
* DM: Why does the code need to exist anyway?
* JB: For something like constant folding. [e.g. to compute blitz from blah] But, this is just a concern about implementation complexity
* KG: Each pipeline creation that does a different override will have to recompute.
* DN: What attrib name should we use? Id?
* MM: “location”!
* DM: Can we still override by name then?
* MM: Yes, can always override by name, and alternatively by location if given one
    * E.g. “override foo: i32;” would be valid, and would be identified by the ident “foo”
* DM: We’re introducing a new keyword so that we can have separate contexts here, but we haven’t introduced a new type to enforce this. It would be nice if the function signature could tell us if it’s an override enough
* MM: We already have keywords with different expressivities, such as let allowing reassignment, while var does not. I think for const exprs we do want something obvious on signatures so that people know what to expect.
* **Resolution: General approval, needs more specific issues for follow-ups probably. DN will fixup PR to match consensus.**
* DN: I’ll update the PR to match consensus, and think about constexpr encroach into type system,and what to do at formal parameter boundary.

</details>

**Comment by dneto0** [comment]
> re [[location(17)]] override x vs override<17> x we have a slight preference for the former, but only because of consistency with vertex attributes and stage-in-outs

I'm fine with making it an attribute.  I would quibble with reusing 'location' because for pipeline IO the location numeric space is dense, but for pipeline overrides it's quite sparse.  Also it's clearer to avoid confusion between the two different numeric spaces (e.g. what happens with overlap... no problem)

**Comment by litherum** [comment]
> This proposal will make it really easy for authors to create lots and lots of specialization constants, perhaps even accidentally. I need to do some testing on Metal to make sure this won't be a problem.

I wrote a [little benchmark](https://github.com/gpuweb/gpuweb/files/7737813/ManyFunctionConstants.zip) to see how long it takes to compile and run a program that adds a bunch of function constants together.

# Compilation time

We're making sure there's no superlinear performance here, because superlinear performance would indicate we should be more stingy with out function constants, and might not want to add a feature into WGSL which makes it really easy to use a lot of them.

<img width="786" alt="Screen Shot 2021-12-17 at 1 09 20 PM" src="https://user-images.githubusercontent.com/918903/146608319-22d00162-f176-4e02-b50b-df7f255a168c.png">

<img width="742" alt="Screen Shot 2021-12-17 at 1 09 27 PM" src="https://user-images.githubusercontent.com/918903/146608329-4cf61c58-bcff-45f8-83cd-20e81bbaa0fb.png">

<img width="742" alt="Screen Shot 2021-12-17 at 1 09 33 PM" src="https://user-images.githubusercontent.com/918903/146608330-6103fdb7-3540-484f-b585-2f7b453e6d0f.png">

<img width="737" alt="Screen Shot 2021-12-17 at 1 09 39 PM" src="https://user-images.githubusercontent.com/918903/146608334-ed0cf979-4bcf-4af5-80f3-10d9bab8e73c.png">

As you can see, the graphs are all linear and increasing. This is good - nothing appears to be superlinear.

# GPU execution time

We're making sure there's no linear performance here - the runtime should be unaffected by the number of function constants. This would indicate that an author promoting variables to function constants would be a good way of improving runtime performance.

<img width="850" alt="Screen Shot 2021-12-17 at 1 10 52 PM" src="https://user-images.githubusercontent.com/918903/146608468-3a06af4e-5dd0-4b5e-972a-d08c9f3b93a6.png">

<img width="795" alt="Screen Shot 2021-12-17 at 1 11 00 PM" src="https://user-images.githubusercontent.com/918903/146608475-4703f2e2-d129-4ef4-81c8-0fc7c8703e19.png">

<img width="801" alt="Screen Shot 2021-12-17 at 1 11 08 PM" src="https://user-images.githubusercontent.com/918903/146608478-3a61b577-b4f2-4aac-983a-624c9b60130a.png">

<img width="800" alt="Screen Shot 2021-12-17 at 1 11 19 PM" src="https://user-images.githubusercontent.com/918903/146608480-1531beba-c543-4c49-95d7-32d105fd0913.png">

As you can see, the graphs are all pretty much flat. This is good - nothing linear.

# Sanity check

And, just as a sanity check, here's another set of graphs which plots the entire end-to-end runtime, including shader compilation, execution, and downloading the data again to make sure the correct answer is calculated, plotted against compilation time. This just makes sure that Metal isn't doing any deferred/asynchronous compilation kind of thing (like WebGPU does). If these graphs show an x=y line, that means we should have confidence in the above graphs.

<img width="839" alt="Screen Shot 2021-12-17 at 1 13 09 PM" src="https://user-images.githubusercontent.com/918903/146608711-baf7ba7e-6d15-4037-b6b6-e4188970b594.png">

<img width="775" alt="Screen Shot 2021-12-17 at 1 13 17 PM" src="https://user-images.githubusercontent.com/918903/146608716-7ef1fa89-ff3f-4976-9e4e-358485046a52.png">

<img width="783" alt="Screen Shot 2021-12-17 at 1 13 26 PM" src="https://user-images.githubusercontent.com/918903/146608719-2a8c6e96-5b2f-4b3c-a665-ea5ed46ffeb7.png">

<img width="772" alt="Screen Shot 2021-12-17 at 1 13 35 PM" src="https://user-images.githubusercontent.com/918903/146608722-30c3a8c5-4265-4947-b2dc-7ad33725a262.png">

They're all pretty much perfect y=x lines.

# Conclusion

The data looks good; we don't have any performance concerns about this proposal.
