### ISSUE TITLE
should WGSL handle unicode bidirectional overrides specially?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2245]
Unicode allows text to change direction partway through a text.   This can be used to fool a human reader by showing active code as being inside a comment.

* Rust security advisory, and mitigations https://blog.rust-lang.org/2021/11/01/cve-2021-42574.html 
* https://research.swtch.com/trojan - Nice overview and perspective.  Summary:  It's not new, and suggest the answer is proper review, not mitigations in the language or tooling.

Should WGSL do anything about the bidirectional overrides case?

Related: issues with characters that look very similar (homoglyphs)

**Comment by dneto0** [comment]
Discussed during 2020-11-09:  Agreed no language change was required.  However, tools are encouraged to issue a warning because experience with Rust code shows that these control sequences are not used in practice, even if it's perfectly valid.

**Comment by dneto0** [comment]
Hey @jdashg please close this once you post official minutes.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-09-Minutes#should-wgsl-handle-unicode-bidirectional-overrides-specially--issue-2245">WGSL meeting minutes 2021-11-09</a></summary>



* BC: Big splash a few weeks ago.  Unicode lets you change direction of text within a single line.  It’s visually indistinguishable from having written it a different way.  Hear Rust has ruled out the offending patterns.  Could recommend erroring out.
* MM: This has nothing to do with control characters and overrides.  A native right-to-left speaker can write comments that will do this.  Burden on the editor understand what a comment is and display it reasonably.  Two paths forward, aside.
    * 1. Your editor should make comments displayed intelligently with knowledge of the unicode bidi. 
    * 2.?
    * Neither requires a language change
* RM: Useful for an implementation to issue warning. Rust compiler found no false positives across open source codebases.  So tooling can help. Since warnings are implementation dependent, there’s no reason to change.
* BC: Github now has tooling for calling this out visually.  So maybe we don’t need to do anything within the language spec.
* MM: Reasonable to have a warning when one of these characters appears.  Can appear in good-faith written text. But the case study that found no nefarious uses.
* JG: So recommend **warnings but no language change.**


</details>
