### ISSUE TITLE
WGSL should specify the execution order

### ISSUE THREAD

**Issue by RobinMorisset** [gpuweb/gpuweb#2261]
I noticed in reviewing https://github.com/gpuweb/gpuweb/pull/2055 that we don't seem to specify the order of execution of arguments to a function (or to an operator).

I'd like to propose specifying the order of execution (left-to-right seems simplest, but I am not attached to that particular order).
Cons:
- In theory could cause a tiny perf loss by preventing some compiler reordering. In practice I don't know of any result that proves this to be a concern; and it would not apply to Vulkan anyway (since SPIRV does not have nested expressions)

Pros:
- Better portability (since otherwise a shader can work fine on one machine+browser and behave differently on another one)
- Less confusion about possible same-thread races. Consider the following function:
```
fn f(x: ptr<function, u32>) -> u32 {
  let y = *x;
  *x = y + 1;
  return y;
}
```
From reading the spec, it is not clear whether `f(&some_local_variable) + f(&some_local_variable)` would cause a data race, even if each thread gets its own `x`. It would depend on exactly how the program-order relationship is defined (is it just unspecified which store is before the other, or are they truly unsequenced like in C/C++11?)
- Somewhat paradoxically a clearer spec as it can be tricky to say just how unspecified the ordering is. For example, I don't think the current spec says whether `a()` can execute between `c()` and `d()` in the following expression: `f(a(), b()) + g(c(), d())`

**Comment by dneto0** [comment]
I do not want this.  The  lack of ordering as written in the spec is intentional.

- MSL, HLSL, GLSL do not specify an ordering.
- A programmer who cares about this ordering can put the expressions into different statements, and then sequence the statements.
- There are other cases too, e.g.      `a[f()] = b[g()]` is also indeterminately ordered.

**Comment by litherum** [comment]
It's pretty surprising to hear that, given all the other concessions we've made in WGSL toward the goal of portability. This specific problem is particularly important in WGSL because we have so many things at global scope, meaning it will be very easy to write code with side-effects where order of execution is important.

> MSL, HLSL, GLSL do not specify an ordering.

Every other web programming language has a well-defined order of execution. (GLSL-as-used-on-the-web has a de-facto order of execution, because every browser uses the same compiler.) The portability requirements of web APIs is higher than those of native APIs. We are targeting more backends than WebGL is (WebGL is targeting OpenGL and potentially D3D, whereas WebGPU is targeting Metal, D3D, and Vulkan) so portability is even more important for WebGPU than it is for WebGL.

> A programmer who cares about this ordering can put the expressions into different statements, and then sequence the statements.

Reiterating a point @RobinMorisset made above - there's very little reason to _not_ to have a well-defined execution order, and there _is_ significant reason to have one. The portability concerns are clear, as in the example above. The only reason we can think of _not_ to do this would be a vague notion about performance, but A) we're not aware of any significant performance optimizations that this allows which are used in practice, and B) any such performance improvements have not been demonstrated.

> There are other cases too, e.g. `a[f()] = b[g()]` is also indeterminately ordered.

This GitHub issue is about all of these cases, not just argument evaluation order.

**Comment by RobinMorisset** [comment]
I just realized that we already had an issue for this: #663.
I am not sure which one should be marked as a duplicate of the other as there is now discussion on both.

**Comment by dneto0** [comment]
(not attempting to make a qualitative statement or argument)

Investigation into WebGL's constraint, per the spec:
* WebGL uses GLSL ES 1.0, which  [says](https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf):
    *  "5.9  Expressions":  "Except where stated otherwise, the order of evaluation of operands in an expression is undefined."
         * For example, binary arithmetic operations have unspecified orderings
     * "6.1.1 Function calling conventions" says: "All arguments are evaluated at call time, in order, from left to right."

I assume WebAssembly imposes an order because it executes a sequence of instructions.

**Comment by dneto0** [comment]
Specifying a detailed order of evaluation interacts with may-discard.  (Example due to @ben-clayton )

In:

     f(a(),b())

If `a` discards then `b` must not execute.

**Comment by RobinMorisset** [comment]
I agree that it interacts with the uniformity analysis because of discard; I had assumed in it a left-to-right execution order. It can trivially be adapted to a different execution order, but dealing with an undefined execution order would be tricky.

I'd also like to note that `a[f()] = b[g()]` seems to have a well-defined execution order today, as the rule for an assignment `r = e` says:
> Evaluates e, evaluates r, then writes the value computed for e into the memory locations referenced by r

Finally, while WebAssembly is obviously defining an execution order as it is a sequence of instructions, JS also has a well-defined execution order. It was not an accident, the spec is taking great pains to make it clear exactly in which order things execute, and I believe it would be a major portability otherwise.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-09-Minutes#wgsl-should-specify-the-execution-order--issue-2261">WGSL meeting minutes 2021-11-09</a></summary>



* RM:  C languages allow permuting, but don’t know of study showing perf wins.
* Web has greater portability goals.
* BC: Discussed internally.  Think it’s worth pursuing. Massaging code to ensure ordering in various backends can be tricky.  E.g. decompose into a sequence of a let-declarations, then the actual statement. Fine until you get something like a for-loop.
    * E.g. condition has a few function calls nested.  But backend doesn’t allow ordering of arguments.   So you explode the evaluation to a bunch of lets.  But where do you put those lets.
* RM: ‘for’ is just sugar for ‘loop’.
* BC: Yes.  Tint has that transform for the hard cases. Want to hear from Mozilla.
* JB: One goal is to have the output shader be legible.  This would go against.  Understand MSL has weak guarantees like C++.
* JB: We can do this. Our complexity should not hold it back.
* MM: Competing desires: legibility of an output shader vs. portability for users.  Portability clearly win.
* DN: Had thought briefly about how this plays with floating point reassociation.  But it’s independent because you can still force evaluation of primary inputs first, then evaluate the combinations.
* JB: Naga treats all function calls as statements, so we may already be forcing the order in these cases.
* **Consensus: Robin to write PR.**


</details>
