### ISSUE TITLE
It's not clear what popErrorScope() returns

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2274]
> Issue 101: Define popErrorScope.

It appears to only be able to return a single error. What if more than one error occurred in the error scope? Does it return the first one? How is "first" defined? Or does it just return any of them? Should it be changed to return `Promise<sequence<GPUError>>`? If so, are implementations required to generate every single last error in the scope? What if the first error caused successive errors?

**Comment by Kangz** [comment]
I think the intent is that it returns one error that is any errors that happened in the error scope. It can be the "first" one for your implementation since that's what's most useful to developers. `Promise<sequence<GPUError>>` seems a bit worrisome because of the reason you stated: a single programming error can cascade into a large amount of validation error because of the error monad, so I don't think we should require implementations to surface all the errors.

**Comment by kainino0x** [comment]
It's intended to return the first error (the error from the first failing method call in the scope).
https://github.com/gpuweb/gpuweb/blob/main/design/ErrorHandling.md#error-scopes
> It resolves to null if no errors were captured, and otherwise resolves to the first error that occurred in the scope

The spec work is still TODO but I think I can close this as the question should be resolved.
