### ISSUE TITLE
Expose WGSL errors in the API

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2308]
https://gpuweb.github.io/gpuweb/wgsl/#processing-errors

> TODO: Update the WebGPU spec, referring back to the three kinds of errors defined here.

One particular aspect is figuring out how "uncategorized errors" are exposed. Is it useful to expose them from createShaderModule? If not, errors occurring in shader creation can be stored and returned later in createPipeline. And should they be exposed to the error scope as a "validation" error or something else?

**Comment by kainino0x** [comment]
cc @dneto0

**Comment by kainino0x** [comment]
"Uncategorized errors" added in #1997

**Comment by dneto0** [comment]
See #2352

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-02-16#expose-wgsl-errors-in-the-api-2308">WebGPU meeting minutes 2022-02-16</a></summary>


* KN: needs a proposal. Nothing to discuss.


</details>

**Comment by Kangz** [comment]
How about making WGSL uncategorized errors be exposed just like regular validation errors? When a developer hits uncategorized errors during development they would know to change something. But when a site hits an uncategorized error in the wild, there nothing it can do to react to it, so it can look similar to a validation error and propagate.

**Comment by kainino0x** [comment]
Discussed in 2022-06-22 meeting and we realized these errors are similar in semantic to out-of-memory errors. Editors to discuss aligning the two concepts, possibly merging them.

**Comment by litherum** [comment]
Sounds like we're pretty much resolved, modulo specifics (@kainino0x?) - there's general agreement on the call today to add a new module type.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-06-29#expose-wgsl-errors-in-the-api-2308">WGSL meeting minutes 2022-06-29</a></summary>

* KN: did we have more to discuss here? Internet's out here now.
* KG: didn't come to conclusion last week.
* KN: thought we'd treat this more like out-of-memory errors. Treat them like potentially recoverable. Thought we were done with discussion for now. Result - someone makes proposal like that.
* MM: q: in order to know whether one of these uncategorized errors has occurred, you have to invoke the platform compiler. If exposed like other validation errors - they'd show up at shadermodule creation time. So have to be able to run platform compiler at shadermodule creation time - not sure whether other impls plan to do this.
* KN: I think we should defer all of these to createPipeline time, even if impl gets the error from the platform compiler earlier.
* MM: think that's the only way this can work. Some impls don't run the platform compiler until createPipeline. "This error can be exposed either in createShaderModule or createPipeline." The OpenGL way.
* BJ: I'd prefer if this were consistent. Fewer places people have to wrap in error-catching mechanisms. If app absolutely needs to know error came from specific shader module - they could create dummy pipeline around it. Not convinced this is necessary.
* KG: in GL, standard practice - you check program link status. Print program link log then. Didn't compile a shader properly. You blindly check for link status - print program link status, VS/FS compile statuses, compile logs. Nice if we didn't do that - just report it late.
* KG: only way you can get around this.
* KN: also one other reason we need these in pipeline creation - they don't just come from the compilers but also from pipeline creation like inability to allocate shmem or registers.
* MM: check link status, then link log, etc - are you describing what the browser does or what users do?
* KG: both. At some time in FF I added compile failure logs to the program link failure log. Could technically guarantee that.
* MM: So are we done/resolved then?
* KN: We were talking about whether we should differentiate between validation errors and uncategorized errors. Validation errors are probably author error/not automatically recoverable, but you might have fallbacks for uncategorized errors.
* KN: Thus we should consider adding uncat errors to ooms (not validation errors), or add a new type of error.
* MM: Why with ooms?
* KN: They are also unpredictable, and you can kind of respond to them programmatically
* KN: We don’t want people looking at the string to figure out what to do programmatically. 
* KG: Probably don’t fold with oom, but just realize they kinda are similar
* MM: +1, let’s add a new error type.
* **Resolved: New error kind**
    * KN: need proposal for this, but mostly editorial. Hopefully someone will come up with proposal and bring it back here.

</details>
