### ISSUE TITLE
Shader resources reflection from ShaderModule is needed.

### ISSUE THREAD

**Issue by JasonHuang3D** [gpuweb/gpuweb#2316]
Dear all,
I am a native graphics developer, I have been working with modern graphics APIs, such as DX12, Vulkan and Metal2 to deliver a intermediate level for commercial 3d graphics engine and products.

I found that getting shader resources reelection for a specific shader stage is very useful :
1. By using SPIRV-Cross(see: https://github.com/KhronosGroup/SPIRV-Cross/wiki/Reflection-API-user-guide) and DxShaderReflection for DX12(see : https://docs.microsoft.com/en-us/windows/win32/api/d3d12shader/nn-d3d12shader-id3d12shaderreflection).
2. Once we have got the shader resources reflection, we are able to construct the platform specific shader resource binding automatically for pipeline states by providing update frequency configurations to the user.

I saw Dawn native implementation is using Tint to get all shader reflections internally which is very similar to what I pointed out for DX12 and SPIRV-Cross. (see :https://dawn.googlesource.com/dawn/+/refs/heads/main/src/dawn_native/ShaderModule.cpp#611).
And then all reflections are stored in ShaderModule instance as a private member (see: https://dawn.googlesource.com/dawn/+/refs/heads/main/src/dawn_native/ShaderModule.h#292).

So can we have the access to the shader reflection from ShaderModule? 
i.e. the private member mEntryPoints of ShaderModule struct in Dawn(https://dawn.googlesource.com/dawn/+/refs/heads/main/src/dawn_native/ShaderModule.h#292).

Thanks a lot.

**Comment by Kangz** [comment]
#624 is another feature request to add shader reflection. One thing though it that shader reflection, if any, would have to be provided asynchronously since browsers implementing WebGPU by offloading the GPU calls and compilation to a different process. It would most likely be added to [`GPUCompilationInfo`](https://gpuweb.github.io/gpuweb/#gpucompilationinfo).

However this is not likely to make the cut for v1 because defining a reflection format would take a lot of standardization effort that we don't have before WebGPU v1. Luckily there are alternative, like @brendan-duncan's [wgsl_reflect](https://github.com/brendan-duncan/wgsl_reflect) that he just shared, or in native [Naga](https://github.com/gfx-rs/naga) / [Tint](https://dawn.googlesource.com/tint) can provide reflection.

I wish we had a better answer, but right now I think your best way forward is using one of the tools above.

**Comment by JasonHuang3D** [comment]
Thanks a lot, I have tried with Tint and struggling to make it to be available for the runtime on web by using WebAssembly.  I think even if I have gone succeed, it is pretty much doing the same thing as what browser dose, i.e. parsing the wgsl raw string to a tint::Program and get reflection and entrypoints, etc. 

It is nice to hear it is on the roadmap, I will let you know if I have gone succeed with an wasm verison of some necessary parts from libtint. 

Thanks a lot.

**Comment by JasonHuang3D** [comment]
@Kangz  Please kindly let me know if I can make any contributions to push the shader reflection works forward, I would like to do anything that can make this thing to be published earlier. Should I somehow begin with a API proposal or do we have the it already, thanks a lot.

**Comment by Kangz** [comment]
To be perfectly clear, shader reflection is an idea for after WebGPU v1, as in we'll discuss whether it is needed and in which form after v1. I personally think it is likely there will be something one day but I dread the discussions around the specific reflection format. For that reason I don't know what's the best way to contribute to this right now. Maybe a proposal? But I think we can't prioritize discussing it for v1.

**Comment by JasonHuang3D** [comment]
Thanks for the details, I would love to first experiment tint for wasm and then perhaps will draft a proposal after that.

**Comment by Kangz** [comment]
Closing in favor of https://github.com/gpuweb/gpuweb/issues/624
