### ISSUE TITLE
Add integer increment and decrement statements

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2320]
This is prompted by developer feedback.   Related to #2241, but simpler.

Example:

    var n: i32;
    n++;  // as statement, not as an expression
    n--;  

Also, add as an option for the update clause of a for loop.

      for (var i: u32 = 0; i < n ; i++ ) {...}

Proposed rules: 
- allow it on a read_write reference to integer scalar. 
- evaluates the reference once,  loads, then add (or subtract) 1, then stores.
- Allowed as a general statement, and in the update clause of a for loop
- Counts as both a read and a write access to the reference .

**Comment by kvark** [comment]
This is going to be less of a problem in the presence of #2241
Increment/decrement are not essential operators, as shown by Rust.

**Comment by dneto0** [comment]
> Increment/decrement are not essential operators, as shown by Rust.

#2241 is also not essential. :-)

**Comment by Kangz** [comment]
> Increment/decrement are not essential operators, as shown by Rust.

Rust has `Iter` based for loops but WGSL doesn't enjoy the same nicety.

**Comment by jdashg** [comment]
I'll also note that python does fine with requiring `i+=1`, and it's only one extra character.

**Comment by Kangz** [comment]
Python is also a language that has only iterator based loops. (subjectively typing `for(var i = 0; i < 3; i += 1` would be weird but not that weird)

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-30-Minutes#add-integer-increment-and-decrement-statements-2320">WGSL meeting minutes 2021-11-30</a></summary>



* DN: There is a PR, but it’s poorly phrased. I’d like to rephrase it.
* RM: If the earlier PR is merged, then this can be specified as pure syntactic sugar for that
* DN: I’ll rewrite, pass it by RM
* MM: It’s not unreasonable to have ++ work on floats, if it’s easy to specify
* DN: It’s not easy to specify.
* MM: The ULP of some floats is greater than 1, so +=1 can have no effect, so therefore, we should probably not support ++ on floats, to make it clearer that people are adding a tiny number to a large number.
* DN: It’s a little more of a footgun, so let’s not have ++
* JG: There’s merit to pure syntactic sugar definitions, though.
* DN: It’s all PDP worship
* JG: It doesn’t seem necessary
* DM: iteration is the actual need
* JG: we can abbreviate for loops ad nauseum but it doesn’t establish necessity
* MM: People do use ++ all the time
* JG: but the frequency of something’s use is not evidence for its necessity. We should weigh the actual quality of life engendered by the feature. Many popular languages don’t have it
* BC: But every time I trip over its absence, I wonder why it was taken away from me
* JG: People get used to Python.
* MM: Swift doesn’t have ++, but the reason is that they didn’t like the prefix/postfix confusion. They do have += because it lacks that ambiguity.
* JG: We solved that by saying it’s only a statement. If in the future += becomes an expression, then at that point I would really object to ++ as an expression
* MM: I will never want ++ as an expression, no matter what we do with +=
* JG: Well, with my and DM’s weak objections noted, let’s look at the revised PR and then accept it
* **ACCEPTED pending revisions**


</details>

**Comment by jdashg** [comment]
I think it's tolerably weird! You really do get used to it.
