### ISSUE TITLE
Support webgpu context canvas for copyExternalImageToTexture

### ISSUE THREAD

**Issue by qjia7** [gpuweb/gpuweb#2350]
The current [spec copyexternalimagetotexture](https://www.w3.org/TR/webgpu/#dom-gpuqueue-copyexternalimagetotexture) says that `If source.source is an HTMLCanvasElement: Its canvas context mode must be "2d", "webgl", or "webgl2"`. It seems that webgpu context mode is not supported.
However, for [tfjs-webgpu](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-webgpu), we are meeting a scenario which may need webgpu context mode supported.

Some users of tfjs are using tfjs' result in their gpu programs. If they directly use gpu backend (webgl/webgpu) to do the prediction, they hope only have gpu->gpu copying to move tfjs's result to the `GPUTexture` of their gpu program. However, for tfjs-webgpu, we create a `GPUDevice` silently for webgpu backend and donot expose it to upper user. To get the result, the user either reads data to cpu by `tensor.data()` or gets data from a `HTMLCanvasElement`.  For the latter, the user can implement gpu-gpu copying to move tfjs's result to **another device's** `GPUTexture`. However, to support the latter path, we need webgpu context mode is supported for copyExternalImageToTexture. Otherwise, there will be an extra copy needed (webgpu canvas -> 2d canvas/webgl canvas -> webgpu canvas). And webgl doesn't exist such kind of problem.

**Comment by kainino0x** [comment]
I avoided allowing webgpu canvases as sources initially because it had the potential to save implementation work for a feature I wasn't sure was actually necessary. This could be a compelling use-case: some middleware (like TF.js) wants to produce image data on the GPU, so it exposes an HTMLCanvasElement with the appropriate contents, but doesn't promise what the context type of the canvas will be. This way an application works regardless of whether TF.js is using a WebGL backend or a WebGPU backend.

In theory, ImageBitmap could be used for this purpose. With `OffscreenCanvas.transferToImageBitmap()` an ImageBitmap could be produced from the canvas (zero-copy, because it detaches the drawing buffer of the OffscreenCanvas), then used as a source to copyExternalImageToTexture.
In practice, however, it may be much harder for browser implementations to make this efficient (ImageBitmaps don't fundamentally know what they're going to be used for, or on which adapter - solving this requires heuristics or specifying new options for transferToImageBitmap).

**Comment by shaoboyan** [comment]
Babylon.js construct WebGPU Engine with code:
```
new WebGPUEngine(canvas: HTMLCanvasElement, options?: WebGPUEngineOptions): WebGPUEngine
```
TFJS also has an API named fromPixels which could accept `HTMLCanvasElement` as input.

 It seems that libraries might need the ability to accept HTMLCanvasElement without the knowledge of the context. By adding ability to copy from WebGPU context canvas will accelerate some use cases for these libraries.

**Comment by kainino0x** [comment]
Resolution: Allow any canvas that can generally be used as an image source. In particular, use toDataURL as the litmus test: if it works, so should this. Agreement that implementations don't necessarily _have_ to do the fastest possible thing in every case, so as long as they can implement toDataURL they should be able to make a slow implementation that doesn't incur much maintenance burden. (webgpu-to-webgpu would most likely get optimized though.)

**Comment by kainino0x** [comment]
Filed #2373 for fully expanding this. Meanwhile, we can simply add "webgpu" to this list to address the most important concerns. @shaoboyan would you be willing to open a PR for it?

**Comment by shaoboyan** [comment]
@kainino0x  I'll make a PR for this.
