### ISSUE TITLE
Should unreachable-code be an error or warning?

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#2378]
The specification states in multiple places that unreachable statements should be an error. This is mostly clearly described in the behavior section's [7.6.2. Notes](https://www.w3.org/TR/WGSL/#behaviors-notes):

> Here is the full list of ways that these rules can cause a program to be rejected (this is just restating information already listed above):
> * The body of a function (treated as a regular statement) has a behavior not included in {Next, Return, Discard}.
> * The body of a function with a return type has a behavior which is neither {Return} nor {Return, Discard}
> * **A statement without Next in its behavior is not the last in a sequence of statements**
> ...

Several people have expressed a strong preference for unreachable-code to be a **warning**, instead of a hard-error.
What's the group's thoughts on this?

---

Note that Tint will need to consider unreachable-code as a warning anyway while transitioning to the new behavioural analysis, as the old specification **required** all functions to end in a return, and now this may be treated as an error. Example:

```rust
fn f(x : bool) -> i32 {
  if (x) {
    return 1;
  } else {
    return 2;
  }
  return 0; // <-- Was previously required to compile
            //     but now considered unreachable, and so an error 
}
```

**Comment by kvark** [comment]
I think this would be a positive thing. There is no direct harm by allowing unreachable code, but there is a good deal of convenience associated with it. It becomes easier to trans-pile anything to WGSL, and it allows users to insert early returns for debugging.

**Comment by litherum** [comment]
Error on this kind of unreachable code would have avoided the [goto fail](https://en.wikipedia.org/wiki/Unreachable_code#goto_fail_bug) bug, which is a pretty strong argument I think.

On the other hand, I do understand the value of being flexible to let authors hack on functions during their development process.

What if we made it mandatory to emit warning about unreachable code? That way, we'd have the best of both worlds - people could hack on their code, but also developers will be guaranteed to at least be notified that they're doing something potentially harmful.

We (the CG) may also want to add a -Werror option, too, though this has different tradeoffs.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-12-07-(APAC)-Minutes#should-unreachable-code-be-an-error-or-warning-2378">WGSL meeting minutes 2021-12-07</a></summary>



* BC: Complaints from developers wanting to do an early return.  Implementing in Tint, and found some cases that used to be required one way are now an error. So implemented as a warning.  Modified behavior analysis to say “unreachable statements don’t contribute to the overall behavior”.  To make the change for a warning would require some thought to spec it.
* MM: I think we’d be ok with warnings. I would like this to be a “normative warning” (which is new) where we’d *require* this to generate a warning.
* DN: I think we can implement this in CTS, and at least show that this does generate a warning.
* AB: I don’t like it being a required warning. If it should always be raised, it should be an error, otherwise just a warning. If an implementation wants, it can, though.
* KG: Common workflow; there are languages that complain about unreachable code. Done naively. Can do ‘if (1) return;’ as an escape hatch.
* BC: Yes, in current rules in the spec you can use if (true){return;}
* KG: Ton of prior art for this kind of thing.  Often says “you have code after a return”.
* BC: Another reason folks have asked for this as a warning: code generation. Behavior analysis has to be replicated in the code generator. 
* MM: Generator may have to know about behavior analysis anyway.  May already have to know about it due to uniformity.
* BC: Case in point is spirv reader in Tint produces WGSL.  Was nontrivial enough to that I wrote a transform to strip from the AST, instead of modifying the construction in thef r
* KG: Phrasing:  “statements after control flow” is what’s made problematic.
* AB: If we add constexpr at some point, then could expect to see through “if (true)” to be analyzed.
* RM: Are you suggesting a new different analysis for this warning?
* KG: It’s purely a lexical analysis.  /look for stuff after continue, break, return. A nonlocal exit.
* RM: I’d be fine with warning rather than error. Developers can choose to pay attention to warnings, and then elect to treat that as an error. There is no security or portability issue that we are guarding against.  Folks writing code generators can use the “if true return” trick.
* AB: I want there to be a future with constexpr that we’ll evaluate and pay attention to the condition.  I view ‘if (true)’ trick as short term.
* MM: As long as the dead code elimination is run after the constexpr analysis.
* AB: Run the behaviour analysis after the constexpr.
* KG: I want to see protection against the tripping hazard.
* MM: That matches my thoughts.  We should guarantee that compilers will do something in response to the kind of bug that caused the goto fail problem. Don’t have opinion error vs. warning. Should guarantee the programmer will be notified somehow.
* KG: I like status quo.    Error required, and you can work around it with if(true) trick.
* GR: Precedent?
* KG: “most languages”.
* **Resolved: Continue to have an error.**


</details>

**Comment by kvark** [comment]
I raised this topic again on the office hour, and I think I have a problem with this statement:
> Generator may have to know about behavior analysis anyway. May already have to know about it due to uniformity.

I believe the ecosystem would flourish better if generating WGSL did *not* require behavioral or uniformity analysis.

If the generated code doesn't validate because of uniformity, that's a real situation, because the source shader wasn't semantically correct.
But failing validation because of dead code is silly.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2022-01-11-Minutes#should-unreachable-code-be-an-error-or-warning-2378">WGSL meeting minutes 2022-01-11</a></summary>



* (During office hours, we came to believe that we misunderstood each other when reaching for consensus)
* RM: I think it would be ok if it were a warning that users could choose to make fatal/an error.
* AB: I really really don’t like spec-mandated warnings
* DN: “SHOULD” says do it unless you have a reason not to, so that might match well for this.
* MM: I think we’d be ok with SHOULD instead of MUST
* MM: If there’s a uniformity error in dead code, is that an error?
* DM: Can there be? We would realize it’s not run, right?
* DN: We will post an example. It’s a subtle case.
* **Consensus: SHOULD warn on dead code**


</details>

**Comment by dneto0** [comment]
Agreement is to change the spec:  no longer shader creation error.  but "should" issue a warning (without prescribed text).

**Comment by dneto0** [comment]
Relatedly, the behaviour analysis now has to produce valid answers for new cases that are not covered by the current rule set.  This will have a knock-on effect on the uniformity analysis #1571

**Comment by RobinMorisset** [comment]
Turns out there are quite a few possible meanings of "allow dead code" as we discussed in office hours, so let's try to list them for comparison. As a reminder, currently, the rule for `s1 s2` is the following (with a tweaked syntax so I can easily put it in this comment without having to figure out the details of tables in markdown):
```
if (s1: B1, s2: B2, Next in B1)
  return (B1∖{Next}) ∪ B2;
```

### List of options
#### 0) Keep the current statu-quo (forbidding syntactically dead code)

#### 1) Just allow Next to be absent in B1

In terms of rule we would get:
```
if (s1: B1, s2: B2, Next in B1)
  return (B1∖{Next}) ∪ B2;
else if (s1: B1, s2: B2, Next not in B1)
  return B1 ∪ B2;
```

This is very easy to implement and understand.

#### 2) When Next is absent, just return B1, but still check the behavior of s2

In terms of rule we would get:
```
if (s1: B1, s2: B2, Next in B1)
  return (B1∖{Next}) ∪ B2;
else if (s1: B1, s2: B2, Next not in B1)
  return B1;
```

This is more precise in cases like the following:
```
fn foo() -> i32 {
  discard;
  return 42;
}
```
Since it would give it the behavior {Discard} instead of {Discard, Return}.

As we have a rule that requires Return in the behavior of any function with a return type, the function would then get rejected.

#### 2b) Like 2, but remove the rule that requires Return in the behavior of any function with a return type

Now we have the extra precision, and we accept this function. But we give a behavior of {Next, Discard} to code like:
```
var x : i32 = foo();
```
despite it not being able to do anything but discard. The reason is that the rules for expressions were written under the assumption that every function call in an expression has a chance to return a value.

#### 2c) Like 2b, but modify the rules for expressions with extra precision 

This is essentially https://github.com/gpuweb/gpuweb/pull/2515.

#### 3) Don't bother analyzing s2 at all whenever Next is not in B1
```
if (s1: B1, Next in B1, s2: B2)
  return (B1∖{Next}) ∪ B2;
else if (s1: B1, Next not in B1)
  return B1;
```

This would allow code like:
```
fn foo() -> i32 {
  return 42;
  continue;
}
```
in spite of the rule that `continue;` should always be within a loop.

Proposals 3b and 3c, analogous to 2b and 2c are also possible.

### Comments

I personally prefer either 1 or 0, as both are very easy to define, justify and implement.
2 is not my preference, but would still be reasonable. I consider 3 pretty bad, since I don't know of any language that would silently avoid doing static checks on code based on an analysis saying that it is dead.

One possibly important point to note is that we can move from 0 to 1 to 2 to 2b to 2c over time without breaking backwards-compatibility since it progressively allows more programs. So I would like to stick with one of the earlier options for now and only move to the more complex ones if we find a real-world need for them.

Did I miss any other options that anyone wants to advocate for?

**Comment by litherum** [comment]
One thought I had - currently the spec disallows something like this:

**Comment by litherum** [comment]
One thought I had: Right now the spec disallows something like this:

```
fn foo(x: i32) -> i32 {
    if (x == 3) {
        writeToSomeGlobalBuffer();
        discard;
    } else {
        writeToSomeOtherGlobalBuffer();
        discard;
    }
}
```
presumably because it's trying to be helpful - you said the program returns an `i32` but it never actually _does_ return an `i32`, so you've probably got a bug.

The group also resolved to allow something like this (I think?):
```
fn foo(x: i32) {
    if (x == 3) {
        writeToSomeGlobalBuffer();
        return;
    } else {
        writeToSomeOtherGlobalBuffer();
        return;
    }
    writeToAThirdGlobalBuffer();
}
```
but allowing this is contrary to the above desire for the compiler to be helpful and try to catch your bugs for you.

I don't think it makes sense to allow one but disallow the other. We should probably either allow both or disallow both.

**Comment by alan-baker** [comment]
In terms of the options Robin laid out my opinions are:
Option 0. Good from a spec POV, but annoying for users so not my favourite option.
Option 1. I dislike the imprecision of this option. Subtracting the real next from the behaviour just seems wrong.
Option 2a. This feels strange that dead code leads to behaviour problems
Option 2b. I dislike this option since it seems to intentionally provide an incorrect answer
Option 2c. I do like increased precision of the analysis
Option 3. I actually like this option

To me, behaviour analysis is not a syntactic (although it is based on syntax) check like parsing or type checking. If, in c++, I had a nullptr dereference in dead code I would want a static analyzer to complain. I'd expect it to restrict itself to code that could possibly execute. In a way, the syntax and type checking are about making sure the program is well-formed, which is only a part of being valid (table stakes). I think there ought to be more leeway for other validity checks to not have to apply to dead code (mostly because I see it as an inconvenience).

**Comment by RobinMorisset** [comment]
> To me, behaviour analysis is not a syntactic (although it is based on syntax) check like parsing or type checking

I think this is a major difference with how I see things. I see behavior checking as a part of type checking, and originally I was thinking in terms of "expression types" and "statement types" before picking the less confusing names "types"/"behaviors".

**Comment by dneto0** [comment]
To me, some higher principles apply:

- **Serves-uniformity principle**: Behaviour analysis exists primarily to support uniformity analysis.  That's more important than what we say about dead code, which is a design choice.
- **Intent principle**: We should keep the intent of the definition of a behaviour as "a summary of the ways in which control flow can exit an evaluation".   We should avoid shortcuts that make that definition untrue. Of course, we should allow conservative analysis for the sake of tractability.


With that lens:

Option 1:  Violates the intent principle.   When Next is not in B1, there is no way control will flow from s1 to s2.  So B2 should not matter, and does not contribute to the behaviour of "s1 s2"

Option 2: Better about the intent principle.  But I would *not* check the behaviour or uniformity of B2 when Next is not in B1.  Why?
- There is no way control will get to s1.  So any assertion of fact or diagnostic about the potential execution of s2 is made up. There is no way it can happen.   
- We should avoid issuing diagnostics about that code: it's just noise.  The author may be deliberately cutting off that part of the code so they can focus on *other* code with *other* diagnostics.  Don't flood them with useless noise.  When they remove that cutoff (delete a return), then the analysis will reach the code they re-enable.

Example:
```
    fn foo_return_return(c: f32) -> f32 {
      return 0.1;  // Author deliberately supplying a dummy value.
      return textureSample(t,s,c).x;  // Could potentially trigger a uniformity error at the call site of foo.
             // This goes against their explicit intent of doing the early return with the fixed 0.1 value.
   }
```

I heard it suggested that the author should use a block comment instead (which can nest).  But the `return 0.1;` is less work in the editor: it's a one line edit rather than a multiple line gotta-find-the-end-of-the-function edit.

So I guess that means any variation of option 2 is out, and I only like Option 3.

The behaviour of`fn foo_discard_return() -> i32 { discard; return 42; }` should be {Discard}
Similarly  `fn foo_discard() -> i32 { discard; }` should also be {Discard}

It would be very strange if someone transformed foo_discard to foo_discard_return and have that result in going from invalid to valid. (!!)

So I think we should keep the "function with return type must reach a return" rule, and so foo_discard_return should be invalid.


Option 2b: Violates the intent principle, as above.

Option 2c: Sounds good to me.

Option 3: This is good.  But also keep the "function with return type must reach a return"

Note:  continue outside a loop is already disallowed by the grammar. We don't need behaviour analysis to do that.
Similarly, placement of a fallthrough is constrained by the grammar.

But the argument applies to `break`. We need behaviour analysis to check that it's not outside a loop or switch.
But if it's placed in truly unreachable code, it's harmeless. It can only become harmful when the cutoff of that early return is removed.
```
fn foo_return_break() -> i32 {
   return 12;
   break;  // dead.  Also harmless, at least until the early return is removed.
}
```

I think I ended up in the same place as @alan-baker .  I didn't have to make analogies to type checking though.  Hopefully I've explained my rationale as grounded in user experience principles.

**Comment by dneto0** [comment]
Regarding @litherum's cases  in this comment: https://github.com/gpuweb/gpuweb/issues/2378#issuecomment-1016857521 
* The first function has behaviour {Discard} and arg_i connected to MustBeUniformForControlFlowAfter.
* The second function has interior behaviour {Return} (converted to {Next}) and arg_i connected to MustBeUniformForControlFlowAfter.

The stated rationale of the analysis is a "desire for the compiler to be helpful".
But there's multiple rules being checked:
- dead code: is about whether the inside of a function body makes sense. 
- are calls to this function sensible
      -  does the function produce a value when it promises to
      -  propagate uniformity damage out to call sites

No matter how we decide the "allow dead code" question, the call-site analysis should still be "correct".   So the analysis of the two function can and should be different.

There are two functions in the "middle" of the two that help us separate cases:

```
fn foo_discard_discard_value(x: i32) -> i32 {
    // Invalid because this function promises to return a value, but does not.
    if (x == 3) {
        writeToSomeGlobalBuffer();
        discard;
    } else {
        writeToSomeOtherGlobalBuffer();
        discard;
    }
    writeToAThirdGlobalBuffer();  // dead. That's fine. separate question.
}

fn foo_discard_discard_void(x: i32)  {
    // Valid.   function behaviour is {Discard}, arg_i has an edge to MustBeUniformForControlFlowAfter (I think)
    if (x == 3) {
        writeToSomeGlobalBuffer();
        discard;
    } else {
        writeToSomeOtherGlobalBuffer();
        discard;
    }
    writeToAThirdGlobalBuffer();  // dead. that's fine.
}
```

**Comment by litherum** [comment]
> are calls to this function sensible

For a function that unconditionally discards, I think the answer is "yes" because it is unobservable from the caller’s point of view that it never ended up returning a value. It seems pretty natural to me for the rule to be "all control flow paths that don't discard need to return a value" - thereby treating discard and return as siblings.

I guess I view discard the same as undefined in Haskell, where it seems totally natural to me to have a function that says it returns i32 but actually discards unconditionally instead.

**Comment by dneto0** [comment]
> For a function that unconditionally discards, I think the answer is "yes" because it is unobservable from the caller’s point of view that it never ended up returning a value. It seems pretty natural to me for the rule to be "all control flow paths that don't discard need to return a value" - thereby treating discard and return as siblings.

I can see that as a totally consistent view.

I guess my higher level point is that question is actually independent of "allow _dead_ code" decision, so we have flexibility.
So it turns on what is more likely to be helpful, and not get in the way.

**Comment by dneto0** [comment]
@kvark  filed #2523.

> During the office hour we discussed a case where all control flow ends with discard, and whether we want to support it.
It conflicts with this rule in the behavioral spec:
>
>  > If the function has a return type, the behavior of its body must be one of {Return} or {Return, Discard}.
>
> I raised the concern that this restriction feels artificial and unhelpful, and that we should also allow {Discard} behavior.

The provoking use case is [described here](https://github.com/gfx-rs/naga/issues/1679#issue-1110334090)

>In pygfx we generate wgsl shaders with a form of templating. One of the shaders we generate has a fragment function that ends with an unconditional discard:
```
[[stage(fragment)]]
 fn fs_main(varyings: Varyings) -> FragmentOutput {
     ...
    discard;
}
```

And that author wants this to be valid.

So that would be support for @litherum's formulation "all control flow paths that don't discard need to return a value".

**Comment by RobinMorisset** [comment]
Thank you for the detailed answers.
I don't get however how the same arguments don't apply to type checking:
- type checking serves safety
- Intent: the type of an expression expresses an (over-approximation) of the set of values that can be computed when that expression is evaluated.

Dead code is by definition never evaluated, so the intent principle would argue against bothering to type-check it. And similarly it has no impact on safety And similarly all of the other arguments about using `return 0.1;` instead of a block comment should apply.

So I am wondering whether I am missing some difference, or whether you are also in favor of skipping type checking in statically dead code.

**Comment by kdashg** [comment]
It's generally desirable to get type checking on code even if the compiler sees that it is never used, and I do believe that's what people expect to happen.
I don't think we should go looking for more ways to be different here.

Returns have to typecheck with the return type, but for ways to leave the function without returning anything, there's nothing to typecheck.

I think our category for "function exits" in shaders is just [`return`, `discard`], and all control flows must exit the function. (If we have the concept of trapping, this could be another element of the category)
This isn't much different from "all control flow paths that don't discard need to return a value", but the different emphasis makes it more natural that discard is not merely an exception to some 'everything must return' rule, but rather that they're conceptual peers.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-01-25-minutes#should-unreachable-code-be-an-error-or-warning-2378">WGSL meeting minutes 2022-01-25</a></summary>



* RM: Already agreed to allow unreachable code, with a warning.
    * But what is the behaviour analysis of that code.
    * What should be checked inside that code.
    * 
* RM: I think we should not treat these questions differently. Don’t think it’s wise to allow dead code to be silently bad.
* KG: Should type check dead code no matter what.  For behaviour or uniformity, I’m more fuzzy.  Not sure of the philosophical tying them together; whether that’s the driving factor. Should decide on their own merits, not the tying principle.
* MM: What is the motivation for discussing this.  Design choice or codegen example.
* DM: We like dead code when we hack on stuff. Also codegen examples show us this is wanted.
* MM: If we know of codegens that exercise the weird case, then we can try to be as strict as possible that accommodates those cases.
* DN:  Like the change: For functions with a return type "all control flow paths that don't discard need to return a value".
* BC: Tint implementation does not accumulate behaviours for unreachable code.  Argument is it’s control flow analysis: what are the kinds of execution paths through your code. You have a return, then content underneath. That’s definitely unreachable. Behaviour analysis right now feeds on the inputs and paths into that block.  So that code after the return doesn’t have an input from anywhere. Your behaviour analysis is definitely going to draw invalid conclusions about that code (there are no inputs).  Gets worse with uniformity.  Example you could imagine:  a uniformity bug post-return, but then it goes away when the terminating return goes away; or vice versa.  Value-type analysis is much less context-dependent that way.
* RM: Behaviour analysis is always conservative. Can’t be 100% precise.  We still run it even over `if (false) { .. } `  So don’t see why we run it on one kind of dead code, but not another.   Not clear why it’s different from type checking, but I see I’m in the minority in considering it that way.
* RM: We can make rules that are more strict (reject more programs), then relax later.
* DM: We have a framework in analyzing what dead code is.  Let’s use it. If the framework new that “if (false) { … } “ is really dead then we would take advantage of it.
* RM: The soundness of the analysis cannot depend on not running the dead code. It’s always safe to be more conservative.
* DN: When I insert a return in the middle of development, I deliberately want to cut off analysis of tha tlater code when I work on another  part.  Value type-checking I still want because of programming culture: it arrived much earlier than flow control checking.
* KG: I view value-type checking in dead code as a feature.  In Mozilla code I’ve moved away from #ifdef and toward constexpr conditions, so that static type checking is enforced on any platform I’m working on.
* MM: Maybe we want a new keyword to mean “cut off analysis here”, rather than trying to do it with “return …;”.
* KG: Want to see examples where it breaks down.


</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-02-01-minutes#should-unreachable-code-be-an-error-or-warning-2378">WGSL meeting minutes 2022-02-01</a></summary>



* RM: During the last meeting, folks stated positions, but did not reach consensus.  Might be useful to split motivations  There are two audiences: folks writing generators; folks hand-writing code. The motivations are slightly different. For hand-written code it’s easy to use comments to remove code from consideration.
* KG: In the abstract, yes, but want to emphasize the value in having dead code type checked.
* RM: Also in favour of that. 
* RM: If you have code you don’t want to type-check, then commenting it is better than making it dead.
* DN: In my mind, value type checking is about expressions and names and those are lexically scoped, but behaviour+continuity is truly about inter-block and inter-procedural analysis of flow itself; and that’s tightly bound to control flow.  It’s a false analysis to have a ‘discard’ in dead code to bleed out.
    * 
* JB: One view of type checking is it’s an approximation to the possible dynamic behaviours.  So in that view you wouldn’t want to type check in dead code.  But decades of practice does do that checking in dead code.  Behaviours and uniformity is trying to answer questions about control flow so it’s sensible to treat them differently.
* Ben:
    * Ben Clayton2:15 PM
    * fn a() -> i32 {
    *   return 5;
    *   discard;
    * }
    * 
    * fn b() {
    *   for (var i : 32; i &lt; a(); i++) {
    *     // ...
    *   }
    * }
* DM: Like Jim, want to understand why we should analyze flow in dead code.  We have a mandated model of when code is going to be executed. It’s an approximation.  But let’s use the analysis for what it’s for.
    * Example in a Vulkan implementation if code is actually dead, then it can’t violate any uniformity rules.  So a sufficiently smart analysis would see that.  But we have a conservative/coarse analysis.
* RM: Trying to understand one kind of analysis (value-type checking) is different from another kind of analysis (behaviour-uniformity).
* DM: My point is there should be no question about whether to analyze uniformity in dead code.  I believe we should not analyze behaviour or uniformity in dead code.
* MM: Point is either do both uniformity analysis and type checking, or neither.
* KG: As summarized by Jim, a lot is momentum/cultural. Even though in principle it’s different we’d be spending innovation points to do it.
* MM: We have previous experience/signal that type checking is done in dead code. But have no signal that uniformity analysis is done in dead code.
* RM:
    * fn c() {
    *   return;
    *   if (thread_id)
    *       derivative():
    * }
    * Think in this case the error should be reported. (In contraposition to Ben’s example)
* RM: We don’t have data on how often problems will occur and stop people from making an application.  It’s easier to remove a restriction later.
* AB: For Robin’s example, I’d say you can issue an error when that code becomes live.  And you haven’t lost anything.  To Myles’ position, we do have some signal; most languages don’t have a static check, and that itself is a signal. It’s not like the idea has never come up.
* JB: Question for Myles: In Ben’s code, what conclusion do you want about that loop.
* MM: Defer to Robin.
* RM: We have several options. (as laid out [https://github.com/gpuweb/gpuweb/issues/2378#issuecomment-1016834026](https://github.com/gpuweb/gpuweb/issues/2378#issuecomment-1016834026) )  (option 2 in the issue):. Check dead code uniformity but not let the behaviour result of that dead code flow outside.  I slightly prefer option 1, and say control flow is not uniform in this case.  Option 2 feels better to me than option 3, where we don’t check the dead code at all.
* DM: Comment on Robin’s example.  I would be very upset if it would be an error in this case.  Uniformity analysis would give me an error not for my program, but for a hypothetical program where one of my statements is ignored (essentially). So, why.
* RM: Have found it convenient to have more checks apply to code that isn’t currently in effect. Keep circling back to thinking of behaviour+uniformity as a kind of type-checking.
* Ben: Have two arguments:   use return to intentionally cutoff analysis; another view is check more than.  What’s going to annoy more people.  Presume the developer is experienced and knowing what they are doing.  My stance: annoy fewer people at potential loss of having a few people lose a feature.
* MM: Here’s a program where the compiler will complain about even though something essential is not exercised.
    * struct Foo { ... } struct Bar { ... } fn d() { return; var f: Foo; var b: Bar; f = b; }
* JB: "annoy the fewest people" has a lot of appeal, to me
* GR: I agree strongly. I don't feel we've universally applied that philosophy
* 


</details>

**Comment by dneto0** [comment]
I want to write down something I said yesterday but I don't think have written yet.

When dead code is detected, the implementation _already has a **should** obligation_ to issue a warning that there's something that looks wrong.  There's a risk of being annoying by cascading additional errors on top of that.

So, for example even in this ugly example from @RobinMorisset 's option 3, the user should already get a diagnostic.

```
fn foo() -> i32 {
  return 42;
  continue;    // implementation already *should* issue a warning for this dead code
}
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-VF2F-2022-02-08%2C09-Minutes#should-unreachable-code-be-an-error-or-warning-2378">WGSL meeting minutes 2022-02-08</a></summary>



* RM: I feel like things have gotten kind of stuck. We can easily change things in one direction in the future: We can allow more programs, but not the other way around.
* RM : I would like to stick to a most restrictive approach until we get data that it is bothering real users. We did get feedback that forbidding dead code was harsh for users, so we did allow that now. For analysis in dead code, that would be an error, and we can just wait for users to complain to us about it.
* DM: And that would include uniformity errors? (yes) What I said there was that we would be analyzing what we think the author wrote, rather than what they [meant?].
* RM: I think that’s like type checking. And I’m not sure that type checking and behavior are distinct checks.
* MM: I do think that we are validation what authors wrote, since they did write it, and they get what they get.
* DM: We would check validation for uniformity, but we would have to e.g. check uniformity past the point where we realize there’s e.g. a return and where dead code begins.
* E.g. should be rejected:
```
return; 
If (thread_id == 1) 
  control_barrier();
``` 

* This should be allowed:
```
If (thread_id == 1) { 
  return; 
  control_barrier(); 
}
``` 

* AB: As a user encountering this, I would be scratching my head.
* I would like the same kind of thing for rejecting the first one:
```
Return;
If (42u == 43.0)
```
* DN: The difference for me between value checking and behavior checking is with how e.g. uniformity analysis bleeds out of its immediate surrounds. BC said, once you get to * dead code, nothing in dead code affects behavior.
```
switch(thread_id) { … replace with a function body if needed, to make the point
  default: {
    break;  
    discard;  // this should not poison the textureSample below.
  }
}
textureSample
```

* DN: Don’t want behaviour of dead code to leak out badness to beyond it. I care about this more than whether we check dead code intrinsically.
* KG: Maybe to crystalize, maybe then “whether behavior analysis validates dead code” would fall out of a definition for the analysis. If all the edges leave, then the dead code couldn’t violate (some example of) an analysis. (I think a point DM made)
* AB: Type checking is precise.  We don’t get the types wrong.  There’s no ambiguity.  But for flow analysis, the author can know more than the compiler might be able to.  Author knows this code won’t execute.  People will complain on Twitter.
* RM: I do want to push back on DN’s “type checking is lexically scoped”, because behavior checking is lexically scoped also.  Option 2 does what David wants. I see behavior checking as a type of type checking.
* DM: One point to reemphasize is that static languages always check types, even though dynamically typed languages don’t.
* RM: Surprised by this claim that types are precise. I feel like it’s very similar to saying a piece of code has certain behaviors, though at runtime it has a subset of the possible behaviors of that snippet [in the abstract].
* KG: Uniformity analysis can be consistent in several ways.  It’s a choice.   Can be tautological.
* RM: For this analysis “dead code” is   s2 in   “s1 s2” where S1 does not have Next in its behaviors.   It’s a definition.
* MM: I don’t think discussion on philosophy is helping make progress here. What specifically would move the needle on peoples’ opinions here? In particular, can we wait until users complain?
* DN: I would need to see why it’s helpful to the user. Adding a cutting-off “return” is an intent by the user to say “stop control flow here”.  The implementation already has a “should warn” obligation in that case when there is code that follows that cutting-off return.  I would need to see why it’s helpful to a user to add potentially _additional_ errors based on control flow when the user knows the flow won’t get there.
* RM: 
* AB: I would like behaviour analysis to be as precise as possible.  Then uniformity analysis should provide useful errors when it can detect them.  The closer I can get to precise behaviour analysis, then we can pay less attention to the uniformity analysis. 
* KG: Concretely you want us to iterate more on behaviour analysis to reduce the false negative cases, such that it’s precise enough so people wouldn’t have frustrating problems with it.
* AB: There are two ways we can go, (taking aside errors vs. warnings).  Prefer to decide on sets of rules like, where “s1 s2”, if “s1” has behaviour {Return}, then analyze “s1 s2” as having behaviour {Return}, i.e. ignore the behaviours coming from s2 in this case.  Compared to the current draft the spec, this allows more valid programs, and gives more precise info about the actual actions of the program.  Would add rules to the table, but that’s ok.
* AB: Uniformity analysis already needs to know behaviours.  Propose adding more behaviour cases where it reflects reality of the execution.
* RM: Can change rule to avoid adding behaviours from dead code is easy (spec wise and conceptually).  Would be ok to modify the rules to disconnect a subgraph when that subgraph is proven to be “dead”.  But much harder to modify uniformity analysis to not even run/analyze on dead code (building a subgraph for it in the first place).
* AB: We could make uniformity analysis be more aware of behaviours.  Now we’re talking about mechanisms. But not further on philosophy.
* RM: Could try to write versions of the analysis to show the options.
* DN: Would be most helpful if that came with separating cases.
* AB: what would it take for me to change my mind.  Will people understand.  Like the idea of workshopping different sets of rules.  E.g. if get 800 lines of spec that’s not graspable by folks.
* RM: **Can try to write proposals, and re-open /revisit Alan’s earlier PR.**
* AB: Will look at that and discuss internally.


</details>

**Comment by alan-baker** [comment]
I drafted #2622 to spec the changes necessary to support allowing unreachable code and not having that unreachable code contribute to uniformity errors.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-03-01-minutes#should-unreachable-code-be-an-error-or-warning-2378">WGSL meeting minutes 2022-03-01</a></summary>



* Alan’s proposal: [https://github.com/gpuweb/gpuweb/pull/2622](https://github.com/gpuweb/gpuweb/pull/2622) 
* Previously:
    * RM: Current state.  I was supposed to write a PR to show possible spec text.  Let’s delay.
* AB: There were actions for me and Robin.  I wrote my proposal, in a PR as draft, for review. Think it looks quite minimal in:
    * Non-uniformity problem in unreachable code is not an error. That’s what Google desires.
* MM: Robin is preparing a PR.  Let’s come back to this.
* KG: Will take time to do homework.
* RM: Looked at Alan’s PR.  Nice surprise that it’s smaller than expected. Don’t think I can make mine simpler or nicer. Ok with landing his PR.
* KG: Did you have different goal. 
* RM: I did, but realized I was in minority.
* RM: Also, David noted in an issue is that there is already a “should” obligation to issue a warning for the existence of the dead code.  Don’t think it’s too bad to not get uniformity errors in that dead code. Implementation won’t be *completely* silent. Programmer will get notification to look closer.
* KG: **Ok, have consensus direction**.  I need to review.
* MM:  This program:   ​​  fn foo() { return; break; }    is valid.  But has a “should” obligation to issue warning.


</details>
