### ISSUE TITLE
spec: Cannot bind "null" texture.

### ISSUE THREAD

**Issue by Axiverse** [gpuweb/gpuweb#2389]
The current specification requires that a texture is bound when create bind groups. Generally, APIs that I'm familiar with do not require a bound texture and will read 0s in those instances. I don't know if metal or other recent apis don't allow this. Is this intentional?

Workaround: create a 1x1x1 texture to put in place of all "null" textures.

**Comment by Kangz** [comment]
> Generally, APIs that I'm familiar with do not require a bound texture and will read 0s in those instances.

I'm pretty sure that only the OpenGL family of APIs does that. It would be undefined behavior (and likely a crash) on D3D12 / Metal and Vulkan. It's on purpose because WebGPU guarantees the safety of operations, and dereferencing a null texture would do bad things. Like you found, you can create the 1x1x1 texture and add it to your bindgroup.

If we decided that WebGPU should do that for you, then we'd need to specify that it is a 1x1x1 texture (because the size is visible in the shader). But IMHO we that would be adding a bunch of complexity to implementations for somewhat of an edge case that can be resolved in the application side.

**Comment by Axiverse** [comment]
It's been a while since I worked on D3D12, but 11 definitely works fine. I don't remember this distinctly being an issue when I did work on D3D12, though perhaps I'm wrong there. The workaround is fine in this case. Thanks for explaining.
