### ISSUE TITLE
wgsl: Preferred way to extract mat3x3 from mat4x4

### ISSUE THREAD

**Issue by Axiverse** [gpuweb/gpuweb#2399]
A common operation is to extract the rotation/scaling matrix from a transformation matrix. This is done by taking the first 3 rows and columns of a mat4x4 and creating a mat3x3 from that. What is the preferred way to do this?

e.g. HLSL lets you do a straight cast:
```hlsl
  float3 normal = mul((float3x3)World, IN.Normal);
```

**Comment by alan-baker** [comment]
Right now, you'd have to break it down into the columns and swizzle those to vec3s.

```
let myMat3x3 = mat3x3(myMat4x4[0].xyz, myMat4x4[1].xyz, myMat4x4[2].xyz);
```

**Comment by jdashg** [comment]
You can also do (something like) `let normal = (World * vec4<f32>(IN.Normal, 0)).xyz;`, if my memory serves me right.

**Comment by Axiverse** [comment]
That's correct, I've used the method described by @jdashg above. Closing as there's a reasonable work around.

**Comment by lcodes** [comment]
Can this be reopened?

The workaround is adding more shader ops than necessary when having many instances of vec4(x,y,z,1) needing to be transformed to a vec3(x,y,z,0) and then back again.

Workarounds should be handled by the implementation, not pushed to users. This could also be useful to other functions where scalars have to be manually lifted into vectors; if the hardware supports it, all good; otherwise it should be up to the implementation to coerce the scalar into a vector during shader translation time.

**Comment by lcodes** [comment]
It's also non-intuitive when translating GLSL/HLSL code into WGSL and finding that commonly adopted expressions no longer work, then wasting time searching for workarounds.
