### ISSUE TITLE
"Storage class" term is unnecessarily confusing

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2440]
Having a "storage class" of something being "storage" is a good way to confuse a lot of people.

### History

Our "storage class" is inherited from SPIR-V. In SPIR-V this term appeared originally in 1.0, while the working group realized later that they actually need "storage buffer" being one of the types and added it post-factum in 1.1 and "VK_KHR_storage_buffer_storage_class" extension. Just look at this extension name!

@dneto0 can shed some light here. My expectation is that the "storage buffer" class didn't get designed at the right time, hence it got a very unfortunate naming conflict.

### Proposal

Rename all the "storage class" to something neutral and less confusing. Like "memory class".

Edit: "storage type" -> "storage class"

**Comment by dneto0** [comment]
I think you mean having a "storage class" named "storage".

That I can buy.

Right.  We need names for two things at least.


| Language  |  first buffer kind | second buffer kind | Notes |
|-------|---------|-------------|-----------------
| GLSL / OpenGL  |  Uniform Buffer Object, or UBO, limited size, read-only, and weird layout constraints | Shader Storage Buffer Object, or SSBO, can be read/write, flexible layouts | |
| WGSL | uniform buffer | storage buffer | |
| OpenCL |  __constant |  __global |  No weird layout constraint differences 
| MSL | constant | device | No weird layout constraint differences
| HLSL | constant buffer, cbuffer |  (lots of things) | Constrained cbuffer layouts are legacy |
| Vulkan SPIR-V | Uniform storage class with Block decorated struct | StorageBuffer storage class with Block decorated struct | Newer-ish. <br> Weird layout constraints disappear if the implementation supports VK_KHR_uniform_buffer_standard_layout, and that's in core in Vulkan 1.2  |
| Vulkan SPIR-V | Uniform storage class with Block decorated struct | Uniform storage class with BufferBlock decorated struct | Original, and nobody liked this. Consider it deprecated (almost) |

I have no appetite for "constant" as a word because have so many kinds of constants already:  let, override, read_only. Boo.

## Here come "push constants"

I expect we'll see something akin to "push constants" which I think of as "pass the values directly in the descriptor register set, so it's very small space but fast because it eliminates a level of indirection compared to UBO".
These matter because they make a meaningful performance difference.

I think "push constant" is a very non-intuitive name!
We could call those things draw-constant or dispatch-constants, because that's when their values are finalized.  But I haven't discussed this with anyone else...

**Comment by kvark** [comment]
I think the "storage" itself is fine as a class name. The issue is about "storage class" as a meta-term under which "uniform", "storage", "private", "function", and "workgroup" all live.

The fact that we got confused here is just another confirmation that this is a real issue :)
