### ISSUE TITLE
Should GPUCompliationIssue.messages be an ObservableArray?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#2447]
https://github.com/gpuweb/gpuweb/blob/9c5272e77d57bf4c0dce5701045e2c31f50e23bf/spec/index.bs#L4152

A notification just crossed my email in some other API where they were changing something that was a FrozenArray into an ObservableArray. The comment said [`ObservableArray`](https://webidl.spec.whatwg.org/#idl-observable-array) is a standard javascript array so you can do `myArray.push(someValue)` on it among other things. I'm completely out of my element here so I don't know if this makes sense or not, but.... I recently needed to manipulate the error messages and to do so I had to make a copy

```
const myCopy = [...info.messages];
```

Where as apparently if it was `ObservableArray` I wouldn't have needed that step? It's not a big deal, but then it's not like this is a link into some internal data structure so maybe it should just be `ObservableArray` to start?

**Comment by kainino0x** [comment]
Huh, I don't think I knew about this. Maybe it's relatively new.

> The comment said [`ObservableArray`](https://webidl.spec.whatwg.org/#idl-observable-array) is a standard javascript array

My reading of the spec differs, though I'm not totally sure I'm understanding correctly. In particular: "Both of these algorithms are optional, and if not provided, the default behavior will be to do nothing" seems to mean that if you don't override either algorithm, then you can't actually change the contents of the array (as with FrozenArray although I'm not sure if the behavior is exactly the same). If that's true, we'd have to override both to make it behave like a normal array.

I think if we wanted to return a *new* array object from each call to compilationInfo() we could return a `sequence<GPUCompilationMessage>` instead. That [gets converted](https://webidl.spec.whatwg.org/#es-sequence) to a brand new JS array every time it's passed out into JS.

> a link into some internal data structure

This depends on whether compilationInfo() returns the same object, or constructs a new one, every time it's called.

**Comment by kainino0x** [comment]
Editors: We can consider this in the future but right now there's no compelling reason to change this since `[...info.messages]` is a viable workaround. In particular we think it makes the API unclear whether editing the messages array would be visible to future callers of `compilationInfo()` or not.

Also I searched my email and I think the thread you're talking about is [this blink-dev thread](https://groups.google.com/a/chromium.org/g/blink-dev/c/8p7QvGn3Ezo) referring to adoptedStyleSheets changing from FrozenArray to ObservableArray - ObservableArray was apparently created for that purpose. My understanding there is that mutating the array *does* have an effect, which previously had to be achieved by copying the array, modifying the copy, and then assigning `adoptedStyleSheets` back to the new array (`adoptedStyleSheets` is a non-readonly attribute).
