### ISSUE TITLE
Supporting MSAA without rendering capability?

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2465]
Discussion spawned from #2463 and related to #2459.

Should we support creating MSAA textures even if one can't render to them?

For example "r8snorm" can't be rendered to because of Vulkan, but can be multisampled in all of the APIs. Problem is - there is no way to use such a texture. You can't render into it. You can't write into a storage binding of it. You can't copy from buffer into it (since multisampled). You could copy from another texture into it, but the formats have to match, and that another texture has the same problem then.

Proposal - forbid this at texture creation. Not only it's practically useless, it's also going to be a problem for implementations, which still need to zero-initialize such textures. Since there is no way to populate this texture, it can't be zero-initialized.

**Comment by kainino0x** [comment]
I agree it makes sense to forbid this. I forgot that if we didn't we would actually allow creating the useless texture.

I think we should make a real spreadsheet of all of the format capabilities in all of the APIs and use it to derive our tables. Then we can formalize in the spreadsheet the exact logic behind each of our capabilities.

**Comment by kainino0x** [comment]
Resolved to add this limitation

**Comment by Jiawei-Shao** [comment]
Hi all, will this issue be discussed before V1?

**Comment by kdashg** [comment]
@Jiawei-Shao Is there anything else here that you think we should discuss? It sounds like we decided to forbid creation of a type of resource that had no valid use given the rest of our API.
If there's a use-case for MSAA that's not met, can you file a separate issue about that?

**Comment by Jiawei-Shao** [comment]
> that

In the latest SPEC [r8snorm, rg8snorm and rgba8snorm supports "multisampling"](https://gpuweb.github.io/gpuweb/#plain-color-formats), while actually they don't always support multisampling in Vulkan according to Vulkan SPEC, which is causing [failures in Chromium bots](https://bugs.chromium.org/p/chromium/issues/detail?id=1299154).

So I'd expect this issue can be finally resolved (either we do or don't support MSAA on the formats without rendering capability) so that I can fix those test failures.

**Comment by kvark** [comment]
The issue is in "Needs Specification" stage.
