### ISSUE TITLE
Consider removing or reworking implicit pipeline layouts

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#2470]
Hi. For the past six months or so, I've been helping people learn the WebGPU APIs from people of all skill levels, and one of the big stumbling blocks has been implicit pipeline layouts. This feature has caused a lot of confusion and might be the biggest cause of support that I've seen.

To me, that suggests that even if we decide the feature is helpful and keep it, we should at least rework some details of its design. A non-exhaustive list of issues I've seen:

1. Beginners are confused by code samples and tutorials. Some code samples provide bind group layouts, and others rely on implicit pipeline layouts. Two ways to do something is really confusing, and tutorials do not motivate why both options exist.
2. The algorithm feels magical, and I've experienced users become scared or afraid to modify their shaders once they get things working. Using implicit pipeline layouts correctly means understanding what the algorithm will do in all scenarios, which does not feel like it significantly helps lighten cognitive load. Some users I've helped feel more comfortable with their code after adding explicit pipeline layouts, since they now know all the relevant places to adjust, rather than having to "reverse engineer" what the algorithm is doing to build a bind group that matches.
3. The error messages are not great, and it's unclear how what should be changed to get something the user will want. While I expect implementation error messages to improve, I suspect the magic-ness of the algorithm to remain an impediment to users.
4. A silent loss of performance. On many devices, changing the BGL will incur a full device flush. Implicit pipeline layouts are easy to reach for, and it's not always obvious that the user is trading *performance* when relying on implicit pipeline layouts between different devices, and not just precision or specificity.

For these reasons, I don't believe that implicit pipeline layouts are providing a huge benefit over explicit ones, and I feel, given my experience, beginner users become a lot more comfortable not using them, instead using explicit pipeline layouts.

I have been told in the past that intended use case for them was for "simple" shaders like post-processing shaders. If we decide to keep implicit pipeline layouts, I still think we should rework their implementation to help limit the concerns given above. Here are a few non-exclusive options:

1. Reduce their scope, and make it so that only very simple shaders work (the "postprocessing" case). Perhaps, once the user is using uint/int textures, or storage buffers, we throw an error and tell the user that implicit pipeline layouts are not supported if the shader uses an advanced feature; this should cut down on the amount of accidental resource mismatches. Bikeshedding might be required for what features are "advanced".
2. Make implicit pipeline layouts harder to reach for. Rather than automatically kicking in if the user does not provide a layout, maybe we should make the user provide something like: `layout: 'implicit'` in the pipeline. This would require the user to look at the documentation and possibly read about the pros and cons; if the left was instead left missing, the user might never think to look. As an example, TypeScript does not warn on a missing field, so a user filling out their pipeline field by field until TypeScript stops erroring out might not ever notice the "layout" field, nor read its documentation.
3. Make pipeline layouts easier to specify. If explicit pipeline layouts are too annoying to specify, we might want to look into why, and see if there are approaches or helpers we can specify to make this easier. See for one example, #2469.

**Comment by brendan-duncan** [comment]
There are a number of cases when implicit layouts fail, too. When using dynamic buffer offsets, for example.

**Comment by m-schuetz** [comment]
Not a huge fan of explicit layouts because they require you to specify the layout twice - once in the shader, and once in JS. I'd rather have WebGPU deduce the layouts directly from the shader. But yes, the occasional pitfall when the explicit layout suddenly doesn't work is confusing, especially without helpful error messages.

**Comment by magcius** [comment]
I should probably mention my usual guidance: if you are going to be using multiple shaders / pipelines, you want to keep the pipeline layouts as similar as possible. First of all because it's nicer to share bind groups between them, but secondly, performance will remain the best and most consistent if pipeline layouts are shared as much as possible.

As stated today, the static usage rules make this difficult to do for larger numbers of shaders, and you cannot share bind groups between two pipelines with implicit pipeline layouts, even if those layouts are equivalent.

**Comment by Kangz** [comment]
The guidance to use the same pipeline layout is useful when doing a lot of draws / dispatches (thousands) but in @m-schuetz's case with Potree, my understanding is that there's a very small number of dispatches (< 100) so there is no perf gain to be had by sharing bindgroups (it is nowhere close to the bottleneck).

**Comment by kainino0x** [comment]
Adding to editor's meeting to discuss option 2 specifically, which would be very minor.

**Comment by kainino0x** [comment]
Editors liked option 2 but we're still discussing the overall issue.

**Comment by kainino0x** [comment]
OK, so when the editors were discussing this, we ended up going on a bit of a tangent on it. We started thinking that a tweak to the design could make them significantly more useful and wonder if it would alleviate problems people have with the current API. Notes:

- We like option 2 (user must explicitly choose automatic layouts instead of having it be implicit)
- But we also would like if it were possible for a pipeline to have partially implicit layout (mix explicit and implicit BGLs) because then you can achieve bind group reuse without having to jump fully to explicit
- This seems it would essentially make pipeline layout objects obsolete, since they're compared by value (not by reference): #2550

Anyway that was a bit of a tangent and we were contemplating proposing something like this (or similar but without having a GPUPipelineLayout object at all):
```
dictionary GPUPipelineDescriptorBase : GPUObjectDescriptorBase {
    required (GPUPipelineLayout or GPUPartialPipelineLayoutDescriptor) layout;
};

dictionary GPUPartialPipelineLayoutDescriptor {
    required sequence<GPUBindGroupLayout or GPUAutoBindGroupLayoutMode> bindGroupLayouts;
};

enum GPUAutoBindGroupLayoutMode {
    "auto",
};
```

**Comment by toji** [comment]
Summarizing an editors conversation on the topic earlier today: The proposal in #2572 to remove `createPipelineLayout()` is a decent one, but at this late stage it's not so critical that it's worth making the breaking change for. We'd prefer to defer ergonomics changes in this area till post-v1 in order to keep the focus on other more pressing issues.

There's still a reasonable path forward for this change post-v1 where `layout:` is updated to accept an array of `BindGroupLayout`s directly OR a `PipelineLayout` object. That leaves `PipelineLayout` as a little bit of a weird API wart, but that's not the end of the world.

Despite the desire to defer that particular change, there's still a desire to implement the `layout: "auto"` suggestion from above in v1 as a more explicit way of opting in to implicit pipeline creation. A PR for that will be put together shortly.

**Comment by magcius** [comment]
This seems solved to me now that we added the explicit "auto" sentinel.
