### ISSUE TITLE
Determine whether getBindGroupLayout returns a new object or not

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2501]

**Comment by Kangz** [comment]
It has to return a new object, at least when the pipeline has an implicit layout, because we don't know on the content timeline what the bindgroup actually is. For explicit BGLs we could keep the JS wrapper object and pipe it around to the pipelines so they can be returned in `getBindGroupLayout` but that doesn't seem super useful?

**Comment by kainino0x** [comment]
Editors decided this should just return a new object every time as already written in the spec.
@toji to add `[NewObject]` to getBindGroupLayout.
