### ISSUE TITLE
constrain attribute alignment value to divide device alignment limits

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2505]
When creating a GPUBindGroup, validation requires a buffer binding's offset to divide the device alignments:

* for uniform, resource.offset is a multiple of limits.minUniformBufferOffsetAlignment.
* for storage or read-only-storage:  resource.offset is a multiple of limits.minStorageBufferOffsetAlignment.

There is an extra constraint not quite captured anywhere:
- the alignment requirement of the store type an associated WGSL buffer variable must divide the bindgroup's offset (and also base address).

To keep things simple we propose the simple constraint:
- The alignment of the store type for a uniform buffer must divide limits.minUniformBufferOffsetAlignment.
- The alignment of the store type for a storage (or read-only-storage) buffer must divide limits.minStorageBufferOffsetAlignment.

Those two limits are device-wide, so the constraint can be checked early: at shader creation time or at pipeline creation time.   I'm not too fussy about which of the two, because both are off the critical path.

Thanks @kainino0x for the suggested simple constraint.

Note: Indirectly, this might constrain the magnitude of the `align` and `size` attributes in WGSL.

Note: Currently WebGPU says picking a "better" (smaller) alignment requirement always relaxes constraints.  This would no longer be true, so that language would have to be adjusted.

**Comment by kainino0x** [comment]
For completeness I want to also explain David's original proposal, which was to put the alignment constraint in GPUBufferBindingLayout (in the bind group layout) and validate: shader offsets must divide BGL offsets, and BGL offsets must divide BG offsets.

In particular I think this is also worth considering, because adjusting this:

> Note: Currently WebGPU says picking a "better" (smaller) alignment requirement always relaxes constraints. This would no longer be true, so that language would have to be adjusted.

is going to need some consideration. It was designed this way so that libraries/middleware can assume the base limits of a device, and then they'll work on any device the application hands them. This breaks that - **if** we allow these two limits to actually be configured (#1865).

**Comment by Kangz** [comment]
> There is an extra constraint not quite captured anywhere:
>
>  - the alignment requirement of the store type an associated WGSL buffer variable must divide the bindgroup's offset (and also base address).

Is that a constraint in the APIs that we target? It seems that the `min[Storage|Uniform]BufferOffsetAlignment` limits can be guaranteed to always be at least the  "worst required memory load" requirement, in which case on the API side we can ignore the alignment of the WGSL type. All that the alignment is used for is for WGSL to define the memory layout, but it doesn't have an effect apart from that?

I'm suggesting this solution because adding validation for the memory alignment seems unfortunate when it will be exceedingly rare that the alignment provided by the developer will be more than `min[Storage|Uniform]BufferOffsetAlignment` so it is unnecessary CPU overhead.

**Comment by dneto0** [comment]
> Is that a constraint in the APIs that we target?

It's an implied contract with the application author, that the implicit type alignments and explicitly-requested alignments will be honoured.  It imposes a chain of promises:  buffer base address +  offset into that buffer will divide the promised alignment of the buffer variables.

There are two reasons for the alignment promises
- load and store alignments imposed by hardware constraints. E.g. bus error on SPARC if loading a 32-bit int on anything other than 4-byte aligned.
- additional requirements by the programmer.  This is only possible with an explicit align attribute.  The programmer may want this to do cache-line alignment, for example, to avoid false sharing. (This use case can't be addressed by adjusting sizes.)


> I'm suggesting this solution because adding validation for the memory alignment seems unfortunate when it will be exceedingly rare that the alignment provided by the developer will be more than min[Storage|Uniform]BufferOffsetAlignment so it is unnecessary CPU overhead.

The idea of the simpler check means it can be checked off the hot path: at shader creation time.

**Comment by dneto0** [comment]
> It was designed this way so that libraries/middleware can assume the base limits of a device, and then they'll work on any device the application hands them. 

To spell it out: ... works on any _better_ device....

So, for example if the middleware is developed on a device with min[Storage|Uniform]BufferOffsetAlignment = 256, then it will always work on a device with min[Storage|Uniform]BufferOffsetAlignment = 2.  (Yea, that's extreme and weird.)

> This breaks that - if we allow these two limits to actually be configured (#1865).

Interesting. I didn't know the motivation for it.

**Comment by dneto0** [comment]
There's two ways to think about this.

The API-side attitude (so far) is that alignment rules are **only** about the strict hardware-based load/store alignment requirements, and making a simple promise to middleware.

The question is how to balance the strictness of those against a shader-requested alignment request beyond those.

Consider other use cases for the explicit request:
- a shader generating block-based data for use with specialized hardware
    - compressed-textures (e.g. ASTC uses 128-byte blocks, as I've just learned)
    - tensors being fed into specialized tensor cores

You'd want these to be handled with zero-copy, so you want the originating code to be able to assume high alignments will be honoured, and avoid the need for fallbacks.


If we side with taking the application promise seriously, the middleware promise is expressed as a range instead, e.g.
  "This middleware works with any device with min buffer alignment between 64 and 256."

**Comment by Kangz** [comment]
From what I can read in this thread, we have three possibilities, each with their own drawback:

 1. Don't require the alignment declared in WGSL to match the alignment of the GPU pointer given in the `GPUBindGroup`. The drawback is that it breaks a programmer assumption and could cause other alignment issues down the line.
 2. Require that the alignment in WGSL is less than the `minAlignement` limits. The drawback is that now opting into a better limits can introduce validation errors.
 3. Check that the alignment matches between WGSL and the `GPUBindGroup` at draw/dispatch time. This requires a check added for each draw/dispatch whether the pipeline needs additional validation for alignments.

Writing this down I realized another issue: in all implementations we expect small buffers to be sub-allocated from a larger allocation. It means that the start of each buffer is not at page granularity but could be anywhere (up to the granularity of memory accesses, since drivers would be asking for that). So I think we should take 1) since it would be very hard to provide real alignment guarantee of the GPU pointer.

**Comment by kainino0x** [comment]
If the alignment constraint were in GPUBufferBindingLayout then we could check it at createPipeline and createBindGroup. It's similar to minBindingSize, but I don't think it needs the special draw-time validation mode, because the ergonomic impact should be much smaller (even though this validation would still be a new invention compared with native APIs).

In option 1 would we just have undefined results if the alignments don't match properly?

> in all implementations we expect small buffers to be sub-allocated from a larger allocation. It means that the start of each buffer is not at page granularity but could be anywhere (up to the granularity of memory accesses, since drivers would be asking for that)

I think there's a finite maximum alignment that a shader can possibly need due to natural constraints (16 or 64 bytes maybe?). As long as the suballocator adheres to that constraint wouldn't it be OK? (I don't even think there would have to be a restriction on the max value of an align() in WGSL for this to be valid.)

**Comment by kdashg** [comment]
Is this actually a WGSL issue, or instead an API issue? @dneto0

**Comment by kainino0x** [comment]
It technically interacts with both, but more on the API side. I think we should have this slated for the main group agenda (eventually).

**Comment by kainino0x** [comment]
Here's a summary of the GPUBufferBindingLayout solution, as I understand/remember it:

- Add a GPUBufferBindingLayout.bindingOffsetAlignment defaulting to 256 (and can't be larger than 256). Then:
    - bindingOffsetAlignment must be a multiple of the WGSL alignment (check in pipeline creation)
    - bindingOffsetAlignment must be a multiple of the corresponding alignment limit (check in createBindGroupLayout)
    - static binding offsets must be multiples of bindingOffsetAlignment (check in createBindGroup)
    - dynamic binding offsets must be multiples of bindingOffsetAlignment (check in setBindGroup)

Another note, as long as the alignment limits are "unconfigurable" (#1865), I don't think we need to solve this now. We can just take option 2, and then adopt the bindingOffsetAlignment solution later if we make them configurable.

---

Rereading this conversation, I'm pretty sure that there isn't a fundamental requirement for the *declared* alignment to divide the binding address. The maximum [*required*](https://gpuweb.github.io/gpuweb/wgsl/#address-space-layout-constraints) alignment is static (16 bytes today, could maybe be 32 bytes for `vec4<f64>`?). So as long as the device alignment limits stay above the required WGSL alignment, I don't think we encounter any invalid/undefined behavior. Am I understanding this correctly? @dneto0 

As said by David here:

> There are two reasons for the alignment promises
> 
> * load and store alignments imposed by hardware constraints. E.g. bus error on SPARC if loading a 32-bit int on anything other than 4-byte aligned.

Then there's this second thing:

> * additional requirements by the programmer.  This is only possible with an explicit align attribute.  The programmer may want this to do cache-line alignment, for example, to avoid false sharing. (This use case can't be addressed by adjusting sizes.)

We'd need to decide how important we think it is to guard programmers against doing something that's valid, but probably not what they wanted. It seems to me this doesn't need to be a hard error. It could be a warning, _maybe_, but for example a programmer might use a large alignment as a practical way to create spacing between struct members/array elements, and not because they wanted to align with cache lines.

**Comment by dneto0** [comment]
I think this is an ok resolution.
The WGSL worst case alignment requirement (16) is a hardware-imposed constraint, and helps support portability.  So it's important to enforce that by spec and implementation.

The bigger alignments a shader author can request (e.g. 128) are about an application-level conventions.    The proposed solution here says that it's not the business of the API implementation to enforce that contract.  Instead it's up to authors to check the documentation for each component they use.  At best, I could see using reflection on the shader to extract the desired constraint, and then checking that against the various interacting middleware components.

As  a concrete example, consider block-based ASTC algorithms:  The system designer uses a bunch of different components, and needs to make sure things like the memory (sub)allocator can serve up memory blobs that are 128-byte aligned. And they know they need 128-alignment because the package of shaders advertise that constraint.

I think WGSL should have a non-normative note saying that up to a certain factor, the API checks the buffer alignments, but beyond that it's the application's responsibility.
