### ISSUE TITLE
Parameter order in writeBuffer and copyBufferToBuffer

### ISSUE THREAD

**Issue by terier** [gpuweb/gpuweb#2511]
I noticed that writeBuffer accepts the destination buffer first and then the source buffer, while in copyBufferToBuffer it is the other way around. Is this intended? Has it already been discussed before? If there are no specific reasons for these orders, would you consider unifying them?

**Comment by kainino0x** [comment]
Thanks for filing! I suspect writeBuffer is this way because it has optional arguments for the source data, and writeTexture is this way to match that. But it's a fair point.

I think this relates to #244 which proposes not to have those optional arguments to the source data. If we did that then this change would become more obvious.

I've added it to the list of stuff for the editors to discuss (although I've put a lot of stuff in that bucket lately, so we might not get to it this week).

**Comment by terier** [comment]
To be honest, given the current naming, it is completely reasonable that writeBuffer should accept a destination buffer as the first parameter, and that copyBufferToBuffer should copy some source buffer to a destination buffer. It would seem more appropriate though to change the names of the copy*To* functions, but I unfortunately do not have any obvious suggestions. The order of the parameters of each function separately makes sense, only when looked at as a whole it is mildly annoying that they are not unified. :slightly_smiling_face:

Thanks for considering this for the editors meeting!

**Comment by kainino0x** [comment]
Editors discussed and think that the current name (writeBuffer/etc) is best and this is the ideal order for the arguments (writeBuffer: which buffer, what to write).
