### ISSUE TITLE
Indirect Parameter Struct compatibility investigation

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#257]
[Originally filed](https://github.com/gpuweb/gpuweb/pull/155/files#r243832661) by @devshgraphicsprogramming - moving here so we can see it.

> Vulkan and D3D12 seem portable in their Indirect parameter buffer structs (same argument order w.r.t. semantics and data type)
> 
> Unindexed
> https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDrawIndirectCommand.html
> https://docs.microsoft.com/en-us/windows/desktop/api/D3D12/ns-d3d12-d3d12_draw_arguments
> 
> Indexed
> https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDrawIndexedIndirectCommand.html
> https://docs.microsoft.com/en-us/windows/desktop/api/D3D12/ns-d3d12-d3d12_draw_indexed_arguments
> 
> Compute
> https://docs.microsoft.com/en-us/windows/desktop/api/D3D12/ns-d3d12-d3d12_dispatch_arguments
> https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDispatchIndirectCommand.html
> 
> 
> As for sourcing the draw count in MDI from a buffer, it seems that Vulkan (via VK_KHR_draw_indirect_count) and Metal may be compatible
> https://github.com/KhronosGroup/MoltenVK/issues/168
> 
> That would also imply that Metal is compatible with the above indirect draw and dispatch parameter buffers.
> 
> The only change WebGPU may have to make is add more usages, because D3D12 seems to split the `INDIRECT` Vulkan usage into 3 distinct usages (un-indexed, indexed and dispatch).

> Also a Khronos discussion about whether to map HLSL's `Buffer<>` to "Uniform Texel Buffer"
> https://github.com/KhronosGroup/glslang/issues/795

**Comment by litherum** [comment]
Here are the buffer layouts for Metal. They correspond to `drawPrimitives`, `drawIndexedPrimitives`, and `dispatchThreadgroups`, respectively.

```Obj-C
typedef struct {
    uint32_t vertexCount;
    uint32_t instanceCount;
    uint32_t vertexStart;
    uint32_t baseInstance;
} MTLDrawPrimitivesIndirectArguments;

typedef struct {
    uint32_t indexCount;
    uint32_t instanceCount;
    uint32_t indexStart;
    int32_t  baseVertex;
    uint32_t baseInstance;
} MTLDrawIndexedPrimitivesIndirectArguments;

typedef struct {
    uint32_t threadgroupsPerGrid[3];
} MTLDispatchThreadgroupsIndirectArguments;
```

https://developer.apple.com/documentation/metal/mtlrendercommandencoder?language=objc#3036994
https://developer.apple.com/documentation/metal/mtlcomputecommandencoder?language=objc#3314720

**Comment by litherum** [comment]
Now that I think about this some more, I don't think it matters very much what the buffer layout is. We're going to have to validate these fields for all 3 layouts. The validation can also be in charge of reformatting the fields to whatever form the platform needs them to be in.

Sticking validation in the middle of a render pass is difficult, because there's no guarantees that draw calls are strictly ordered inside a single pass. Instead, we should probably record a separate command buffer which does the validation, and submit it just before the command buffer that contains the render pass gets submitted. This requires that the indirect buffer doesn't get populated from within the same command buffer, which is a restriction which I think is worth it. We should enforce this restriction and report an error if the author tries to do it wrong. This enforcement will have to occur regardless of whether the GPU/driver happens to support the robust access behavior.

Support for indirect draws/dispatches is valuable because it allows for some effects (like particle systems) which exist entirely on the GPU. Trying to download data from the GPU in order to issue draw calls would likely incur a frame of latency because of how our mapping calls work, which makes these kinds of effects impossible. This, coupled with the fact that all 3 APIs support these facilities in almost exactly the same way, make a fairly strong case for including these facilities in WebGPU.

**Comment by kainino0x** [comment]
I think this is actually all covered by #31. We already added the indirect calls to the spec a few months ago when Idan was working on it. We also discussed validation on the call and in #320 and for now we are assuming that for render we'll do vertex pulling on Metal and use robust buffer access everywhere else, and for compute we'll clamp in a compute shader (which should be okay to be inline since it'll already be in a compute pass).

Anyway, is there anything here that's not in the other places, or should we just close this one?

**Comment by litherum** [comment]
Aha! I didn’t realize they were already in the spec. That’s great!

Which telecon did we agree on doing vertex pulling in Metal?

Robust buffer access works everywhere else? That’s surprising.

**Comment by kainino0x** [comment]
> Aha! I didn’t realize they were already in the spec. That’s great!

#317

> Which telecon did we agree on doing vertex pulling in Metal?

We didn't agree on a telcon, but we were the only ones still arguing for it so I decided to drop it and close #320 until someone comes up with a concrete reason we need to reconsider nooping bad draw calls.

> Robust buffer access works everywhere else? That’s surprising.

Vulkan requires it, D3D has had it in core since at least D3D11, and we rely on it on many OpenGL implementations too. For untrusted robust buffer access implementations, we'd have to do workarounds like index buffer copy+clamp or vertex pulling (probably the former).

**Comment by litherum** [comment]
> We'll probably reopen this discussion when we do more investigation/implementation.
