### ISSUE TITLE
Proposal: Make `(` `)` optional for `if`, `switch` and `for`

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#2575]
The requirement for each of these to follow with an opening brace (`{`) means there's no grammatical need for parentheses.

`if` and `switch` take an expression, so these naturally can accept parentheses as this can be parsed as part of the expression:

```rust
if cond { ... }
// or
if (cond) { ... }
```

```rust
switch val { ... }
// or
switch (val) { ... }
```

For loops would require a bit of special casing in the spec:

```rust
for var i = 0; i < 5; i = i + 1 { ... }
// or
for (var i = 0; i < 5; i = i + 1) { ... }
```

For people coming from C / C++, nothing has to change when writing your shaders. For people who are more familiar with Rust, Swift, Python, Go, Lua, etc then this is one less (albeit minor) C-ism to deal with.

---
Note: This is a personal suggestion, not an official Google proposal.

**Comment by munrocket** [comment]
This is not solve any problem, but makes grammar harder. 

```
for var i = 0; i < 5; i = i + 1 { ... }
```
Looks like this is not rust/c/c#/lua/python/js, but it’s go.

**Comment by RobinMorisset** [comment]
I can see the argument against it for `for` loops, but it seems very readable to me for `if/switch`, and seems to match some other languages such as rust which inspired other parts of the syntax.

`loop (cond) {}` is not currently in the language, but I have proposed adding `while`, and I also believe that making the parenthesis optional around its condition would be good.

**Comment by dneto0** [comment]
Discussed in [2022-02-09](https://docs.google.com/document/d/1r5QbKsqwZxZzD2CqbpteTGJ2bQwTHje_coZ8UCIAyik/edit#bookmark=id.yf5wk9say1yu).

Agreed to the change for `if` and `switch`.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-vf2f-2022-02-08,09-minutes#proposal-make---optional-for-if-switch-loop-and-for-2575">WGSL meeting minutes 2022-02-09</a></summary>

* BC: Parens around these things don’t serve any purpose. The parens can be absorbed by the expression.  Some folks at Google expressed preference against this, from background in C.  Many modern languages don’t require this. I keep getting compilation errors.
* BC: The for loop is the most contentious of these.  Golang allows the form shown.  You know in the grammar when the thing is over.  Because we enforce braces.   
* RM: Fine going either way for for loops. For if and switch, precedent of Rust shows it’s readable without the parens.
* DM: Appreciate removing these parens is backwards compatible.  But for-loop looks weird. Would rather keep it.
* KG: My feeling as well.
* MM: An argument in favour of the “for” is Jim suggested having new kinds of for-loops; for those, you would not have parens.   You’d want whether parens are required to be the same for all the kids of ‘for’ loops.
* KG: Can be backward compatible to remove them later.
* KG: Like that it allows these to be optional.  Not so foreign to me any more. I write python too, and it’s optional there.
* KG: The point about making it harder if we want to omit the curly-braces.  I’ve been proponent of making braces optional in the past, so a bit sad. But at least it’s the same number of characters saved.
* MM: Might be reasonable to say you can omit the braces but only if you keep the curlies, and vice versa.
* **_Resolved needs spec for “if” and “switch”.  Not resolved for “for”.  To revisit the “for”, make another issue._**

</details>
