### ISSUE TITLE
Reconsider adding `while` to the language

### ISSUE THREAD

**Issue by RobinMorisset** [gpuweb/gpuweb#2578]
In https://github.com/gpuweb/gpuweb/issues/569 we debated for a long time which constructs to have between `loop`, `continuing`,`for`, `while`.

I do not wish to reopen the question of `loop/continuing`. What I'd like to discuss before V1 is the possibility of adding `while(e) { s }` as syntactic sugar for `for(;e;) { s }`. This would not replace or remove `loop/continuing` in any way.

It has the obvious benefits of making the language more familiar and convenient to write for new programmers, while being trivial to implement (being mere sugar for trivial `for` loops). And I believe it would match our recent attempts to make the language more convenient with things like https://github.com/gpuweb/gpuweb/issues/2243, https://github.com/gpuweb/gpuweb/issues/2492.

**Comment by dneto0** [comment]
Given the sentiment around parentheses for `if` and `switch` (#2575), I assume the parentheses are not required for the condition.

**Comment by RobinMorisset** [comment]
I agree, I think that being able to do `while x < 4 { ... }` is quite nice compared with `for (; x < 4 ;) { ... }`, so I'd like to make the parentheses optional.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-vf2f-2022-02-08,09-minutes#reconsider-adding-while-to-the-language-2578">WGSL meeting minutes 2022-02-09</a></summary>

* RM: Since prior argument long ago, we added ‘for’ as syntactic sugar. Want to repeat the pattern to give a while loop, as sugar over   for ( ; cond ; ) {  }
* RM: Benefit is familiarity.  Cost is small. Benefit is real.
* BC: In internal discussion, there were no strong feeling. My concern is having three keywords for expressing a loop.  An alternative is      loop (cond)  { }
* BC: Golang only has `for`, to express all these things.  It’s “the loop” of the language.  This is quite minor.  I can live with three keywords.  It’s remember what keyword maps to what kind of loop you’re dealing with.
* JB: Rust also has a “loop” keyword which has an infinite loop. It’s important in Rust. We have definite-assignment rule. We have type inference. Both  benefit knowing there is no exit other than a “break”.  So if you have while(true), you have to look at that condition, which is a burden. Having a syntactically specific form that has no exit is beneficial for a bunch of these analyses.  Seems we have analyses that would benefit.
* KG: you don’t think we will improve our analyses to recognize while(true).  Or is it something we need to teach best practice that loop { } and while(true) look like they do the same thing but they have material difference on analysis.
* JB: You do have to teach folks that sometimes loop is better to use.
* JB: It’s important to distinguish between analyses that the language guarantees will occur, and those that it could perform opportunistically. Sometimes it’s important to have a loop that is guaranteed to be infinite, independently of how smart the compiler is.
* AB: while is small amount of sugar on top of other things.  Seems reasonable.
* DN: Agree.  When we describe it in spec; prefer to see it as sugar over loop {  } Rather than two levels of sugar.
* **_Resolved needs spec._**


---


</details>
