### ISSUE TITLE
Workgroup Broadcast

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#2586]
As discussed in the [February VF2F](https://docs.google.com/document/d/1r5QbKsqwZxZzD2CqbpteTGJ2bQwTHje_coZ8UCIAyik/edit#bookmark=id.3at46l50old1), WGSL should get a built-in function `workgroupBroadcast`. This would allow users to branch uniformly on reads from storage buffers for example.

# Proposal
Workgroup broadcast is a new collective operation (i.e. must be called only in uniform control flow). It would be compute stage only. The function would return a uniform value (i.e. the same value for each invocation in the workgroup). Uniformity analysis would understand the built-in function and consider the result uniform regardless of the uniformity of the input value.

```
// Returns "value" for linear local invocation index 0 to all workgroup invocations.
fn workgroupBroadcastFirst(value : T) -> T

// Local invocation index 0 loads p and returns the value to all workgroup invocations.
fn workgroupBroadcastFirst(p : ptr<T, S>) -> T

// Possible, generic broadcast. Takes the local invocation index to broadcast (must be const expression).
fn workgroupBroadcast(value : T, linear_id : i32/u32) -> T
fn workgroupBroadcast(p : ptr<T, S>, linear_id : i32/u32) -> T
```

A possible implementation in pseudo-WGSL would look like:
```rust
var<workgroup> wg_storage : T;
fn workgroupBroadcastFirst(p : ptr<T, S>) -> T {
  workgroupBarrier();
  if (local_invocation_index == 0) {
    wg_storage = *p;
  }
  workgroupBarrier();
  return wg_storage;
}
```

Depending on the underlying implementation the polyfill could be improved to use subgroup broadcasts to reduce workgroup memory reads.

**Comment by kvark** [comment]
The feedback I provided on F2F had this note, roughly "we aren't sure this is the best form to expose the ability, and would like to think more about it". So here I'm trying to follow-up on that.

The issues I see with the current approach:
  1. The workgroup allocation is implicit. I believe WebGPU needs to validate the amount of workgroup memory the user needs against the limits of the hardware, and also - that WebGPU exposes tools for the users to write code in a way that would be guaranteed to pass this validation. This works best when the user declares all the workgroup-space data, although it's not a requirement. @jimblandy noted that explicitly listing workgroup memory also helps reasoning about occupancy.
  2. A lot of this code is technically something users should be able to do themselves. This includes loading from the original pointer (with the thread ID comparison), storing into the workgroup, the first barrier. There is very little of this code that needs special semantics.

Observation: right after the second `workgroupBarrier()` we could fetch *any* workgroup value and consider it to be uniform. There is nothing specific about `wg_storage` any more. From here, perhaps our API could be simplified to just this:

```rust
fn workgroupLoad(p : ptr<T, workgroup>) -> T {
  workgroupBarrier();
  // barrier ensures that the following load will get the same value for all threads
  return *p;
}
```

This is very much a regular load from a workgroup pointer, but it requires that `p` is uniform, that the function is invoked in uniform control flow, and it guarantees that the result is uniform.

I don't think I need to convince you why this is a better approach, but for completeness here are some thoughts:
  - smaller API surface (one function instead of 4)
  - less magic - special functions that can receive pointer arguments in address spaces that are unavailable to user functions, less generic functions that users can't write, etc
  - less polyfill - the user can combine the first barrier in the original `workgroupBroadcastFirst` with something they need from a barrier

There is one downside. There may be a more optimized implementation of `workgroupBroadcastFirst` versus the polyfill.
If we know of a smarter way to implement it, we can still expose a builtin function like `workgroupBroadcastFirst` in the future.

**Comment by alan-baker** [comment]
`p` will never be uniform according to the current analysis because it must derive from a global writable variable. So your proposal is missing the changes necessary to make that possible. Do you add a special rule for the address-of expression?

Your polyfill also has more opportunities to introduce a race. Consider:
```
let tmp = workgroupLoad(&wg_var);
...
wg_var = ...;
```

If the intervening code does not include proper synchronization (e.g. a barrier) the program is undefined. This sort of mistake is possible with the pointer version of my proposed function (I might argue to a lesser extent though), but not with the pure value version.

As for the benefits you list:
* if 4 function are too many we can choose to expose fewer
* this still uses a pointer in an address space available to the user (is it really so different because it is restricted to workgroup?)

**Comment by Kangz** [comment]
@alan-baker can you detail why `p` will never be uniform and why that matters? I'm not able to see the issue.

What about this polyfill though? It seems it prevents data races before/after and avoid the need to pipe local_invocation_index around. If it can be made correct, then it looks like it could be a good alternative?

```
fn workgroupLoad(p : ptr<T, workgroup>) -> T {
  workgroupBarrier();
  const v = *p;
  workgroupBarrier();
  return v;
}
```

**Comment by alan-baker** [comment]
The uniformity analysis currently says any reference to a writable global gets connected to CannotBeUniform. Inevitably this will be an address-of expression on workgroup (global) variable. That's why I asked whether Dmitry intends to change the uniformity analysis to have address-of expressions get treated specially. I haven't thought of an easy way to express the necessary change in the analysis. Consider:

```
var<workgroup> wg_var : array<u32, 4>;
let x = &(wg_var[0]); // this pointer is uniform, but currently the analysis says non-uniform
let y = &(wg_var[local_invocation_id.x]); // this needs to remain non-uniform after the change
```

In the example you need the graoh to connect the subexpressions, but then recognize the reference isn't for a load/store at this point.

**Comment by jrprice** [comment]
The motivation for adding a `workgroupBroadcast` builtin is because loading from a shared, writable resource (either `workgroup` or `storage`) produces a `MayBeNonUniform` value. We're starting to question whether this needs to be the case for non-atomic accesses.

In order for two different invocations to see two different values when non-atomically loading from a uniform address, something else would have to have written to that address in between those two load operations. Without any synchronization, this would be a data-race, and therefore undefined behavior. For this reason, we believe that it should be possible to change the uniformity analysis to consider non-atomic loads from writable resources to be uniform, rather than `MayBeNonUniform`.

This would remove the need to add a `workgroupBroadcast` builtin, since developers would not need such an escape hatch. 

One issue here is that FXC's own uniformity analysis rejects shaders that have conditional barriers, when the condition comes from load from a `RWByteAddressBuffer`. This might prevent us from making this change for the `storage` address space.

**Comment by kdashg** [comment]
> we believe that it should be possible to change the uniformity analysis to consider non-atomic loads from writable resources to be uniform, rather than MayBeNonUniform.

Do you mean "non-writable resources" here?

**Comment by jrprice** [comment]
Here's an example of a shader where different invocations of a workgroup would receive different values for the same load expression without any data-races, because the load occurs on different iterations of a loop:
```
@binding(0) @group(0)
var<storage, read_write> data : array<u32>;

let workgroup_size = 64u;

@stage(compute) @workgroup_size(workgroup_size)
fn main(@builtin(local_invocation_index) local_id : u32) {
  var x : u32;
  for (var i = 0u; i < workgroup_size; i = i + 1u) {
    workgroupBarrier();
    if (local_id == i) {
      // Load a value from data[0] if the iteration count matches my ID.
      // The index is uniform, but this load will happen at different
      // iterations of the loop for different invocations, and they will get
      // different values.
      x = data[0];
      data[0] = local_id;
    }
    workgroupBarrier();
  }

  // Non-uniform, because the value of `x` is non-uniform.
  if (x % 2u == 0u) {
    workgroupBarrier();
  }
}
```

In this case, even if the load itself is always considered to be uniform (due to the above proposal), the variable `x` would still be considered to have a non-uniform value on exiting the loop, since its assignment is conditional. Therefore, this shader would still be rejected, as we would hope.

**Comment by kdashg** [comment]
Oh, sorry, I see now!

**Comment by kvark** [comment]
@jrprice 
> In order for two different invocations to see two different values when non-atomically loading from a uniform address, something else would have to have written to that address in between those two load operations. Without any synchronization, this would be a data-race, and therefore undefined behavior. For this reason, we believe that it should be possible to change the uniformity analysis to consider non-atomic loads from writable resources to be uniform, rather than MayBeNonUniform.

Vulkan, Metal, D3D12 can be heavy handed and just say they don't care about the behavior in this case, and yet I'm confident that many shipped applications rely on *some* sort of behavior there. For example, if you are writing to the same integer value from 2 different pixel invocations, you expect that everything will be fine, world will not explode, and the resulting value will be one of the 2 that pixel invocations tried to write.

I see where you are coming from, but I'll have to disagree. In WebGPU we can **not** simply have undefined behavior. 
Unsynchronized load/stores into storage buffers in WebGPU *should* produce undefined values instead of undefined behavior. For this reason, considering these values "uniform" doesn't make a lot of sense (from this perspective, at least).

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-03-08-minutes#workgroup-broadcast-2586">WGSL meeting minutes 2022-03-08</a></summary>



* JP: Posted comment just before. Discussing, and want to revisit the idea that loads from writable resources will be nonuniform. The only examples we could think where different values coming from that would be data races, and therefore already undefined behaviour. So would change uniformity analysis to rule those loads as not automatically uniform.  And so would need this feature less.
* KG: Aren’t we trying to protect against undef behaviour in the first place?
* RM Looking at the example, with the rules as currently, even if the load you’re doing is uniform, if it’s done in non-uniform *flow*, it’s still non-uniform.
* JP: Exactly, that’s the point of the example.  Only place you would see different values _without a data race _ is when you’d already analyse the example as non-uniform.  So there’s no more reason to add the extra rule.
* KG: Can you have written in a nonuniform way, but now later you’re in uniform control flow. And then get wrong analysis.
* AB:  The index is uniform as well, which makes a difference
* RM: Think agree. Can’t have a case where reading from uniform location, and without data race, see different values.
* MM: So say there is a race, and we allow this program, and program does a derivative. What’s stopping that derivative that isn’t owned by your application.
* AB: Your sandbox has to be resilient against undef behaviour in the shader. It’s not WGSL that can do it.
* MM: As an implementor, don’t see how to strongly guarantee that.
* AB: Then we have a bigger problem. Undef behaviour has lots of ways of occurring.   It’s not just derivative.
* AB: Go think about it. Texture operations should be sandboxed like any other memory operation.
* **Timebox’d, let’s think more.**


</details>

**Comment by litherum** [comment]
I agree with @kvark. The whole point of the uniformity analysis is to prove that certain expressions are uniform. If we allow nonuniform-in-practice values to lie within expressions we detect to be uniform, then there’s no point in the proof, and we might as well not do any uniformity analysis at all.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-03-15-minutes#workgroup-broadcast-2586">WGSL meeting minutes 2022-03-15</a></summary>



* JP: Previously, we said that the only time a load could actually have non-uniform behavior was in the presence of a data race, and I think we should just accept that yeah, a data race makes things non-uniform (undefined behavior). The sticking point seems to be whether data races produce undefined behavior, versus undefined values.
* MM: It is within the rules for the metal shader compiler to look at your program, prove a data race, and do whatever it wants.
* 


</details>

**Comment by Kangz** [comment]
I have a similar concern as @kvark and @litherum if we decide to just say "it's UB so you're on your own". While UBs are technically anything, on a specific hardware and compiler, what happens is defined and most likely results in undefined values being loaded written. No compiler will explicitly go out of its way to break your code, and we assume at least some level of sanity in the UB, otherwise UB could lead to allowing OOB accesses for example (which we discussed in a separate issue).

One reason the uniformity analysis is there to help developers produce correct code, that for example won't deadlock the GPU because they called `workgroupBarrier` in control flow that's not workgroup uniform. In general memory loads of a uniform pointer into read-writable memory don't result in a uniform value and we must help developers by making that part of the type system (otherwise we'd be lying). So they need a way to make that value uniform somehow, either with `workgroupBroadcastFirst` or with a `@uniform(workgroup) fn unsafeThisValueIsUniformIPromise(t : T) -> @uniform(workgroup) T`.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-26-minutes#workgroup-broadcast--issue-2586-">WGSL meeting minutes 2022-04-26</a></summary>



* JP: Essentially, the only way two invocations could get different values from a load from the same location, is from a data-race. So the only way it could be non-uniform is if it is a data race.
* MM
* JP: If E’m a shader compiler that’s presented with this case…
* JP: In either of the two cases, do users want workgroup broadcast? I worry that workgroup broadcast isn’t the right tool to tell the compiler that “I don’t have data races in my shader”.
* MM: So you’re imagining a program where an if statement has a non-uniform load. The programmer “knows in their brain” that the load is uniform, but needs to tell the compiler that “I know you can’t prove it, but trust me”, because otherwise it’s slower.
* JP: Yes but I think a user should prefer to load from a read-only storage.
* MM: Well there’s SIMD broadcast, and that’s useful even without uniformity analysis. I think that shows that this kind of broadcast would be useful even without UA. 
* KG: Is a “arbitrary value” concept a useful concept here?
* MM: After talking with the Metal team, `volatile` is the officially supported way to ensure that UV doesn’t cause UB for bounds checks. That is, when the index being bounds-checked is an undefined value, you can store it in a volatile variable, and then check the volatile variable in the bounds check. Making the array indexing operation conditional on that check ensures that the value produced is not undefined.
* JB: Is that written down?
* MM: No
* KG: Just in our minutes now. :)
* KG: It feels like WB is like volatile but for workgroups.
* MM: 
* JP: What I was proposing here is to say that loads from writable storage buffers are still uniform. …
* JP: In the spec, underlying APIs define things as UB. Where does WGSL talk about this?
* AB: We defer to Vulkan here.
* JP: I think what I’m hearing is that “practically, these are UV not UB”, and that maybe we can just spec that?
* AB: The UB comes from a complicated place. People think they can “ask for a value from memory”, but lots of things go on behind the scenes that make this much more complicated, and e.g. x != x. It’s because of assumptions the compiler has made, that cause these surprising things. 
* AB: If we get to the point where we want races to not be UB anymore, we might make a different decision on this topic.
* KG: Could we use volatile for that?
* MM: We’re sort of saying “data races gonna data race”, so long as we can be safe. Having every load be volatile would be maybe too expensive, but doing it for every array access would be doable. 
* KG: So you could get UB, but it’s “safe UB”. 
* …
* MM: Probably more than half of WGSL programs will have races somewhere, so it feels too pessimistic to say that these programs are all SOL, we we won’t try to help them.
* AB: Do you think it’s that many programs?
* MM: Yes
* …
* MM: So I’ve described safe bounds checks in Metal. How would you do it in spir-v?
* AB: I don’t know as our guarantee always happens in shader code. Might need hardware requirements.
* MM: Would you require RBAB for WGSL?
* AB: No, but we have other things we can maybe do.
* AB: Spir-v does have a volatile, but it’s not necessarily enough.
* MM: Is volatile required/core?
* AB: It’s core, you can always annotate with it.
* KG: But it might not give you what you need here?
* AB: Certain classes of issues go away with volatile (no rematerialization of loads) but it doesn’t make races go away


</details>

**Comment by litherum** [comment]
I made a point in the last call that I figure is probably worth reiterating here: Metal has `simd_broadcast()`, SPIR-V has `OpGroupBroadcast`, and HLSL has `WaveReadLaneAt()`/`WaveReadLaneFirst()`. Those functions exist outside of uniformity analysis, so there's some indication that this kind of broadcast functionality is useful by itself.

(They operate on SIMD-groups rather than workgroups, and will have different performance characteristics than a workgroup version, but I think the general point stands - there is an existence proof that that this kind of functionality is generally useful in the wild.)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-10-minutes#workgroup-broadcast--issue-2586-">WGSL meeting minutes 2022-05-10</a></summary>



* MM: Tried to comment to move forward. Even if we can’t agree function is necessary for uniformity, there are still reasons for it to exist. Reasons to exist were stated before. Mirrors similar but not exactly other functions.
* KG: Feels like consensus to have this thing just do we count it as uniform or not
* MM: What is "it"
* KG: Workgroup broadcast
* MM: Output?
* KG: Yea, broadcast read
* MM: Didn’t realize it was suggest the output would not be uniform
* AB: Should we just make refs to global vars uniform and not add this vs adding this function and leaving globals as non-uniform
* MM: Place we start having strong opinions. What does it mean analysis declared non-uniform can we rely on it or just htat if the program has no data races then it’s uniform? Hoping we can solve that issue
* KG: Would be valuable to me given MM point that underlying platforms have bultins for this to have this and it’s an easy thing to mark as uniform i think. The other thing we can either figure out another approach or leave as is. Can do it separately. Inclined to having workgroup broadcast
* MM: One path formward that might help, can we separate having workgroup broadcast vs reads of read-write buffers being uniform. If separate can get resolution on this issue and discuss harder later.
* AB: Suggested earlier due to just uniformity. Do you have use cases?
* MM: Don’t have use cases, just symmetry argument
* KG: Because underlying impls have it?
* MM: Don’t have it, have something similar
* AB: Better left to an extension where we have something more close ot underlying?
* MM: This woudlnt’ be part of subgroup extension as there are no subgroups in this. Don’t know if this should be in an extension or not
* DN: Do you mean workgroup or subtgroup broadcast?
* MM: All subgroup have to be in extension as not in v1. Proposal we split issue and try to get resolution on this issue. Discuss reads from rw buffers separately. 2nd issue has to be in v1, this doesn’t have to be v1.
* DN: Not convinced. Leaning against adding workgroup broadcast as it doesn’t exist in underlying platforms. Synthesizing out of parts and feels like we’re going a bit further then we should. I would want to consider this post-v1 in any case. Regardless of resolution of other bit. In part portability aspect, if synthensizing high likelihood different platforms have different performances and that’s not good for ecosystem.
* KG: Think splitting out issue from this and saying must finish other for v1. Think that’s accurate and happy to do that. Generally in favour of leaving workgroupBroadcast to post-v1. 
* MM: Sort of what i was going to mention. Community group will get uniformity analysis feedback and that may drive it.
* AB: I don’t know that solving uniformity question needs to be pre-v1 as we analyze the global variable as non-uniform and tighten it to uniform it later.  Doing so would only allow more programs, not invalidate existing working programs. 
* KG: If we say it’s uniform
* AB: If we say it’s non-uniform which is what spec says
* MM: So, latter if we change from non-uniform to uniform then you’re allowing a strictly larger set of programs.
* AB: Yes.
* MM: Sounds legit.
* KG: Does that mean don’t have to discuss other issue in v1? 
AB: Not a requirement. HOpefully uniformity feedback will inform if we need something extra. Need more feedback, don’t want to spend tonnes of time without more feedback
* KG: Sound good MM?
* MM: Sounds reasonable. Think this would be reasonable to have but ???
* KG: In marking uniform vs non-uniform satisfied as leaving not uniform?
* MM: Would have been my position, so satisfied with that.
* KG: Think we know enough to move forward.


</details>

**Comment by kdashg** [comment]
I believe post-v1 reflects consensus. We want feedback on whether the current behavior works in the real world, and we're about to start getting that feedback soon. But absent a course-correction based on feedback, this is a maybe-post-v1 idea.

**Comment by dragostis** [comment]
I also wonder if splitting this into two would make sense. Namely read-write storage and workgroup memory. It seems like uniformity of data in workgroup memory is easier to reason about since only one workgroup can write to it.

**Comment by kdashg** [comment]
I want to see if we can use this to help with uniformity analysis pain points in v1.

**Comment by alan-baker** [comment]
We discussed this internally again. We're currently leaning towards the function declaring its own workgroup memory. The main reason is similar to where we ended up with the pointer discussion. Generating HLSL or SPIR-V code would require similar transformations as more fully featured pointers. We could introduce the workgroup pointer variant when we require better pointers in the future.

So for now, we'd suggest:
```rust
// Broadcast |value| from |local_id| invocation to the rest of the workgroup.
fn workgroupBroadcast(value : T, local_id : vec3<u32>) -> T;

// Alternate possible version based on local_invocation_index instead.
fn workgroupBroadcast(value : T, invocation_index : u32) -> T;
```

**Comment by litherum** [comment]
local_id and invocation_index would have to be uniform, yes? Otherwise it would be a shuffle, rather than a broadcast, and I think a shuffle would require O(n) memory, rather than O(1). But maybe a shuffle is useful too?

If it’s a broadcast operation, why not always assume 0 for the local_id / invocation_index, and not have them configurable as an argument? I believe the main use case we’re trying to solve is where the author believes their data is already uniform, but needs a way to guarantee that to the compiler - in which case, the specific lane to broadcast isn’t necessary to be configurable.

And the call(s) would only be valid in uniform control flow, I assume?

Not stating an opinion, but just wanting to be explicit: if the workgroup memory is internal to the function, then 2 functions can’t share the same workgroup memory. (And even if the backend compiler does cause them to share memory, we can’t rely on that in the WGSL-level accounting of workgroup memory.) Maybe that’s okay, maybe it’s not.

**Comment by alan-baker** [comment]
I think we could require the id to be a const-expression. Maybe a broadcast first type of functionality is useful enough, but it seemed reasonable to have some flexibility.

Yes, these would be collective operations so uniform control flow only. I would even add to the synchronization built-in function section of the spec (alongside barriers).

Right with this proposal there would be no sharing of memory; however I think that means the polyfill could get away with a single barrier (since the other parameter is not a pointer).

```rust
// Potential polyfill
var<workgroup> shared_mem : T;
fn workgroupBroadcast(value : T, local_id : vec3<u32>) -> T {
  if local_id == local_invocation_id {
    shared_mem = value;
  }
  workgroupBarrier();
  return shared_mem;
}
```

**Comment by alan-baker** [comment]
Actually, now that I think about it, if the polyfill was inlined instead a separate function then we could avoid the pointer issues and separate the workgroup storage. It would require two barriers for safety though.

**Comment by alan-baker** [comment]
Chatting more with @jrprice perhaps two variants are in order:
```
// broadcasts the value in p to all members of the workgroup.
fn workgroupBroadcast(p : ptr<workgroup, T>) -> T;

// Declares the shared memory for the programmer.
fn workgroupBroadcast(value : T, local_id : vec3<u32>) -> T;
```

The first version is a better fit case provided by @raphlinus. The second version could hardcode 0 as suggested by @litherum, but is a more generic tool for ease of use. There might be a slight concern of having both versions take 1 parameter since missing a `&` would end up as the second case inefficiently.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-11-08-minutes#workgroup-broadcast--issue-2586-">WGSL 2022-11-08 Minutes</a></summary>

* AB: How about #2586: There could be two useful variants of this function: One would help Raph out with his barriers in his compute shader; and one that would be a general easy-to-handle tool for people that need to make something uniform, where the compiler would allocate the workgroup memory for you. There are reasonable arguments for both variants.
* KG: Is either of these a “more primitive” operation that you could implement the other in terms of?
* AB: Yes, the first one is more primitive
* KG: If we can provide a primitive that satisfies the concern, then we should provide something low-level that people can use themselves
* AB: They have different tradeoffs in flexibility. The second one doesn’t need two barriers; the first does. But, if you already have to store to workgroup memory anyway, then maybe the first one is all you need
* KG: Just give them different names?
* AB: Maybe, but could be confusing
* KG: The first one feels less like a broadcast and more like a read, whereas the second one seems more like a broadcast
* AB: I’m not too particular about the naming
* KG: I could write that up as a proposal
* AB: Just the one version, or rename and have both versions?
* KG: Have both versions
* **Decision: continue to discuss offline**

</details>

**Comment by kdashg** [comment]
Specifically, something like:
```
// broadcasts the value in p to all members of the workgroup.
fn workgroupUniformRead(p : ptr<workgroup, T>) -> T;

// Declares the shared memory for the programmer.
fn workgroupBroadcast(value : T, local_id : vec3<u32>) -> T;
```

**Comment by raphlinus** [comment]
I'm in favor of this proposal. My personal feeling regarding shuffle is that it's useful but doesn't needed to be provided as a built-in or intrinsic, it should be possible for the shader author to express the exact shuffle semantics in terms of what's already there. I like the explicitness of passing in a workgroup pointer, as that doesn't put any additional burden on computing resource requirements.

Thanks!

**Comment by dneto0** [comment]
In trying to land `workgroupUniformLoad` I noticed some problems,  see https://github.com/gpuweb/gpuweb/pull/3586#discussion_r1025592103   and copying here:


Given the polyfills anticipated and expected in the discussion above, the description of workgroupUniformLoad needs to say the return value is uniform if p is uniform.

That is the uniformity analysis graph should have an arc from return value of the function to the p arg's node.

To do any better requires broadcasting someone's p to the other invocations, which is not done by the polyfills.

To make this concrete:

```
override size=16;
var<workgroup> a:array<i32,size>;

@compute @workgroup_size(size)
fn main(@builtin(local_invocation_index) i:u32) {
   a[i] = i;
   let yolo = workgroupUniformLoad( &a[i] );
   // yolo is what?
}
```
Discussing with @jrprice, currently uniformity analysis judges a reference to a module-scope variable to always be "MayBeNonUniform" value.  So with that the formulation of "return value is unform when p is uniform" would be vacuous.   So this needs more work and likely uniformity analysis needs more work.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-11-15-minutes#workgroup-broadcast--issue-2586-">WGSL 2022-11-15 Minutes</a></summary>

* PR: [Add workgroup broadcast and uniform load built-ins #3586](https://github.com/gpuweb/gpuweb/pull/3586) 
* DN: Google think workgroupUniformLoad is the nicer solution. No magic about allocating behind the scenes that you would get with workgroupBroadcast.  
* JB: Think it’s fine, Alan is the most pessimistic about implementation, and Raph is most demanding of features, so if they both like it, that’s good
* KG: What caused us to drop the ability to load from other address spaces? Why is it only workgroup now?
* DN: If you have multiple workgroups in flight, you can’t guarantee that they won’t race on other address spaces. Metal doesn’t have any way to prevent that. Restricting it to workgroup ensures that that won’t happen. Synchronization picture is much clearer.
* KG: Main concern was that this solves the issue for compute shaders with workgroup memory, but not other use cases that need the storage address class. But apparently it’s harder to get guarantees about that from the underlying implementation.
* JP: If you really need other address classes, you could pass it through workgroup memory
* KG: But I’m interested in fragment shaders.
* DN: You should use atomics for this. You’re trying to communicate something globally across all the invocations in a shader. The mechanism for that is to use an atomic in a storage buffer. Oh, but you’re saying it’s still not uniform.
* KG: The analogy between workgroup uniformity and quad uniformity.
* DN: If you want to communicate across a quad, you can use two derivatives. But there’s a chicken-and-egg problem, because you know it’s not uniform, but the compiler can’t tell
* KG: Right, the purpose here is something the compiler does know is uniform.
* KG: I like workgroupUniformLoad
* KG: It seems like Google’s feelings have evolved, so the PR needs to be updated?
* DN: Yes, and I’ll make sure to amend the uniformity rules
* KG: It should also be explicit that workgroupUniformLoad requires uniform control flow, like barriers do
* DN: This will need to be added to the collective operations list. The uniformity chapter lists the things that require uniformity

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-11-22-minutes#workgroup-broadcast--issue-2586-">WGSL 2022-11-22 Minutes</a></summary>

* PR: [Add workgroup broadcast and uniform load built-ins #3586](https://github.com/gpuweb/gpuweb/pull/3586) 
* DN: Had consensus last week, but we didn’t really clarify everything, found something that we didn’t handle. E.g. workgroundUniformLoad, where each WG provides a different pointer. So really the condition we want is to separate the address and the contents at that address. DN+AB iterated and we’re looking to keep something as straightforward as we can. One option is to abandon workgroupUniformLoad and go back to workgroupUniformBroadcast.
    * FYI: The confounding example is from [https://github.com/gpuweb/gpuweb/pull/3586#discussion_r1025511559](https://github.com/gpuweb/gpuweb/pull/3586#discussion_r1025511559) 
        * `override size=16;`
        * `var&lt;workgroup> a:array&lt;i32,size>;`
        * 
        * `@compute @workgroup_size(size)`
        * `fn main(@builtin(local_invocation_index) i:u32) {`
        * `   a[i] = i;`
        * `   let yolo = workgroupUniformLoad( &a[i] ); // the problem is i `
        * `   // yolo is what?`
        * `}`
        * 
* AB: So we think the way broadcast is done *will* work, but not an ideal solution for everyone. For uniformLoad though, it’s really the base address that matters. We don’;t have a way to let you have different base pointers per invocation. All of your address math would have to be formed out of an override expression, or anything that Counts-As. But wanting to do this fully, we’d need to do full-program analysis, sounds ugly. Wouldn’t be able to verify as you see the call. It could put an odd restriction on a function, maybe couldn’t use it on a pointer param, would have to use it on a global var. If you want something like uniformLoad, you need either full prog analysis, or something restrictive. Either way, you need some way to restrict to overload expression. If none of those are good, the Broadcast is the other option.
* JB: Is this instead of #3602? Or in addition to?
* DN: Instead of #3602. You want to make the address uniform. We’re going to restrict by construction, because the indexing math is Override, and so its’ uniform by construction. I pasted the motivating example above. The `i` is wildly non-uniform. The rule AB is saying, si the `i` is not allowed because it’s not an override expr.
* JB: So you’re seized upon overload expression having the right restrictions without introducing new language.
* AB: And without new analysis to data-flow-analysis.
* JP: What I’m missing is why we need to restrict to override, and we can’t use data-flow analysis, why not uniformity to figure it out?
* DN: That should get you what you want, but how do we say that… *thinking* Now you have a validation rule on wgUniformLoad, have to find indices that feed it, need the cone of deps, and require a uniform edge coming out of it. You analyzed the program, have to add edges after the fact.
* AB: First time we have a requirement that the value is uniform, in the graph. We have incidental usage, but anywhere you check rightnow must be called from UCF. That may not matter to you, but it’s a differfnt thing that’s cvhecked by uniform analysis.
* JB: The way I expect this to work, is eval of `a[i]` yields a reference, and uniformity of the ref would talka bout the address itself, would say not a uniform reference. Uniformity would not look into the value stored in the loc until you do the load. Can tell what the uniformity needs to be based on the storage space of the reference. Don’t need to track anything more than we already do?
* DN: That’s way I was headed, but current UA doesn’t distinguish them right now.
* JB: Doesn’t that mean UA doesn’t understand refs?
* DN: It has collapsed the two. An `a[i]` is both the address part and the value part. So every expr effectively has two nodes in it. 
* JB: That’s the #3602 approach?
* DN: Yes.
* JB: I read it, don’t understand why you need pairs. It feels like this should fall out naturally. When you apply a load rule, a uniform pointer might become a non-uni value at that time.
* DN: Could be.
* AB: You may not need to carry it in every node, but you do hav to track the value.
* JB: Don’t we just know that anything in such Storages yields a non-uni value?
* AB: Possible, as DN says, it’s a different cut-line with different sharp-edges. You could say “why didn’t you use a uniform” but I think it becomes more annoying to discuss and spec. If you want to make all read-write loads non-uni, you couldn’t chain uniform loads.
* JB: Well, isn’t that correct though? Isn’t that the restriction that we want?
* DN: It’s a restriction that we want to eliminate. But we also want to eliminate more cases.
* AB: COmes to “how many cases do you want to cover with this”, and how much work would it be to get more *useful* usecases working.
* JB: I thought this would be simpler.
* DN: Pair values *would* work, but making it so we only track single values *should* work. We already have to fixup rval/lval stuff, so maybe we should fix it at the same time?
* JB: I feel like we did the work do spec how references work, and that we should maybe try to go all-in. Sorry to ask for more time, but can I have another week? (yes)
* JP: We already have a special case for array-length, so if we were to solve this, we could get rid of that special case too.
* DN: Is JP volunteering? :)
* JP: I would be interesting in prototyping…something

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-11-29-minutes#workgroup-broadcast--issue-2586-">WGSL 2022-11-29 Minutes</a></summary>

* PR: [Add workgroup broadcast and uniform load built-ins #3586](https://github.com/gpuweb/gpuweb/pull/3586) 
* Alan: reworked the PR to remove workgroupBroadcast and update uniformity analysis to maintain uniformity of memory views. workgroupUniformLoad parameter is required to be uniform. Credit to Jim Blandy.

</details>
