### ISSUE TITLE
GPURenderBundleEncoderDescriptor needs maxCommandCount if it is to be implementable on MTLIndirectCommandBuffer

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2612]
In order to create a `MTLIndirectCommandBuffer`, authors need to specify how many commands it can hold: https://developer.apple.com/documentation/metal/mtldevice/2967420-newindirectcommandbufferwithdesc?language=objc

I believe we originally designed the expressivity of `GPURenderBundleEncoder` to be implementable on `MTLIndirectCommandBuffer`, so this omission is probably an oversight.

**Comment by kainino0x** [comment]
Defining this will be a bit tricky. Some WebGPU commands can result in multiple Metal commands (like validation for indirect commands).

In absence of this you can still use MTLIndirectCommandBuffer though, you just have to do all the recording on finish(). So while I agree it's an oversight, it would still be valid to go either way on the resolution.

I assume it's inefficient if the implementation fills `maxCommandCount` with some very large number?

**Comment by austinEng** [comment]
The implementation could also back the GPURenderBundleEncoder using multiple MTLIndirectCommandBuffers each sized to maybe ~100 or ~1000 commands. On finish(), the implementation can then consolidate them into a single MTLIndirectCommandBuffer if that's desirable using [`[MTLBlitEncoder copyIndirectCommandBuffer]`](https://developer.apple.com/documentation/metal/mtlblitcommandencoder/2967412-copyindirectcommandbuffer?language=objc).

This approach allows the implementation to easily insert additional commands for validation, keeps flexibility such that the developer does not need to know exactly how much work they're going to encode, while maintaining reusability of the commands. Worst case is that the first time a `GPURenderBundle` is used, the implementation needs to perform `[MTLRenderCommandEncoder executeCommandsInBuffer]` N / 1000 times. Once the implementation has time to consolidate into a single MTLIndirectCommandBuffer, there will only be a single call to `executeCommandsInBuffer`.

**Comment by litherum** [comment]
> Defining this will be a bit tricky. Some WebGPU commands can result in multiple Metal commands (like validation for indirect commands).

I suppose we should pessimize.

> In absence of this you can still use MTLIndirectCommandBuffer though, you just have to do all the recording on finish(). So while I agree it's an oversight, it would still be valid to go either way on the resolution.

Doing all recording on `finish()` hasn't been a requirement before, and I don't think we should add it as a requirement now. Our experience indicates that being able to stream commands as we receive them is important for performance.

> I assume it's inefficient if the implementation fills `maxCommandCount` with some very large number?

Yes.

> The implementation could also back the GPURenderBundleEncoder using multiple MTLIndirectCommandBuffers each sized to maybe ~100 or ~1000 commands.

Why couldn't the application do this themselves?

**Comment by austinEng** [comment]
> Why couldn't the application do this themselves?

They could. It would be unfortunate for the application to do this themselves for a few reasons:
 - Unlike the implementation, the application is unable to consolidate multiple GPURenderBundles into a single one. This is possible to do with MTLIndirectCommandBuffer because you can copy all of the commands from separate indirect command buffers into a single one. We'd be leaving applications with worse performance when the whole point of GPURenderBundle is to improve execution performance of repeated pieces of work.
 We should not expose the copying behavior since to my knowledge, it's not available for Vulkan secondary command buffers and D3D12 bundles.
 - Encoding the number of Metal commands a particular command requires into the spec ties implementations to implementing things in a very specific way. We'd have to come to consensus on the very specific commands that are used to implement things like the draw indirect validation. This type of inflexibility is unfortunate. Even if all implementations decreased the number of commands required, the application would still need to pretend operations take some pessimized, inflated number of commands. That means wasted, unused space in the MTLIndirectCommandBuffer.
 In the long term, the spec may end up with a somewhat arbitrary table of command counts for each operation.
 - Generally, I don't think anyone wants to iterate their scene graph and also keep a counter of how many commands they've encoded. It's annoying to do, and the implementation can paper over it easily and with better performance in native code.
 -  In order to validate, the implementation needs to perform the counting. So, both the application and the implementation will need to be counting. We can remove the overhead of application-side counting if we take the final small step to push the MTLIndirectCommandBuffer into a list of them, and start a new one.

**Comment by litherum** [comment]
> Encoding the number of Metal commands a particular command requires into the spec

This wouldn't be how it would work. It would represent the number of WebGPU commands, and then an implementation would pessimize to create the value passed into Metal.

> Generally, I don't think anyone wants to iterate their scene graph and also keep a counter

The requirement for WebGPU, if it added such a `maxCommandCount` field, would be identical to the requirements for Metal applications using `MTLIndirectCommandBuffer`.

But, even beyond that, iterating the scene graph twice doesn't need to happen in many situations. If an engine is using ICBs to render items, they'll often already have a maximum number of items they could handle - this will be reflected in the size of the buffers they're binding to contain pose information, for example. Another example: In particle systems, it's pretty common to allocate a buffer of a certain size, and keep track of how many particles are alive within that buffer, without reallocating the buffer. The size of the buffer indicates the maximum number of particles which can be alive, just as the size of the ICB would indicate the maximum number of items to be drawn.

**Comment by austinEng** [comment]
Ah, thank you for the clarification about how command counts might be specified. That makes the situation better, but I think the other points still stand.
The implementation can do a better job of this than the application with relatively little effort. So if we can improve the developer experience and also have better performance, that seems like the better option.
While it may be true iterating a scene graph doesn't have to happen in all cases, it is not evidence that there do not exist applications that would benefit from being able to record into a render bundle in a single pass.

**Comment by Kangz** [comment]
Closing, as discussed in the meeting.
