### ISSUE TITLE
Add rg11b10ufloat as valid render attachment format

### ISSUE THREAD

**Issue by pplux** [gpuweb/gpuweb#2648]
In the specification the format rg11b10ufloat is marked as not valid for render_attachment:

https://gpuweb.github.io/gpuweb/#plain-color-formats

We at Sketchfab/Epic have been using this format on WebGL2 as a render target for quite a long time, and have found it is very good for carrying HDR data through the postprocess/render pipeline. It is very convenient format to reduce gpu bandwidth with a very decent range. 

Looking at vulkan (https://vulkan.gpuinfo.org/listoptimaltilingformats.php) and metal (https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) it is a very well supported format for writing into. It is also a required color-renderable format for OpenglES 3.2.

We were wondering if this could be added to V1, or at least as an extension.

**Comment by kainino0x** [comment]
It's not required by the Vulkan spec, and I don't think we previously investigated the actual ecosystem. Metal and D3D12 do appear to fully support it, so that leaves just Vulkan. Checking with https://github.com/kainino0x/gpuinfo-vulkan-query
If I'm querying correctly, I find that it's not supported on Adreno 500 series GPUs, and a lot of Adreno 600 series devices:

```
Requirement "rg11b10ufloat renderable" loses 9 (and partially loses 3) further deviceNames:
  In ALL reports (9 deviceNames):
    x Adreno (TM) 504: 6 (8629 9137 10642 11160 11664 12378)
    x Adreno (TM) 505: 23 (4259 4457 4489 4824 6129 7394 7550 8516 8922 9025 9063 9355 9501 9798 10174 10776 11057 11789 12203 12269 12277 12342 13211)
    x Adreno (TM) 506: 47 (3851 4541 4680 4724 4916 4956 5006 5250 5990 6044 6058 6151 6814 7023 7137 7612 8841 9054 9060 9935 10294 10314 10414 10431 10513 10542 10810 10941 10997 11017 11346 11423 11493 11526 11656 12201 12360 12454 12578 12618 12636 12785 12953 13423 13426 13508 13618)
    x Adreno (TM) 508: 8 (4452 6680 8652 10383 10442 10589 12379 13414)
    x Adreno (TM) 509: 13 (4924 6120 8358 9062 9064 11486 11487 11488 11673 11820 12108 12678 13230)
    x Adreno (TM) 510: 1 (6786)
    x Adreno (TM) 512: 34 (3724 4394 4400 4683 4768 5679 6063 6787 7385 8566 8697 10195 10204 10546 10608 10638 10656 10700 10775 11177 11237 11326 11399 11452 11475 11605 11663 11933 12813 13364 13421 13578 13616 13837)
    x Adreno (TM) 530: 43 (3183 3597 3603 3765 3907 4359 4363 4773 4999 5019 5103 5210 5314 5399 5402 6072 6100 6215 6285 6560 6841 6885 7313 7542 7601 8268 8483 8544 9061 9332 10486 10681 10827 10838 10958 11034 11724 11874 12263 13278 13802 13934 13964)
    x Adreno (TM) 540: 56 (3422 3450 3532 3571 4071 4145 4433 4503 5102 5150 5215 5259 5383 5632 5811 5866 6046 6068 6083 6163 6208 6405 6796 7584 8603 8977 9008 9251 9354 9705 10284 10347 10597 10728 10752 10784 10786 10819 10844 10908 11101 11225 11338 11350 11485 11498 11665 11669 12292 12489 13097 13246 13294 13482 13577 13751)
  In SOME reports (3 deviceNames):
    ~ Adreno (TM) 615: 3 of 15 (5944 6088 7898; ok: 6436 7927 8903 9147 9184 9422 10427 11275 12085 12583 12996 13171)
    ~ Adreno (TM) 616: 5 of 12 (4986 5287 6492 9756 11712; ok: 7806 10393 10604 11072 12858 13327 13564)
    ~ Adreno (TM) 630: 48 of 101 (2801 3024 3138 3305 3442 3665 3687 3754 3755 3795 3810 3927 4134 4140 4249 4270 4366 4403 4413 4486 4525 4563 4599 4628 4632 4915 4926 5175 5253 5800 6032 6038 6056 6107 6162 6234 6266 6704 6996 7057 8585 8951 10285 11026 12775 13424 13749 13963; ok: 5886 6434 6788 6987 7108 7374 7949 8473 8577 8907 9097 9267 9471 10287 10291 10300 10302 10303 10351 10371 10424 10460 10551 10672 10678 10730 10770 10813 10966 11016 11035 11120 11464 11602 11670 11695 11914 11922 12213 12280 12363 12429 12430 12667 13256 13428 13552 13642 13675 13676 13752 13991 14092)
```

**Comment by pplux** [comment]
Thanks! that's thorough! since the support was not 100% we already knew we will had to deal with some devices not supporting that format (talking about webgl2) and maybe have a fallback as rgb16f. 

But it will be really great given it's widely supported to have that possibility at least as an extension. Will it be possible to have formats conditionally? is it possible to query that info to webgpu?

**Comment by Kuranes** [comment]
To add to the topic, for perf oriented code, even on "latest mobile GPU" (with framebuffer compression and all), it's still the best format for rendering: 
https://community.arm.com/arm-community-blogs/b/graphics-gaming-and-vr-blog/posts/mali-g710-developer-overview#mcetoc_1fta9hbo9b

**Comment by litherum** [comment]
https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf says:

<img width="1245" alt="Screen Shot 2022-03-09 at 11 31 15 AM" src="https://user-images.githubusercontent.com/918903/157517461-1cc8dc6d-3885-4e4a-a72c-5d1d18f72d47.png"><img width="1246" alt="Screen Shot 2022-03-09 at 11 31 05 AM" src="https://user-images.githubusercontent.com/918903/157517479-4233f022-1f85-4699-ba00-f3f7587046eb.png">

**Comment by kainino0x** [comment]
I believe the capability in question here is the "Color" in that table, so it should be supported universally.

**Comment by kainino0x** [comment]
> But it will be really great given it's widely supported to have that possibility at least as an extension. Will it be possible to have formats conditionally? is it possible to query that info to webgpu?

forgot to answer this. Yes, if we don't add it in core, we'd add it as [feature flag](https://gpuweb.github.io/gpuweb/#features) like "rg11b10ufloat-renderable" which would become detectable on the GPUAdapter and you can then request it in requestDevice. Enabling it would lift the validation and allow you to use it.

**Comment by pplux** [comment]
If I'm not mistaken in Metal's table the first two Apple GPU's do not support writing into that format, they are missing the label "write", but everything since Version 3 (Cortex A9 -> iPhone 6.0 2015) supports it.  So yes, it is true there is no 100% support on older devices, but nowadays is a very well supported format.

I can't say how safe webGPU should play regarding older devices, but if it can be queried through a feature flag for us it is more than enough :)

**Comment by kainino0x** [comment]
The "Write" capability says "the texture can be written to by a function"
which I'm pretty certain is equivalent to write-only storage textures in WebGPU. Not necessary for render attachments.

The "Color" capability is "the texture can be used as a color render target".

**Comment by pplux** [comment]
Even better, thanks for the clarification :)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-03-09#add-rg11b10ufloat-as-valid-render-attachment-format--issue-2648-">WebGPU meeting minutes 2022-03-09</a></summary>



* KN: Basically Adreno 500.
* KG: Polyfill/emulate it in core. Maybe add this to core after 1.0.
* MM: Emulate the reduced precision?
* KG: Probably not
* KN: I’d probably actually have an rg11b10 texture underneath, copy into it from a temporary render target.
* RC: Think in the past we’ve gotten in trouble trying to emulate formats, especially expanding compressed textures.
* MM: Maybe we shouldn’t polyfill it if users would want to know it’s polyfilled.
* MS: This would be memory magically created behind the scenes that we don’t know about, on already memory-constrained devices.
* KG: Think it’s worth including because such a large majority would benefit from it. Think the subset is getting small enough that it’s worth the tradeoff. Since it’s so widely beneficial, would like to put it in core, and polyfill it to increase the reach.
* MM: If I’m a developer, under what situation would I use this format? Sure nice if my data fits into it, but when would I actually prefer it? I think it’s only when you’re memory constrained, otherwise can use a larger format. So think this is a point in favor of KG’s proposal.
* KG/KN/MM discussion: Adds implementation cost for 1.0 release on these devices, but can release on those devices later, probably fine.
    * (KN: As long as we’re sure we can emulate it)
* **KG to write PR**
    * (posted: [https://github.com/gpuweb/gpuweb/pull/2659](https://github.com/gpuweb/gpuweb/pull/2659) )


</details>

**Comment by Kangz** [comment]
This was already brought up in the meeting, but I'm a bit worried about the implementation cost of polyfilling this on Adreno 500. Can we put it in a feature level instead?
