### ISSUE TITLE
What do the GPUBufferUsageFlags constants mean?

### ISSUE THREAD

**Issue by joeedh** [gpuweb/gpuweb#2663]
The GPUBufferUsageFlags bitflags are not explained very well (or at all in some cases).

What does COPY_SRC/COPY_DST mean?  How are the INDEX/VERTEX/UNIFORM bitflags supposed to be used? There is one example of making a writable uniform buffer that uses UNIFORM | COPY_DST.  But isn't COPY_DST for reading from buffers, not writing to them?  This is example 11 at [5.2.2](https://www.w3.org/TR/webgpu/#buffer-usage).

I don't understand. 

Thanks.

**Comment by kainino0x** [comment]
They are indeed not yet documented in the spec (they will be), though they're fairly self-descriptive \*if\* you know the magic sentence to slot them into:
- the buffer can be "used" as a "copy source" (source of a copy operation)
- the buffer can be "used" as an "index" buffer
- the buffer can be "used" as a "uniform" buffer
- the buffer can be "used" in a "mapAsync" operation with mode "write"
- etc.

However, you can find out what they do by searching the text of the spec, as _most_ (not all) of the relevant validation text is there, e.g.:
- copyBufferToBuffer requires its source to have COPY_SRC and its destination to have COPY_DST
- setIndexBuffer requires its buffer to have INDEX
- createBindGroup requires buffers used as "uniform" binding type to have UNIFORM
- etc.

In the specific example of `UNIFORM | COPY_DST`, `UNIFORM` allows the buffer to be used as a uniform buffer (bound to a shader, in a dispatch or draw call), and `COPY_DST` allows the data in the buffer to be initialized via a copy, usually copyBufferToBuffer (otherwise it's just zeroed out).

---

I'll leave this issue open as a task to go and write definitions for the buffer (and texture) usages.

**Comment by kainino0x** [comment]
@toji assigning this one to you since you're already looking at writing definitions for API surface.
I think you can roughly adopt the language above ("buffer can be used as ...") since it maps nicely to a mental model of usages.
