### ISSUE TITLE
Proposal: Support DP4a as WGSL built-in functions

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#2677]
# Motivation

Nowadays **Int8 quantization** has become a popular approach to optimize the computation and memory bandwidth of real-time deep learning inferences on client devices on the basis of the `float32` or `float16` models. And the term “**DP4a**” (8-bit integer Dot-Product of 4 Elements and Accumulate) refers to a set of GPU instructions that are widely used to accelerate the computation of such int8-quantized models.

DP4a instructions take 2 `uint32` values and 1 `int32` value, or 3 `uint32` values as inputs, and return one `uint32` or `int32` value. The first 2 `uint32` values are logically packed 4-element 8-bit signed/unsigned integer vectors, and the instruction first computes the dot product of these two vectors, and then returns the sum of the dot product and the third input value. 

For example,
```javascript
var a = 0x01020304u;
var b = 0x02040608u;
var c = 1u;
var output = dot4AddU8Packed(a, b, c); // output == 61u;
```

Because executing a DP4a instruction is very fast on the GPUs with DP4a supported in their ISAs (Instruction Set Architecture), they have already been widely used in the industry to accelerate the computation with popular AI frameworks (e.g. [Intel](https://community.intel.com/t5/Blogs/Tech-Innovation/Artificial-Intelligence-AI/Accelerate-Deep-Learning-Performance-with-Intel-Xe-Graphics-and/post/1335669), [Nvidia](https://developer.nvidia.com/blog/mixed-precision-programming-cuda-8/)).

It should be easy to support DP4a in WGSL as we just need to add two more WGSL built-in functions, whose inputs and outputs are all 32-bit signed or unsigned integers. 

# Requirements to be Standardized in the WebGPU CG / WG

DP4a meets all [the requirements to be standardized in the WebGPU CG / WG](https://github.com/gpuweb/gpuweb/blob/main/process/RequirementsForAdditionalFunctionality.md).

## A proposal for new functionality must be implementable on at least 2 different browser engines.

It is straightforward to implement DP4a in all WGSL compilers. Even on the native APIs without directly support of DP4a, we can easily polyfill DP4a (e.g. [DP4a is polyfilled in Mesa](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/compiler/nir/nir_opcodes.py#L1367) on the platforms without hardware accelerated DP4a instructions)

## A proposal for new functionality must be implementable on at least 2 different native APIs.
It is straightforward to implement DP4a in HLSL, Metal Shading Language and SPIR-V with the method used in Mesa.

The DP4a intrinsics are supported in D3D12 and Vulkan.
- D3D12 [shader model 6.4](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-4-features-for-direct3d-12) supports DP4a (DXIL: `Dot4AddI8Packed` and `Dot4AddU8Packed`).
- Vulkan 1.3 core or [VK_KHR_shader_integer_dot_product](https://github.com/KhronosGroup/Vulkan-Docs/blob/main/proposals/VK_KHR_shader_integer_dot_product.asciidoc) with SPIR-V extension [SPV_KHR_integer_dot_product](https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_integer_dot_product.html)

Note that we will meet two issues when we directly implement DP4a with the native DP4a intrinsics.
1. **Query if DP4ais hardware accelerated**

    In Vulkan we can query if DP4a is hardware accelerated (with [`VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR`](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR.html)), while on D3D12 we can't query such information (according to [the Microsoft document](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-4-features-for-direct3d-12), "**consequently, no separate capability bit check is required, beyond assuring the use of Shader Model 6.4**”)

2. **Behaviors when there is overflow or underflow in the final addition**

    The behaviors of the overflow or underflow in the final addition of DP4a instructions are different on D3D12 and Vulkan.
    - When we don't do the accumulation the result won't be overflow or underflow. We can see the introductions of the operation `OpUDotKHR` and `OpSDotKHR` for more details.
    - In `SPV_KHR_integer_dot_product`, the final add in the operation `OpSDotAccSatKHR` and `OpUDotAccSatKHR` are **saturated**. According to the SPEC of SPIR-V, `SaturatedConversion` indicates that a conversion to an integer type which is outside the representable range of Result Type is **clamped to the nearest representable value of Result Type**. [In Mesa the result is always clamped to the range of `INT` or `UINT`.](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/compiler/nir/nir_opcodes.py#L1417)
    - On D3D12 there is no description about the behavior of potential overflow or underflow on the final accumulation. For example, on Nvidia 2080Ti (Windows version 10.0.19044.1586, 30.0.15.1179) and Intel UHD Graphics 770 (Windows version 10.0.22000.556, 30.0.101.1273), the result of DP4a is overflowed.

```HLSL
RWByteAddressBuffer dst : register(u0);
[numthreads(1, 1, 1)]
void main()
{
    uint a = 0x02;
    uint b = 0x02;
    uint c = 0xFFFFFFFF;
    uint output = dot4add_u8packed(a, b, c);
    dst.Store(0, output);  // output == 3u
}
```

## A proposal for new functionality must be implementable on devices created (designed? manufactured?) by at least 2 different device vendors.

The non-hardware-accelerated DP4a built-in functions can be implemented on all Vulkan, D3D12 and Metal platforms.

Below GPUs support DP4a in their ISAs.
- [Intel Gen12+ GPUs](https://community.intel.com/t5/Blogs/Tech-Innovation/Artificial-Intelligence-AI/Accelerate-Deep-Learning-Performance-with-Intel-Xe-Graphics-and/post/1335669)
- [Nvidia GPUs in Pascal architecture and later](https://developer.nvidia.com/blog/mixed-precision-programming-cuda-8/)
- AMD GPUs in ["Vega" 7nm Instruction Set Architecture](https://developer.amd.com/wp-content/resources/Vega_7nm_Shader_ISA.pdf) (`V_DOT4_I32_I8` and `V_DOT4_U32_U8`)
- [ARM Valhall](https://people.collabora.com/~alyssa/Valhall-Documentation.pdf) (`IDP.v4s8`, `IDP.v4u8`)

# Proposal

Our proposal is supporting DP4a **without accumulation** as **new WGSL built-in functions in an extension**:

```javascript
dot4U8Packed(e1: u32, e2: u32) -> u32    // OpUDot with 32-bit unsigned integers as inputs
dot4I8Packed(e1: u32, e2: u32) -> i32    // OpSDot with 32-bit unsigned integers as inputs
```

- **Why “without accumulation”**
The behaviors of DP4a with accumulation on the overflow or underflow of last addition are different on Vulkan and D3D12. Note that:
    - Intel GPUs support both saturated and non-saturated version of DP4a instructions, and it is easy for the compilers to optimize `(OpSDot + OpFAdd)` into one non-saturated version of DP4a instruction in the Vulkan driver.
    - While it is also useful to support the saturated version of DP4a (`OpSDotAccSatKHR` and `OpUDotAccSatKHR`) for AI applications, on D3D12 we have to implement it with below piece of code, which is much more difficult to optimize it inside the driver.
```HLSL
int int32add_saturated(int a, int b){    
    int sum = a + b;
    if (a < 0 && b < 0 && a < sum)
        sum = INT_MIN;
     } else if (a >= 0 && b >= 0 && sum < a)
        sum = INT_MAX;
     }
     return sum;
}

int dot4I8PackedAccumulationSaturated(uint a, uint b, int acc)
{
    return int32add_saturated(dot4add_i8packed(a, b, 0), acc);
}
```

- **Why “as new WGSL built-in functions in an extension”**
We’d like to support DP4a to accelerate the computation of machine learning, while the emulated version of DP4a won’t get such performance gain. On such platforms we can choose not to support DP4a to imply `float32` models may be a better choice.
  - On Vulkan we can rely on the query on `VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR`.
  - On D3D12 we can make the decision with the Windows version and device id.

**Comment by Kangz** [comment]
Thanks for making this proposal. DP4A seems like a small bit very useful extension. However we're trying to ship a v1, so to avoid distracting the group, I suggest we take a look at this post-V1.

**Comment by litherum** [comment]
This seems reasonable to add. It might not even need an extension!

A few thoughts:

1. In existing applications which use DP4a, do they have different codepaths for devices which don't support the hardware instruction - specifically due to this specific hardware instruction? If the answer is "no," then WGSL could just a simple function to the standard library, and if its hardware-accelerated then great, and if it's not then that's fine too. On the other hand, if the answer is "yes" then it might need to be in an extension to authors will know whether or not they should use a different codepath or not.
2. How confident are you that the "without accumulation" version will be generally useful? How much performance would we be giving up by not including the accumulation in the operation?
3. We may want to wait until we have shorter-than-32-bit integral types, so we can represent these operands as `vector<u8, 4>` instead of u32.

**Comment by mehmetoguzderin** [comment]
Just a little text on not requiring extension and poly-filling: during the WebGPU & WGSL spec discussion process, the topic of particular poly-fillable instructions that indispensably boost performance yet do not appear in all target devices came up already a few times. I think, eventually, a streamlined way to explain maintaining developer trust while making instruction universals where it has a performance implication could be a positive step for the ecosystem and eliminate a massive vector of preprocessor necessity or shader permutation.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#dp4a">GPU Web F2F 2023-02-16/17</a></summary>

* Issue: [Proposal: Support DP4a as WGSL built-in functions · Issue #2677](https://github.com/gpuweb/gpuweb/issues/2677)
* PR: [WGSL: Add dot4U8Packed and dot4I8Packed as new built-in functions by Jiawei-Shao · Pull Request #2738](https://github.com/gpuweb/gpuweb/pull/2738) 
* JS: though this is post-V1, we want to propose it again. Useful for executing int8 ML models on the web. Can run much more quickly.
* JS: thanks David for reviewing my patch. Couple new primitives that map to SPIRV, HLSL. Can't expose the saturating primitives because not supported in HLSL.
* AB: Questions. The way the SPIR-V extension in Vulkan is you have to expose all the functionality and add a flag to say whether it’s actually in the HW.  In WebGPU, should these be polyfilled in software?
* AB: In SPIR-V, the dot products can take any vector supported in SPIR-V. When we add types like i16, then do we want to expand these builtins to that type.  I’m not a great fan of using such specific names. Instead should we overload the ‘dot’ builtin function?
* JS: I think - these have been supported as core feature of Vulkan and HLSL.
* AB: do you want these polyfilled? Then there's more impetus to add them to the spec as a core feature. If you want them HW accelerated, we need an enable flag. Is there concern that there would be a noticeable performance cliff if it has to be polyfilled in software.
* MM: today, for apps using DP4A - they exist - do they not work on devices that don't have that instruction? Or what do they do? App has 2 code paths?
* JS: not sure. For Intel's XESS, only requires SM 6.4. Supported on many other devices.
* MM: so apps themselves don't check for HW support, they just run the instruction.
* AB: on the Vulkan side you can see if it's HW accelerated.
* JS: similar on D3D. Can query device ID.
* MM / KG: sounds like we should polyfill it.
* KG: Agree should polyfill it.
* CW: then people won't know whether it's HW accelerated.
* MM: they're saying people don't care.
* KG: agree the name's unfortunate, if we expand to 16-bit pieces. But if stuck with this weird builtin and go in a different direction, that's acceptable.
* MM: if we picked a different name would that disappointing Intel?
* AB: the "A" - accumulations - the proposed feature here don’t do accumulations. Would also want to think about a future where we have unpacked i8 support. Understand packed dot situation, and integer performance.
* MM: how much does Intel care about the name?
* JS: not sure. DP4 is not a name only used by Intel.
* MM: OK for us to rename it?
* JS: sure. Also compilation time we can fuse together to DP4A instruction.
* CW: the "A" - accumulation - peephole optimization in compiler.
* AB: Vulkan only adds accumulation if you add saturation. We don't expose that.
* MM: sounds like everyone's pretty positive. Questions about the name, etc. But general thumbs up.
* KG: also, pretty narrow use case, so not too worried about the name.
* CW: since thinking of polyfilling - it's not an enable. It's in WebGPU V1?
* MM: you OK with that?
* BC: there are other things we have hardware caps for. Why polyfill?
* MM: existence proof - there are apps running on D3D12 and they run everywhere, just hardware accelerated in some places. Tried polyfilling FP16, was unsuccessful.
* BC: V1 vs. 1.1?
* AB: thought we agreed, post-V1.
* CW: **consensus** - yes for this - name is fine.
* AB: long ago, we agreed post-V1 on this.
* KG: technically, post-V1 polish - agreeing now that we should just do this, soon after V1.
* DS: thought this could be the first post-V1 sugar feature.
* 
* 

</details>

**Comment by Jiawei-Shao** [comment]
On all Metal version DP4A can be implemented with dot products on ```packed_char4``` and ```packed_uchar4```:

```C++
uint dot4U8Packed(uint input1, uint input2) {
    packed_uchar4 vec1 = as_type<packed_uchar4>(input1);
    packed_uchar4 vec2 = as_type<packed_uchar4>(input2);
    return vec1[0] * vec2[0] + vec1[1] * vec2[1] + vec1[2] * vec2[2] + vec1[3] * vec2[3];
}

int dot4I8Packed(uint input1, uint input2) {
    packed_char4 vec1 = as_type<packed_char4>(input1);
    packed_char4 vec2 = as_type<packed_char4>(input2);
    return vec1[0] * vec2[0] + vec1[1] * vec2[1] + vec1[2] * vec2[2] + vec1[3] * vec2[3];
}
```

**Comment by dneto0** [comment]
Google would like to land this soon.

After more internal discussion:
* We affirm the previous decision to make it available everywhere.  (It is a '[language extension](https://gpuweb.github.io/gpuweb/wgsl/#language-extension)' and not an '[enable-extension](https://gpuweb.github.io/gpuweb/wgsl/#enable-extension)')
* We would like to revisit one thing:  We would like to match the HLSL pattern of using only the accumulation form; accumulation wraps (and does not saturate).
    * The mapping to HLSL is direct.
    * For SPIR-V, at best you get 2 instructions: the dot product, and then the 32-bit add is separate.  We estimate this is fine.
    * The MSL polyfill is straightforward.

**Comment by alan-baker** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2023-10-10-Minutes#dp4a">WGSL meeting minutes 2022-10-10</a></summary>

* PR: [#2378](https://github.com/gpuweb/gpuweb/pull/2738)
* AB: Google wants to ship this.
* AB: After internal discussion, we asked to add the accumulator back since it will be polyfilled if support is missing; map more directly to HLSL. Can supply 0 to get the non-accumulating form.
* SJ: Then we need to consider the overflow issue on the accumulator
* AB: Language extension name is a suggestion.
* AB: Assume overflow is like any other integer add (on concrete type) which is wrapping behaviour. In SPIR-V the accum is separate instruction, so assume wrap. Need to check what HLSL says/ spir-v says dot product overflow yields indeterminate value.
* JB: In general use this applies to u32 read from a buffer. If you did the pack/unpack yourself you probably lost the throughput.
* AB: Pack/unpack is for assembling data, and supplying a constant. Yes, generally think the data comes as u32 from a buffer.
* JB: No strong opinion on accum/non-accum.
* AB: Chrome/Dawn has experimental implementation of non-accumulating.
* JB: Fits directly onto a machine instruction. Is your peephole optimization not effective?
* AB: That’s a reasonable expectation. SPIR-V arrived at a different answer than HLSL. SPIR-V thought addition was only worth combining for the saturation case.
* JB: ML folks seem to have moved to 4bit values, and so maybe don’t worry too much about this optimizing perfectly. Let’s ship something here ASAP.
* AB: If we prefer to leave it off, then we’re ok with that.
* JB: easier to document the feature without accumulation.
_Consensus to keep it as the non-accumulating form._

</details>
