### ISSUE TITLE
Consider putting most of the writeTexture validation on the device timeline.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2680]
Right now `GPUQueue.writeTexture` runs `validating linear layout` on the content timeline and raises an exception if it fails. There doesn't seem to be a strong reason why that's the case, and this is duplicating validation code in browsers to be both in the GPU process and the content process. We should run that validation on the device timeline instead.

**Comment by kainino0x** [comment]
FTR, this was changed in #832.

It's technically possible to move this validation to the device timeline, but in actual practice the content timeline (content process) must always do similar computations in order to figure out how much data (from `dataBytes`) to send to the device timeline (GPU process). Spec-wise, we can either:

- leave it as is (editorially, we need to actually write down the fact that it's computing the number of bytes to copy)
- write the spec as if it copies the entire source buffer to the device timeline, and then the device timeline does validation and extracts the right part. But non-normatively, actual implementations will have to diverge from this because they can't just copy the whole source buffer (which may be the WASM heap), so must compute either the exact number of bytes needed for the copy, or conservatively overestimate it.

The specific reason people run into this is that the `dataLayout` parameter contains an `offset` into the `BufferSource` which allows using this entry point without [creating a view](https://github.com/emscripten-core/emscripten/blob/d4873eb3f22a0f4a87bcf82df331712030564358/src/library_webgpu.js#L1470) with the correct offset. If we didn't have that, maybe we could either:

- get away with copying the entire `BufferSource` (issuing a warning if it's way too large), because users would have to create subarrays anyway and could specify a length.
- add a required `dataLength` parameter which tells us how much to copy.

cc @Richard-Yunchao who recently [did work on this](https://chromium-review.googlesource.com/c/chromium/src/+/3457847/4..11/third_party/blink/renderer/modules/webgpu/texture_utils.cc#b72)

**Comment by kainino0x** [comment]
OK, I think moving it to the device timeline is fine.

I think your pseudocode needs to get slightly more complex, since it needs to handle all valid cases correctly including zero-sized copies (which are generally valid but we shouldn't no-op because other validation is still supposed to run).

**Comment by Kangz** [comment]
There's been agreement to proceed with this. Moving to needs-spec.

**Comment by kainino0x** [comment]
This ended up getting fixed in #2702.
