### ISSUE TITLE
etc2-rgba8unorm and etc2-rgba8unorm-srgb do not exist in Metal

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2683]
https://developer.apple.com/documentation/metal/mtlpixelformat

> - MTLPixelFormatETC2_RGB8
> - MTLPixelFormatETC2_RGB8_sRGB
> - MTLPixelFormatETC2_RGB8A1
> - MTLPixelFormatETC2_RGB8A1_sRGB

**Comment by Kangz** [comment]
Wouldn't these be the `MTLPixelFormatEAC_RGBA8` and `MTLPixelFormatEAC_RGBA8_sRGB` formats? We didn't implement support in Chromium for ETC2 and ASTC compressed formats due to a lack of Apple M1 hardware to test on so I can't know for sure.

**Comment by Kangz** [comment]
I [implemented ASTC and ETC2](https://dawn-review.googlesource.com/c/dawn/+/84481) support in Dawn on Metal and someone kindly tested it for me. Using the mapping for `etc2-rgba8unorm*` I commented above works, and passes test that check some simple test vectors. I'll close this issue since the mapping above looks correct.

**Comment by litherum** [comment]
Ah, I got confused about ETC vs EAC.
