### ISSUE TITLE
my2DArrayTexture.createView() doesn't create a full view

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2684]
The steps for [defaulting the `GPUTextureViewDescriptor`](https://gpuweb.github.io/gpuweb/#abstract-opdef-resolving-gputextureviewdescriptor-defaults) for a 2D array texture first default `dimension` to `2d` and then default the `arrayLayerCount` to `1`. This is quite unexpected since `.createView()` seems like it would create a full view of a texture.

Looking at the history of that spec section, it seems that the change comes from [this comment thread](https://github.com/gpuweb/gpuweb/pull/1416#discussion_r571331271), that doesn't call out this change of behavior explicitly. @kainino0x @toji, this seems like a bug, can you confirm?

**Comment by kainino0x** [comment]
I believe it was intentional, basically because the algorithm was too complicated. There was a sort of feedback loop between the defaulting of `dimension` and `arrayLayerCount`, and though it was possible to come up with rules that worked, they were complicated and not that obvious. For example:
- what if texture is 2x2x2 and you `texture.createView({ arrayLayerCount: 1 })`?
- what happens if you request arrayLayerCount=1 on a 2d texture with multiple layers?
- what happens if you request baseArrayLayer = (texture depth - 1)?

**Comment by kainino0x** [comment]
(accidentally submitted before I finished writing)

Having the resulting dimension depend on the input texture depth is the most straightforward, but it also results in a weird situation when that value is data-driven: some change results in the texture depth going from 2x2x2 to 2x2x1 and suddenly you get a different type of view.

**Comment by Kangz** [comment]
Was this change discussed in the meetings or even mentioned? I can't find any trace of it.

While I agree that the algorithm was previously a bit complicated, having `CreateView()` not always return a full view to the texture is extremely misleading.

What about defaulting the dimension first depending on the texture's dimension and arrayLayerCount, then doing the rest of the defaulting? It seems the only surprising case would be when developers create a 2D array texture programmatically and it happens to have 1 array layer, but that's basically never going to happen?

**Comment by toji** [comment]
It was discussed in the editors meetings. This was also relatively early days of my contributions to the spec, so I was probably leaning on the editors a bit more for guidance than I would have if I were making this change later.

The tricky thing is that in order to do the most "naturally" correct thing, you'd almost have to have two different algorithms. To expand on Kai's examples, assuming I have a 2d texture with multiple layers, how do we write an algorithm that cleanly does the "naturally" correct thing in all these scenarios?

- `texture.createView();` -> Default to `2d-array`?
- `texture.createView({ arrayLayerCount: 1 });` -> Should probably be a `2d` view, right?
- `texture.createView({ arrayLayerCount: 6 });` -> Default to `2d-array`, even though it could also be a `cube`.
- `texture.createView({ baseArrayLayer: 5 });` -> Wait, is this a `2d-array`? What if it has 6 layers? Then does it default to `2d`? So now dimension is dependent on both the arrayLayerCount and the baseArrayLayer?
- `texture.createView({ dimension: '2d' });` -> 1 layers
- `texture.createView({ dimension: '2d-array' });` -> All layers
- `texture.createView({ dimension: 'cube' });` -> 6 layers
- `texture.createView({ dimension: 'cube-array' });` -> floor(All layers / 6)? That's getting weird.

In my mind defaulting the dimension to match the texture dimension every time is pretty sensible and predictable and breaks the two way dependency of arrayLayers and dimension. Plus we make it as easy as possible to get a good default if you explicitly request any other dimension. The rules are easy to remember because they don't have a ton of interdependencies.

**Comment by kainino0x** [comment]
Maybe we could just make the view dimension required if the source texture has more than 1 array layer?

**Comment by Kangz** [comment]
> In my mind defaulting the dimension to match the texture dimension every time is pretty sensible and predictable and breaks the two way dependency of arrayLayers and dimension. Plus we make it as easy as possible to get a good default if you explicitly request any other dimension. The rules are easy to remember because they don't have a ton of interdependencies.

I totally agree that the previous version of the algorithm was too unpredictable. I think there's way to solve this issue without introducing it back, by using the texture's `depthOrArrayLayers`. Right now, as a developer, if I create a 2d array texture, I will tend to get 2d textures out of `createView` and that's surprising.  What about this algorithm:

```js
if (dimension === undefined) {
    switch (texture.dimension) {
        case "1d": dimension = "1d"; break;
        case "3d": dimension = "3d"; break;
        case "2d":
             // THIS IS WHAT CHANGES
             if (texture.size.depthOrArrayLayers > 1) {
                 dimension = "2d-array";
             } else {
                 dimension = "2d";
             }
             break;
    }
}

format ??= texture.format;
mipLevelCount ??= texture.mipLevelCount - firstMipLevel;

if (arrayLayerCount == undefined) {
    switch (dimension) {
         case "1d" | "2d" | "3d": arrayLayerCount = 1; break;
         case "cube": arrayLayerCount = 6; break;
         case "2d-array" | "cube-array":  arrayLayerCount = texture.arrayLayerCount - firstArrayLevel; break;
     }
}
```

It is basically the current algorithm, except that the defaulted 2D-arrayness is decided based on the number array layers of the texture. Looking at the examples:

 * `texture.createView();` -> Reasonable, defaults to the full 2d-array
 * `texture.createView({ arrayLayerCount: 1 });` -> Defaults to a `2d-array` with a single layer. Somewhat expected since the texture is a 2d array..
 * `texture.createView({ arrayLayerCount: 6 });` -> Default to `2d-array`, reasonable, cubes are special.
 * `texture.createView({ baseArrayLayer: 5 });` -> Defaults to a `2d-array` with whatever the remaining layers are.
 * `texture.createView({ dimension: '2d' });` -> 1 layer, reasonable.
 * `texture.createView({ dimension: '2d-array' });` -> All layers, reasonable.
 * `texture.createView({ dimension: 'cube' });` -> 6 layers, reasonable.
 * `texture.createView({ dimension: 'cube-array' });` -> All layers, might cause a validation error, somewhat reasonable?

So the only two somewhat tricky cases are if a developer creates a 2d array texture programmatically and sometimes ends up with 1 layer (IMHO this is the only major drawback). It seems somewhat rare and they can always specify `2d-array` when creating views. The other slightly tricky case is if you set `viewDesc.arrayLayerCount = 1` for a 2D array texture, but regularity is pretty clear so I think it will be simple for developers.

**Comment by toji** [comment]
It's still slightly more magic than I typically like, but it's also a small enough change that I'd be OK with that. Kai?

It would be an annoying deprecation, mind you. Couldn't actually change the default behavior outright, so we'd need to have a period where any time the defaulting behavior is used with more than one array layer we'd throw out a warning telling people not to rely on the defaults. ☹️

**Comment by kainino0x** [comment]
I don't think the texture depth will be data-driven that often, but when it is, the problem I see is that it's very easy to accidentally not test this corner case, and then your application breaks in production (e.g. different model file, or some quality settings got automatically scaled down, or something)

I also prefer adding validation because it's a much easier deprecation to implement...

**Comment by Kangz** [comment]
> I also prefer adding validation because it's a much easier deprecation to implement...

That's an implementation detail :) but also we discussed it briefly with @toji and agreed we could do it with no deprecation.

**Comment by kainino0x** [comment]
> The tradeoff feels like gaining really tiny correctness and the cost of larger developer usefulness imho.

An additional thought, I think it's more in line with other parts of the API. In cases where it's not obvious what the default should be (in this case, 2d vs 2d-array, but also cube and cube-array) we usually just require you to specify. Better for readability. (Though any amount of defaulting here is a _little_ bad for readability, since it's hard to know what the internal configuration of a GPUTexture is without seeing the createTexture call.)

**Comment by toji** [comment]
I think @kainino0x might have messaged @Kangz about this directly, but wanted to recap here: Kai and I talked about this yesteday and I'm onboard with an approach that requires an explicit dimension be specified in the number of array layers is > 1.

The primary reasoning on my end is that I feel like between cubemaps and 2D array textures, I actually feel like cubemaps are going to be the more common use case when constructing textures like this. As such, it feels weird to provide a default that doesn't match the common usage, and any attempt to default to cube maps when the layer number is a multiple of 6 but 2D arrays otherwise is going to cause way more confusion. It's simpler and more consistent to just require the developer be specific about their needs when we don't have an obvious default to fall back to.

**Comment by kainino0x** [comment]
After talking with Corentin about this I understand better why this is a problem. In essence, if you create a 2d-array, it's usually because you wanted to use it as a 2d-array (or cube/cube-array), and not just because you wanted to use it as a stack of 2d textures. Between 2d-array/cube/cube-array, there's a clear default of 2d-array. So the tension for me is just between 2d and 2d-array. One thing Corentin said was since views are kind of "in the way" in a lot of cases, it's very nice to allow people to just `.createView()` as much as possible.

Understanding that problem, I'm pretty neutral on this, and would go either way (change the default, or make the view dimension required).

An alternate idea (just throwing it out there, not particularly in favor of it): Just distinguish '2d' and '2d-array' texture dimensions. None of the 3 backend APIs need this info, and you'd be able to use '2d-array' just as you use '2d' today, but it would communicate the intent. Could also add 'cube' and 'cube-array' and just merge the texture/textureview dimension enums. (This would help on OpenGL, btw, though that's not a design consideration.)

**Comment by kainino0x** [comment]
I think the "texture dimension '2d' actually means 2d-array" thing trips up a lot of learners, but they probably get past it pretty quickly.

**Comment by kainino0x** [comment]
Editors+Myles thoughts:
- Corentin's proposal is good: just make the view dimension default depend on the texture depthOrArrayLayers. Only a minor wart that when depthOrArrayLayers is programmatic, you'll want to specify a view dimension explicitly because the default is unstable.
- Bring that to the group as the proposal (tacit resolution queue probably), but just mention the alternate proposal of adding an (otherwise unnecessary) distinction between 2d and 2d-array to the texture object (in GPUTextureDimension).
