### ISSUE TITLE
WGSL parsing assumes context-aware tokenization

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2717]
Summary: The current description of the WGSL tokenization and parser is not accurate. Something more subtle is needed.

The WGSL spec describes tokenization as independent of parsing.
But Treesitter, which we use to check for validity and potential ambiguity, uses a few tricks that go beyond textbook parsing.
See https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens 

The first thing mentioned there, context-aware lexing, is essential to making the WGSL grammar "work".

The background research is referenced from the Treesitter docs:  
[Context-Aware Scanning for Parsing Extensible Languages](https://www-users.cse.umn.edu/~evw/pubs/vanwyk07gpce/vanwyk07gpce.pdf) Eric R. Van Wyk, August C. Schwerdfeger, GCPE'07, 2007.

The key idea is there's cooperation between the parser and the tokenizer.  When asking for a token, the parser tells the token-scanner which tokens are acceptable to return, assuming the _current parser state_.   If your grammar is reasonable, then it will all be deterministic and predictable.

For example, consider `let v: vec2<i32>= vec2(1,2);`
The two code points `>` `=` are adjacent.   The greedy tokenization, as described by the WGSL spec would yield the `greater_than_equal` token, and cause the parse to fail.

Instead, Treesitter knows that at that point in the parse, immediately after the `i32` token, that `>` is an acceptable next token and `>=` is not.    So when it requests a next token, the scanner is given that discriminating info, and the scanner will return the `>` token.  Then the parse can succeed.

Hand-written parsers, like the ones in Tint, handle this with a manually-specified retry. First it tries to consume the greater_than_equal token, and if the parse *would* fail, it backs of and splits the token into two.

Note: I found this when exploring how to add the shift tokens back again (due to popular demand).

**Comment by dneto0** [comment]
## Relation to standard LR and LALR parsing

Ok, I've reviewed LR parsing (and construction of SLR, LALR(1) tables), and the context-aware tokenization looks like a pretty straightforward modification.  LR(1) and LALR(1) parse tables have the same structure:

The _action_ table is indexed by parser state and lookahead token, and the entries are one of four kinds: shift, reduce, error, or accept.

From the paper, section 3.2 "Modified LR Parsing":

> Valid lookahead sets: A valid lookahead set is defined for each parse state _ps_ as the set of terminals that have non-error parse actions associated with them: ...

And then later it says that the parser's interface to the scanner is modified to add a parameter to indicate which are the valid tokens.  That is, tokenization occurs during parsing, and the token is only requested at the time of the lookup in the action table.  So you have the current state in hand, then you request a token from the scanner, limited to the valid tokens in the current state. Then you look up the action given both the state and the returned token.

That actually seems really straightforward.
 
Also, a hand-written recursive descent parse can (easily) incorporate the "valid lookahead tokens" restriction when requesting the next token.   I'd want the spec to spell out the valid token set for each such state, or to have that automatically generated from the spec (and checked by CI).

## Lexical determinism

A subtlety is making sure tokens are well defined and unique.

Section 5.2 gives an algorithm/test to ensure that there is "lexical determinism".  

> A scanner exhibits lexical determinism if for any input, it will match 0 or 1 terminals.  We have developed a simple analysis that tests whether or not lexical ambiguities exist in a lexical specification with respect to a given parser.  Since the valid lookahead set
plays a critical role in this analysis, lexical determinism can only be
determined by examining both the lexical and context free syntax.
In our algorithms, any set of tokens returned to the parser is the intersection of a valid lookahead set (validLA) and the accept set of
a DFA-state (acc(ss)) from which is removed any terminal whose
lexical precedence is lower than that of some other terminal in that
set. Such a set with cardinality greater than 1 is a lexical ambiguity.

Lexical precedence is one of the extra features the authors use to help them compose grammars and lexers on top of each other.  The WGSL grammar doesn't have any precedence rules applied, except to say that identifiers can't be keywords or reserved words, etc.

The formalized rule is (rewritten without latex symbols....):

    forall sp in ParserState
      forall ss in the state space of the lexer's DFA
         Let  Candidates = { t in validLookahead(sp) intersected with tokens accepted in the DFA starting at state ss }
         Let  FavouredCandidates = { t in Candidates | there are no t' in Candidates, with precedence(t') > precedence(t) }
         The size of FavouredCandidates should be 0 or 1.

Reviewing https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens there are 5 ways of resolving conflicts among tokens:

1. Context-aware lexing.  Restrict the next token to the valid ones in that parser state.
2. Lexical precedence.  See the `prec` functions in the Treesitter model.  The WGSL grammar construction does not use or generate these.  So we can ignore this.
3. Match length.  This is the usual longest-match heuristic for tokenizers.
4. Match specificity:  literal string is favoured over regexp.  
     * The only regexp rules are for the numeric literal tokens, comments, and identifiers.
6. Rule order:   Earlier tokens are favoured over later tokens.
       * This is actually used for WGSL, where we put the generic identifier rule after all other tokens.   
       * The numeric literal tokens can't overlap among each other:  If any of a decimal point, exponent spec, or 'f' suffix is present, then it's a float literal.  Otherwise it's an integer literal.  The regexps ensure this.
       * There is no overlap between the regexp rules: numeric literals,  identifiers, comments.
       * So the only way the "rule order" is used is to choose keywords (and reserved keywords) over an identifier.

I strongly suspect that for WGSL there's a far simpler formulation of the lexical determinism rule. 
* For fixed strings, the longest-match (among valid lookahead tokens) removes ambiguity. E.g. if both `>=` and `>` are allowed then `>=` is favoured anyway.
* In WGSL the regexps don't overlap the fixed string tokens, except for the known rule about identifiers vs. keywords and reserved words.
* So the conflict can only occur between a regexp vs. regexp.
* The only regexps are for identifiers, comments, and numeric literals. 
* Let's ignore comments, since WGSL specifies they are replaced by spaces before doing any parsing or lexing.
* But we know from above that identifiers and numeric literals can never be confused for one another.

So the context-aware scanner for WGSL has lexical determinism:  Given a position in the input, and the LR parser state at that position, the scanner will only ever yield at most one token from the ValidLookahead tokens at that parser state.

(I think that's right).

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-05-minutes-(apac)#wgsl-parsing-assumes-context-aware-tokenization-2717">WGSL meeting minutes 2022-04-05</a></summary>



* DN posted PR: [https://github.com/gpuweb/gpuweb/pull/2735](https://github.com/gpuweb/gpuweb/pull/2735) 
    * LALR(1), with context-aware tokenization
    * Removes parsing ambiguity between function call and type-constructor expression by refactoring the grammar.
* DN: We’ve been relying on treesitter, that our grammar is unambiguous. However treesitter also goes beyond more limited parsing. Effectively it does have a way to address what we’ve called our layering violation here. So it implements the 2007 paper that limits what it can tokenize next from its valid lookahead table. Thus I feel this is a perfectly fine thing to do, so I’ve written this up explicitly in the spec. Also removed some other ambiguities.
* RM: I agree that having some context awareness is required. I’m wondering what you mean when you say “set of valid lookahead tokens”.
* DN: When you generate the LR states, and you compute the first set of non-terminals to be consumed, *taht* is the (valid) lookahead token. So you’re in a state with a bunch of items, and each item has a set of items that’s allowed to have a valid transition. Any token that would cause you to immediately go to an error, would not be part of the valid set.
* RM: A token that allows you to do one reduce would still be allowed?
* DN: You only reduce when you consume the token at the end. It’s hard to explain.
* RM: Trying to figure out how to implement this in a recursive-descent parser. Do I need to keep track of more state, or can I figure this our purely from known local state?
* DN: Not sure. I wondered, “do I need an LR parser in order to get these sets?” Not sure still.
* AB: consider:
    * let x : array&lt;i32, 4>= ...;
    * the ">=" would be tokenized as ">" and "=" instead.
* AB: Currently, this would be an invalid token to see there.
* AB: The real thing we want consensus on is “will everyone’s parser [be able to] do this”. E.g., will Naga do this?
* JB: I think maybe the code will be ugly, but like, big deal. Worth doing in our code, to save millions of users from having to do e.g. what c++ used to need.
* AB: DN did have another approach, fwiw.
* MM: I think the interesting question is exactly “is this worth having in the grammar”, and I’m not sure if we can evaluate without evaluating more holistically
* DS: This example is only a problem with constexpr, so this is not currently an issue. Is there a case where you would actually parse with the wrong token, but then comiple successfully but get the wrong answer.
* MM: I was previously more confident that splitting-vs-not-splitting wouldn’t lead to two valid parsings, but now I’m less sure.
* AB: I think with this new approach that we’re using with treesitter, means that we are safe from this.
* DN: Treesitter’s hack generally does what you want. 
* MM: So in the >= case, the >= would win over the >, so this would be an error?
* DN: Normally it would, but the context-awareness would realize it’s parsing a template arg list, so it would know it can’t use a >=.
* DS: Shift?
* AB: Shift is still ambiguous, so we do need e.g. parens there.
* JB: Do we know that we will not have ternary expressions here?
* AB: The grammar where you define the array here knows that it can’t have that. That’s why I explain that if we do add ternaries it could certainly cause problems.
* MM: I don’t think we should assume we won’t have ternaries.
* DN: I think you can fix this with multiple roots for the grammar for these, one with parens, one without.
* DS: Can we just force the constexpr tree to be parenthesized.
* MM: I think you want to say const a = 4+5, and that if we can’t say that, we’re doing users a disservice.
* MM example let x : array&lt;i32, 13 >> 2>;
* MM example: let x : array&lt;i32, 4>= 3 ? 2 : 1> = ...;
* JB: If the len expression of an array jumps into the middle of precedence levels, the precedence levels here are very low, we would already be required to paren expressions just in order to have it at all. By jumping into the middle to the precedence stack, we’re already requiring that we have parens around all the weird things.
* DN: I think I get the spirit about what you’re saying. I think if we try MM’s example, treesitter will say “there’s an ambiguity”, and I’d solve that by having different grammar roots used there. 
* MM: We’d like some time to make sure we don’t need to keep a global structure for where we are in our recursive-descent parser.
* JB: Naga is also RD, so while we want to solve this core issue for users, I agree that I want to make sure it’s possible
* DN: Tint is also RD :)
* **_Leave this for a week. Call to action: review your recursive descent parser to see _**


</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-12-minutes#wgsl-parsing-assumes-context-aware-tokenization-2717">WGSL meeting minutes 2022-04-12</a></summary>



* Previously:
    * Leave this for a week. Call to action: review your recursive descent parser to see 	
* DN: Landed the grammar refactoring separately, as [https://github.com/gpuweb/gpuweb/pull/2737](https://github.com/gpuweb/gpuweb/pull/2737) 
* DN: Still working on programmatically extracting the lookahaeds from the grammar. 
* MM:  Our concerns last week was number of tokens to lookahead to be bounded. 
* JB: Have not reviewed parser structure.
* _Check back next week._


</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-19-minutes#wgsl-parsing-assumes-context-aware-tokenization-2717">WGSL meeting minutes 2022-04-19</a></summary>



* DN: Working on parser generator/analyzer. which can now determine LL1-ness, but WGSL is not. Not the intent to make it so.   Working on upgrading to LALR-table generation.


</details>
