### ISSUE TITLE
WebGPURenderingContext should support preserveDrawingBuffer: true

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#2743]
My understanding is that currently, the thinking is there will be no `preseveDrawingBuffer` attribute for the `WebGPURenderingContext`

I don't know if this is a compelling use case for `preserveDrawingBuffer` but ... many products use something like [html2canvas](https://github.com/niklasvh/html2canvas)(25k stars) to generate screenshots for feedback/bugreports. I don't know what library Google uses but as an example, most Google apps have a feedback form and most of those forms generate a screenshot with AFAIK, some similar library.

To do this they need to be able to call `toDataURL` or `toBlob` on all canvases. In general, in WebGL and WebGPU, every canvas has 2 buffers, a drawingBuffer and a displayBuffer. `toDataURL`, `toBlob`, `texImage2D`, and `createImageBitmap` all read from the drawingBuffer. The displayBuffer is never exposed to the app (it's used by the browser's compositor). When `preseveDrawingBuffer` is false, t the drawingBuffer is cleared on composite. When composite happens is undefined but basically with `preserveDrawingBuffer` is false, the only safe time to call `toDataURL` or `toBlob` or any of those other functions is before exiting the current event.

Without `preserveDrawingBuffer: true`, it seems difficult to do support use cases like html2canvas. Off the top of my head they would have to insert themselves into the render loop of every library on every canvas so that when that render loop exits they can grab a copy. Further, they can't just augment `requestAnimationFrame` and grab a copy at the end. Instead they'd have to wrap every possible event since rendering might happen on `setTimeout`, `setInterval`, `mouseMove`, `touchMove`, `pointerMove`, `click`, `fetch` completion, a message from a worker, etc...

If `preserveDrawingBuffer` exists, the easy way for them to support html2cavnas is to patch `getContext` with something like

```
HTMLCanvasElement.prototype.getContext = function(origFn) {
  return function(type, attribs, ...args) {
    const newAttribs = {...(attribs || {}), {preserveDrawingBuffer: true}}
    return origFn.call(this, type, newAttribs, ...args);
  };
}(HTMLCanvasElement.prototype.getContext);
```

A counter argument is you could say they're required to re-architect their app so they can do something like

```
function takeScreenshot() {
  // in a single event, call every library that renders to a canvas so that its content
  // is available since it will be cleared when this event exits.
  renderMap();
  renderGraph();
  renderDoc();
  renderDiagram();

  const screenshot = html2cavnasLib();
}
```

I suspect that's a huge ask for many devs who start off without that architecture and then later want to add screenshot support for feedback and would like it to be as painless as possible and don't really want to have to re-architect or patch 3rd party libraries.

**Comment by kainino0x** [comment]
One of the reasons we didn't add `preserveDrawingBuffer` is that one of its biggest use-cases is exactly this, but it's an excessively heavy hammer for that: it impacts power/performance every frame, forcing the backbuffer to be copied instead of moved every frame, just in case you need to take a screenshot occasionally. At that time, we thought we would be able to make `toDataURL`/etc work after presentation without any special flag, but the spec currently doesn't allow that (my fault), and [recent investigations I'm in the middle of](https://docs.google.com/document/d/1FSIAInhiumYmf2Q5TQUV8uZuS_VgWGeLF7FmPCLFXk4/edit?usp=sharing) uncovered some arguments to keep it that way.

I think we should try hard to find a better solution - option 1c (or similar) in that document would be one option: provide an option that makes the currently-presented image available to `toDataURL`/etc.

**Comment by kainino0x** [comment]
> At that time, we thought

Oh yeah, another detail came to mind: we also really wanted to avoid `preserveDrawingBuffer` being needed for print/copy/save-image-as. I believe we still can. Today, WebGL is [terribly inconsistent](https://codepen.io/kainino0x/pen/jOBXqNV), but I don't suspect there are any any fundamental limitations. (For example, in Chrome the first case is blank on print/copy, but red on save-image-as.)

**Comment by litherum** [comment]
> to generate screenshots for feedback/bugreports

> To do this they need to be able to call toDataURL or toBlob on all canvases.

I don't quite understand how the latter follows from the former. If the use case is generating screenshots for bugreports, then presumably the library would create the destination canvas, rather than having to render into arbitrary canvases.

**Comment by greggman** [comment]
Sorry, my comment should say they need to able to call "toDataURL or toBlob or drawImage" etc...

Some pseudo code.

```
function libraryToMakeScreenShotOfDOM() {
  const dstCanvas = makeACanvas();
  drawDOMElementToCanvas(dstCanvas, document.body);
  return dstCavnas.toBlob();
}

function drawDOMElementToCanvas(dstCanvas, elem) {
   for (const child of elem.children) {
     switch (child.nodeName) {
       case 'DIV': ???; break
       case 'SPAN: ???; break;
       case 'CANVAS':
         {
            // this line fails unless child is preserveDrawingBuffer: true
            // if the canvas is WebGL (and AFAIK for WebGPU too)
            destCanvas.drawImage(child, ...);   
         }
      }
   }
}
```

i believe html2canvas is doing something like this. Often WebGL canvases end up blank. A quick solution is devs add the code in the top comment to their page.

**Comment by litherum** [comment]
> html2canvas needs to read the page's canvases

Then preserveDrawingBuffer doesn't help you - the source canvas doesn't have to set it to true.

**Comment by kdashg** [comment]
It feels like what we really want is:
```
partial interface HTMLCanvasElement {
    async ImageData snapshot();
}
```

**Comment by kainino0x** [comment]
meeting: strong appetite for a solution to this use-case that's better than preserveDrawingBuffer. me to try to come up with a concrete proposal

**Comment by greggman** [comment]
> > html2canvas needs to read the page's canvases
> 
> Then preserveDrawingBuffer doesn't help you - the source canvas doesn't have to set it to true.

See code above in the top message. It's easy for the user to force all canvases to use `preserveDrawingBuffer: true`

Basically, regardless of which solution is picked it would be nice if users could use the solution without having to updating the code doing the "source" drawing.

Example: You put a unity app on your page. Unity is drawing in a WebGL canvas. You try to take a screenshot. It fails and modifying the Unity app is not an option (You don't own unity or the plugins needed for the app, you don't have the source for the app, you don't know C#, and emscripten is magic C++, you only have JavaScript experience, the unity app is a blackbox).

Using [the solution above](https://github.com/gpuweb/gpuweb/issues/2743#issue-1197814836) it's trivial to from outside of the unity code to force Unity to use `preserveDrawingBuffer: true`. 

It would be nice if there is a solution for WebGPU as well where non-WebGPU code and some how get a screenshot of a WebGPU canvas.

> Note: preserveDrawingBuffer:true not guarteed to be slower in WebGL because WebGL defaults to multsampled drawingbuffers which means in most cases it's doing a resolve copy and so then you set `preserveDrawingBuffer: true` it's actually fast (no more clearing the multi-sampled buffer). I know that's different in WebGPU and so looking forward to a better solution

**Comment by kainino0x** [comment]
In WebGPU an option like this would end up in GPUCanvasContext.configure(). So it would still be possible to interpose on that.

It occurs to me, though, that modifying the canvas or configuration underneath the application's feet can affect its correctness. After today's discussion I'm tentatively thinking we can come up with a solution that doesn't even require a configuration option: I think we could make this work all the time without any flags, by just "clearing" the readable texture on getCurrentTexture instead of on present.

**Comment by kainino0x** [comment]
> At that time, we thought we would be able to make `toDataURL`/etc work after presentation without any special flag

I.e. we may have been correct about this the first time.

**Comment by greggman** [comment]
Just for clarification on your proposal

what happens if I do (in psuedo code)

```
for (const alphaMode of ["opaque". "premultiplied"]) {
    webgpuCtx.configure({alphaMode, ...});

    renderPassDescriptor.colorAttachments[0].view = context.getCurrentTexture().createView();

    webgpuClearTo(0, 1, 0, 0);  // transparent green
    webGL.texImage2D(....,  webgpuCanvas);

    webgpuClearTo(0, 0, 1, 1);  // opaque blue
    webGL.texImage2D(....,  webgpuCanvas);

    webgpuClearTo(1, 0, 0, 0.5);  // 0.5 transparent red

    await raf();  // assume compositing happened

    webGL.texImage2D(....,  webgpuCanvas);
}
```

What data will be in the 6 textures? (repeat for drawImage, toBlob, etc... if they are different)

**Comment by greggman** [comment]
To add, what is the state of the canvas texture after each call to texImage2D?

**Comment by kainino0x** [comment]
This is a great example case, thanks for writing it up. You should get:
- `"opaque"` 
    - `0, 1, 0, 0` -> `0, 1, 0, 1`
    - `0, 0, 1, 1` -> `0, 0, 1, 1`
    - `1, 0, 0, 0.5` -> `1, 0, 0, 1` (doesn't matter whether rAF happened, as long as there hasn't been a new getCurrentTexture)
    - if you then call `getCurrentTexture` and try again, you get `0, 0, 0, 1`
- `"premultiplied"` behavior depends on `UNPACK_PREMULTIPLY_ALPHA_WEBGL`. If it's false then an extra unpremultiply step happens before writing into the WebGL texture.
    - premul `0, 1, 0, 0` isn't a valid color, so I think this is currently undefined, I need to think about it and define it
    - premul `0, 0, 1, 1` is preserved, then may be unpremultiplied into `0, 0, 1, 1`
    - premul `1, 0, 0, 0.5` is preserved, then may be unpremultiplied into `2, 0, 0, 0.5` with clamping to the target WebGL format if necessary, I guess? The WebGPU spec can't really spec that. But I think it's the reasonable behavior for "super-luminal" values regardless of the source. (For example WebGL canvas -> WebGL has the same problem)
    - after `getCurrentTexture`: `0, 0, 0, 1`

> To add, what is the state of the canvas texture after each call to texImage2D?

texImage2D won't change the state of the source canvas (in the spec; in implementations, after presentation, texImage2D could clear the alpha channel in place, since it's unobservable)

**Comment by greggman** [comment]
Thanks for the clarification

> texImage2D won't change the state of the source canvas (in the spec; in implementations, after presentation, texImage2D could clear the alpha channel in place, since it's unobservable)

Is this unobservable? It seems like the new spec proposal says the alpha is cleared to zero in place. It also seems like I can call context.configure({usage: RENDER_ATTACHMENT | COPY_SRC}). Which seems to suggest that the clearing that happens is observable but I'm probably mis-reading something.

**Comment by kainino0x** [comment]
The proposal as written says that when the canvas is read out (by the compositor or the page, doesn't matter), a copy is always made of the current canvas context. Then if it's "opaque", the alpha channel of the copy gets cleared and then handed to the caller (compositor or page). Anything that elides a copy or does an alpha-clear in place is supposed to be an optimization (it's just important that we allow those optimizations)

**Comment by kdashg** [comment]
To me, this is an enhancement opportunity, not a blocker for v1.
I'm embarrassed by it, but realistically it's important color here that this pretty similar to a ten year old bug in Gecko's WebGL backend: https://bugzilla.mozilla.org/show_bug.cgi?id=749824

It's also generally more of a Canvas thing than a webgpu thing, though yeah, we're changing what *our* spec says to do about *Canvas's* (polymorphic) API.

I do believe #2905 is similar to what I once implemented in Gecko (but scrapped, possibly because of CTS tests there), so I'm definitely not absolutely opposed to it.

I think my major concern is that generally this is a thing that people want for all Canvas backends, not just WebGPU.
I believe the primary unmet use case is one-off/one-shot requests for snapshots of the already-presented contents of Canvases, rather than efficient gpu->gpu use.

I do want to satisfy this use case, but in my mind the best solution here would be an async one, because I definitely expect to have to make (latency-rich) IPC calls to grab snapshots here.

I would note that preserveDrawingBuffer:true does quite simply bring us back to parity with existing canvas backends, and I would be happy to iterate from there, also. (even if we eventually deprecate it in favor of something truly async)

**Comment by kainino0x** [comment]
I'd strongly prefer if this behavior were always on by default, rather than having to enable it. I also think it *could* be added post-V1. Generally, we don't consider removing validation (turning broken programs into valid programs) to be a breaking change. If we leave the spec roughly as is, you wouldn't get an *error* reading back in the present->getCurrentTexture window, but you would get a blank image. Which seems useless enough that no one is going to rely on that behavior.

So, I'd like to do one of these, in order of preference:
1. Accept #2905 and expect everyone to implement it
2. Accept #2905 with the expectation not everyone will implement it yet
3. Postpone #2905 and land it post-V1

(note: we still need to land the `compositingAlphaMode` -> `alphaMode` part of the PR regardless, in order to future proof the behavior, but should be no big deal)

**Comment by kainino0x** [comment]
A patch on top of #2905 which just removes readback-after-present (keeping the rest of the changes for futureproofing) is here:
https://github.com/gpuweb/gpuweb/commit/dbf8ec49accec5cdf8b11d8e9efddf0fd4635e1d
