### ISSUE TITLE
Combined limit for max vertex stage bind groups + vertex buffer bindings

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2749]
See https://github.com/gpuweb/gpuweb/issues/693#issuecomment-613555566:

> consider adding a maxBuffersPlusVertexBuffersForVertexStage limit later as needed

@kainino0x says that they pessmize, by reporting values for limits such that `maxSampledTexturesPerShaderStage` + `maxSamplersPerShaderStage` + `maxStorageBuffersPerShaderStage` + `maxStorageTexturesPerShaderStage` + `maxUniformBuffersPerShaderStage` + `maxVertexBuffers` < 31. However, this is pretty severe - we probably wouldn't want to pessimize this way.

We plan to use argument buffers (rather than flattening all resources to direct shader arguments) so we would probably want something like a new limit equal to the sum of `maxBindGroups` + `maxVertexBuffers`. That way, we can say "`maxBindGroups` has to be less than 31, and `maxVertexBuffers` has to be 31, and the sum of them also has to be less then 31."

There is precedent for this: WebGPU has limits for `maxComputeWorkgroupSizeX`, `maxComputeWorkgroupSizeY`, and `maxComputeWorkgroupSizeZ`, but there is also a limit for `maxComputeInvocationsPerWorkgroup` which is the product of all 3.

We would probably also need a limit about the number of each kind of resource that can live within a bind group. Such a limit would correspond to the "Maximum number of *** inside an argument buffer" rows in the [Metal feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf).

**Comment by Kangz** [comment]
I think Dawn would require that `maxStorageBuffersPerShaderStage` + `maxUniformBuffersPerShaderStage` + `maxVertexBuffers` + 1 <= 31, this is so that everything fits in Metal's vertex buffers table (with the addition of one buffer for internal use in the implementation). IIRC Dawn supports macOS versions that don't guarantee support for argument buffers so we have to use the resource tables.

> We would probably also need a limit about the number of each kind of resource that can live within a bind group.

The limits should already be validated per BindGroupLayout as the spec says (in the steps to validate `createBindGroupLayout`): "descriptor.[entries](https://gpuweb.github.io/gpuweb/#dom-gpubindgrouplayoutdescriptor-entries) must not [exceed the binding slot limits](https://gpuweb.github.io/gpuweb/#exceeds-the-binding-slot-limits) of this.[[[device]]](https://gpuweb.github.io/gpuweb/#dom-gpuobjectbase-device-slot).[[[limits]]](https://gpuweb.github.io/gpuweb/#dom-device-limits-slot)." so I assume that will be enough for argument buffers.

This isn't to say that we shouldn't add the limit though, if we think the addition of this slight noise will help increase the number of things available in useful ways on some systems.

**Comment by litherum** [comment]
> The limits should already be validated per BindGroupLayout as the spec says (in the steps to validate `createBindGroupLayout`): "descriptor.[entries](https://gpuweb.github.io/gpuweb/#dom-gpubindgrouplayoutdescriptor-entries) must not [exceed the binding slot limits](https://gpuweb.github.io/gpuweb/#exceeds-the-binding-slot-limits) of this.[[[device]]](https://gpuweb.github.io/gpuweb/#dom-gpuobjectbase-device-slot).[[[limits]]](https://gpuweb.github.io/gpuweb/#dom-device-limits-slot)." so I assume that will be enough for argument buffers.

That's a a different thing; that limit is across the whole pipeline layout.

If we assume that each bind group is backed by an argument buffer, then Metal needs 2 things:
1. A limit on the total number of bind groups visible to a shader stage - this corresponds to the "Maximum number of entries in the buffer argument table, per graphics or compute function" row in the [Metal feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf). It might be okay to pessimize a bit here and use the [`maxBindGroups`](https://gpuweb.github.io/gpuweb/#dom-supported-limits-maxbindgroups) limit, but it would be great if we could do a little better here.
2. A limit on the number of resources of each kind inside each bind group - this corresponds to the "Maximum number of *** inside an argument buffer" row in the [Metal feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf).

So, in Metal, if you're allowed 31 bind groups per shader stage, and each bind group can hold 31 buffers, that would allow a WebGPU program to use 961 buffers in total (per shader stage). However, we can't just set [`maxUniformBuffersPerShaderStage`](https://gpuweb.github.io/gpuweb/#dom-supported-limits-maxuniformbufferspershaderstage) to 961, because you only can use that amount if you balance your buffers across bind groups properly.

**Comment by litherum** [comment]
Also, sampled textures and storage textures count against the same Metal limit. Also, storage buffers and uniform buffers count against the same Metal limit too.

**Comment by litherum** [comment]
How come we have a `maxVertexBuffers` limit but not a `maxRenderTargets` limit?

**Comment by litherum** [comment]
We also have different rows for the maximum number of inter shader stage inputs vs inter shader stage components, which is also a bit unfortunate to have to pessimize.

**Comment by Kangz** [comment]
> How come we have a maxVertexBuffers limit but not a maxRenderTargets limit?

The value 8 is hardcoded, it wasn't clear if it should be configurable or not, see https://github.com/gpuweb/gpuweb/issues/1865

> We also have different rows for the maximum number of inter shader stage inputs vs inter shader stage components, which is also a bit unfortunate to have to pessimize.

See https://github.com/gpuweb/gpuweb/issues/2400 and https://github.com/gpuweb/gpuweb/issues/1962 Keeping the vector limit means we'd need to be pessimizing some cases. Keeping only the components limit means that compilers will need to back components together (and there's issues with interpolation likely). I think some people surfaced that we should probably be pessimizing.

> A limit on the total number of bind groups visible to a shader stage - this corresponds to the "Maximum number of entries in the buffer argument table, per graphics or compute function" row in the [Metal feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf). It might be okay to pessimize a bit here and use the [maxBindGroups](https://gpuweb.github.io/gpuweb/#dom-supported-limits-maxbindgroups) limit, but it would be great if we could do a little better here.

How is `maxBindGroups` pessimizing? If it's because it is not per shader stage, this is ok because each binding in bindgroups are per shader stage.

> A limit on the number of resources of each kind inside each bind group - this corresponds to the "Maximum number of *** inside an argument buffer" row in the [Metal feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf).

Ah that explains it. Is it a breaking change  to add limits per bindgroup later? Either way we can easily add it, it just makes the limit more soup but might be necessary anyway.

**Comment by kainino0x** [comment]
> The value 8 is hardcoded, it wasn't clear if it should be configurable or not, see #1865

I keep forgetting about this, but I want to go ahead and add a limit for it even if we don't make it configurable. E.g. we have alignment limits that we may or may not ever relax but they're already there now.

**Comment by kainino0x** [comment]
> Is it a breaking change to add limits per bindgroup later? Either way we can easily add it, it just makes the limit more soup but might be necessary anyway.

Adding any limit is breaking (or would have to somehow be "opt in"). So ideally we get all the limits in for v1.

**Comment by kainino0x** [comment]
meeting: everyone happy with the direction, @litherum to work out details. If they turn out to be more complicated than expected, we'll bring it back to the group, otherwise I'm marking this as editorial.

**Comment by litherum** [comment]
“Editorial” isn’t quite right… it’s a normative change which will result in software being written in implementations

**Comment by litherum** [comment]
I think I've worked out the details in my brain, but it leads to this: https://github.com/gpuweb/gpuweb/issues/3787

**Comment by kainino0x** [comment]
Removing editorial label as this issue has become no-longer-resolved

**Comment by kainino0x** [comment]
To summarize the issue here:

- The pre-argument-buffers implementation strategy means the maximum number of buffers of any kind (bindings or vertex buffers) bound to a stage is 31. We decided not to have an extra combined-limit for these, so instead implementations must choose adapter limits such that they sum to &le; 31. This is currently described in https://gpuweb.github.io/gpuweb/correspondence/
- The post-argument-buffers strategy backs each GPUBindGroup with one argument buffer. Thus that limitation becomes obsolete, and instead the limit of 31 buffers becomes the number of bind groups + number of vertex buffers. We decided to add a combined limit here because eventually all implementations will assume argument buffer support and likely switch to this strategy.

In order for the post-argument-buffers strategy to work, the combined number of vertex buffers and bind groups bound at once to a Metal encoder must not be greater than 31 (minus any reserved by the implementation), and more specifically must know which thing to bind to each index from `0` to `30`. The discussion in #3787 goes into a bit more detail. Here are the ways to achieve this that I've managed to collect so far:

- 0) Statically decide adapter limits such that `maxVertexBuffers` + `maxBindGroups` &le; 31.
    - Pros: No runtime cost, simple, don't actually need a combined limit.
    - Cons: Applications can't take advantage of the actual Metal device limits.
- 1) Let applications pick their distribution between these two limits at requestDevice.
    - Pros: No runtime cost.
    - Cons: Bad for composability. There's no "maximally capable" device for a given adapter. Still can't fully take advantage of the actual Metal device limits.
- 2a) Defer setting bind groups and vertex buffers on the backend, lazily apply them when it's known which ones are used (at draw/dispatch).
    - Pros: Solves issues above.
    - Cons: Additional latency for issuing Metal commands, additional implementation code to queue these up, some runtime cost of queuing up and then flushing updates.
- 2b) Statically allocate some number of each (say, 15 for each) and then use option 2a for any beyond that.
    - Pros: Lazy binding won't be hit very often, so reduced latency and flushing cost.
    - Cons: Still additional code, still some latency and runtime cost.
- 3) #3787: add validation to `setBindGroup()` and `setVertexBuffer()` that check there aren't more than 31 bindings across both. Add a way to unbind both.
    - Pros: Slightly less implementation code than 2a/2b.
    - Cons: Some additional runtime cost in super hot functions (though low I think - just keep bitsets and [count the number of bits set](https://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetNaive) across both). Additional statefulness - bad for composability because a piece of code might need to go through and pessimistically wipe bindings just in case they were used previously (like GL state restoration), though avoidable with render bundles? Finally, I'm not sure this is actually possible? https://github.com/gpuweb/gpuweb/issues/3787#issuecomment-1414758823

**Comment by magcius** [comment]
I feel like ascribing magic to the maximum bound index is a bit goofy if we're imagining this as a sparse set of locations.

Solution 0 does not feel too constraining, I think you'll be hard-pressed to find an app that has more than 16 combined vertex buffers + buffers bindings.

**Comment by kainino0x** [comment]
> I feel like ascribing magic to the maximum bound index is a bit goofy if we're imagining this as a sparse set of locations.

It's sparse but the index values already can't go past the limit. So I don't think it's goofier than what we have now.

That said - as I've said in the meeting - I also think solution 0 is the way to go.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#">GPU Web F2F 2023-02-16/17</a></summary>

    maxBuffersPlusVertexBuffersForVertexStage limit [#2749](https://github.com/gpuweb/gpuweb/issues/2749) [Myles, Brandon]

* MM: maxBindGroupsPlusVertexBuffersForVertexStage is what I'm proposing.
* MM: if we can't agree on "bind groups" + "vertex buffers" then maybe not worth discussing?
* CW: counterpoint: when you have a pipeline, you know where that boundary between the two kinds of resources is. Can remove the unused vertex buffers.
* MM: problem with that - would like to set a bind group before you set a pipeline.
* KG: did we consider save/restore?
* MM: think that'd fit the bill. Seems reasonable.
* KG: I want to use unbinding for save/restore.
* MM: we have this implicitly - bundles.
* BJ: doesn't do that. Causes a state clear.
* MM: state clear would also fit the bill.
* KG: can you enqueue a render bundle?
* CW: executing 0 render bundles probably does this. :)
* MM: can we make a shorthand function? clearEncoderState?
* KG: think it'd be nicer to have a save/restore.
* BJ: the way you'd get there - a way to reflect back what the state is. Not too much attached to encoders. Current bind groups, buffers, pipeline. Then you can build that save/restore yourself more easily than in say OpenGL. Probably the desired direction. I still question the utility a little bit. You mentioned libraries that don't mess with your state, and I appreciate that.
* CW: had some ideas about save/restore, but not the right time to discuss in too much detail.
* KG: idea of clearing encoder state.
* CW: there's still the same thing. More work for the impl to do this thing itself. Very tractable amount of work to track the number of things you need to apply, and do so at draw time. Yes, setBindGroup should have proportionate cost. It's across the IPC boundary. Draw call is close by. Drivers probably have dirty bits for this.
* CW: if you don't do this, then when you do a draw, have to recheck BGLs match the pipeline. Don't want to revalidate BGL.
* MM: don't need to defer anything, just need a bit.
* CW: exactly. Here you'd have a bit as well.
* MM: what's the meaning of the bit?
* CW: the pipeline has changed, so you need to recompute where the boundary between vertex buffers and bind groups is.
* MM: then, have to rebind everything. That's what I'm trying to avoid.
* KN: why?
* MM: don't know how to make progress.
* CW: saying this would be more than a Metal setVertexStageBuffer?
* KN: BGs come from one end, VBs from the other.
* CW: what's the concern? setVertexBuffer can result in more than one call to setVertexBuffer in Metal?
* MM: yes, exactly. Trying to avoid - multiple binds, then they set the pipeline, then they draw.
* CW: then they set another pipeline and draw.
* &lt;discussion>
* BJ: this seems like a problem that'll vanish once we have bindless, for example.
* MM: for some definition of "vanish". :)
* BJ: don't know how far out that is. Seems like something that can be addressed via some feature or extension. Less problematic once bindless is there. Is it problematic to start off with the stricter limits, and allow it to become more flexible down the road?
* KN: if we need this limit, need to add it for V1. Need to check it. If every impl ships it, and it's the sum of the other two, would still have the problem.
* CW: would like to keep the full hour to talk with Intel Shanghai. We can re-discuss this issue.

</details>

**Comment by kainino0x** [comment]
> CW: **Resolved:** New limit, draw time validation, setVB(null) resets, can pass garbage for offset/size (no validation), setBG(null) too.
