### ISSUE TITLE
GPUExternalTexture [[active_imports]] only works if there are RAFs

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2785]
Right now GPUExternalTextures are guaranteed to be valid until the end of the next RAF. This might cause issues for example for backgrounded tabs that don't run RAFs. I kind of remember this issue being brought up before but I don't see any open issue for it, so here it is.

I suggest that we change this to say that GPUExternalTexture may only change `expired` at microtask boundary. Such that if you check a GPUExternalTexture expiredness and submit it in the same microtask, things are guaranteed to work.

CC @shaoboyan @kainino0x

**Comment by shaoboyan** [comment]
>I suggest that we change this to say that GPUExternalTexture may only change expired at microtask boundary. Such that if you check a GPUExternalTexture expiredness and submit it in the same microtask, things are guaranteed to work.

I think what you suggested here is the working model that _"Enqueue a microtask to check whether GPUExternalTexture expired could be changed after importExternalTexture()"_.  I think it could resolve rAF issue in spec.
And there is another question. What is the correct time to expire a GPUExternalTexture if the imported video source doesn't submitted a new video frame for a long time (e.g. paused)
For example, I'm not sure whether the microtask proposal could resolve the situation that HTMLVideoElement is in the backgrounded tabs and has been paused.

**Comment by Kangz** [comment]
> I think what you suggested here is the working model that "Enqueue a microtask to check whether GPUExternalTexture expired could be changed after importExternalTexture()".

Not exactly, it doesn't specify which micro task would expire the texture because we don't want to force expire right after the `importExternalTexture`. It just guarantees to the application that it can check the external texture is not expired, then do a large microtask and know it's not going to expire in the meantime.

> What is the correct time to expire a GPUExternalTexture if the imported video source doesn't submitted a new video frame for a long time (e.g. paused)

Never while the video is paused I guess?

> I think we should destroy all GPUExternalTexture when GPUDevice is destroyed at least.

Spec-wise I don't know (whether device.destroy() causes all isExpired to be true), but implementations are always free to do that, since it is no longer possible to use the texture after device destruction.

**Comment by kainino0x** [comment]
I reread the HTML spec a bit and realized I don't think this is a problem as specced.
We insert our auto-expire steps:
https://gpuweb.github.io/gpuweb/#abstract-opdef-expire-stale-external-textures
into the "Update the rendering" steps here, just before "run the animation frame callbacks" (currently step 13):
https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering

Note that the existing steps all say "For each fully active Document in docs". This is what filters out background tabs (see steps 4 and 5).
Our new step does NOT say that; it will always run even if the tab is backgrounded.
Note we don't even mention any `Document` objects because we maintain our own `[[active_imports]]` list which is not tied to any document (we don't care which document the `<video>` is in, if any).

**Comment by Kangz** [comment]
Wasn't there a concern that a backgrounded tab might still be consuming a video (for the audio for example) but not run RAF because it is backgrounded, in which case a very outdated frame could stay unexpired? Happy to say this isn't a problem and close this issue. But just want to make sure.

**Comment by kainino0x** [comment]
That's what I was saying I didn't think was a problem. But the HTML spec here is pretty complicated and it's possible the event loop can get paused anyway. Specifically I'm now realizing that step 8.3, which basically does a "wait for idle", could introduce a long stall? But I'm pretty sure that any browser that needs to expire things quickly will be within spec to do so, with the spec as written today. That is to say, either:

- The page is doing stuff, so the page is not completely idle, so "Update the rendering" will keep running and we'll keep expiring textures.
- The page is doing nothing and can't observe whether textures get expired earlier or later.

**Comment by kainino0x** [comment]
I asked Domenic about this, as promised. What I learned (if I understood correctly):

- The processing model never pauses for more than a few ms, so there's no concern about our step being reached promptly. I'm still pretty sure nothing stops our step from running when no documents are visible.
- Pages can go into the "bfcache", e.g. when you navigate away from a page (pagehide) and then back (pageshow), the page may just resume where it left off instead of reloading. This shouldn't affect us: I think(?) the processing model keeps running - but is interesting to know about.
- There's a similar thing with "render-blocked" pages which I think is fine for the same reason.
- The current spec expires textures right between a bunch of event handlers and the requestAnimationFrame callbacks, which is fine but probably keeps the texture alive for more parts of the processing loop than necessary. #2855 moves it earlier, rationale explained there.

**Comment by Kangz** [comment]
[Consensus last meeting](https://github.com/gpuweb/gpuweb/wiki/Minutes-2022-05-11#gpuexternaltexture-active_imports-only-works-if-there-are-rafs-2785) was that it was ok (and a good thing) to move the invalidation earlier. Moving to editorial (since all it needs is spec).

**Comment by kainino0x** [comment]
fixed in #2855
