### ISSUE TITLE
Referencing the Unicode Standard

### ISSUE THREAD

**Issue by xfq** [gpuweb/gpuweb#2829]
https://gpuweb.github.io/gpuweb/wgsl/#identifiers

> The form of an identifier is based on the [Unicode Standard Annex #31](https://www.unicode.org/reports/tr31/tr31-35.html#unicode-standard-annex-31-for-unicode-version-1400) for [Unicode Version 14.0.0](https://gpuweb.github.io/gpuweb/wgsl/#biblio-unicodeversion14), with the following elaborations.

> [Unicode Character Database for Unicode Version 14.0.0](https://www.unicode.org/Public/14.0.0/ucd/DerivedCoreProperties.txt#unicode-character-database-for-unicode-version-1400) includes non-normative listing with all valid code points of both [XID_Start](https://www.unicode.org/reports/tr31/tr31-35.html#Table_Lexical_Classes_for_Identifiers) and [XID_Continue](https://www.unicode.org/reports/tr31/tr31-35.html#Table_Lexical_Classes_for_Identifiers).

The i18n WG generally recommends referencing the Unicode Standard directly rather than including a version number, especially in the body text of a spec. Why is Unicode v14 specified here?

**Comment by mehmetoguzderin** [comment]
The i18n Best Practices document, in https://w3c.github.io/bp-i18n-specdev/#char_unicoderef section, says that:

> A generic reference to the Unicode Standard MUST be made if it is desired that characters allocated after a specification is published are usable with that specification. A specific reference to the Unicode Standard MAY be included to ensure that functionality depending on a particular version is available and will not change over time.

In the first sentence, the conditional clause is primarily relevant to us here. Although the group eventually did not use Immutable Identifiers, where generic Unicode references would always mean the same data, it was, and I believe still is, a present desire to have a specific, versioned set associated with our spec. There were many considerations, ranging from tooling to runtime detection. Furthermore, except for JavaScript, most prior art to our Unicode identifier support practically is versioned:
- Python versions through its unicodedata module, which pins to version 13 as of Python 3.10 (the next release will be Unicode version 14).
- Perl versions through its perluniprops module, which pins to version 13 at Perl 5.34.1.
- Rust directly specifies version 13.
- Go derives from version 13 but does not specify the constraint anywhere except for the literal in the source code.

In addition, all current WGSL implementations effectively derive their tables as compact and embeddable Unicode data was a primary goal. In Tint, they have their tables, and in Naga, their dependency, the de-facto XID crate in the Rust ecosystem, just recently updated to Unicode 14.

I think WGSL could intend to be specific about the version. Otherwise, one obvious choice is to have the generic reference and inherit it from JavaScript.

cc: @dneto0 @litherum @kdashg @ben-clayton @jimblandy

**Comment by dneto0** [comment]
The CTS will test specific cases, and those should match the WGSL spec, and that should be specific.

If WGSL should evolve with new versions of Unicode, then we'll update its spec and CTS.

**Comment by xfq** [comment]
> We believe we'd like to keep the unversioned reference for now, and fix it later if it's a problem.

Sorry, you said you would like to keep the ***unversioned*** reference, but in the document it's still the ***versioned*** reference. Am I missing something?

**Comment by kdashg** [comment]
Sorry, yes, keep the versioned reference.

**Comment by r12a** [comment]
@kdashg I wasn't completely sure, after reading the discussion notes, whether the group is aware that the current version of Unicode is 15, rather than 14.  Does that change the intended reference?
