### ISSUE TITLE
Uniformity analysis of local variables

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#2859]
The uniformity analysis relies on having value nodes to represent local variables (function variables). The expression tables describe these nodes generally as:
>X is the node corresponding to "x"

For LHS expressions, the result node is also `X`.

This seems to imply, but there is a single node for each variable, but that modelling is overly conservative in our opinion. For example:
```
fn foo() -> i32 {
  var x : i32 = non_uniform_val;
  x = uniform_val;
  return x;
}
```
In the above example, the initial value assignment would pollute the value of `x` for the whole function if the analysis used a single node. A better modelling (intended I think, but not well described) would be that value node for a variable depends on where it is accessed in the program. We believe this is the better direction to take even though it is more complicated. 

What about control flow?
```
fn foo() {
  var x = 1;
  if (non_uniform_cond) {
    x = a;
  } else {
    x = b;
  }
  let y = x;
}
```
In the above example, `x` is non-uniform in and after the if, but the more  interesting question is what node should the reference to `x` use in the assignment to `y`? This becomes very similar to generating SSA values, that is, there is an effective node for `x` after the if that would have edges to both assignments within the if statement.

Local variables with composite types are further not well described assuming a program flow style of nodes. For scalar values, it is always obvious that the new value completely replaces the old value, but for composites it is more complicated. For example:

```
fn foo() {
  var x = vec3(1, 2, 3);
  x.x = non_uniform_value;
  x.y = uniform_value;
}
```
In the above example, is `x` uniform after the `x.x` assignment? Certainly not, but what about after the `x.y` assignment? The second component is, but `x` as a whole is not. If the node for the value of `x` is different depending on the flow, then we think composite assignments should get an edge to the last "current" value of the variable (e.g. `x.y` assignment in this example).

A final question then becomes should we have special cases for certain statement behaviours. For example:
```
fn foo() {
  var x = non_uniform_value;
  if (uniform_cond) {
    x = uniform_value;
  } else {
    return;
  }
  if (x == 0) {
    workgroupBarrier();
  }
}
```
Tint's in progress implementation can handle this case by examining whether the statements include the `Next` behaviour. This allows it to be more precise, but we don't have internal consensus on whether the analysis should be required to support this example. There is an expectation that it might be difficult to describe in the spec in a section that is already very dense.

We are raising this issue to get consensus on some of these issues before attempting to write spec text for any of them. So feedback welcome.

-----
Decisions:
- [ ] Single node for variables vs program flow style
- [ ] Aggregates access and assignment
- [ ] Special cases for behaviour

cc @jrprice

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-17-minutes#uniformity-analysis-of-local-variables-2859">WGSL meeting minutes 2022-05-17</a></summary>



* AB: JP implemented uniformity analysis in Tint and we had a lot of discussion about meanings. A lot focusing on if you ref a local variable it doesn’t say in the spec, it may mean a single node with errors to and from but if you override variable by putting a non-uniform it’s dirty’ed for the rest of the function. Could do data flow analysis and keep better track. That’s what Tint does as we thought it was right thing. Tried to jot down what we came up against and break down to making decisions before spec’ing to get consensus that’s how we should treat it . Should we treat values as having a data flow like model. If aggregate value, in spec if ref to variable alone, even into field, we think it’s OK to pollute everything. Not too many cases where you would be concerned. 2 builtin values that are uniform. Could add a note about splitting into separate input param where uniform ones are by themselves and analysis could handle. Easy enough to be split. Last one is how smart for data flow analysis. We haven’t defined it yet we have options for conservative or not. Some examples for each.
* JB: These are all matters of resolution. Granularity of analysis. Is it var related or assignment that we relate or do something more specific. Most concerned is that we write down and put into spec. Don’t think we should have different implementations. One gives lots of uniform values and other doesn’t. Don’t want to end up in that situation. Whatever we do it all has to be written down. How hard do we want to work, how much memory and time.
* AB: Agree
* JB: Analysis is what makes frontends slow/expensive.
* JP: When landed saw a 10-20% perf hit on frontend. No effort to make fast, just to make work.
* KG: LIke number of things, called out feels like generating SSA values. Like that polluting aggregates is a good place to stop trying to be smarter. Think polluting aggregates is fine and if folks want can do like said. Can override non-uniform with uniform uniformly and have  a deadzone of uniformity where it’s non-uniform and then uniform feels weirder. Wonder if it’s both simpler and tolerable to say if you want it uniform make a new variable.
* AB: That’s an option.
* KG: You already did the hard thing?
* AB: We did. With new thing didn’t want to phase in extra warnings and errors. Not as well spelled out so guessing as intent. We attempted to be as helpful as we could. Forcing to not-rename to a temp variable didn’t feel as helpful vs knowing what hte value is and what control flow nodes associated with. JP can comment on complexity. Didn’t seem terrible but not easiest thing to take away from spec, lots of text needed
* KG: And examples
* AB: Those would be helpful
* KG: Some probably omes down to implementation complexity. Don’t have a good feeling fro in Naga
* JB: Going to be a bit weird. Have identifiers for expressions, good place for metadata, for statements have tree. Rust doesn’t like pointing into other things. Wondering about that. We’re going to have to do it for other reasons, but change, but one of several. Not more concerned then about other things.
* KG: Would like to hear from apple also. Let’s not resolve until Apple weighs in. But sounds good. Modulo hearing from Apple, consensus is we can try to do this and see if we fall short or if it’s too hard.


</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-31-minutes#uniformity-analysis-of-local-variables-2859">WGSL meeting minutes 2022-05-31</a></summary>



* MM: Bunch of examples here. We discussed examples on team but not larger principles. Could go through examples and talk about each one?
* KG: Think so, leads towards solution.
* MM: For first, RM made uniformity every var either runiform or non. Scope is entire variable. If ever write uniform or non-uniform then the variable takes that attribute. Discussed months ago splitting the lifetime for when it is and isn't' uniform. Reason didn’t do that was simplicity. Didn’t think better or worse, could split if we need to do that. Question of where you split. If you split at every write the graph gets bigger, maybe ok maybe not. For first example ambivalence from us if real authors think split lifetime is needed we can do that but don’t have opinions.
* KG: Because they can just use a new variable?
* MM: In trivial cases, yes. Haven’t made proof you can always make new var. If write is inside condition then new var has to be hoisted. Not confident for every case, but maybe true.
* DN: Our experience, JP said could do precise thing and impl was fast. No worse then what already have to do to understand dataflow. We think it’s a net benefit for users and is better to handle for them. We want to do the more precise analysis.
* MM: Split lifetime at each write?
* DN: Yes at every write and any time you exit control flow you get values together (PHis in SSA). If assign in condition you re-analyze outside the condition.
* MM: So if the condition is uniform and inside the then you write and the value is uniform and the value was uniform before then you’re phi is between uniforms then you’re uniform but if any of those was non-uniform you’re non-uniform
* DN: That’s my understanding
* MM: Works for me if we’re ok of the graph getting bigger
* KG: just graph size. What about composites? If I”m write tint stops short of re-unifying composites
* DN: Poison one component the whole thing is poisoned
* AB: That was due to ???
* MM: Good initial position, if authors want more we can talk about it. Good story if you want parts uniform and parts non-uniform in struct then either split the struct or make 2 structs and only pay attention to half.
* KG: **Think we have loose and cautious consensus to try it this way. Resolved**.


</details>
