### ISSUE TITLE
Encoder results reuse

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#286]
Metal has [Indirect Command Buffers](https://developer.apple.com/documentation/metal/advanced_command_setup/encoding_indirect_command_buffers_on_the_cpu). Direct3D 12 has [Bundles](https://docs.microsoft.com/en-us/windows/desktop/direct3d12/recording-command-lists-and-bundles). Vulkan has [secondary command buffers](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#commandbuffers-secondary).

Unfortunately, not all hardware supports these facilities directly. Metal indirect command buffers are behind the MTLFeatureSet_macOS_GPUFamily2_v1 and MTLFeatureSet_iOS_GPUFamily3_v4 feature sets. From the [docs](https://developer.apple.com/documentation/metal/mtlfeatureset), this looks like iPhone 6s and later and most Macs from 2016 or later.

It is, of course, possible to emulate this functionality by "recording" commands into a browser-owned log, and then "executing" the commands by running through the log and issuing the commands directly. Presumably this would cost significant performance, as otherwise the feature wouldn't exist in the 3D APIs directly.

Inside an indirect command buffer, Metal doesn't allow compute commands. For rendering commands, it [supports](https://developer.apple.com/documentation/metal/mtlindirectrendercommand):
- Draw calls
- Setting buffers (this includes argument buffers, which can include references to textures / samplers)
- Setting the pipeline state object

Inside a Bundle, Direct3D 12 [supports everything except](https://docs.microsoft.com/en-us/windows/desktop/direct3d12/recording-command-lists-and-bundles#bundle-restrictions):
- Any Clear method
- Any Copy method
- DiscardResource
- ExecuteBundle
- ResourceBarrier
- ResolveSubresource
- SetPredication
- BeginQuery
- EndQuery
- SOSetTargets
- OMSetRenderTargets
- RSSetViewports
- RSSetScissorRects
- SetDescriptorHeaps

[From my reading](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkSubpassContents), Vulkan secondary command buffers can record any command, but a subpass that `vkCmdExecuteCommands(secondaryCommandBuffer)` isn't allowed to do anything except call `vkCmdExecuteCommands()`. Presumably this means a secondary command buffer can't change the render target either.

**Comment by litherum** [comment]
We should also investigate how the recorded commands can be tweaked.

In Metal, when you create an Indirect Command Buffer, you can specify whether or not the bound buffers or the pipeline state object should be inherited from the calling command buffer. This means it's possible to run the same Indirect Command Buffer from a different context, and get a different result, without giving up performance.

**Comment by kvark** [comment]
@litherum thank you for the investigation!
It looks like a good opportunity for us to expose an API that is basically an intersection of these mechanics. This would be mimicking Metal's indirect command buffers:
  - ability to draw()
  - set pipeline
  - set bind groups

The baked object would be executable from within a render pass encoder.

We would natively support it on D3D12, Vulkan, and those Metal devices that have ICB. For platforms without native support, there is still a benefit to be extracted from baking these commands: less javascript overhead when re-recording something, and the implementation would have easier time validating (since part of the work related to the contents of that ICB can be validated ahead of time).

> This means it's possible to run the same Indirect Command Buffer from a different context, and get a different result, without giving up performance.

I wonder, is there any benefit in *not* permitting inheritance of the pipeline state objects and resources on Metal from the render pass encoder an ICB is executed from?

**Comment by Kangz** [comment]
Thanks indeed @litherum. Likewise I think there is value in having reusable command buffers if only for the CPU overhead of validation and JS. Note that in practice any form of command buffer reuse may need some patching of the command buffer from drivers for a variety of reasons.

@kvark, for render passes encoder SCBs do you mean to also have setVertexBuffers?

While SCBs in render passes would get us 80% of the useful cases of command buffer reuses, I think we should still have top-level command buffer reuse even if it isn't a thing in some of the underlying APIs.

**Comment by kvark** [comment]
@Kangz good point about `setVertexBuffers`. It should be in the list of stuff in our WebGPU bundles.

**Comment by kainino0x** [comment]
I think it is critical that we not limit our reuse to the reuse allowed in underlying APIs. We must not underestimate the cost of JS bindings, translating descriptor objects and strings, the process boundary, and validation. I'm pretty sure these massively outweigh the cost of re-recording in native for the foreseeable future.

**Comment by kvark** [comment]
@kainino0x it would help if we had any benchmarks/metrics on the table to see what the savings are (re: JS overhead of re-recording)

**Comment by kainino0x** [comment]
Anecdotally, see the sidebyside comparison video here:
https://medium.com/@babylonjs/webgpu-is-coming-to-babylon-js-c44f8065ac05

Without command buffer reuse, the performance was ~similar to WebGL.

**Comment by austinEng** [comment]
I did some traces of a port of Animometer to WebGPU to provide some data to this discussion.
This test just creates a render pass and then calls `setBindGroup(...); draw(...);` 10,000 times. I injected tracing events to BeginRenderPass() and EndPass() so there's only tracing overhead twice per frame: once at the beginning and once at the end of a pass. What we want to pay attention to here is the time it takes to record a render pass.

|       | Record render pass (ms) | Fill MTL command buffer (ms) |
|  --  |--| -- |
| 10k triangles | 2.96 | 1.15 |
| 10k triangles (command buffer reuse) | 0 | 1.15 |
| 10k triangles (JS bindings only) | **2.12** | N/A (doesn't draw) |

Note that the time to record the commands from Javascript even if calls to the actual implementation are removed is 2.118 ms. This measures just the cost of the bindings (no allocation or encoding into Chromium's command buffer). Whereas the time to convert our serialized format to a MTL command buffer is 1.15 ms. This means that **even single-process implementations would be able to submit commands twice as fast by reusing a command buffer instead of re-recording from Javascript**.

For Chromium, end-to-end, this means that command buffer reuse lets us do ~160,000 individual `setBindGroup(...); draw(...);` per frame at 60fps. Without command buffer reuse, we can only do ~30,000 at 60fps.

*Screenshots of relevant traces below:*

**WebGPU Animometer with 10,000 draws**
<img width="1680" alt="webgpu_animometer_10k" src="https://user-images.githubusercontent.com/2154796/57659210-59951f00-7596-11e9-9ca1-1a7e151cddfe.png">

**WebGPU Animometer with 10,000 draws and command buffer reuse**
<img width="1680" alt="webgpu_animometer_10k_reuse" src="https://user-images.githubusercontent.com/2154796/57659211-59951f00-7596-11e9-821a-42045a1669d3.png">

**WebGPU Animometer with calls to implementation removed (Javascript bindings only)**
(still calls setRenderPipeline + setVertexBuffers)
<img width="1680" alt="webgpu_animometer_10k_passthrough" src="https://user-images.githubusercontent.com/2154796/57659212-5a2db580-7596-11e9-8a6e-915d91ce81bd.png">

**Comment by grovesNL** [comment]
I guess one issue with always rerecording in native is that under certain conditions bundles could be optimized further (i.e. become native bundles). So users could hit hidden fast paths just by omitting a certain command, which could be a bit too magical.

Regardless I think we should attempt to reduce the overhead of JS bindings as implementations progress further, either internally where possible or at the API level. The overhead measured above seems relatively high. For example, consider opaque handles for some reusable objects instead of plain JS objects, ensure string interning is actually occurring or reconsider usage of string values as discussed previously, avoid re-validating when possible, more efficient serialization in implementations, etc.

**Comment by kvark** [comment]
Comparison of API capabilities (within a render pass) with the subject:

| command                | Vk SCB  | DX12 Bundle | Metal ICB |
| ---------------------- | --------- | --------------- | ----------- |
| draw                        | V           | V                   | V              |
| drawIndirect            | V           | V                   | V              |
| setPipeline               | V           | V                   | V              |
| setBindGroup           | V           | V                   | V              |
| setVertexBuffers      | V           | V                   | V              |
| setIndexBuffer         | V           | V                   | V              |
| setBlendColor          | V           | V                   |                |
| setStencilReference | V           | V                   |                |
| setScissor                | V           |                      |                |
| setViewport             |  V           |                      |                |
| *reusable*               | V?          | V                   | V             |

Note: in Vulkan, re-usability of secondary command buffers is controlled by a flag (specified when you start recording it) and it affects how much the driver tries to optimize the command stream for fast execution on GPU.
