### ISSUE TITLE
Relax the null buffer check for zero-attribute vertex buffers in "valid to draw with GPURenderCommandsMixin" 

### ISSUE THREAD

**Issue by takahirox** [gpuweb/gpuweb#2864]
From: https://dawn-review.googlesource.com/c/dawn/+/89340

Currently the validation of drawing with [GPURenderCommandsMixin](https://www.w3.org/TR/webgpu/#gpurendercommandsmixin) encoder in WebGPU [spec](https://www.w3.org/TR/webgpu/#abstract-opdef-valid-to-draw) requires

> * For each GPUIndex32 slot 0 to pipelineDescriptor.vertex.buffers.length:
>   * If pipelineDescriptor.vertex.buffers[slot] is not null, encoder.[[vertex_buffers]] must [=map/contain=] |slot|.
 
And validating [GPUVertexBufferLayout](https://www.w3.org/TR/webgpu/#dictdef-gpuvertexbufferlayout) in the [spec](https://www.w3.org/TR/webgpu/#abstract-opdef-validating-gpuvertexbufferlayout) doesn't state zero-attribute buffer should be ignored.

So, buffers must be set even for zero-attribute vertex buffer slots with [GPURenderCommandsMixin.setVertexBuffer()](https://www.w3.org/TR/webgpu/#dom-gpurendercommandsmixin-setvertexbuffer). But this may sound a bit weird because buffers are not used in practice.

It may be worth to consider to relax the validation of drawing with [GPURenderCommandsMixin](https://www.w3.org/TR/webgpu/#gpurendercommandsmixin) encoder to skip the null buffer check for zero-attribute vertex buffer slots.

> * For each GPUIndex32 slot 0 to pipelineDescriptor.vertex.buffers.length:
>   * If pipelineDescriptor.vertex.buffers[slot] is not null and pipelineDescriptor.vertex.buffers[slot].attributes.length is not zero, encoder.[[vertex_buffers]] must [=map/contain=] |slot|.

**Comment by kainino0x** [comment]
Editors+Myles discussion:
- Special casing this in the draw-time validation doesn't seem necessary. It seems like a fairly rare corner case, and it's easy to fix on the app side.
- Extra draw-time validation would require implementations to write an optimization (under the "as if" rule, they'd pre-normalize these so they don't have to check twice at draw time)
- We're confused about the goal of this change, because the original issue seems to be about render pipeline creation, not draw-time validation.

[After the editors call]
From reading the Dawn context link, it seems the problem is that WebGPU distinguishes between having no attributes, and having a hole in the vertex buffers array, while webgpu.h doesn't have a way to express that. We want webgpu.h and WebGPU to be equally expressive, so either both should distinguish them, or neither should. This PR just papers over the difference.

So I think we need to discuss a change in createRenderPipeline on one side or the other. Either:

1. Find an alternate way for webgpu.h to express a hole in the vertex buffer array
2. Validate `attributes` isn't allowed to have length 0, [here](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuvertexbufferlayout)
3. Normalize the [descriptor](https://gpuweb.github.io/gpuweb/#dom-gpurenderpipeline-descriptor-slot) during creation so that if `attributes` is empty, the vertex buffer entry gets dropped.

 I think the WebGPU spec makes sense and we should do option 1. Maybe either a special value for `attributesCount` (`.attributesCount = WGPU_SKIP_VERTEX_SLOT`) or distinguish between `attributes` being `NULL` vs another value?

**Comment by takahirox** [comment]
> it seems the problem is that WebGPU distinguishes between having no attributes, and having a hole in the vertex buffers array, while webgpu.h doesn't have a way to express that.

Yes, the discussion was started from the fact that `webgpu.h` doesn't have a way to express a hole.

> We want webgpu.h and WebGPU to be equally expressive, so either both should distinguish them, or neither should. 

That's nice to update `webgpu.h` to express a hole that can be expressed in WebGPU spec.

> I think the WebGPU spec makes sense and we should do option 1. Maybe either a special value for `attributesCount` (.`attributesCount = WGPU_SKIP_VERTEX_SLOT`) or distinguish between `attributes` being `NULL` vs another value?

Yes, the option 1 sounds good to me. There seems to be some `sequence`s that elements can be nullable in the WebGPU, for example [`GPURenderPassDescriptor.colorAttachments`](https://gpuweb.github.io/gpuweb/#dom-gpurenderpassdescriptor-colorattachments) and [`GPURenderPassLayout.colorFormats`](https://gpuweb.github.io/gpuweb/#dom-gpurenderpasslayout-colorformats)
. How is null (empty, hole) expressed in them? If possible, using the same manner would be good for consistency?

I want to make a PR or CL if we decide the way.

**Comment by Kangz** [comment]
Tagging as "tacit resolution" to not change the spec.

> There seems to be some sequences that elements can be nullable in the WebGPU, for example [GPURenderPassDescriptor.colorAttachments](https://gpuweb.github.io/gpuweb/#dom-gpurenderpassdescriptor-colorattachments) and [GPURenderPassLayout.colorFormats](https://gpuweb.github.io/gpuweb/#dom-gpurenderpasslayout-colorformats). How is null (empty, hole) expressed in them? If possible, using the same manner would be good for consistency?

In `colorAttachments` a null `view` means a hole. In `colorFormats` a `wgpu::TextureFormat::Undefined` means a hole. IMHO we should go with `wgpu::StepMode::VertexBufferNotUsed == wgpu::StepMode::Undefined == 0`.

**Comment by takahirox** [comment]
> In `colorAttachments` a null `view` means a hole. In `colorFormats` a `wgpu::TextureFormat::Undefined` means a hole. 

OK, there doesn't seem to be a consistent expression for a hole in `webgpu.h`. Thanks.

>  IMHO we should go with `wgpu::StepMode::VertexBufferNotUsed == wgpu::StepMode::Undefined == 0`.

I would vote for this.

**Comment by kainino0x** [comment]
> IMHO we should go with `wgpu::StepMode::VertexBufferNotUsed == wgpu::StepMode::Undefined == 0`.

This is getting into webgpu.h so we should move the discussion there. But just wanted to record a thought:
I generally think webgpu.h should use "Undefined" = 0 to mean "use the default as specified in JS" so the APIs match more closely. That way if we ever add more defaulting behavior to WebGPU (e.g. moving the default from IDL into our own text so that we can describe more complex defaulting for future added features) then there's API surface for it.

**Comment by takahirox** [comment]
> This is getting into webgpu.h so we should move the discussion there.

OK, let's move to https://dawn-review.googlesource.com/c/dawn/+/89340 for `webgpu.h` stuffs.

Closing this issue because the suggestion for the spec change doesn't seem to make sense. Thanks for the comments, all.

**Comment by kainino0x** [comment]
Thanks for working out this gap between the API definitions!
