### ISSUE TITLE
integer bit shift by bit width or more

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#289]
What happens when an integer A is shifted by an amount B where B is equal to or greater than the number of bits in A?  This applies to both left shift and right shift. 

C++ has has various answers over time, see https://en.cppreference.com/w/cpp/language/operator_arithmetic#Bitwise_shift_operators 

It's common to say undefined results occur if the shift width is equal or greater to the bit width. SPIR-V does this because it's the common case in ISAs.

What do we want to do here?  
I don't think we have to cater to applications which do use very large shifts, and we can make them slow to make them consistent.  But I'd like to keep the small shifts fast.

**Comment by kvark** [comment]
Triggering a run-time error whenever we encounter such a shift would be rather inconvenient to both implement and handle. I think we should just replace all shifts by a variable with condition:

For example, for `u32 z = x >> s;` we'd generate:
```cpp
u32 z = s >= 32 ? 0 : x >> s;
```
This matches the expected behavior of shifts as they were done sequentially:
```cpp
u32 z = x;
for(u32 i=0; i<s; ++i) {
  z >>= 1;
}
```

The complication doesn't need to apply for shifts that are known constants at compile time though, so hopefully it's a compromise we can live with. I wonder if we can get any data/statistics on the shifts used in, say, Unreal Engine shaders.

P.S. I think having similar modifications is required anyway for stuff like `sqrt()` that would always want to have `abs()` applied to the argument. The difference is that `abs()` is almost free, and the extra condition for shifts may be less free :)

**Comment by dneto0** [comment]
Decided at F2F 2019-05-16:
[Minutes doc](https://docs.google.com/document/d/1HR9vPk48-lhzHAsyF57QzjKMmi0gQHfSXMmyqZuFWkc/edit#)

Implementation behaves as if the shift count is masked with (bitwidth-1).  (e.g. if the bit width is 32 then mask the shift count by 0xFFFF).
This eliminates the overflow cases.

**Comment by kdashg** [comment]
I think this was done in https://github.com/gpuweb/spirv-execution-env/issues/34 .
