### ISSUE TITLE
Confusing languages in technical overview around conversions.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2910]
The `Technical Overview` (https://www.w3.org/TR/WGSL/#technical-overview) section states:

> WGSL does not have implicit conversions or promotions between numeric or boolean types. Converting a value from one numeric or boolean type to another requires an explicit [conversion](https://www.w3.org/TR/WGSL/#conversion-expr), [construction](https://www.w3.org/TR/WGSL/#type-constructor-expr), or [reinterpretation of bits](https://www.w3.org/TR/WGSL/#bitcast-expr). This also applies to vector types.

This raises two questions:

1. How do abstract values fit in, as they are numeric types which do convert to other types.
1. Should the last sentence be `This also applies to matrix and vector types` to make clear that a `f32` matrix won't convert to an `f16` matrix?

**Comment by dneto0** [comment]
+1

1.  This predated abstract numeric types, and wasn't updated
2.  good catch.  This also applies more generally to composites.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-24-minutes#confusing-languages-in-technical-overview-around-conversions-2910">WGSL meeting minutes 2022-05-24</a></summary>



* KG: Not pure editorial? Due to question 1?
* DN: Yea, needs to be qualified for that case. Overview needs to be updated for abstract
* KG: Is it editorial?
* DN: Yes.


</details>
