### ISSUE TITLE
Specify what happens if stencilClearValue > 255

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2921]
It's not clear at the moment if the bits are ignored (I think we should do that) or a validation error.

**Comment by kainino0x** [comment]
I don't even remember if there's a good reason we use `unsigned int` instead of `octet` for [GPUStencilValue](https://gpuweb.github.io/gpuweb/#typedefdef-gpustencilvalue). If there's no good reason to think stencils will ever be more than u8, I'd say just change that.

Ignoring the upper bits would also be fine IMO.

**Comment by kainino0x** [comment]
> I'd say just change that.

to be clear, Metal/Vulkan/D3D12 do use `uint32_t` for stencil. But as a JS API, we can easily change `octet` back to `unsigned int` if we want. C API would probably want to stick to uint32_t.

**Comment by kainino0x** [comment]
I'm OK with either changing the type to `[EnforceRange] octet` or just specifying we take the LSBs.
We could possibly even just remove the `[EnforceRange]` from this type because I think it also takes the LSBs. So we'd be taking the 32 LSBs and then taking the 8 LSBs of the result. But I think best to keep the EnforceRange so that errors are caught when you go outside the safe-integer range (int53).

(Regardless, the C API should keep using uint32_t to match Vulkan and Metal.)
