### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2951]
Can be seen here:
https://github.com/gpuweb/gpuweb/actions/workflows/publish-specs.yml
First instance:
https://github.com/gpuweb/gpuweb/runs/6588654555?check_suite_focus=true#step:4:746

Logs:

```
  [INFO] Build bikeshed document "spec/index.bs" (gh)…
    $ bikeshed --die-on=warning spec "spec/index.bs" "spec/index.bs.built.html" 
      WARNING: Multiple elements have the same ID 'biblio-html'.
      Deduping, but this ID may not be stable across revisions.
       ✘  Did not generate, due to fatal errors
    Failed
  Error: Process completed with exit code 2.
  Error: w3c/spec-prod/v2/action.yml (Line: 113, Col: 24):
  Error: The template is not valid. w3c/spec-prod/v2/action.yml (Line: 113, Col: 24): Error reading JToken from JsonReader. Path '', line 0, position 0.
  Error: w3c/spec-prod/v2/action.yml (Line: 123, Col: 24):
  Error: The template is not valid. w3c/spec-prod/v2/action.yml (Line: 123, Col: 24): Error reading JToken from JsonReader. Path '', line 0, position 0.
  Error: w3c/spec-prod/v2/action.yml (Line: 133, Col: 24):
  Error: The template is not valid. w3c/spec-prod/v2/action.yml (Line: 133, Col: 24): Error reading JToken from JsonReader. Path '', line 0, position 0.
  Error: w3c/spec-prod/v2/action.yml (Line: 144, Col: 24):
  Error: The template is not valid. w3c/spec-prod/v2/action.yml (Line: 144, Col: 24): Error reading JToken from JsonReader. Path '', line 0, position 0.
  Error: w3c/spec-prod/v2/action.yml (Line: 154, Col: 21):
  Error: The template is not valid. w3c/spec-prod/v2/action.yml (Line: 154, Col: 21): Error reading JToken from JsonReader. Path '', line 0, position 0.
  Error: w3c/spec-prod/v2/action.yml (Line: 164, Col: 24):
  Error: The template is not valid. w3c/spec-prod/v2/action.yml (Line: 164, Col: 24): Error reading JToken from JsonReader. Path '', line 0, position 0.
```

**Comment by kainino0x** [comment]
This seems like an issue with spec-prod? @tidoust do you know what's going on?

**Comment by tidoust** [comment]
The spec-prod error messages are confusing but not the root cause of the issue. I raised https://github.com/w3c/spec-prod/issues/137 to track removal of these messages.

The problem is rather with the latest version of Bikeshed that gets confused with the section link to the HTML spec in an informative note and creates an informative reference to HTML on top of the normative one as a result, whereas the normative biblio entry to HTML should win. I reported the problem in https://github.com/tabatkins/bikeshed/issues/2284

I prepared a PR to workaround the problem (and fix a couple of other minor biblio hiccups). It may be worth waiting for a fix in Bikeshed though.

**Comment by kainino0x** [comment]
Thanks for the workarounds! I discovered this late yesterday so didn't have much time to investigate, but I did try to install the latest bikeshed to see if I could repro. Unfortunately something went wrong and I didn't realize I was still using an older version.
