### ISSUE TITLE
maxColorAttachments not sufficient?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#2965]
I noticed recently Metal has 2 limits

1. "max color render targets per render pass descriptor"
2. "max total render target size, per pixel"

So, for example, Apple5 through Apple8 have 8 max color attachments, but max target render size per pixel is 512bits. 8 color attachments with rgba32float, rgba32uint, and rgba32sint, is 1024bits.

In other words, you can render to 8 rgba8uorm but you can't render to 8 rgba32uint

ALSO: `maxColorAttachments` doesn't show up [here](https://www.w3.org/TR/webgpu/#gpu-supportedlimits)

**Comment by Kangz** [comment]
> ALSO: maxColorAttachments doesn't show up [here](https://www.w3.org/TR/webgpu/#gpu-supportedlimits)

That's because until recently we thought that this limit is unlikely to every change, we shouldn't list it. We changed opinions recently AFAIK and the spec doesn't reflect that yet.

> So, for example, Apple5 through Apple8 have 8 max color attachments, but max target render size per pixel is 512bits. 8 color attachments with rgba32float, rgba32uint, and rgba32sint, is 1024bits.

We target A9+, see https://github.com/gpuweb/gpuweb/issues/1069. Though I think this problem is still present on iOS because all  `MTLGPUFamilyAppleN` only support 512. @litherum do we need to add a new limit for this?

**Comment by kainino0x** [comment]
Sounds to me like we do need a new limit. I'm surprised there isn't an equivalent one in Vulkan, I wonder if implementation-defined pipeline creation failures can ever happen due to a similar limit.

> ALSO: `maxColorAttachments` doesn't show up [here](https://www.w3.org/TR/webgpu/#gpu-supportedlimits)

Oops, editorial error. I added it in one place but not the other.

**Comment by kainino0x** [comment]
I started trying to spec this and I realized for multisampling it's not immediately clear whether:
1. The limit is per-sample
2. The limit is per-pixel (so 4x multisampling is 4x the size) but resolve targets aren't counted
3. The limit is per-pixel AND resolve targets are also counted

On ImgTec, the fundamental limitation on the amount of memory inside of a tile (and tiles apparently have a fixed size):
https://docs.imgtec.com/Profiling_and_Optimisations/PerfRec/topics/c_PerfRec_multi_render_targets.html
It's possible the architectural limitations on other devices are similar (and probably Vulkan etc paper over this by allowing spilling as described in that doc).

If that's it, then I think the most likely is interpretation 2.

**Comment by kainino0x** [comment]
Opened tentative #3028

**Comment by litherum** [comment]
On Metal, the limit is per pixel, not per sample. Resolve targets are _not_ counted.

**Comment by litherum** [comment]
Also, the limit on Metal only counts for render targets with a store action that actually stores things.

**Comment by litherum** [comment]
The way it works in Metal is kind of complicated. There are 2 relevant limits:

1. Each pixel has to lie within a maximum number of bytes. This limit is the "Maximum total render target size, per pixel, when using multiple color render targets" row in the [Metal feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf). Each pixel contains one texel from each of the render targets, which may have different formats. Because you're packing data together with different formats, there may be padding between them (e.g. consider one render target that's R32Float, next to another that's R8Unorm). The cost for a multisampled format is the same as the cost as the same format that isn't multisampled, with a handful of exceptions. There is no cost difference between different sample counts (e.g. 2x costs the same as 4x).

2. A tile of the render targets has to fit within thread group memory. The tile size is [user-selectable](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/2866529-tilewidth), but the smallest tile is 16x16. The size of all the texel data (as computed in (1), with padding), times the size of the tile, times the multisampling count, has to be less than the "Maximum total threadgroup memory allocation" limit on the [Metal feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf).

This is complicated enough that I'm willing to simplify this to WebGPU authors (assuming we don't leave too much on the table by pessimizing).

**Comment by kainino0x** [comment]
> 2\. the "Maximum total threadgroup memory allocation" limit

FTR: the possible values here on supported devices (#1069) are 16KiB and 32KiB.

**Comment by kainino0x** [comment]
Options described by Myles in editors meeting:

- No limit, make it an uncategorized error. Editors decided this is not acceptable for portability.
- Pessimize a little bit, e.g. "if you're using this format, you can only use this many targets"
- Make a big table by format (similar to the one we used for #1962) and put it in the spec and say you have to look at that. Still a pessimization but more precise.
- Fully encode all the Metal limits into our spec. (KN: unclear if the limits in the Metal validation layers are futureproof for writing in our spec, since it's not a spec itself)

Myles has ideas for how to describe this in our spec and is going to work on a proposal.

**Comment by kainino0x** [comment]
Also to consider if we drop the Apple3 GPU family (A9/A10) if it would substantially simplify things. IIRC this would let us lift some other limits as well.

**Comment by litherum** [comment]
Looking at this now.

**Comment by litherum** [comment]
I have a proposal for this, but I'm not sure it's correct on older versions of macOS/iOS. I don't want to post it until I'm a bit more confident in it.

**Comment by litherum** [comment]
In the [above post](https://github.com/gpuweb/gpuweb/issues/2965#issuecomment-1158100115), the second limit only kicks in for render passes using tile shaders (which are only available in Apple4 or later). The way we know whether the app intends to use tile shaders is by checking the fields under "Specifying Tile Shading Parameters" in the [documentation for MTLRenderPassDescriptor](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor?language=objc). If those fields aren't set, then the "Maximum total threadgroup memory allocation" limit doesn't apply to render targets. For WebGPU, tile shaders are not supported, so we can safely disregard this limit for the purposes of calculating render target cost.

Beyond that, the "Maximum total render target size, per pixel, when using multiple color render targets" limit does apply. Here are some details:

- Multisampling does not affect this limit, with some exceptions listed below
- Resolve targets are not counted toward this limit
- Depth or stencil targets are not counted toward this limit
- Padding is counted toward this limit - imagine the on-chip data is held as an array-of-structures where each structure holds one texel from all the render targets. Within that struct, texels are aligned to their components' natural alignment (e.g. RG32Float is aligned to a 4-byte boundary).
- Packed formats cost as-if each channel was 16-bits wide

The exceptions for multisampling are: When multisampling (and only when multisampling), the following texture formats cost 8 bytes instead of 4 bytes:

- `rgba8unorm-srgb`
- `rgba8unorm`
- `bgra8unorm-srgb`
- `bgra8unorm`
- `rgba8snorm`

So, after all this, I think the proposal is something like:

```
var widest = 0
foreach renderTarget in renderTargets:
    let format = renderTarget.pixelFormat
    var width = widthOfFormatInBytes(format)
    if isSpecialCase(format):
        width = 8
    widest = max(widest, width)
make sure widest * renderTargets.count <= maxBytesPerPixelAcrossAllRenderTargets
```

The justification for this is:
- The list of special cases is very small, relative to the total number of pixel formats we have. It would be unfortunate to pessimize on _all_ formats just because 5 of them are special.
- The `max()` operation is a simplification for padding. It is a pessimization, but hopefully not too severe. It would be reasonable to adding the complexity of padding, but I'm not sure the complication is worth it. Also, this is assuming that we can't automatically sort render targets by size (to get perfect padding). If we _can_ sort render targets, then we don't have to pessimize at all here, and we can just sum up the widths instead of multiplying the count by the max.

**Comment by kainino0x** [comment]
Sounds to me like computing the padding only makes things a tiny bit more complicated, and we should just go ahead avoid the pessimization.

**Comment by toji** [comment]
Probably the biggest concern that Kai and I have in discussing this in the editors meeting is simply determining what, if any, the equivalent limits are on devices outside the Apple ecosystem. We're not aware of any at the moment, Vulkan doesn't appear to document it if there are. There's a suspicion that if there are practical limits we'll only find them out by testing on a large array of devices, especially mobile, and they probably won't be as nicely uniform across GPUs as the Metal ecosystem is. Additionally, it might not manifest as an outright failure, but instead as a performance cliff.

Making that evaluation more complicated is the fact that we're not currently set up to do that type of evaluation, though we want to reach out to the people in charge of the DEQP tests and see if they can help. In any case, it may be a while before we can properly evaluate this. And, of course, things can always change as new devices (or even drivers) enter the market.

What this all boils down to is that even if we do implement the above limit algorithms, we probably want an "escape valve" for situations where we're unexpectedly blocked. It seems like a good scenario to make use of the `internal` error type that we've been discussing.

**Comment by litherum** [comment]
Sounds like we should at least start with the Metal ones and expand from there once new data presents itself.

**Comment by kainino0x** [comment]
The problem is we're very limited in how we can change this limit after V1. We can make it strictly less strict, but we can't add add another limit or make any valid cases into error cases.

That said, like Brandon said, we can generate an `internal` error in various cases and it's most likely fine to rely on that to paper over any differences if we find them.

We should still try to find out how Vulkan implementations deal with situations like this.

**Comment by kainino0x** [comment]
editors: implement the algorithm described above, except with padding instead of the pessimization. @litherum to try to find time to implement it. Then we'll put that on tacit resolution queue.

**Comment by litherum** [comment]
```
var total = 0
foreach renderTarget in renderTargets:
    let format = renderTarget.pixelFormat
    var formatWidth = widthOfFormatInBytes(format)
    var componentWidth = widthOfComponentFormatInBytes(format)
    if isSpecialCase(format):
        width = 8
    if isPacked(format):
        width = 8
        componentWidth = 2
    total = roundUp(total, componentWidth)
    total += width
make sure total <= maxBytesPerPixelAcrossAllRenderTargets
```

**Comment by teoxoy** [comment]
@kainino0x 

> We should still try to find out how Vulkan implementations deal with situations like this.

Any news on this front? 👀

I also wonder about DX12.

**Comment by Kangz** [comment]
DX12 probably doesn't have a problem because it doesn't really target hardware that has an explicit tile cache, which is what this limit is about.

Nothing for Vulkan unfortunately. I'd expect either of `VkRenderPass` or `VkFramebuffer` creation to fail if going above what HW can do, but haven't verified it.
