### ISSUE TITLE
The validating linear texture data algorithm is overly complex

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2971]
https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-linear-texture-data

 - It mixes simple argument validation with the computation of requiredBytesInCopy.
 - It special cases the cases where depth > 1 and height > 1
 - It could early out if the copy size is 0.

I was looking at a failure around writeTexture and it was very difficult to check what the spec said for a copy of size `[3, 0, 6]` and to make sure that it said `requiredBytesInCopy` is computed to be 0.

**Comment by Kangz** [comment]
Actually, the algorithm still needs cleanup, but it seems to count the padding bytes of empty copies on purpose, so it's probably ok to keep.

**Comment by kainino0x** [comment]
> * It mixes simple argument validation with the computation of requiredBytesInCopy.
> * It special cases the cases where depth > 1 and height > 1

This is the way it is because bytesPerRow and rowsPerImage are only guaranteed to be set under those conditions. The alternative is to do `?? 0` which I suppose does make it cognitively simpler.

The first block of validation validates the input to the algorithm, and the second checks the actual result of the algorithm. It just ends up looking interleaved because of the block size stuff.

I did a series of changes in #3120, you can tell me what you think of the various changes. The end result is not *that* different, though.

**Comment by Kangz** [comment]
Thank you for the change. I think it reads much more clearly.
