### ISSUE TITLE
wgsl: The term `override expression` is confusing

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2981]
When reading the [Array Types](https://www.w3.org/TR/WGSL/#array-types) we specify the element count `It [must](https://www.w3.org/TR/WGSL/#shader-creation-error) be an [override expression](https://www.w3.org/TR/WGSL/#override-expression).`

On first reading, this makes me think it _must_ be an _override_ value. So, leading me to believe that `let a: array<f32, 8>` wouldn't be valid, as `8` isn't an `override` variable.

Is there a better name to encapsulate what we are calling `override expression` so it is easier to understand outside the context of overrides?

Specifically, an `override expression` is:

> be composed only [creation-time expressions](https://www.w3.org/TR/WGSL/#creation-time-expressions) or expressions where all identifiers [resolve](https://www.w3.org/TR/WGSL/#resolves) to overridable constants, [creation-time constants](https://www.w3.org/TR/WGSL/#creation-time-constant), or [creation-time functions](https://www.w3.org/TR/WGSL/#creation-time-functions). Such an expression is called an override expression.

**Comment by teoxoy** [comment]
`pipeline-creation-time expression`? 😄 or `late creation-time expression`?

**Comment by dj2** [comment]
They aren't `pipeline-creation-time` though. That's the thing, they're a lot more general then that. They include all `creation-time` constants, expressions and functions along with the overridable constants.

Only overridable constants come at creation time. Everything else is at compile time (so even `late creation-time` doesn't work. You know what `8` means immediately, heh.

**Comment by teoxoy** [comment]
Considering "override expressions" are not widely used throughout the spec I think it might be worth defining them as: "creation-time expressions where at least one identifier resolves to an overridable constant". And modifying the language where they were previously used (only array el count) to say: "creation-time expressions or pipeline-creation-time expressions".

I think this makes things clearer since expressions will now have the possibility of only being one or the other (XOR instead of OR).
