### ISSUE TITLE
Specify that structures compare by name, not by structure.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2994]
For `array` we specify exactly how two arrays compare to determine if they're the same. We should note in the spec that two `struct` types are only the same if their names are equal. We _do not_ compare structures by the structure, only by the name.

So:

```
struct A {
 b: i32,
};
struct B {
 b: i32,
};
fn foo(a: A) {
}

var a: A;
var b: B;

foo(a);  // valid
foo(b);  // invalid
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-07-minutes#specify-that-structures-compare-by-name-not-by-structure-2994">WGSL meeting minutes 2022-06-07</a></summary>



* KG: Structs are not “duck” typed.  It’s by-name match instead of structural.
* Agree this is the way it is. Make sure spec says it.


</details>
