### ISSUE TITLE
Add `saturate()` or `clamp01()`

### ISSUE THREAD

**Issue by jespertheend** [gpuweb/gpuweb#3012]
This was mentioned briefly in https://github.com/gpuweb/gpuweb/issues/667#issuecomment-648322728 but I haven't seen this being mentioned anywhere else.
At the moment you can simply do `clamp(x, 0.0, 1.0)` so I reckon this doesn't have a super high priority, but I do find myself doing this quite frequently so a dedicated std function for this would certainly be appreciated.

As for the name, I've always found `saturate()` to be very confusing, whereas with `clamp01()` it is immediately clear what it does. But that might also be because I'm used to the Unity api.

**Comment by magcius** [comment]
Hardware also usually has support for this -- saturate can often be completely free.

**Comment by dneto0** [comment]
> Hardware also usually has support for this -- saturate can often be completely free.

Example:  AMD Vega ALU instructions have a CLAMP bit (emphasis added)

> When the VOP3 form is used, instructions with a floating-point result can apply an output
modifier (OMOD field) that multiplies the result by: 0.5, 1.0, 2.0 or 4.0.
> *Optionally, the result can be clamped (CLAMP field) to the range [0.0, +1.0].*

clamp01 seems like a fine name.

For definiteness, I'd suggest adding this for    scalar and vector over f32 and f16 (or any float scalar type that may come in the future)

**Comment by dneto0** [comment]
Here's the Vega reference manual I found it in:  https://developer.amd.com/wp-content/resources/Vega_Shader_ISA.pdf  See 6.2.2 Instruction Outputs

**Comment by ben-clayton** [comment]
[HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-saturate), [MSL](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) and [Cg](https://developer.download.nvidia.com/cg/saturate.html) uses `saturate` (GLSL being the odd one out with no builtin for this).

In the past we've leaned towards reusing the standard term for these kind of builtins. For that reason, I'd vote for `saturate` over `clamp01` or variants thereof.

**Comment by jespertheend** [comment]
> In the past we've leaned towards reusing the standard term

Ah in that case `saturate` does sound like a better option yeah.

**Comment by dneto0** [comment]
I didn't realize these builtins already existed so widely.  :-)

**Comment by kdashg** [comment]
My naive preference is for `clamp01`, where I immediately know what it means.
`saturate` always feels like a self-modification. HLSL and MSL have a strong voting block for `saturate` here, but I still think it's not a good name.

**Comment by Jiawei-Shao** [comment]
Intel ISA also supports [`destination saturation`](https://github.com/intel/intel-graphics-compiler/blob/master/documentation/visa/2_datatypes.md#saturation):

"Saturation is a clamping operation that converts any data that is outside the saturation target range for the destination data type to the closest represented value with the target range. **If the destination type is float, saturation target range is [0.0, 1.0]**)."

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-07-minutes#add-saturate-or-clamp01-3012">WGSL meeting minutes 2022-06-07</a></summary>



* DN: Someone noticed that it’s missing from WGSL, and that it exists in e.g. hlsl and MSL and that e.g. AMD has hardware support for this, so I think it’s worth adding.
* MM: *The* reason for accepting this isn’t performance, because we can recognize this anyways. The difference is that this should be helping authors, about being nice to authors. I think it should be called saturate and not clamp.
* KG: Also feel should be nice to authors.  Clamp01 makes more sense to me.  ‘Saturate’ sounds like a self-modifying verb.  Comes down to where we come from in our programming culture.  I’d have to look up what ‘saturate’ means. That’s my vote, but not strongly held.
* KG: Unity have clamp01.: [https://docs.unity3d.com/ScriptReference/Mathf.Clamp01.html](https://docs.unity3d.com/ScriptReference/Mathf.Clamp01.html) (but this isn’t a shader language)
* GR: Can we have both?
* MOD: Clamp01 reads to me as a different version of ‘clamp’.  Looks like a version not a function.
* KG: I’m resigned to it being saturate instead of clamp.  I still would have to go lookup.
* KG: Compiler should translate the idiom   clamp(x,0,1) and translate it to saturate call. 
* _Agreed to ‘saturate’_


</details>
