### ISSUE TITLE
Include arrays in creation-time constant expressions

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3056]
Currently, creation-time constant expressions support:
* scalars
* abstract-numerics
* vectors of scalars and abstract-numerics
* matrices of floats and abstract-floats

IIRC, module-scope `let` was removed as we believed `const` fully superceded it. However, module-scope `let` also supported array and structure types.

In updating tint to support `const` and deprecate module-scope `let`, I'm finding a significant number of shaders that used module-scope `let` arrays. To fix this, the shaders would either have to use a module-scope `var` (requiring storage, and is mutable), or duplicate the array as a bunch of function-scope `let`s (unpleasant). Neither will be treated as `const` and so may produce less efficient code, nor can they be used in other constant expressions.

If we were to add arrays to the list of supported `const` types, then we may also want to consider:
* Adding type inference to array, much like `vec(1, 2)`. This would allow for arrays of abstract numerics.
* Supporting structures too. Note - I haven't seen any use of module-scope `let` of structure type in the wild (yet). This is also more complex to spec and implement.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-21-minutes#include-arrays-in-creation-time-constant-expressions-3056">WGSL meeting minutes 2022-06-21</a></summary>



* BC: Implementation shader creation time expression evaluation, tried to deprecated module scoped let as we said const was superior and discovered shaders with module scope let arrays. (and by whole load, quite a few). Wondering if arrays could be part of const expression plan. If we do that, could other things like going further for abstract numeric in arrays, do we have structures in const expressions. Haven’t seen any shaders with structures but seen a lot of arrays.
* KG: Would punt structures for now.
* BC: Happy with that. Any concerns?
* MM: In shaders found with let at global scope to define an array how do they spell the array? What characters do they type after =?
* BC: Have to type array&lt;f32, 5>(1, 2, 3, 4, 5). Immutable lookup tables
* MM: So we synthesize constructors so if i said array&lt;f32, 17> we’d make the constructor?
* BC: Bit lost. Always ben able to have array constructors as lets so you’d say array&lt;i32, 5>(1, 2, 3, 4, 5)
* MM: If the array is size 17 you write 17 things
* BC: No way to writer fewere (modulo 0 initializer). Can’t do single element splat with array unlike matrix and vector
* MM: See no reason to not have this.
* BC: Do we want non templated form to match mat and vec to infer type 
* AB: If want abstract then we have to do it
* BC: Yup.
* MM: [??]
* BC: So, array(1, ,2 3, 4)
* MM: Makes sense
* MM: Phrased as compiler creates constructor, do we do this for structures already? So you cannot use a structure in the global scope?
* AB: Don’t see why constructo rat module scope
* MM: What do you put after equal
* AB: Member wise initializer for structure.
* MM: So that should work with const also?
* KG If not asked for, don’t want to do it. If it’s free, sure but these things aren’t necessarily free and want to focus on user wants
* MM: View compiler generated constructors as identical for arrays and structures
* KG: Second request, spec most basic thing and get that through an dwe can propose structures for const. Maybe too afraid of it being spec work
* BC: Also implementation work to support structures in Tint. Would be keen to leave structures to future support in const.
* KG: **Resolve for now, allow arrays and it sounds like generic arrays**.
* BC: Sounds good.



</details>

**Comment by dneto0** [comment]
I'm working on this patch.
There's an interesting delicacy around "fixed footprint" array types.  The "creation-fixed" and generic "fixed" are meant to talk about constraints on the element count.   We still want to keep that, but the language is mainly about the number of memory locations, but abstract types don't have a spec-defined specific byte count.

**Comment by dneto0** [comment]
#3213 supports this.

The new constructor looks like this  `array(e0,e1, ... en)`
