### ISSUE TITLE
wgsl: Is/should initializer of module-scope variables limited to creation-time expressions?

### ISSUE THREAD

**Issue by jzm-intel** [gpuweb/gpuweb#3081]
(By saying initializer of module-scope variables, it is actually initializer of `private` variables, since other types of module-scope variables must not have an initializer.)

In current WGSL spec, module scope creation-time constant (`const` declaration) are required to have a initializer of creation-time expression ([Spec 5.1.3](https://gpuweb.github.io/gpuweb/wgsl/#creation-time-consts)), and override constant are required to have a initializer of override expression ([Spec 5.1.2](https://gpuweb.github.io/gpuweb/wgsl/#override-decls)). 
However, it seems that there is no restriction for initializer of module-scope variables (`private` variable), so the following codes *may* be valid:
1. `var<private> f: f32 = f32(1.0f);    // Good`
2. `var<private> f: f32 = f32(1.0f + 2.0f);    // A little complex, but should be creation-time expression`
3. `const v = 2.0f; var<private> f: f32 = f32(v);    // Still creation-time expression`
4. `const v = 2.0f; var<private> f: f32 = f32(v * 2.0f);    // Still`
5. `override v: f32 = 2.0f; var<private> f: f32 = f32(v);    // Override expression`
6. `override v: f32 = 2.0f; var<private> f: f32 = f32(v * 2.0f);    // Override expression`
7. `var<private> v: f32 = 2.0f; var<private> f: f32 = f32(v);    // Not a creation-time expression, but is a module scope variable`
8. `var<private> v: f32 = 2.0f; var<private> f: f32 = f32(v * 2.0f);    // Not a creation-time expression`
9. ```
    /* in is a read-only storage buffer with f32 element v */
    var<private> f: f32 = f32(in.v);    // Not a creation-time expression
   ```
My question is that should we (or does it) restrict the initializer of module scope `private` variables to creation-time expression / override expression, or allow any expression (like the initializer of function scope variables)?
A concern is that SPIRV require that initializer of OpVariable must be rather a constant or a module scope variable.

**Comment by alan-baker** [comment]
The intention is that initializer are limited to creation-time expressions; however, it appears that restriction was missed when creation-time expressions were introduced. Previously, the grammar enforced this restriction, but now it should be textual in module-scope variables section.

**Comment by ben-clayton** [comment]
> The intention is that initializers are limited to creation-time expressions for module-scope variables; however, it appears that restriction was missed when creation-time expressions were introduced. Previously, the grammar enforced this restriction, but now it should be textual in module-scope variables section.

I'm wondering if module-scope `var` initializers should be `override expressions`, so that:

* `const` variables can be initialized with `const expressions` (shader creation time constants), which includes references to other `const` variables.
* `override` variables can be initialized with `override expressions`, which includes references to other `const` and `override` variables.
* `var<private>` variables can also be initialized with `override expressions`, which includes references to other `const` and `override` variables.

Is there any technical reason why you wouldn't allow `override expressions` for the initializer of a `var<private>`?

**Comment by dneto0** [comment]
The model for this is module-scope OpVariable in SPIR-V.  That allows any OpConstant* or specialization constant.
So yes, it should actually be override expression.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-07-05-minutes#wgsl-pointer-aliasing-rules--issue-1457">WGSL meeting minutes 2022-07-05</a></summary>

* ZJ: On #3081, it seems we don’t have a way to mandate override expressions for non-scalar types? Because we say that override must have scalar types, but we could have a vector of another override. Maybe I will leave a comment, and we can discuss if needed.
* DN: So the proposal would be that "override expressions can include structure-construction expressions, and member-access expressions"
* ZJ: So what about e.g. `override x = 1; vec4&lt;i32>(x,x,x,x);`
* AB: Think it could be supported, but would need more implementation work.
* MM: If we mark something as override, then it must be settable from the API side
* ZJ: That’s for an override declaration.  But expression can be more types.
* MM: If you give a name to this thing vec4&lt;i32>(x,x,x,x); then it should be something that should be overriable from the API side, but it is not possible right now.  So if we add this feature, then it should be overridable from the API side.
* AB: Right, that must be part of the solution. Will take more design work.  Suggest filing this as a separate issue.  Think it’s orthogonal to the resolution.
* MM: Question for ZJ: which milestone: v1 or post-v1?
* **ZJ: I will file another issue to track this.**

</details>

**Comment by dneto0** [comment]
@alan-baker  rewrote the variable and value sections in [#3226 ](https://github.com/gpuweb/gpuweb/pull/3226), and clarified that initializers for `private` address space variables must be a const-expression or an override-expression.
