### ISSUE TITLE
Clarification of loop identifier lifetime

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3153]
In [7.4.3 Loop Statement](https://www.w3.org/TR/WGSL/#loop-statement) we note:

> The identifier of a declaration in a loop is in scope from the start of the next statement until the end of the loop body. The declaration is executed each time it is reached, so each new iteration creates a new instance of the variable or constant, and re-initializes it.

This seems a bit too general. An identifier of a declaration declared in the top scope? of the loop is in scope to the end of the loop but an identifier declared in the loop inside another block is not in scope to the end of the loop. As written, it sounds like the identifier expands in scope to the end of the loop.

**Comment by kdashg** [comment]
How about...
> The identifier of a declaration in a loop is in scope like normal, from the start of the next statement until the end of its lexical scope. (e.g. for an identifier in the top level of the loop body, until the end of the loop body) However, the declaration is executed each time it is reached, so each new iteration creates a new instance of the variable or constant, and re-initializes it.

**Comment by litherum** [comment]
We are discussing this example?

**Comment by djg** [comment]
We believe that the example:
```
for (let i = 0; i < 10; i = i + 1) {
    let i = 17;
}
```

Should be an error to keep the uniformity with multiple `let` in the same scopes being an error and, despite WGSL syntax being "Rust" inspired, it being an error in C++:
```
for (int i = 0; i < 10; ++i) {
    int i = 17;
}
```

```
<source>:4:13: error: redeclaration of 'int i'
    4 |         int i = 17;
      |             ^
<source>:3:14: note: 'int i' previously declared here
    3 |     for (int i = 0; i < num; ++i) {
      |              ^
```

**Comment by dj2** [comment]
> We are discussing this example?
> 
> ```
> for (let i = 0; i < 10; i = i + 1) {
>     let i = 17;
> }
> ```
> 
> With the previous wording this would be illegal, but with the new wording this would be legal?

No, that should be legal in both cases. This is stricly editorial as, my reading of that sentence says the following should be legal:

```rust
for (var i = 0; i < 10; i++) {
 if (true) {
   var a = 4;
 }
 var b = a;
}
```
This is because it says a variable declared is valid until the _end of the loop body_ not the enclosing scope.

(Note, you can't use `let` as `let` is constant. You have to use `var` for `i`)

**Comment by dj2** [comment]
> We believe that the example:
> 
> ```
> for (let i = 0; i < 10; i = i + 1) {
>     let i = 17;
> }
> ```
> 
> Should be an error to keep the uniformity with multiple `let` in the same scopes being an error and, despite WGSL syntax being "Rust" inspired, it being an error in C++:
> 

That's actually already illegal as `let` is a constant value, you can't do `i = i + 1` in that example.

(WGSL isn't actually "Rust" inspired, it's lots of things inspired and Rust and lots of things happen to look the same)

**Comment by dj2** [comment]
> Should be an error to keep the uniformity with multiple `let` in the same scopes being an error and, despite WGSL syntax being "Rust" inspired, it being an error in C++:


Chatting internally, I mis-understood this, I though you were talking about a "uniformity" error, but I believe you're saying to keep the spec consistent with scoping, yea?

**Comment by dneto0** [comment]
For the original issue, another solution is to delete the entire paragraph.  (!)

**Comment by dneto0** [comment]
To be concrete about the original complaint, it's this:

```
loop  {
   if (true) {
         let x = 0u;
   }
   // i is not in scope here... But the current text seems to make it so.
}
```

**Comment by dneto0** [comment]
Regarding this example (but changing `let` to `var`, because var is updatable but let is not.):

```
for (var i = 0; i < 10; i = i + 1) {
     var i = 17;
}
```

> With the previous wording this would be illegal, but with the new wording this would be legal?

Right, with previous wording it's invalid: the scope of the `var i = 0` declaration extends to the "end of the loop body", and so does the scope of the `var i = 17`.

**Comment by dneto0** [comment]
Kudos @alan-baker for pointing out (and putting in) an example of exactly this form of loop, in  https://gpuweb.github.io/gpuweb/wgsl/#declaration-and-scope 

Look for
```
    // Valid, i_1 is in scope until the end of the for loop
    for ( var i: i32 = 0; i < 10; i++ ) { // i_1
      // Invalid, i_2 has the same end scope as i_1.
      var i: i32 = 1; // i_2.
    }
```

**Comment by dneto0** [comment]
Taking a second look at this.  In this week's meeting @alan-baker noted that 'compound statement' already says the right thing, and perhaps we can lean on that:

>  A compound statement is a brace-enclosed sequence of zero or more statements. When a [declaration](https://gpuweb.github.io/gpuweb/wgsl/#declaration) is one of those statements, its [identifier](https://gpuweb.github.io/gpuweb/wgsl/#identifier) is [in scope](https://gpuweb.github.io/gpuweb/wgsl/#in-scope) from the start of the next statement until the end of the compound statement.


And loop statement starts with

> A loop statement repeatedly executes a loop body; the loop body is specified as a [compound statement](https://gpuweb.github.io/gpuweb/wgsl/#compound-statement). Each execution of the loop body is called an iteration.

So how about

> When one of the statements in the loop body is a declaration, it follows the normal scoping and lifetime rules of a declaration in a compound statement. That is, the loop body is a sequence of statements, and if one of those is a declaration then the declared identifier is in scope from the start of the next statement in the sequence until the end of the loop body.  
The declaration executes each time execution reaches it, creating a new instance of the variable or constant, and re-initializes it.

**Comment by dneto0** [comment]
Tweaked it to the following (apologies for broken links):

> When one of the statements in the loop body is a [declaration](https://github.com/gpuweb/gpuweb/issues/3153#declaration), it follows the normal [scope](https://github.com/gpuweb/gpuweb/issues/3153#scope) and [lifetime](https://github.com/gpuweb/gpuweb/issues/3153#lifetime) rules of a declaration in a [compound statement](https://github.com/gpuweb/gpuweb/issues/3153#compound-statement). That is, the loop body is a sequence of statements, and if one of those is a declaration then the scope of that declaration extends from the start of the next statement in the sequence until the end of the loop body. The declaration executes each time it is reached, so each new iteration creates a new instance of the [variable](https://github.com/gpuweb/gpuweb/issues/3153#variable-declaration) or [value](https://github.com/gpuweb/gpuweb/issues/3153#value-declaration), and re-initializes it.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-07-26-minutes#clarification-of-loop-identifier-lifetime-3153">WGSL meeting minutes 2022-07-26</a></summary>

* DN: One solution is delete the paragraph: [https://github.com/gpuweb/gpuweb/pull/3247](https://github.com/gpuweb/gpuweb/pull/3247) 
* DN: DS pointed out confusing language about scopes inside loops lasting to end of loop. Proposed solution is delete the paragraph as we don’t have it elsewhere. Then resort to general scoping rules. Question in the middle about something different, the existing language disallowed a shadow case and deleting the paragraph then it stays. The wording from KG would allow a thing we didn’t want to allow. Would like to sidestep by deleting paragraph.
* AB: Concern would be if you declare a var in the initializer, thinking about compound statements, might think it’s a larger scope then otherwise, the end of the thing that encloses the loop. Want to make sure the initializer section ends at the for loop.
* DN: Paragraph is in loop statement, looking at for statement an init clause if it’s a declaration it’s scope ends at end of loop body. Already pretty well spelled out.
* KG: If deleting the paragraph works, that’s cool. Don’t see how rewording changes meaning. Would be cool to understand how declarations in for loops are like scopes but not actually scopes. Like, 2 for loops using `i` but can’t use `i` inside the scope.
* DN: A scope is ‘blah’ isn’t really defined thing. We talk about the extent of source code in which a declaration can be referenced. The scope attaches to the declaration. Not a concept of braces make a scope (not as first class as might want). Raises questions rather then resolves then.
* KG: Trying to read and figure out what is and isn’t allowed and phrase in terms folks would understand. If the answer is more complicated then I understand then I can’t explain it.
* DN: By deleting the paragraph what did that paragraph do in the first place. Finding another way to do that, happy to iterate.
* DS: Don’t understand why what KG wrote is wrong
* KG: Two ways, internal body to loop is like an anonymous braced scope and we’re saying that isn’t the case. Things in the ()’s are effectively inside the scope of the for.
* DN: Re-reading text, think it’s fine and Myles is incorrect thinking it allows more. There are scopes and they can overlap. The overlapping is fine, what is bound is resolution.
* KG: Pointed out we have examples below, might be helpful if we can’t link line to inject inline to show what we mean.
* DN: Will drop PR and we’ll make it better.

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-02-minutes#clarification-of-loop-identifier-lifetime-3153">WGSL meeting minutes 2022-08-02</a></summary>

* Now has PR: [https://github.com/gpuweb/gpuweb/pull/3267](https://github.com/gpuweb/gpuweb/pull/3267) 
* MM: Kinda two issues here:
    * 1. Does a declaration in the parens collide with a declaration within the curlies?
        * for (var i = 0; i &lt; 10; i = i + 1) {
        *     let i = 17; // **consensus: error “`i` is already declared”**
        * }
        * 
        * I think consensus is that within-curlies **do** conflict with decls from within parens
    * 2. Declaring in a subscope of a loop.
        * for (var i = 0; i &lt; 10; i++) {
        *  if (true) {
        *    var a = 4;
        *  }
        *  var b = a; // **consensus: error “no `a` in scope”**
        * }
    * 
    * 
    * 

</details>
