### ISSUE TITLE
Specification needs to clarify behavior of indexing of abstract composite type with runtime value

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3210]
Consider the following:

```ts
const v = vec2(1, 2); // vec2 of abstract-int
const m = mat2x2(1.0, 2.0, 3.0, 4.0); // vec2 of abstract-float
var i = 1i; // A runtime (non-constant expression) i32
var a = v[i];
var b = m[i];
```

For the index accessors `v[i]` and `m[i]`, the objects being indexed (`v`, `m`) are both composite types of abstract numerics. In order to assign to the runtime-storage variables `var a` and `var b`, the RHS needs to be materialized† to their concrete types.

Materialization cannot be done **after** the index operation because the index value `i` is not known at compile time, and so the expression is not fully constant. As the expression is not constant, the dynamic index operation will need to be emitted by the backend (i.e. the index cannot be constant folded away). However, we cannot generate the index operation if it is operating on abstract types.

I would recommend that we spec that the indexed object is materialized **before** the dynamic index. For example: to evaluate `v[i]` above, we would do the following, in sequence: `vec2<abstract-int>(1, 2)` -> `vec2<i32>(1i, 2i)` -> `vec2<i32>(1i, 2i)[i]`

Note: This problem applies to single-liners, such as: `vec3(10, 20, 30)[i]`

---

† **_materialized_** is Tint terminology for the implicit conversion from an abstract numeric type to a concrete type. It isn't currently used in the spec.

**Comment by ben-clayton** [comment]
Note: When we finally spec the inferred-type array constructor (`array(1,2,3)`), this will also need to apply to arrays.

**Comment by dneto0** [comment]
> I would recommend that we spec that the indexed object is materialized before the dynamic index.

That makes sense.

For example, in the vector case,  there is one type rule for `e[i]` in https://gpuweb.github.io/gpuweb/wgsl/#vector-single-component 

 It should be split into two cases:
* abstract vector case where the index expression is a const expression
* concrete vector case where the index expression otherwise unconstrained (but still of correct type i32 or u32)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-09-06-minutes#specification-needs-to-clarify-behavior-of-indexing-of-abstract-composite-type-with-runtime-value-3210">WGSL 2022-09-06 Minutes</a></summary>

* KG: Feels editorial but technically a change? Recommendation from BC that we materialize the index before doing the index.
* BC: Don't think there is much else you can do.
* KG: Brain running away from what else you'd do. Resolved. If weird we can come back to it.
* MM: Trying to understand, vec where all components are const-expr and indexed with const-expr then result is const-expr. That's cool. Separate, have vector where components are const-expr and index with non-const-expr trying to determine that result is non-const expr?
* BC: Not about const-expr but about abstract. Can have vector of abstract and as written we don't materialize before the index. Given vector of abstract which isn't representable in backends you're dynamically executing on GPU but the thing indexing is non-representable. So have to materialize before the index as you can't emit the abstract.
* KG: Otherwise jumptable or something
* JB: Thought the spec said that anyway, so having it say that is fine with me.
* MM: Seems legit.
* KG: **We'll do that**.

</details>
