### ISSUE TITLE
Dataview instead of arraybuffer for buffer mapping operations

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#322]
How about returning promises with a [`DataView`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) instead of an [`ArrayBuffer` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) for `mapReadAsync` and `mapWriteAsync`? It makes it easier to access individual values.

```js
// Currently
const arrayBuffer = await gpuWriteBuffer.mapWriteAsync();
const view = new Uint8Array(arrayBuffer);
view[1] = 7;

// Proposal for writing
const dataView = await gpuWriteBuffer.mapWriteAsync();
dataView.setUint8(1, 7);

// Proposal for reading
const dataView = await gpuReadBuffer.mapReadAsync();
console.log(dataView.getUint8(1));
```

Note that we can still access arrayBuffer with `dataView.buffer`.
What do you think?

**Comment by grovesNL** [comment]
I don't think usage of `DataView` is very common except when working with binary data directly. It's a bit inconvenient to specify reads/writes in byte offsets if the entire buffer is known to be `Float32`. Most use cases in WebGL (including interleaved vertex data) seem to use typed arrays because of the convenience or performance (i.e. access to copying methods like [`.set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/set)).

For these reasons I think this might decrease usability, because most users would have to add another step to get data into one of the other typed arrays formats, i.e. `new Float32Array(dataView.buffer)`

**Comment by magcius** [comment]
mapWriteAsync and mapReadAsync are a bit unfortunate because of the GC costs -- both because of a Promise, but because an ArrayBuffer is useless unless you can create one of the wrappers. And in my experience, GC pauses are a huge issue for interactive applications.

I don't agree with using DataView or typed arrays though -- DataView isn't user-friendly, and typed arrays are unfriendly for cases where you have mixed buffer data (common for vertex data).

And if we agree that removing garbage from the hot loop is a goal, then the Promises have to go too.

**Comment by kainino0x** [comment]
Agreed, only minority cases (writing structured directly into a uniform buffer) would benefit from this; raw data uploads, and memcpys of pre-structured data, don't benefit at all because they'll just make a typed array like Josh's example.

In addition, this is unfriendly to WASM apps, which use their internal understanding of the memory layout instead of using DataView, and will need either a typed array (for memcpying) or an ArrayBuffer (in a hypothetical future where mmapping in the WASM heap is possible).

**Comment by grovesNL** [comment]
I also share @magcius's concern though – the current design is going to create a lot of GC pressure on hot paths (i.e. streaming uploads).

I'm not sure if we should split it into another issue or how to proceed with this concern, but I think it's very important to consider the GC impact of potentially many promises and typed arrays per frame, ideally before the snapshot is taken. It was discussed previously a bit in #214 and #52, and the concept of `Thenable` (instead of a regular `Promise`) in #138.

**Comment by beaufortfrancois** [comment]
I've been convinced by all of you that using `DataView` is not suitable in this case.
Thanks for your input!

I'll close this issue so that we can continue discussing GC pressure on separate issues.
