### ISSUE TITLE
Clarification of `@builtin` values in structs not used in an entry-point

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3261]
From the spec:

> Must only be applied to an entry point function parameter, entry point return type, or member of a structure.

Are these two functions valid or invalid? 

```
struct S {
  @builtin(sample_mask) value : u32,
};

fn main() -> S {
  return S();
}
```

```
struct S {
  @builtin(front_facing) value : bool,
};

fn main(in : S)  {}
```

From the spec, it sounds like they're valid as the attribute is on the struct, not the function, but is it expected?

If these are allowed, do the `in/out` constraints for the builtin have to match?

e.g. the `num_workgroups` is an `in` builtin, can I use it on an `out` struct if the function is not an entry point?

```
struct S {
  @builtin(num_workgroups) value : vec3<u32>,
};

fn main() -> S {
  return S();
}
```

**Comment by dneto0** [comment]
> Are these two functions valid or invalid?

Valid.  

>  From the spec, it sounds like they're valid as the attribute is on the struct, not the function, but is it expected?

Yes, this is expected.

The validity and usage of this should be covered by https://gpuweb.github.io/gpuweb/wgsl/#builtin-inputs-outputs

> If these are allowed, do the in/out constraints for the builtin have to match?

Intent is yes:   when a builtin value appears where a builtin value may be expected (i.e. entry point param or entry point return type), the triple (stage, in/out, value type) must be satisfied.  (Phrase it this way because 'position' is an output to vertex shader but also an input to fragment shader)

Intent:  Elsewhere in the shader (variable and value declarations, expressions, statements, user-defined functions), the @builtin attribute is ignored.

Intent (but I just thought of this and haven't thought it through), `@builtin` attribute is carried over from a struct into a type aliasing to that struct.   (Seems consistent with the 'an alias really is substitutable for the original').

I don't think the three intents above are captured appropriately.  Thanks for filing this!

**Comment by dneto0** [comment]
oh wait. The first 'intent' given above is covered by the two sentences starting with "Conversely" in [9.3.1.1 Built-in Inputs and Outputs](https://gpuweb.github.io/gpuweb/wgsl/#builtin-inputs-outputs)

**Comment by dneto0** [comment]
Similar questions can be raised about other I/O attributes:  location, flat, interpolate, invariant

**Comment by dj2** [comment]
Yea, I was asking about builtin's in general, not the exact ones in the examples.

K, so all three of those are valid, good to know, thanks.

**Comment by dneto0** [comment]
Maybe the new text is added to [9.3.1 Pipeline Input and Output Interface](https://gpuweb.github.io/gpuweb/wgsl/#pipeline-inputs-outputs)

> The I/O attributes are: builtin, location, flat, interpolate, invariant.

> An I/O attribute on a member of structure S has an effect only when:
> - S is used as as the type of a formal parameter or return type of an entry point.
> - S is the right-hand side of a type alias.  In this case I/O attributes on members of S are carried over into the type alias being defined.

(We can't have nesting of a struct in a struct for entry point IO)
