### ISSUE TITLE
Object labels require client-shared state

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3263]
"Client-shared state" = state in the content process that's shared by multiple JS interfaces (e.g. two GPUBuffer interfaces on different threads pointing to the same buffer object).

Recently I've been working on detangling the client (content timeline) and service (device timeline) states in the spec. Part of this was #3014 which led to the realization that (I think) there is actually no client-shared state required in GPUBuffer for mapping state like I had thought there was.

I believe this leaves `.label` as the last piece of potentially client-shared state when we add multithreading. Here are the options I see for it:

1. Label is internally-synchronized client-shared state, can be racily used across threads. Also creates a high precision timer, but we probably already have that.
2. Labels are per-interface, not per-device-timeline-object, and we somehow send down the label with every call individually or something.
3. The string you get from `.label` is the last label set *from this interface* and may be incorrect if e.g. another thread set it since then.
4. Just change `.label` to `.setLabel()` so you can't read back the label. Users have to store the label off themselves if they want the behavior of option 1 or 3. Unlike the others, this one is a pre-V1 change.

I'm in favor of option 4.

**Comment by toji** [comment]
Of those, I'm in favor of option 4 as well. Though for completeness we may also consider a 5th option:

  5. Only allow labels to be set during object creation, and either change `.label` to be a read-only attribute or omit it entirely.

This is how I personally tend to use labels, and I don't find it particularly difficult. May represent a problem for developers trying to debug issues with a library that created objects internally and exposed them to the calling code (devices, passEncoders, etc.)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-meeting-2022-08-0203-apac-timed#object-labels-require-client-shared-state-3263">WGSL meeting minutes 2022-08-02</a></summary>

* KN: I thought there was client-side state e.g. mapping state that was shared between different workers because they’re in the same content process. I now think that this in untrue, and we don’t have any shared state like this.
* KN: Therefore I think that the only state that is shared would be labels, which are read+write attributes. You probably think that changing the label on one worker would cause it to (racily) update for other readers on other workers.
* KN: So I am enumerating four options for us to choose from.
* KN: One is to change the labels to be set via a function, and make stronger guarantees there.
* KG: I don’t think people should expect this to be shared client state. Didn’t we punt cross-worker sharing to post-v1?
* KN: Yes, but paving the way for that.
* RC: Think it’s valuable to allow changing the label. E.g. you’re using a cache of objects and want to reuse one. Was against allowing multiple threads to access the same object. Think we should do transfer semantics so it’s easy to know which thread owns which thing.
* MM: We have the same concern as Rafael with option 5. We think option 4 is probably the best one.
* MM: Isn’t there shared state for buffer mapping? Didn’t we just add a way to check the state?
* KN: My proposal with multithreading will be that that state is per-thread. Threads can rely on the server to tell it whether another thread has it mapped.
* **(Let’s come back to this next week)**

</details>

**Comment by kainino0x** [comment]
Meeting: resolved on no change. When we get to multithreading we can choose between options 1/2/3.

**Comment by kainino0x** [comment]
Corentin proposed the following semantics and implementation strategy for an implementation that:

- deduplicates immutable objects (like bind group layouts) but doesn't want to maintain separate state for deduplicated objects just for the sake of label state
- doesn't want to mislead developers by mislabeling objects in error messages and in native APIs

Proposal:

- Choose option 3 above: when you read `.label`, it tells you only the last label set on this JS wrapper, never something from another wrapper. (Option 4 would be compatible, as well, but is not proposed.)
- Implementation would be able to: write the `label` setter in terms of `removeLabel(old label)` and `addLabel(new label)`. The GPU service side tracks the list (multiset) of labels for an object, and concatenates those labels together for error messages and platform objects, so developers can see all of the possible labels (and that the object was deduplicated).
    - Note: the destructor of the wrapper would also `removeLabel` with the wrapper's current label, so that label doesn't leak.

This should also make #3454 easy to resolve.

cc @litherum

**Comment by kainino0x** [comment]
In essence, this would codify that there is no normative difference between two internal objects that have the same immutable values (e.g. two bind group layouts with the same layout, or two samplers with the same parameters).

**Comment by litherum** [comment]
🆗 makes sense.

**Comment by Kangz** [comment]
I think this is now on the tacit resolution queue to change nothing.
