### ISSUE TITLE
importExternalTexture/copyExternalImageToTexture should not throw when source image is not decodable

### ISSUE THREAD

**Issue by junov** [gpuweb/gpuweb#3288]
Step 3 of [importExternalTexture](https://www.w3.org/TR/webgpu/#dom-gpudevice-importexternaltexture) states: "If usability is bad, throw an [InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror) and stop."

[EDIT: and `copyExternalImageToTexture` --@kainino0x]

Because this exception needs to be thrown synchronously, importExternalTexture cannot be implemented in a way where the source image is decoded asynchronously.

It would give implementers more flexibility to decode images in a separate thread or on the GPU if we could emit a WebGPU error instead of throwing an exception when the source image is not fully decodable.

**Comment by kainino0x** [comment]
I thought I copied this language from somewhere, but I don't know where. Maybe I copied it from `drawImage` but changed it to error explicitly instead of just giving a blank image. In any case, generating a WebGPU error (and making the `GPUExternalTexture` object asynchronously invalid) makes a lot more sense to me, and fits with the rest of the API.

**Comment by litherum** [comment]
I think we probably need to go further than this. ExternalTextures will require us to be able to emit shader code to do color space conversion, but video files can be in a huge variety of color spaces and arbitrary ICC profiles. We probably need an affordance in the spec to indicate “everything about the video is correct and ready to go, but it’s using a colorspace / ICC profile which my emitted shader code can’t handle.”

**Comment by litherum** [comment]
Thinking more about this, I wonder if we should somehow let the author pass in some extra information into `createShaderModule()` to help us make sure we're generating good code for the external textures.

Maybe they could pass in the `GPUExternalTextureDescriptor` itself (though this isn't perfect because each frame of the video can have a different color space). Or maybe we represent color spaces some other way, and let the author pass in that other way's data?

**Comment by litherum** [comment]
(Related: colorspace conversions are somewhat arbitrarily complex: https://color.org/specification/ICC.1-2022-05.pdf)

**Comment by kainino0x** [comment]
That isn't the intended design of GPUExternalTexture. The injected code is supposed to be fully independent of the video encoding/colorspace; that code should be able to dynamically switch between 0-copy and 1-copy inputs, depending on whether the implementation was able to use 0-copy or not. The 0-copy path should handle "most" conversions, and the implementation should fall back to a 1-copy path when the injected code can't handle the conversion (either by converting to RGB or by converting to Y/UV with the unsupported conversions pre-applied).

**Comment by litherum** [comment]
That's kind of unfortunate, from an author's point of view - some videos will appear to be magically faster than other videos, without any obvious explanation. It seems to go against the design principles of these lower-level graphics APIs in the first place.

**Comment by litherum** [comment]
I guess I should move this to a new issue 🤔

**Comment by kainino0x** [comment]
re: the original issue: I think we also need to fix copyExternalImageToTexture in the same way
