### ISSUE TITLE
shaders: equivalent of gl_PointCoord and gl_PointSize don't exist in HLSL

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#332]
D3D doesn't have facility to create point sprites and expects developers to draw small quads or use geometry shaders to implement them. This means it doesn't have a `gl_PointSize` output for the vertex shader (and the `PSIZE` semantic is for D3D9 only as far as I can tell). Likewise it doesn't have the equivalent of `gl_PointCoord`.

Should we not support variable point sizes in WebGPU and always have points have a radius of 1?

**Comment by kvark** [comment]
Yes, I think it would be fine to restrict this. There is never a case where using point sprites is a good solution: it can always be replaced by instanced geometry rendering, which prompts to also follow the outline of an actual particle being drawn (reducing fragment count and fill rate consumption).

**Comment by litherum** [comment]
If you have a particle system that is updated in a compute shader, that compute shader doesn't want to have to care about the visual bounds of each sprite. Instead, it would model a particle as a single point, and update that point's position each frame.

Without geometry shaders, how would a WebGPU program draw a particle system with variable-sized particles that are updated in a compute shader? Would it require binding the particle buffer as a UAV, and using instanced drawing?

**Comment by kvark** [comment]
@litherum you'd have the vertex shader producing correct vertices, based on the size, i.e.
```
// per-instance particle data updated by a compute shader
struct Instance {
    vec2 pos;
    float radius;
    vec4 color;
};

// vertex buffer that basically defines the particle shape points
struct Vertex {
    vec2 pos;
};

void vs_main(Vertex vert, Instance inst) {
    // scale the position away from the instance center, based on the radius
    vec2 vertex_pos = inst.pos + inst.radius * vert.pos;
}
```

**Comment by RafaelCintron** [comment]
I agree with @kvark we should not have this in WebGPU.  `gl_PointSize` and `gl_PointCoord` require complicated emulation in ANGLE and IE11's WebGL implementation. Tying up the alternate mechanisms (geometry shaders & instancing) with point sprites make it more difficult to combine them with "real" developer content.

**Comment by m-schuetz** [comment]
Hi,

> There is never a case where using point sprites is a good solution: it can always be replaced by instanced geometry rendering 

I don't know about instanced geometry rendering, but the way that ANGLE currently does it (geometry shaders afaik) tends to be about 1.5 to 8 times slower than gl_PointSize. I've had that kind of speed up simply by setting a chrome or firefox browser flag that would use OpenGL instead of ANGLE. 

I've found one benchmark online: [Multiple Ways to Render Point Sprites in DX11](https://blogs.msdn.microsoft.com/ivanne/2012/01/04/multiple-ways-to-render-point-sprites-in-dx11/). According to this benchmark, instanced quad rendering is barely faster than creating point sprites with geometry shaders for large sizes, and some methods that are faster for large point sizes are slower for small point sizes. 

My main use case of WebGL, and WebGPU in the future, is [rendering point clouds](http://potree.org/) so for me it's kind of important to have the fastest point sprite rendering technique available. From my experience, that's GL_POINT with glPointSize in OpenGL, which completely outperforms sized point sprite rendering with geometry shaders in DirectX. Unfortunately I lack the experience to create a point sprite benchmark in DirectX and figure out whether instanced geometry can achieve similar performances, but the current ANGLE implementation does not.

**Comment by kvark** [comment]
> I don't know about instanced geometry rendering,

To clarify: I didn't suggest the use of geometry *shaders* (since WebGPU doesn't have them), what I meant was just instancing.

> the way that ANGLE currently does it (geometry shaders afaik) tends to be about 1.5 to 8 times slower than gl_PointSize.

That's a good reason *not* to expose `gl_PointSize`.

> According to this benchmark, instanced quad rendering is barely faster than creating point sprites with geometry shaders for large sizes.

But it's faster, right? Even the benchmark [author says](https://blogs.msdn.microsoft.com/ivanne/2012/01/04/multiple-ways-to-render-point-sprites-in-dx11/#comment-33):
> Apart from the tri/quad difference, the difference in methods is very much measurable and noticeable. In my tests I can't see why anyone would want to use GS for the given scenario. Vertex Shader Instancing is as flexible and is consistently 10-15% faster than GS.

> Also, some methods that are faster for large point sizes are slower for small point sizes.

Sure! Some things are just not very friendly to the hardware. I'm not sure if we want to expose any feature to cover this case. Sounds like a good thing to follow up with after MVP of the spec/implementations is ready.

**Comment by magcius** [comment]
Note that instancing of vertex counts than the warp size (32) will chew up a full warp on NV, leaving you with terrible occupancy. This is an architectural limitation in the NVIDIA driver. Packing 8 quads into a single instance is the easiest way to do things performantly on NV. Just use degenerate tris if you do not have a multiple of 8 quads.

**Comment by m-schuetz** [comment]
> That's a good reason not to expose gl_PointSize

I don't see how making things equally slow on all platforms in an improvement. I'd love to see things equally fast. 

> Vertex Shader Instancing is as flexible and is consistently 10-15% faster than GS.

As mentioned, I got slow downs by factors of 1.5 times (majority in view-frustum) to 8 times (majority outside frustum) from OpenGL to ANGLE. The improvements of 10-15% aren't anywhere close to covering that loss. 

In any case, I'm going to try an instancing version for point sprites in OpenGL, also accounting for @magcius suggestion, to check whether it can match the performance of GL_POINT.

**Comment by magcius** [comment]
I just checked ANGLE source code, and it appears to use D3D11_PRIMITIVE_TOPOLOGY_POINTLIST assuming that you aren't using the workaround path (which happens on devices with less than D3D feature level 9.3. That shouldn't happen on a DX11 device). I'm not sure why you're seeing poor results -- perhaps write a mail to the ANGLE project.

Geometry shaders don't appear to be used.

https://github.com/google/angle/blob/master/src/libANGLE/renderer/d3d/d3d11/StateManager11.cpp#L3833-L3857

**Comment by potree** [comment]
I've now tested GL_POINTS in an OpenGL framework compared to "point-list" in WebGPU, and both are pretty much the same performance. The difference is that GL_POINTS with a size of 2x2 pixels is barely slower than with a size of 1 pixel, but with WebGPU you'll need to use instancing which has a massive negative impact on performance, and is probably the reason why the DirectX backend in WebGL is up to 8 times slower than the OpenGL backend when it comes to rendering points with a size greater than 1.

> That's a good reason not to expose gl_PointSize.

Yeah, I understand that it's unfortunately not feasibly solvable with DirectX as a backend. From what I've seen so far, using screen-space hole-filling shaders seems to be a faster (and with potentially better quality) than instancing for sizes between 1 to 3 pixels, though.

**Comment by Kangz** [comment]
Closing. The group agreed to only have point with size 1. The builtin to set the point size doesn't even exist in WGSL.
