### ISSUE TITLE
How do we specify the timing of external texture expiration?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3324]
This issue has evolved into a question of the best way to spec external texture expiry. See discussion below.

---

**Original issue summary**

This is probably a fairly minor issue, but deserves to be raised in the group because I misrepresented it in meetings due to my own misunderstanding of how the HTML event loop runs and how it relates to the production of frames. @toji and I found this while working through another spec issue.

In very, very broad terms, the event loop is:

- I thought: loop { run a bunch of tasks, update rendering of visible docs }
- Actually: loop { run one task, update rendering of docs which are due for an update }

The result of this is:

- I thought: stale external textures expire once per frame, just before any document updates if any.
- Actually: stale external texture expire after every single task (but only for top-level tasks, not things like rAF callbacks).

I think that what we ended up speccing actually makes good sense, so I propose we should keep it approximately as is (with possible smaller changes that tie into another issue, #3295).

**Comment by kainino0x** [comment]
cc @shaoboyan

**Comment by kainino0x** [comment]
After running into an implementation bug which is slightly related to this, in Chromium: https://crbug.com/1353621
I've become concerned that running this in every iteration of the event loop is bad for power. Especially, imagine a video is paused and has had its paused frame imported. Now, for *every iteration of the event loop*, we'll be checking its state.

I'd like to see if we can reduce the frequency closer to the vsync frequency, somehow.

Some of our spec mentors at Google suggested enqueueing a task from a frame advancement event, if that were possible, but unfortunately there's no clear way to do so in the HTML spec according to one of our video folks. However it's still an idea to pursue.

**Comment by kainino0x** [comment]
If we are willing to give up some consistency of the timing (across devices and browsers), maybe we can enqueue a task next to the firing of the "timeupdate" event in "[time marches on](https://html.spec.whatwg.org/multipage/media.html#time-marches-on)", or maybe we can register an event handler of that event itself.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-09-07-08-apac-timed#misunderstanding-of-external-texture-expiration-frequency-3324">GPU Web 2022-09-07/08 APAC-timed</a></summary>

* KN: **haven't had time to get back to this one**. Can discuss a little to get people up to speed.
* KG: we can table this, too.
* KN: going on right now - how do we spec when external textures expire? Difficult because there's no algorithm for how frames advance. requestVideoFrameCallback's defined as - on every rAF, see if timestamp's changed, and if so, we'll give you a new frame. Polling based. Specs for video don't have a way to hook events like this. How do we trigger expiration?
* KN: original thing we wrote down, it expires every task. Event loop can run many many times per frame. You wouldn't implement it this way (hopefully). Can optimize, but not clear - what's a better way to spec this? Add a note, "you should optimize this"?
* KN: misunderstanding in the title - didn't realize it was running every task. Thought it was once per frame.
* MM: in researching this - in our platform we have a similar situation for one of our internal objects. Every produced object lives for 1 second. That's an option.
* KN: interesting.
* KG: have come up before - if they need to live for some time, let them live for that time frame.
* KN: we could do this - some other browsers may have something working in a similar way.
* KR: Only caveat is some platforms have a certain number of these frames, and once they hand them out, they can’t make forward progress. This means a second is probably not possible, but maybe something in that direction. 
* MM: that's fair.
* KN: may still be similar solutions.
* MM: ideally this issue would get a more descriptive title.
* KN: **I'll retitle it.**
* KG: **I'll double check with our media people too**.

</details>

**Comment by Kangz** [comment]
The discussion last meeting was about naturally piggy-backing on #3295 which meant different things to participants. Using a new "task queue" in the spec to specify that invalidation happens at task boundary seemed fine to everyone. But when the invalidation should happen was not clear:

 1. it could mean that invalidation should happen as soon as possible, similarly to canvas textures, such that applications might have to important the same video frame multiple times.
 2. or that invalidation should happen as soon as possible when the video has advanced, and application developers must check `GPUExternalTexture.expired` to see if they need to re-important.

The concern with 1) is that it might cause redundant imports, which are taxing to the browser due to various synchronization  and OS overheads (or requiring difficult caching). The concern with 2) is that application developers might rely on some browser behavior where expiration happens (for example) right before requestVideoFrameCallback is called but is actually faster in some others.

@toji and I concurrently came to the idea of having a `GPUExternalTexture.tryRefresh()` method that returns a boolean (name courtesy of @toji, the one I suggested was ridiculously bad). What happens is that when an external texture is first imported, or after a `tryRefresh`, a new task is enqueued on a high-priority queue to make the `GPUExternalTexture` unavailable (not destroyed, just temporarily unavailable). Calling `tryRefresh()` can cause the external texture to be made available again for a short time (~the duration of the task) in which case `true` is returned, or this is not possible and the external texture is effectively destroyed, in which case `false` is returned.

Code using `.expired` looked like this:

```js
function myFrame() {
    // If the application forgets to do this second check, things might still work, which is bad.
    if (externalTexture === null || externalTexture.expired) {
        externalTexture = device.importExternalTexture(...);
        videoBindGroup = ...;
    }

    // Draw the frame using videoBindGroup.
}
```

With `tryRefresh` it looks like the same but applications cannot mistakenly forget to check the external texture status.


```js
function myFrame() {
    // If the application forgets to do this second check, things might still work, which is bad.
    if (externalTexture === null || !externalTexture.tryRefresh()) {
        externalTexture = device.importExternalTexture(...);
        videoBindGroup = ...;
    }

    // Draw the frame using videoBindGroup.
}
```

**Comment by kainino0x** [comment]
I had been tentatively leaning toward option 1 for reliability (removing the `.expired` property again). `tryRefresh()` is an interesting direction. I'm not sure how helpful it is to make the application explicitly choose between refreshing an existing frame and importing a new one. It does mean an application could avoid recreating its bind group, as in your example, if nothing else in it is changing, which is nice. But I'm not sure whether it alleviates the "caching" requirement from option 1 much. Also, we'd still have to handle when an application tries to import again during the same frame.

`tryRefresh()` is very similar to allowing `importExternalTexture()` to refresh a previously-returned `GPUExternalTexture` object and return it again, if the frame hasn't advanced. That wouldn't _require_ the application to have special logic, but it could still optionally check if the object is `===` to determine whether to recreate its bind group.

And that's not too far from option 1. The difference of course is that with option 1 you'd get a new `GPUExternalTexture` each time and would have to recreate the bind group. The cache is still there, but I wonder if implementations could find a way to avoid the synchronization cost of re-importing by using the "refresh and reuse" strategy _internally_, while maintaining that previous bind groups stay invalid. For example, instead of a "destroyed" flag, maybe implementations could have some kind of generation counter, for which refresh of the texture you're using.

**Comment by shaoboyan** [comment]
>What happens is that when an external texture is first imported, or after a tryRefresh, a new task is enqueued on a high-priority queue to make the GPUExternalTexture unavailable (not destroyed, just temporarily unavailable).

My understanding about the key point of `tryRefresh()` is that it tries to force the user to use `GPUExternalTexture` after calling  `tryRefresh()`  in a task scope or browser could return a 'invalid' GPUExternalTexture directly.  It seems like a forced "query then used" model.

I think it could resolve the problem `.expired` has which user imported without checking `expired` attribute from spec level(maybe expired vs ensure invalid).

I'm slighty favour of `tryRefresh`.

From implementation view, `tryRefresh` + `GPUExternalTexture` provides a internal(real frame expired or not)-external(js scope invalid or refreshed) state object. It seems such model could avoid re-import issue without a implicit  `GPUExternalTextureInternal` cache system in browser.
And it left the room for browser implementation (e.g. the real time to expired the video frame)

**Comment by toji** [comment]
One additional point in favor of a `tryRefresh()`-style approach is that the ability to re-use bind groups also means that we gain the ability to effectively use external textures in Render Bundles, whereas previously you'd get at best a frame or two of use out of a render bundle that included an external texture before it expired and invalidated the whole thing. That seems like a significant upside for some use cases.

**Comment by kainino0x** [comment]
I'd still expect those bundles to churn pretty fast generally (maybe video is as low as 24Hz and screen is up to 144 Hz), though for paused videos it could be a significant savings. This does work regardless of whether we do tryRefresh or allow importExternalTexture to return the same object repeatedly.

I have a slight preference for the latter, since it eliminates the reimport-vs-refresh distinction, but it's fair that maintaining the cache may be somewhat complex. I don't have a very strong opinion, we'll just have to test both.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-meeting-2022-11-02-03-apac-timed#how-do-we-specify-the-timing-of-external-texture-expiration-3324">GPU Web meeting 2022-11-02/03 APAC-timed</a></summary>

* SY: … Corentin proposed another option - tryRefresh. Things invalidated after current task. If user doesn't cause tryRefresh, they'll get invalidated external texture. Browser can also say whether the video frame was expired. Left a comment - leaning to option (3). Compared to option (2), if you don't call tryRefresh, can't use external texture across frames. Compared to option (1), gives opportunity to reuse previous external texture, bind group, etc.
* KN: I'm in favor of tryRefresh too. Have an idea of slight variation on it, but generally, think it's a good idea.
* KG: tryRefresh satisfies my concerns. Any concerns?
* KN: any concerns on tryRefresh on the object, rather than allowing import() to return the same object again? Slight preference for the latter. tryRefresh on the object means you could import the texture again, refresh the old one - then have 2 references to the same thing. Seems more complex, would rather avoid. Maybe you can't import if the refresh would succeed. Little odd, maybe fine. Or maybe import gives you the same object again. Caching complexity. Don't leak the object.
* MM: I'm most interested in what happens if the app never calls tryRefresh.
* KN: in that case, if they just import again?
* MM: (1) they import a new frame every rAF. (2) they import a frame once and use it for the next 10 minutes.
* KN: it'll expire. Refresh would be the only way to un-expire it.
* MM: tryRefresh revives lifetime to end of current task?
* KN: takes external texture that's already expired, and attempts to un-expire it. Tells you whether it could do that. Expiry follows previous pattern.
* MM: expiry doesn't mean the bytes are gone?
* KN: correct.
* MM: is'nt this non-portable too? tryRefresh might succeed, or might fail.
* KG: difference - if you don't call tryRefresh, it absolutely won't work.
* BJ: we're consistently expiring the texture at the end of every task, every time. Only way you get back a usable texture for the next task is to try refreshing it again.
* KN: not too concerned about people calling tryRefresh and ignoring the result. If the browser advances the video frame, the video texture will expire, and tryRefresh will fail. Hard to ignore the result.
* MM: say 24 FPS video. 2 rAFs between frames. No tryRefresh => second rAF can't use the external texture?
* KN: correct.
* MM: but it could import a new one?
* KN: yes.
* RC: can't use => you get a black texture?
* KN: you get an error.
* RC: so it is an object.
* KG: invalid object.
* RC: not neutered, a valid JS object.
* KN: it's a validation error in WebGPU.
* RC: ok.
* MM: causes the whole command buffer to not be run. Result potentially disastrous.
* KG: that's why I want people checking the result. Want an API where you have to be paranoid the video's going away. At task boundaries - because it might expire there - force it to go away. Want to keep using it - you need to ask for it to be given back to you.
* KN: strongly agree. Exactly the problem I wanted to solve here.
* KG: interesting idea to have it return the same object. Can't tell when they give us back the same object without making them recreate BindGroups.
* KN: we could also return an new object and make them create new BindGroups. But forcing the creation of new Bindgroups when you don't need them isn't ideal.
* KN: sounds like we're more or less in agreement, anyone object to these two refresh-based options?
* KG: any objections going for returning the same object, 
* KR: I vote for whatever option produces the least garbage, i.e., doesn't require artificially creating new BindGroups.
* KG/KN: OK. Both solutions address this.

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-meeting-2022-11-09-10-apac-timed#how-do-we-specify-the-timing-of-external-texture-expiration-3324">GPU Web meeting 2022-11-09/10 APAC-timed</a></summary>

* KN: thought we resolved this last week. Were going to allow importExternalTexture to return the same object, and were going to propose a PR doing this, but we ran out of time.
* KG: didn't see perhaps one area of consensus?
* KN: I have concerns about tryRefresh. Lets you import the same texture multiple times. Adds complexity.
* KN: thoughts since last meeting:
* KN: when you import an external texture now, we take some texture owned by the decoder and use interop to import it as a Vulkan texture into e.g. Dawn/WebGPU. Maybe multiple, for multiple planes. To use them, we BeginAccess before using it, and EndAccess afterward. If you can import the same frame multiple times and don't cache the results, you can end up importing the same underlying texture multiple times. Use both in same draw call - will need to BeginAccess on both for synchronization, and EndAccess. They may conflict because you're trying to lock the same lock twice. Will probably say, if holding this lock, don't hold it again. Similar cache we'd need to let import() return the same object. I don't think we avoid any impl complexity with tryRefresh. Talked with Corentin too - he was in favor of tryRefresh, but he's convinced by this argument.
* KG: would also make it easier for you if someone imported the same texture twice?
* KN: yes. I think it's a pretty good solution. When I write a proposal - I'll propose a version that returns the same object. No objections to this idea last week.
* KG: **think we can resolve on that. Waiting for a PR**.

</details>

**Comment by kainino0x** [comment]
We still intend to bring the PR back to the CG meeting for confirmation, but adding the "editorial" label to put it on the editorial to-do list and since we broadly have a resolution.
