### ISSUE TITLE
Add precedence rules description into spec

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3346]
In https://github.com/gpuweb/gpuweb/issues/1146 we worked out the precedence rules and the grammar was updated. There is no text (or diagram) explaining the rules outside of reading the grammar.

We should add some text (or preferably text with the image from the last comment in #1146) to describe how precedence works in WGSL.

**Comment by jzm-intel** [comment]
I have a problem about this.

As for C/C++, we have the operators precedence `&` lower than `+`, and if we write expression `1+2&4` and `4&2+1`, these are ***valid*** and should be interpreted as `(1+2)&4` and `4&(2+1)` corresponding to the precedence order.

However for current WGSL specification, `1+2&4` or `4&2+1` are both ***invalid expression***, as [`bitwise_expression`](https://gpuweb.github.io/gpuweb/wgsl/#syntax-bitwise_expression) only may expends the operand to [`unary_expression`](https://gpuweb.github.io/gpuweb/wgsl/#syntax-unary_expression), e.g. `~1u` or `(1+2)` but not `1+2`, and the only valid way is to spell out `(1+2)&4`, `1+(2&4)`, `4&(2+1)` or `(4&2)+1`. So (it makes me thought that) maybe we can not discuss about the precedence relationship between `+` and `&`, since they can not occurs in sequent (like the case of C/C++/Python/Rust...). Such design is not common.
What's more, [`shift_expression`](https://gpuweb.github.io/gpuweb/wgsl/#syntax-shift_expression) and [`multiplicative_expression`](https://gpuweb.github.io/gpuweb/wgsl/#syntax-multiplicative_expression) also require their operand to be `unary_expression`, making `1+2<<3+4` ***invalid*** in WGSL (which is valid in C/C++/Pyhton/...).
So are we going to state that `&` and `<<` and `*` are of the same precedence (since they are of same form in grammar)? Or maybe we can not define precedence for each operator and describe the expression analysis based on precedence, but we should explicit clarify (in human language) the analysis rules according to the grammar definition?

**Comment by dj2** [comment]
Even just providing the image with the explanation from the initial discussion bug would be a great improvement since these rules aren't referenced at all in the spec.

Yes, the WGSL rules are different and require `()`s around more things then you'd see in other languages. That's intentional as the brackets make future reading simpler, and reduce the possiblity of mistakes. Just looking at `1+2<<3+4` I don't actually know what is intended and would have to go lookup the rules for whichever language is being programmed. Writing `1 + (2 << 3) + 4` is a lot clearer.

The spec could state something along the lines of `*`, `<<` and `&` _don't_ associate and `()`'s must be used in order to combine them into a single expression. Then mention that `*`, `/` and `%` associate with left-associtivity. Similar for `+` and `-`.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-09-06-minutes#add-precedence-rules-description-into-spec-3346">WGSL 2022-09-06 Minutes</a></summary>

* ZJ: Had internal discussion around operator precedence like (..) not sure what todo.
* DG: Spoke to MM about this this week. 
* DS: Issue is to add words about precedence. There are currently none.
* MM: What are concerns from JZ specifically.
* ZJ: We have different behaviour for & and | and bitwise logical and and or. Kind of confusing. We treat & for float and unsigned and the bool and vector fo bool say logical & but actually in grammar it's all treated identically. It's different from short circuit &&. However in spec we put short circuit && and logical & in one table while putting bitwise & for other table in bitwise expression. Kind of misleading. Maybe people will think for bool logical & and short circuit & will be similar but different from bitwise.
* DN: **Naming is in conflict, it's an editorial issue. Functions over bool are logical but grammar rules are named same**.
* ZJ: One idea is merge logical and with bitwise expressions of other types. Maybe we should figure out a ?? maybe we could call that bitwise  because we didn't' define bool bit patterns
* MM: Don't want to short circuit bitwise operations. Would be confusing if bitwis was all zero and we short circuited.
* ZJ: We split short circuit already. Vector of bool doesn't do short circuit. Only scalar bool can short circuit.
* DN: Concrete is to rename bitwise expression grammar rule to something better to hopefully clear up confusion. Are you OK with the structure that's there in that you can't mix addition with shift.
* KG: That was deliberate right
* DN: Yes. Just wanted to confirm.
* ZJ: Personally, appreciate making more clear but we have some existing code which just did a+b & c+d and when tint updated we had regression.
* KG: That's fair.
* ZJ: Maybe make more clear to have description in spec.
* KG: **Should find KN's image and put in spec**
* DS: It's linked from issue.
* [https://github.com/gpuweb/gpuweb/issues/1146#issuecomment-714721825](https://github.com/gpuweb/gpuweb/issues/1146#issuecomment-714721825)  ←  Kai’s diagram
* DG: That makes more sense then what read in spec. Should == and != operators be lower precedence then comparison &lt;, >, >=, etc.
* MM: So want a &lt; b == c &lt; d. Want a &lt; b and c &lt; b then then ==?
* DS: No, brackets
* DG: So, (a &lt; b) == (c &lt; d)
* MM: Context of previous resolution was it's a trade off worth it to improve clarity and reduce misunderstanding.
* DG: Trade off, other languages don't necessarily do this.
* ZJ: If we can put arbitrary operators together then we can compare precedence but we just can't put them together. \
KG: KNs thing has some groups and a tree of sets. Should both put the words in the spec can make sure it's what we implemented.
* MM: Sounds like there are at least 2 people who were surprised by this decision. Lets come back in a week and see if worth reopening.
* KG: **Recommend if we're surprised but not sad then we just need to explain better.**
* BC: Would like to add that people being surprised was due to Tints terrible errors. (No cookie for DS.)


</details>
