### ISSUE TITLE
Why does CopyExternalImageToTexture() require RENDER_ATTACHMENT usage?

### ISSUE THREAD

**Issue by shi-yan** [gpuweb/gpuweb#3357]
### Discussed in https://github.com/gpuweb/gpuweb/discussions/3339

<div type='discussions-op-text'>

<sup>Originally posted by **shi-yan** August 16, 2022</sup>
in the current chrome implementation:

```javascript
        const textureDescriptor = {
            size: { width: imgBitmap.width, height: imgBitmap.height },
            format: 'rgba8unorm',
            usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST 
        };
```

does not work and results in a black surface with an error in the console:

texture requires COPY_DST and RENDER_ATTACHMENT

changing it to 

```javascript
        const textureDescriptor = {
            size: { width: imgBitmap.width, height: imgBitmap.height },
            format: 'rgba8unorm',
            usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST | GPUTextureUsage.RENDER_ATTACHMENT
        };
```

fixes it. but why? A render attachment is a target to draw to. Here I only need read-only access.

I can't tell from the spec that RENDER_ATTACHMENT is required here. 

a live example: https://austin-eng.com/webgpu-samples/samples/texturedCube#main.ts

 in the rust implementation, RENDER_ATTACHMENT is not required, see

https://sotrh.github.io/learn-wgpu/beginner/tutorial5-textures/#loading-an-image-from-a-file

They are not consistent? 

```rust
let diffuse_texture = device.create_texture(
    &wgpu::TextureDescriptor {
        // All textures are stored as 3D, we represent our 2D texture
        // by setting depth to 1.
        size: texture_size,
        mip_level_count: 1, // We'll talk about this a little later
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        // Most images are stored using sRGB so we need to reflect that here.
        format: wgpu::TextureFormat::Rgba8UnormSrgb,
        // TEXTURE_BINDING tells wgpu that we want to use this texture in shaders
        // COPY_DST means that we want to copy data to this texture
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        label: Some("diffuse_texture"),
    }
);
 
```</div>

**Comment by shaoboyan** [comment]
(I forget to reply in origin issue, sry)
@shi-yan The reason is that the API `CopyExternalImageToTexture` is not a simple `Copy` op. When you use this API, you'll provide an `GPUTexture` and then call the API `CopyExternalImageToTexture()`
`ImageBitmap` and `Canvas` are containers which might have different `texture_format`, `color_space`, `orientation` from the provided `dst GPUtexture`. If the case requires any convert, we have options:
- Download all the source content to CPU, do conversion, upload to the dst `GPUTexture`. It's a slow path but doesn't need extra usages for the dst texture
- Using an internal rendering pipeline to do the conversion, keeps all the data on GPU. It's a fast path but requires the `RENDER_ATTACHMENT`.
The performance test shows the preference for the `RENDER_ATTACHMENT` usage fast path. So that's why the spec requires this usage.

**Comment by shi-yan** [comment]
Thank you very much!
