### ISSUE TITLE
add AbstractFloat overloads for modf and frexp?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3358]
Currently modf and frexp have overloads for T = f32.  Seems they should allow AbstractFloat as well.
Maybe we didn't do it because the result is a struct, and there's no way to declare a struct with abstract numeric members.

But we can always tweak the explanation differently.

cc: @ben-clayton

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-23-minutes#add-abstractfloat-overloads-for-modf-and-frexp-3358">WGSL 2022-08-23 Minutes</a></summary>

* KG: Called out weird because return structs and don’t have structs with abstract floats
* DN: Only usable if extracted one of the components by name and used that in const-eval expression. Generality issue.
* AB: What happens if result of frexp is assigned to let but it’s an abstract. Does it keep abstract and resolve to f32 at let? Where does conversion occur?
* BC: Same happens with abstract array assigned to let. The assignment does a materialization. Would assume struct with abstract would decay to natural, so f32 if put in let, if in const still abstract
* KG: SO struct of abstract?
* AB: Which user can’t do, but not an issue, already can’t declare these structs
* KG: Ok.
* DN: To handle conversion would need to put entry in conversion rank table for decay path. User can’t declare so only case is builtin, so can just spell out type returned from blah decays.
* BC: Don’t think spec forbids abstract in struct, you just can’t type them.
* KG: Which is fine.
* BC: Don’t see reason why not have abstract version
* KG: Sounds like everyone agrees on complexity but we should probably just do it and come back if it breaks.
* MM: Don’t feel bad about this
* KG: **Resolution, have struct with abstract float and rules to materialize**.
* MM: Sounds good.

</details>
