### ISSUE TITLE
Inconsistent status of leading zeros

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#3415]
In the numeric literals section, the simple case of both decimal and floating point literals ban leading-with-zero cases, but despite that, exponential or hexadecimal versions allow leading zeros.

Should we make this status consistent by allowing leading zeros in all cases?

**Comment by alan-baker** [comment]
Languages that allow octal literals do so by specifying a leading 0. So 0123 != 123 (643 vs 123). My memory is that we wanted to avoid confusion there (and maybe possible expansion). The hexadecimal case on the other hand is unambiguous due to the 0x prefix.

**Comment by mehmetoguzderin** [comment]
@alan-baker It seems that JavaScript (a later change), Rust, and Swift use "0o" (a zero digit and an o letter) as the prefix to start octal literals. I am not leaning towards either side, but it is possible to think of "0o" as the more potential candidate in the octal scenario.

**Comment by mehmetoguzderin** [comment]
We inherit this inconsistency from C.

https://en.cppreference.com/w/cpp/language/floating_literal

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-09-06-minutes#inconsistent-status-of-leading-zeros-3415">WGSL 2022-09-06 Minutes</a></summary>

* MOD: Stems from float point integer case has limitation as integers but exponential case allows leading zeros. Either we change that to not allow or allow for everything. Looking for opinions
* KG: With AB. In particular, typing octal literals is usual a mistake, typing hex values are very useful to pad with zeros.
* DG: Confused, if we added octal we'd have a 0o prefix?
* KG: It's a potential, but don't want to discuss now, so no octals for v1
* DG: But wouldn't have leading zero for octals, so could allow them?
* KG: Could if we wanted too. Not trying to torpedo because I don't like octals, but one other concern in JS 0123 is 83. In the spirit of not being surprising to JS developers, leading zeros is something we want to tell folks to not use.
* MM: Is proposal to make leading zero a compile error, or make it work?
* KG: Believe it's a parse error currently
* MOD: Spec doesn't want leading zeros. But floating point with exponential doesn't reject.
* MM: So looking for consistency?
* KG: For exponential form you mean 10e3 form?
* MOD: Yes, 00010e3 is allowed.
* KG: Don't love it but don't care that much. Feels like general attitude is to not care about octals, but hex case we want leading zeros. Exponential case take or leave it. Inclined to forbid it as don't allow it in normal form case. Would be weird if we allowed it.
* DN: Would want to check what c and c++ do for floats for exponent and fraction parts. Agree with summary so far and think it's ok to have integers different from floats but want to make sure we're being consistent.
* MM: Checked JS 2e3 is 2000, 02e3 is error. 2e03 is 2000.
* DN: First character indicates octal but seeing e means exponent.
* MM: &lt;some things that are same result>
* MOD: Can you start floating point with zeros even with a dot inside.
* MM: 00.5 is parse error.
* DS: 0.5 as a parse error would be weird.
* JB: Reviewed regexes and patches to regexes, think they're fine and don't need to change. Please lets not implement this.
* MOD: Think we need to change regex to not permit leading zeros for floating point cases.
* JB: In the exponent of the floating point.
* KG: Happy to go towards JS here. Either PR to more closely match JS or to have a strong argument, not just symmetry.
* DN: Reading c++14, allows digit sequences, which allows zeros for fractional constant and exponent. So, we match c++14 for floats.  Section  [lex.fcon]
* KG: **If have specific things to change, add them specifically otherwise we'll close it.**
* MOD: **Will check and put up a PR if I find C++ to be different**.
* MM: Stated that humans have solved parsing literals and should take parsing rules from some other language. Innovating here isn't worth it.

</details>
