### ISSUE TITLE
Override constant should not provided by pipeline as NaN or Inf

### ISSUE THREAD

**Issue by jzm-intel** [gpuweb/gpuweb#3435]
We have some discussion on forbidding `NaN`, `Inf` or other invalid number or expression to be const-expr or override-expr, thus also initializer of constant and override values, in issue #3253.
In this way, we should also require the pipeline-override values provided by by the WebGPU pipeline-creation method must not be invalid, NaN, or Inf after converted (from `double` type in JS) to corresponding WGSL types. This validation rule, if shall be added, may occurs under [GPUProgrammableStage](https://www.w3.org/TR/webgpu/#GPUProgrammableStage) in WebGPU Spec.

**Comment by Kangz** [comment]
**Consensus: WebIDL doesn't allow passing infinity and NaNs from JS to the browser, so this would naturally be a type error.**

For Dawn's webgpu.h (because I believe that's where the issue originated), I think we should add the validation, but it's non-observable from JS.

**Comment by kainino0x** [comment]
https://webidl.spec.whatwg.org/#idl-double

**Comment by jzm-intel** [comment]
A concern is that although WebIDL double type forbids NaN and Inf in f64, a finite double value can still be not exactly-representable by and/or exceed the valid range of target type of WGSL shader (`f32`, `i32`, `u32`, and especially `f16`). For example, provides `1.0e128` to a `f32` override constant, or `1.0e20` to a `f16` override, will lead to `Inf` in `f32` and `f16` correspondingly.

Currently the Spec says a given double would be *"converted to the WGSL data type of the corresponding pipeline-overridable constant (bool, i32, u32, or f32) via [an IDL value](https://webidl.spec.whatwg.org/#dfn-convert-ecmascript-to-idl-value) ([boolean](https://webidl.spec.whatwg.org/#idl-boolean), [long](https://webidl.spec.whatwg.org/#idl-long), [unsigned long](https://webidl.spec.whatwg.org/#idl-unsigned-long), or [float](https://webidl.spec.whatwg.org/#idl-float))"*. I understand that this sentence suggest that the conversion algorithms described in WebIDL should be used, in particular [double to float(`f32`)](https://webidl.spec.whatwg.org/#es-float), [double to long(`i32`)](https://webidl.spec.whatwg.org/#es-long) and [double to unsigned long(`u32`)](https://webidl.spec.whatwg.org/#es-unsigned-long), and the least two algorithms further refer to [`ConvertToInt` algorithm](https://webidl.spec.whatwg.org/#abstract-opdef-converttoint).

The [double to float(`f32`)](https://webidl.spec.whatwg.org/#es-float) does throw TypeError if source double is Nan, Inf or out of f32 bound, as expected. For double to `f16` conversion, we first convert the double to f32, resulting a finite f32 value or TypeError, then convert the f32 value to f16 following [the algorithm defined in WGSL spec](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion). **If such `f32` value is out of `f16` bound, WGSL spec [only require *shader-creation error if the original value is of abstract numeric type*](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion:~:text=A%20shader%2Dcreation%20error%20results%20if%20the%20original%20value%20is%20of%20abstract%20numeric%20type), otherwise no error would be generated and Inf of `f16` may be generated.** I think maybe an explicit requirement of WebGPU validation on this case (double to `f16` conversion OOB) is valuable.

I also noticed that the [`ConvertToInt`](https://webidl.spec.whatwg.org/#abstract-opdef-converttoint) defined in WebIDL describing double to `i32`/`u32` will throw TypeError when source double value is out of bound in target integer value **if and only if `[EnforceRange]` extended attribute are used to target IDL type**. ***Otherwise Nan, Inf, or OOB values will not cause TypeError***, but will be clamped if `[Clamp]` extended attribute used or modulo to `2^32` if no extended attribute is given. Maybe we should explicit call out `[EnforceRange] long` (or `[Clamp] long`?) in Spec, rather than just `long`, if we are not intend to do the modulo?

**Comment by jzm-intel** [comment]
So since the WebIDL double-to-float(`f32`) algorithm forbids converting a double value, which is finite but out of `f32` range, to float type by throwing TypeError, maybe we shall do similar thing for f16, i.e. throw a validation error if providing a finite but out of `f16` range double value to a WGSL `f16` override constant.

Also I think we should make providing a double value out of `long` or `unsigned long` range to a WGSL `i32` or `u32` override constant a TypeError (by explicitly using `[EnforceRange] long` and `[EnforceRange] unsigned long`) or a validation error (by adding a explicit validation rule), rather than silently clamp it without warning programmer. One step further, we may validate that a given double value is exactly-representable in target types (`i32` or `u32`), or a validation error should occurs. In this way we can avoid override constant values getting changed (clamped or rounded) without knowing it and get unexpected results when running shader.

If I get it right, WGSL WG also tend to validate invalid values and non-exactly-representable values as many and as early as possible, and using/causing invalid values in compile-time will result in shader-creation error. We can do the same thing for override constants in WebGPU.

@dneto0 Would you have any comments from WGSL's perspective? Thanks.

**Comment by kdashg** [comment]
I think it would be fine if we merely warned in console, but limped along in the case where we are handed e.g. f32::max+1 via Number. I think Clamp might make sense, rather than showing nothing in this case, given that these feel like they're likely to be generated programatically by the webapp at runtime.

**Comment by kainino0x** [comment]
I think the other place in the API spec where we do numeric conversions to WGSL is here https://gpuweb.github.io/gpuweb/#dom-gpurenderpasscolorattachment-clearvalue
Note there, we use `unrestricted float`. I think this was specifically so that it could not throw an exception, since the conversion is expected to be done in the GPU process.

We similarly expect overrides' conversions to be done in the GPU process, so we shouldn't throw exceptions. We can either use conversions where exceptions are impossible, or use exception catching to describe the behavior.

---

As a summary/reference:

For integers there are three options in WebIDL. Note, in all 3 cases the fractional part is dropped silently.

- default: Out-of-range values are converted "modulo 2<sup>bitLength</sup>". NaN and infinities are converted to 0.
- `[Clamp]`: Out-of-range values and infinities are clamped to the range. NaN is converted to 0.
- `[EnforceRange]`: Out-of-range values and NaN and infinities throw an exception.

For floats there are 2 options:

- `unrestricted float`: Out-of-range values are converted to infinities. Infinities are preserved. NaN is normalized to a particular NaN representation (`0x7fc00000`).
- `float`: Out-of-range values and NaN and infinities throw an exception.
- (Note there is no Clamp option, but we could easily define our own clamping on top of `unrestricted float`.)

Reading the WGSL f32->f16 conversion, it appears it gives us pretty much exactly the same choice as `float` vs `unrestricted float` depending on whether we feed in an abstract numeric type - which we could do.

**Comment by kainino0x** [comment]
Resolved to do a validation error, and do that for the clearValue (color/depth) as well

**Comment by kainino0x** [comment]
FWIW, for clear values, the conversions are only to i32/u32/f32, not to arbitrary texture formats, because we define them in terms of how they'd be written out by a WGSL shader that outputs i32/u32/f32. So there would be no validation error for example if you output 2.0 into a unorm texture.
