### ISSUE TITLE
wgsl: atan2 result depends on signs of both arguments, not spec'd

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3437]
Defining it in terms of e1 / e2 loses information about the signs of e1 and e2, which are significant.

E.g. https://en.cppreference.com/w/cpp/numeric/math/atan2 has a colour chart showing how the sign affects the result.

SPIR-V extended instruction qualifies:

>  The signs of x and y are used to determine what quadrant the angle is in.

MSL has a table of implementations of atan2(y,x) as:

> Implemented as
if x > 0, atan(y / x),
if x < 0 and y > 0, atan(y / x) + M_PI_F
if x < 0 and y < 0, atan(y / x) – M_PI_F
and if x = 0 and y = 0, is undefined.

**Comment by zoddicus** [comment]
For MSL, what about x < 0 and y = 0?

**Comment by zoddicus** [comment]
Looks likes DirectX does the following, https://github.com/microsoft/DirectXShaderCompiler/blob/b3101a2feb078a9da9c78b44d9b61c8c312b646e/lib/HLSL/HLOperationLower.cpp#L1530:
```
// x > 0 -> atan.
// x < 0, y >= 0 -> atan + pi.
// x < 0, y < 0 -> atan - pi.
// x == 0, y < 0 -> -pi/2
// x == 0, y > 0 -> pi/2
```
which follows the wiki definition of atan2 https://en.wikipedia.org/wiki/Atan2

The whole what to do around y/x = 0 is a giant pain.
Previously  in the CTS it has accepted anything in [-π, π], because some implementations will return 0, π/2, -π/2, π, or -π depending on what the internal details, i.e. does it approach from the left or right, does it hard code these cases, etc.

**Comment by zoddicus** [comment]
I have written an updated version of the CTS atan2 tests based on this discussion and looking at the DirectX code.
https://github.com/gpuweb/cts/pull/1837

**Comment by dneto0** [comment]
Staring at the MSL description, it doesn't cover the x < 0  and y = 0 case.

**Comment by dneto0** [comment]
@zoddicus ' s work on drafting the CTS updates made us realize that the function has dramatically terrible error bounds as the point approaches the origin.  See comment at https://github.com/gpuweb/cts/pull/1837/files#r978058671 

So the spec's accuracy table should say the bounds only hold when y is normal (at best).
