### ISSUE TITLE
Allow signedness to differ between integer texture builtin arguments (`C` template)

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3536]
Consider the overload:

| Parameterization | Overload |
|-|-|
|`C is i32 or u32` | `fn textureLoad(t: texture_depth_2d_array, coords: vec2<C>, array_index: C, level: C) -> f32` |

There's no good reason that vector element type of `coords`, `array_index` and `level` all need to be the same signedness. This all-must-be-signed or all-must-be-unsigned is going to add confusion to overload mismatch failures, and adds a bunch of complexity and messy casts into translating from SPIR-V to WGSL†.

I propose that we separate out the template type for each integer parameter, e.g.:

| Parameterization | Overload |
|-|-|
|`C is i32 or u32`<br>`I is i32 or u32`<br>`L is i32 or u32` | `fn textureLoad(t: texture_depth_2d_array, coords: vec2<C>, array_index: I, level: L) -> f32` |

---

† SPIR-V -> WGSL could benefit from using the signed / unsigned overloads to avoid casts, however doing this is tricky - as you need to keep track of the signedness of all the integer parameters, and cast those that don't match the picked overload. Tint continues to cast all unsigned integer arguments to signed to ensure that we translate to a valid WGSL overload, but mixed parameter signedness could produce significantly more readable WGSL.

**Comment by ben-clayton** [comment]
I'd argue that what we have right now is more complex for the end user and tooling.

**Comment by dneto0** [comment]
We should revisit to understand the tradeoffs

**Comment by ben-clayton** [comment]
I've also realized that we can't safely introduce this post-V1 without risk of breaking shaders.

Consider:

```ts
let x = textureLoad(tex, vec2<u32>(0), 0x80000000)
```

Today, the `vec2<u32>(0)` will force the `C` template type to `u32`, and so `0x80000000` will materialize to `u32`.

If we allowed *each* parameter to be either `i32` or `u32`, `0x80000000` will attempt to materialize to `i32`, but will error that it does not fit.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-10-25-minutes#allow-signedness-to-differ-between-integer-texture-builtin-arguments-c-template-3536">WGSL 2022-10-25 Minutes</a></summary>

* BC: Have discussed before and got consensus on post-v1. Since then, abstracts appeared and have been trying ot implement some spec changes for texture builtins. Integers being signed or unsigned. Thought it was odd that all integer params of builtins all have to be signed or all unsigned, no ability to mix. Implementing this was really awkward. Translating from spv -> wgsl, spv doesn't care about signed vs unsigned, for WGSL have to be same across the board. To do without casts all the time is terrible. Bunch of tests very difficult to do. Just trying to write, landing this and spent a few days writing WGSL and diagnostics are confusing as don't expect coord sign to affect level of detail sign. Orthogonal things. Keps the spec simple, to tie together. Don't think we could change this without breaking shaders, gave example of materialization failing if each type is independent. Contrived example, but still impossible for us to do without possible breaking changes. Would like to propose making a separate generic type per thing and allow each to be signed/unsigned.
* JB: The way sign is bound together and spec simplification makes sense and could be confusing behaviour. Should consider just being bold and making everything signed all the time across the board.
* MM: Long discussion, months for array indexing sign vs unsigned. Was hard to get consensus there.
* JB: Was that discussion before or after abstract?
* MM: Before.
* JB: Does abstract int change that discussion?
* BC: Not entirely. Abstracts naturally decay to signed, have made decisions like the query methods for number of levels are unsigned. Get mismatch from what you type and hwat is return. Lot of concerns come from there. Shaders to be fixed up are a bunch of that. People take return and miss match.
* JB: That's an argument for mixed
* KG: This proposal was to boil the ocean. Just have signed for … ?
* BC: Went other way, query methods went from signed to unsigned. 
* KG: Think consensus thing is to allow anything for these. Just feels weird given we don't normally freely coerce between signed and unsigned except when using builtin seems hypocritical. If wrote function yourself would have to pick one.
* MM: To restate, if i wanted to call textureSmaple and pass unsigned i just do it, it works. If i want to call textureSample and pass signed it just works. However if i wrote a wrapper for textureSample this could not be said and that's unfortunate.
* AB: Bigger complaint seems to be we don't allow overloads.
* JB: Don't want to write both copies of the function. It's not that i wish for overload, i wish for implicit coercion. We're in a different place now with better literals. Feels like lot of discussion were around code I could write and had to do stuff around out. Things go more smoothly when you just have one thing. Don't want to re-open everything, getting close tot he end. Disentangling those arguments makes sense but seems like, it's only going to get worse in the future. Seems ike we could simplify stuff and end a whole lot of questions if everything was signed except if you have representation things.
* MM: One argument, there is no texture for which that upper bit is meaningful. So, feel like it doesn't' really matter and let authors write what they want, if it's unsigned it's fine. The same can't be true for user code. That wrapper function could do anything, could be doing math in there. So the user code might be sensitive to the top bit, but the texture function isn't. Should meet authors where we are and accept this PR.
* JB: Not concerned about Naga implementation as far as that's concerned.
* BC: At this stage, trying to change these again, now in more relaxed state, constraining to signed/unsigned at this stage would be unplatiable. Lots of shaders out there that work. Preference is allow signed/unsigned for each param.
* KG: Can we just resolve to do that and also resolve to feel appropriately sad it isn't as pure as we'd like
* JB: I'm sad.
* KG: So, accept this PR.
* AB: Have to make PR.
* KG: Resolved.

</details>
