### ISSUE TITLE
Impact of WGSL Uniformity Check Compatibility on Performance

### ISSUE THREAD

**Issue by hana-alice** [gpuweb/gpuweb#3583]
Lately I've been trying integrate our engine [Cocos](https://github.com/cocos/cocos-engine) with WebGPU, when runing some test cases it works on chromium 105 with several uniformity warnings, when it comes to chromium 108 I get errors instead of warnings on the uniformity check. 

Top of our engine the shading language is GLSL, and it's compiled to SPIR-V then using SPIRV-cross to match shader language by different backends. So I have made some changes on the GLSL to get rid of this validation: [PR here](https://github.com/cocos/cocos-engine/pull/13180/files). 
Here's the performance test:

A drawcall of static scene with soft CSM shadow:
![csmafter](https://user-images.githubusercontent.com/18626925/200492256-44eb39ac-6e4a-48f7-bb10-21c82f7c8f82.png)
before change: 175,264 ns
after change: 174,709 ns

A drawcall of 600 instancing model animation scene with soft CSM shadow:
![animafter](https://user-images.githubusercontent.com/18626925/200501322-80d52358-a70b-400d-898c-6fa9df20d0e7.png)
before change: 377,952 ns
after change: 380,043 ns

Statistics from PIX, test for 4 times for each scene, drop the most different one and get the average of the rest, on windows 11 with gtx 1660 super.

Since changing GLSL has a influence on all the other backend, so I have had a test on other backends:
static scene 
| hardware | before change(μs) | after change(μs) |
| -- | -- | -- |
| samsung Note10+ snapdragon855:GLES | 2981 | 3663 |
| samsung Note10+ snapdragon855:VULKAN | 2707 | 3706 |
| mac intel: Metal | 430 | 594 |
| iphone SE2 A13: Metal | 1510 | 1490 |
| WebGL on PC win11 1660super | 60fps | 60fps |

animation scene
| hardware | before change(μs) | after change(μs) |
| -- | -- | -- |
| samsung Note10+ snapdragon855:GLES | 2601 | 2331 |
| samsung Note10+ snapdragon855:VULKAN | 1917 | 2221 |
| mac intel: Metal | 2340 | 1550 |
| iphone SE2 A13: Metal | 1040 | 696 |
| WebGL on PC win11 1660super | 15fps | 17fps |

Statistics with Metal from xcode, others from renderDoc.
Sorry for not finding proper tools for WebGL so I record the fps here.
Same time I get the this from xcode:

A drawcall of static scene with soft CSM shadow
| -- | before change | after change |
| -- | -- | -- |
| GPU Time | 590μs | 609μs |
| DRAM Bandwidth | 5.87 | 4.73 |
| Shader Core Time | 97.11% | 95.74% |
| Shader Core Stall Time | 0.25% | 2.01% |
| Texture Unit Time | 93.34% | 90.94% |
| Texture Unit Stall Time | 0.41% | 0.75% |

A drawcall of 600 instancing model animation scene with soft CSM shadow
| -- | before change | after change |
| -- | -- | -- |
| GPU Time | 2.81ms | 1.55ms |
| DRAM Bandwidth | 9.5 | 4.56 |
| Shader Core Time | 81.61% | 96.10% |
| Shader Core Stall Time | 16.96% | 2.50% |
| Texture Unit Time | 97.23% | 97.25% |
| Texture Unit Stall Time | 5.17% | 13.45% |

Hope this helps.

update: fix typo

**Comment by jzm-intel** [comment]
FYI, as mentioned by @jrprice's [comment](https://bugs.chromium.org/p/tint/issues/detail?id=1554#c10), "The WGSL spec has been updated such that non-uniform control flow will reconverge when functions return", as is noted [here](https://gpuweb.github.io/gpuweb/wgsl/#uniformity:~:text=Note%3A%20A%20WGSL%20implementation%20will%20ensure%20that%20if%20control%20flow%20prior%20to%20a%20function%20call%20is%20uniform%2C%20it%20will%20also%20be%20uniform%20after%20the%20function%20call.), and "this change has now been [implemented in Tint](https://dawn-review.googlesource.com/c/dawn/+/107364)" in Nov 1. 

I notice that in your Cocos PR, some modification is about early returning in a function. This case was once indeed causing uniformity issues, but it should has now get fixed in WGSL spec and latest Tint implementation as well.

Maybe you can use the latest Chrome Canary, which is now Version 109.0.5408.0, to test and see if the validation error is still happening for your origin shader.

**Comment by dneto0** [comment]
> I notice that in your Cocos PR, some modification is about early returning in a function. This case was once indeed causing uniformity issues, but it should has now get fixed in WGSL spec and latest Tint implementation as well.

It looks like *all* the changes in the Cocos PR are to avoid returning early. 

The Tint fix had two parts: (1) update the analysis to match the updated spec, and (2) update Vulkan SPIR-V code generation to rewrite functions to avoid the early return.
In particular, the code generation for other platforms is not changed because both Metal and DX experts tell us we would not have to.

**Comment by dneto0** [comment]
FYI.  The WGSL spec change is #3524, linking back to original issue #3007   (It's interesting to have performance numbers)

**Comment by hana-alice** [comment]
Thanks for knowing this! Works fine with latest Chrome Canary.
