### ISSUE TITLE
consider expanding concept of full reference: include indexing into single-element array, and member access of single-member struct?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3605]
https://gpuweb.github.io/gpuweb/wgsl/#func-var-value-analysis
 defines "full reference" "full assignment" "partial reference" "partial assignment"

The intent is that full assignment cuts the reaching-definitions chain.  The intent is that assignment via full reference will set all memory locations in the variable, whereas assignment via partial assignment will *not* set all memory locations in the variable.

But there are funky cases with 
* Structs having a single member
* Arrays with a single element.

Example:
```rust
struct S { member: i32; }
fn foo() {
  var s: S;
  var arr: array<i32,1>;

  // s.member is not a "full reference", by spec, even though
  // it covers all (accessible) memory locations of 's'.
  s.member = 1;  // Analysis says this is not a full assignment
  // arr[0] is not a "full reference"
  arr[0] = 1; // Analysis says this is not a full assignment. 


  s.member = 2;
  let m = s.member;  // uniformity analysis thinks the 's.member=1' assignment "reaches" 's' here.

  arr[0] = 2;
  let a = arr[0]; // uniformity analysis thinks the 'arr[0]=1' assignment "reaches" 'arr' here.

}
```

So the uniformity analysis ends up being conservative in this case. It's harmless, but a slight infelicity.

It would make the spec more complex to fix this.
It's not clear it would be very useful.  But filing this for consideration.
I'd like @jrprice  and @alan-baker to comment.

**Comment by dneto0** [comment]
The extra complexity may be worth it because it would allow us to keep the clear picture of what a "full assignment" and "partial assignment" are:

>  An assignment is a full assignment if:

> * The variable’s [effective-value-type](https://gpuweb.github.io/gpuweb/wgsl/#effective-value-type) is a [scalar](https://gpuweb.github.io/gpuweb/wgsl/#scalar) type, or 
> * the variable’s [effective-value-type](https://gpuweb.github.io/gpuweb/wgsl/#effective-value-type) is a [composite](https://gpuweb.github.io/gpuweb/wgsl/#composite) type and each [component](https://gpuweb.github.io/gpuweb/wgsl/#components) of the composite is assigned a value.

> Otherwise, an assignment is a partial assignment.

**Comment by dneto0** [comment]
Handling the structure case is straighforward.

Handling the array case is more nuanced.  If the index is a runtime-expression, then
* Either it is 0, and all is ok for reads and writes
* Or it is out of bounds, and:
    * For stores, it either writes the only element, or the store does not occur, in which case it is not a full assignment
   
It's that last case (no store) which invalidates the reaching analysis.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-11-22-minutes#consider-expanding-concept-of-full-reference-include-indexing-into-single-element-array-and-member-access-of-single-member-struct-3605-">WGSL 2022-11-22 Minutes</a></summary>

* DN: There’s a sentence that tries to explain why we have the concept of a full reference. There are two ways to d this: have the full reference, versus notice overwrites of structs with a single member / arrays with a single element. (because they’re both the same memory - JB). There is a PR that Alan has reviewed that keeps that current rule, but has the extra explanation of the case of a struct with a single member, or an array with a single element.
* KG: Sounds tolerable. We still support full assignment if want to. This is just a case where the programmer can do something that should work, but doesn’t happen to at the moment.
* DN: Intent is not expand the expand concept of full reference - just wordsmith to make the explanation less confusing.
* **RESOLVED: take this change**

</details>
