### ISSUE TITLE
texture size requirement and load process

### ISSUE THREAD

**Issue by caxieyou** [gpuweb/gpuweb#362]
Hi There
I am trying to learn the framework and sample code from
https://github.com/austinEng/webgpu-samples
listed on the website.

So several questions:
1. I read the loading texture process from here:
https://github.com/austinEng/webgpu-samples/blob/master/utils.js#L23
so is webgpu has specific requirement for the size of the image?
is it just needs the time of 4 with width? no need to care about the height?
or exponential factor of 2 like 1024 or 2046?

2. the shader, is it has to be SPIR-V?

3. so the loading image function createTextureFromImage is using the async keyword. i suppose this is because when you bind the buffer data to the texture handler is an asynchronous operation since it happens inside the GPU. However even so, with "async and await" it seem like the CPU side can control the flow of GPU?
Any command in the queue if i use the await, then I can put something like a barrier to stop the GPU queue? Still sounds wired because you can only

Thanks for any help and if this is not the right place to discuss this, please let me know.

**Comment by Kangz** [comment]
> Hi There
> I am trying to learn the framework and sample code from
> https://github.com/austinEng/webgpu-samples
> listed on the website.
> 
> So several questions:
> 
> 1. I read the loading texture process from here:
>    https://github.com/austinEng/webgpu-samples/blob/master/utils.js#L23
>    so is webgpu has specific requirement for the size of the image?
>    is it just needs the time of 4 with width? no need to care about the height?
>    or exponential factor of 2 like 1024 or 2046?

WebGPU doesn't have size requirements for images except that they must be less then 8k in each dimension (or 4k I can't remember). The reason the code looks complicated is because of the rowPitch constraint in buffer to texture copies that it should be a multiple of 256. The code could be simplified by using `copyImageBitmapToTexture` but I don't think any browser implements it yet.

> 2. the shader, is it has to be SPIR-V?

Chrome's implementation that these samples were written against uses SPIR-V but the shading language for WebGPU isn't decided yet.

> 3. so the loading image function createTextureFromImage is using the async keyword. i suppose this is because when you bind the buffer data to the texture handler is an asynchronous operation since it happens inside the GPU. However even so, with "async and await" it seem like the CPU side can control the flow of GPU?

The use of async is only for this line: `await img.decode();` and isn't required for the WebGPU operations.

>    Any command in the queue if i use the await, then I can put something like a barrier to stop the GPU queue? Still sounds wired because you can only
> 
> Thanks for any help and if this is not the right place to discuss this, please let me know.

The best place for this would have been on the samples repo directly but here is probably ok too.
