### ISSUE TITLE
Suggestion to add function domains

### ISSUE THREAD

**Issue by munrocket** [gpuweb/gpuweb#3628]
Right now log, log2 note in wgsl spec is not correct
```
Note: The result is not mathematically meaningful if e < 0
```
It should be
```
Note: The result is ill-defined when if e ≤ 0
```
But writing it everywhere maybe not so good practice, instead it can be table like that for all special functions

| Overload | @const fn log(e: T) -> T |
| -- | -- |
| Parameterization | ... |
| Description | ... |
| Domain | e > 0 |

It will be better? Also we still not specified pow.

**Comment by dneto0** [comment]
We've had this request before: #3220

I think we had that inf vs. NaN split when drafting it.

In IEEE floating point log(0) is negative infinity, and signals divideByZero.
log(x) for x < 0 is NaN and signals an "invalid operation"

> The invalid operation exception is signaled if and only if there is no usefully definable result. In these cases
the operands are invalid for the operation to be performed.
For operations producing results in floating-point format, the default result of an operation that signals the
invalid operation exception shall be a quiet NaN that should provide some diagnostic information.

But point taken:  
* When it's a const-expression log(0.0) produces a shader-creation error, just like for log(-5)
* Because neither inf or nan are required to be supported, both may yield an indeterminate result.


Thanks for labeling this so I'd see it.  :-)

**Comment by munrocket** [comment]
Oh, it's duplication. I will close it then.
