### ISSUE TITLE
Restrict grammar of `texture_and_sampler_types`

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#3672]
> texture_and_sampler_types :
> ...
> | [storage_texture_type](https://gpuweb.github.io/gpuweb/wgsl/#syntax-storage_texture_type) [less_than](https://gpuweb.github.io/gpuweb/wgsl/#syntax-less_than) [texel_format](https://gpuweb.github.io/gpuweb/wgsl/#syntax-texel_format) [comma](https://gpuweb.github.io/gpuweb/wgsl/#syntax-comma) [access_mode](https://gpuweb.github.io/gpuweb/wgsl/#syntax-access_mode) [greater_than](https://gpuweb.github.io/gpuweb/wgsl/#syntax-greater_than)

Considering we now (https://github.com/gpuweb/gpuweb/pull/1794) only have write-only storage textures would it make sense to only allow 'write' access in the grammar for those?

**Comment by teoxoy** [comment]
We also don't support write-only storage buffers (the only other place where `access_mode` is used). So, it might be worth changing `access_mode` to only consist of `read` and `read_write`?

Just some suggestions/questions, feel free to close the issue if it's not worthwhile.

**Comment by dneto0** [comment]
Thanks for the suggestion.

This was discussed in the 2022-12-13 meeting.

We've discussed this kind of thing  before, and decided keep validation in a post-parsing phase.
It keeps the grammar simpler, because there are fewer rules, and allows easier evolution of features with less churn in the parser.
Also, there is value to always referring back to the same grammar rule.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-12-13-minutes#restrict-grammar-of-texture_and_sampler_types-3672">WGSL 2022-12-13 Minutes</a></summary>

* KG: Think we’ve talked about this kind of thing before and leaned on doing the validation in validation rather than gramm.
* DN: Yes.
* AB: There’s value in always referencing the same grammar element from many places.
* **Resolved: Leave restriction in the validation instead of the grammar.**

</details>
