### ISSUE TITLE
Explainer is marked as a "living standard"

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#3687]
See [here](https://gpuweb.github.io/gpuweb/explainer/#:~:text=WebGPU%20Explainer-,Living%20Standard%2C,-14%20December%202022). There must have been something we forgot to change in the bikeshed template.

**Comment by kainino0x** [comment]
Huh, I could swear I chose a different status when I created the bikeshed doc. That said I don't actually know which is the correct one. I think I chose `LD` "Living Document" at the time? `LS` "Living Standard" is actually a [non-w3c status](https://tabatkins.github.io/bikeshed/#metadata) so I don't think it has a very strongly specified meaning. All of the W3C document types are described [here](https://www.w3.org/standards/types) but I'm not sure if we should use one of them or not. These seem like the likely options to me:

- `LS` Living Standard
- `LD` Living Document
- `CG-DRAFT` W3C Draft Community Group Report (unsure of the implications)
- `ED` W3C Editor's Draft (unsure of the implications)
- `NOTE`/`NOTE-ED`/`NOTE-WD` W3C Note (It seems these can't be published by community groups)

**Comment by tidoust** [comment]
I don't think the status matters that much for documents published under `https://gpuweb.github.io`. A more correct status would be `CG-DRAFT` since the Community Group develops the document. If you prefer `LD`, that's all fine, no reason for anyone to complain. `ED` would work too. I don't see any implication regardless of the status you choose.

What's more important is the copyright and license under which the document is published. Right now, it is that of a `CG-DRAFT` document:

> [Copyright](http://www.w3.org/Consortium/Legal/ipr-notice#Copyright) © 2022 the Contributors to the WebGPU Explainer Specification, published by the [GPU for the Web Community Group](http://www.w3.org/community/gpu/) under the [W3C Community Contributor License Agreement (CLA)](https://www.w3.org/community/about/agreements/cla/). A human-readable [summary](http://www.w3.org/community/about/agreements/cla-deed/) is available.

That seems good to me. Just make sure that remains intact if you pick up another status.

Side note: If you also wanted to publish that document as a Working Group deliverable under `https://www.w3.org/TR/`, that is doable too. Published /TR status would then be one of `NOTE-WD` or `NOTE`. Overhead would be low (no strong requirement for a Working Group to publish notes), but it's unclear to me that there are compelling reasons to do so.
