### ISSUE TITLE
wgsl: refine range diagnostic filters: where they can be applied, and associated affected ranges

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3689]
Followup to #3683 

There is ongoing discussion about range diagnostic filters:
    - As #3683 is written, they go on call phrases, and the affected range includes the call itself and evaluation of arguments
    - As originally drafted, it was only for the call itself, not the evaluation of the arguments.  This is more "surgical".
    - There's a desire to be able to apply it on some or all statement kinds, and function declarations.
    - There's a programmer's desire to apply it to any expression.  But this can be challenging to implementations.

When applying to statements:
- control flow like "if", "switch", "loop", "for" and any compound statement are good and clear cases
- variable and let declarations are less clear, as it may be too easy to interpret the diagnostic control as applying to any downstream use of that variable and let-declared name.

       var<private> d: f32;    
       fn helper() -> vec4f { 
              // diagnostic control only affects the execution of the declaration.
             @diagnostic(off,derivative_uniformity) dcopy = d;  
             // This textureSample will flag a uniformity error, but that may be unexpected.
             if (dcopy < 0.5) {  return textureSample(t,s,vec2(d)); } 
      }
    
- assignments introduce an apparent ambiguity:

            // Does the diagnostic control affect the entire statment, or the LHS reference expression?
            @diagnostic(off,derivative_uniformity) x[i32(textureSample(t,s,vec2(d))).x)]  = textureSample(t,s,vec2(d));

**Comment by dneto0** [comment]
Regarding 

> - As originally drafted, it was only for the call itself, not the evaluation of the arguments. This is more "surgical".

From internal feedback:
> Applying the rule to the call's arguments is very unexpected, and somewhat ruins the 'precision' of this attribute.
Consider:

      @diagnostic(off,derivative_uniformity) textureSample(t1, s1, textureSample(t2, s2, coords))

>  You want to turn of UA just for the outer sample. You have to hoist the inner textureSample out to another statement if you want to be alerted to UA violations on the inner sampling (going against the "precise" goal of the attribute). I also don't think most people would realize this would silence both calls.

**Comment by ben-clayton** [comment]
Some feedback from internal discussions.

Applying the `@diagnostic` to expressions is raising a number of questions / concerns. [As commented above](https://github.com/gpuweb/gpuweb/issues/3689#issuecomment-1352341978) it's unclear whether the attribute should apply to the call-expression's arguments or not.
For example, are UA violations of `textureSample(t2, s2, coords)` in the following silenced or not?
  ```ts
   @diagnostic(off,derivative_uniformity) textureSample(t1, s1, textureSample(t2, s2, coords).xy)
  ```
  * If the diagnostic control applies to the call argument **and all argument sub-expressions**, then the developer is forced to hoist out sub-expressions, if they only want this diagnostic control applied to the outer expression. Example:
    ```ts
    let inner = textureSample(t2, s2, coords).xy; // Will check for UA violations on this call...
    @diagnostic(off,derivative_uniformity) textureSample(t1, s1, inner); // ...but not this one!
    ```
  * If the diagnostic control **does not apply** to the call argument expressions, then there's a question of how `@diagnostic` could (one day) be applied to non-call expressions. Consider in a future WGSL version where we want to allow for `@diagnostic` on expression parenthesis: `@diagnostic(off,some_new_diag) (a + b)`. Does that mean that the following two inner `textureSample(t2, s2, coords)` expressions would have different diagnostic behaviors?
    * `@diagnostic(off,derivative_uniformity)  textureSample(t1, s1, textureSample(t2, s2, coords).xy)`
    * `@diagnostic(off,derivative_uniformity) (textureSample(t1, s1, textureSample(t2, s2, coords).xy))`
 
Note: Allowing `@diagnostic` to apply to a sub-tree of expressions (call arguments, or expressions in parentheses) would require a substantial amount of engineering for Tint - enough that it would likely impact our shipping date for V1.00. Applying `@diagnostic` to a single, specific call-expression (excluding arguments), or consistently to all expressions of a statement, would be far easier to implement.

---

Some <sup>(not all)</sup> of us at Google feel that limiting `@diagnostic` to `if`, `switch`, `loop`, `while`, `for`, `{}` and `fn`, instead of expressions, would eliminate a bunch of complexity and ambiguity.

In the office hours today, we briefly toyed with the idea of allowing the `@diagnostic` in all the places there's a ▲ or ▼:

```ts
▲ fn f() ▼ { // ▲ and ▼ are equivalent, scoping the entire function 
  let cond = true;
  ▲ { // ▲ scoped to block
    x();
  }

  ▲ if (x()) ▼ { // ▲ scopes if-condition, true-block and false-block, ▼ only scopes true-block only
  } else ▲ { // ▲ covers false-block only
  }

  ▲ switch(x()) ▼ { // ▲ scopes switch-condition and all cases, ▼ only scopes cases.
     case 1: ▲ { // ▲ scopes case block
     }
     default ▲ { // ▲ scopes case block
     }
  }

  ▲ loop ▼ { // ▲ and ▼ are equivalent, scoping the entire loop body
  } 

  ▲ while(x()) ▼ { // ▲ scopes while-condition and loop body, ▼ only scopes loop body
  } 

  ▲ for(var v = x(); v < y(); v += z()) ▼ { // ▲ scopes for loop init, cond, cont and loop body, ▼ only scopes loop body
  } 
}
```

In the office hours, there was some concern about how we would apply `@diagnostic` to `let` and `var` initializers, as scoping of the `@diagnostic` attribute would limit the scoping of the declaration's variable.
Consider:

```ts
fn f() { // f() is called with non-uniform control flow
    let s = textureSample(t, s, coords); // So this is a UA error, which we want to silence. How?
    // ... lots of stuff that uses 's' ...
}
```

We can't just wrap `let s = textureSample(t, s, coords);` with `@diagnostic(off,derivative_uniformity) { let s = textureSample(t, s, coords); }`, as the scoping of the diagnostic has now made `s` fall out of scope after the declaration.
We can however use a `var`:

```ts
fn f() { // f() is called with non-uniform control flow
    var s : vec4f;
    @diagnostic(off,derivative_uniformity) { 
        s = textureSample(t, s, coords); // no errors here
    }
    // ... lots of stuff that uses 's' ...
}
```

As pointed out by @dneto0 - this approach would not work with `let` of pointer types, as you cannot assign a pointer to a `var` - however there is no intersection between fragment derivative operations and pointer values.

Replacing `let` with `var` to solve this does change the mutability of the variable, which is a minor inconvenience. Another alternative would be to place the expression into a helper function:

```ts
@diagnostic(off,derivative_uniformity) 
fn helper(coords : vec2f) -> vec4f {
   return textureSample(t, s, coords);
}

fn f() { // f() is called with non-uniform control flow
    let s = helper(coords); // No errors, and 's' is still a let
    // ... lots of stuff that uses 's' ...
}
```

So we believe there's a couple of ways to handle the variable initializer case without allowing `@diagnostic` on expressions. Some of us believe this is a much cleaner way to scope the `@diagnostic` rules, with little to no ambiguity.

**Comment by dneto0** [comment]
Ok, expressions.
How do we design it so the "scope" of diagnostic attribute on an expression is clear (i.e readable).

Suggestion:  Only allow the `@diagnostic` attribute immediately after the left-parenthesis of a parenthesized expression.

For example:
```rust
let v = (@diagnostic(off,foo) textureSample(t,s,c)) + textureSample(t2,s2,c);
```
The idea is that the closing parenthesis terminates the affected range. The range lines up exactly with what the programmer **sees**: a matched set of parentheses.

This still has the nested arguments question, which may requires hoisting like in (A) and (C).
But at least there is only one rule.


No, I don't think this is *necessary* for v1, but should be considered for later.

**Comment by dneto0** [comment]
In drafting this, this rule is a bit wonky:

>  ▲ fn f() ▼ { // ▲ and ▼ are equivalent, scoping the entire function 

The first should scope over the entire function declaration, and the second should scope over the function body.
This doesn't make a difference for derivative_uniformity, but it might for other things in the future.
