### ISSUE TITLE
Shader compilation is fragile because FXC

### ISSUE THREAD

**Issue by raphlinus** [gpuweb/gpuweb#3691]
I filed [tint#1787](https://bugs.chromium.org/p/tint/issues/detail?id=1787) to track a shader compilation failure on Windows because WGSL with complex control flow and barriers is being translated to valid HLSL, which then fails on D3DCompile (FXC). The original shader is [coarse.wgsl](https://github.com/linebender/vello/blob/3bc81afbf669f9e195dac34a03ecbd1d744ce087/vello/shader/coarse.wgsl) from Vello (formerly known as piet-gpu).

There's a bit more subtlety here, as the original shader fails uniformity analysis (and the log prints the appropriate warning), but once `workgroupUniformLoad` is implemented we expect the generated HLSL to be similar, so will very likely hit the same kinds of FXC errors. In the linked tint bug there are two different errors depending on placement of barriers around the load, one triggering a race condition warning, the other an internal compilation error.

While this is technically an implementation issue rather than a spec issue, there are a couple of potentially relevant implications. One is that it might be useful to document the fact that shader compilation is fragile and may fail due to platform-specific compiler limitations. Second, it might be useful to provide an information channel indicating whether FXC workarounds are needed. We might be able to wire up a backstop when we get a validation GPUError when computing the create pipeline, but don't currently have a mechanism for that (and it's slightly painful as the error is async).

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-01-17-minutes#shader-compilation-is-fragile-because-fxc-3691-">WGSL 2023-01-17 Minutes</a></summary>

* KG: No milestone
* AB: Not sure if we want to do anything. We have to live with some FXC issues and categorize as spurious failures
* BC: Part of the implementation issues with FXC
* MM: What it comes down to, if there is a way to create a category of failures tha FXC fails on we can ban that category. Can't change WGSL spec so Vello’s coarse.wgsl shader succeeds. This is one of the uncategorized failures
* KG: Fits in to the existing set of uncategorized. Think general problem is that we're taking on that danger/risk/work as implementations and the individual parts that don't work well we'll talk about. We're promising that we'll make it work on fxc knowing we'll fail a little bit. Materially we're saying we'll make it work.
* RC: Summary for this issue? Didn't follow what exactly is the issue, is FXC correct or is it in the wrong?
* MM: Raph claims the generated HLSL is valid.
* RC: Has that been verified by a 3rd party?
* KG: Unknown
* JP: Sort of, we did workgroupUniformLoad in Chrome, Raph tried and it did resolve the issue. The WGSL compile would reject due to uniformity first, using workgroupUniformLoad we can validate that FXC does not reject for this shader.
* RC: So there is a workaround?
* JP For this specific shader. Raph says he expects there to be other cases where that is not true.
* RC: **TR and GR said they'd take a brief look and see**, weren't sure if this should be an issue in the first place but haven't looked in detail.
* MM: Is workgroupUniformLoad part of the spec now?
* JP Yes
* MM: Cool.

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-01-24-minutes#shader-compilation-is-fragile-because-fxc-3691-">WGSL 2023-01-24 Minutes</a></summary>

* > **TR and GR said they'd take a brief look and see**, weren't sure if this should be an issue in the first place but haven't looked in detail.
* TR: There are a few levels. The specific run into is a bug in old version of FXC and there is a followup comment on the Tint issue. On the other issue, that seems to be something for the group. For issues in that backend path, or any backend path, there needs to be a mechanism to surface things so the user doesn't just get things to fail at runtime
* KG: Have that as UAs. Can give more context then the api allows us to give. Thought we had string error messages programmatically so I think we're set here. Even if this is that something failed and we don't know why, it wasn't spec compliant. Think we're set there.
* TR: **Only other thing is if WGSL supports dynamically uniform control flow with barriers** because that's something that is not supported on FXC or some implementations if you by-pass it. So, dynamically uniform will break things even though SPIRV supports
* DN: **WGSL requires static uniform that it can prove is statically uniform**.
* AB: **For barriers**.
* TR: Right just for barriers.
* KG: **Satisfied with this issue**.

</details>
