### ISSUE TITLE
Concretization of abstract expressions can produce surprising types

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3716]
Expressions that use sub-expressions of abstract-numerics and non-constant-expressions as inputs must first concretize (aka materialize) the abstract-numeric sub-expression. See https://github.com/gpuweb/gpuweb/issues/3210 for why.

This means that some expressions change type, based on whether one input is a constant-expression or not.

Consider:

```ts
fn a() {
  const C = array(1, 2, 3); // an array of abstract-int
  const i = 1i;             // constant expression
  let j = 1i;               // runtime expression
  let x : f32 = C[i];       // okay: abstract-int can implicitly convert to f32
  let y : f32 = C[j];       // error: cannot initialize let of type 'f32' with value of type 'i32'
}
```

and also:

```ts
fn b() {
  const C = 1;          // abstract-int
  const i = 1u;         // constant expression
  let j = 1u;           // runtime expression
  let x : u32 = C << i; // okay:  abstract-int can implicitly convert to u32
  let y : u32 = C << j; // error: cannot initialize let of type 'u32' with value of type 'i32'
}
```

This is a rough edge, but I haven't figured out a simple way to smooth this out.

**Comment by charlestonxorg** [comment]
Its all verry frightening

**Comment by dneto0** [comment]
After internal discussion at Google:

* There's a pretty strong design principle that the types of values are determined in a bottom-up manner, knowing the types of terms, and very limited surrounding context.
* "Fixing" this would require backing out that principle, or adding significant complexity to the type rules.
      * If someone thinks otherwise, they should propose the better solution.
* The original case where Ben saw this had low impact, and was easy to fix:
      * There was a 'const' array with a bunch of vertices, where the numbers were given as untyped integers.  In the use, a dynamic index was used to get elements, and the vertices ended up being interpreted as integer-vectors.   The result was a compile error which was good enough to diagnose and fix. 
      * There are two fixes: 
             * Write "1.0" or "1f" instead of "1" for example, in at least one of the numbers, or
             * Explicitly declare the array type for the const.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-01-24-minutes#concretization-of-abstract-expressions-can-produce-surprising-types-3716-">WGSL 2023-01-24 Minutes</a></summary>

* JB: Two examples BC chooses, when reading it may help to know the first example is self contained. Everything in the first example, don't compare to the second. The problem is the array C gets to stay abstract in the first case but it doesn't get to stay abstract in the y case. Basically the second example shows similar with right shift operator. Our observation is that array indexing is a special case because the index operand, the type of the index operand does not affect the expression, it's not like + or an ordinary binary op. It seems like, maybe we missed something, we should be able to let the result of the subtract stay abstract even when the index type is not. Basically it's a matter of adding the right overloads to the subscripts. Right and left shift operators are analogous to array subscript in that the type of the right operand doesn't affect the result. On an operator by operator we could finesse this and make both work out.
* AB: Will always have to concretize the abstract array because you have to index at runtime so you can't have an abstract at runtime. At some time, concretize. The question is when does that occur. Understand the point about the indexing being a different type and it becomes a question, part of it is how long do you defer. I have runtime and will have to concretize, but don't know when I have to.
* KG: Distinction between concretization of value and types. We determine the runtime type at compile time but it's a distinction of when the value are concretized. If you have an array that is being indexed dynamically the type of the result is still know at compile time. 
* AB: But it's not abstract
* KG: It's not abstract, we could say the resulting type is abstract but the value is not.
* BC: The problem comes down to having an array of abstract and have an index, regardless of type, you have a runtime value, in the backend you have to make an index operation. So the index operands have to be values, so you have to concretize the array. What you concretize to is bottom up. The first time you see something that requires concretization we kick in the rule. In the case of array we default to i32.
* KG: I get that, just saying knowing that you'll have to provide a dynamic runtime value and given a type for it, knowing it happens and emitting the framework for that code don't think we need to concretize it. Depends on the backend if it's easy or not, conceptually the argument doesn't really mean it has to be concretized.
* BC: Problem is the abstract values can be outside range of 32 bit integers. Backend may not be able to represent value if provided in abstract form.
* KG: Need to think about this more.
* JB: Understand we need to concretize the index but I don't see why we need to concretize the array. By the time we're generating code, we've settled types, the abstract type we just have decided at that phase, ultimately everything has a concrete type by the time we generate code. So, why does the array itself have to be concretized.
* BC: What would you generate for the array in the backend
* JB: Don't choose until we've determined everything
* KG: Determine it when further along
* BC: Right but need to bubble up through expressions to infer, then have type you have to propagate back down. In that chain, if you have a builtin overloaded which is the target for concretization, now you have to infer the param types for the inner expression and don't think that's solvable. Think we have ambiguous overloads.
* KG: That's not a death-knell, would have to say it's an error for now
* AB: Is that better than concretizing when hitting a non-const expression?
* KG: Possibly due to this issue where it's surprising
* JB: The context is that this doesn't seem like a major issue, it's a quirk that people live with. If we find a nice solution, great, but don't have super strong feelings.
* BC: Filed the issue because I was caught out, it wasn't hard to fix, got compiler error that types didn't match. It might have folks scratching their heads. All I did was add a `.` to make it a float again. Took 10 seconds. Might take a bit longer, but not the end of the world.
* KG: Does provide a bottleneck in that folks have to concretize earlier
* MM: All this concretization stuff is novel. Wonder if folks have written code that interacts with this subsystem are not also compiler writers
* BC: Adopted from go. Although, go has a single abstract type, there is no float, just abstract float. THe distinction between float and abstract float adds complexity.
* MM: That wasn't the point I was trying to say. We're trying to make decisions that are best from authors, do we have experience from any authors that have looked at this and did they run away screaming?
* BC: Don't think most folks notice. That was the goal. For the 99% you write literals and constants and it does the right thing. This was the one place I saw it do something unexpected. We're probably nit-picking at the algorithm right now.
* BC: Generally when folks talk tint vs naga, naga doesn't do this and folks have heard that tint does it and they don't have to think about it and people like not having to pay attention.

</details>

**Comment by dneto0** [comment]
From 2023-01-31 notes:

(KG: Are we done here?)
KG: Think we decided it's a little confusing but probably tolerable?
DN: Yes, that's my vote.
KG: **Sold.**
