### ISSUE TITLE
Language around `atan2`'s accuracy is unclear

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#3731]
Currently language in the spec:
`atan2` accuracy:
```
When y is finite and normal, inherited from atan(y / x)
```

`atan2` definition:
```
atan(y/x) when x > 0
atan(y/x) + π when (x < 0) and (y > 0)
atan(y/x) - π when (x < 0) and (y < 0)`
```

The CTS currently interprets this as meaning the acceptance interval for something like atan2(y = -1.1754943508222875e-38, x = -1) is precisely -π, which is somewhat unexpected, and probably not intended.

This interval is generated by returning the interval of `atan(y/x) - π`, where `atan(y/x)` is the interval of `atan(interval of y/x)`
What is happening is that `atan(y/x)` in this case is giving an interval of `[0 - 4096* ULP(0),  0 + 4096* ULP(0)]` (`[-4.81482486096809e-35, 4.81482486096809e-35]`), since `atan(y/x) = 0`.

The issue is that that the error at -π, is order of magnitudes larger than at 0, so when subtracting π , the result from atan(y/x) effectively looks like precisely 0, because `-π - 4096* ULP(0)` and `-π + 4096* ULP(0)` are within 1ULP(-π) of -π.

I think what is actually intended is that atan2's value is calculated at infinite precision given the definition using atan(y/x), and the 4096 * ULP applied at the end. So for our example the acceptance interval should be `[-π - 4096* ULP(-π),  -π + 4096* ULP(-π)]`

**Comment by zoddicus** [comment]
@dneto0 thoughts?

**Comment by zoddicus** [comment]
Vulkan defines atan2 accuracy as 4096 ULP, so that is probably sufficient instead of doing something more baroque.

**Comment by dneto0** [comment]
> Vulkan defines atan2 accuracy as 4096 ULP, so that is probably sufficient instead of doing something more baroque.

I thought the issue was that HLSL compilers on D3D implement it literally as atan(y/x), and that floating division there (or was it Vulkan?) is only defined well for y finite and normal.

Looking at the graph, at https://en.cppreference.com/w/File:math-atan2.png  things go very strange near the origin, and I thought the language currently in the spec was supposed to accomodate that.

But you've thought this through much more thoroughly than me, so I'm happy to defer.
