### ISSUE TITLE
wgsl:  stop using "type" to create type aliases. 

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3738]
Today we create a type alias like this:

       type float = f32;

This declares `float` as an *alias* type `f32`: they are completely interchangeable.

There's been discussion about a future in which WGSL has overloaded user-declared functions. In that case it would be nice to create *distinct* types with the same shape.
E.g. 

      type Position = vec3<f32>;
      type Velocity = vec3<f32>;

And have Position and Velocity being *different* types, so you can't accidentally interchange them.
If we want to allow that future, we should stop using `type` to declare aliases.

So we need another keyword introduce an alias:

Option 1:  "alias"
   * `alias Position = vec3<f32>;`
   * Advantages: does what it says.

Option 2:  "using"
   * `using Position = vec3<f32>;`
   * Advantages: same as C++ type-alias.  https://en.cppreference.com/w/cpp/language/type_alias

**Comment by mehmetoguzderin** [comment]
> ...a future in which WGSL has overloaded user-declared functions. In that case it would be nice to create _distinct_ types with the same shape. ...

Are there strongly typed language precedents where this is different from type inheritance? If not, are there any strongly typed languages where inheritance sets through an equality operator?

**Comment by ben-clayton** [comment]
In go, you can have:

```go
type A = int;
type B int;
```

`A` is an alias - you can interchange `A` and `int` - they're the same type. This is equivalent to WGSL's current `type`.

`B` is a new type. You cannot mix `B` and `int` without explicit casting. This is handy for code where you want to statically ensure you do not silently mix up units. Could be useful in WGSL someday for, say ensuring you don't muddle up points from directional vectors.

---

note: I don't like go's syntax here. The inclusion / omission of `=` is subtle, and I'd much prefer `alias` and `type` for `A` and `B`, respectfully. So a +1 from me for the proposed Option A

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-01-17-minutes#wgsl-stop-using-type-to-create-type-aliases-3738-">WGSL 2023-01-17 Minutes</a></summary>

* DN: Request to rename `type` from type aliases to `alias` if we're anticipating overloads, templated or not, may want a way to create  new type. AB says just use struct for that. I think alias is slightly nicer.
* KG: I like alias or using
* DN: Either would work.
* KG: Sounds reasonable. 
* JB: Alias is nice and explicit. 
* BC: Using in c++ is overloaded with namespaces.
* MM: What might we awnt to use type for in the future?
* DN: To create a new distinct type for type checking, overload resolution, that otherwise is the same as the original type, differ by name.
* MM: Is there an example in c++ or another language?
* DN: In c type matching is by structure, in c++ it's a breaking change where it's by name. Velocity and Position are both Vec3 and don't want to call function expecting Velocity with Position.
* BC: go has `type` and `type =` and one is an alias and ones a new type. Could use an f32 but can't implicity use it as the wrong thign.
* KG: Not just primitive types but any type. All that aside if making type alias and condensing to one word, alias is the better word then type. Type is ambiguous and not certain which you mean and alias is clearer. Think calling it alias is the way to go
* MM: typedef? I guess we dont' want that because the order is flipped?
* KG: Still confusing which one you want. Alias vs type is the core thing. These are aliases and they can be used interchangeable. vec2f is interchangeable with vec2&lt;f32>.
* MM: The thing we might want to use type for in the future is better then struct.
* KG: **Resolved, switch to alias**.

</details>
