### ISSUE TITLE
WebGPU bikeshed error:  LINE ~6751: No 'dfn' refs found for 'serializable objects' that are marked for export.

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3752]
The bulid-validate-publish flow is failing.
E.g. https://github.com/gpuweb/gpuweb/actions/runs/3943724824/jobs/6748888303

make: *** Waiting for unfinished jobs....
LINE ~6751: No 'dfn' refs found for 'serializable objects' that are marked for export.
[=serializable objects=]
 ✘  Did not generate, due to fatal errors
make[1]: *** [Makefile:10: index.pre.html] Error 2

I think the problem is in spec/index.bs:

$ grep -n "serializable ob" index.bs 
6751:{{GPUPipelineError}} objects are [=serializable objects=].

**Comment by kainino0x** [comment]
Not sure what's going on here. Unlike the TR flow, this one uses a pinned version of Bikeshed, so there must have been a change in the bikeshed crossref database. Oddly, when I run this locally with that pinned version 3.7.0 I actually get a different error, but basically the same:
```
LINE ~3012: No 'dfn' refs found for 'getter steps' that are marked for export.
```

With 3.11.1:
```
LINE ~6751: No 'dfn' refs found for 'serializable objects' that are marked for export.
```

Also this seems to be the correct way to refer to this:
https://github.com/whatwg/webidl/blob/872888179a985d88a9c6a26da07e1635a17fed08/index.bs#L14608
So I'm still guessing this is a bikeshed database bug.

**Comment by kainino0x** [comment]
BTW to update the bikeshed database locally, `bikeshed update`. I'll try to remember to run this again tomorrow and see if it's fixed itself I guess.

**Comment by tidoust** [comment]
Bikeshed switched from Shepherd to [Webref](https://github.com/w3c/webref) for its cross-references database last week, see [announcement on spec-prod mailing-list](https://lists.w3.org/Archives/Public/spec-prod/2023JanMar/0004.html).

I don't see any reason why this would make `[=getter steps=]` fail and cannot reproduce that locally.

For `[=serializable objects=]`, right now, that's by design: the HTML spec does not explicitly export the term. I suppose Shepherd used to consider that terms defined in headings were to be exported. Webref does not have that rule (and this had not been raised as an issue so far). I'll look into it: headings themselves can be cross-referenced, so it seems reasonable to export terms they define as well.

**Comment by kainino0x** [comment]
Thanks François!
`[=getter steps=]` is probably not a problem, I only saw it with the older Bikeshed, and we can upgrade our pinned version.

We can always link to the heading as a workaround. I considered this, but then looked and saw the WebIDL spec did it the same way, so didn't try.

**Comment by kainino0x** [comment]
Working on this
