### ISSUE TITLE
WGSL fails to clearly define the target user, and fails to meet user needs

### ISSUE THREAD

**Issue by jwatte** [gpuweb/gpuweb#3786]
I have a lot of experience with shader languages and GPU targeting, all the way back to the original pre-HT&L versions of OpenGL and Direct3D.
I believe that WGSL will fail to meet any real needs of actual developers, if it proceeds as currently suggested.

There are two high-level concerns:
1. Who is the actual user?
2. How do you best meet the needs of that user?

If the user is "a human being writing these shaders by hand in a meaningful way without additional tool support," then the language should be as close as possible to one existing shading language, because those languages have been battle hardened, most of the ambiguities and implementation specifics have been ironed out, and plenty of documentation, examples, and knowledge already exists on the world.
The two languages that could be considered would be a flavor of HLSL, or a flavor of GLSL. Both of these languages support some notion of "profiles," and thus could have a profile that restricts the language to the subset targeted by WGSL.
As a bonus, the IHVs already have mature pipelines that understand these languages.

If the user is "any tooling pipeline that generates shaders to run on web gpus" then the text-readability of the language is no more important than the text-readability of other machine formats, like Postscript, WASM, or MP4. Thus, the learning form both HLSL and GLSL that a well-defined byte code definition fits this need much better, could be leveraged. A code like SPIR-V would benefit from existing IHV pipelines, available tooling, online documentation and knowledge.

If the goal is to actually make webgpu a serious target for current practitioners of the art (e g, anything from online communities like Roblox or IMVU, to the engines like Unreal and Unity) then I highly recommend engaging with and listening to those users, and I can tell you that they do not see WGSL as a viable proposal.
If the goal is to get good adoption by IHVs and wide-ranging compatibility, then I highly recommend re-using as much as possible of existing tooling and approaches; especially the Vulkan approach of SPIR-V would be applicable.

**Comment by jimblandy** [comment]
These issues were discussed, at great length, by the committee. Originally WebGPU was going to simply use SPIR-V; there was little appetite for designing an entirely new shading language. But when it came down to working out the details, it didn't work out as well as one might expect. There's some good background in [kvark's blog post](http://kvark.github.io/spirv/2021/05/01/spirv-horrors.html) from that time.

There's an argument that it doesn't matter much, because most people are going to be using WebGPU through other tools, using WGSL as a compilation target. It should work fine in that role.

**Comment by jimblandy** [comment]
It's probably also worth saying that the horse has pretty much left the barn. (I don't agree with the OP, I think WGSL is fine - but let's just set that aside for the moment). Chromium will be shipping their WebGPU implementation very soon, and Firefox will be enabling WebGPU in nightly builds soon as well. WGSL is a done deal.

Ultimately, I think the things that matter here are not the aesthetics of what you type. People are very good at getting used to superficial syntactical details. What's much more important are the semantics - and in that area, WGSL should be extremely familiar to experienced developers. There are no new concepts in WGSL.

The exception might be the uniformity analysis - but even that is mostly about conveying harsh realities from device driver authors to shader authors about what the driver actually promises and what it does not. People write a lot of stuff that works on their machine but is not technically supported by the platform API, and is not portable in practice. WGSL includes an analysis to detect these cases, which is indeed novel among shading languages. But since this is an analysis that reports problems, if it turns out to be unhelpful, removing it would be a backwards-compatible change to the spec. We'll have to see whether people find it valuable, or whether the portability issues are minor enough in practice that they don't care.

**Comment by kdashg** [comment]
Thank you for your perspective!
I want to reassure you that all these points came up in our vigorous discussions on direction for shaders for WebGPU.
Many of these points, such as the desire for a strong tooling ecosystem and minimizing barriers for adoption for existing projects, continue to be important inputs to our decision-making on WGSL, and more broadly for WebGPU as a whole.

We are actively engaged with a number of current and future authors of WebGPU and WGSL, including some fantastic feedback and collaboration with Unity on our uniformity analysis iterations.

Since the group has discussed these points extensively and relatively exhaustively, I'll close this issue. But do please open new issues if you run into specific roadblocks for porting or any other use-cases you run into! Thanks!
