### ISSUE TITLE
Swapchain coordinates system inconsistency

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#379]
While playing with WebGPU in Safari Technology Preview and Chrome browsers, I've noticed that the "red triangle" example demo wasn't behaving consistently. As you can see in the screenshot below, triangles don't point in the same Y direction.

Is that an implementation issue or should this behaviour be defined in the WebGPU spec?

![image](https://user-images.githubusercontent.com/634478/61943750-6ffb2600-af9c-11e9-9945-31aa313d7f98.png)

**Comment by kainino0x** [comment]
I have a vague recollection that we discussed this a very, very long time ago and said we would use the D3D/Vulkan convention of +Y=down. But I can't remember if it was a standards discussion or just in Dawn.

FYI, we recently discovered in Chrome that we had an accidental y-flip and removed it - making +Y be down.

**Comment by litherum** [comment]
It should absolutely be defined in the spec. I believe D3D and Metal define NDC coordinates differently, so we need to pick one and consider how to implement it on other platforms/APIs.

**Comment by magcius** [comment]
D3D and Metal define the same NDC coordinates: +Y = Up. And in viewport space, +Y = down).
OpenGL defines NDC: +Y = Up, Viewport: +Y = Up
Vulkan defines NDC: +Y = Down, Viewport: +Y = Down (`VK_KHR_MAINTENANCE1` allows you to specify a negative viewport to get +Y = Up, so you can port your code from one to the other, but you have to flip your front face and cull mode states)

I recommend picking the D3D/Metal convention.

**Comment by kainino0x** [comment]
Oops, thought D3D used the same conventions as Vulkan (thought that was why Vulkan was the way it is), but I'm sure you're right (that was just from memory).

**Comment by sebavan** [comment]
Would it make sense to follow the same convention than WebGL to simplify the migration and port of some WebGL frameworks to ease the adoption of WebGPU (which is if I remember NDC and Viewport +Y=Up) ?

If not could we chose a convention where both +Y are matching ? This would prevent the need of different Projection Matrices or UV mapping when rendering to textures or the addition of a special flip pass.

**Comment by Kangz** [comment]
@magcius to add to what you said, when presenting to the screen, by default OpenGL is +Y = Up, and D3D12 / Metal / Vulkan are +Y Down.

Also I'm pretty sure Vulkan has NDC and viewport +Y = Up, see section 23.4 Coordinate transformations and  23.5 Controlling the viewport of the Vulkan spec that don't have flips.

Having flips in places in the pipeline is very inconvenient so I'd recommend +Y = Up everywhere since it matches WebGL like @sebavan said.

**Comment by magcius** [comment]
WebGL had the bizarre property of the origin of textures/FBOs being at the bottom-left (or put another way, "Viewport +Y = Up"), requiring Y-flips throughout most of the driver and stack. Most treat OpenGL the same as D3D, using "upside-down textures" (uploading data assuming the top-left is the origin), and it just so happens that everything else cancels out... However, when reusing FBOs as textures, the FBO image would be "right-side up" (with the origin at bottom left), and so a common beginner bug is for FBO textures to be "upside down" when used in the scene. Most engines solve this with a hacky "y-flip" boolean somewhere in their texture binding class.

The flipping is caused not by using different Y+ origins (after all, D3D/Metal use differing Y+ and they do not have this issue), but simply by nobody actually respecting what OpenGL says is the proper origin.

So, I would recommend Y+ Down for Viewport, and a lower-left origin for textures. They need to match for FBOs. NDC should be Y+ Up but I have no strong preference on this.

I don't recommend picking the same convention as WebGL as it indeed has lots of Y-flipping in the driver all over the place.

**Comment by magcius** [comment]
> Also I'm pretty sure Vulkan has NDC and viewport +Y = Up, see section 23.4 Coordinate transformations and 23.5 Controlling the viewport of the Vulkan spec that don't have flips.

There not being flips can either mean both or +Y = Down or +Y = Up. In the spec documentation for [VkViewport](https://renderdoc.org/vkspec_chunked/chap25.html#VkViewport):

> x and y are the viewport’s upper left corner (x,y).

If the origin is at the upper left, then +Y = Down. Not having the flip was the oversight that caused NDC to be +Y = Down.

**Comment by Kangz** [comment]
> If the origin is at the upper left, then +Y = Down.

I didn't realize the spec said this, in Dawn we don't do anything specific for Vulkan compared to OpenGL and it passes tests for viewport / winding / fragcoord so I assumed it was the same.

Running through an example on paper, I don't see a way to be able to tell the difference between both +Y = Up, or both +Y = Down (if we forget about presenting to the screen) because sampling textures in all API is defined the same way (1, 1 will become the texture's width and height irrespective of +Y up or down.)

**Comment by sebavan** [comment]
I am always struggling out with all the different spaces in place here, the main need for us would be to ensure that we do not need any flip depending if we render to texture or to the final canvas. 

We are trying to prevent different ways to render as it would involves different pipelines to render the same scene depending where it is rendered to. 

@magcius If we use +Y down for the viewport and upper-left origin for textures, does it not imply that I need to flip the render to texture to ensure that the bottom of a scene would match with the smaller UV values (or the top of the texture) ? meaning the opposite of what we would use when rendering to the canvas texture to be sure the bottom of the scene is rendered at the bottom of the canvas ?

**Comment by sebavan** [comment]
Else could we introduce a special flag to flip automatically what is presented on screen ? so that we keep +Y down everywhere for the drivers and do not force the users to deal with the final presentation flip ?

**Comment by magcius** [comment]
> Running through an example on paper, I don't see a way to be able to tell the difference between both +Y = Up, or both +Y = Down (if we forget about presenting to the screen) because sampling textures in all API is defined the same way (1, 1 will become the texture's width and height irrespective of +Y up or down.)

Not quite. Again, when you upload data with, say, glTexImage2D, you are expected to provide the row of pixels for the *lower-left* of the image first. And then (0,0) will correspond to the *lower-left* of the image, and (1,1) will correspond to the upper-right. In practice, nobody does this, and uploads data starting with the upper-left, and treats (0,0) as the upper-left and (1,1) as the lower-right. These two mistakes cancel each other out, *except* in the case of texturing from an FBO, where (0,0) is the lower-left. So users will Y-flip there.

> I am always struggling out with all the different spaces in place here

We are all. I'll need to work this out on paper and get back to you.

**Comment by sebavan** [comment]
The main thing is that we try to adapt our WebGL engine to WebGPU and would like the least amount of changes in coordinates to be compatible with both. So being flipped everywhere is kind of easy enough. 

The main issue being the final presentation that needs to be flipped and that is why I wonder if it would make sense to introduce a flag for this one ?

**Comment by magcius** [comment]
Porting existing content to other platforms is always a challenge. My recommendation would be to use the unified coordinates for both textures and FBOs, even with WebGL, and either apply the Y-flip at texture time or presentation time on the WebGL side. If you aren't using unified coordinates for FBOs, that means that content might be bizarre when using render-to-texture to texture a model rather than just a fullscreen tri.

But this is getting a bit off-topic for this thread. Again, reminder that UNPACK_FLIP_Y_WEBGL and friends are things -- driver complexity is real.

**Comment by beaufortfrancois** [comment]
@mrdoob Do you have any opinion in this?

**Comment by Kangz** [comment]
> Again, when you upload data with, say, glTexImage2D, you are expected to provide the row of pixels for the lower-left of the image first.

We also have tests for that and all our backends are consistent without needing to do any work. From what you're saying, Dawn should be broken somewhere but all backends pass all tests so we must be missing some coverage somewhere, I can't find where.

**Comment by deltakosh** [comment]
> I recommend picking the D3D/Metal convention.

I highly recommend the same as WebGL. The engines at the beginning will have to deal with both API (webGL and webGPU): OpenGL defines NDC: +Y = Up, Viewport: +Y = Up

**Comment by magcius** [comment]
> We also have tests for that and all our backends are consistent without needing to do any work.

As I mention, the two mistakes (UV mapping and texture uploads) cancel each other out, until you care about FBOs. Put another way (this is what I believe you were trying to phrase originally), (0,0) will map to the first pixel sent in the array in glTexImage2D, and (1,1) will map to the last pixel, regardless of image origin.

FBOs map (0,0) to the lower-left origin, which is frustrating and inconsistent for people coming from D3D/Metal.

**Comment by magcius** [comment]
It's probably worth noting that OpenGL in its latest revisions actually has a flag to configure this, with `glClipControl`: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glClipControl.xhtml

**Comment by deltakosh** [comment]
>  which is frustrating and inconsistent for people coming from other platform APIs, like D3D/Metal.

Yeah but why introducing a frustration for people already on the platform?

>  flag to configure this, with glClipControl

That would be ideal for WebGPU as well then

**Comment by magcius** [comment]
To be clear, I'm already on the platform, and would like to see the D3D model adapted. I currently have a `flipY` boolean in [my own engine](https://github.com/magcius/noclip.website/search?q=flipY) to differentiate the two cases (top-left origin for textures, bottom-left origin for FBOs) that I would like to do away with.

**Comment by jdashg** [comment]
Origin top-/bottom-left can be tricky, but ultimately workable either way, we just need clarity here.

glClipControl only went core in 4.5, and isn't available in ES.

I think we need a feasibility investigation on this, but my choices would be from:
* What WebGL already does
* What the majority of modern APIs do

But I would like to see an investigation, because this thread is self-contradictory in places, and we need to know both what the various APIs do, and also what's implementable. (I worry that we can't trivially implement all of the possibilities)

**Comment by Richard-Yunchao** [comment]
I can investigate on this and write a document if nobody has started to write it. I implemented corresponding features (culling and front face, and setViewport) and wrote many tests about NDC and viewport coordinates in Dawn project recently.

**Comment by mrdoob** [comment]
> @mrdoob Do you have any opinion in this?

I do not have strong opinions on this, but I personally dislike that in WebGL Viewport: +Y = Up. In my mind Viewport: +Y = Down makes more sense (just like Canvas2D).

As per @jdashg options, I would vote to adapt to modern APIs.

**Comment by grorg** [comment]
Discussed at [5 August 2019 Teleconference](https://docs.google.com/document/d/1_SZqLdSaG1I3Pwe2SJFqrcXtAvH4aIDcXbf5kEple88/)

**Comment by RafaelCintron** [comment]
The [Coordinate Systems](https://docs.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-coordinates) page describes the coordinate system for Pixels and Texels.  The D3D10 description apples to D3D11 and D3D12. 

In summary:
* NDC coordinates are +Y up, same as it was in Algebra class.
* Viewport coordinates are +Y down as evidenced by [D3D12_VIEWPORT](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_viewport)'s TopLeftX and TopLeftY fields.
* UV coordinates are +Y down.  

Texture coordinate naming and orientation has been covered in issue #157 .  The decision was to name them UV and for them to be +Y down.

+1 to @mrdoob on disliking WebGL's +Y Up viewport style.

**Comment by deltakosh** [comment]
I just would like to be sure we have the same direction for RT and FBO so we do not have to update shaders depending on where they render

**Comment by magcius** [comment]
To clear up my past posts a bit:

* Texture coordinates, in isolation, don't *really* matter. The GL spec officially defines 0,0 to be the bottom-left and glTexImage2D saying that the first pixel uploaded is at the bottom left, this ultimately just means that sampling the coordinate at 0,0 will sample the first pixel uploaded with glTexImage2D, which is also true of Direct3D/Metal/Vulkan.

* Texture coordinates matter because of other things. The GL spec officially defines 0,0 to be the bottom left, and this also applies when sampling a texture coming from an FBO. But of course, all spaces are relative. So "bottom left" is defined relative to the FBO's viewport space.

* NDC space matters for two things: 1. Defining CW/CCW for front face, and 2. Whether it is the same or flipped from Viewport. It has no strong influence besides those two things.

* Viewport space decides what the coordinates are for the final image that's used. If we have already decided that 0,0 is the top-left for texture space, then it makes sense to use an orientation that matches, so that rendering to an offscreen and then sampling it is consistent. That would be the Y+ Down coordinates for Viewport, which matches Direct3D and Metal, but the opposite of (default) Vulkan and (default) OpenGL.

--

There's a second component to it, which is the depth range, whether to use 0..1 or -1..1. I don't think there's as big a debate on this one, since the former provides a lot of benefits. Direct3D, Vulkan, and Metal all use a 0..1 depth range. OpenGL uses -1..1 by default, but can be changed to use 0..1.

What this means is that, in practice, someone naively porting WebGL code to WebGPU, it won't work as expected, since the projection matrix needs to change for the new depth range ( see https://matthewwellings.com/blog/the-new-vulkan-coordinate-system/ ).

**Comment by grorg** [comment]
Discussed at the [2019-08-12 meeting](https://docs.google.com/document/d/18Ze0h9InJN5QWXe0iN9UzEebfiEIg8HYo-aX9rKvhuk/edit)

See also [an investigation](https://docs.google.com/document/d/1pXTWc8U2_pz-2hUMUv6jeS-cnjPa37Rie30rzO5slnI/)

**Comment by krogovin** [comment]
For NDC, how about the shader has a directive in it that specifies the NDC coordinate system? I guess it might be actually two directives: one for y up or down and another for z [-1, 1] or [0, 1]. Then a WebGPU implementation can use the shader directive to add the small amount of epilogue code on the vertex shader to realize the y and z to whatever the underlying API uses.

However, the viewport issue is still present and the funkiness it induces when rendering to offscreen buffers. The next suggestion-pair is essentially a thought out-loud wanting commentary:

1. On the issue of texture sampling (and image load-store), a declaration of such a variable can have, like OpenGL's layout, an option to "flip the V of a UV texture/texel coordinate", together with
2. A mechanism to specify if the viewport coordinates are with (0, 0) is the first pixel/texel or if (0, height - 1) is the first pixel/texel. I advocate placing this as part of creating a GPUDevice (since changing the convention mid-application will generate a nightmare of potentially recreating  pipeline state objects).

I admit that the above suggestions are essentially "let the application decide", but considering that the underlying API's don't agree and that the current web 3D API also does not agree with any of them, it might be best to allow a web-app to choose its conventions to aid in porting efforts.

**Comment by devshgraphicsprogramming** [comment]
OpenGL 4.0+ has facilities for controlling NDC and `gl_FragCoord` to match Vulkan and D3D.

I used this in my OpenGL engine to make everything consistent.

The only problem is that tex-coord origin is not adjustable so Vulkan and OpenGL are opposite of D3D

**Comment by jdashg** [comment]
According to an early post here, D3D has the same NDC as GL, and only Vulkan has NDC +down.

**Comment by magcius** [comment]
OpenGL and D3D's NDCs are both Y+ Up. Where they differ is the range of Z (either 0..1 or -1..1). `glClipControl` allows you to set a Y+ = Down NDC, which doesn't precisely match D3D, but combined with all the other differences, they cancel each other out almost exactly (maybe even exactly?).

**Comment by devshgraphicsprogramming** [comment]
@magcius @jdashg GLSL also has an extension that just changes the semantics of `gl_FragCoord` without any C API intervention in OpenGL/Vulkan.

Actually Vulkan redeclares `gl_FragCoord` with a different default than OpenGL XD.

**Comment by kainino0x** [comment]
^ GLSL `layout(origin_upper_left)`, SPIR-V `OriginUpperLeft`.

**Comment by devshgraphicsprogramming** [comment]
@kainino0x yeah, but OpenGL behaves as if the default declaration is `layout(origin_lower_left)` in the absence of programmer's declaration in GLSL source.

**Comment by kainino0x** [comment]
Right, just adding a ref so people know what to look up.

**Comment by beaufortfrancois** [comment]
For info, https://github.com/gpuweb/gpuweb/issues/416 attempts to summarize coordinate systems in native graphics APIs and WebGL and propose appropriate solution for WebGPU.

**Comment by Richard-Yunchao** [comment]
@beaufortfrancois , thank you. You found the investigation before I finished it. :)  

To all participants, please take a look at the investigation. Feel free to correct me and/or raise questions.

**Comment by Kangz** [comment]
Fixed by #416 and the following discussion.
