### ISSUE TITLE
Defaults for depthWriteEnabled and depthCompare may be surprising

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3798]
As an offshoot of #3777 I pointed out that `depthWriteEnabled` defaulting to false may be surprising, and @greggman pointed out that `depthCompare` defaulting to `"always"` may be surprising.

The question raised was, should we make these required for now? We would be able to change them back to having default values post-V1 but would help prevent blank-screens and other difficult-to-debug developer issues.

**Comment by magcius** [comment]
Why would the screen be blank? With this default configuration, draws should always go through, right?

**Comment by greggman** [comment]
>  blank-screens **and other difficult-to-debug developer issues**.

**Comment by greggman** [comment]
To me, the fact that I created and attached a depth buffer should be enough to signal that I want to use it. Currently there are 3 defaults 

```js
{ 
  depthClearValue: 0,
  depthWriteEnabled: false,
  depthComapre: 'always',
}
```

They should arguably be either

```js
{ 
  depthClearValue: 1,
  depthWriteEnabled: true,
  depthComapre: 'less',
}
```

or 

```js
{ 
  depthClearValue: 0,
  depthWriteEnabled: true,
  depthComapre: 'greater',
}
```

I'd pick the first since `less` is more common.

To me this is no different than the scissor and viewport defaulting to the size of the attachments. The arguement can be made if these are zero, false, always, then the scissor and viewport should also default to 0 because by the same arguement, adding color attachments is apparently not a signal I want to render to them.

**Comment by kainino0x** [comment]
> Why would the screen be blank? With this default configuration, draws should always go through, right?

Yeah, I think you're right. That was part of the thinking behind the original defaults: have the depth test default "do nothing" by never rejecting (and never writing).

---

I think we all agree it's a bit weird to have the defaults do nothing: no depth test, and no depth write. Let's look at what people are most likely to do. We can't discount any of the 4 options:
- Enable both (drawing solid objects into a scene)
- Enable depth-test but not depth-write (drawing things like non-alpha-to-coverage transparent particle effects)
- Enable depth-write but not depth-test (I'm sure there's a use case for this, don't know what)
- Disable both (but you still have a depth attachment - probably the only reason is for pipeline compatibility with a render pass that does have depth)

It definitely seems less common to actually want depth-test disabled. The remaining problem is, we don't know which default people want. Forward-Z (Z away from the viewer) is of course the most popular, though reversed-Z performs strictly better. Unfortunately, reversed-Z isn't something we can "just" use by default, even ignoring that it would eventually confuse people: the reversal has to happen in the user's projection matrix. We already switched from the GL projection matrix convention (-1..1) to the D3D convention (0..1), it's not that practical to force a totally new convention (1..0) on users, especially now.

Having thought through this, I'm willing to give up on the idea of neutrality or promoting reversed-Z here (so #3777 is fine). Though I still think the the original guiding principles of "do nothing" by default are acceptable for depthWriteEnabled/depthCompare.

Just in case, let's look at backend defaults again.

|  | Depth test | Depth test compare function | Depth write or mask |
|---|---|---|---|
| Vulkan | no default, but 0 = disabled | no default, but 0 = "never" | no default, but 0 = disabled |
| Metal | enabled (no such option) | "always" | disabled |
| D3D12 | enabled | "less" | enabled |
| OpenGL | disabled | "less" | enabled (note, depth write can't be enabled without depth test - must set compare function to "always" instead. One can perhaps see how Metal ended up without a depth test option.) |

Okay, well, that's wildly inconclusive as expected. Except of course none of the APIs default to reversed-Z.

Finally, there's the WebIDL issue of defaulting to true. The [problem](https://lists.w3.org/Archives/Public/public-script-coord/2013OctDec/0302.html) applies equally to both optional arguments and optional dictionary members. In our case, these behave differently:

```js
desc.depthWriteEnable = myDepthWriteEnable;
```

```js
if (myDepthWriteEnable) {
    desc.depthWriteEnable = true;
} else {
    desc.depthWriteEnable = false;
}
```

Should we rename it to `depthWriteDisable`? Leave it required? Have a `depthWriteMask` like D3D12 and OpenGL? (Doesn't really fix it.) Make it a 2-valued enum? Make it a nullable `boolean?` and reject `null` (and [therefore](https://webidl.spec.whatwg.org/#es-nullable-type) `undefined`) as a bespoke `TypeError`? (I might choose this one if forced to decide after V1.)

**Comment by kainino0x** [comment]
Oh, and finally, for release schedule reasons, I'll suggest Chrome should intentionally break spec temporarily, by making `depthClearValue`, `depthWriteEnabled`, and `depthCompare` all `required` for a few months to mitigate the breakage.

**Comment by magcius** [comment]
depthTest enabled but depthWrite disabled is not just for particle effects, it's the correct settings for *any* transparent object, and what a lot of 2D game engines do out of the box if the sprite has transparency.

I don't think there's any "obvious" or "correct" default behavior here. Every default will be surprising to someone, and I don't know if it's worth the energy to change.

**Comment by Kangz** [comment]
Why are we considering changing the defaults, can't we just close this and live with whatever the defaults are? Especially considering the following:

 - WebIDL's rule that it is preferrable for defaults to be null-ish.
 - Defaults having been there for years at this point and developers having never voiced any issue with them since then (#3777 is the first time I have heard someone raise this issue)
 - Defaults having been there for years and group participants having had ample time to comment on them until now.
 - The group trying to tie up WebGPU in the coming month / couple months.
 - The engineering burden on the group to update the CTS and other parts of the WebGPU ecosystem.
 - No API agreeing on what the defaults should be so we don't have clear prior art to follow.

IMHO changing the defaults at this stage is unnecessary with no clear benefits, nor clear solutions, and highly disruptive to actually shipping the API. I request that we close this and #3777 with no changes.

**Comment by greggman** [comment]
> WebIDL's rule that it is preferrable for defaults to be null-ish.

This doesn't seem to hold in the WebGPU spec. What's special about these? Why call out that preference for this issue but not all of these others?

* GPUPrimitiveState.topology defaults to 'triangle-list' not 'point-list' or required
* GPUMultisampleState.mask defaults to 0xFFFFFFFF not 0
* GPUBlendOperation.srcFactor defaults to 'one' not 'zero'
* GPUDepthStencilState.stencilReadMask defaults to 0xFFFFFFFF not 0
* GPUDepthStencilState.stencilWriteMask defaults to 0xFFFFFFFF not 0
* GPURenderPassDescriptor.maxDrawCount defaults to 5000000 not 0
* GPUCanvasConfigurtion.usage defaults to 0x10 not 0
* GPUTextureDescriptor.sampleCount defaults to 1 not 0
* GPUTextureDescriptor.mipLevelCount defaults to 1 not 0
* GPUTextureDescriptor.dimensions defaults to '2d' not '1d' or required
* GPUSamplerDescriptor.lodMaxClamp defaults to 32
* GPUBufferBindingLayout.type defaults to 'uniform'
* GPUSamplerBindingLayout.type defaults to 'filtering' not 'non-filtering'
* GPUTextureBindingLayout.sampleType defaults to 'float'
* GPUTextureBindingLayout.viewDimension defaults to '2d' not '1d' or required
* GPUStorageTextureBindingLayout.viewDimension defaults to '2d' not '1d' or required
* GPUTextureDescriptor.size defaults to [x, 1, 1] not [x, 0, 0]
* GPUBufferDescriptor.size defaults to size of buffer, not 0

> depthTest enabled but depthWrite disabled is not just for particle effects, it's the correct settings for any transparent object, and what a lot of 2D game engines do out of the box if the sprite has transparency.

depthTest enabled but depthWrite disabled is useless if you didn't already render something to the depth buffer previously. Most 2d arguably doesn't use a depth buffer in which case you just don't create one.

**Comment by kainino0x** [comment]
> This doesn't seem to hold in the WebGPU spec. What's special about these? Why call out that preference for this issue but not all of these others?

I think the logic only applies to things that _have_ nullish values (so, not the enum ones); actually though, I think IDL only really cares about defaulting to boolean `true`, not other non-nullish things. Regardless, IMO this is the least important of the reasons to keep things as they are.

**Comment by greggman** [comment]
So just for fun, if `depthWritEnabled` and `depthCompare` were made required, these are the changes needed to the CTS

https://github.com/greggman/cts/commit/38c073cebbfdc54b154c6c2e69365ec7317c1066

As for `depthClearValue`, it unfortunately can not be made required, at least not easily, as it's only valid if `depthLoadOp = 'clear'`  We could make it that that if `depthLoadOp = 'clear'` that `depthClearValue` must be set, not undefined, but as is that can not be expressed in the IDL, only in validation.

**Comment by greggman** [comment]
Here are the changes needed if `depthClearValue` being undefined was a validation error when `depthLoadOp = 'clear'`

https://github.com/greggman/cts/commit/f797dcdf97585a9b41e87bc9e871daf8c08013d9

yes: it's 2 lines

**Comment by kainino0x** [comment]
**Resolved** to make all three things required: `depthClearValue` (#3777), `depthWriteEnabled`, `depthCompare`.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#">GPU Web F2F 2023-02-16/17</a></summary>

    Defaults for depthWriteEnabled and depthCompare may be surprising [#3798](https://github.com/gpuweb/gpuweb/issues/3798) [Brandon]

* Also [#3777](https://github.com/gpuweb/gpuweb/issues/3777)
* BJ: defaults, and whether we want to do anything at all.
* BJ: what should be the drivers of these defaults? If all the native APIs have a particular default, we shouldn't question it. Make porting easier. Developers won't trip over it. Even if just historical momentum for why it's in place.
* [Spreadsheet](https://docs.google.com/spreadsheets/d/14Wxaau82x7PnipRTvTL2EbcBgjFmAW9BysBAC4GWbNM/edit?usp=sharing)
* BJ: which face is front face? Didn't realize this was controversial.
* BJ: think not worth trying to change things up in various situations. No default we can adhere to. frontFace, cullMode. D3D12 default is cullMode=back. Don't think we should adopt that. (If cull mode's wrong, you notice this quickly.)
* BJ: pick reasonable default - user will notice right away.
* BJ: now we come to the ones Myles brought up. depthWriteEnabled, and depthCompare. depthWriteEnabled is False on all APIs except D3D12 and OpenGL.
* BJ: any interaction with depth buffer - have to include whole stanza about depth/stencil. You'll see visually whether you're getting what you want.
* BJ: depthCompare - think "less" is probably what we want to do.
* CW: concerned we're reconsidering defaults at this stage, for reasons I pointed out in the issue. My preferred solution - stop changing, whatever's in the API now is good. If we start talking about cullFace, cullMode - more changes that didn't trip anybody.
* KG: not sure that's true. Maybe nobody's bashing down our door. But maybe the gap there isn't important.
* JS: is this user-facing API expectations?
* BJ / KN: entirely.
* BJ: Myles did complain about it.
* MM: I don't count.
* MW: this is the first thing I ran into, depth writes getting set to 0.
* KG: esp. if people are coming from something, like WebGL. Most people don't read the WebGPU spec, and won't know why things silently didn't work.
* MM: 1) changing these in impl is super cheap. 2) Mike found this just walking in the door. 3) once we set defaults.
* CW: changing these in impl isn't cheap. CTS is this group's responsibility. Purely Chrome's responsibility - changing these isn't cheap. Have to update hundreds of tests, or because we removed a default. Same true for this group. Have to maintain the CTS. Update hundreds of CTS tests. No uninitialized value in JS - "undefined" - IDL validation of browsers would explode. Has a cost. It's valuable feedback - but we thought about these defaults a long time ago, haven't changed in years.
* KG: disagreements about whether we thought about this deeply.
* CW: we did. Understand Mike's feedback is coming now, but 0 user feedback in the past 2 years.
* KG: frustration - trying to put together a spec. At some point, have to make the decision to cut the changes.
* &lt;discussion>
* MW: are we proposing changing some of the other defaults?
* BJ: think that's what we want to get to the bottom of. Part of the reason I did this spreadsheet - a lot of defaults we have right now that match up with the graphics ecosystem so don't try to relitigate. A few where we don't match up. Requested we talk about them. A few of them - required - some of these were discussed extensively among Kai, Dzmitry and I. Don't want to revisit them. And a couple we've had requests to discuss.
* BJ: I think I sit somewhere between the two endpoints. Think it's a discussion coming in fairly late in the process. But I've seen that these kinds of issues that can be deferred again and again until it's too late to change them.
* JB: emergent processes that ensure that when we're under the most pressure, the largest issues come up. :)
* KG: anything in the "required" list, I'm not worried about authors messing up. Ignore all of those.
* Reason we're re-discussing - Chrome doesn't want to do the previously discussed strategy of making it required, then making it optional again with the other default.
* Resolved:
    * Make depthStencilAttachment.depthClearValue 1.
* GT: I've run into this. Why not make the other ones required?
* KG: we know when something's passed to us vs. not. We can generate warnings if you don't pass something to us. We can choose to have that warning on by default, or when DevTools is open. No breaking change needed. I hear you, super frustrating.
* KR: what about the verbosity of having to specify these?
* GT: you already have to specify all three for the state to be useful.
* &lt;break>

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#defaults-for-depthwriteenabled-and-depthcompare-may-be-surprising-3798-brandon">GPU Web F2F 2023-02-16/17</a></summary>

* CW: we suggest making depthWriteEnabled, depthCompare, required. depthClearValue - doesn't need to be required since it's a validation error to leave it undefined.
* MM: Thought we were going to make them required, then add defaults again _before_ v1?
* CW: that’s only necessary for implementation strategy. Spec can just choose now to either change to required, or change the defaults.
* KN: I still oppose the new defaults for V1, I want them required in V1 [if we make a change].
* KG: making them required is slightly better. Even better to have good defaults. Can litigate that later. Comfortable with having no defaults and making them required.
* CW: Gregg had good reasoning for keeping them required indefinitely. Better to make people explicitly choose what they want.
* GT: my preference - all required. Defaults impossible to litigate - will be a vote. Required = fewer changes, more explicit.
* KG: you can add these kinds of defaults by modifying the JS prototype, too. Consensus to make them required?
* MM: "the future's longer than the past". Can make changes in the future.
* CW: **resolved**. Editors to take it.

</details>
