### ISSUE TITLE
wgsl: Statement must not be only a type-constructor.

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3819]
We'd like to reconsider part of #3813 

We'd like to disallow the a statement whose top-level thing is a type-constructor expression.

Example:
```
struct S { a: i32 }
fn foo_bad() {
    i32();  // This parses, but we should disallow this.  
    S(15);  // This parses, but we should disallow this.
    42;     // Already disallowed; this doesn't even parse in the first place.
}
```
A type-constructor does not have side effects (once you've evaluated its arguments).  So there is no use for it.

If you really want to evaluate a type constructor, then use a phone assignment, even though that is silly:  `_ = i32();` 

We *do* explicitly allow function calls as statements.  The desirable use case is to capture the side effects, like this:

```
var<workgroup> p: i32;
fn foo_ok() {
    workgroupBarrier();  // allowed
    atomicStore(&p, 0); // allowed
    my_helper_does_something(); // allowed, whether or not the helper returns a value.
}
```

**Comment by dneto0** [comment]
For concreteness, the list to disallow is: https://gpuweb.github.io/gpuweb/wgsl/#type-constructor-expr

**Comment by dneto0** [comment]
cc: @ben-clayton

**Comment by alan-baker** [comment]
F2F 2023-02-16: introduce `@mustuse` and add to all builtins except side-effect built-in functions.

**Comment by ben-clayton** [comment]
nit: `@must_use` ?

**Comment by ben-clayton** [comment]
We've implemented this in tint as discussed at the F2F.

One additional validation rule we have is that it is an error for `@must_use` to be declared on a function that has no return type, as this makes no sense:

```
@must_use
fn f() {}
```

```
test.wgsl:1:2 error: @must_use can only be applied to functions that return a value
@must_use
 ^^^^^^^^
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#3819-wgsl-statement-must-not-be-a-type-constructor">GPU Web F2F 2023-02-16/17</a></summary>

* BC: current spec doesn't rule it out. Tint has validation to prevent this. This week, noticed a mismatch. Think we should rule it out. Probably a cause of bugs.
* MM: context: right now illegal to write variable name + semicolon. Can write ident + semicolon - function call. If ident is type name - that has no side effects, so should be illegal.
* BC: discussing this AM. Unification we're talking about - type initializers becoming builtins. Why should these be special? Propose a new attribute like C++'s nodiscard. Tag functions, don't evaluate this thing and throw it away. min/max, tag with this attribute, same for type initializers and converters. Used to have rule - every function call, have to use the return value. People complained. Atomic add, don't want to have to use the return value. 
* KG: do we have a method for discarding something?
* BC: phony assignment.
* AB: feels like we're going back on a decision we made. Don't think we're getting enough out of this to bother.
* KG: think this'd be good warning to have. Attribute still useful - you should not discard this. On the fence about making it a hard error.
* AB: in that case - leave it to the impl to add a diagnostic. Then can turn on diagnostics as error.
* MM: aren't there 3 options here? 1) if function returns something, you don't consume it - no error. 2) opposite - you call it, don't use the result - hard error. 3) some functions will cause errors for unused return values, some won't.
* AB: think the default should be no error. Up to impl to implement a diagnostic to turn it into an error if the user wants.
* BC: difficulty - no easy translation for the backend. Type constructor that's an array - have to work to pull out things from array constructor. Then throw away the array constructor.
* AB: Or you can introduce a fake name in the target language
* BC: you could.
* MM: thought we were discussing whether some constructions in WGSL cause errors or not. Why talking about code generation?
* DS: If you allow to call i32() then when we codegen we have a problem (cannot do array construction without assigning to something)
* KG: the spec's "as-if". As if you declared an array and didn't do anything.
* MM: get rid of the whole call.
* KN: but keep side effects that were in them.
* KG: do we have rough consensus to add nodiscard attribute. Should hinge the diagnostic off that. atomicAdd shouldn't warn if you don't use the result. Contention over hard errors. Inclined to say, leave it as a diagnostic.
* MM: do we have consensus for nodiscard?
* MM: would it make it in V1? It’s a significant feature.
* KG: we can add attributes and do nothing with them.
* MM: "free" what does that mean?
* KG: would we accept a PR that added @nodiscard to all of our builtins? Spec as builtin might not say it does anything with that yet. Could say “implementations **should** produce a warning”
* MM: want whatever is done here to be systems-driven. Not just constructors because they’re special. Want either no restriction or a nodiscard attribute.
* BC: ask if we add a diagnostic that we not do it for V1.
* KG: concern is implementation work? that you’re shipping
* BC: bunch of code in tint that assumes type constructors are not statements.
* JB: for our implementation it doesn’t matter. But would save you a lot of implementation work for v1.
* EG: something that can start out as an error and turn into a diagnostic later?
* KG: don’t love it but it’s a shippable thing
* AB: feel we’re reversing the decision that we had to use the phony _ = assignment everywhere.
* BC: not same, this affects things for which there’s no point at all in calling without saving the result
* BC: that decision was made because ……
* JB: nothing wrong with reversing decision as long as you don't forget considerations from last time.
* KG: what about making it an error for now, for V1? Tolerable?
* JB: attribute later to soften it? Seems fine.
* MM: so "discard" instead of "nodiscard"?
* KG: mark things nodiscard. We can make it an error at first, warnings later.
* MM: what about user functions?
* KG: think we should be able to mark them nodiscard.
* BC: we would annotate the builtins, and add the language attribute for users
* KG: language attribute, use it for our builtins.
* BC: can user type "nodiscard"? Only an hour's work. Fine.
* MM: what's the default?
* BC: default's as is right now. Function returns value, ignore it, that's fine.
* MM: can we reverse the default?
* BC: would break a lot of shaders
* KG: even ignoring that I would prefer discardable to be the default
* (...)
* DN: wrt naming, I like must_use more than nodiscard.
* BC/MM: we can’t use “discard” because we already have something called that.
* EG: rust community has interesting history and usage reports about #[must_use]
* JP: does it go on the function or on the return type?
* KG: I think it's function-level, not return-type thing.
* MM: goes next to the workgroup size declaration?
* JB: yes, or "vertex" or "fragment".
* DN: and we'll add this to builtin functions that don't have side effects?
* KG: yes.
* AB: texture sampling? Tied up with type constructors too. Right now they're not functions.
* KG: think an easy way to figure out what should and shouldn’t be, is part of this decision is so tint can ship. So what does tint effectively treat as must_use now?
* AB: if you define the attribute as only applying to functions - where do we put that annotation? Don't think you should introduce this without moving. (?)
* KG: to me type constructors _are_ builtin functions.
* MM: agree. Just named the same way.
* JB: you saying we have to apply this attribute to types too? Type constructors always side-effect-free and meaningless.
* AB: for now yes. Spec is set up so - we should do issue #3823 first as approved. Do it at the same time.
* KN: in a future where type constructors aren’t side effect free, it’s because you’re able to write constructors for them. So can add the attribute to the constructor function if desired.
* KN: in Rust, mustuse can go on functions and types. On types - if you return that type from a function, the function implicitly becomes mustuse (must use its return value). Return a `Result&lt;>` for error handling - Result&lt;> has mustuse. So caller can't accidentally throw away an error.
    * JB: it's a crucial move that Rust made.
    * KN: should reserve the idea of putting mustuse on types.
* MM: still have Q's about the default. Lot of code that doesn't have annotations. We haven't shipped so not concerned about that. Why not flip the default?
* BC: reason we got rid of the error was users complained that calling functions and discarding results was an error, and was annoying.
* KG: think there's momentum for discardable functions by default, and adding nodiscard yourself. If I were designing the language from scratch, I would not make the default "mustuse". Tolerable to go in this direction?
* MM: we're satisfied with that.
* &lt;consensus>
* KG: as Alan mentioned - consensus toward 3823. Type constructors as builtins, can tag them with mustuse.
* KG: will come back to this post-V1. Consider warning instead of hard error.
* JB: is it nicer in the spec to treat type constructors as builtin functions?
* BC: maybe not in spec. But the future of these becomes clearer if we want to add user overloads. Consider everything that can take templates, easier than splitting spec into distinct things.
* JB: so, spec'ed as - when you define a type, this introduces a builtin function like so?
* AB: almost same stuff we have for type constructor expressions. Move into builtin functions chapter.
* JB: so, builtin functions i32, etc.
* MM: that'd be great, just like bitcast.
* AB: already have… no worse than structs & type aliases. Had issues filed about this in the past. Why no const on this? etc.
* JB: so when you define them as builtin functions you just make them const in the usual way. I see.
* KG: with type aliases to preserve that - type alias = i32, and want to construct it?
* BC: another topic to discuss.
* **Resolution:**
    * Turn everything into builtins
    * Add mustuse annotations. They'll match what's in Tint.
    * mustuse is a requirement. Hard error if you don't consume the result.
* That'll be V1.
* JB: easier to remove mustuse in the future. Be liberal in what you add it to. Judgment call though.
* AM: when C++ committee added nodiscard - they felt they made the default wrong. Would have wanted all functions that return something to be nodiscard. And have added "discard" to things you want.
* MM: that's our preference too.
* KR: but there was user feedback saying that that was too annoying.
* &lt;discussion>
* KG: I think the Rust solution of putting it on types is nice. But do I want a compiler function so I have to annotate every single thing?
* AM: can you share the user research on this in Rust?
* EG: I can compile some user reports and present that.

</details>
