### ISSUE TITLE
Add `rgb10a2uint` texture format

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#3841]
It seems that this format with RENDER_ATTACHMENT and multisampling is supported by all backends.

It maps to:
- Metal: `rgb10a2uint`
- D3D: `DXGI_FORMAT_R10G10B10A2_UINT`
- Vulkan: `A2B10G10R10_UINT_PACK32`

I'm not sure if it was previously dismissed (for any reason) - couldn't find a discussion about it.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#post-v1-add-rgb10a2uint-texture-format-3841">GPU Web F2F 2023-02-16/17</a></summary>

* CW: seems to be available everywhere. Didn't check Vulkan 1.0 spec though.
* JB: Kai, you have a correspondence doc.  Is it listed there?
* KN: Yes, it should, but that data isn’t there yet.
* KG: put it in core, and if it doesn't work, take it out? Try it.
* CW: in Milestone 2?
* KG: yes.

</details>

**Comment by kainino0x** [comment]
**Metal:**

Always supported (even in older metal feature set tables docs)

**D3D12:**

Always supported in [FL11_0](https://docs.google.com/spreadsheets/d/1ALlgyOA5BXXhJDZXPyEQ-vXV_E8IKZfe1xcNmhIM4Mw/edit?usp=sharing).

**Vulkan:**

```py
    add_rq('rgb10a2uint', lambda info: format_supported_with_optimal_tiling_features(
        info.fmts, vk.Format.A2B10G10R10_UINT_PACK32, vk.FormatFeature.COLOR_ATTACHMENT | vk.FormatFeature.SAMPLED_IMAGE))
```

```
Requirement "rgb10a2uint" loses no further reports!
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/Minutes-2023-04-19#add-rgb10a2uint-texture-format-3841">GPU Web 2023-04-19 Atlantic</a></summary>

* KG: seems we could literally just add this. Call it Post-V1-Polish instead of Milestone 2?
* CW: is this supported on all WebGPU V1 platforms?
* KG: think it is.
* CW: would like to see the Vulkan Info report for this, and double-check on D3D12. Issue doesn't mention these. Would like to have the fact that it is supported recorded in the issue.
* CW: if we can determine it's available / supported, then we add the format?
    * MM: thumbs up
    * KG: sure.
* KN: I volunteer to do the GPUInfo investigation.
* CW: we'll do this for next week, then tacit resolution. 

</details>

**Comment by kainino0x** [comment]
Meeting: Agreed to add this for "polish" (i.e. we can open a PR and land it).
Marking editorial for someone to get around to doing this. (PRs welcome!)

**Comment by kainino0x** [comment]
Just remembered we might need to be able to feature detect this

**Comment by teoxoy** [comment]
> Just remembered we might need to be able to feature detect this

Could you expand on this? Last time I looked into support for it, it was present in all APIs we target.

**Comment by kainino0x** [comment]
Sorry I mean, we might need to provide a surface so applications can feature detect whether this is available. Since Chrome has already shipped without it.
