### ISSUE TITLE
Would having Float16Array in JS be useful for integration with WebGPU?

### ISSUE THREAD

**Issue by bakkot** [gpuweb/gpuweb#3848]
I'm on TC39. We've had a request from the ColorWebCG [to add a `Float16Array`](https://github.com/w3c/ColorWeb-CG/blob/14bffcb85327b011026def4f7ebf9b88e724afad/canvas_float.md#choice-of-float32array-for-imagedata) to represent float-backed canvases.

In pursuing [that proposal](https://github.com/tc39/proposal-float16array) within TC39, it would be helpful to know if it would be useful for people integrating with WebGPU as well. I saw that [float16 is supported in WebGPU](https://github.com/gpuweb/gpuweb/issues/2512), and I saw [an example of wrapping a buffer in a `Float32Array`](https://gpuweb.github.io/gpuweb/explainer/#example-eed014f1). Can I conclude that therefore some buffers are created holding float16 values, and that it would be helpful in some cases to wrap those buffers in a `Float16Array`? I am guessing so, but I haven't gone through the WebGPU spec before, and it's a bit too large for me to confidently conclude either way.

I've tentatively added that as a use case to the proposal for now, but am happy to remove it if I'm mistaken.

(To be clear, this would be specifically IEEE754 "binary16" floats, not bfloat16.)

**Comment by ben-clayton** [comment]
I believe that `Float16Array` would indeed be a helpful addition to complement WGSL's `f16` feature.

We [added a dependency](https://github.com/gpuweb/cts/pull/1828) to https://github.com/petamoriken/float16 for WebGPU CTS, in order to test the `f16` feature. This is a good signal that the proposal would benefit WebGPU users.

**Comment by bakkot** [comment]
Great, thanks!

**Comment by grovesNL** [comment]
@bakkot I'm not sure if this is helpful, but there's interest in `Float16Array` for WebGL dating back to 2014 or so, e.g., https://esdiscuss.org/topic/float16array

**Comment by zoddicus** [comment]
I agree with Ben's assessment (since I was the one that pulled in the dependency to the CTS).

Currently the CTS only uses 16-bit floats for a handful of 32-bit based builtins (quantizing to 16-bit and packing/unpacking to/from 16-bit).
When CTS adds testing for the WGSL f16 data type, there is going to be a bunch more code depending on 16-bit floats, so having it be part of JS proper would be nice.
I expect there is going to be many users of WebGPU/WGSL in the future that are going to want `Float16Array` support in JS, when they start writing shaders using 16-bit floats.

**Comment by bakkot** [comment]
Update: the proposal to add Float16Array to JavaScript today reached [stage 3](https://tc39.es/process-document/), meaning the design is finished, the committee is in favor, and engines can start implementing and shipping it.

**Comment by kainino0x** [comment]
@bakkot that's incredible! Congrats and thank you for working on it! We look forward to implicitly picking it up when BufferSource is updated :)
