### ISSUE TITLE
add query for list of WGSL software/shader-lang extensions (e.g. do-while)

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3875]
This is the API side of #3149 

From [here](https://github.com/gpuweb/gpuweb/issues/3149#issuecomment-1433869176):

>*  The API side exposes a list of supported features (as a list of strings)
>    * This allows applications, and the CTS, to see what is supported.
>    * Discussion: is this on the adaptor, or the device? Argument in favour of the adaptor is that these are "sugar" features.

**Comment by dneto0** [comment]
Official minutes are not posted yet, but the google docs bookmark is [here](https://docs.google.com/document/d/1bbwoAu7NZ5GAWAE12xUNZi08fRuSRDfYLzHxV6yFDF8/edit#bookmark=id.mmb1492enidn)

**Comment by dneto0** [comment]
After some reading, it seems this fits into the 'features' list of a GPUAdapter already?

I *think* we only need to say in the WGSL spec that software-extensions are listed in the GPUAdapter features list.

**Comment by dneto0** [comment]
After internal discussion, the intent is these are not GPUFeatureName, because the application never has to opt into them.
We need a separate enum for these software-only features, and a separate adaptor property for them.

**Comment by toji** [comment]
The [`GPUSupportedFeatures` interface](https://gpuweb.github.io/gpuweb/#gpusupportedfeatures) seems like it's still appropriate to use here. We'd need to tweak the definition to allow for more than just strings from the [`GPUFeatureName` enum](https://gpuweb.github.io/gpuweb/#gpufeaturename)`, and then have each specific use declare which enum it can pull from, but that wouldn't be too bad.

My reading of #3874 is that whether a WGSL extension is "software" or not, it will always need a `requires` directive in order to use, correct? It's not clear to me if the string that you will need to add to the `requires` directive will always match the `GPUFeatureName`. Given that the only existing extension does match that pattern I'm going to assume that's the case, but I could perhaps envision a scenario where a given WGSL extension relies on multiple WebGPU features, or a given WebGPU features enables multiple WGSL extensions.

Regardless, I think what I'd want on the `GPUDevice` is a very clear list of which directives I can use in my shaders, regardless of whether they are explicitly enabled extensions or software extensions, because I'm going to be enabling them the same way. Even if it involves a bit of data duplication, I'd prefer that to saying "You need to check two different lists, based one some internal concept of whether a feature is "software" or not. As such I'd propose something like this:

```webidl
enum GPUShaderExtensionName {
  "shader-f16", // Duplicated from GPUFeatureName?
};

partial interface GPUAdapter {
  [SameObject] readonly attribute GPUSupportedFeatures features; // Existing property
  [SameObject] readonly attribute GPUSupportedFeatures defaultShaderExtensions;
}

partial interface GPUDevice {
  [SameObject] readonly attribute GPUSupportedFeatures features; // Existing property
  [SameObject] readonly attribute GPUSupportedFeatures shaderExtensions;
}
```

On the adapter the `defaultShaderExtensions` (names subject to bikeshedding) would include all the "software" extensions, with the name hopefully suggesting that nothing needs to be done to enable them. On the device side the `shaderExtensions` would include both any software extensions in the adapter's `defaultShaderExtensions`, AND any extensions that were enabled by one of the device `features`. That functions both as a convenience for developers (one place to check) and doesn't lock us in to an exact 1:1 features-to-wgsl-extensions mapping forevermore.

Both new `GPUSupportedFeatures` would be allowed to contain values from a new `GPUShaderExtensionName` enum, that would contain both all the software features and duplicate any feature names that also function as shader extensions. That would largely be for easier developer reference, so they can quickly see which possible values may appear in the extension sets (And, again, gives wiggle room to move away from a 1:1 mapping in the future.)

No changes are made to the device descriptor.

(Side note: It feels strange that WebGPU describes these things in terms of "features" and WGSL describes them in terms of "extensions". Is there a reason for the split?)

**Comment by dj2** [comment]
No, the `requires` line is optional. It's a way to tell the compiler `I must have this thing` but even if you didn't say that you can still use it. It's a hint to the compiler, versus a request to use something.

**Comment by kainino0x** [comment]
> An additional thing to consider is that maybe the software extensions don't need to be listed on the adapter at all?

Agreed with this. For the same reason I picture this being on `navigator.gpu` only, not adapters or devices. Not sure if it should be:
- query: `navigator.gpu.hasWGSLLanguageFeature('do-while')`
- FrozenArray: `navigator.gpu.wgslLanguageFeatures.includes('do-while')`
- interface: `'doWhile' in navigator.gpu.wgslLanguageFeatures` (gives `true` or `false`) or `navigator.gpu.wgslLanguageFeatures.doWhile` (gives `true` or `undefined`)

**Comment by greggman** [comment]
does putting these on `navigator.gpu` become a passive privacy issue? With `requestAdaptor` the browser has the opportunity to ask the user if the page should be allowed to look up this info. With them on `navigator.gpu` it does not?

**Comment by Kangz** [comment]
This is completely correlated with the browser and its version, so it's ok?

**Comment by kainino0x** [comment]
Maybe technically, but every time a browser ships a new JS-visible API of any kind you can immediately see it's available (`typeof GPUBuffer` or whatever). I don't see how it could help to make WGSL feature detection more secretive than other features.
