### ISSUE TITLE
HW Clip Planes support

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#390]
This is a feature request to support HW clip planes. It is OK for a platform to return that it support 0 HW-clip planes.

Each of the "new" 3D API's have HW-clip plane support (atleast a cursory look supports this):

1. Vulkan: VkPhysicalDeviceFeatures has fields for both clipping and culling (shaderClipDistance and shaderCullDistance) along with how many from the fields maxClipDistances and maxCulldistances from VkPhysicalDeviceLimits

2. Direct3D12: see the enumeration D3D12_CLIP_OR_CULL_DISTANCE_COUNT at https://docs.microsoft.com/en-us/windows/win32/direct3d12/constants

3. Metal: see 5.2.3.3 Vertex Function Output Attributes of the Metal 2.2 shading spec,
https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf.

I am just advocating for clip-disance and not cull-distance as the latter is more esoteric IMO.

I advocate that this feature to be part of the 1.0 core interface and not as an extension.

**Comment by kvark** [comment]
It would be great to have. VulkanDB [reports](https://vulkan.gpuinfo.org/listreports.php?feature=shaderClipDistance&option=not) it not being available on a whole lot of mobile GPUs as well as Intel, which could be a showstopper.

**Comment by prideout** [comment]
FWIW, ClipDistance and CullDistance are available in the GLSL-ES 3.2 spec (not in earlier versions) however the API spec for ES 3.2 makes no mention of them in section 12.5 (Primitive Clipping).

So, I doubt there is great support for this feature from mobile vendors.

**Comment by magcius** [comment]
Bizarre that Intel does not have clip planes, since it's required for D3D10+ through the SV_ClipDistance semantic.

**Comment by krogovin** [comment]
Intel most certainly has clip-planes. Indeed, the open source Mesa drivers implements clip-planes as far back as Gen4 (which was a Direct3D *9* part). These clip-planes are NOT emulated with discard either, they genuinely clip triangles. I can see from the source code that the open source Vulkan implementation from Intel should support clip-planes (see file genX_pipeline_state.c, method emit_3dstate_clip()).

However, I don't know about the Vulkan driver MS-Windows from Intel (these are two totally different code-bases). However, for that platform, chances are the D3D12 API is to be used instead. 



If the Intel Vulkan open source driver does not support clip-planes, file a bug ASAP.

**Comment by krogovin** [comment]
I am advocating that it is OK, like in Vulkan, to report zero clip-planes. When that happens an application is going to have to do something: some will go the discard route and others will roll up their sleeves and go the compute route. Both fallbacks are slower, but an app has got to do what an app has got to do.

**Comment by jdashg** [comment]
Reporting zero clip-planes seems fine to me.

**Comment by frustum** [comment]
Clip-distance is a great feature to have. Clip-distances can emulate multiple viewports as well (which is missing now).

**Comment by sseanwang** [comment]
Clip-distance is an very important and useful feature in many industrial 3d app, I hope it can be implemented soon

**Comment by magcius** [comment]
For a single clip plane, consider using an oblique projection matrix: http://terathon.com/code/oblique.html

**Comment by unvestigate** [comment]
As suggested in the matrix webgpu room, I'd like to mention that this would be a very nice addition to the spec. Having ported the renderer of our game engine from Vulkan/D3D11 to WebGPU, I currently cannot implement certain effects because clip planes aren't supported. This is ironic since all of the backends we target (Metal,D3D,Vk) support clip planes just fine.

**Comment by olofwalker** [comment]
I'm in the sam boat as @unvestigate, I need clip planes as well.

**Comment by kohakukun** [comment]
I'm also interested in this feature 👀

**Comment by kdashg** [comment]
> Reporting zero clip-planes seems fine to me.

I disagree with this these days. :)

**Comment by kdashg** [comment]
There's useful background info on this feature here:
https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#15.4%20Clipping
(especially in 15.4.1 and 15.4.2)

**Comment by unvestigate** [comment]
> If we can confirm that Metal also supports 8 clip distances, we can have this be a static limit.

I cannot find the max value listed anywhere either, not in the MTL shading language spec, nor anywhere else. The closest thing I could find is an old post on a bug in UE, which sorta suggests using clip planes 0-7 (even though the comment actually talks about 0-8). See the "fix to MetalUtils.cpp".

Any Apple folks around who could confirm this?

**Comment by mwyrzykowski** [comment]
`[clip_distance]` supports 8 values, e.g., `float clipDistance [[clip_distance]] [8];`

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐01‐23-Minutes#hw-clip-planes-support--issue-390-m2">WGSL 2024-01-23 Minutes</a></summary>

* JS: Investigating the limit of number of clip planes allowed. It seems Metal has an undocumented limit of 8.
* KG: How to bridge the gap between the desire and what can be done.
* JS: We’re still investigating support level.
* DN: Primer on this feature?
* KG: See the D3D11 functional spec;  describes it well.
* DN: ok.
* KG: There’s a similar investigation for an extension for WebGL.

</details>

**Comment by Jiawei-Shao** [comment]
# User Defined Clipping

## Introduction
User-defined Clipping is a way to do more primitive clipping besides the default clipping rules in WebGPU (clipping against the clip volume).

With user-defined clipping, we can define multiple clip distances (in `f32`) as the output of the vertex shaders, and each of them is assumed to be a float32 signed distance to a plane. Primitive setup only invokes rasterization on pixels for which the interpolated plane distance(s) are >= 0 ([Reference, chapter 15.4.1](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm))

## Uses
User-defined clipping can be used to discard the primitives that are not necessary to be processed by the fragment shader. 

The classic use is to clip all vertices in a scene that are beyond a certain plane. The clip distance in this case is the distance to the plane, with the visible side of the plane providing non-negative distances.

### Rendering water reflection or refraction 
The water plane can be a user-defined clipping plane. Reflection should only be related to the objects that are above the water, and refraction should only be related to the objects that are under the water ([example](https://www.youtube.com/watch?v=0NH9k4zTAqk)).

### CAD
User-defined Clipping Plane is useful in CAD to view the internal structure of the current object ([example1](https://www.youtube.com/watch?v=FU-Wsf7Sfs0), [example2](https://www.youtube.com/watch?v=4aKSV3uuh38))

### GUI
In GUI elements, it is often desired to ensure that objects inside a GUI window cannot be drawn outside of that window.

User-defined clipping can be per-vertex values, sampled from vertex arrays. The Vertex Shader will be able to use them to set the gl_ClipDistance outputs to do such clipping against each GUI window. ([Reference](https://www.khronos.org/opengl/wiki/Vertex_Post-Processing#User-defined_clipping))

## User Defined Clipping in WebGPU

### Clip Distance in native graphics APIs


|         | D3D11 and D3D12 | Metal | Vulkan| OpenGL | OpenGL ES |
|---------|-------|-------|-------|--------|-----------|
|Support |Always|Always|[`VkPhysicalDeviceFeatures.shaderClipDistance`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceFeatures.html)<br>(Coverage: [82.38%](https://vulkan.gpuinfo.org/listfeaturescore10.php):<br>Android (67.52%), Windows (99.4%), Linux (98.86%), macOS (100%), iOS (100%)|[GLSL 1.3](https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_ClipDistance.xhtml)|[EXT_clip_cull_distance](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_clip_cull_distance.txt)|
|Minimum Clip Distances if supported|8<br>(`D3D12_CLIP_OR_CULL_DISTANCE_ELEMENT_COUNT`)|8|8<br>(`maxClipDistances`)|8<br>(`MAX_COMBINED_CLIP_AND_CULL_DISTANCES_EXT`)|8<br>(`MAX_COMBINED_CLIP_AND_CULL_DISTANCES_EXT`)|
|Built-ins when use 8 clip distances| `SV_ClipDistance0` (`float4`)<br>`SV_ClipDistance1` (`float4`)|`float [[clip_distance]][8]`| `ClipDistance` |`highp float gl_ClipDistance[8]`|`highp float gl_ClipDistance[8]`|
|User defined culling|Supported|**Not Supported**|Supported|Supported|Supported|
|As Fragment Input|Supported|**Not Supported**|Supported|Supported|Supported|
|Additional API side commands| - | - | -|`glEnable(GL_CLIP_DISTANCE0)`<br>`glDisable(GL_CLIP_DISTANCE0)`|`glEnable(GL_CLIP_DISTANCE0)`<br>`glDisable(GL_CLIP_DISTANCE0)`|

In addition, user-defined clipping and culling has been supported in WebGL as an extension [WEBGL_clip_cull_distance](https://registry.khronos.org/webgl/extensions/WEBGL_clip_cull_distance)

### Proposal in WebGPU

We'd like to propose user-defined clipping as an optional WebGPU feature. 

- User-defined clipping cannot be a core feature because it is still not supported on some old Android devices.
- User-defined culling is not included because Metal doesn't support it.
- Two built-ins are introduced as vertex stage outputs: `[[clip_distance0]]` and
`[[clip_distance1]]`, which can both be `f32` or `vec2f` or `vec3f` or `vec4f` to align with `SV_ClipDistance0` and `SV_ClipDistance1` in HLSL. In the WGSL shader the developer can either declare `[[clip_distance0]]` or both `[[clip_distance0]]` and `[[clip_distance1]]`, which depends on how many user-defined clip distances are used.
- Each user-defined clip distance vertex outputs will consume 1 inter-stage shader variable and the certain number of inter-stage shader components that depends on its declaration.
- Clip distances as fragment stage inputs are not included because Metal doesn't support it.

**Comment by Kangz** [comment]
I agree that it would be nice to have clip distances even on hardware that doesn't support it by emulating when compiling the render pipeline, but I don't know how much implementations will want to take this on. It is a non-trivial amount of work in the compiler.

Why do the clip distances need to be numbered unless we want to access them in the FS? It seems that `@clip_distance` could work. (also `@clip_distance(N)` otherwise?). It's a bit inconvenient for the developers to have to pack things in vec3s. What about allowing not just two clip distances but N < 8 and having them use inter stage variable slots as usual?

**Comment by Jiawei-Shao** [comment]
> Why do the clip distances need to be numbered unless we want to access them in the FS? It seems that `@clip_distance` could work. (also `@clip_distance(N)` otherwise?). It's a bit inconvenient for the developers to have to pack things in vec3s. What about allowing not just two clip distances but N < 8 and having them use inter stage variable slots as usual?

I think making `@clip_distance` an array or vector is helpful for the developer to iterate all the planes in a for-loop:

```
  for (var i = 0; i < clipPlanes; i++){
    clipDistance[i] = dot(planes[i], currentLocation);
  }
```

**Comment by Jiawei-Shao** [comment]
> Good point, then maybe require that `@clip_distance` be an `array<f32/f16, N>` and make it consume N/4 variable slots.

In fact I suggest we use HLSL tradition (two `vec4f`) instead of MSL and Vulkan (GLSL) ones (an `f32` array) because translating `clipDistance0 : vec4f` and `clipDistance1 : vec4f` into `float clipDistances[N]` is straightforward:
```
clipDistance0[i] -> clipDistances[i]
clipDistance1[i] -> clipDistances[i + 4]
```

While translating `float clipDistances[N]` into HLSL will introduce a check on the index, which seems unnecessary and may cause performance penalty:
```
clipDistance[i]

->

if (i > 4) {
    clipDistance0[i]
} else {
    clipDistance1[i - 4]
}
````

**Comment by Kangz** [comment]
The check doesn't seem expensive, and look like something that the developer would have to write anyway if they uses more than 4 clip distances no?

**Comment by kdashg** [comment]
Without an if: `select(clipDistance0, clipDistance1, i >= 4)[i % 4]`

**Comment by kdashg** [comment]
What happens if you don't write to these output?

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐03‐12-Minutes#hw-clip-planes-support--issue-390">WGSL 2024-03-12 Minutes</a></summary>

* [From the API meeting](https://docs.google.com/document/d/1PLjCjOJM6K3SIh8CiiOQGrXk7BjfvR9XhRlTHX7mp3I/edit#heading=h.vnhxdq3d21ui): “Finish discussing the shape of the WGSL builtins in the WGSL meeting.” (Added by KN who probably won’t be here and doesn’t know needs to be discussed exactly. Feel free to punt if needed, but I think Jiawei wanted to keep working on this.)
* KG: HLSL exposes it as up to 2 vec4f, and others use arrays.
* KG: My taste is to make it arrays of floats.
* (JiaweS: Agreed with meeting emoji)
* (JB: Agreed with thumbs up)
* KG: Think the translation is relatively small, and affects (MSL?)
* KG: I propose an array of 8 floats.
* DN: Agree.
* BC: Agree. Prefer don’t baking in the two vectors.
* **_Consensus for array of floats._**
* DN: Need to make sure the output slots counting is clear.  E.g. that array-of-4 floats really only counts as one output slot.
* KG: What happens if you don’t write the outputs?  
* JS: If not written, then they are not clipped.  
* JB: Background question: by using these clipping planes we can chop up a triangle in more ways.
* DN: You’re adding more clipping half planes.
* JB: Never generates anything that’s concave? (correct)

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-03-06#hw-clip-planes-support-390">GPU Web 2024-03-06 Pacific-time</a></summary>

* JS: last WGSL meeting discussed this: widely supported, useful. Supported in WebGL as an extension. Think we should have it in WebGPU as an extension.
* JS: small issue - HLSL style or Metal style. Think HLSL style is easier to implement in Vulkan. If Metal style, should at least have an if-statement to do a check.
* KG: potentially have overhead if we don't optimize it. I don't like the HLSL style, but that's a WGSL style question rather than an API style question. Do we add this now? And is it an optional feature?
* JS: yes, it'd be optional.
* KG: think it's time to write a PR for this. Finish discussing the shape of the WGSL builtins in the WGSL meeting.
* JS: we'll do it.
* KG: thanks.

</details>

**Comment by Jiawei-Shao** [comment]
FYI "clip-distances" has been enabled by default since Chrome 131.
