### ISSUE TITLE
depthWriteEnabled and depthCompare are required even for stencil-only formats

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3905]
See thread: https://github.com/gpuweb/gpuweb/pull/3849/files#r1122411287

Can be post-v1 if we want to punt it.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/Minutes-2023-03-08#depthwriteenabled-and-depthcompare-are-required-even-for-stencil-only-formats-3905">GPU Web 2023-03-08</a></summary>

* CW: not helpful for developers.
* KN: rare enough case that I don't care about this for V1, but wanted it documented.
* KG: +1
* MM: what's the reason to not have the default?
* KN: in the stencil only case or generally?
* MM: stencil.
* KN: makes an optional boolean. tri-state thing, annoying for implementations. Would rather deal with this later.
* MM: think optional seems straightforward. Benefits seem to outweigh the costs.
* KG: I think if you want a proposal, you should make one. I think otherwise we’re fine for V1.
* KN: part of complexity - two possibilities. It's either regular validation, or make it a JS exception so impls don't need to wire the tri-state through.
* CW: 
* KG: if no proposal, can leave this incomplete for v1
* KR: If these are required in the WebIDL and you didn’t provide them, that would be a JS exception. So I think the closer we can get to that behavior the better.
* KN: Different from how we do most validation.
* **CW: would like to propose we fix this in Milestone 2.**
* KG: agreed, would like to not do anything right now.
* **MM: I'm willing to make a concrete proposal**.
* KG: take an AI. 🙂

</details>

**Comment by kainino0x** [comment]
An additional note from someone who ran into the new validation: depthCompare doesn't need to be required even for depth if it's not used for anything: i.e. if depthWriteEnabled is `false` AND depthFailOp is `"keep"`, I think.

**Comment by beaufortfrancois** [comment]
@kainino0x Shall we close this issue?

**Comment by kainino0x** [comment]
It looks like we still need to do the additional thing above, so we should keep it open for now.

> An additional note from someone who ran into the new validation: depthCompare doesn't need to be required, even for depth attachments, if it's not used for anything: i.e. if depthWriteEnabled is `false` AND depthFailOp is `"keep"`, I think.

**Comment by kainino0x** [comment]
That change should go in "tacit resolution queue" before landing it, though, because the editors' agreement wasn't a standardization consensus yet.

**Comment by beaufortfrancois** [comment]
Shall I send a spec PR?
