### ISSUE TITLE
wgsl: float to integer conversions should saturate in the destination type, not the source type.

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3908]
Here's the behaviour on Apple clang++:

signed integers:
```
2147483520.000000 +        0*65536 = 2147483520.000000 -->   2147483520
2147483520.000000 +       16*65536 = 2148532224.000000 -->   2147483647
2147483520.000000 +       32*65536 = 2149580800.000000 -->   2147483647
2147483520.000000 +       48*65536 = 2150629376.000000 -->   2147483647
2147483520.000000 +       64*65536 = 2151677952.000000 -->   2147483647
2147483520.000000 +       80*65536 = 2152726528.000000 -->   2147483647
2147483520.000000 +       96*65536 = 2153775104.000000 -->   2147483647
2147483520.000000 +      112*65536 = 2154823680.000000 -->   2147483647
2147483520.000000 +      128*65536 = 2155872256.000000 -->   2147483647
2147483520.000000 +      144*65536 = 2156920832.000000 -->   2147483647
2147483520.000000 +      160*65536 = 2157969408.000000 -->   2147483647
2147483520.000000 +      176*65536 = 2159017984.000000 -->   2147483647
2147483520.000000 +      192*65536 = 2160066560.000000 -->   2147483647
2147483520.000000 +      208*65536 = 2161115136.000000 -->   2147483647
2147483520.000000 +      224*65536 = 2162163712.000000 -->   2147483647
2147483520.000000 +      240*65536 = 2163212288.000000 -->   2147483647
```
unsigned integers:
```
4294967040.000000 +        0*65536 = 4294967040.000000 -->   4294967040
4294967040.000000 +       16*65536 = 4296015872.000000 -->   4294967295
4294967040.000000 +       32*65536 = 4297064448.000000 -->   4294967295
4294967040.000000 +       48*65536 = 4298113024.000000 -->   4294967295
4294967040.000000 +       64*65536 = 4299161600.000000 -->   4294967295
4294967040.000000 +       80*65536 = 4300210176.000000 -->   4294967295
4294967040.000000 +       96*65536 = 4301258752.000000 -->   4294967295
4294967040.000000 +      112*65536 = 4302307328.000000 -->   4294967295
4294967040.000000 +      128*65536 = 4303355904.000000 -->   4294967295
4294967040.000000 +      144*65536 = 4304404480.000000 -->   4294967295
4294967040.000000 +      160*65536 = 4305453056.000000 -->   4294967295
4294967040.000000 +      176*65536 = 4306501632.000000 -->   4294967295
4294967040.000000 +      192*65536 = 4307550208.000000 -->   4294967295
4294967040.000000 +      208*65536 = 4308598784.000000 -->   4294967295
4294967040.000000 +      224*65536 = 4309647360.000000 -->   4294967295
4294967040.000000 +      240*65536 = 4310695936.000000 -->   4294967295
```
The ugly program for the signed case is:

```c++
#include <iostream>
#include <cstdint>

void u(float base, uint32_t i, float fpfi) {
  //printf("%14f + %8u*65536 = %14f --> %12i\n", base, i, fpfi, int32_t(fpfi));
  printf("%14f + %8u*65536 = %14f --> %12u\n", base, i, fpfi, uint32_t(fpfi));
}
int main() {
  float f = 4294967295u;
   f = 4294967040u;
  for (uint32_t i = 0u ; i < 250 ; i += 16) {
    float fi = i*65536;
    u(f,i, f + fi);
  }
  return 0;
}
```

Earlier we made the rule because of my reading of the C++ spec saying that floating to integral conversions truncate toward zero in the *original* type, not the target type.
See meeting minutes (original doc): https://docs.google.com/document/d/1bW9E11tXsbzHG7iMHxMF7F0gNFu5_mtKEEKkM2O_en0/edit#heading=h.7x4c45ghpqfl

**Comment by dneto0** [comment]
Original issue is #2434

**Comment by dneto0** [comment]
I think the code I wrote in the original post exercises undefined behaviour in C++.

I stand by the analysis in  https://github.com/gpuweb/gpuweb/pull/2434#issuecomment-998334160 (showing undef behaviour in underlying specs), and the edge case analysis in https://github.com/gpuweb/gpuweb/pull/2434#issuecomment-1005971463 


The polyfill suggested in #2434 is
```
u32( a: f32 ) -> u32 {  return u32(clamp(a, 0.0, 4294967040.0)); }
```

An alternative is to saturate to UNIT_MAX more often.
```
u32_alternative( a: f32) -> u32  { return select(0xffffffff, select(u32(a), 0, a >= 0), a > 0x1.fffffep+31); }
```
Note:
4294967040.0    = 0x1.fffffep+31   // largest u32 value representable exactly in f32
4294967296.0    = 0x1p+32

**Comment by dneto0** [comment]
The u32_alternative polyfill given above would map NaNs to UINT_MAX.

**Comment by ben-clayton** [comment]
> The u32_alternative polyfill given above would map NaNs to UINT_MAX.

Curious to know if this is preferable to mapping `NaN` to `0`.

Pros:
* User less likely to silently rely on `NaN`s converting to `0`.

Cons:
*  User *can't* rely on `NaN`s converting to `0`.  
   * We currently do not provide a `isNaN` builtin - so a user is unable to test for `NaN` before conversion. The user can't safely condition on the post-conversion value, as it's ambiguous whether it was `NaN` or the truncated float value. For this reason, `0` might be the 'less offensive' number.
   * In a future world, when WGSL has a `isNaN` builtin: If the user does have an algorithm that can DBZ in edge cases, and they're concerned about performance, and don't want to add branches, in my experience they likely want to mask these values away to `0`. An example that comes to mind is screen-space effects (tone mapping, HDR blooming, etc), where you're working with 2D image kernels. `NaN`s have a tendency to creep into this sort of stuff, and virally  spread across the whole kernel. For kernels that perform integer accumulation (e.g. bloom effects), often the easiest option is to `select(value, 0, isNaN(value))` these out. By flipping the conditions, they'll get this behaviour for free. This might be less of an issue for a world with FP framebuffers.
* Inconsistent conversion values for `NaN` → `i32` vs `NaN` → `u32`.

**Comment by ben-clayton** [comment]
While implementing this, I've realised that you can't convert `NaN` → `0` for `i32` without yet another `select`.
A limit value might be the best we can implement without incurring too much overhead.

**Comment by dneto0** [comment]
I got the parameter order wrong for select.

Should be

```
u32_alternative( a: f32) -> u32  { 
    return select( select(0,u32(a), a >= 0), 
                            0xffffffff, 
                            a > 0x1.fffffep+31);
}
```

**Comment by dneto0** [comment]
this also works:    select(4294967295, select(u32(v), 0, (v < 0.0)), (v < 4294967040.0)) 


It maps NaNs to UINT_MAX as well.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-03-07-minutes#wgsl-float-to-integer-conversions-should-saturate-in-the-destination-type-not-the-source-type--issue-3908">WGSL 2023-03-07 Minutes</a></summary>

* DN: E.g. there was no way to get uint::max into a float, so this is BC’s proposal for how to fix it.
* BC: This was discussed before, and criticized for requiring conditionals. My current proposal uses two selects instead of true conditionals. 
* MM: I am concerned about performance here, because adds and muls on float are expected to be mega-fast.
* DN: This is just for conversions, not for arithmetic.
* MM: What is it these examples?
* DN: Oh, not that part, look further down.

	`u32_alternative( a: f32) -> u32  { return select(0xffffffff, select(u32(a), 0, a >= 0), a > 0x1.fffffep+31); }`



* MM:: The common case of conversions should be indexing into an array, which we already check, so I’m not worried about this then.
* JB: Worried that people will care about perf here, and we’re giving that up for a feature that fewer people care about
* BC: &lt;quantization is surprising>
* JB: I think that we should consider whether people will hate wgsl because it’s hard, or because it’s slow.
* DN: too large float to int is undef behaviour in C++ and poison in llvm. This is probably a programming error in general.
* JB: is this improperly rounded? Shouldn’t a gpu give a well rounded result
* MM/DN: not in the apis.
* KG: Seems it’s something folks might be concerned about being too slow.  But it’s UB.
* MM: Motivated by the need to avoid UB, so already taking a performance hit.  Output a value that’s meaningful.
* KG: Caveat is that for some platforms it might be something other than UB, and we might be different.
* BC: Current spec rule does not result in UB.  It says clamp to largest quantized value of source type that fits in target type
* **_Resolved: take the new rule._**

</details>
