### ISSUE TITLE
Shader extensions are redundant

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#3961]
The [spec says](https://gpuweb.github.io/gpuweb/wgsl/#enable-extension):

> An enable-extension is an [extension](https://gpuweb.github.io/gpuweb/wgsl/#extension) whose functionality is available only if:
> - The implementation supports it, and
> - The shader explicitly requests it via an [enable directive](https://gpuweb.github.io/gpuweb/wgsl/#enable-directive), and
> - The corresponding WebGPU [GPUFeatureName](https://gpuweb.github.io/gpuweb/#gpufeaturename) was one of the required features requested when creating the [GPUDevice](https://gpuweb.github.io/gpuweb/#gpudevice).

Right now, WGSL only has a single [extension](https://gpuweb.github.io/gpuweb/wgsl/#enable-extensions-sec): [`shader-f16`](https://gpuweb.github.io/gpuweb/wgsl/#extension-f16).

WebGPU has an accompanying [feature](https://gpuweb.github.io/gpuweb/#feature-index): [`shader-f16`](https://gpuweb.github.io/gpuweb/#shader-f16).

Because of the 3 bullet points above, if we extrapolate to a future where there are a variety of shader extensions, we can assume that each and every one of them will be duplicated this way.

This is redundant; it means the WebGPU developer has to enable the same feature/extension, with the same name, twice: once at device creation time, and once in the shader module. The author already has to jump through a lot of hoops when setting up their devices and shaders; requiring this information duplicated seems unnecessarily arduous.

It's probably impossible to remove the need to enable the feature at device creation time, because Vulkan requires that. However, it is completely possible to remove the need for the shader to enable the extension itself. So, this is a proposal to remove the `enable_directive` production entirely from WGSL, in favor of features specified in the API at device creation time.

FP16 doesn't have any inherent cost _just_ from enabling it; but if a future feature/extension is created which _does_ have inherent cost just from enabling it, such an extension can be explicitly enabled at the shader module level, or even at the entry point level, via API additions, if necessary. (This isn't necessary for FP16.)

**Comment by JonahPlusPlus** [comment]
I don't often work with WGPU directly, but I do write shaders for Bevy.

I would prefer features to be enabled through the shader, since it makes the files more portable (for example, if I copy a file off the internet and don't have access to the WGPU code, how do I know what extensions it's using? what if there are extensions that look similar but have different behavior?). When you enable features at device creation, you are enabling them because of the shaders you are using. In that sense, shader authoring comes before device creation, making the latter the redundancy, but exceptions exist (shader authoring that comes after device creation, like a shader editor or downloaded file), making it necessary. I think the best solution would be to leave both and instead use some preprocessor (like in a game engine or framework) to help automate picking features.

An alternative is to split shader creation into two steps before and after device creation, but that would be a waste of disk IO and memory compared to preprocessing and prevents loading shaders that don't exist before device creation but that you know will work with already enabled features, like ones downloaded from the internet during runtime.

If I got anything wrong, please correct me. Like I said, I don't work often with WGPU directly, so I might have made some assumptions with how things work.

**Comment by dneto0** [comment]
Thanks @JonahPlusPlus for the good feedback.

In brief:

* Some features are invisible. 
     * Example: an algorithm might critically depend on IEEE-like support for infinities, NaNs, subnormals, and signed zeros.  This is may be impossible to tell by reading the source code.
* Agreeing with and reinforcing what @JonahPlusPlus said:  It's extremely common for shaders to be written in one place and time, and used in another.  An in-band label is very useful for capturing intent.  Shader authoring is often a wholly separate role (done by different people), and the label serves as part of the contract between shader author and the developer deploying it in an application.

To the degree there is redundancy, it's low cost and high value.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-04-04-minutes#shader-extensions-are-redundant--issue-3961">WGSL 2023-04-04 Minutes</a></summary>

* KG: Feedback from Mozilla is we think it’s fine to do it in both places. There are advantages to having it in both places.  One advantage, as noted already, is it’s an in-band assertion within the shader that is readily readable. Think that’s a benefit.  Technically it is redundant, but it’s ok to be overconstrained.  You can imagine a case where the shader would have it, but didn’t enable it at device-creation, and it’s ok for the browser to complain.
* KG: One of the things you do at device-creation, and another is at shader-creation.  Many apps are single-focused and know the bounds of what they will require.  But middleware that might need the feature later, will have to ask for the feature up front. But if we got rid of this redundancy it would be implicitly enabled in all the shaders, but might have a cost.
* MM: Thought I addressed the issue. Example is f16, and there is no cost to turn it on. Yes, there are hypothetical features in the future that have a cost when turned on.  But the signal for that doesn’t have to be in the shading language.  For those cases, it’s ok to remove that extra information into the pipeline creation call rather than in the shader source.  And in that case it’s not redundant info.  Our goal is to eliminate true redundancy.
* JB: Would you be amenable to changing the title to “shader-f16” is redundant.
* MM: “shader-f16” is too narrow.  Looking for general rule for cases where the feature is truly redundant.  Having that true redundancy is setting themselves up for failure.
* KG: Think OpenGL does things poorly in this space. Think we did better in WebGL.
* MM:I’m with you for things that have cost.
* KG: Kind of asking for a lint.  The lint is “am I using shader-f16 when I haven’t enabled it at device creation”.
* MM: If you haven’t enabled it at device creation, you can’t do anything about it in the shader. 
* KG: If you haven’t declared it at device creation, then we have to reject the shader.
* KG: If you have declared it, … (?)
* MM: If it doesn’t cost, then why not always enable it?
* KG: User enjoys that the browser has these built-in lints. What we’re weighing is should we be slightly less redundant in a way that doesn’t matter much?  Or users can lint with what we already have in the browser.  Two relatively minimally beneficial things. Don’t think the goal of “being less redundant” overrides the other thing.
* JB: I’m understanding Myles’ argument better. We can treat ‘enable shader-f16’ to lint uses of f16.  We decide to lint for specific reasons. We specifically lint things that have some kind of problem attached to them.  Perf cost, programming risks.  Myles’ argument is ‘f16’ is not interesting. He’s saying in this particular case, f16 isn’t different from all the other language features we have.  I see that….
* KG: This is a portability lint.   Folks write code with “if it works on my machine i assume it works on others”.
* JB: But device creation fails….
* KG: You often test on your powerful machine, and seldom on your low capability thing.  When you write this one new shader, you accidentally use this portable-hazard feature.  Today you include or not include in the shader. If you develop this app, your expectation is it will be portable.
* JB: You can get that same testing device without asking for f16.  
* KG:If you realize that you have that portability hazard.
* KG: WebGL got really far by forcing you to always say these things.  And being pedantic.  The benefit is that it almost always worked on low spec devices. Slight redundancy gives us benefits.
* AB: Overall, agree with KG.  There are benefits to being in the shader, and not necessarily cost at all.  The small cost is smaller than the benefits.  You get a cleaner split between API and compiler. Get better offline tooling.  Benefit to separation between asset creation time and deployment.
* MM: The user story Kelsey gave about which programs work on which device. Think redundancy actually works against that. If you have two sources of truth then the author will be confused.   Second is philosophical. That separation between shading language and API, is ideally reduced not enlarged.  People using WGSL are going to be using WebGPU. They would already declare which features are to be used.
* KG: Assert it doesn’t cause confusion.
* JB: Also interested in high quality offline tooling.
* JB: You say enable shader-f16 has benefits.  If you have free reign. Alan, if there are other places you’d add.  Kelsey is making a case in favour of them. What other things would we be flagging this way.
* AB: Already thought we reached consensus.  Things that are not prevalent on all hardware. Think that’s reasonable.  If you’re expecting some feature that’s not everywhere, then do so. May expect some of them to become superfluous. We know other features are coming soon that are not universal.
* DN: Want to repeat the point by JonahPlusPlus: shaders are developed separately from the app itself. Separation in time, space, skillset and who is doing the authoring.  The enable forms one half of the handshake with the app deployment.  Make the contract clear and smooth.
* KG: There are other places we’ve ceded the declaration. But don’t want to cede this one down to zero.  Benefits outweigh the cost of the redundancy, therefore don’t want to eliminate it.
* JB: Would like to talk more about the handshake.
* AB: Hope I understood Myles’ point.  Anybody who uses WGSL will use WebGPU.  Have partners that don’t start with WGSL. IT’s better to capture signals earlier in their flow.
* MM: If you’re on a device that doesn’t support f16, or you’re on such a device but haven’t enabled it.  Then if you use an f16 shader then that compilation will fail.  Now take the shader and add f16; it will still fail. Adding it didn’t benefit.  Take the converse.  Enabled it on the device, but then the shader will or will not run depending on if it is otherwise correct. (assuming we relax this rule).
* KG: This is like defense in depth against accidental portability leaks. Additionally I see it as a benefit to be listed somewhere affirmatively in the shader.  It’s a benefit not a disadvantage.
* MM: What’s the difference between this and a version? Don’t see this as different.
* KG: I see it as different.
* AB: I would reiterate Kelsey’s argument is where we reached previous discussion “because we have A, doesn’t mean B follows”. If we wanted the most portable thing is “v1”. After much discussion we decided not to do that. Lots of arguments on whether to be a version. Decided one way.
* KG: Can draw similarities.  But analogies are imperfect. The difference lies in there.
* DN: For versioning, if I have a machine/browser that doesn’t run the app, then my solution is to wait for a software upgrade to support that language-version thing.  But if I can’t run it due to hardware shortcoming, there is no solution to me on that machine. I can wait forever and it still won’t be portable to that machine.
* KG: Would like to close the communication gap.


</details>

**Comment by litherum** [comment]
Looking over the minutes, I think I see a few arguments being made. Please feel free to correct this list if I've forgotten anything:

1. Authors _want_ to be redundant

> it’s an in-band assertion within the shader that is readily readable. ... User enjoys that the browser has these built-in lints.

I'm assuming this argument is indicating that people want to know which features they're using in their shaders. They can do this even without the `enable_directive` - these are listed in the device creation parameters that are prefixed with `shader_`.

The difference is that these are specified in WebGPU rather than inside the shader itself - so it seems like this is a disagreement about what "in-band" means. If the "band" is considered to be wide enough to include the API, then the information is in-band.

I was confused about the discussion of lints, specifically, because lints are things that are typically executed outside any compiler, and generally do not lead to compilation errors.

2. Portability

> You often test on your powerful machine, and seldom on your low capability thing. When you write this one new shader, you accidentally use this portable-hazard feature. Today you include or not include in the shader. If you develop this app, your expectation is it will be portable. ... This is like defense in depth against accidental portability leaks.

I didn't understand this argument. Here's a table showing the behavior of what is in the spec today, compared to what is being proposed:

| Enabled on the device  | Enabled in the shader | Feature actually used in the shader | Works according to the spec today | Works according to this proposal | Notes
| -- | -- | -- | -- | -- | -- |
| ❌ | ❌ | ❌ | ✅ | ✅ | &nbsp; |
| ❌ | ❌ | ✅ | ❌ | ❌ | &nbsp; |
| ❌ | ✅ | ❌ | ❌ | ✅ | We'd consider this a progression - they didn't enable the feature at startup time, and didn't actually use it - so we can just run their shader no problem |
| ❌ | ✅ | ✅ | ❌ | ❌ | &nbsp; |
| ✅ | ❌ | ❌ | ✅ | ✅ | They asked for something they didn't use, which is fine |
| ✅ | ❌ | ✅ | ❌ | ✅ | This is the inverse of the ❌ ✅ ❌ row - the author enabled the feature in one place, but forgot to enable it in the other, but we can still run their program |
| ✅ | ✅ | ❌ | ✅ | ✅ | They asked for something they didn't use, which is fine |
| ✅ | ✅ | ✅ | ✅ | ✅ | &nbsp; |

As you can see, there are only 2 rows with different behaviors with this proposal, and both of those rows are places where they got the `enable_directive` wrong; i.e. they didn't do their bookkeeping correctly.

So, I didn't understand the portability argument. Those 2 rows in the table with different behaviors don't seem to affect portability.

3. Division of labor

> shaders are developed separately from the app itself. Separation in time, space, skillset and who is doing the authoring.

I'm assuming this is an argument about the big shader houses, which have multiple teams working on their 3D engine.

We believe that this is true _sometimes_. The tradeoff is to make _everyone_ do extra bookkeeping, so that these big shader houses have a slightly easier time keeping track of the context of their shaders.

But shaders already exist within a pretty large context which needs to be kept track of anyway - in order to use a shader, you need to know its vertex attributes, bind group layout, render targets, overridable constants, etc. So if the big shader houses are already going to be keeping context for each shader, I don't see a material benefit to putting _this_ piece of information inside the shader itself rather than in the accompanying context object.

4. Invisible features

> Some features are invisible.

This is a good point! I think we should cross that bridge when we get to it. FP16 is definitely not invisible. FP16 is the one feature at hand, so that's the one we're focused on.

### Additional context

The case that I'm really interested in is:
1. Someone learning WebGPU copies some FP16 code off of Stack Overflow into their own program, and tries to run it
2. The computer tells them that FP16 isn't enabled
3. They go and enable it, and try again
4. The computer tells them they didn't enable FP16 hard enough
6. They go find some other, totally separate place to enable FP16 _again_
7. Now their program works

### Compromise

I think there is room for compromise here, though. We could hook into the `diagnostic` infrastructure. We could say that, if FP16 is used without it being enabled, it generates a diagnostic, and the author can promote that to an error or not. The default would be a warning, not an error. Surely the big shader houses would be willing to have their style guide say they must always promote these diagnostics to become errors. That way, the new users can just use FP16 more easily, whereas the big shader houses can be more explicit.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-04-11-minutes#shader-extensions-are-redundant--issue-3961">WGSL 2023-04-11 Minutes</a></summary>

* MM: I wrote a really long post where I tried to go throught the arguments and give context, and suggest a path to compromise - but that was just before the meeting. This probably doesn’t have to be done for V1, since it only makes more programs valid. So we could say, let’s take a week to read the issue and then talk about it next week.
* KG: I’d like a chance to read it offline
* **Tabled for next week**

</details>

**Comment by dneto0** [comment]
Thanks for writing up your thoughts in detail, @litherum 

To me the feature request at the API level is not "in band".    The enable in the shader is "in band".

We have two extremes of communities:
* big development houses with distinct people doing API design vs. shader authoring.  This is the "big shader houses" case.
* small developer with less intrinsic expertise.  This person goes to Stack Overflow to see how to do something, copy-and-paste into their small app and try it.  Let's call this "stack-overflow-learner".

It's the second case, stack-overflow-learner, that motivates my desire for "in band" signalling being the *shader*.

If you squint, the fundamental point is there is a loss of context between authoring vs. use of the shader.  It's just that they have different supporting stories.  Both stories are valid. For me both of them lead to a desire for in-shader signalling.

You listed 1. Authors want to be redundant, 2. Portability, 3. Division of labor, 4. Invisible features.

The "3. Portability" is focused on functional portability: does it run vs. not.
But I think there's additional nuance, so I'll call it out as:

5. Committee wants authors to be consciously aware of non-portability (before they get very far).

My position is: The W3C WebGPU group wants shader authors to be deliberately / consciously aware of introducing non-portability into their application. I *want* a speedbump to exist when using a non-portable feature.

This is perfectly in line with existing philosophy of having uniformity analysis rejecting shaders.  You have to say something more to disable uniformity diagnostics in fragment shaders. That is an acceptable price.

Let me write a slightly alternate user story:

1.  Someone learning WebGPU copies some FP16 code off of Stack Overflow into their own program, and tries to run it
2. The computer tells them that FP16 isn't enabled
3. They think.  "oops, I meant my app to be fully portable." Back to Stack Overflow.

It's *better* if there's a step somewhere in 1. 
  1.1   They see Stack Overflow sample code with "enable f16" and they say "oops,  I want full portability" and go looking for code that will work everywhere instead.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-04-18-minutes#shader-extensions-are-redundant--issue-3961">WGSL 2023-04-18 Minutes</a></summary>

* MM: **David replied just before the meeting so need time to review**. Think it’s slightly different argument from Kelsey’s, so still **would like to see Kelsey’s writeup**.


</details>

**Comment by litherum** [comment]
## Portability argument

I think you've described quite well why I don't understand the portability argument.

> Committee wants authors to be consciously aware of non-portability (before they get very far).

The author already has to opt-in to non-portability. That opt-in is just at device creation time.

> The W3C WebGPU group wants shader authors to be deliberately / consciously aware of introducing non-portability into their application. I want a speedbump to exist when using a non-portable feature.

They are; there is a speed bump. The speed bump is having to opt-in to the non-portable feature _at all_.

> You have to say something more to disable uniformity diagnostics in fragment shaders.

Right. You have to say something at device creation time.

> 1. Someone learning WebGPU copies some FP16 code off of Stack Overflow into their own program, and tries to run it
> 2. The computer tells them that FP16 isn't enabled
> 3. They think. "oops, I meant my app to be fully portable." Back to Stack Overflow.

This story is exactly the same regardless of whether the opt-in is just at device creation time, or whether it's both at device creation time and at the top of the shader. In both of those stories, the computer tells them that FP16 isn't enabled, and they can choose to go back to Stack Overflow at that point.

## "loss of context between authoring vs. use of the shader"

As we understand it, this is really the crux of the disagreement. If the person writing the shader has the context of how the device is (will be) created, they can write their shader accordingly. If they're not, then they can't.

For the new learner, they wrote all their sources at roughly the same time, so they will have all the context. Hence the redundancy described in the OP.

For the larger shader houses, we understand that the people writing the shaders are often not the same people who write the device creation code.

However, many of the large shader houses either write in HLSL (which doesn't have this required redundancy), or compile to HLSL. Therefore, we're skeptical that this redundancy would actually be helping these houses. If we heard directly from one of these houses that they would get concrete benefit, or if we hard from Microsoft saying that they have requests from devs in the field to add this kind of redundancy, that would be sufficient justification for this redundancy.

But, even if the redundancy would be useful for these large shader houses, that doesn't mean it has to be required for the new authors, too. So, if this kind of evidence arises, we would still aim for a solution where the large shader houses can opt-in to required redundancy, but the new author doesn't need to do anything.

There are a couple different ways this could be accomplished:
- Only validate if the author specifies more than zero `enable_directive`s; otherwise, don't validate
- Use the diagnostic infrastructure, so the large shader houses can promote missing `enable_directive`s to errors
- (Maybe others?)

**Comment by greggman** [comment]
> This story is exactly the same regardless of whether the opt-in is just at device creation time, or whether it's both at device creation time and at the top of the shader. In both of those stories, the computer tells them that FP16 isn't enabled, and they can choose to go back to Stack Overflow at that point.

This story doesn't seem the same. One is tedious. The other is simple.

With the metadata, you just glance at the required extensions and if they don't fit your needs to move to the next shader. 

Without the metadata you end up having to read through the code or try integrating it into your project. That's like buying a mix at the supermarket and having it not tell you what ingredients you need to make it on the outside of the package. You get home only to find you have to drive back to the store.

I don't know where I really fall on this topic.

On the one hand I see the value in having the metadata.

On the other hand, I don't think I've seen too much C++, C#, Swift, JavaScript, or Typescript marked with versions or similar metadata.

That doesn't mean some of those wouldn't be better off with more metadata. For JavaScript there are polyfills and transpilers from new to old but that won't happen for WGSL features. A great many JavaScript libraries are using the npm packaging system so version requirements and other dependences are listed there. I've also personally run into the issue on C# when unity was stuck on V2.1 and the rest of the world was on V4 or V5 and I needed to track down solutions that ran on V2.1 so the metadata would have been helpful.

**Comment by litherum** [comment]
> With the metadata, you just glance at the required extensions

Stack Overflow answers aren't usually fully-formed programs, with all the `#include`s, etc. They are usually a function or two, or maybe even just part of a function. So discovering that a code snippet from Stack Overflow uses a particular extension will still usually involve copying at least some of it into your own shader.

**Comment by magcius** [comment]
Another way to think of this divide is about dependencies, and global vs. local. After a codebase grows for a little while, you will end up with a list of enabled extensions at device setup time.

If you are extremely lucky, there is a comment or some documentation describing why each one is enabled, e.g. `"shader_f16", // Volumetric fog uses f16.`

If you are not, you end up with a giant list of extensions with no clear understanding of where each one is used, and that makes the list tend to just grow over time out of fear of breaking something. With each shader *locally* describing exactly the extensions it needs, it's a lot easier to understand the usage of each.

I think everyone agrees namespaces and modules are a good idea, and that extra granularity is never a bad thing. Let's keep that going. I think the benefits of the tiny bit of plumbing far outweigh the costs.

**Comment by mwyrzykowski** [comment]
@magcius is this really a valid argument to have it in the WGSL source however?

Any offline WGSL compiler could trivially provide the extensions required to compile a certain WGSL shader. It is unnecessarily verbose to include it in the WGSL source.

Per @litherum's [earlier points](https://github.com/gpuweb/gpuweb/issues/3961#issuecomment-1503846817) there already exists an audience where the extra redundancy is cumbersome or at the very least, adds an extra, unnecessary step towards getting something working.

For larger projects / larger teams, any number of tools could easily provide the information regarding extensions used. Needing to manually inspect the shaders to see which shader uses which extension is less efficient than having tooling provide this information and unnecessary verbose.

**Comment by magcius** [comment]
Personally, I don't think it's "unnecessarily verbose" to include it in the WGSL source, any more than I think an import statement in a line of source code is "unnecessarily verbose". I think it's about declaring what you use.

An analogy: to use a third-party package in my JavaScript app, I need to both add a dependency to package.json declaring I want to install the feature, but I also need to add an import to use the feature in my code. Is this extra redundancy? Yeah. Is it cumbersome? A bit. Do the benefits outweigh the downsides? From many years of experience in environments where this wasn't always the case, I would argue that they do.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-05-30-minutes#shader-extensions-are-redundant--issue-3961">WGSL 2023-05-30 Minutes</a></summary>

* KG: Recommend folks check how much you care about this issue.
* MM: **Want Mike on the call to discuss this when done in detail**.

</details>

**Comment by litherum** [comment]
In almost every case of prior art, there is no required enable directive. People have been writing non-portable code since the beginning of time. If I call `queryPerformanceCounter()` or `mmap()` in CPU code, I don't need to annotate in the source code which OS the file is meant for. As far as I'm aware, GLSL is the _only_ popular human-written language, in the whole world, which requires you to describe the nature of any non-portabilities which exist within the source code itself.

The closest comparison to fp16 on the web would probably be BigInt, which you don't need to `enable` before you use it - you just use it. You can feature detect its presence, just like you can (in fact, must!) feature detect the presence of fp16.

**Comment by magcius** [comment]
> As far as I'm aware, GLSL is the only popular human-written language, in the whole world, which requires you to describe the nature of any non-portabilities which exist within the source code itself.

* Perl has the [`use feature` directive](https://perldoc.perl.org/feature) to selectively enable new language features.
* Rust has the [`#[feature()]` directive](https://doc.rust-lang.org/unstable-book/index.html) to selectively enable unstable or experimental compiler features.
* Python has the [`from __future__ import XYZ` directive](https://docs.python.org/3/library/__future__.html) to selectively enable proposed experimental language features.
* Swift has the [`#if hasFeature()` directive](https://github.com/apple/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md#feature-detection-in-source-code) to test for the support of language features.
* C/C++ has the preprocessor to process source text based on external declarations. [autoconf](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/C-Compiler.html), [CMake](https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html), and [meson](https://mesonbuild.com/Compiler-properties.html) all support configuring preprocessor variables based on feature detected support of the compiler, and there is always the standardized [__cplusplus](https://en.cppreference.com/w/cpp/preprocessor/replace#Predefined_macros) version macro if you wish to feature detect based on expected environment.
* It's also common to use the linker for this purpose. One can link `platformMac.cpp` which uses `mmap()` on Mac platforms, and link `platformWin32.cpp` which uses `MapViewOfFile()` on Win32 platforms, exposing a standardized API using the same header file for both.
* I am leaving many, many others off of this list.

You can argue that some of these are not necessarily *required* feature declarations, but WGSL has no equivalent to *any* of the above features. It has no preprocessor, it has no linker, it has no explicit "use feature" pragma, and it has no way of doing feature detection from within the language. Any of these solutions would be acceptable, but none is rather constraining.

It's worth noting that WGSL is kind-of a special case compared to other environments. Many of the above (and also HLSL and MSL) do not have shader extensions, they have language versions. In DXC, [you specify which language version you require at compile-time](https://github.com/microsoft/DirectXShaderCompiler/wiki/HLSL-2021) with the `-HV` flag. This is distinct from WGSL's "extensions" functionality, where currently, the exposed language functionality changes based on runtime device configuration. The same is true for GLSL as well, and explicit extension (and shader language version!) declaration was chosen there too. I am not aware of any other languages besides WGSL and GLSL where this is the case.

> The closest comparison to fp16 on the web would probably be BigInt, which you don't need to enable before you use it - you just use it. You can feature detect its presence, just like you can (in fact, must!) feature detect the presence of fp16.

I am not arguing against selective feature detection. I am arguing against the enablement of a device extension ambiently changing the syntax or semantics of WGSL, especially in ways that are undetectable from within WGSL itself. Explicitly declaring which features are required for the code to compile correctly is only the simplest form of this.

**Comment by kdashg** [comment]
It's redundant but it has value.

A core engine module will have some set of features S1 that it requests. (possibly "all features")
Other modules within or on top of the engine might have some subset (of S1) of features S2 that they require.
Shaders-vs-API is a common boundary between modules.
There must be agreements between e.g. API bind groups and shader input declarations.
The intent of explicitly enabling a feature is to implicitly (or explicitly) opt out of using a feature.
Implementations must support this kind of per-feature linting anyway, in case a device without the API feature is requested.

For runtime-generated content, engines must pre-emptively enable all features that they might need.
Consider ShaderToy authoring, where code is written live, and would implicitly inherit activation of all features, even if an author would find value (particularly for portability) in ensuring they don't use more than they expect.
As shader files grow, it ceases to be easy for the reader to tell what's required, and easier to accidentally use constructs that you're trying to forbid yourself.
We have a design today that prevents this, and makes requirements for shaders explicit, even when requirements for devices are more unbounded.

It's common-practice for languages to list (some degree of) dependencies at the top of files. (e.g. #include, requires, import)
These lists provide value, even though the compiler can tell that e.g. you need to `#include <vector>` if you declare a `std::vector<>`.
This kind of redundancy has value for readability because it makes explicit and concise what is expected to be used.

Consider a hypothetical compute shader a_star_nof16, which serves as the fallback for when a faster a_star_f16 isn't usable.
Portability testing could include testing explicitly without shader-f16 at Device creation.
This would require full-stack testing, whereas the proposed/existing alternative could be done less intrusively and with less overhead/combinatorics.

To me, designing for portability is pretty mission-critical for WebGPU, as it was for WebGL.
Accidentally relying on extensions/features is a huge portability hazard.
Making explicit what requirements are helps prevent this, even if it's redundent.
Many apps will *need* to ask for all device features to be enabled or risk needing to recreate the device.
Having this second point of listing of requirements helps those kinds of apps a lot.

**Comment by dneto0** [comment]
A small point re:

>  If I call queryPerformanceCounter() or mmap() in CPU code, I don't need to annotate in the source code which OS the file is meant for.

For mmap, you have to do something like `#include <sys/mman.h>`, earlier in the source file.

**Comment by litherum** [comment]
A few responses:

1.
> Perl has ... Rust has ... Python has ...

This is a false equivalency to WGSL. In WGSL, `require foo;` doesn't textually include any headers, import any modules, look in the filesystem for source code, etc, which is what those other languages do. In WGSL, all the `require` directive does is _give the author permission to use something that already exists_.

2. In the call today, we discussed the use-case of a developer editing shaders inside a larger graphics engine. However, a large engine probably has _their own_ concept of portability. E.g. it's pretty common for a large engine to just say "I always require feature X; if the device doesn't support feature X, I just won't run at all." Should the developer have to write `require featureX;` at the top of literally every shader?

It's more likely that these large engines have their own set of optional features, totally different than the WebGPU/WGSL set of optional features - likely at a higher level of granularity, like "tier1" "tier2" etc. where "tierN" corresponds to a particular set of WebGPU/WGSL optional features (and potentially other differences too, like which codepaths are expected to be fast). In this situation, it doesn't make sense for the larger shop to be forced to keep track of their own optional feature system _and_ WGSL's optional feature system for the same source.

3. We found the example of Unity having `#pragma require foo` as compelling evidence that there is an audience which could benefit from these annotations. In the spirit of compromise, we would be comfortable with a global opt-in to enforcement of these annotations. Considering the "in-engine shader editor" use case, the opt-in mechanism could even be at the API level (possibly a new field in `GPUShaderModuleDescriptor`) so that the in-engine shader editor can't flip the switch themselves, and must follow the policy which is set at a higher level. If the higher-level switch is flipped to say "`require`s are enforced" then the shader author would be forced to write them.

**Comment by magcius** [comment]
> This is a false equivalency to WGSL. In WGSL, require foo; doesn't textually include any headers, import any modules, look in the filesystem for source code, etc, which is what those other languages do.

David mentioned Perl above, but I'll also say that the same is true for Python. It reads like an import statement, but [it's special-cased by the compiler](https://github.com/python/cpython/blob/main/Python/future.c). Rust's `#[future()]` directive does not and has never included any code to my knowledge, and neither has Swift's `#if hasFeature()` directive. The comment does apply to C/C++, but that's an ecosystem where new language features are often supplied as additional header files to include, so it's comparable here.

**Comment by dj2** [comment]
We've been discussing an idea similar to point 3 in https://github.com/gpuweb/gpuweb/issues/3961#issuecomment-1589951328. We don't have concensus, so this isn't our position, but wanted to list it here so others could comment.

The current behaviour stays as default. If you do nothing, then `enable` is required to be listed in the shader as it is now. We add a new GPU device feature, `enable_wgsl_corresponding_features`. If that feature is requested on the device, then for any feature that has been requested during device creation the shader compiler will pretend the corresponding `enable` was provided.

For example, if you have device features of `fp16,enable_wgsl_corresponding_features` then the shader would pretend `enable f16` was present. It would not pretend `enable ray_tracing` was provided and would error on any usage of that extension.

This means, if you want the current behaviour, it's the default, and we enforce it. The shader offline tooling would work as the shaders are required to list their enables. If you want the device to control it, then adding `enable_wgsl_corresponding_features` makes any requested device feature enabled at the shader level as well. You're still protected from using extensions which were not requested at device creation (or you have to `enable` those features in the shader).

This, I think, is similar to `diagnostics` in that the default behaviour is protection, but you can request to loosen the protections.

**Comment by litherum** [comment]
Regarding `enable_wgsl_corresponding_features`: We would be willing to pursue this as a compromise solution.

One question about it, though: In this proposal, why did you propose `enable_wgsl_corresponding_features` part of the device feature set, rather than the shading language `@enable` feature set? (I'm asking this question to gain background knowledge; I'm _not_ expressing an opinion.)

**Comment by dj2** [comment]
It seemed to make sense at the time? Device creation is the place where you're turning on the things `enable_wgsl_corresponding_features` is referring too. This keeps things more self contained. I'd have no issue with it being some kind of `enable` in the shader (but, again, my idea doesn't have internal concensus, so we'd have to see if folks internally were more receptive to the idea of it being an enable in the shader)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐01‐09-Minutes#shader-extensions-are-redundant--issue-3961-">WGSL 2024-01-09 Minutes</a></summary>

* (let’s just check in on this)
* KG: Still think not necessary. 
* JB: Find the redundancy valuable.
* DS: Google did not have consensus on the enable_corresponding_wgsl_features.
* KG: Call to action: **think about it again**.

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐01‐23-Minutes#shader-extensions-are-redundant--issue-3961-m0">WGSL 2024-01-23 Minutes</a></summary>

* DN: Google’s stance is the redundancy is fine, and do not want a change in the spec.

</details>

**Comment by mwyrzykowski** [comment]
After some discussion we are ok resolving this as no change needed. Shall we close this issue?

**Comment by dneto0** [comment]
> After some discussion we are ok resolving this as no change needed. Shall we close this issue?

Yes. I recommend closing this.  I'll defer to @kdashg here, as chair.

**Comment by kdashg** [comment]
Thanks all!

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐02‐20-Minutes#shader-extensions-are-redundant--issue-3961-m0">WGSL 2024-02-20 Minutes</a></summary>

* **CLOSED**

</details>
