### ISSUE TITLE
`requestAdapterInfo()` should be required to prompt (in at least some circumstances)

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#3962]
```
interface GPUAdapter {
    ...
    Promise<GPUAdapterInfo> requestAdapterInfo(optional sequence<DOMString> unmaskHints = []);
};

interface GPUAdapterInfo {
    readonly attribute DOMString vendor;
    readonly attribute DOMString architecture;
    readonly attribute DOMString device;
    readonly attribute DOMString description;
};
```

The information in GPUAdapterInfo is significantly privacy-invasive. There are (at least) 2 reasons why:
1. GPUs are quite varied across the world; there is a lot of diversity/entropy in them
2. GPU information can be correlated with GPU price, to actually learn about the user's socioeconomic situation, in addition to simply fingerprinting them.

Right now, the spec permits a conformant information to implement `requestAdapterInfo()` by never prompting, and to give away all this privacy-invasive information to anyone who asks for it, regardless of first-party or third-party or anything else. If authors develop using such a browser, they could easily be led astray by the expectation that this information is freely available, when it won't be in all browsers.

It might be a valid use case for a AAA renderer to request this information to trigger different codepaths for different hardware inside their engine. However, as evidenced by the fact that use of AAA WebGL is fairly rare compared to the number uses of WebGL in total across the web, we expect that AAA WebGPU will be fairly rare compared to all the uses of WebGPU in total across the web. Most WebGPU content across the web likely won't need this information. Indeed; if the authors of most WebGPU content feel they need this information, that means that us implementors have collectively done a terrible job at implementation.

Also, for AAA situations, the user already knows what they are getting themselves into, and wants to enable the AAA experience - they'll be willing to click through a prompt to do so.

So, there's a natural split: most uses won't need this information, and for the uses for which the authors think they need it, those uses are ones that a prompt should be readily accepted by a user.

There are, of course, some situations where it doesn't make sense for `requestAdapterInfo()` to show a prompt. For example, if the user is logged in to Facebook and they want to play a Facebook game, there's no point prompting in that situation. We're not proposing that `requestAdapterInfo()` _always_ prompt; we're proposing that there is always _some_ situation where a prompt will occur, and that this prompt will be common enough for web authors to recognize that this privacy-sensitive data isn't freely available (in any browser).

The goal here isn't to _solve_ fingerprinting; the goal is to add one more fingerprinting mitigation to carry us further on the path toward making fingerprinting less and less practical, across the whole web.

**Comment by Kangz** [comment]
We discussed this option extensively in meetings about `requestAdapterInfo` and friends and decided to let UAs to what they think is best. Why do we re-open this discussion? Our position hasn't changed and we still believe that it should be up to the UA to choose since the information that a UA returns can be made to be extremely correlated with other source of fingerprinting like canvas hashes and feature/limit buckets.

**Comment by Kangz** [comment]
A reminder of what the spec says:

> None of the members in [GPUAdapterInfo](https://gpuweb.github.io/gpuweb/#gpuadapterinfo) are guaranteed to be populated. It is at the user agent’s discretion which values to reveal, and it is likely that on some devices none of the values will be populated. As such, applications must be able to handle any possible [GPUAdapterInfo](https://gpuweb.github.io/gpuweb/#gpuadapterinfo) values, including the absence of those values.

This is true even if the application request more information. So what is provided is completely left at the UA's discretion.

**Comment by Kangz** [comment]
While this is a recurring and understandable concern, prior experience, for example with WebGL2 adoption, shows that developers care about their page running correctly on multiple browsers. This conversation should also be part of the larger privacy discussions that are happening in other standardization forums. I don't know exactly which one off-hand, but it seems that this discussion shouldn't be resolved only in the WebGPU group. 

Also Chromium happens to throw an exception if any `unmaskHints` are provided because we need to discuss with our privacy team what our policy should be and didn't get to do it before v1.

**Comment by annevk** [comment]
While you are correct that there is a larger concern, I don't think that means you can dismiss the concern. Each API designer is responsible for the fingerprinting footprint they add to the web. I recommend reading https://w3ctag.github.io/design-principles/#leave-the-web-better in particular, but there's a number of other principles there that are applicable here as well.

I encourage you to have that discussion with your privacy team. Perhaps that allows us to make progress here.

**Comment by kdashg** [comment]
On this topic, please be 20% nicer than usual. This is contentious, but we are here to work together to address concerns. :)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/Minutes-2023-04-19#requestadapterinfo-should-be-required-to-prompt-in-at-least-some-circumstances-3962">GPU Web 2023-04-19 Atlantic</a></summary>

* MM: Found this when thinking about what we should prompt for. This group discussed this issue last week?
* BJ: Mike suggested we revisit it this week to have MM's opinion. But after discussion, Apple's opinion that API as it exists is probably OK, given that we're taking out the hints. Accurate?
* MM: accurate. Were worried that if we didn't have resolution now, that no browser'd ever be able to prompt. But CHrome's throwing an exception from this API today if hints are passed anyway. Nobody likes prompts. Focusing mostly on promptless mitigations. If we really do need to prompt, bad if that option's taken away.
* BJ: clarification. Right now, you can call requestAdapterInfo in Chrome, and get info back. But if you try to pass unmasking hints, that's when you throw the exception. And we'll be taking that codepath out, to avoid setting developer expectations / behaviors. Chrome wants to remove unmaskHints entirely - don't have time to implement it properly at this time, and look at reintroducing down the line.
* MM: flexibility is the reason we opened this issue. Want to have the same flexibility you do.
* MM: is the expectation - if someone calls requestAdapterInfo and don't provide unmaskHints, are you going to give back an object with no strings inside?
* BJ: our intent - unmaskHints won't be an option. Want to remove them from the spec. If you call this API, it will give back an object and it will be populated with what the browser's comfortable returning. It can be nothing.
* MM: and not commenting on what you plan to return?
* CW: we can describe what's planned to ship. Right now - returns non-empty strings for vendor and architecture.
* BJ: yes. There are other fields we leave there empty, unless you've set a developer flag in about:flags. Including up to driver version, which isn't in the spec, just for developers, don't intend to expose to the web at large.
* KG: dream of how this works in Firefox - we'd never prompt for this API, ignore / remove unmaskHints from spec, return you sanitized description of device. In future, to add more info, if valuable - don't think it's strictly needed - we'd come back to this group and propose a new entry point that would prompt. So, reserve the ability to add something that's expected to prompt by adding a new API entry point.
* BJ: seems reasonable and in line with what Chromium wants. Returning sanitized data's perfectly fine. General flexibility of revisiting this later - in line with what Chromium wants to do, too.
* CW: hearing:
    * Remove unmaskHints
    * No prompting
    * Revisit later if need be
* BJ: agreement between Google/Moz. Slight mismatch between what MM thought Chrome was doing and what we are doing - addressed / OK?
* MM: don't think we should resolve today to remove unmaskHints. Not sure that was an option. Privacy team told us it's important for websites to ask for what they want. Like to defer that at least a week.
* MM: clarification about Chrome's shipping behavior - concerning because people will be calling this API and it will never prompt. Since you're only returning vendor/arch - that's helpful enough to avoid the privacy problems that I think that's OK. 
* KG: personally don't want to implement vendor/arch, but have sanitized device. Lets me tune buckets more easily. Arch maybe too narrow, but sometimes too broad for what I want to tell you. That's why I tell you my aspiration. Always give you sanitized thing with no prompt. Vendor's easy, Arch not so much.
* BJ: data's not necessarily tiered. Viable to say, I'll fill in vendor/device. Maybe not your actual device, but something representing the device class. Skip arch entirely.
* MM: "AMD RTX 4090"
* BJ: yes. You could also plug in the architecture since the card has one associated. But you're not compelled to fill in the arch.
* KG: doesn't feel that way.
* BJ: not the intent of the spec.
* KN: dev expectation is that it'd be there. Chromium won't even fill in the device field.
* CW: though there's expectation of the formatting of the architecture, there's no specification of it.
* KG: in practice we really don't want to do that. Arguably, dev should know the range of things. Strings are fine to start. Agreed I don't have to impl full arch lookup thing, so no concerns there. Vendor's trivial.
* BJ: hope there wasn't an impression given that when you call this API that the unmaskHints would be required at any point. Haven't been considering that.
* MM: if someone calls this API and doesn't pass an input, they're asking for all the info they could get?
* BJ: they're asking for all the info they can get without a prompt. And spec text says, if you give unmaskHints, you may be subject to a prompt.
* KG: opinion - when you call this API in Firefox - we'll give you back 1 of 32 or fewer options. Paraphrasing - that's the one piece of info you're asking for when you call this API. Satisfying the requirement for getting back what you need. But you can't ask for just the vendor and get back one of 8 options.
* CW: in Chromium we'd like to consider giving less info to pages we trust less, too. (Third-party iframe for example.)
* BJ: supporting what Kelsey said - Chromium still falls under the 32-bucket limit.
* MM: nitpick - goal of bucketing was for all APIs together.
* KG: if that's not true in our browser - please file a bug.
* BJ: though this API might return various combinations, and limits another set of combinations - the union will still fall under that limit.
* KN: note, this is an interface. Handing back data - we haven't done that until they've accessed the attribute. Still an opportunity to see what info they use. In terms of privacy/tracking, there's more nuance there, and the chance to make late-binding decision of what you return for each attribute.

</details>

**Comment by mwyrzykowski** [comment]
With requestAdapterInfo becoming sync ( https://github.com/gpuweb/gpuweb/issues/4536 ) and given the flexibility in regards to what GPUAdapterInfo reports, shall we close this?

The privacy concern does not exist any longer, we can choose to report 'Apple' and 'apple' for all of our platforms while satisfying the specification.

**Comment by kainino0x** [comment]
I agree this is obsolete/resolved now, since now there is no possibility of a prompt there's no possibility of different browsers prompting in different circumstances.

For the record of this issue - I've written this on some other issue already - _if_ we ever add the possibility of prompting for adapter info, it will probably be before requestAdapter(). And my opinion is that if we do that, the API should look like "promptForDetailedAdapterInfo()", i.e. the API is requesting a prompt, not requesting a list of what info it wants and letting the browser decide whether to prompt, because letting the browser decide puts stricter browsers at a disadvantage.
