### ISSUE TITLE
Triangle Strips + PrimitiveRestart

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#397]
Each of the targeted API's: Metal, Vulkan and Direct3D 12 support rendering triangle strips with primitive restart. There are a number of worthwhile situations, especially when coupled with compute, that triangle strips with PrimitiveRestart is much nicer (and efficient) than just triangles. For simplicity, the restart index should be all bits up (rather than being settable).

I advocate to add such a feature as either an extension or core.

**Comment by magcius** [comment]
There's an argument to be made that Primitive Restart is a performance hazard, because it means that the dispatch unit that reads from the stream can't just split up the stream to be processed in parallel; instead it requires a serial parse of the index stream. IHVs have raised concerns about this before.

**Comment by kvark** [comment]
IIRC, when we discussed primitive restart last time (in https://github.com/gpuweb/gpuweb/pull/29#discussion_r134866347), we found out the mismatch between the backends: https://github.com/gpuweb/gpuweb/blob/c4fc14daf47d5d61faa3abf20faa61080426e80e/design/Pipelines.md#render-pipeline-creation

I think we settled on enabling it unconditionally (following Metal restriction), hence we require the user to specify the index buffer type at the pipeline creation (so that we know the restart value).

**Comment by krogovin** [comment]
I am all for this approach, and I am a little embarrassed that I missed in the .idl that triangle strips were already listed as there.

**Comment by kainino0x** [comment]
Yup, we're already supporting this. I think this can be closed.
