### ISSUE TITLE
No abstract type overloads for zero value builtins

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#4019]
I don't know if this is deliberate, but the spec has no overloads for abstract types for the zero value built-in functions like vec2(), nor for the multi-argument value constructor builtins like vec2(1,2).

I would assume that `vec2()` would be equivalent to `vec2(0,0)`. It looks to me like the feasible automatic conversion rules allow us to simply say that `vec2(e1, e2): vec2<S>` when `e1: S` and `e2: S`. If the two arguments are different abstract types, then they'll be coerced.

If there's some reason the multi-argument constructors don't make sense on abstract operands, it might be nice to explain this at the top of the section.

**Comment by alan-baker** [comment]
```
@const @must_use fn vec2<T>(e1 : T, e2 : T) -> vec2<T>
@const @must_use fn vec2(e1 : T, e2 : T) -> vec2<T>
```
Where `T` is a scalar type. Scalar includes abstracts. So `vec2(1,2)` would yield an abstract int vec2.

I don't think we allow `vec2()` at all, only the fully typed versions (e.g. `vec2<f32>()` or `vec2f()`) so abstracts can't be written there.

**Comment by jimblandy** [comment]
Okay - I was carrying the restraints on `T` from the upper bunch of `vec2` overloads down to the second batch, and thus assuming it had to be a "concrete scalar".

I guess this becomes an editorial suggestion: let's use consistent type metavariables for concrete vs. potentially-abstract types. Like, `T` for "concrete foo" and `S` for "(potentially abstract) foo".

**Comment by jimblandy** [comment]
> I don't think we allow `vec2()` at all

Right - that's the other question I'm raising here: should we allow it? It seems clear what it ought to mean.

**Comment by alan-baker** [comment]
Is it an AbstractInt or AbstractFloat vector? There's no context to help. I guess AbstractInt would make more sense since you can't down convert from AbstractFloat.

**Comment by litherum** [comment]
`vec2()` sounds like a good idea (if we can get the abstract types story ironed out).

`mat4x4()` is less clear: should it be filled with 0s, or should it be the identity matrix? IIRC existing shading languages fill with 0s which I always thought was weird. Maybe we should have `identityMatrix4x4()` or something?

**Comment by jimblandy** [comment]
I agree that for matrices, "zeroed" is probably not the value we should work on making easier to produce.

Let's leave matrices to a different issue.

**Comment by dneto0** [comment]
Agreed to in the 2023-04-11 meaning that vec2() means vec2(0,0) which makes it a vector of AbstractInt

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-04-11-minutes#no-abstract-type-overloads-for-zero-value-builtins--issue-4019">WGSL 2023-04-11 Minutes</a></summary>

* JB: We don’t say what vec2() is.  Seems it should be the same as vec2(0,0), etc.  Not clear what it should be for matrices, since zero matrix is not particularly useful.
* BC: It doesn’t exist.  Semi-intentionally. HIstory is we started type constructors with explicit type. We added aliases, and sugar forms. Added the infer-the-type form from the arguments.  In this case, there are no expressions to infer the type from. It’s fair as a _new_ feature request.
* JB: We have abstract-typed vectors.
* AB: You have to spell the zero.  You have to name something.
* KG: The feature is vec2() is the same as vec2(0,0).
* BC: Want to make clear it’s not a mistake; the ‘inferred type’ constructors are short-hand when you have the argument expressions.
* JB: I want the abstractness to propagate further.
* MM: Want to touch on matrices.
* KG: Zero matrices are not useful on their one, but it’s useful to be the starting point to make a useful matrix from it.
* AB: It would be wrong to make the matrix non-zero, for consistency sake.  Would need a different name for the constructor.
* BC: Have a way to make implicit zeroes. If you want an identity, make an identity.
* MM: Need _some_ way to make identity matrix.
* KG: Suggest add identity builtins. …
* AB: Got stuck before: which identity matrix you want; we don’t do templated functions. So naming the type is fiddly.  Had dropped from v1.
* MM: Shall I open a new issue for matrices? (square matrices)
* KG: Affine translation matrices make sense.
* **_Consensus to add vec2() mean vec2(0,0), and also vec3() vec4()_**
* **_File new issue for matrix spin offs._**

</details>
