### ISSUE TITLE
Handling of omitted labels is unclear

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#4083]
The algorithm "create a new WebGPU object" says:

> 6. Set `object.label` to `descriptor.label`.

However, `descriptor.label` is an optional member of the `GPUObjectDescriptorBase` dictionary type, whereas the `label` attribute of `GPUObjectBase` is declared:

```
attribute USVString label;
```

which doesn't admit `null` as a value.

When the `label` is omitted from the descriptor, it's not clear what we want to have happen:

- If `USVString` is the type we want, then I guess it'd have to be set to the empty string.

- But maybe we want `USVString?`, and an omitted `label` dictionary member results in a `null` label.

**Comment by kainino0x** [comment]
I thought the intent was that the default label would be the empty string. But I'm surprised this slipped through the cracks.
I would propose we change the descriptor label to default to empty string instead of being optional, so there's no ambiguity and only one type. IMO there's no need to distinguish "no label" from "labelled with empty string".

BTW in chrome currently, objects created without a label are labeled with the empty string.

**Comment by takahirox** [comment]
+1 for empty string. If it is an optional (`undefined` is allowed), clients might need additional work to handle label on some platforms for example first checking whether it is defined and then accessing it, like

```
if (obj.label !== undefined) {
  obl.label.stringSpecifiCuntion(...);
}
```

**Comment by kainino0x** [comment]
(Looks like we simply forgot about it when I did the PR #3405)

**Comment by kainino0x** [comment]
Resolved: Explicitly default label to empty string
