### ISSUE TITLE
No way to destroy a shader?

### ISSUE THREAD

**Issue by mrakh** [gpuweb/gpuweb#4116]
I see that it's possible to create shaders with [`GPUDevice.createShaderModule()`](https://www.w3.org/TR/webgpu/#dom-gpudevice-createshadermodule), but I can't find any corresponding function to destroy a shader module that is no longer needed. Is this an oversight in the spec, or is there a reason that no such method exists? This seems like it could easily cause memory leaks in any application that constructs shaders dynamically and/or based on user input.

**Comment by litherum** [comment]
JavaScript is garbage-collected, so it will get destroyed eventually.

Is there a reason you’d like it destroyed earlier?

**Comment by greggman** [comment]
Tracking objects with this [this lib](https://gist.github.com/greggman/1d70c66fedc6e60a934cf6d822366149) I see them get destroyed automatically

Example: https://jsgist.org/?src=a095068816bf6d08e5a4ef3ce416b1cb

Note that when garbage-collection happens is undefined and is up to the browser.

**Comment by mrakh** [comment]
> JavaScript is garbage-collected, so it will get destroyed eventually.

Ah, I had assumed that GPUShaderModule would follow the pattern of GPUTexture, GPUBuffer etc. in having a dedicated destroy function.

> Is there a reason you’d like it destroyed earlier?

Control over VRAM pressure, mainly. I want to create and destroy lots of shader modules with wildly varying lifetimes (think a multiplayer game where player avatars are rendered with user-submitted shaders). A destroy function that forces (or at least strongly hints) GPU resources to be cleaned up immediately would better allow for building latency sensitive VRAM management on top, rather than relying on the browser engine's garbage collector, which might be optimized differently.

**Comment by greggman** [comment]
I think the assumption is that shaders don't take much vram, if any, compared to buffers and textures (both of which can be manually destroyed)

**Comment by litherum** [comment]
Right - that's the reason that textures and buffers have destroy functions. They use so much vram that an application totally might want to free up some of that memory eagerly, rather than waiting for GC.

I'm not aware that shaders usually use that much vram, when compared to resources (textures, buffers).

Also, a WebGPU implementation is totally free to move the binary shader blobs on and off the GPU at its leisure (just as long as any shaders that a particular command buffer uses are on the GPU by the time that command buffer executes).

In your application, can you instrument it to determine how much vram your shaders use? If it is significant, then that would be the strongest argument in favor of this API addition proposal.

**Comment by kainino0x** [comment]
No plan to do this at the moment, but could be reopened.
