### ISSUE TITLE
Should navigator.gpu not be readonly?

### ISSUE THREAD

**Issue by juj** [gpuweb/gpuweb#4150]
I wanted to delete the `navigator.gpu` object from a JS scope to make a dual WebGPU+WebGL 2 aware page fall back to use WebGL instead of WebGPU.

I notice that in Firefox and Chrome, `delete navigator.gpu;` does not work, because `navigator.gpu` is read-only. (it just keeps the object around)

However, if one does `navigator.gpu = {};`, then in Firefox, this does override the object with a new empty object, but in Chrome the statement does nothing, and WebGPU capability remains. (which one is buggy?)

Even though the object is `readonly`, one can do

```js
Object.defineProperty(navigator, "gpu", {});
delete navigator.gpu;
```
to remove support for WebGPU on a page, which works in both Firefox and Chrome. Though that seems unnecessarily complex?

Should the IDL just remove the `readonly` field to enable pages to disable WebGPU in a straightforward manner? Iiuc that would work by changing the current IDL from

```idl
interface mixin NavigatorGPU {
    [SameObject, SecureContext] readonly attribute GPU gpu;
};
```
to
```
interface mixin NavigatorGPU {
    [SameObject, SecureContext] attribute GPU gpu;
};
```

**Comment by kainino0x** [comment]
`gpu` is a key on the *prototype* of `Navigator`, as I believe it should be because that's what `interface` means in WebIDL:

- `navigator.hasOwnProperty('gpu')` returns false
- `delete navigator.gpu` does nothing
- `Navigator.prototype.hasOwnProperty('gpu')` returns true
- `delete Navigator.prototype.gpu` works

`readonly`: means the property is not writable: https://webidl.spec.whatwg.org/#dfn-read-only
The behavior in Firefox is that setting `navigator.gpu` shadows `Navigator.prototype.gpu`. From reading the WebIDL spec, this seems incorrect: that behavior is supposed to happen only if the property is [`[Replaceable]`](https://webidl.spec.whatwg.org/#Replaceable).

cc @jimblandy

**Comment by juj** [comment]
Ah of course, that totally makes sense. `delete Navigator.prototype.gpu` works well.

Reported https://bugzilla.mozilla.org/show_bug.cgi?id=1837835 for the Firefox side behavior.
