### ISSUE TITLE
Position: Directly ingest a human-writable shading language

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#42]
WebGPU should directly ingest this (https://github.com/gpuweb/gpuweb/issues/41) human-writable shading language. This is for a few reasons:

- **Easing Developers’ Burdens**: Because almost all shaders are already written in this language, these preexisting shaders can be supplied directly into WebGPU without the need for an additional compilation step.
- **View-Source**: We’ve gotten a significant amount of feedback from the WebAssembly effort that developers wish they had some way of viewing the source that a webpage was written in (and not the source that was supplied to the browser). We’ve heard this from both authors of webpages as well as users who wish they can inspect a webpage’s source. Because one language will be blessed as the preferred WebGPU language, developer tools would attempt to reverse-compile any ingested language to the blessed language, at which point the tools for the language are already in the browse and should thus be made directly available to the web.
- **Dynamism**: Many 3D web applications dynamically create or modify existing shaders at runtime. This kind of workflow would require a webpage to ship a compiler, which is big enough that downloading a compiler from each page load would be slow and potentially costly on metered connections. We have not seen any history of webpages modifying a non-human-writable source program at runtime.
- **Interoperability**: A human-authored shading language can be as interoperable as a non-human-authored shading language. There were times in the early days of Java where its (non-human-authored) byte code was not fully specified and behavior divergences occurred for well-formed programs in compliant runtimes. GLSL in WebGL is a perfect example of this a well-specified human-authored shading language. Secure HLSL improves upon GLSL by fully specifying every construct in the language, thereby eliminating the ambiguities that GLSL had. Secure HLSL includes a comprehensive test suite that the WebGPU Community Group is currently creating.
- **Size**: A compiler for Secure HLSL does not necessarily need to be large. A compiler for a very similar language, WSL, is 22,000 lines of JavaScript (as opposed to LLVM’s 2.5 million lines of C++). Browser binary sizes do not necessarily need to increase dramatically to handle Secure HLSL.
- **Security**: The WebGPU Community Group is proving that Secure HLSL is secure using a static proof solver. In addition, Secure HLSL compilers will be submitted to extensive security testing and fuzzing before ever being exposed to the Web.
- **Specificity**: The WebGPU Community Group is currently writing a specification for Secure HLSL. This will result in a fully-defined specification, including security model and API bindings.
- **Performance**: All modern browsers optimize all source code that passes through them, such as Javascript and WebAssembly. Web authors also routinely perform offline optimizations on their (human-authorable) Javascript sources before serving it to the browser. In addition, all shader source ends up going through the graphics driver where it may be further optimized. The WebGPU Community Group is gathering metrics showing that human-authorable shaders optimize to a form as fast or faster than an optimized form of non-human-authorable shaders.
- **Versatility**: Just as TypeScript and Dart compile to Javascript, other human-authorable shading languages can be compiled to Secure HLSL.

**Comment by grovesNL** [comment]
> Easing Developers’ Burdens: Because almost all shaders are already written in this language, these preexisting shaders can be supplied directly into WebGPU without the need for an additional compilation step.

This doesn't appear to be a strong argument because most modern web projects use compilation steps already (i.e. Webpack, Browserify, Rollup, TypeScript, Elm, Dart, SASS, LESS, JSX).

> View-Source: <snip> Because one language will be blessed as the preferred WebGPU language, developer tools would attempt to reverse-compile any ingested language to the blessed language, at which point the tools for the language are already in the browse and should thus be made directly available to the web.

Browsers should not attempt to decompile shaders. Source maps already exist for this purpose and the website can choose whether to distribute source maps and the corresponding source code.

> Dynamism: Many 3D web applications dynamically create or modify existing shaders at runtime. <snip> We have not seen any history of webpages modifying a non-human-writable source program at runtime.

Websites have never had the ability to modify non-human-readable shaders at runtime. It seems unlikely that those applications (which concatenate shader text today) would not benefit from being able to manipulate lower-level shader code instead.

> Security: The WebGPU Community Group is proving that Secure HLSL is secure using a static proof solver. In addition, Secure HLSL compilers will be submitted to extensive security testing and fuzzing before ever being exposed to the Web.

> Specificity: The WebGPU Community Group is currently writing a specification for Secure HLSL. This will result in a fully-defined specification, including security model and API bindings.

Both of these could apply to non-human-readable languages as well, so this doesn't seem like an argument in favor of either approach.

> Performance: All modern browsers optimize all source code that passes through them, such as Javascript and WebAssembly. Web authors also routinely perform offline optimizations on their (human-authorable) Javascript sources before serving it to the browser. In addition, all shader source ends up going through the graphics driver where it may be further optimized.

If a web author prefers to take advantage of offline compilation, why should it be disallowed by the API? Many web authors would prefer to statically compile and optimize if it meant the runtime performance improvements (i.e. Prepack). JIT compilation appears to contradict the goal of moving to low level graphics APIs.

> Versatility: Just as TypeScript and Dart compile to Javascript, other human-authorable shading languages can be compiled to Secure HLSL.

Languages compile to JavaScript because it was necessary prior to WebAssembly. It is much easier to compile to a language (i.e. handling control flow) that was designed to act as a compile target (Secure HLSL was not).

**Comment by Kangz** [comment]
until the explainer for Secure HLSL is published, let's assume here that the high-level language will be HLSL and hope that most of the discussion will translate easily to Secure HLSL.

**Comment by Kangz** [comment]
Agreed with most of @grovesNL's points.

> > Dynamism: Many 3D web applications dynamically create or modify existing shaders at runtime. We have not seen any history of webpages modifying a non-human-writable source program at runtime.
>
> Websites have never had the ability to modify non-human-readable shaders at runtime. It seems unlikely that those applications (which concatenate shader text today) would not benefit from being able to manipulate lower-level shader code instead.

This is true for a large class of applications but some of them might not get away from text (ShaderToy, "custom shader nodes" in some engines) and others would like to keep their text shaders at least for a while when porting to WebGPU. For these a WASM-ed shader compiler that is already precompiled in a browser cache should work well and like @litherum mentioned it needn't be a large download (our toy shaderc.wasm is 0.5MB).

> **View-Source**: We’ve gotten a significant amount of feedback from the WebAssembly effort that developers wish they had some way of viewing the source that a webpage was written in (and not the source that was supplied to the browser).

This is not the experience of our WASM team and I would like to have more details on this given that source maps exist, SPIR-V has debug info, and that all of the Web is "uglified" in production.

> The WebGPU Community Group is gathering metrics showing that human-authorable shaders optimize to a form as fast or faster than an optimized form of non-human-authorable shaders.

"Members of the WebGPU CG" are. I'm looking forward to your analysis on this, but suspect that there is no inherent optimization you can do when going from HLSL to ISA directly and not from HLSL to SPIR-V.

> **Interoperability**: A human-authored shading language can be as interoperable as a non-human-authored shading language. There were times in the early days of Java where its (non-human-authored) byte code was not fully specified and behavior divergences occurred for well-formed programs in compliant runtimes. GLSL in WebGL is a perfect example of this a well-specified human-authored shading language. Secure HLSL improves upon GLSL by fully specifying every construct in the language, thereby eliminating the ambiguities that GLSL had. Secure HLSL includes a comprehensive test suite that the WebGPU Community Group is currently creating.

That "Members of ..." are creating. Being one of the main reviewers on the ANGLE shader compiler code, I have first-hand experience that GLSL is NOT an example of a well-specified language by any means. And Khronos group members spent a lot of time trying to tighten it.

Another point we've made in the meeting is that there's very few languages that have multiple interoperable implementations: C/C++, Javascript and maybe a subset of Python. IMHO it's crazy to think we can do as good a job as them to specify a language. Even Java is specified in term of its bytecode format!

**Comment by devshgraphicsprogramming** [comment]
> If a web author prefers to take advantage of offline compilation, why should it be disallowed by the API? Many web authors would prefer to statically compile and optimize if it meant the runtime performance improvements (i.e. Prepack). JIT compilation appears to contradict the goal of moving to low level graphics APIs.

I could not agree more.

> That "Members of ..." are creating. Being one of the main reviewers on the ANGLE shader compiler code, I have first-hand experience that GLSL is NOT an example of a well-specified language by any means. And Khronos group members spent a lot of time trying to tighten it.

Honestly doubt you can beat SPIR-V with a better and tighter specification for your own shading language.


I'm sure that a HLSL/GLSL/Metal/Cg to IR compiler could be included as part of the webGPU tool-kit even as a webAssembly implementation (or maybe even an webAssembly implementation of shaderc+SPIRV-Cross), so nothing would stop ShaderToy and the likes from supporting text-shaders.

Can I just ask will Secure HLSL have a formal memory model? Just like Vulkan and SPIR-V have?

Because to me it makes absolutely no sense why you would not want to extend the SPIR-V spec and adopt it as the ingested shader langauge given that:
1. It has a **formal memory model** with **memory semantics** which you can rely on the final ISA driver compiler respecting and not reordering your reads/writes if your backend is Vulkan
2. The memory model also specifies **cache visibility** which is even more than what the C++11 memory model does.
3. It is an Intermediate Representation (hence fast to parse, build ASTs, validate, manipulate etc.)
4. The compiler should have had already performed all the optimizations it could without folding the specialization constants
5. It is an open and extensible specification where you can address the security concerns with your own extension.

Just look at the example #35, if you have no memory model and memory semantics there is nothing to stop your driver compiler from reordering your reads or respect reading to temporary invocation/thread-local variables, *including the reads that fetch the variables that you check your bounds with*.

**Comment by litherum** [comment]
It’s unfortunate that web developers need to run their programs through an explicit optimization pass before handing it to the browser. Shaders should get good performance by default.

One of the things we’re trying to measure is how much optimizations are done inside Vulkan drivers. If drivers run the SPIR-V through LLVM optimization phases before it hits the hardware, that affects how we generate SPIR-V in the WHLSL compiler.

**Comment by Kangz** [comment]
> It would be unfortunate if web developers needed to run their programs through an explicit optimization pass before handing it to the browser. Shaders should get good performance by default.

It's safe to assume that browsers would be running optimization passes on SPIR-V before handing it to the driver. That's why @kvark was asking for the list of passes applications typically perform before passing SPIR-V to the driver.

**Comment by grovesNL** [comment]
> If drivers run the SPIR-V through LLVM optimization phases before it hits the hardware, that affects how we generate SPIR-V in the WHLSL compiler.

If WHLSL is the ingestion format, then WHLSL should aim to output reasonably optimized SPIR-V, and we will likely still have to perform optimization passes on the SPIR-V produced anyway (because it can be optimized at a lower level -- WHLSL and SPIR-V operations don't match 1:1). We shouldn't rely on all Vulkan drivers to perform these optimizations for us, since normally the expectation is that the SPIR-V should be optimized before making it to the driver.

This is a big reason I'd prefer SPIR-V to be the ingestion format. Previously Apple mentioned WHLSL could be optimized enough that later SPIR-V optimizations wouldn't be necessary, but I'm not confident that's the case. I'd also prefer for avoid WebGPU having to take on the burden of developing a full toolchain around WHLSL (writing optimization passes, etc.) because a lot of this already exists in the SPIR-V ecosystem.

**Comment by kvark** [comment]
To clarify my colorful emoji, I agree with @grovesNL reasoning. If the browser would need to optimize SPIR-V unconditionally then that would be a missed opportunity for us *not to* do this on every application run on every shader.

**Comment by devshgraphicsprogramming** [comment]
> It's safe to assume that browsers would be running optimization passes on SPIR-V before handing it to the driver. That's why @kvark was asking for the list of passes applications typically perform before passing SPIR-V to the driver.

Applications never do and never did (sauf Unity as a workaround for crappy mobile drivers) shader optimizations before feeding the driver, this is because the compiler did what it pleased anyway since the ingested format was text before the next-gen APIs.

There is and always has been reliance on the vendor drivers to do the optimizations, because with an IR its unwise to do the following:
- Register Coloring (don't know how many registers a GPU has before we see the GPU)
- Loop Unrolling (no heuristics on how program size affects speed)
- Hardcore GPU optimizations such as using wave-intrinsics for increasing the performance of atomic oprations, loading UBO data and reading/writing identical values from/to identical addresses in all warps (I've actually found out that Nvidia's GLSL compiler does that, although it misses some opportunities: https://github.com/buildaworldnet/IrrlichtBAW/wiki/Think-You're-Reducing-Atomic-SSBO-Op-Contention%3F-Think-Again ) 
You're kind of limited to what webASM can do.

However I would like to defend ARM, Arduino and PowerVR, the reason why these optimizations were not performed and Aras P. had to make a GLSL optimizer is because the CPUs on these devices are very weak and the same level of optimization as you'd expect from an NVIDIA driver would take seconds per shader as well as eat a lot of power from the battery.

Battery drainage and mobile loading times are exactly the reason why you should not encourage developers to feed the browser's webGPU API shaders that have not gone through offline optimization when releasing in production.

The main thing to note here is that shader optimization that is outside the bounds of what spirv optimizer does, should be the domain of the Vendor Driver. 
Again, for reference: https://github.com/buildaworldnet/IrrlichtBAW/wiki/Think-You're-Reducing-Atomic-SSBO-Op-Contention%3F-Think-Again
You would need to be on top of every vendor specific extension as it hits the shelf, because if you actually modify SPIR-V to do some non-AST, GPU specific optimizations they will actually bite you when the next generation of GPUs hits the shelves.
Its like vectorizing C++ code by hand with intrinsics, if you did it in SSE3 now you lose against the default compiler implementation that can emit AVX, AVX2 or even AVX-512.

**Comment by devshgraphicsprogramming** [comment]
> We shouldn't rely on all Vulkan drivers to perform these optimizations for us, since normally the expectation is that the SPIR-V should be optimized before making it to the driver.

The drivers always did it for GLSL and HLSL, and they did it very well coming up with insane solutions:
https://github.com/buildaworldnet/IrrlichtBAW/wiki/Think-You're-Reducing-Atomic-SSBO-Op-Contention%3F-Think-Again

The reason is that the GPU market is very competetive, so even if a company cannot outdo their competitor with raw silicon performance and specs they will do their best with optimizing drivers.
In-fact NVIDIA goes as far as replace the shaders shipped with major games both to fix bugs and provide custom NVIDIA-specific performance boosts (yes, I'm not a fan of that, but it works).

The only outlier were some of the mobile drivers that didn't even optimize variable re-use, storage operations, dead-code elimination and constant folding.

**Comment by othermaciej** [comment]
> @devshgraphicsprogramming to be fair, the memory model can be adopted for WHSL, and the discussions are ongoing in the mailing lists.
> 
> > Honestly, I doubt you can beat SPIR-V with a better and tighter specification for your own shading language.
> 
> This point has been brought up in various forms, but at the end of the day it's clear that Apple disagrees, and we can only make this judgement when we see the specification.

SPIR-V does not have a tight specification compared to other modern languages. It's certainly not the worst spec ever, and it's better than GLSL. But it doesn't have the level of precision of, for example, WebAssembly or JavaScript. Most of the spec is informal and it uses a lot of language that is ambiguous. Actually tight specifications use structured formalisms to define the behavior of the language. I don't think this is a weird or uniquely-Apple view, nor something that needs to be proven by creating new specs.

**Comment by devshgraphicsprogramming** [comment]
> SPIR-V does not have a tight specification compared to other modern languages. It's certainly not the worst spec ever, and it's better than GLSL. But it doesn't have the level of precision of, for example, WebAssembly or JavaScript. Most of the spec is informal and it uses a lot of language that is ambiguous. Actually tight specifications use structured formalisms to define the behavior of the language. I don't think this is a weird or uniquely-Apple view, nor something that needs to be proven by creating new specs.

My original point about SPIR-V being tight was in comparison to other shading languages of the past, especially the memory model which is ever so important given that GPUs do not have unified cache hierarchies.

Although the Metal spec looks tight as well.

And yes sure, C++, Java, JavaScript and WebAssembly have much tighter and disambiguated specifications.

**Comment by Ninja-Koala** [comment]
Not sure if this is the right place, but why does WHLSL have pointers?
AFAIK the only shading language with pointers is the Metal Shading Language, so this seems like a serious divergence from HLSL.

**Comment by othermaciej** [comment]
WHSL has pointers. They are restricted to guarantee safety, with an additional set of restrictions that even makes the semantics easily compilable to SPIR-V (which is probably what we'd want to enforce for V1 of the language, until/unless the  pointer variable Vulkan extension becomes commonly deployed).

**Comment by grovesNL** [comment]
Is there a document or thread somewhere which contains justification for divergences or extensions to the language beyond HLSL (like pointers)?

**Comment by kainino0x** [comment]
I find it confusing to refer to them as pointers, because the term usually refers to byte-address pointers. I think of them as safe opaque references.

**Comment by Ninja-Koala** [comment]
I'm less concerned about semantics, as the pointers in WHLSL are indeed quite restricted. I'm more concerned about compatibility. I think it would be nice if not only most HLSL shaders work in WHLSL but also most WHLSL work or can be easily converted to HLSL. I fear pointers will make this very difficult.
