### ISSUE TITLE
How to add default offsets to setVertexBuffers?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#421]
We started this conversation on #414.

kainino0x:
> This is a little less trivial for setVertexBuffers. E.g. should we allow offsets to be smaller than buffers, and any past the end are treated as 0? Then the default could be []. Or should buffers.length === offsets.length, in which case it would probably make more sense to have two overloads, one with offsets and one without

> Another alternative for setVertexBuffers is
> ```
> setVertexBuffers(u32 startSlot, sequence<GPUBuffer or GPUBufferWithOffset> buffers);
> dictionary GPUBufferWithOffset { required GPUBuffer buffer; required u64 offset; }
> ```
> 
> but this results in annoying-to-type/read code like `[{ buffer: b0, offset: o0 }, { buffer: b1, offset: o1 }]`.
> 
> Both this and the current alternative leave something to be desired when it comes to having minimum bindings overhead in the hot path.

> Yet another is
> 
> ```
> setVertexBuffer(u32 slot, GPUBuffer buffer, u64 offset = 0);
> ```
> 
> I actually think this one is not so bad ergonomically (even though you have to call setVertexBuffer a lot, at least the result code is easy to read). It results in a lot of function calls, though. fwiw, apps also can't cache the two array objects for reuse between frames.

austinEng:
> We could also have both so we can support both patterns:
>  - Preparing the arrays of arguments in advance and then encoding them
>  - Encoding on the fly without array allocations

kvark:
> I'm in favor of individual `setVertexBuffer` calls. When suggested earlier, the approach was dismissed because of the JS encoding overhead. Now that we have `GPURenderBundle`, this becomes less of an issue.

**Comment by austinEng** [comment]
> Bigger problem though is that it's not clear how to implement this efficiently

Very good point. Related: previously @kvark said
> I'm in favor of individual setVertexBuffer calls. When suggested earlier, the approach was dismissed because of the JS encoding overhead. Now that we have GPURenderBundle, this becomes less of an issue.

This also has a similar issue (though less bad) where it's unclear how to implement efficiently. It isn't as bad as rebinding `VkDescriptorSet` with different offsets, but it could result in more native API calls than necessary. If there were individual `setVertexBuffer` calls:
 - Would you simply call `vkCmdBindVertexBuffers` once for each?
 - Or defer a batched `vkCmdBindVertexBuffers` until draw time?

---

> In Vulkan, the dynamic offsets are u32 anyway, so we can just use `Uint32Array` in JS.

Right, I remember running into this recently. We should at least change this to 
```webidl
void setBindGroup(
  unsigned long index,
  GPUBindGroup bindGroup,
  optional (Uint32Array or sequence<unsigned long>) dynamicOffsets);
```

**Comment by jdashg** [comment]
> Furthermore, I'd like to argue that multiple function calls is cheaper than an array of dynamic offsets. 
@kenrussell, didn't the multidraw investigations generally find the opposite of this, even in Webkit?

**Comment by austinEng** [comment]
@jdashg, I mentioned this above. The difference here is that MultiDraw used typed arrays. Right now the offsets are 64-bit so we can't use Uint32Array. However, @kvark pointed out that these should indeed be 32-bit because of Vulkan.

**Comment by kvark** [comment]
I suppose part of the reason why I find individual `setVertexBuffer` calls most appealing is because I'm not expecting binding many vertex buffers to be a hotspot in the profile. Interleaving vertex data is something people do today, splitting only for cases where different rendering techniques are used (i.e. only bind the positions buffer when drawing into the shadow map). So my expectation is that we'll mostly be seeing 1-3 vertex buffers being bound, and the more are bound the higher chance that the user is also changing the pipeline, bind groups, etc. So I'm not seeing an attempt to provide `setVertexBuffers` having much return on API investment.

I wonder if we can get some statistics on how people are using vertex buffers, to inform our decision.

**Comment by austinEng** [comment]
@litherum I implemented `setVertexBuffer` (singular) in Webkit ([diff](https://gist.github.com/austinEng/f73c9bed7cd253844e3c3471aa1ee4fb)) and ran the following microbenchmark:

```javascript
(async () => {

function time(trials, fn) {
  const start = performance.now();
  for (let i = 0; i < trials; ++i) {
    fn();
  }
  console.log(performance.now() - start);
}

const trials = 100000;

const adapter = await navigator.gpu.requestAdapter();
const device = await adapter.requestDevice();

const buffer = device.createBuffer({ size: 4, usage: GPUBufferUsage.VERTEX | GPUBufferUsage.INDEX });

const commandEncoder = device.createCommandEncoder({});
const pass = commandEncoder.beginRenderPass({ colorAttachments: [] });

// Create this here to avoid allocations and garbage later.
const offsets = [0, 256, 512, 768];
const buffers = [buffer, buffer, buffer, buffer];

console.log('setVertexBuffer 4 times');
time(trials, () => {
  pass.setVertexBuffer(0, buffers[0], offsets[0]);
  pass.setVertexBuffer(1, buffers[1], offsets[1]);
  pass.setVertexBuffer(2, buffers[2], offsets[2]);
  pass.setVertexBuffer(3, buffers[3], offsets[3]);
});

console.log('setVertexBuffers plural');
time(trials, () => {
  pass.setVertexBuffers(0, buffers, offsets);
});

})();
```

100,000 trials of multiple calls to `setVertexBuffer` (singular) took 14 ms
100,000 trials of a batched call to `setVertexBuffers` (plural) took 148 ms

I'm not an expert with the Webkit WebGPU code, so it's very possible I made a mistake.

However, if the test is correct, then multiple calls to `setVertexBuffer` are *ten times faster* than a batched `setVertexBuffers` in Webkit.

I would imagine this is because of the same Javascript bindings issue in Chrome and probably Firefox as well. Allocating and populating `const Vector<RefPtr<WebGPUBuffer>>&, const Vector<uint64_t>& offsets` is much more expensive than extracting arguments one-by-one within JavaScript and passing them on the stack, especially after the JS engine inlines the code.
