### ISSUE TITLE
Only one pipeline layout for each entry point can be given as compilation hint

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#4233]
From https://github.com/gpuweb/gpuweb/issues/4222

> Consider a case when single fragment shader is used with multiple different pipelines, each having different vertex shader with different bindings, thus having multiple different pipeline layouts. Problem is that only one pipeline layout for each entry point can be given as compilation hint.

Right now, the hint can only hold exactly one pipeline layout. It would be useful if a sequence of pipeline layouts could be supplied instead.

This would change this:
```
dictionary GPUShaderModuleCompilationHint {
    (GPUPipelineLayout or GPUAutoLayoutMode) layout;
};
```

to

```
dictionary GPUShaderModuleCompilationHint {
    (GPUPipelineLayout or sequence<GPUPipelineLayout> or GPUAutoLayoutMode) layout;
};
```

**Comment by kainino0x** [comment]
Marking as a candidate for polish-post-v1 because this is a hint-only API and it's okay to implement trivially (by ignoring the input)

**Comment by kainino0x** [comment]
Is this sufficient? The parent bug described a situation where you use:
- vertex entrypoint 1 + fragment entrypoint 1 + pipeline layout 1
- vertex entrypoint 2 + fragment entrypoint 1 + pipeline layout 1

Do we need to know the vertex-fragment pairs or is it sufficient for the hints to be broken up:
- vertex entrypoint 1 + pipeline layout 1
- vertex entrypoint 2 + pipeline layout 2
- fragment entrypoint 1 + pipeline layout 1
- fragment entrypoint 1 + pipeline layout 2 <- the only thing here we can't describe currently

**Comment by litherum** [comment]
We don’t need to know the pairs; early compilation is independent for each entry point.

**Comment by kainino0x** [comment]
> (GPUPipelineLayout or sequence<GPUPipelineLayout> or GPUAutoLayoutMode) layout;

The sequence may also need to accept GPUAutoLayout

`(GPUPipelineLayout or GPUAutoLayoutMode or sequence<GPUPipelineLayout or GPUAutoLayoutMode>) layout;`

**Comment by kainino0x** [comment]
(Never mind, obsolete since we decided we should have multiple hints per entrypoint instead of multiple layouts per hint.)

**Comment by litherum** [comment]
RESOLVED: Add the ability for multiple hints (rather than multiple pipeline layouts) per entry point

**Comment by ottoville** [comment]
Is it still going to be a dictionary? I just realized that for the compute shaders it does not make a sense to define a dictionary as there are no benefits of defining a multiple pipeline layouts of a compute shader.
Compute shader is not part of pipeline with other shaders, and since all entry points of the same shader must share same layout, there are no multiple pipeline layouts for compute shader.

**Comment by kainino0x** [comment]
> Compute shader is not part of pipeline with other shaders, and since all entry points of the same shader must share same layout, there cannot be multiple pipeline layouts for single compute shader.

This isn't quite the case since different entry points can reference a different set of bindings. Even for a single entry point it's possible to have multiple layouts because of the filtering/non-filtering//filterable/unfilterable distinctions. Whether this is useful for a hint or not I'm not totally sure, but it still seems feasible.

Regardless, this API is shared between render and compute, and it's hint-only, so it should be as general as possible I think. If the user provides two hints for the same compute entry point and the browser can't do anything with that, it can drop one on the floor (and issue a warning if it's confident that's never useful in any implementation).
