### ISSUE TITLE
Transfer a GPUTexture or GPUBuffer from one Worker to another.

### ISSUE THREAD

**Issue by sucong0826** [gpuweb/gpuweb#4244]
Hi team,
I am excited to see the topic of Multithreading(https://gpuweb.github.io/gpuweb/explainer/#multithreading) on the WebGPU Explainer. 
As the document mentions, WebGPU does not yet allow multithreaded use of a single GPUDevice, but a tentative plan is provided here. For example, a GPUTexture can be transferred to a worker thread via `postMessage()` because it can be regarded as a handle that can be shared between threads.
I **tried on Chrome and Chrome Canary version on Mac but failed**. This is my code showing how I use it:
```javascript
// DataWorker.js DataWorker is a worker
self.onmessage() = function(e) {
  const data = new Uint8Array([r * 255, g * 255, b * 255, a * 255]);
  let tex = createTextureOnGPU(data);
  drPort.postMessage({ cmd: e.data.cmd, workerId: workerId, source: tex });
}

function createTextureOnGPU(data) {
    if (!device) {
        console.error("GPUDevice is not ready!");
        return;
    }

    const texture = device.createTexture({
        size: { width: 1, height: 1 },
        format: "rgba8unorm",
        usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST,
    });

    device.queue.writeTexture({ texture }, data, {}, { width: 1, height: 1 });
    return texture;
}
```
An error(**Uncaught DOMException: Failed to execute 'postMessage' on 'MessagePort': GPUTexture object could not be cloned.**) occurs while `postMessage({..., source: tex})` is called.
So, I want to know whether this tentative plan is supported. Or any experimental features that I have to enable. 
I am expecting a reply. 
![Screenshot2023_07_24_173415](https://github.com/gpuweb/gpuweb/assets/11333806/33a54362-1af7-4b6e-8e40-9f989aa972e9)
<img width="910" alt="image" src="https://github.com/gpuweb/gpuweb/assets/11333806/27b0af23-e31a-473b-9b09-1cae15658545">

**Comment by Kangz** [comment]
As you found out, posting WebGPU objects between workers is not supported. The spec is slightly unclear because it talks about what would happen if it were supported which makes it seem like posting a GPUTexture should work, but it isn't meant to work.

Adding multi worker support to WebGPU is an extremely complicated addition, and while a lot of people, including browser vendors, are interested, it will be a long time before it is present.

**Comment by sucong0826** [comment]
@Kangz Appreciate!

**Comment by Linchenn** [comment]
@Kangz You mentioned `posting WebGPU objects between workers is not supported`. Are `GPUComputePipeline` instances supported to be transferred between web workers?

I am asking because we want to save a worker thread's compiled WebGPU programs to the main worker, and then a new worker would be able to reuse them to reduce the compilation time for WebGPU programs.

**Comment by Kangz** [comment]
No WebGPU object can be transferred at the moment. Depending on the implementation the GPU process of the browser could be caching pipelines such that the creation on the second worker would be fast. But there's no spec guarantee of that. When multi-worker support is added, I'm positive that pipelines will be part of the addition since they are simple-ish objects that don't have any content.

**Comment by Linchenn** [comment]
Thank you a lot for providing such detailed contexts! @Kangz

**Comment by kainino0x** [comment]
The feature request for this is tracked by #354. I think the question here is answered so I'll close this issue for now.
