### ISSUE TITLE
HTMLCanvasElement copyExternalImageToTexture under specifed?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4255]
The spec currently says

> [GPUImageCopyExternalImage](https://www.w3.org/TR/webgpu/#dictdef-gpuimagecopyexternalimage) has the following members:
>
> source, of type [GPUImageCopyExternalImageSource](https://www.w3.org/TR/webgpu/#typedefdef-gpuimagecopyexternalimagesource)
The source of the [image copy](https://www.w3.org/TR/webgpu/#image-copy). The copy source data is captured at the moment that [copyExternalImageToTexture()](https://www.w3.org/TR/webgpu/#dom-gpuqueue-copyexternalimagetotexture) is issued. Source size is defined by source type, given by this table:

| Source Type | Width | Height |
| -- | -- | -- |
| HTMLCanvasElement | HTMLCanvasElement.width | HTMLCanvasElement.height |

It's not clear what happens if you have a WebGL canvas where `canvas.width > gl.drawingBufferWidth` etc...

**Comment by shaoboyan** [comment]
According to [WebGL spec](https://registry.khronos.org/webgl/specs/latest/1.0/#2.2), drawingBuffer size might not be a 1:1 scale of canvas size.
My understanding is that `copyExternalImageToTexture()` wants to copy valid contents from the input external image (And that should be the valid contents on the screen).
So how about adding a row to see that "when source type is canvas and context type is webgl, width should be drawingBuffer.width and height should be drawingBuffer.height" ?
(NOTE: Other context type canvases have the same context size as canvas size)

**Comment by greggman** [comment]
TODO:

* update spec
* right CTS tests
* add note in spec warning of same event / preserveDrawingBuffer issues

**Comment by jimblandy** [comment]
<details><summary><a href="https://docs.google.com/document/d/1IFhPws-8qhCOKGcUCGZDJ1SmIUbdX7wAKswj_7f-DsA/edit#heading=h.rh26vovxv1fn">Agenda / Minutes for GPU Web meeting 2023-11-01</a></summary>

- GT: not sure what happens if canvas/texture size don't match. In WebGL, canvas width/height aren't the size of the texture, it's drawingBufferWidth/Height, and these may not match.
- KN: tried to solve this on HTML spec side, had hard time. Couple of years ago. Lot of back-and-forth with annevk. How sizes work for canvas, WebGL, ImageBitmap rendering, etc. Don't remember where that left off. Not sure what the behavior is in WebGL or if it's consistent.
- GT: So - hard to spec, need to write tests and tell people to pass them?
- …
- KR: No way to trigger the behavior where width!=drawingBufferWidth with CSS.
- GT: Make a canvas larger than the GL max texture size and it should always trigger this behavior. Doesn’t have to be added to the document.
- KR: No concern with Shaobo’s suggestion to use drawingBufferWidth/Height as the width/height for the copy.
- GT: not hard to make a canvas large. Just zoom out 6x. If multiplying by devicePixelRatio you'll get a 5X canvas.
- SY: as developer, I have WebGL canvas, want to copy into WebGPU. If I render, I might get different content size than canvas width/height. Want to see this fixed. Maybe drawingBufferWidth/Height is a good option.
- KR: seems possible to write a fairly robust test for this.
- JB: what if we copy from a WebGPU canvas? Similar problems?
- KN: no, WebGPU doesn't have this behavior where drawing buffer you get can be smaller than what you asked for. It fails instead.
- JB: is the next step to write tests?
- GT: write spec, then write tests. :)
- KN: probably good idea to also write tests for WebGL & 2D canvas, make sure they also do the same thing. Can go into WebGL CTS b/c both are interactions with WebGL. No guarantee that HTML people will like it.
- KR: can this not be in the WebGPU spec?
- KN: it can go there. WebGL -> 2D canvas though, should be in HTML spec. Our spec'd then pick it up automatically. If defined there, might not need to special case.
- KR: that's CanvasRenderingContext2D.drawImage's behavior right?
- KN: yes.
- GT: you can pass canvas to toDataURL, toBlob, createImageBitmap, …
- KN: it's something we do need a definition for ultimately. Also where you can encode canvas to video stream. Should have definition for this. But this case, think it's OK to special case in our spec.
- GT: other question: thought videos can change size on the fly.
    - KN: yes.
    - GT: how does that work with importExternalTexture? No width/height provided to WebGPU.
    - KN: it captures particular frame, which has well-defined size. Best-guess situation? requestVideoFrameCallback can snapshot width/height at the right time? Preferable, add width/height properties to the external texture object.
    - SY: in external texture impl details, it expects from WebCodecs video frame or HTMLVideoElement. Think we use the video frame size, should resolve this problem.
    - KN: external texture's size is somewhat well defined but no way for app to check what it is. We have width/height properties on GPUTexture, just not GPUExternalTexture.
    - JB: probably should table the video discussion, sounds complex, but file issue & put on future agendas.
- Using CopyExternalImageToTexture() to copy from webgl canvas might get blank result discussion#4356
    - SY: other issue, from our experience: user can use copyExternalImageToTexture from WebGL canvas, get black results. WebGL spec, when you copy from WebGL canvas w/o preserveDrawingBuffer behavior's undefined. (KR: not accurate - only if you do work across different requestAnimationFrame callbacks.) Seems like surprising behavior esp. if they don't know WebGL. Could we add a note to warn people when copying from WebGL canvas?
    - SY: if we can copy WebGL canvas contents before presenting, might get expected results. Any spec that defines well when is "before presenting"? In Chrome we could use rendering to WebGL canvas & copy to WebGPU texture in same render loop - that works. preserveDrawingBuffer may slow performance.
    - KR: This is well-defined in the WebGL spec. Having a warning note in the WebGPU spec about how to use this reliably, and noting the performance impact, would be fine. But WebDL’s behavior is well-defined.
    - KN: we also tried to define this strongly in the WebGPU spec. But we have different guarantees than WebGL. If you're in the same Task, then rendering's guaranteed to still be there. Think we should put a note in the spec. We should also put a warning in place if this happens, if you copy from a WebGL canvas that was already presented+cleared.
    - JB: are warnings called out in the WebGPU spec?
    - KN: we call some out, but they're non-normative.
- JB: AIs: Gregg: spec work/tests. Proposal for the "warning note" in the spec, recommended warnings in impls when working with alrea

</details>

**Comment by toji** [comment]
Appears to have been resolved by #4366
