### ISSUE TITLE
Clarify GPUBufferUsage validation rules

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#426]
Chromium WebGPU implementation forces two rules for GPUBufferUsage:
- Only `COPY_SRC` is allowed with `MAP_WRITE`
- Only `COPY_DST` is allowed with `MAP_READ`

Is that a WebGPU spec requirement? 
FYI I don't see this enforced in Safari WebGPU implementation.

**Comment by jdashg** [comment]
I don't think we should add those restrictions, at least.

**Comment by RafaelCintron** [comment]
In Dawn, the limitation is present due to the way readback and upload heaps work in D3D12.  

D3D12 Upload and readback heap exists so that the API can determine where best to place the memory you’re allocating.  Intent is important.  

In D3D12, it is possible to allocate a custom heap that is on the GPU and CPU writable.  However, CPU reads and/or writes to these custom-heap resources on discrete hardware may be significantly slower than desired.  You’re typically better off allocating upload/readback heaps and using a copy queue to perform explicit transfers between CPU and GPU.  

On cache coherent UMA devices, however, using upload/readback heaps typically has fewer benefits over mapping CPU and GPU writable heaps directly.  See the [D3D12_FEATURE_DATA_ARCHITECTURE](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_feature_data_architecture) page for more information. 

For WebGPU, it’s up to us to decide how much of these details we want to emulate on behalf of the developer while also being performance portable.  Since the [buffer operations](https://github.com/gpuweb/gpuweb/blob/master/design/BufferOperations.md) proposal already prevents developers from writing to memory that is in use by the GPU, I think we should be able to efficiently hide the details of UMA vs. discrete adapters by performing copies behind the developer’s back.  

I do not think we should expose an API where we allow developers to write to memory while it is still in use by the GPU and attempt to emulate that efficiently on discrete hardware.

**Comment by kainino0x** [comment]
If I understand correctly, you're advocating that we *do* allow additional usages along with MAP usages, by implicitly adding copies on discrete gpus?

Under what situation might we allow writing memory while it's in use by the GPU? We would just not resolve the mapWriteAsync promise until we're ready.

**Comment by Kangz** [comment]
Closing in favor of https://github.com/gpuweb/gpuweb/issues/2388
