### ISSUE TITLE
rgb10a2 vertex format

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4275]
WebGPU doesn't have an rgb10a2 vertex format. It is required in all backend APIs:
- Metal: [`MTLVertexFormatUInt1010102Normalized`](https://developer.apple.com/documentation/metal/mtlvertexformat/mtlvertexformatuint1010102normalized?language=objc)
- D3D12: [`DXGI_FORMAT_R10G10B10A2_UNORM` with "Input Assembler Vertex Buffer"](https://docs.google.com/spreadsheets/d/1ALlgyOA5BXXhJDZXPyEQ-vXV_E8IKZfe1xcNmhIM4Mw/edit#gid=1384276076&range=G28)
- Vulkan: [`VK_FORMAT_A2B10G10R10_UNORM_PACK32` with `VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT`](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap48.html#formats-mandatory-features-10bit)

It seem like an oversight that we never added it: https://github.com/gpuweb/gpuweb/pull/206#issuecomment-461630657

Tentatively proposing milestone 1.

**Comment by kainino0x** [comment]
Meeting: Accepted, needs PR!

Will take a small bit of work on backends which implement vertex attributes using vertex pulling (have to unpack the bits).

**Comment by scurest** [comment]
For anyone else who, like me, came here looking for the reason there is no `snorm10-10-10-2`, it appears to be because it is missing from D3D12.

* Metal has [`MTLVertexFormatInt1010102Normalized`](https://developer.apple.com/documentation/metal/mtlvertexformat/mtlvertexformatint1010102normalized?language=objc)
* Vulkan has `VK_FORMAT_A2R10G10B10_SNORM_PACK32`
* But D3D12 does not have `DXGI_FORMAT_R10G10B10A2_SNORM` (the presumed name if it did exist)

**Comment by alecazam** [comment]
@scurest post mistmatched bgr10a2 format for Vulkan.  The correct constant to match Metal is: 

Vulkan has VK_FORMAT_A2B10G10R10_SNORM_PACK32

So that means using the rgb10a2_unorm format, and doing a ~2*n-1 conversion with this omission.  Also complicates custom vfetch from uint in shader.  Metal for custom vfetch is also missing snorm calls.  Only has unpack_unorm10a2_to_float.

**Comment by Kangz** [comment]
Can you detail? In Dawn we use [VK_FORMAT_A2B10G10R10_UNORM_PACK32](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/vulkan/RenderPipelineVk.cpp;drc=c503186f7bd048c46186c18b0587c02ee75d140f;l=145) and it passes tests with the unorm conversion (and not snorm). Likewise the [Metal vertex pulling we inject](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/tint/lang/core/ir/transform/vertex_pulling.cc;drc=69cb4a24bbe798ac9d4d7bb476a91fb1763df562;l=667) does the unorm conversion.

**Comment by alecazam** [comment]
Unorm is usable for hdr.   I guess I'll just adjust all my normals/tangents to 10a2_unorm.  Then that fits all the apis.
