### ISSUE TITLE
Allow emulated capabilities for testing?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#432]
Right now, we've designed WebGPU so it's easy to make sure your application works on the lowest common denominator of devices (by requesting minimum limits and no extensions).

I think we should consider allowing applications to force-enable capabilities which are not supported by hardware, but which we can emulate in the browser.

I'm specifically thinking about compressed texture formats, which are very easy to decompress on upload - it would allow apps to end-to-end and unit test their code which uses compressed texture formats, without requiring them to test on the right hardware. (It takes extra work to make T2B copies work in these cases, though - we can emulate them or disable them, or even not support them at all to begin with.)

OTOH, we should eventually be able to expose every extension (at least the compressed texture extensions) on software implementations like SwiftShader. This is likely to be sufficient for users (and has the benefit of being easy to support on automated testing infrastructure like Travis).

WDYT?

**Comment by Kangz** [comment]
> OTOH, we should eventually be able to expose every extension (at least the compressed texture extensions) on software implementations like SwiftShader.

The advantage of this is that it wouldn't require any special mechanism in the WebGPU spec, while the emulated capabilities probably would need changes to GPUDeviceDescriptor.

**Comment by kvark** [comment]
Sounds like turning a boolean yes/no extension support into tiers:
  1. Yes - GPU supports that
  2. Can emulate on GPU with small overhead
  3. Can emulate on CPU with large overhead
  4. No

**Comment by litherum** [comment]
Extensions already fragment the usages of the WebGPU API. Splitting each extension into 4 tiers makes this problem way worse. Also, I don't think there's any precedent for doing this on extensions in any other 3D graphics API. I don't think this particular solution is a good fit for the problem.

**Comment by litherum** [comment]
I also don't think that emulating compressed textures solves the general problem of having to test extensions on hardware that actually support the extensions. In the future, I'd imagine that almost all of the extensions we will be creating won't be able to be emulated. Therefore, in the long term, we're still going to have a testing strategy where we have a collection of different devices running the WebGPU tests. Therefore, the proposed of emulating compressed textures probably wouldn't actually help much.

Unrelatedly, I'd worry about adding complexity to the API just for the sake of easing our testing burden. If the cost is that it's much more confusing to authors to use an extension correctly (where "correctly" means "non-emulated"), then the cost seems to outweigh the benefit. Rather than giving authors the chance to do it wrong, we should just have robust testing infrastructure.

**Comment by kainino0x** [comment]
Sorry, I wasn't clear. I'm not talking about our testing, I mean apps and frameworks testing infra (e.g. three.js)

**Comment by Kangz** [comment]
@kainino0x is this proposal still current? It seems it could be browser flags when using a software implementation.

**Comment by kainino0x** [comment]
I think that's generally true. Rereading the issue, I think there could actually be some value in exposing emulated compressed textures - it would allow an application to think about only one mobile compressed texture format (say, ETC2), and take the decompression hit on desktop where memory is more plentiful. But absent a request for that, it can just go on the shelf of ideas.
