### ISSUE TITLE
Limitation on the precision of hex floats?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4350]
Reading the WGSL specification: https://gpuweb.github.io/gpuweb/wgsl/#hexadecimal-floating-point-literal

is there a limitation on the number of digits a hexadecimal float can contain? From the wording it appears to be unbounded but that does not seem to align with the expectations in the CTS either

**Comment by dneto0** [comment]
I think we don't need a special rule here. I think "no limit" is the right choice.

The intent is to avoid strange edge cases.  So the spec places no limit on the textual extent of the hex float literal.

Last I looked the CTS did not extensively exercise hex floats, either for validity, or for correctly parsed results. It's one of many holes.  (Happy to accept patches!)

First, the precision of the significand maxes out at 16 hex digits.  That's explained at the section starting: 

> The mathematical value of a [hexadecimal floating point literal](https://gpuweb.github.io/gpuweb/wgsl/#hexadecimal-floating-point-literal) is computed as follows...

So you never need more than 64bits of significand.

Ok, so to first order, an implementation can approach it this way:
* If the literal has a suffix `f` or `h` then it's a shader creation error if the significand has more bits than fit.  [see here](https://gpuweb.github.io/gpuweb/wgsl/#ref-for-shader-creation-error%E2%91%A8)
* Otherwise the literal is abstract float.  This is the limiting case w.r.t. capacities.
    * If the significand is zero, then any syntactically correct exponent is valid because the result is zero.
    * Otherwise, the result is non-zero:
         * You only ever need to keep up to 64 bits of significand (16 hex digits).  (You can cut corners and drop 10 bits because you'll only ever get 52 bits of significand, and you're allowed to round up or down).
         * You can always scan over leading zeros in the significand.  Such leading zeros need to be counted when they appear to the right of the decimal point.
         * You need the exponent contribution from the significand (basically ceil(log2(significand))). And combine that with the written exponent.  This can be done with uint64_t or int64_t counts and arithmetic. It will only go wrong if the token was unreasonably large (e.g. 2<sup>62</sup> hex digits long).  

Tint takes a shortcut on that last point, and in the non-zero significand case, Tint will outright reject any written exponent larger than `std::numeric_limits<int64_t>::max() - 1023`.   But I don't think that case is practically exercisable *and* get the wrong answer because you'd need an unreasonably large token to see the difference.

Tint's internal test suite exercises some interesting cases implied by the above algorithm. E.g. zero-significand written with exponents that have unreasonably large magnitude (positive and negative); that should correctly parse to zero.

It took a few iterations to get Tint to where it is now.  *If the analysis in the general approach above is wrong, please point it out.* 

Stepping back, we also don't have limits on the length of an identifier or other name-like token.  We might want to have a rule that limits token length generally.  I think the above argument says hex-floats don't need their own rule.

**Comment by dneto0** [comment]
(Note: watch out for undefined behaviour in C/C++ with signed integers.)

**Comment by mwyrzykowski** [comment]
Thanks @dneto0 and apologies for the delayed response.

I think we were thrown off with the discussion regarding `truncated_mantissa_next` in the specification when an implementation can set `effective_mantissa` to `truncated_mantissa` which is limited to 16 hex digits. 

I think we can close out this issue.
