### ISSUE TITLE
Make Setting canvas.width and canvas.height lighter weight

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4388]
The current spec says

>   When an `HTMLCanvasElement` or `OffscreenCanvas` |canvas| with a
>   `GPUCanvasContext` |context| has its `width` or `height` properties modified,
>    update the canvas size:
>
>   1. Replace the drawing buffer of context.
>   2. ...

This seems less than ideal. The new drawing buffer will not be used until
the next call to `context.getCurrentTexture()` so I'd like to suggest the
spec should change to something to the effect of

    1. Record the new drawing buffer size

...

And then at `getCurrentTexture()`, a texture of the recorded size should be created

In effect, changing the size of a webgpu canvas should only record the size, not actually cause any other operations to happen (maybe at compositing time something happens?)

The spec shows this code currently

```js
const canvas = document.createElement('canvas');
const context = canvas.getContext('webgpu');

const resizeObserver = new ResizeObserver(entries => {
    for (const entry of entries) {
        if (entry.target != canvas) { continue; }
        canvas.width = entry.devicePixelContentBoxSize[0].inlineSize;
        canvas.height = entry.devicePixelContentBoxSize[0].blockSize;
    }
});
resizeObserver.observe(canvas);
```

The code above provides a bad experience, at least on Chrome. The reason seems to be because of the requirement that setting the width and height of the canvas do something immediately (step 1, replace the drawing buffer).

Chrome might be able to fix this issue without changing the spec but it seems like it would be nice if the spec tried to make it more explicit that the code above is best practice. As it is, it's not best practice.

To see the issue, imagine you have a rAF loop. If you follow the code above, when the user resizes the page, you'll get this behavior

https://github.com/w3c/csswg-drafts/assets/234804/1023d046-ee35-4249-8019-9b3ebdae7b69

The workaround is to only record what you want the size to be but don't actually change the size until just before you call `getCurrentTexture` **AND**, only if the size has changed. This turns out to be a little tedious

```js
const canvas = document.createElement('canvas');
const context = canvas.getContext('webgpu');

const desiredCanvasSize = {
  width: canvas.width,
  height: canvas.height,
};

function render() {
  // Only change the width and height of canvas if they are different
  // because some browsers this is a heavy operation. Since the spec doesn't
  // prevent this from being a heavy operation we have to be pro-active and
  // assume it is
  if (canvas.width !== desiredCanvasSize.width ||
      canvas.height !== desiredCanvasSize.height) {
    canvas.width = desiredCanvasSize.width;
    canvas.height = desiredCanvasSize.height;
  }
  
  const texture = context.getCurrentTexture();

  requestAnimationFrame(render);
}
requestAnimationFrame(render);

const resizeObserver = new ResizeObserver(entries => {
    for (const entry of entries) {
        if (entry.target != canvas) { continue; }
        // Only record the new size here because setting the
        // canvas size itself here is problematic.
        desiredCanvasSize.width = entry.devicePixelContentBoxSize[0].inlineSize;
        desiredCanvasSize.height = entry.devicePixelContentBoxSize[0].blockSize;
    }
});
resizeObserver.observe(canvas);
```

Now the behavior when the user resizes is like this

https://github.com/w3c/csswg-drafts/assets/234804/e5047428-bea9-47fc-8be5-d3fb2906c39f

I'm curious if we could change the spec so setting the canvas width
and height only record the new size and then nothing else happens until
some operation that requires the new width and height. Examples would be

* calling `getCurrentTexture`
* calling `toDataURL`, `toBlob`
* passing the canvas to `drawImage`, `texImage2D`, `copyExternalImageToTexture`

I'm also curious if it would be bad if these functions,
(`toDataURL`, `toBlob`, `drawImage`, `texImage2D`, `copyExternalImageToTexture`)
all used the previous texture and that the only thing that actually changed
textures was `getCurrentTexture`

Conversely, we could change the example in the spec to explicitly call out that it provides a bad experience. It seems like it would be nice to not have to make the user jump through hoops and guess what they'll need to do (1) record the size (2) don't set it if it's the same and instead, just update the spec so the code that's in their currently is, as much as possible, specified to be best practice.

**Comment by kdashg** [comment]
This sounds like what we implement in-practice for webgl and canvas2d already, and what we expect to do for webgpu if we don't already. Is there a reason we need to make this more explicit in webgpu?

**Comment by greggman** [comment]
My observation is that, at least in Chrome, this is not fast currently. (see videos)

That fact, that it's not fast, and that the spec doesn't it require it to be fast, seemed to me to be less than desirable. Which is why I brought it up. If the spec can trivially make this more likely to be performant, that seems good. I know the spec can not dictate performance but, by design, it can make it more likely to be performant.

Otherwise, devs have to assume it's possibly not performant and write defensive code (the current case)

**Comment by greggman** [comment]
Checking some more, the current spec *requires* that setting `canvas.width` or `canvas.height` destroy the current texture, which is observable by trying to use it, and probably heavy.

> When an [HTMLCanvasElement](https://html.spec.whatwg.org/multipage/canvas.html#htmlcanvaselement) or [OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas) canvas with a [GPUCanvasContext](https://www.w3.org/TR/webgpu/#gpucanvascontext) context has its width or height properties modified, update the canvas size:
>
> 1. [Replace the drawing buffer](https://www.w3.org/TR/webgpu/#abstract-opdef-replace-the-drawing-buffer) of context.

Where "Replace the drawing buffer" says to "Expire the current texture" and that in turn says to call `texture.destroy()`.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024‐01‐10-Pacific‐time#make-setting-canvaswidth-and-canvasheight-lighter-weight-4388">GPU Web 2024-01-10 Pacific-time</a></summary>

* GT: can we make this lighter weight? Record the new width/height, and make the next texture the right size. Currently requires destroying the texture, which is problematic - and create the new one. Is that observable?
* GT: I have something which calls "free()" now, and have to refactor a bunch of code to mark it as freed.
* KG: point is - if you want to know how this can work, look at how 2D canvas and WebGL handle this, they already do this optimization.
* GT: I want this to be fast. Portably and reliably. It's easy to fall off the fast path. Can we word things in a way that will make it more obvious? The function does nothing except set the width/height - can't see the effect until you call getCurrentTexture. You can view the destruction of the old texture.
* KG: you can see the clearing of the canvas in the other specs - e.g. 2D canvas resets the context upon resize. The way you have to set width and then height, all the browsers record these and do things lazily.
* KN: it's not just a perf issue - if you write the code that seems correct, it'll do the wrong thing. That seems like the thing to try to figure out
* KG: I hear you, but in context of the other canvas contexts, what we have today is what the others are doing, things are going fine there.
* KN: trying to figure out what's happening in Gregg's screen recording. Behavior I see is not what I'd expect from the spec. I'd expect the canvas to go blank during the resize, potentially. Don't understand the order of things in the frame that causes the stretching behavior.
* KG: often the stretching behavior's because the GPU can't produce new frames because you're allocating over and over. Previous frame wasn't done rendering.
* GT: it's just a ResizeObserver setting the canvas width/height, and rendering on every rAF. It might just be a bug in Chrome.
* KN: trying to figure out whether this is just a Chrome bug. ResizeObserver should be happening between frames. If you're rendering in each frame I think it shouldn't be happening.
* KG: one concern of going down this path of making it more explicit when these things happen - in the spec we'll try hard to spec when things happen, but in a way that's more complex than they are today. And later we may find we need more optimizations, so we're stacking spec optimizations on top of implementation optimizations. Would be simpler if we had a simple reading of the spec. Maybe behave as-if. Browsers can do coarse-grained perf tests in the CTS - e.g. resizing 1000x behaves OK.
* KN: to clarify - 2 different things. One is perf (I didn't read this till now). I think I agree with you - if we can make it fast, no worries about complexity in Chrome. I'm concerned about allowing applications to do the right thing and get a good user experience.
* KG: high level, my interpretation of the spec - it matches the analogous wording of the other 2 specs, and those provide a usable developer UX.
* KN: it's intended to match those. Hopefully it does.
* GT: don't want to make it more confusing. :) But right now the spec's more complex because of the current wording. If you just change it to set two variables that are taken into consideration when calling getCurrentTexture, it's far simpler.
* KN: when you read out of a canvas, we always give you an image with the canvas width/height. 2D canvas was designed as a synchronous API. Canvas is beholden to that. That's why it works like this.
* KG: would be beneficial to take this example and do it in WebGL.
* GT: I did that, it doesn't have the same problem.
* KN: then this sounds like a Chrome bug. We'll talk about it more.

</details>

**Comment by greggman** [comment]
Well, haha, none of the APIs work well with that pattern 😅

Here's Chrome

https://github.com/gpuweb/gpuweb/assets/234804/63010b3d-5b97-4485-81a3-a74b6fece07a

WebGPU behaves best, at least it doesn't flicker

Here's Firefox Nightly

https://github.com/gpuweb/gpuweb/assets/234804/b11db005-9684-4aec-8672-3f96dfb42c43

Note: With WebGPU enabled in Firefox the browser would resize for about 1/2 a second and then freeze for multiple seconds (also had to change `let` to `var` in WGSL and not expect `AbstractInt` to get converted to `f32`

Here's Safari Technology Preview. No errors from Safari with WebGPU but also it didn't draw the WebGPU circle and no errors (at least in the JS console)

https://github.com/gpuweb/gpuweb/assets/234804/35f66c3b-aeb2-4880-8f8f-943c17238a6f

I'm not sure what that means for my proposal. I'd like WebGPU to do better. I'd also like WebGL and Canvas 2D to do better. But given they're all broken right now and unlikely to be fixed anytime so I think the WebGPU spec should probably change its example to something that actually works today.

The example is [here](https://jsgist.org/?src=85491ee9201b6fd68516cc48224c9855). If pick "Save" and scroll down to export you can save it as a stand alone file.

**Comment by greggman** [comment]
Note: I thought maybe because there were 3 canvases in the example above, that it was triggering something but I made an example with a single canvas and just WebGL and it exhibited the same behavior on all 3 browsers. It flickered.


https://github.com/gpuweb/gpuweb/assets/234804/beacabac-29c5-412e-bcfd-148aa904c529

**Comment by greggman** [comment]
I'm going to close this. I think we've resolved that if anything is going to change here it should change in the web platform, not webgpu
