### ISSUE TITLE
Define a `WGSLFeatureName` IDL enum.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#4414]
Found while implementing proper support for `wgslLanguageFeatures` in Chromium. Ideally it'd be nice to have offline consensus instead of waiting for the next meeting (which will be in the new year). Tagging @kainino0x @dneto0 @jimblandy @mwyrzykowski.

Right now the WebGPU spec gives no type for WGSL language features:

```webidl
[Exposed=(Window, DedicatedWorker), SecureContext]
interface WGSLLanguageFeatures {
    readonly setlike<DOMString>;
};
```

And the only way to get the list of possible values is to look them up as string in the WGSL spec. Could we define an IDL enum for them? Also all the WGSL features in the WGSL spec are `snake_case` because `kebab-case` doesn't work in programming language, however it is the convention for JS enums, so can we have the `kebab-case` for the `WGSLFeatureName` JS enums?

**Comment by kainino0x** [comment]
We can't use `readonly setlike<WGSLFeatureName>` because that propagates to the types of the methods like `has(WGSLFeatureName featureName)`. So `wgslLanguageFeatures.has('unknown-feature-name')` will throw an exception instead of returning false.

We could define an enum, but it wouldn't be used anywhere. `GPUFeatureName` is only used in GPUDeviceDescriptor.requiredFeatures which has no equivalent for wgslLanguageFeatures.

We could just write out a list of the extension strings somewhere in the spec. It would be redundant with [the WGSL spec](https://gpuweb.github.io/gpuweb/wgsl/#language-extensions-sec) but that's OK with a comment in both specs that you need to also update the other one.

Personally I think the string should match exactly the one that you use in WGSL (snake case).
