### ISSUE TITLE
Conversion from AbstractInteger to i32 appears to be underspecified

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4415]
We observe the following conversion issue with one of the WebGPU samples and it is unclear if this is a specification bug, an bug in the sample, or a misunderstanding on our part:

In the denominator of line 111 of https://webgpu.github.io/webgpu-samples/samples/cornell#./common.wgsl we see:
```
f32(0xffffffff)
```

`0xffffffff` is initially an `AbstractInt`. As `f32(...)` requires a concrete scalar type https://www.w3.org/TR/WGSL/#f32-builtin, a conversion from `AbstractInt` to `i32` is performed as that has conversion rank 3: https://www.w3.org/TR/WGSL/#conversionrank

However 0xffffffff as an AbstractInt would overflow when conversion to i32 is attempted, failing conversion and therefore shader compilation.

Is this is a misunderstanding on how the conversion rules from AbstractInt to i32 are specified?

**Comment by mwyrzykowski** [comment]
cc @alan-baker, @mehmetoguzderin, and @dneto0 as WGSL spec editors for clarification on the specification.

**Comment by jimblandy** [comment]
This is similar to #4291.

I think we should add an overload to the `f32` constructor for `AbstractInt`.

It doesn't need an overload for `AbstractFloat`, because the only reasonable semantics for that would be identical to the ones when an `AbstractFloat`-to-`f32` automatic conversion is used, which is what we get now.

**Comment by jimblandy** [comment]
It doesn't seem to me that the behavior is underspecified, though. It seems unambiguous to me that the selected automatic conversion is from AbstractInt to i32, and the rightmost column makes it clear that converting the AbstractInt `0xffffffff` to `i32` is an error. It looks to me like whatever implementation is permitting this has a bug.

**Comment by mwyrzykowski** [comment]
Yes the behavior works in tint. We agree this is a bug in tint’s implementation which allows this. 

Should we change the Cornell Box sample then? Or do we want to make a specification change to allow such conversions?

**Comment by ben-clayton** [comment]
I investigated why Tint was not conforming to the spec. It looks like we've been incorrectly including abstract numerics in the type constructors:

[Our WGSL definition file list the overloads](https://github.com/google/dawn/blob/db92ed6fa4b6c575f90576e7215b1bcb45a35bd0/src/tint/lang/wgsl/wgsl.def#L853-L857):
```wgsl
@must_use @const conv f32<T: scalar_no_f32>(T) -> f32
@must_use @const conv f16<T: scalar_no_f16>(T) -> f16
@must_use @const conv i32<T: scalar_no_i32>(T) -> i32
@must_use @const conv u32<T: scalar_no_u32>(T) -> u32
@must_use @const conv bool<T: scalar_no_bool>(T) -> bool

@must_use @const conv vec2<T: f32, U: scalar_no_f32>(vec2<U>) -> vec2<f32>
// and so on ...
```

[Where the matchers are defined as](https://github.com/google/dawn/blob/db92ed6fa4b6c575f90576e7215b1bcb45a35bd0/src/tint/lang/wgsl/wgsl.def#L175-L179):
```
match scalar_no_f32: ia | fa | i32 | f16 | u32 | bool // ia is abstract-int
match scalar_no_f16: ia | fa | f32 | i32 | u32 | bool // fa is abstract-float
match scalar_no_i32: ia | fa | f32 | f16 | u32 | bool
match scalar_no_u32: ia | fa | f32 | f16 | i32 | bool
match scalar_no_bool: ia | fa | f32 | f16 | i32 | u32
```

I remember there was a fair amount of implementation and spec churn around these overloads, and unfortunately it appears that we fell out of sync at some point.

> Should we change the Cornell Box sample then? Or do we want to make a specification change to allow such conversions?

Without trying to impose a _we've implemented and shipped it this way_ bias, I think it would be preferable to change the spec here. It's obviously something that can be implemented (as Chrome did), and obviously something people ([like me](https://github.com/webgpu/webgpu-samples/commit/987937d051f922e8f015c07ce36f5fcdee63a7ce#diff-c22c47b193720da36a33c59665027cafef978aa6066de20b2f8a5c5865a783a4R111)) expect to work when writing WGSL.
I'd be happy to hear any arguments against adding these overloads though.

**Comment by mwyrzykowski** [comment]
@ben-clayton I would propose we both change the spec since it seems preferable to allow this behavior and also change Cornell Box temporarily unless we think the spec change can be made prior to the next WGSL meeting which I think is scheduled for January.

**Comment by ben-clayton** [comment]
Temporary fix for the cornell sample: https://github.com/webgpu/webgpu-samples/pull/338

**Comment by mwyrzykowski** [comment]
@ben-clayton we noticed this issue causes CTS failures as well, e.g., https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,execution,expression,binary,af_addition:scalar:*

For instance, the first test case generates `2097151.99` and stores it in a u32 like `u32(2097151.99)`. There is currently no constructor from AbstractFloat to u32, so 2097151.99 should be converted to a concrete scalar first resulting in 2097152 and then the resulting u32 value is `2097152`. 

The CTS expects truncation of 2097151.99 to 2097151 which is why the result we think the specification should give differs in the CTS specification. 

It would be good to have a resolution on this because the CTS does not seem to be in agreement with the specification either at the moment.

**Comment by dneto0** [comment]
We've been internally discussing the ramifications of this.
It affects the numeric scalar and vector constructors:   f32(.) f16(.) vec2(.,.,.) vec3(.,.,.), vec4(.,.,.) and `array(...)` because they have multiple overloads.

It doesn't affects struct-value-construction or user-declared function calls because there is only one overload.
We think adding the overloads to the spec as a bug-fix is the best way forward.

Here's some code samples to stare at:

```

// These work in Tint/ Chrome but are out of spec.
const scalar:f32 = f32(0xffffffff);
const a:vec2f = vec2(0xffffffff,1.0f);
const a2:array<f32,2> = array(0xffffffff,1.0f);


// Only one "overload" of a struct-value construction.
struct S {
  a: f32,
  b: f32,
}
const s: S = S(0xffffffff,1.0f); // Valid by conversion-rank  AbstractInt --> AbstractFloat --> f32

// Only one overload of a user-declared function.
fn f(a: f32, b:f32) {
}
fn boo() {
 f(0xffffffff,1.0f);  // Valid by conversion-rank  AbstractInt --> AbstractFloat --> f32
}
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐01‐09-Minutes#abstractint-conversion-ranking-forces-unfortunate-compromise--issue-4291">WGSL 2024-01-09 Minutes</a></summary>

* Also: [Conversion from AbstractInteger to i32 appears to be underspecified #4415](https://github.com/gpuweb/gpuweb/issues/4415)
* (needs milestone)
* DN:  
* JB: I think this should be M1, since it’s a bugfix of a feature that we already added. 
* MW: Also noticed an issue converting abstractFloat to int32.
    * [https://github.com/gpuweb/cts/issues/3253](https://github.com/gpuweb/cts/issues/3253)  (shader,execution,expression,binary,af_addition:scalar:* has incorrect expectations #3253)
* AB: Think Ryan was looking into this today.
* BC: Part of a bag of features.
* BC: Think this is a bugfix that would land ASAP.
* JB: Agree this is a bugfix.
* **_#4415 Resolved, needs a PR.  _**
* AB: Is #4291 also closeable?
* JB: **Yes**


---

</details>
