### ISSUE TITLE
Provide a kind of memory layout mapping in BufferDescriptor/BufferInitDescriptor

### ISSUE THREAD

**Issue by Alphapage** [gpuweb/gpuweb#4498]
Hello,

This is just my opinion about how memory layout should be handle by wgsl.
I really don't care about memory layout, alignment ...
I think it must be the job of webgpu to calculate this.

It would be great to be able to submit a contiguous data buffer and a mapping reflecting the size of each data. Something like:
```
struct A {
a:f32,
b:vec2f
}
```
And the mapping: `[4,8]` for example (very basic).

We could implement some trait in the struct A to give the mapping.

The only problem which arises is that vec2f and vec3f have strange memory layout alignment compared to a struct with 2 floats (or 3 floats for vec3f), so it needs to add an identifier something like : `[4,{8}]` to tell to align with vec2f memory layout specs.

So with this optional mapping field filled, then webgpu will send a gpu memory aligned buffer; otherwise, send the buffer to the gpu without any processing.
Is it a crazy idea ?

Thank you in advance for your answers.

**Comment by Kangz** [comment]
Your mention of "trait" seems to imply that this is related to the [wgpu-rs](https://wgpu.rs/) library and not the WebGPU Javascript specification that this repo is for. However the same sort of capability would be useful in Javascript and there has been multiple prototypes of what a [helper library](https://github.com/greggman/webgpu-utils?tab=readme-ov-file#easily-set-uniforms-based-on-your-wgsl-structstypes) could look like. Tentatively closing both because it seems a wgpu-rs issue, but also because work around reflection is discussed in #624.

**Comment by Alphapage** [comment]
Very interesting...
But I think a javascript developer doesn't want to deal with memory layout even with a helper tool.
It is the job of webgpu to take flatten bytes, matching wgsl struct and transform the buffer to the correct memory layout for gpu or in reverse transform the memory layout to contiguous bytes depending on wgsl struct or primitive back from gpu.
and as a rust developer, I don't want to care about memory layout except for few cases whose need to switch to a low level api of course.
I don't understand why webgpu can do it, but nothing will be implemented: this is probably a choice (a bad choice in my opinion)!
