### ISSUE TITLE
Use enum tokens when they are the only possible grammar usage.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#4505]
When moving various parts of the grammar over to be general we moved all of the enums and builtins
to be shadowable. We then do lookups to determine which variable to use. This works well for things
like `f32` and `mix` where the user may want to re-define them and allows us to add new types in the
future.

This doesn't work well for places where we _require_ specific enum values to be used, the value
can't be anything else, and it can't be overridden by the user. The `@builtin` attribute is a good
example for this. There is a set list of tokens which can be used here and they can't be otherwise.

The problem we run into now is that `position` is a very common thing to use in a shader, but if
used then `@builtin(position)` is no longer available. But, we _know_ that `@builtin(position)` isn't
the position variable declared by the user.

We should un-generalize the places where we have enum usages where it can _only_ be the enum value
and specify that we lookup from the set enum list.

Some of these include:

 - `@builtin` can only be a builtin-value enumerant
 - `@diagnostic` the `severity_control_name`
 - `@interpolate` the `interpolation_type` and `interpolation_sampling`

Possibly the usages of `access_mode`, `texel_format` and `address_space` but I haven't checked the
grammar yet.

For the attributes this means changing the grammar from:

```
'@' 'builtin' '(' expression attrib_end
```

to something like

```
'@' 'builtin' '(' builtin_value_enumerant attrib_end
```

**Comment by ben-clayton** [comment]
> Possibly the usages of access_mode, texel_format and address_space but I haven't checked the grammar yet.

These are used by type template arguments, and to support future user-templated code, I feel these should remain as expressions.

I have also hoped that `alias` can alias more than just types, and would allow for something like:

```wgsl
// A single place to control the texel format for textures used by the shader.
alias MyTexelFormat = rgba8unorm;

@group(0) @binding(0) var InputTexture : texture_storage_2d<MyTexelFormat, read_write>;
@group(0) @binding(1) var OutputTexture : texture_storage_2d<MyTexelFormat, read_write>;
```

An alternative to reworking attribute argument resolving would be to accept ["concise attributes"](https://github.com/gpuweb/gpuweb/issues/2589), and migrate developers to use `@position` instead. (That's what I continually find myself writing, then have to fix it after the compiler screams.)

**Comment by dj2** [comment]
I'm fine leaving the access_mode, etc, but I think the argument still stands for the various attributes. 

I'm not a fan of the concise attributes for reasons similar to the arguments on the linked bug, so would prefer we fixed this in a what that works with what we have now.

**Comment by mehmetoguzderin** [comment]
During the 2023 F2F, consensus was made to generalize syntax: https://github.com/gpuweb/gpuweb/issues/3520#issuecomment-1447714561

> The syntax of a language defines its **surface form**.
From https://en.wikipedia.org/wiki/Syntax_(programming_languages) on [2024 02 28](tel:2024 02 28).

Examples:

> attribute-namespace :: identifier ( argument-list (optional) )
C++ attribute specifier syntax (4) from https://en.cppreference.com/w/cpp/language/attributes on [2024 02 28](tel:2024 02 28).

Rust: https://doc.rust-lang.org/reference/macros.html

These distinctions should ideally be handled semantically rather than syntactically. Specializing syntax leads to an unnecessarily rigid language structure and duplication of information for both syntax and definitions. Instead, the differentiation should occur at the semantic analysis or type-checking stage, where the context and usage of these attributes can be thoroughly validated against the language's rules. This approach maintains grammar simplicity and flexibility, leveraging the existing parsing phase without overcomplicating the syntax. By reserving syntax specialization for truly distinct language constructs, we preserve the language's extensibility and maintainability, ensuring that attributes like functions remain versatile while enforcing necessary constraints during semantic analysis.

The fact that current grammar has been working well is a testament to the correct interpretation of the spec. In this regard, a table or a section is already the normative part of how meaning arises from tokens. The spec text is always normative over everything, and if a special rule requires enumerator-like treatment, there is no reason why a normative part can't exercise influence. We don't specialize in syntax for functions or uniformity analysis for the sake of convenience.

What needs to happen, as by consensus, is to generalize and normalize the evaluation, just like built-in functions, by recording once in a table or a list rather than syntax. The syntax is not a reading aid but rather a robust, general form defining the language before semantic and pragmatic evaluation.

Merits of generalization:
- Stable syntax: Attributes are the last place in grammar where we would have to update the syntax for extensions or potential future values.
- Alignment with other programming languages: Almost no programming language specializes in their syntax in this manner.
- Enhanced readability: Generalized syntax reduces distraction from going back between two sources of information, reducing the risk of incoherency and hard comprehension.
- Future-proofing the language for both extensions and tooling: Generalization ensures a temporally stable expression of syntax, eliminating a source of divergence between community tooling and spec, and also increasing convenience in the future.

Hence, I would like to suggest to implement the F2F consensus. We already had a discussion over this, and motivation and gains are clear. https://github.com/gpuweb/gpuweb/issues/3520#issuecomment-1447714561

**Comment by dj2** [comment]
This generalized form is what we have in Tint now and we've been receiving reports from folks using the language that they hit issues like a variable `position` causing `@builtin(position)` to no longer work correctly. So, while we had consensus, from implementing we've run into issues with how this is currently spec'd. This generalization is currently causing frustration for users and should be re-considered.

There are several ways we could fix this, making these pieces of grammar specific solves the issue with the framework we already have in place.

**Comment by mehmetoguzderin** [comment]
As per the consensus https://github.com/gpuweb/gpuweb/issues/3520#issuecomment-1447714561 here, which had serious time and energy of the group with further downstream advantages for WGSL spec tools, too, I would advocate going by the merits of generalizing and then increasing the strength of tables and definitions in the normative text to accommodate any changes in interpreting these constructs (if the group agrees for such **behavior** change to take place) in later stages rather than bending syntactic principles. Hence, out of the ways to fix, given the prior information, it is more beneficial for the language and the spec to generalize grammar and tighten the behavior out-of-band from syntax. The cost of specializing syntax does not pay off (and I believe implementations have freedom as to how they stage their interpretation of the language as in spec; some might prefer treatment earlier than later; the principled approach in spec wouldn't set things in stone for implementation specifics).

**Comment by dj2** [comment]
I'm not sure I see the issue with having the more specific syntax. Downstream tools can handle it as well as they can a super generalized syntax, and it provides more context for them.

I'm not sure what you mean with "implementations have freedom as to how they stage their interpretation of the language". I don't think implementations should have to interpret language of the spec, and if there are multiple interpretations then we've done something wrong as we won't be portable anymore.

**Comment by mehmetoguzderin** [comment]
I elaborated on why generalized syntax in this comment, merits for TL;DR or paragraphs otherwise: https://github.com/gpuweb/gpuweb/issues/4505#issuecomment-1969824534

The spec is not and should not be ambiguous. What I mean there is how they stage their algorithms to interpret language (from a source file) in a spec-compliant way.

**Comment by dj2** [comment]
The attributes aren't the only place that potentially needs to change in the spec for extensions and future values. If we add a new integer character like we have for `i`, `u`, `h`, etc, those would require changes. Even just the list of valid extension names requires updating the spec as they're all listed. So, it really depends on what the extension is doing  if we need to update the spec (look at the changes made to add the f16 extension)

I'm not terribly concerned with how other programming languages write their specs, I think we should write in a way that we find works best for WGSL.

I actually find the generalized versions harder to understand (just trying to determine if we had a list of extensions took me a bunch of clicking around). I have the same issue that I keep mentioning about abstracts and the builtin definitions. Scattering things around the spec makes them harder to find and piece together. Even now, if I'm looking at the `attribute` grammar rule, I can see `builtin` takes an expression but, I now have to search around to find out what that expression can be. It's not clear what the restrictions on it are without scrolling back up and reviewing a separate table.

There will always be a disconnect between tools when the spec evolves. They'll need to be updated in some fashion. If we change the grammar they have to match, if we add enum values they have to add them, there will always be a process of updating as the spec changes.

**Comment by mehmetoguzderin** [comment]
- Going from 10 to 9 places of change is one less place to change, and still having 9 of them does not invalidate the value of gain.
- WGSL does not live in a vacuum; it is a programming language. Aligning with the principles of PL is better than otherwise, and we have clear evidence of how languages interpret the meaning of syntax for the context of attributes. Being per definitions of programming language terminology is what would work best for the WGSL, and there is not only "us" but also a community reading and relying on this language. We can not demand everybody to read every word and construct in a bent way and expect them to be happy about this.
- Syntax is not a reading aid and hard navigation of spec is an editorial issue that needs no pursuit for solution in syntax. There is certainly room to improve, but that is a presentation matter rather than a matter of changing the syntax of the language.
- Tooling is not a primary concern for the group but it just happens that generalization to align with other programming languages is future-proofing and stabilization of one component of the language, incentivizing readers to not look in syntax for changes or behavior details beyond surface form.

**Comment by kdashg** [comment]
I propose:
`'@' 'builtin' '(' ident_pattern_token attrib_end`

That's what I thought I was agreeing to at the F2F.

**Comment by dneto0** [comment]
More of my personal views:
- I care more about the usability of WGSL than how much work it takes to update downstream tools.

Thinking out loud (not a proposal).  Technically the various enums are values (of synthetic types)
We can get Ben's desired aliasing behaviour by allowing the author to write a const declaration for them.

```
const rw = read_write; // currently disallowed 
```
Currently this is disallowed because const decls can only be made for a value from a concrete or abstract constructible type.

**Comment by mehmetoguzderin** [comment]
TBH, the issue needs to split as it seems like there are four things at discussion here:

1. Behavior change so that user declarations do not shadow predeclared enumerant values for at least attributes (whether in static semantics in the Declaration and Scope section or syntax),
2. Aliasing predeclared enumerant values,
3. Having or not having a general attribute syntax form in spec `'@' ident_pattern_token argument_expression_list ?` (for which, previous https://github.com/gpuweb/gpuweb/issues/3520 issue and pending https://github.com/gpuweb/gpuweb/pull/3911 PR, which seems to perfectly align with my understanding at F2F consensus),
4. Human-readability of spec for syntactic and semantic rules.

Without this sorting into multiple issues and focus, I don't think dialogue can be optimally constructive, inhibiting members (including myself) from representing with reasonable clarity. Hence, I suggest first having clear issues to improve the directions for all four topics. Thank you.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐03‐12-Minutes#use-enum-tokens-when-they-are-the-only-possible-grammar-usage--issue-4505">WGSL 2024-03-12 Minutes</a></summary>

* (needs milestone)
* KG: This should wait until Dan can join us, since he filed the issue
* MOD: Concerned this issue brings up valid points about user declarations overriding the enumerants in the attribut parameters. I’m concerned this valid topic is presented in a way that could silently override the previous consensus about generalized attributes.  The F2F consensus was about shrinking the number of rules.
    * Substantive: behaviour change
    * Aliasing predeclared enumerate values
    * Generalized attribute
    * Human navigability of the spec.
* MOD: Suggest we split these issues to focus areas. 
* KG: Personally what matters most for me is, historically, my proposal was that we would allow identifier[-ish] tokens in this case. But the intent was not that they would incur shadowing behaviour. I call that out because I don’t want to operate only that “we had a previous consensus” because evidently we did not (because we understood different things).
* BC: regarding the idea of splitting things apart.  I’m opposed splitting them is because there’s a lot of interaction.  The original proposal made had knockon consequences.  We have to remember the interactions.
* MOD: Agree they play with each other. For the shadowing behaviour change, it could be done in declaration and scope section (add a semantic rule).
* DN: I think the two general wings of this are [editorial spec-reading] side and user-facing behavior side. Of these, the latter is more important.
* DN: [Willing to break backwards compat for e.g. extra parens like `@builtin(((position)))`]
* JB: I think it’s important to think of the template argument case separately from the attribute param case.  They have different constraints. For template arguments it’s fine to live with the template arguments. The urgent one is shadowing builtin position.  When we express an opinion we should be careful to say what we are talking about.
* MOD: Agree priority is the author experience of the language. Is it not the same for user experience whether these rules are set in static semantics for lexical scoping or syntax?
* DN: I don’t worry about how it’s expressed (as semantics words, vs. grammar).
* KG: Let’s be example driven.  See the examples and decide.
* **MOD: Let’s fork an issue** to focus on the issue of whether these builtin params should be shadowable or not.
* DN: I do want to keep the current behavior for template case.
* JB: I agree.

</details>

**Comment by kdashg** [comment]
I tried to split things out along the lines of @mehmetoguzderin's list.
1 -> https://github.com/gpuweb/gpuweb/issues/4539
2 -> https://github.com/gpuweb/gpuweb/issues/4540
3 -> I believe is already #3911
4 -> I believe is best tackled via #3520, though #3520 is a specific case of this.

**Comment by alan-baker** [comment]
#4540 is tracking the only remaining work, recommend closing this issue.
