### ISSUE TITLE
Compat: Disallow vertex stride of 0

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#4515]
I think this is another thing that needs to be added to the list. [WebGPU supports a stride of 0 for attributes](https://jsgist.org/?src=730bcf98d39f4b9d3d717891200c20a0). OpenGL ES does not. Stride of 0 in GL = advance the size of the attribute. Stride of 0 in WebGPU = a stride of 0 as in don't advance the attribute. Just keep reading the same value.

I guess in Compat a stride if 0 in an attribute would generate a validation error? Otherwise you could read value in the buffer, turn off the attribute (gl.disableVertexAttribPointer), and set the attribute's constant value (gl.vertexAttrib4f(...valueReadFromBuffer))

_Originally posted by @greggman in https://github.com/gpuweb/gpuweb/issues/4266#issuecomment-1816139353_

**Comment by greggman** [comment]
There's a common further down, there's a CTS test for that and it's already passing

https://github.com/gpuweb/cts/blob/6e75f19212e3deaebd5bd8542fe10a6fdedc0cdf/src/webgpu/api/operation/vertex_state/correctness.spec.ts#L728

It's passing because in OpenGL this can be emulated by setting the divisor for the attribute to a high number

    glVertexAttribDivisor(attribLocation, 0xffffffff)

Which [is what Dawn is currently doing](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/opengl/RenderPipelineGL.cpp;l=291;drc=cc2516ac15ebeb6c3c07a427a76d6b57832d3154). So I guess no spec changes are needed for this. Just passing on the existing solution.

**Comment by greggman** [comment]
Instancing works fine and is tested in the test linked above. `glVertexAttribDivisor` sets how many instances you have to draw before the attribute advances and setting it to `0xffffffff` means you'll never advance since that's also the maximum instance count.

@kdashg 

I'm going to close this issue since it's solved/done. Re-open if needed.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-03-13#compat-disallow-vertex-stride-of-0-4515">GPU Web CG 2024-03-13 Atlantic-time</a></summary>

    * GT: already a solution. Set divisor of attribute to a giant number, and it works.
    * KG: instance and non-instance values?
    * CW: think we have tests for both. Remember writing tests for them.
    * GT: I can double-check.
    * Consensus. If it works, good - don't need to disallow.

</details>
