### ISSUE TITLE
Accuracy for AbstractFloat `fract` give unintuitive/unexpected results

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#4523]
Currently in the spec, the accuracy `fract` is inherited from `x - floor(x)`, which combined with the spec rules about AbstractFloat inherited accuracy [14.6.2.2](https://www.w3.org/TR/WGSL/#abstract-float-accuracy), so should be 'as accurate as f32`.

Now if I pick a random AF/f64 value, lets say 3937509.87755102, which isn't precisely representable as a f32, that leads to an unfortunate situation.

The f32 version will round the input to 3937510.0 or 3937509.75, which gives an interval of [0, 0.75]... whereas if one stays as f64, you end up with ~0.87755102, which is outside of the f32 interval...

Due to the discontinutity introduced by the use of `floor` there will be a large number of these problematic values.

Since subtraction and floor are correctly rounded/correct accuracies, and fract is not used in the accuracies for an of the other operations my recommendation is to have an explicit carve out for fract saying that its accuracy is defined in f64 not f32

**Comment by kdashg** [comment]
I think you are reading 39375**10**.0 as 39375**09**, as 3937509.87755102 is within [3937509.75, 3937510.0]. But I'm curious about cases where something of this nature leaks through!

**Comment by zoddicus** [comment]
I am unclear on how that would change anything fract(3937510.0) is still 0, because  3937510.0 - floor( 3937510.0) =  3937510.0 - 0.0 = 0.

If you were to include in the context that we are actually doing an operation on a f64 in the f32 space thus this was the upwards rounding, you could infer that the 'correct' fract is actually 1.0 and thus get [0.75, 1.0], but my understanding of the spec is that operations do not carry that context, i.e. the calculation of intervals for a specific value should not need to know where that value came from.

**Comment by kdashg** [comment]
Oh I see, sorry! So `fract` is the trigger:
`fract(f32(3937509.87755102))` -> `0.0` or `0.75`
`f32(fract(3937509.87755102))` -> `.8775...`

 Yes, I think there's not much we can do here, because rounding is a harsh mistress.
If you want the rounding to match, I think it's reasonable to say you can't use abstract floats, and have to use explicit typing.

**Comment by zoddicus** [comment]
The issue we currently have is that they actually agree :-)
because the spec says that AF should defer to f32 in this case (because the accuracy is inherited), so the expectation of fract(3937509.87755102)) is [0.0, 0.75], but the spec in general says that accuracy intervals are approximations of the infinitely precise result with some amount of error.
This is fine for f32 to have this slightly wonky value, because it should be understood that there is a quantization to f32 happening. It is kinda unintuitive though when it happens for AF since the f32 quantitzation is non-obvious.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐03‐26-Minutes#accuracy-for-abstractfloat-fract-give-unintuitiveunexpected-results--issue-4523">WGSL 2024-03-26 Minutes</a></summary>

* (untriaged)
* DN: Gets swept up with the general rule that AF accuracy should be no worse than f32. But in this case that gets weird /bad answers, while doing the perfect thing is easy enough to implement.
* RH: Most times translating to f32 is intuitive enough. In this case you get a drastically different value; there’s a bad discontinuity you fall into.  Should be easy/clear to ..
* KG: Seems works-as-intended. 
* RH: That overload for fract is expected to return between 0.0 and 0.75 (if in f32 domain) in that case but it yields a number outside that range. 0.877 is the right answer.
* KG: Discontinuous functions can’t have error bars. 
* RH: Weirdness comes in because we round to something with a fraction of 0.
* JB: So the proposal is to have an exception in 14.6.2.
* RH: Say fract is calculated in f64 correctly rounded.  Depends on floor and subtraction which are both correctly rounded already.
* KG:** Please propose resolution. ** To my thinking discontinuities will always be a problem.
    * PR [https://github.com/gpuweb/gpuweb/pull/4541](https://github.com/gpuweb/gpuweb/pull/4541) 

DN: rule for abstract float 

	The accuracy of an [AbstractFloat](https://gpuweb.github.io/gpuweb/wgsl/#abstractfloat) operation is as follows:



* A correct result is required when the corresponding [f32](https://gpuweb.github.io/gpuweb/wgsl/#f32) operation requires a correct result.

 

</details>

**Comment by zoddicus** [comment]
As a data point, making the CTS spec compliant for fract caused all of the backends for Tint to start failing the test, https://dawn-review.googlesource.com/c/dawn/+/184160.
So I think the existing spec'd behaviour does not appear to be what people expect.
