### ISSUE TITLE
Synchronously query GPUAdapterInfo

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4536]
Right now it is only possible to get GPUAdapterInfo by calling requestAdapterInfo, which is async.
However, in #4316 we removed the possibility that it would trigger a permission prompt, and I think we should consider it a breaking change to add a prompt - that is, we shouldn't do it (see #3962).

Because of this I don't think there is any reason that `requestAdapterInfo` as it exists today should be async:
- It's easy to prefetch this info along with the adapter - no reason for a round trip.
    - Unless browsers need to keep fingerprintable (but not otherwise secure or private) data out of the content process?
- Any dynamic *measurement* or *modulation* of the adapter info, done by the browser, does not need to be async: `GPUAdapterInfo` has 4 separate getters that can do that stuff. (In fact, this is already necessary: browsers shouldn't assume that just calling `requestAdapterInfo` gives the page everything in the `GPUAdapterInfo` struct. They don't get it until they access the properties.)
- If we make `requestAdapterInfo` actually do anything extra (like via a flag that says "please give me everything you're willing to give me *with* a permission prompt"), the synchronously accessed GPUAdapterInfo can dynamically update to provide that data.

Strawperson proposal:
- Add a `[SameObject] readonly attribute GPUAdapterInfo info;` to `GPUAdapter`.
- It returns the same JS object every time you access it.
- `requestAdapterInfo` still returns a new one each time for minor backward-compatibility reasons (unless we think it's better to change this and return the same one as `adapter.info`).
- If the info available to the page changes, the attributes on the `GPUAdapterInfo` object start returning different values (like an empty string gets changed to a non-empty string).

**Comment by kainino0x** [comment]
^ FWIW the thing that prompted looking at this was designing the C API for RequestAdapterInfo. In the C API we may make it synchronous even if it remains async in the JS API - unless we come up with a reason in this issue that it would be bad for Wasm bindings to call requestAdapterInfo ahead-of-time during C's RequestAdapter.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-03-27#synchronously-query-gpuadapterinfo-4536">GPU Web WG 2024-03-27</a></summary>

* KN: came up because we were talking about the C API. Handy - not fundamental to that though. Where we landed with requestAdapterInfo - no reason for it to be async. Just happened because of how we got there.
* KG: I do agree with that. Not that bad to make your own async function with requestAdapterInfo - no hard requirement to make it sync.
* KN I'd still prefer to clean this up in the JS API. If we agree on that I'll probably change the C API to make this synchronous.
* KG: only reason we might not want to do that - think by the time you request an adapter. you get it from a list that already has this info.
* KN: this is once you have the adapter though.
* KG: think this is fine. Deprecate requestAdapterInfo?
* KN: yes - maybe use it later for something that will pop up a permission prompt.
* MW: I'm fine with this proposal.
* KG: let's put up a PR.
* KN: milestone 1?
* KG: yes.

</details>

**Comment by kainino0x** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-05-22#add-synchronous-gpuadapterinfo-4550">GPU Web WG 2024-05-22 Atlantic-time</a></summary>

* KN: We more or less agreed to do this, the PR is up. There are a few points people should be aware of:
    * With this change, we’re saying that the available info about an adapter may not change: once you’ve accessed it once, it will keep returning the same thing. The only reason it would change if there were a permission prompt. Now the only way to get that new info would be to get a new adapter.
    * The old adapterRequestInfo should not open a user permission prompt, because it would create strange corner cases, depending on what you’d asked for first
    * This PR markes adapterRequestInfo as deprecated but not marked for removal. We should decide if we want to remove it. FF and Safari could just ship without it, Chrome could remove it all
    * JB: no opinion about deprecation; seems pretty easy. Just immediately resolve the Promise.
    * KR: agree.
    * MW: not much of an opinion - our impl already resolves the Promise synchronously
    * BJ: mainly a question - do we need a getter and the function version which fetches the same info. I'd argue "no". Given we have 2 major impls yet to ship, seems like good opportunity - if we won't use permission prompt for function version, phase it out now. FF / Safari ship without that variant.
    * JB: seems removal impacts Chrome more than anyone else.
    * CW: we're willing to do it, keep the wart for a bit, communicate with developers, then remove it. We don't expect a lot of usage of this API.
    * KN: should I remove it?
    * CW: yes, let's just remove it from the spec and we deal with it on the Chrome side.
    * KN: OK. Spec won’t serve as a reference for it anymore, but think MDN's a good enough reference for this.

</details>
