### ISSUE TITLE
Implementation on Windows?

### ISSUE THREAD

**Issue by Nielsbishere** [gpuweb/gpuweb#457]
Is there any implementation for Windows? Or does it only work on Mac? How long will it take until this gets to other platforms?

**Comment by kainino0x** [comment]
On the Chrome side:

If you're willing to build Chromium for Windows or Linux, it's possible to turn it on with a build flag (with some synchronization bugs). Otherwise, I think we plan to have it in Chrome Canary on Windows in the coming weeks. We should be updating webgpu.io when it happens, and you can watch these lists (not sure where we'll announce it).

[Public mailing list for this community group](https://lists.w3.org/Archives/Public/public-gpu/)
[Public mailing list for Dawn (Chrome's implementation)](https://groups.google.com/forum/#!forum/dawn-graphics)

**Comment by kvark** [comment]
Might be worth having a visible section in the Readme: "here is where you file bugs about implementations:", listing Webkit, Dawn, and wgpu issue trackers.

**Comment by kainino0x** [comment]
We sort of have that on the implementation status page (webgpu.io), but it could be called out more clearly, say in a single section at the top.

However this question is not really implementation specific. If there were any implementations available on Windows right now, regardless of browser, it would have been a useful answer.

**Comment by Nielsbishere** [comment]
Thank you, looking forward to it 👍

**Comment by litherum** [comment]
Can we close this issue since it isn't regarding the WebGPU spec?
