### ISSUE TITLE
Add error code to GPUValidationError

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#464]
CTS validation tests currently check that a validation error occurred. However, without looking at the GPUValidationError error message, there is no reliable way to know that a specific error was triggered. And even, when you're sure the right GPUValidationError error was fired, it can change afterwards, and tests wouldn't be able to catch it.

To fix this, I propose adding an error code to GPUValidationError errors. All these errors code would be specified in WebGPU spec.

## Proposal 1

```diff
  interface GPUValidationError {
      constructor(DOMString message);
      readonly attribute DOMString message;
+     readonly attribute unsigned short code;
  };
```

## Proposal 2

`GPUValidationError.message` must always match regular expression: `^\[[0-9]+\]\ *`.
It means (in case I got it wrong which is to be expected) that error messages would look like
`"[42] Vertex Inputs number exceeds maximum"` instead of `"Vertex Inputs number exceeds maximum"`.

**Comment by jdashg** [comment]
Based on my experience in WebGL adding otherwise-unnecessary logic to differentiate e.g. INVALID_OPERATION from INVALID_FRAMEBUFFER_OPERATION, I would love to test only pass/fail, and not try to enforce require specific validation order/logic in the CTS.

**Comment by kvark** [comment]
I think having the CTS comparing some distinct values (like error codes) as opposed to pure strings, because strings are subject to re-phrasing and refining. If we only do pass/fail, we may end up with a situation where it fails for a different reason than expected, and we consider it to be fine. Has this never happen with WebGL?

If we can agree on the code, could we perhaps define an `enum GPUValidationErrorKind` instead of an opaque integer code? With this in, I don't think we should constraint `message` in any way, and instead we can leave it up to implementation to provide additional details.

**Comment by jdashg** [comment]
It shouldn't be important why something fails, but rather whether it fails.
(The spec is as-if, after all!) I would prefer instead that if we want to
test something in particular, carefully craft a test such that exactly one
thing is wrong.

WebGL does have cases where it's valid to return multiple error codes,
because the order of validation is not defined. When you enforce validation
order, you constrain possible implementations, or require overcomplicating
them.

**Comment by jdashg** [comment]
One of the concrete examples was for texImage `format` and `type`. At one point, I started doing validation on these by using a map<FormatAndType, FormatInfo>, and returning INVALID_OPERATION if the pair wasn't in the map. However, technically speaking we needed to return INVALID_ENUM if either format or type was an unrecognized enum for that slot, (e.g. RGBA for passed as `type`) so I had to add back in a check for valid enums. (even though we provide detail text errors to the JS console)

Another case is where the error generated due to operations on an incomplete framebuffer changes based on the entrypoint, leading to having to pipe through the error we need to generate: https://searchfox.org/mozilla-central/rev/7cc0f0e89cb40e43bf5c96906f13d44705401042/dom/canvas/WebGLFramebuffer.cpp#713

**Comment by kvark** [comment]
I think the stronger we can make our test expectations, the better. But since I didn't do much WebGL tests, I'll happily yield to the experts :) Does the Google/Apple/Microsoft WebGL experience match the described above?

**Comment by kainino0x** [comment]
I know we talked about this in some depth a long, long, long time ago. We decided deliberately not to have error codes because in practice, there has been questionable benefit to having multiple error types. Jeff's examples are really good concrete cases where it made the browser more complicated.

When you create a test that hits error cases 1 and 2 (and don't catch it in review), here's how I think it plays out in browser A (which checks 1, then 2) and browser B (which checks 2, then 1).
- no error codes: both browsers pass, you potentially end up with a coverage hole because you thought you had a test you didn't have (perhaps code coverage [in the cts](https://github.com/gpuweb/cts/issues/56) or browsers helps with this). If there's no coverage hole, real life apps looking at errors see consistent results.
- error codes: one browser fails, you fix the test. Real life apps see inconsistent error codes across browsers (with minimal impact). Browser implementations are more complicated because they have to get the error codes right in every case (even if, say, the validation occurred GPU-side). 

And a third case for fun:
- error codes AND the order of error checks is specified: now you have to CTS test the order of every error check in the browser.

**Comment by kvark** [comment]
So the downside of (2) ("error codes") is:
> Browser implementations are more complicated because they have to get the error codes right in every case

Would it be difficult for us to figure out what the error conditions are and how the implementation reacts to them? I thought we are already doing that :) In the spec, everywhere instead of saying "a validation error occurs" we'd be more specific with something like "a validation error of kind 'xxx'" occurs.

**Comment by kainino0x** [comment]
Another downside of error codes is that they are giving some extra data to the app that the app doesn't need. This could end up with people checking the error codes in their actual app logic, when in theory they shouldn't. In other words, it's a feature just for the CTS, which seems bad. If we really wanted it, maybe there could be browser flags to add the code member? Eh.

**Comment by kainino0x** [comment]
> Would it be difficult for us to figure out what the error conditions are and how the implementation reacts to them?

No, not particularly. It's more about cases like the one Jeff shared.

**Comment by Kangz** [comment]
@jdashg I think your concerns based on WebGL experience are the following (correct me if I'm wrong):

 1. Having just a handful of error codes (`INVALID_VALUE`, `INVALID_OPERATION`) isn't really helpful compared to just semantically having a single error code.
 2. Forcing the ordering of error checking is bad because it overly constrains implementations.

I've fixed a couple error code ordering "bugs" in ANGLE so I agree that overly constraining the behavior is annoying.

## Proposal (borrowing from all the comments above)

How about the following, have unique error codes for each validation, similar to the Vulkan VUID mechanism where each "valid usage" rule has a unique ID so that they can be precisely reported by the validation layers. For WebGPU we could make these numbers or strings, whichever. This has the following advantages:

 - Error codes / ids are unique which make questions or bug reports in the WebGPU ecosystem extremely actionable. (better than saying "I got an `INVALID_OPERATION`" on `gl.drawArrays`, which could be any of these 10 rules).
 - Errors codes if codified in the error message will be indexed by Web search engines, which means it will be easy for developers to find resources like StackOverflow even if the error messages produced by several implementations differ. (for example the string WE_0x00140003 would appear the same way in all implementations) The WebGPU spec could also have an index of all these codes that point back to the relevant section of the spec (not hard, just dfn the error code in the algorithm to make them appear in the Bikeshed index).

Then in the spec instead of having algorithms errors return synchronously, we could say they are inserted in a set of errors and if there is any error in the set at the end of the validation, a validation error is produced with one of the IDs in the set. This has the following advantages:

 - Implementation can choose in which order they validate things, and can return eagerly when they encounter an error. They don't implement a set of error codes but under the as-if rule, it works.
 - The spec language will naturally have algorithm that first list all the validation error, return if any error was inserted, then perform the operation. Splitting validation from the rest like that makes it easier for WebGPU developers to read the spec to understand validation constraints.
 - In the CTS we can check that the correct validation error is produced.

The only issue is that in the CTS we don't know if a single error was triggered or multiple. I'd argue this is ok, because as long as the correct error code was produced we know that at least the correct validation code path was covered.

**Comment by jdashg** [comment]
Having to pick the specific error code is onerous to implementations, which could otherwise enforce validation by construction. If we require specific error codes, we end up in an even more constrained state than WebGL.

My experience is that "pick the right error code" is an anti-pattern game we force ourselves to play. Almost no one posts questions about WebGL for "why did I get INVALID_OP", because implementations (or at least Gecko's!) provide quite good text errors to the console, and we try to keep these actionable.

What I want us to consider is whether error codes are have value worth the implementation overhead, and it's been my experience that the more-specific of error codes we have to choose between, the more complicated our implementations. 

I assert:
* Error codes provide no additional value to users and devs, given superior existing text error messages.
* Error code expectations in a CTS cause implementation overhead by forcing the "why" of validation failures.

I see a desire to have CTS tests "get the error for the right reason", but I would rather work on this from the CTS side:
* CTS tests should be "exactly one error" checks, laser-focused on the "what" to enforce the "why" of the failure.
* CTS tests have access to the error message, and should integrate it into test pass/fail text as a sanity-check:
  * GPUValidationError.message: `format("GPUTextureViewDescriptor.baseMipLevel must be >=0, was %i", desc.baseMipLevel)`
  * CTS error line: `"PASS: Negative GPUTextureViewDescriptor.baseMipLevel forbidden: " + error.message`

NB: If I thought I could get away with collapsing WebGL errors to [OUT_OF_MEMORY, INVALID_OPERATION], I would!

**Comment by kvark** [comment]
> because implementations (or at least Gecko's!) provide quite good text errors to the console, and we try to keep these actionable.

There is still a great deal of value in having the errors shared between implementations. We don't want to cause the users to fight with search engines in a search for almost but not exactly error message on the web. This will *especially* hurt less popular browsers, because people searching for our errors will mostly see the errors from Chrome...

And if we do standardize the errors, it seems much more straightforward to do it for some limited enum of codes/kinds than dealing with text strings.

> it's been my experience that the more-specific of error codes we have to choose between, the more complicated our implementations

This is an interesting observation, in a sense that it's unexpected. We do have validation algorithms specified. Where does the overhead come from?

**Comment by jdashg** [comment]
Prop 2: Subtest failure checks as a harness feature
--
CTS includes optional harnessing to inject subtest output checks:
`harness.addSubtestHandler(function (string subtestKey, GPUValidationError) -> bool)`

Enforcing subtest error key/code matching in CI would be as easy as:
`harness.addSubtestHandler((subtestKey, err) => err.message.search(subtestKey))`

It would be easy to add exact error-string checks too, if desired. (I think Microsoft does this for WebGL)

FWIW, it might be generally useful for the harness code to allow hooking results for custom reporting in general, like we do for WebGL already. Such harness code would be sufficient to do the above.

**Comment by kainino0x** [comment]
Here's one further concern to insert into the conversation: It's likely that in some cases the dev tools console error messages will be significantly more detailed than the ones returned programmatically. In particular, the `.message` may be a static string, while the console message may be a detailed string constructed from available info (e.g. the "stack trace" idea in ErrorHandling.md). In most cases, apps will receive the `.message` and then completely ignore it (and it's very hard to construct it lazily, due to multiprocess).

Maybe this is unwanted. After all, this is the error case, so we're not so worried about optimizations. And it doesn't hurt fingerprinting, because it doesn't give any more than is present in the user agent string (i.e. the browser version).

**Comment by Kangz** [comment]
> Implementations can validate by construction/architecture instead of following a validation algorithm exactly.

That's something that we have in Dawn right now, for example we have an `AttachmentState` that represents the compatibility equivalence classes for `RenderPipeline`, `RenderBundle` and `BeginRenderPass`. This way we can check all of the attachment compatibility rules with a single pointer comparison.

Having error codes would indeed require adding more error handling code, but it would only be executed in the error case which shouldn't need to be optimized for performance:

```
if (pipeline->GetAttachmentState() != renderPassAttachmentState) {
  return GenerateCorrectErrorForRenderPipelineAttachmentStateMismatch(...);
}
```

This is something that we would end up doing even without error codes, when we improve or error message to include more information (like the pipeline name, the mismatching attachment and what doesn't match, etc.)

**Comment by kainino0x** [comment]
Discussed on [2019-10-21](https://docs.google.com/document/d/1622qfucqJ4BcGh-cmuCDR7pnm1Af3dmRORzibwXn2nU/edit#heading=h.wt610scv1zb0). Resolution: Google to make a new proposal
