### ISSUE TITLE
GPURenderCommandsMixin.draw / drawIndexed allows for the execution of far too many vertices

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4659]
A website which has a vertex shader which uses zero buffers in its pipeline can issue a draw calls of 4294967295 * 4294967295 vertex shader executions, likely hanging the user's machine or requiring a force-restart. For instance, a call like so:
```
renderPassEncoder.draw(4294967295, 4294967295, 0, 0);
```

is presumably valid when no vertex buffers are required by the pipeline, but results in a number of vertex shader executions which no consumer class computer can easily execute.

The validation for [GPURenderCommandsMixin.draw](https://gpuweb.github.io/gpuweb/#dom-gpurendercommandsmixin-draw) does not prevent this and furthermore, appears to require an implementation to attempt an execution of this many vertices.

I don't know if a limit is necessary, but it would be good to have an escape hatch of sorts in the specification where an implementation can choose to say 'not going to attempt that' before causing a perceived hang for the end user. 

I.e., discard the draw, report a GPUInternalError => vertex * index count is too large.

**Comment by mwyrzykowski** [comment]
cc @kainino0x @jimblandy @toji as the spec editors

**Comment by mwyrzykowski** [comment]
Lost device would seem perfectly acceptable as well

**Comment by toji** [comment]
Adding a bit of existing spec weight to this, the following phrase appears multiple times ([1](https://gpuweb.github.io/gpuweb/#computing-operations), [2](https://gpuweb.github.io/gpuweb/#vertex-processing), [3](https://gpuweb.github.io/gpuweb/#fragment-processing)):

"The device may become lost if shader execution does not end in a reasonable amount of time, as determined by the user agent."

I would say this scenario definitely produces a shader execution that does not end in a reasonable timeframe, and it's not necessary to run the shader to predict that. Preemptively losing the device is warranted.

**Comment by kainino0x** [comment]
> "The device may become lost if shader execution does not end in a reasonable amount of time, as determined by the user agent."

FWIW, this note is just there to call this out as a likely source of device losses. Implementations can of course choose to lose the device whenever they want, so it would be allowed even if not for that note.

+1 to device loss. I don't think it's a good idea to define a hard/configurable limit on draw sizes. There's no number that's simultaneously useful and able to protect against timeouts in all cases (since hardware can be slow, and shaders can be long).

`out-of-memory` or `internal` would _not_ be allowed without changing the spec, but I don't think it's feasible to allow. If we could spontaneously decide not to execute something the application is assuming will execute, it could easily cause serious logic errors for subsequent application code.

**Comment by mwyrzykowski** [comment]
Sounds like device lost is the way to go. Is there any clarification we need to make in the specification or does the existing wording on device lost apply globally throughout the spec?

**Comment by kainino0x** [comment]
Device loss can happen at any time (it has to - drivers can also initiate it):

> Any time the user agent needs to revoke access to a device, it calls [lose the device](https://gpuweb.github.io/gpuweb/#lose-the-device)(device, ["unknown"](https://gpuweb.github.io/gpuweb/#dom-gpudevicelostreason-unknown)) on the device’s [device timeline](https://gpuweb.github.io/gpuweb/#device-timeline), potentially ahead of other operations currently queued on that timeline.

**Comment by greggman** [comment]
I want to just point out that guessing that the call is going to take too long based on number of vertices is a poor metric.

Back when we made O3D (before WebGL), a colleague showed it was trivial to make a draw call that takes too long with very few vertices. 100? 1000?  The simple example is, just make a few nested random texture dependent lookups

    for (var i = 0; i < 20; i += 1) {
      uv = textureSample(randomData, sampler, uv).xy;
    }

You can probably make it worse by having multiple textures instead of one. This effectively kills the cache. Draw a few fullscreen quads and you'll easily get draws that take 10s of seconds or more.

[Here's an example](https://jsgist.org/?src=9799290bd56f389bafa308278afa3d98
) Draws a single quad. Takes 30-60 seconds before I can kill the tab on my M1 Mac. IShadertoy has quite a few single quad shaders that are super expensive.

As we discussed then, while it sucks, there's no incentive for a page to do this. If they do people will no longer go to their page. The site does not gain any info. They don't get any special access. All they do is tell the user "don't ever come back here"

Further, there's nothing we can do. It's effectively [the halting problem](https://en.wikipedia.org/wiki/Halting_problem). The only real solutions that we know of are

* GPU watchdogs like Window's has that reboots the GPU if it doesn't respond in a short amount of time (chrome has/had some implementation of this as well)
* GPUs that are preemptable
* ???

**Comment by mwyrzykowski** [comment]
Oh yes this is very true and we have similar issues in WebGL. It is more along of the lines of preventing the issues we can as opposed to saying all these hangs are undetectable.
