### ISSUE TITLE
Clarification regarding double negation (--) operator?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4669]
The spec appears to be unclear regarding the expected behavior of the following code:
```
    int a = 4;
    int b = 3;
    int c = a -- b;
```
We don't see this called out specifically under https://www.w3.org/TR/WGSL/#operator-precedence-associativity

In JavaScript and C++ this is an error. Tint appears to parse it as `a - (-b)` which is unexpected to us.

Should `a -- b` be an error? Or do we intentionally want this to deviate from JavaScript / existing shading languages in which case should it be called out in the specification?

**Comment by dneto0** [comment]
For concreteness, sample WGSL would be:

```
fn foo() {
  var a = 1;
  var b = 1;
  let c = a -- b;
}
```
The `--` token is only valid in a [decrement_statement](https://gpuweb.github.io/gpuweb/wgsl/#syntax-decrement_statement).  (In the recursive descent form of the grammar, that has been inlined into [variable_updating_statment](https://gpuweb.github.io/gpuweb/wgsl/#recursive-descent-syntax-variable_updating_statement))

The grammar is LALR(1), and the last clause in the parsing algorithm says:

> The token returned is the longest [token candidate](https://gpuweb.github.io/gpuweb/wgsl/#token-candidate) that is also a valid lookahead token for the current parser state. [[VanWyk2007]](https://gpuweb.github.io/gpuweb/wgsl/#biblio-vanwyk2007)

So the set of tokens restricted by the parser state.  In the sample code above `a -- b` is an expression rather than a statement.  

If you build the WGSL spec from source, the LALR checker outputs `wgsl.lalr.txt` that contains the full LALR(1) parsing tables.

For the declaration `let c = a -- b;`  the RHS is an `expression` and you eventually get to matching against `additive_expression`.  Once the parser shifts `a` as a `multiplicative_expression` then the next token is selected from `multiplicative_expression`'s  .follow set.

> multiplicative_expression .follow: {'!=' '%' '&&' ')' '*' '+' ',' '-' '/' ':' ';' '==' '@' ']' '{' '||' /\u200B_greater_than/ /\u200B_greater_than_equal/ /\u200B_less_than/ /\u200B_less_than_equal/ /\u200B_template_args_end/}

The `-` token is in there but not `--`. 
And that's why the parse ends up like `let c = (a - (-b));`

**Comment by mwyrzykowski** [comment]
Is the difference from other languages intentional @dneto0 ?

**Comment by mwyrzykowski** [comment]
To summarize, the concern is the deviation from JavaScript and existing shading languages seems unexpected and likely the specification should be corrected to avoid this. I verified in both GLSL and HLSL this is also a compiler error (as well as MSL which is essentially C++).

It doesn't seem like WGSL should be different from other shading languages, JavaScript, and C++ in this regard.

**Comment by dneto0** [comment]
Avoiding spurious side effects was a design goal of WGSL. The grammar rules fall out from that desire (i.e. increment not being an expression).

Maybe your users might appreciate a warning diagnostic about `--` appearing in an expression.

**Comment by mwyrzykowski** [comment]
Avoiding spurious side effects is reasonable. In this case, it results in a deviation from existing languages. So we think the specification should be corrected to avoid the deviation in this case specifically.  Using the example from above:
```
let c = a -- b;
```
is likely unintentional as this fails to compile in JavaScript and other shading languages (GLSL, HLSL, MSL). We can omit a warning, but it seems like it should be an error to avoid unintentionally allowing such syntax, which in tint is equivalent to:
```
let c = a + b;
```

Otherwise we create a language with very minute differences from established standards. I'm not sure if following established standards is a design goal of WGSL, but I would be rather concerned if it not.

**Comment by jimblandy** [comment]
Mozilla doesn't see the existing WGSL behavior as a problem. We don't plan to add warnings about `--` being interpreted as two tokens.

We introduced the "that is also a valid lookahead token for the current parser state" restriction in #2717, to support parsing text like this:

    let v: vec2<i32>=vec2(1,2);

In order to ensure that the `>=` text in these types is interpreted as two closing angle brackets, rather than a `>=` comparison operator.

#2717 also mentions adding back the bitshift operators, while still permitting `>>` in types like `array<vec4<f32>>`. The introduction of template list discovery disambiguates this particular case without depending on the "valid lookahead token" rule, but I think it doesn't address the `>=` case shown above.

**Comment by mwyrzykowski** [comment]
Resolved today as keeping -- as allowed here but will keep an eye out for similar issues

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐06‐04-Minutes#clarification-regarding-double-negation----operator-4669">WGSL 2024-06-04 Minutes</a></summary>

* MW: Confusing to users who either unintentionally type this. Difference from existing languages is unexpected. Don’t think WGSL is in the business of correcting mistakes in other languages.
* KG: One of the things mentioned on the issue is “ignoring LALR(1) lookahead rules…”. To me it’s at the core of it.  This case is accidental fallout from our higher level choices.  If we were to address this we’d add supplemental rules to identify and forbid this case.
* JB: I added some context in the issue.  [https://github.com/gpuweb/gpuweb/issues/4669#issuecomment-2148076888](https://github.com/gpuweb/gpuweb/issues/4669#issuecomment-2148076888) When we took our grammar and made sure treesitter could handle it, changing it to recursive descent, then we found this apparent ambiguity. We found a case (put in the comment) that can get confusing.
* JB: Classic greedy tokenization will misparse this as if `>=` is a single token.  At the time there was concern with `>>`, which resolved later as template discovery.  The original thing was resolve before template discovery.  This rule really did address the problems we came across. `--` was not talked about.  It’s not right to say this is unprecedented. For a long time C++ needed a space between `> >` at the end of a template. There was rejoicing when that got fixed.  Don’t look to JS for precedent on parsing ambiguity.   Rust is relevant precedent and Rust allows `>>` as two separate tokens depending on context.
* MW: Given this is a JS API we think JS is a highly relevant precedent.  If this is the only issue like this then we think this is not a big issue. If we start to see more than just this one between JS and shading languages, then it would be more of a concern. If this is the only one then it’s not a large issue.
* JB: That’s fair. JS is relevant for the domain. Another way to say what I wanted is … (?)
* KG: It’s not about whether we’re following one or another, it’s a sliding scale of weight. We agreed JS wasn’t the end-all authority. It has more than zero weight.
* MW: If this is the only place this comes up, then we can accep the current behaviour.  There’s benefit aligning with the existing rule.  We feel generally it would be a problem if there were valid things in HLSL or GLSL that were different behaviour in WGSL.
* KG: Recommend warning about this in your implementation.
* **RESOLVED:** **Keep this <code>minus-minus</code> as allowed.</strong>
* AB: Are you looking for more cases like this?  It would be hard to change things like this down the road. I’m unaware of a systematic attempt to find these.
* MW: We ran across this accidentally when gettitng CTS running,.
* JB: converting the grammar for treesitter was a kind of systematic analysis.
* KG: We also have mandatory parentheses rules.  That’s a possible third option.


</details>
