### ISSUE TITLE
mapAsync early-reject doesn't generate a validation error

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4690]
Most error cases of mapAsync both reject the promise AND generate an error-scope validation error:

> - If any of the following conditions are unsatisfied:
>     ...
>     Then:
>     - Issue the map failure steps on contentTimeline.
>     - [Generate a validation error](https://gpuweb.github.io/gpuweb/#abstract-opdef-generate-a-validation-error).
>     - Return.

(I know we discussed this decision in depth at some point, but it was like this [from the beginning](https://github.com/gpuweb/gpuweb/pull/525/files#diff-40cc3a1ba233cc3ca7b6d5873260da9676f6ae20bb897b62f7871c80d0bda4e9R994) so I'm not sure how to find the discussion. IIRC the main reason we kept it was that it was helpful for logging if errors from non-synchronous webgpu operations went there consistently. Anyway that's how the API works.)

However the early-reject case, which rejects if there's already a mapping pending, does not generate a validation error:

> - If this.[[[pending_map]]](https://gpuweb.github.io/gpuweb/#dom-gpubuffer-pending_map-slot) is not null:
>    - Return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) [OperationError](https://webidl.spec.whatwg.org/#operationerror).

The early-reject was added in #3348. Prior to that, IIUC this would have been a device-timeline error (the device-timeline-side state would have been "unavailable"), which _would_ have generated a validation error.

We didn't think about this so this was definitely an oversight, not an intentional change in behavior. Implementing this requires injecting an error from the content timeline, but this should be not too hard for implementations to change.

It's also a minor breaking change. I'm not too worried about this though.

**Comment by kainino0x** [comment]
Point from a conversation I had yesterday: `create*PipelineAsync` do *not* raise a validation error. These are the only two Promise-returning entrypoints that have the possibility of both promise rejection and webgpu (error scope) errors.

If you want to actually catch errors at runtime (much more likely with `create*PipelineAsync` than `mapAsync`) then it becomes painful:
```js
device.pushErrorScope();
const pipelinePromise = device.createComputePipeline({...});
const errorPromise = device.popErrorScope();
const pipeline = await pipelinePromise;
errorPromise.then(() => { ... });
```

`create*PipelineAsync` is also much harder to implement this for. `mapAsync()` can do all of its validation immediately (when the command reaches the device timeline - it doesn't have any errors that are caught later than that, except on the content timeline). OTOH `create*PipelineAsync` can't report validation results until pipeline creation is complete.

We _could_ make these consistent with each other. It's a lot less important for `mapAsync`, but it would be as "simple" as just removing the error scope error from the `mapAsync` validation steps.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-06-26#mapasync-early-reject-doesnt-generate-a-validation-error-4690">GPU Web WG 2024-06-26 Atlantic-time</a></summary>

* + Clarify that create*PipelineAsync must not generate a validation error [#4714](https://github.com/gpuweb/gpuweb/issues/4714)
* CW: This was from Teo?
* KN: I don’t remember what caused me to file this
* KN: Right now, mapAsync generates a validation error and rejects, except in one case where it only rejects. createPipelineAsync is unclear in the spec but we have tests which make sure it doesn’t generate a validation error.
* KN: mapAsync should be consistent with itself: It should always do both or always do one. We decided a long time ago to do both but I think we could change it to only reject.
* MM: I think mapAsync should do both, because of Javascript ergonomics
* KG: KN expressed implementation concerns…
* KN: For mapAsync it isn’t, but for createPipeline it is. For mapAsync, all validation happens immediately, but that isn’t true for createPipeline
* KG: What about OOM errors? Those are always possible to generate from 
    * KN: “out-of-memory” only allowed in a few places. OOMs from unexpected places are supposed to lose the device.
    * MM: Think that’s user hostile
* KG: What places? As an existence proof, as a place where it has to be implementable, that exists, right? The idea that it’s possible to keep an error scope that was pending for a while, is like, has prior art in our spec. In light of that similarity, is it still very onerous?
* KN: I don’t recall if we have any other cases where an error scope would need to be held open like this.
* KG: To me, this is the purpose of the error scopes
* KN: In principle it’s implementable. But &lt;missed>
* KN: The ergonomics, if you actually want to catch both error… the last comment on #4690… it’s ugly.
* MM: does pop error scope provide information that a promise rejection can’t provide?
* KN: The advantage of promises is that you can associate data with the rejection whereas a popErrorScope just gets a string.
* KG: One reason to have both is that we want to support the reject behavior, the reason to have an error scope is that we could also want to catch in a larger error scope for the whole frame.
* CW: Is early-reject an error?
* KG: Is failure to compile an error? Maybe. You might choose to try to compile something without knowing whether or not it will compile. Then failure to compile is not an error. It’s really only an error if you expect it to succeed.
* CW: Rejection here is definitely an error
* KN: I updated the code snippet to use an “internal”-type error scope, because that’s the way you’d actually do this.
* KG: We need to think more about whether these things should be errors or not
* KN: Whether the rejection should be error scope errors?
* KG: Yes. And whether the two should be consistent.

</details>

**Comment by teoxoy** [comment]
I think this should be M0 since https://github.com/gpuweb/gpuweb/issues/4714 is as well.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-10#mapasync-early-reject-doesnt-generate-a-validation-error-4690">GPU Web WG 2024-07-10 Atlantic-time</a></summary>

* CW: If you call mapAsync and there’s a validation error, you get a promise rejection *and* and an error in your error scope. But there’s a way to make the promise reject without an error in the error scope, which is to early-reject the mapping. That’s not consistent. What should we do?
* KN: Since this was intentional that it should produce both types of errors, then both activities should do both
* CW: The rationale for the error in the error scope for the validation is that a well-formed application should be able to use mapAsync without producing validation errors. If you do something wrong (mapped something too big) you get an error in the error scope. But cancelling a mapping is a correct well-behaved thing to do. So it’s unfortunate to ask apps to wrap things in an error scope for behavior that might not be a programming error, or OOM or internal error.
* CW: Taking this perspective, it’s probably better to keep the consistency. It’s not a programmer error. It is a feature of the API that early-rejection can happen.
* KN: Good point. There are possibly some cases where you might intentionally violate the other validation. Maybe you’d want to redundantly map something. But it would give you a new promise, so it would be messy if you wanted to do that. So it’s a pretty clean line to draw.
* CW: If we decide to keep the spec as-is, maybe we can add a note to the spec, describing “this doesn’t do that because it’s not a programmer error”
* KN: Yeah.
* CW: Everyone okay with this?
* &lt;all>: 👍

</details>

**Comment by kainino0x** [comment]
Adding "copyediting" since we decided not to change anything, only add a note.

**Comment by kainino0x** [comment]
I just started trying to implement this and realized we got a bit mixed up in the conversation. This early-reject is _not_ caused by cancelling the mapping (that rejection happens in `unmap()`, and is an `AbortError` - see also #4774). It is caused by calling `mapAsync()` while another `mapAsync()` is already pending.

As I tangentially mentioned in the meeting, this _can_ be used in a valid application - it "ensures" that the buffer is getting mapped without having to check whether it's mapped or pending already. However:
- If the buffer is _already_ mapped - the first map completes before this - we won't early-reject. We'll instead hit the `this.[[internal state]] is "available"` validation, which will reject _and_ generate a validation error.
- Since `mapAsync()` takes a map range, that isn't really something applications should do - the first range will be used, and the second one will be ignored. Applications can instead just do `if (buffer.mapState === 'unmapped') buffer.mapAsync()` and then they'll have written code which clearly intends to "ensure mapped".

So I think the correct thing to do here is to generate the validation error on early-reject.
(For a bit of timing consistency, we could also early-reject if the buffer is already mapped.)

**Comment by Kangz** [comment]
Also the application can check whether it needs to request a mapping or if one is already pending with [`GPUBuffer.mapState`](https://gpuweb.github.io/gpuweb/#enumdef-gpubuffermapstate). So +1 to generate a validation error in this case and early reject.

**Comment by kdashg** [comment]
That sounds right.

**Comment by mwyrzykowski** [comment]
I commented over in https://github.com/gpuweb/gpuweb/pull/4786#pullrequestreview-2267162292 and I'm not too strongly opposed to the change. 

However, it seems like a pattern which exists nowhere else in WebGPU (early reject + validation error). It requires us to go to the device timeline for something which otherwise would not need to go to the device timeline. 

I also understand the counter-argument, which is a rejection without a validation error does not exist in WebGPU. In either case it seems like a unique pattern, unless we were to re-introduce multiple pending mapAsync promises (reintroducing https://github.com/gpuweb/gpuweb/issues/3271). However that actually seems most consistent with the rest of WebGPU, but I would propose no change here.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-08-28#mapasync-early-reject-doesnt-generate-a-validation-error-4690">GPU Web WG 2024-08-28 Atlantic-time</a></summary>

    * PR now only waiting on Apple review: Generate a validation error on mapAsync early-reject [#4786](https://github.com/gpuweb/gpuweb/pull/4786)
    * MW will review.

</details>
