### ISSUE TITLE
Clarify that create*PipelineAsync must not generate a validation error

### ISSUE THREAD

**Issue by sagudev** [gpuweb/gpuweb#4714]
As talked [on matrix](https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$DmG4RAxcm2SQLYyyUfokBLmhctuD016yNNpO-m-KBTM?via=matrix.org&via=mozilla.org&via=matrix.nrp-nautilus.io) create*PipelineAsync must not generate a validation error as it already returns rejected promise.

Currently there is:

> Let pipeline be a new [GPURenderPipeline](https://www.w3.org/TR/webgpu/#gpurenderpipeline) created as if this.[createRenderPipeline()](https://www.w3.org/TR/webgpu/#dom-gpudevice-createrenderpipeline) was called with descriptor;

and [createRenderPipeline()](https://www.w3.org/TR/webgpu/#dom-gpudevice-createrenderpipeline) generates a validation/internal errors inside, but CTS expects no validation error to occur.

**Comment by kainino0x** [comment]
We should double check the conversations/minutes we had when adding create*PipelineAsync, as I'm not sure which we intended.

For comparison when mapAsync has a validation error we reject the promise *and* generate a validation error.

**Comment by kainino0x** [comment]
@toji and I looked at the conversation (#3296). It's not 100% clear what we intended to do, but there's a lot of discussion that seems to _assume_ there would not be a validation error if the promise rejected.

Given we've written the CTS this way (and I'm assuming Dawn passes), we think it makes most sense to change the spec as you suggested.

It's a bit unfortunate that it will be inconsistent with mapAsync(). I don't think there are any other Promise-returning entry points though, so it's just these three. We could probably change mapAsync to not raise a validation error when it rejects, I doubt this would break anything. (IIRC the reason we raise both is just so that the error will be routed to gpu error logging for telemetry/bugreports, but rejecting mapAsync will cause a JS exception which seems plenty good enough.)

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-06-26#clarify-that-createpipelineasync-must-not-generate-a-validation-error-4714">GPU Web WG 2024-06-26 Atlantic-time</a></summary>

    * CW: Coming from WGPU contributor. Spec seems to say “validation error should be produced” but the test requires none to be. I have a vague memory the spec is wrong, but not sure
    * KN: I think so too, but the implementation is complicated. createPipelineAsync() wont’ know validation results until it’s done, and would then go back in time to insert the error into the sequence at the correct place. Also it’s a pain to actually use, which I commented about on a different issue. If you want to catch both errors, you have to write your JS in a gross way.
    * CW: We can ping MikeW directly (he’s not here). Would there be concern at Mozilla?
    * KG: This ties into mapAsync doesn’t generate a validation error. The spec says it should be produced… &lt;missed> These aren’t the same issue, but the 2 issues inform each other.
    * CW: Should we take this out of tacit resolution?
    * &lt;all>: yes

</details>

**Comment by jimblandy** [comment]
In committee we agreed that `create*PipelineAsync` should not raise validation errors, and that the promise should provide complete information about the results, positive or negative.

We also discussed whether the single device timeline block in each of the `create*PipelineAsync` specifications would unnecessarily constrain implementations wanting to implement these with a separate compilation thread. I think the device timeline block must be split:

- All device timeline blocks are totally ordered.
- Each timeline block executes indivisibly.
- Suppose content does a `create*PipelineAsync` followed by something else that also does work on the device timeline and then does followup work on the content timeline. Then:
    - Those two device timeline blocks must execute in the same order as the content timeline blocks that triggered them,
    - Each of those device blocks' followup content blocks must execute in that order as well.

So as written, it seems to me, the spec prevents implementations from letting async pipeline promise resolution drag on past other followup work. The "as if" rule isn't sufficient to let us use the implementation we all want.

I think the `create*PipelineAsync` device timeline block needs to be split up into two blocks, and the language around "When pipeline is ready to be used" should more explicitly permit other device timeline work to occur between the two blocks.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-10#clarify-that-createpipelineasync-must-not-generate-a-validation-error-4714">GPU Web WG 2024-07-10 Atlantic-time</a></summary>

* CW: (In popErrorScope())
* JB: Mozilla encountered a number of questions we had about the spec. One thing is that in the section of the spec called “promise ordering” it explicitly says “nothing is ordered with respect to anything except for onSubmittedWorkDone() with respect to itself and mapAsync and onSubmittedWorkDone(). Is it intentional that popErrorScope isn’t ordered with create*PipelineAsync()? Those are the 2 channels the app can get errors out of pipeline creation
* KW: I’m not sure, but I believe we didn’t intend any pipeline creation errors to come from createPipelineAsync().
* JB: Is it deliberate that createPipelineAsync produces validation errors? According to the spec, it does, because the spec delegates createXPipelineAsync to createXPipeline, which produces validation errors. But since the idea behind *Async is that you could kick it off onto a separate compilation thread, it would make more sense if the Async one is a free-running thing, and it’s difficult to place those errors in order with respect to other device timeline activity.
* KN: I’m pretty sure the intent was that we’d catch any validation errors that came from there, and not let them escape from the async call. For mapAsync() we explicitly decided it would do both.
* JB: Makes sense.
* JB: Final question: In the specification for createPipelineAsync() there is a single block of device timeline stuff, in a single block. We have this thing that starts an async compilation - presumably running on a thread, but it’s technically completely ordered with respect to other device timeline operations.
* KN: It says “when pipeline is ready to be used” but it should say “when pipeline is ready to be used, go do these other timeline steps, which will then issue steps on the content timeline”. It says “set an event handler when this happens, go run the content timeline steps” I don’t know if it makes sense that the device stuff should be split, but we could…
* JB: Once we clarify that createRenderPipelineAsync does not raise validation errors, then its device timeline block doesn’t have any side effects, so implementations are free to run it any time they like. Then the leeway in scheduling the subsequent content timeline steps is enough to permit off-thread implmentations. (JimB: This isn’t right - if two device timeline blocks each trigger a content timeline block, the content blocks must run in the same order that their device blocks ran in. So the createXPipelineAsync device timeline block must be split. I’ll comment in the issue)
* CW: Under the “as-if” rule - if the device is lost, all the steps might work, but you should still get a rejection.
* KN: It might reject, rather.
* CW: My understanding is that there’s a clarification to be done, but also this issue is about “put the behavior up on the ballot again of whether it should reject or not” Are we fine keeping it with just rejection.
* JB: The promise has everything the caller needs - it shouldn’t *also* produce error scope errors
* KN: It’s more simpler to implement and simpler to use.
* CW: Okay.
* JB: It’s a change in the spec.
* CW: Okay.
* KN: It’s a change to the spec and a clarification.

</details>
