### ISSUE TITLE
Should invalid combinations of storage texture formats and access generate a WGSL error

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4728]
tangentially related to https://github.com/gpuweb/gpuweb/issues/4711

These generate WGSL errors

```
@group(0) @binding(0) var tex: texture_storage_2d<rg32float, read>;
@group(0) @binding(1) var tex: texture_storage_2d<rg32sint, read>;
@group(0) @binding(2) var tex: texture_storage_2d<rg32uint, read>;
```

We decided at the last meeting that this should too

```
@group(0) @binding(0) var tex: texture_storage_2d<bgra8unorm, read>;
```

Should these also generate WGSL errors?

```
@group(0) @binding(0) var tex1: texture_storage_2d<rgba8unorm, read_write>;
@group(0) @binding(1) var tex2: texture_storage_2d<rgba16sint, read_write>;
@group(0) @binding(2) var tex3: texture_storage_2d<rgba32float, read_write>;
...etc...
```

`read_write` access is only allowed with `r32uint`, `r32sint`, `r32float`. This seems the same category of error as the ones at the top. Currently this is only validated at bind group creation time. If the bind group layout requires "read-write" but the format doesn't support read-write then you get an error. But the WGSL shader module creation step doesn't generate an error. Should it?

**Comment by teoxoy** [comment]
Since features can enable more capabilities, there can be shaders containing declarations that are not valid on a device without feature X. If we error at module creation time, we force users to create separate shaders/modules based on device features. I think we should rely on static usage and error at pipeline creation time which seems consistent with previous decisions.

**Comment by greggman** [comment]
> which seems consistent with previous decisions.

I think I'm confused on why we decided that a bunch of things that were pipeline creation errors should be converted to shader module creation errors And what the distinction between one case and another is. Can we write the distinction down somewhere?

Initially, all of the compat related issues were pipeline creation errors

* using a `texture_depth_xxx` with `textureLoad`
* using `rg32xxx` as with `texture_storage_xxx`
* using `sample_mask` or `sample_index`
* using `@interpolate(linear)` or `@interpolate(..., sample)`

The reason it was this way was for exactly the reason you state. You could include multiple entry points in a shader module, some that use features that don't work on your device and others that do. Then select one at runtime by specifying which `entryPoint` to use.

Then recently, IIUC, it was decided that as many errors as possible should happen at shader module creation time regardless of `entryPoint`.

So which is it? And, what is the criteria for when something should be an shader module creation error and when it should be a pipeline error?

The argument that WGSL should be lenient and things only validated later seemed to be a rule. But that changed recently and my understanding is that consensus changed so that as many things that can be WGSL errors, should be. I think one argument was you get a line number where the issue is. 🤷‍♂️

**Comment by kainino0x** [comment]
My personal preference is still to produce errors like this at pipeline creation time but the WG decision was to try to make everything consistently error at shader module creation.

It seems like with these two issues (and iirc 1-2 others) we are finding more cases where that decision requires us to move validation earlier, than we originally realized. Should the overall decision be revisited? Should we decide on a case-by-case basis? Should we just keep the current state of things and avoid making breaking changes?

**Comment by kainino0x** [comment]
> The argument that WGSL should be lenient and things only validated later seemed to be a rule. All of the things validated out in compat could be re-enabled by features, so the same arguments seem to apply.

It was a rule I wanted to have, but we were never entirely consistent about it because we accidentally had people pushing in opposite directions in the API vs WGSL groups so some decisions went one way and some went the other way. IIRC the main one that went the other way was how `enable`s were validated - maybe that one should have been the odd one out, instead of trying to make everything else match it?

**Comment by alan-baker** [comment]
I do think compat is a special case because it is adding restrictions instead of relaxations should I wouldn't advocate using it as precedence for other decisions.

I don't think #4711 was ever discussed at the WGSL meeting so it seems odd to have a resolution on it.

My personal preference is that shader module creation be generally device agnostic and basically allow anything permitted in WGSL. Filter out device specific features after that. I don't think that opinion is shared by everyone though.

**Comment by greggman** [comment]
I'm not sure I understand what makes compat special. There's been talk of adding in features to re-enable capabilities missing from compat. That may or may not happen but if it does happen then it would have the same issues and would seem to follow the same logic as native features.

I think https://github.com/gpuweb/gpuweb/issues/4711 is a perfect example since in both cases it's a similar issue, disallowing a particular format in the expression `texture_storage_xxx<unsupported-format, ...>` and in the bgra case, it's gated on a feature.  

That it was discussed at the API meeting vs the WGSL meeting might have been a mistake? But, features are API so it would probably be good to specify the rules for when something should be a WGSL error and when it should be a pipeline error. And, that sounds like it should be discussed by both groups?

**Comment by greggman** [comment]
I'd expect many devs to treat compat as WebGPU version 0 and want to enable more abilities in their code if core is available. In that regard, getting core vs compat feels similar to seeing if a feature exists. My point being, it doesn't feel like "is gated on a feature flag" should be the criteria for WGSL error vs pipeline error

related: https://github.com/gpuweb/gpuweb/issues/4731

**Comment by kainino0x** [comment]
> I do think compat is a special case because it is adding restrictions instead of relaxations should I wouldn't advocate using it as precedence for other decisions.

FWIW we are advancing a proposal for Feature Levels which will make compat less special - it would behave exactly the same way as other future feature levels, except that it's lower than the default one. https://github.com/gpuweb/gpuweb/pull/4761

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐07‐30-Minutes#should-invalid-combinations-of-storage-texture-formats-and-access-generate-a-wgsl-error--issue-4728">WGSL 2024-07-30 Minutes</a></summary>

* KG: Want to reopen the discussion about when errors happen. When does the shader make contact with the API; that’s pipeline creation time.
* 
* AB: There are 3 categories: enables, formats, compat mode. Formats were creation errors, which is appropriate, because a lot of things move between stacks, there’s no reason to do it, there is a clean boundary. For enables, there’s no consensus internally, there are arguments on both sides. One argument is it would be nice to write a module that enables f16 but only some entry points use it, and should be able to compile. But the counter argument: Have to know how to parse F16. That’s a problem for future features. There are some future implications.
* AB: Enables are a little odd because API validations that don’t get validated at validation time - it’s an error off to the side. Usually WGSL mentions creation errors in WGSL, so there’s some things to clean up in the spec.
* MW: I’d be fine making this a validation error at pipeline creation.
* JB: Mike and I would enthusiastic about making this a shader creation error.
* KG: We did a great job of figuring out how strongly we feel about this. It saved a lot of time here
* **Consensus: Retain the previous behavior (which is not in the spec): They are pipeline errors. That includes compat: WGSL would understand them, and compat violations should be handled at pipeline creation time.**
* DN: 3 categories:
    * 1. Enables -> doesn’t get moved
    * 2. Formats -> gets moved
    * 3. Compat/Access validation -> gets moved
* DN: There’s a benefit of having shipped 1 shader blob which includes both path. This morning we had a discussion: that makes us feel queasy. Maybe there’s a better feature that can support that without being wishy-washy in the spec. We could do @enable f16 on functions and declarations. It works like diagnostics. If you parse the whole thing, it says “these are the bits that i’m going to use” and it’s fine-grained and it’s more user-consistent. That would also solve the forward compat and fallback path.
* JB: The effect of this attribute would be used if F16 is not enabled?
* The function is enabling F16. If you’re a compiler that doesn't understand F16, skip the entire block
* MM: That means we can’t add a feature that has unmatched brackets, but that’s probably good
* JB:  Rust has a balance-brace(?) requirement also.
* JB: It’s like a conditional compilation thing, sort of.
* DS: Yes. could also put it more finegrain, like if-statement.
* MM:If you did @enable(foobar) then that can act as a giant block comment?
* &lt;all> yes
* KG: What milestone are you targeting this for?
* DN: M3+.  Don’t rush into inventing this.
* JB: We aught to be setting up for - we wanna be co-evolving with people who are using stuff. We don’t want to be inventing little features that we think will help people in the large. WGPU should maybe partner with [someone] to ask them for requests

</details>
