### ISSUE TITLE
Depth Bias does not affect line and point primitives.

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#4729]
While working on [an improvement for the wireframe sample](https://github.com/webgpu/webgpu-samples/pull/430) I discovered that `depthBias` and `depthBiasSlopeScale` don't apply to line and point primitives! At least not on D3D and Metal, and maybe not on Vulkan. I was unaware of this limitation previously, and based on my searching through spec discussion it doesn't appear to have come up in this group.

[**D3D12**](https://learn.microsoft.com/en-us/windows/win32/direct3d11/d3d10-graphics-programming-guide-output-merger-stage-depth-bias) 
"Bias is not applied to any point or line primitives, except for lines drawn in wireframe mode." (Page linked is for D3D10/11, but is linked from the [D3D12_RASTERIZER_DESC docs](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_rasterizer_desc).

[**Metal**](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1516269-setdepthbias)
"Note: A depth bias only influences triangle primitives, but doesn’t apply to points or lines."

[**Vulkan**](https://registry.khronos.org/vulkan/specs/1.3/html/chap25.html#primsrast-depthbias)
"Depth bias is applied to triangle topology primitives received by the rasterizer regardless of [polygon mode](https://registry.khronos.org/vulkan/specs/1.3/html/chap25.html#primsrast-polygonmode). Depth bias **may** also be applied to line and point topology primitives received by the rasterizer."

So Vulkan is the only API that leaves open the possibility of depth bias affecting lines and points.

At the very least I think we should add a note to the WebGPU spec to indicate that this is the case, but given the potential for variation in behavior here I'd also suggest that we consider adding validation to enforce that `depthBias`, `depthBiasSlopeScale`, and `depthBiasClamp` are 0 when a line or point primitive topology is used.

**Comment by Kangz** [comment]
An alternative is to silently make it 0 for points and lines if we want to avoid the breaking change. (either solution seems ok to me)

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-10#depth-bias-does-not-affect-line-and-point-primitives-4729">GPU Web WG 2024-07-10 Atlantic-time</a></summary>

* BJ: realized none of the APIs have depth bias affect lines or points; but this isn't reflected in the WebGPU spec. Vulkan spec says depth bias "may" affect these. 2 approaches: if we see pipeline using line/point topology, zero out these values (Corentin's suggestion) so we can say these are ignored all the time. That way we don't break any existing code. If anyone relying on the "may" in the Vulkan spec (hard to imagine) then could turn this into a validation error. Using depth/point topology, then these depth bias values in the pipeline have to be zero. My preference: these will be ignored all the time, so we can just zero them out.
* GT: that error would help me know why my stuff wasn't working. :)
* MM: there's a porting issue here. There'll be apps ported from other APIs to WebGPU, they might have this stuff set and expect it does nothing. So I think an error isn't the right thing. Browser could print a message to the console instead.
* BJ: agree. This would've helped me find issues in my code too. Could print warning to console.
* KG: porting libraries/efforts - not a big deal to just zero these things out. Better to be explicit.
* KN: weak preference for a warning. Think a lot of our validation's onerous. If you set this thing and this other thing must not be set - not good - better to say, these things have to be set to zero. I'm OK either way.
* BJ: also weak preference for the warning; could live with validation error. Like KG's suggestion to have option to re-enable this in the future. Validation error would work for this - have a feature in the future, remove the validation error. If it's a warning - any migration pitfalls? Turn on this feature, something breaks that you didn't know was there before? Warning scenario would spam warnings to the console.
* CW: argument to be able to re-enable this in the future is probably the deciding factor to raise a validation error here. Worth breaking 1-2 websites that use this.
* MM: so today those websites would work OK on D3D and Metal, and sometimes on Vulkan? And we break them all? That sounds bad.
* KG: think this isn't a very important use case. But would save developers like Gregg who were scratching their head.
* CW: either warning or error fixes that. Bar for making breaking changes isn't that high right now while there aren't multiple WebGPU impls in the field. Chromium's OK making this change because this is a tiny change.
* KN: we're removing requestAdapterInfo; that's bigger. More of a trial right now, "can we do this"? This one isn't major. We can collect telemetry, deprecate it. Think it's fine to do. And if we see lots of people using this, we'll know.
* CW: OK to go with hard error for this?
* &lt;consensus: yes>

</details>
