### ISSUE TITLE
Compat: Should requesting compat mode on a device that supports core, return core or compat?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4731]
The spec proposal currently says

> When calling GPU.RequestAdapter(), passing compatibilityMode = true in the GPURequestAdapterOptions will indicate to the User Agent to select the Compatibility subset of WebGPU. Any Devices created from the resulting Adapter on supporting UAs will support only Compatibility mode. Calls to APIs unsupported by Compatibility mode will result in validation errors.
>
> Note that a supporting User Agent may return a compatibilityMode = true Adapter which is backed by a fully WebGPU-capable hardware adapter, such as D3D12, Metal or Vulkan, so long as it validates all subsequent API calls made on the Adapter and the objects it vends against the Compatibility subset.

As a dev, I *think* I'd prefer that if a user agent can return core that it return core. Then, I can design my app to work if I get compat, but use more features if I get core. This seems similar to enabling features

### core

```js
const adapter = await navigator.gpu.requestAdapter();

const requiredFeatures = [];

// enable features both in the device and in my code if they exist
const canFilterF32 = adapter.features.has('float32-filterable');
if (canFilterF32) {
  requiredFeatures.push('float32-filterable');

const device = adapter.requestDevice({ requiredFeatures });

...

const sampler = device.createSampler({
  magFilter: canFilterF32 ? 'linear' : 'nearest',
  ...
});

```

In compat I'd like to do similar things

### compat

```js
const adapter = await navigator.gpu.requestAdapter({compatibilityMode: true});

const canUseSampleInterpolation = !adapter.isCompatibilityMode;

...

const module = device.createShaderModule({
  code: canUseSampleIterpolation
    ? higherQualityShader
    : lowerQualityShader,
});

```

This pattern seems intuitive to me. It will also work for some cases as a UA that doesn't support compat will return a non-compat adapter.

As it is currently implemented in Chrome, requesting compat gives you compat, period. So, the only way to do better than compat is to first request core and, only if it fails, then request compat

```js
const adapter = await navigator.gpu.requestAdapter() ??
                await navigator.gpu.requestAdapter({compatibilityMode: true});

const canUseSampleInterpolation = !adapter.isCompatibilityMode;

...
```

I guess it's not that bad to do two requests, although it is slower. It's also less intuitive IMO but the spec can spell out how to do it.

The disadvantage to returning core when compat is requested is that you can't test compat validation in the CTS nor in your own code without either more flags, either to requestAdapter (`forceCompatibilityModeIfSupported: true`) or browser flags external to the page. 

Whichever direction (1) return core if you can (2) return compat if requested, should it be specified which? The current proposal says "a supporting User Agent **may** return a compatibilityMode = true Adapter". Should that "may" change to "must" or "must not" or stay as "may"?

Note that regardless of these issues, a UA can of course completely ignore compatibility mode.

**Comment by Kangz** [comment]
> The disadvantage to returning core when compat is requested is that you can't test compat validation in the CTS nor in your own code without either more flags, either to requestAdapter (forceCompatibilityModeIfSupported: true) or browser flags external to the page.

This is exactly the reason why requesting a compat adapter returns an adapter with compatibility validation on if it is requested. Maybe the validation should say that it must return a compat adapter if there's any configuration in which it supports a real compat adapter?

**Comment by kainino0x** [comment]
While writing #4898 I realized I don't think we can _really_ normatively specify anything, the UA can always pretend it doesn't have a compat implementation (and so upgrade compat to core).

Also when going through the pros/cons of this when Gregg brought it up again recently, I'm tentatively leaning toward:
- not having the spec encourage either behavior (even non-normatively)
- not enforcing compat behavior by default in chrome (e.g. can be enabled with some dev tools option or flag, or an extra `forceCompatibilityMode` dictionary member only available with `chrome://flags/#enable-webgpu-developer-features`).
  I am more worried about Hyrum's law - sites that only test on Chrome relying on compat to always be enforced; it's _difficult_ but certainly not impossible for a site to break when the enforcement is removed. I am less worried about sites that _want_ to support compat forgetting to _test_ compat - they just have to run their tests with the flag enabled.

**Comment by Kangz** [comment]
Could you detail what brought you to this conclusion?

I assume that the browser should tell you somehow which feature level it ended up choosing, so either a browser tells you it used compat, and does all the validation according to compat, or it says it chose core, and does all the validation according to core.

**Comment by Kangz** [comment]
Decided to keep the currently agreed upon behavior where requesting compat on a browser that supports compat always enables its validation.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-11-20#compat-should-requesting-compat-mode-on-a-device-that-supports-core-return-core-or-compat-4731">GPU Web WG 2024-11-20 Atlantic-time</a></summary>

* GT: presented intro
* CW: intent was always that for Compat, we want developers to be able to easily test Compat if they're on a browser that supports that feature level. They test on their machines, it'll work on all browsers that support Compat. Otherwise they can't really test, if they were auto-upgraded to Core.
* JB: Gregg, under your proposal, how will developers that want to validate against Compat do so?
* GT: they'd have to pass in some flag or something outside the browser to get the behavior.
* KR: could misspell the command line flag…would rather that requesting Compat return Compat if the browser supports that.
* KN: OK with either way - and I think it's a UA decision - only thing that concerns me is Hyrum's law, people depending on Compat because of slight differences. A few differences which are not super hard to accidentally rely on, in a way that'd break on an impl that doesn't support Compat. [Either way we can tell people to test Chrome with a flag to try a browser that does the opposite behavior.]
* CW: WebGPU with features/limts are opt-in. Pushing devs toward max portability, even if annoying sometimes. My app supports Compat - your app will get Compat for max compatibility. If it works on your machine, it'll work everywhere you expect.
* KN: I think that's more important than people accidentally relying on Compat.
* CW: only thing that people can rely on in Compat is vertex stuff, like provoking vertex.
* KG: we discussed this before, think we should have strong reason to do so again. 2 use cases: i want "compat or core", or i want to check compat on a browser that supports core. If we make it not auto-upgrade, and i want it to auto-upgrade, i can write the code to do 2 different calls. If i want compat, can write the code to ask for it. If it were the opposite - in the auto-upgrade case i'd just ask for a thing. But if i want to check compat - and we do want people to do so - it's difficult and depends on the browser. Mean of all these options is to keep the status quo. Think we should pursue more graceful auto-upgrade in the future, but right now think it's tolerable to make the 2 adapter requests.
* CW: think that's compelling, thanks for the description. Unless strong objection, let's close as WontFix.
* GT: &lt;thumbs up>

</details>
