### ISSUE TITLE
The value of the fragment builtin `@position`

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4777]
I wrote tests assuming that fragment builtin `@position` as in

```
@fragment fn fs(@builtin(position) fragCoord: vec4f) {
   ...
}
```

is pixel centers. In other words, the top left pixel's `@builtin(position)` value is `0.5, 0.5, _, _`. The pixel to the left of that is `1.5, 0.5, _, _,` etc...

This test passed on M1 Mac, Intel Mac, AMD Mac, NVidia Windows, Intel Windows, AMD Linux, others..... but not on OpenGL (via ANGLE through Vulkan on AMD Linux)

It was pointed out that the OpenGL spec, while it lists a formula for computing `gl_FragCoord` that seems like it would always return pixel centers, it does not require that formula to be followed.

From the [GLSL ES 3.1 spec](https://registry.khronos.org/OpenGL/specs/es/3.1/GLSL_ES_Specification_3.10.withchanges.pdf)

> The variable *gl_FragCoord* is available as an input variable from within fragment shaders and it holds the
window relative coordinates (x, y, z, 1/w) values for the fragment. **If multi-sampling, this value can be for
any location within the pixel, or one of the fragment samples**. 

It's not clear to me from other specs (DirectX, Metal, Vulkan) whether or not this holds true for them as well. Like OpenGL ES, they all list a formula that would return pixel centers. I didn't find if they have a caveat like OpenGL that the formula is not the truth.

How should we address this? Detail it in the spec? Ignore it?

**Comment by dneto0** [comment]
For Vulkan, see the description of FragCoord in [15.9 Built-in Variables](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#interfaces-builtin-variables)

> Decorating a variable with the FragCoord built-in decoration will make that variable contain the framebuffer coordinate  of the fragment being processed. The (x,y) coordinate (0,0) is the upper left corner of the upper left pixel in the framebuffer.

> When [Sample Shading](https://docs.vulkan.org/spec/latest/chapters/primsrast.html#primsrast-sampleshading) is enabled, the x and y components of FragCoord reflect the location of one of the samples corresponding to the shader invocation.

> Otherwise, the x and y components of FragCoord reflect the location of the center of the fragment.

So that's tighter than the OpenGL rule. If multi-sampling it can't just be anywhere in the pixel.

I should note that the implementation doesn't necessarily have to use the standard sample locations.

> `standardSampleLocations` specifies whether rasterization uses the standard sample locations as documented in [Multisampling](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#primsrast-multisampling).

That's a bool property in `VkPhysicalDeviceLimits`

**Comment by greggman** [comment]
It makes sense that when "sample shading" is on it would be the location of the sample, and I have tests for that. But, GL ES 3.1 doesn't have "sample shading".

**Comment by kainino0x** [comment]
> I should note that the implementation doesn't necessarily have to use the standard sample locations.

We require it in the WebGPU spec.

**Comment by greggman** [comment]
AFAICT, the current spec requires `@position` to always be a fragment position, never a sample position

https://gpuweb.github.io/gpuweb/wgsl/#built-in-values-position

Should we relax that or enforce it?

Enforcing it means if the backend does not return fragment positions, including when multisampling, the implementation must quantize. (eg: `webgpu_position = floor(native_api_position) + 0.5`). 

Users can still know the sample position with code like this

```
const sample_positions = array(
 vec2f(0.375, 0.125),
 vec2f(0.875, 0.375),
 vec2f(0.125, 0.625),
 vec2f(0.625, 0.875),
);

@fragment fn fs(@builtin(position) position: vec4f, @builtin(sample_index) sample_index: u32 {
  let sample_position = position + sample_positions[sample_index];
  ...
```

This would make things portable regardless of the backend (although GL doesn't provide `sample_index`)

Conversely, we could change the spec so that `@position` is implementation defined.

**Comment by Kangz** [comment]
+1 to require specific behavior, either always being the center of the fragment, or also allowing sample-shading to case it to be exact sample positions like in Vulkan. This seems related to #4696 where we'd like to be very precise as to when per-sample shading happens.

**Comment by mwyrzykowski** [comment]
Since we already specify the sample positions in https://gpuweb.github.io/gpuweb/#rasterization and the definition in the WGSL spec https://www.w3.org/TR/WGSL/#position-builtin-value says it is the "Input position of the current fragment.", isn't this already specified precisely between both specifications?

I.e., no additional specification change is needed?

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐08‐27-Minutes#the-value-of-the-fragment-builtin-position-4777">WGSL 2024-08-27 Minutes</a></summary>

* Corentin: Please confirm the milestone. If it is M0 then we would need some resolution.
* KG: We specify the standard positions.  The bug is to specify it more clearly. If someone wants to propose more clear language.
* DN: Gregg’s concern was that OpenGL might not follow what was specified.
* JB: It would only be a problem for compat.
* MM: Seems the cost of a polyfill would be cheap:  observe the deviation, then adjust shaders like that 
* KG: It actually occurred with a particular ANGLE configuration. We could either: don’t ship compat on that config; relax compat for that reason, or the implementation may decide to deviate from the spec.
* **_Resolution: no update needed to the spec. (but if you disagree, please just make a PR to add the language that satisfies you!)_**


</details>
