### ISSUE TITLE
More strongly push developers toward correct use of GPUAdapter

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4784]
> I do wonder if we should do something more aggressive to encourage authors to assume that adapters are flakey, like specing them to *start* expired 10% of the time.
> 
> I also think it would be cleaner to change the one-requestDevice-success-per-adapter rule to one-requestDevice-attempt-per-adapter. I think it would be encourage more robust code if the workflow for requesting a device *always* required requesting an adapter.
> 
> In some ways, this turns an Adapter into a one-shot DeviceRequestConfigurator in a two-step device creation workflow.

_Originally posted by @kdashg in https://github.com/gpuweb/gpuweb/issues/4352#issuecomment-2248596686_

**Comment by toji** [comment]
> encourage authors to assume that adapters are flakey, like specing them to start expired 10% of the time.

For the record, I'm strongly against introducing any "expected flakiness" into the API as a stick for forcing devs to do the right thing. That'll just lead to endless confusion from new developers and over-diagnoses of legitimate problems as "must be the adapter lifetime thing". I do not object, however, to introducing similar behavior via dev tools or flags that developers can opt into in order to harden their apps against real-world problems.

> the one-requestDevice-success-per-adapter rule

As I recall, this was phrased in this way because we had `requestAdapterInfo()` as an async function and we wanted to ensure that developers could both get the adapter info and get a device out of the adapter before it expired. Now that `adapterInfo` is synchronous we could look at if it's beneficial to say that an adapter expires after control returns to the browser if we want to be agressive about it.

**Comment by kainino0x** [comment]
requestAdapterInfo() still worked even after the adapter expired. I'm not sure but I think the reason we did one-success-per-adapter was so people could do things like:
```
device = await adapter.requestDevice(better config);
if (!device) device = await adapter.requestDevice(fallback config);
```
if they had very simple requirements, rather than checking the adapter capabilities.

**Comment by mwyrzykowski** [comment]
I'm not sure if I understand the argument for the change other than to prevent developers from doing the wrong thing. Seems like warnings could be appropriate from the browser vendor and no specification change is needed here

**Comment by jimblandy** [comment]
Mozilla as a team doesn't have a strong opinion on this. For myself, at least, the current spec behavior seems fine.
