### ISSUE TITLE
Draft an extension for depth clamping

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#480]
Depth clamping is very important for implementing regular shadow maps, see https://github.com/gpuweb/gpuweb/issues/137#issuecomment-442947463
The only platforms that [don't support it](https://vulkan.gpuinfo.org/listreports.php?feature=depthClamp&option=not) are some ARM/Qualcomm/ImgTek mobile GPUs.

**Comment by Kangz** [comment]
Yeah it sounds interesting, although the OpenGL extensions say they were designed mostly for stencil shadows which are not used anymore. I'm curious about how much it impacts game developers looking to target mobile devices (esp. Android) today.

It looks like it might be possible to implement by injecting the following at the beginning of fragment shaders: `gl_FragDepth = clamp(0, 1, gl_FragDepth)` and interactions with the stencilDepthFailOp and depth tests would just work. But this would likely cause some mobile GPUs to take underperforming paths because they wouldn't be able to do a depth-only rasterization followed before calling only the visible fragments since the depth is set by the fragment.

**Comment by kvark** [comment]
> It looks like it might be possible to implement by injecting the following at the beginning of fragment shaders: gl_FragDepth = clamp(0, 1, gl_FragDepth)

The depth clipping (if enabled) happens *before* the fragment shader is ran, so this workaround is not possible.

I guess the mobile devs try to adjust the near/far planes of the shadow maps to always include all the geometry, conservatively.

**Comment by magcius** [comment]
The other typical solution for pancaking is changing the vertex in the shader to clip to the near plane, but this can lead to distortions of triangle shapes for big triangles.

**Comment by Kangz** [comment]
> The depth clipping (if enabled) happens before the fragment shader is ran, so this workaround is not possible.

Gotcha, thanks for the clarification.

**Comment by pythonesque** [comment]
@Kangz It is not just useful for stencil shadows, it lets you set your near and far planes to encompass just the shadow receivers when rendering a conventional shadow map, which fully utilizes the available Z range (since you don't care about the depth for shadow casters that aren't in the scene, you can make all their depths the same, but you still need to draw them).
