### ISSUE TITLE
Compat: sample locations don't match the spec in OpenGL

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4804]
Running [this test, which sets each sample of a 4 count multisample texture to a different color and then uses `textureLoad(multisampledTexture, vec2u(0), sample_index)` to read each of the samples to a storage buffer](https://jsgist.org/?src=9594f5173cc5fe871eec74dba2fd3a99) in Chrome on Linux AMD OpenGL gets different results than the other APIs

normal results

```
sample_index: 0  value: 1,0,0,0  si: 0
sample_index: 1  value: 0,1,0,0  si: 1
sample_index: 2  value: 0,0,1,0  si: 2
sample_index: 3  value: 0,0,0,1  si: 3
```

GL results

```
sample_index: 0  value: 1,0,0,0  si: 0
sample_index: 1  value: 0,0,0,1  si: 3
sample_index: 2  value: 0,0,1,0  si: 2
sample_index: 3  value: 0,1,0,0  si: 1
```
  

I ran into this issue writing the [`textureLoad` WGSL tests](https://gpuweb.github.io/cts/standalone/?runnow=1&q=webgpu:shader,execution,expression,call,builtin,textureLoad:multisampled:*)

We think maybe swizzling the index in `textureLoad` on the GL backend is enough to fix this? If not, another solution is to disallow `textureLoad` on `texture_multisample_2d<???>` textures in compat. other ideas?

**Comment by Kangz** [comment]
We could say that locations may be non-standard in compat, and maybe even expose the sample location info on the adapter?

**Comment by kainino0x** [comment]
I don't know for sure but I suspect standard sample locations are not _that_ critical, and compat should just loosen the guarantee.

**Comment by greggman** [comment]
The workground seems trivial and I think they are critical. Either that, or we should remove

```
textureLoad(t: texture_depth_multisampled_2d,
                         coords: vec2<C>,
                         sample_index: S)-> f32
```

from compat

**Comment by kainino0x** [comment]
Resolved in meeting that we will workaround, and the number of devices with non standard sample locations is probably vanishingly small (e.g. [on vulkan](https://vulkan.gpuinfo.org/displaydevicelimit.php?name=standardSampleLocations)) so we will only revisit loosening the spec if we actually find such devices.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-11-20#compat-sample-locations-dont-match-the-spec-in-opengl-4804">GPU Web WG 2024-11-20 Atlantic-time</a></summary>

* CW: what's possible in Compat w.r.t. sample locations?
* GT: can barely remember :) Can't look at sample index or sample mask, but can call textureLoad on a multisample texture. So can draw over corner of a texture that's sample 0 and then textureLoad sample 0 and they'll be in different orders.
* GT: think we should polyfill because if you ask for index 1, should get index 1. This is textureLoad, not textureSample. Expect to get what I asked for in that case.
* JB: in this example, sample index 0 isn't actually disturbed in OpenGL.
* GT: use sample 3 then.
* JB: like your suggestion that since we have a low-cost workaround that works for everybody, Mozilla likes the suggestion. Especially since no change to spec. :) 
* CW: not just that order of samples is shuffled - they might not be in the exact same position.
* KN: nothing we can do about that. Spec has to loosen that guarantee in Compat. Can say order of quadrants is the same, but samples could be in different places.
* CW: OpenGL spec doesn't specify the sample locations.
* SW: surprising if same device in Vk and GL had different locations.
* CW: it is configurable on a lot of hardware. :)
* KN: on Vk, small number of impls that don't report standard sample locations. On GL I don't think there's a way to query it. On Vk , couple of really old NVIDIA devices, and Broadcom D3D?
* GL: you can query this in GL FWIW.
* CW: if we can't change the sample locations, or spec says nothing, people probably won't realize the sample pattern's slightly different.
* SW: I agree. Quadrants are known broken, let's fix that, and sample locations are unknown how broken they are. Revisit when we have more data.
* KN: there's a test for the positions. If they fail, we'll find out.
* CW: everyone's fine remapping quadrants, and is OK not saying anything about non-standard sample locations, and seeing later.
* KN: yes.
* Resolved.

</details>
