### ISSUE TITLE
Error on viewFormat with no compatible usage?

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#4852]
Originally raised in https://github.com/gpuweb/gpuweb/pull/4746#discussion_r1735353059

Should specifying a `viewFormat` that has no compatible `usage` defined on the texture trigger a validation error at texture creation time?

Example:
```js
const t = device.createTexture({
  size: { width: 64, height: 64  },
  format: 'rgba8unorm',
  viewFormats: [ 'rgba8unorm-srgb' ],
  usage: GPUTextureUsage.STORAGE,
});
```

If we implemented this validation, the above would trigger an error because `rgba8unorm-srgb` cannot be used with `STORAGE` usage, which in turn means that you can't create a valid view with that format from this texture. If the texture was instead created with `STORAGE | RENDER_ATTACHMENT` usage it would not fail validation at texture creation time because even though `STORAGE` is still invalid to use with `rgba8unorm-srgb` you could still create a valid view with just the `RENDER_ATTACHMENT` usage.

It is worth noting that the validation proposed in #4426 and added in #4746 already ensures that views must be created with compatible formats and usages, so even without this validation there's no way to create invalid texture views. This instead would be an earlier error to help developers identify potential problems or performance pitfalls in their code.

Alternatively, browsers could be encouraged to surface warnings in this situation rather than surfacing it as an error, since the `createTexture()` call itself can succeed in this case and it's only later potential `createView()` calls using the viewFormat that would fail.

**Comment by Kangz** [comment]
Thank you for splitting this from the PR.

The usual concern about what happens when an application programmably builds arguments lists applies here: the usages could be chosen dynamically based on what the content is. It would be ideal to not force applications to duplicate the validation in their code to avoid this dynamic error (after the first time it fails in the wild and they spend quite some time figuring out what this is)

**Comment by toji** [comment]
Agreed. I feel that a warning from the browser would be sufficient.

**Comment by toji** [comment]
Agreed to keep this as a warning on the call.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-09-11#m0-error-on-createtextures-viewformat-with-no-compatible-usage-4852">GPU Web WG 2024-09-11 Atlantic-time</a></summary>

* (not createTextureView)
* BJ: we have opportunity to raise an error if you create a textureview with a viewformat incompatible with the usages on the top-level texture
* BJ: previously wanted to have browser raise a warning. CW says warning might still be the right way to handle this because otherwise app has to 
* KG: generally in favor of permitting the useless thing
* Consensus: leave this as a warning

</details>
