### ISSUE TITLE
Make GPUAdapterInfo a dictionary instead of an interface?

### ISSUE THREAD

**Issue by saschanaz** [gpuweb/gpuweb#4876]
```webidl
[Exposed=(Window, Worker), SecureContext]
interface GPUAdapterInfo {
    readonly attribute DOMString vendor;
    readonly attribute DOMString architecture;
    readonly attribute DOMString device;
    readonly attribute DOMString description;
};
```

This interface solely includes readonly strings and nothing else, can we make this dictionary? An interface requires more boilerplates and web-exposed objects than a dictionary.

This also applies other Info interfaces, but this one seems easier to change given the spec recently changed how to retrieve the interface (#4662). Note that retrieving a dictionary requires a method than an attribute, though.

**Comment by kainino0x** [comment]
I had to think about this for a while, but I remembered there was actually a specific reason that we used an interface here.

Initially, we did this because it was an output and never an input, and it _seems_ interfaces are usually used for that. Then we realized we want browsers to be able to see exactly which fields are accessed, for detecting fingerprinting, and even making late decisions about which info they'll expose.

This might be technically possible when returning a dictionary (by returning an object that has getters instead of regular properties) but we didn't see that much downside to having an `interface`.
