### ISSUE TITLE
smoothstep: please remove error check when edge0 > edge1 for compile-time constants

### ISSUE THREAD

**Issue by reindernijhoff** [gpuweb/gpuweb#4900]
According to the definition of smoothstep, using smoothstep with values egde0 > edge1 is perfectly fine. It saves you a subtraction, the pattern is used a lot in WebGL shaders and works satisfactory, and the resulting code is easier to read:

```
1. - smoothstep(0., 1., t); vs 
smoothstep(1., 0., t);
```

For unsigned variable types, the return value is probably undefined. But even with this undefined behaviour, it does not need to throw an error. 

The current implementation not only differs from the implementation of smoothstep in WebGL, but it is also internally inconsistent because it is still possible to use egde0 > egde1 by passing numbers that are not compile-time constants

_Originally posted by @johanholwerda in https://github.com/gpuweb/gpuweb/issues/4561#issuecomment-2376045607_

**Comment by greggman** [comment]
That it's possible you can do something illegal is not a reason to allow it.

Here's a shader that fails because of unportable behavior via `pow`

https://compute.toys/view/1467

On AMD/Intel Mac

<img width="544" alt="Screenshot 2024-09-30 at 1 03 51 PM" src="https://github.com/user-attachments/assets/ed9aed4b-e963-4c9b-ba53-006db378e992">

On M1 Mac

<img width="550" alt="Screenshot 2024-09-30 at 13 03 06" src="https://github.com/user-attachments/assets/062084d6-d370-472d-8492-c16717dc22d9">


If you use constants you'll get an error. 

[example](https://webgpufundamentals.org/webgpu/lessons/resources/wgsl-offset-computer.html#x=5d00000100a500000000000000003d888b0237284d06f5efe7f20c7d802a8bf8cf368b1a5b0d15256c17705afa23176227168bcacf9df59f4ca719f476509981ecbff6c30d345e5822b6a75239e40b1b25f637f587cb47bee4f75f40206a59779d7fa16bbcd0c290d057308eaa10a8bd4abd8cf00c993fc646e5824421bc1844d5d9641a7f2bca0023fdcbba80)

And the [counter example](https://webgpufundamentals.org/webgpu/lessons/resources/wgsl-offset-computer.html#x=5d00000100a500000000000000003d888b0237284d06f5efe7f20c7d802a8bf8cf368b1a5b0d15256c17705afa23176227168bcad079ca9f129b86d9cc0b9172fff85caa8e3a3ca1c5d86872ea11ef763fdc173011994a674737987365c1e28fe4ed125e83079b9fbaf04cd2637a462a65d3c72b6013005d58eb328e76ae1f107b5e73e1ad51aac7f8fdca6340) that compiles

If you use variables [you won't get an error](https://webgpufundamentals.org/webgpu/lessons/resources/wgsl-offset-computer.html#x=5d00000100d200000000000000003d888b0237284d06f5efe7f20c7e03a5e0f62b2d3436ac1b3757fb1b227d3d0270443580ea76ec26d3ffaf084fe900989907a4812c69b52323fe596d56f5859a9f6d5e4adaff635394dad004fd15ab257e415f62b720d5842883e81700724c0389532e256d9670c8816543e25deba3bbb69bfd38cf3f27e183ab86e81646a312471d2ffac44ce34c5b4de0ff508bc1632bb9ff4fc48000). 

It seems like you're suggesting that we remove the check when they are constants but the argument is not that we should allow everything but that we should rather catch what we can to help developers find the non-portable bugs in their code.

**Comment by reindernijhoff** [comment]
Taking the pow of a negative number is different than calling smoothstep with edge1 < edge0, as the pow of negative numbers is, in general, not defined for real numbers.

If you look at the definition of smoothstep (as given in all shader documentation I can find), it is perfectly fine to have edge1 < edge0 for any signed type. In the ~10 years of writing shaders for the web (in a commercial setting), I never encountered a problem on any device, so it seems to me that the documentation is overly conservative.  

Adding this restriction makes code less readable (IMO), because you will have to add extra subtractions (1. - smoothstep ) to your code half of the time.

**Comment by reindernijhoff** [comment]
That's also fine for me, as long as I can use smoothstep with edge1 < edge0 :)

**Comment by reindernijhoff** [comment]
> If I look at the definitions I see if edge0 === edge1 then the results are clearly NaN as there is division by 0.
> 
> It looks like the definition should be re-written something like
> 
> ```
> if edge0 === edge1
>    if edge0 < x
>       return 1
>    else
>       return 0
> else
>   t = clamp((x - edge0) / (edge1 - edge0), 0, 1);
>   return t * t * (3 - 2 * t);
> ```
> 
> That's what the GPUs appear to do but it's not what any of the specs say.

I think this is because `clamp(-1/0, 0, 1)` seems to return 0 and `clamp(1/0, 0, 1)` seems to return 1, but as a programmer, I would not rely on this.

**Comment by dneto0** [comment]
I think these are good arguments:
* You're right, the function makes sense with edge0 > edge1. It just traverses the curve backward.  
* It saves you a subtraction.

I'm not opposed; we'll need to review in committee.  I pulled this into Milestone 0.

**Comment by dneto0** [comment]
Hm.  
MSL, SPIR-V, and GLSL say results are undefined when edge0 >= edge 1.  So giving the guarantee in WGSL implies polyfilling it everywhere, which means bloating and slowing down the function for everybody's use case.

**Comment by reindernijhoff** [comment]
If you look at the definition of smoothstep, it is clear that results are undefined when ege0 > edge1 for _unsigned_ variable types when ege0 > edge1. For signed types, it is perfectly fine to have edge0 > edge1, and it would require extra code to return undefined values in this case.

So, my guess is that the documentation is overly conservative, and the remark about undefined behaviour when edge0 > edge1 is only valid for unsigned variable types.

**Comment by reindernijhoff** [comment]
> I think these are good arguments:
> 
> * You're right, the function makes sense with edge0 > edge1. It just traverses the curve backward.
> * It saves you a subtraction.
> 
> I'm not opposed; we'll need to review in committee. I pulled this into Milestone 0.

thanks!

**Comment by kainino0x** [comment]
> If you look at the definition of smoothstep, it is clear that results are undefined when ege0 > edge1 for _unsigned_ variable types when ege0 > edge1.

I wouldn't expect smoothstep to exist at all for any unsigned types, only float types, which are always signed. (This is at least true in WGSL, Metal, and GLSL.)

**Comment by magcius** [comment]
> So giving the guarantee in WGSL implies polyfilling it everywhere, which means bloating and slowing down the function for everybody's use case.

I'm not sure how you could arrive at this conclusion? `smoothstep` is not a native hardware function on any GPU I'm aware of, it compiles down to the same ALU instructions that writing it by hand would.

**Comment by felixfaire** [comment]
The original post describes this issue well but, but i'd like to add another voice that having this smoothstep restriction as a compile error is very limiting and inconvenient from a shader writers perspective. It is very common to use smoothstep (as defined in many popular references) as a function that returns 0 at edge0 and 1 at edge1 (regardless of sign/order).

Our app was working reliably until google chrome recently made this use of smoothstep a compile error in their webgpu implementation and now many of our shaders need to be changed to use more instructions and be less readable for seemingly little gain. This generally gives wgsl a worse developer experience compared to most other shader languages that don't have this strict limitation.

**Comment by cwfitzgerald** [comment]
I think it's reasonable to polyfill it where needed, as the spirv floating point version is also undef if `edge0 >= edge1`. Might be worth looking at the polyfill to ensure similar codegen from platforms so gracious to show us their assembly, but I probably wouldn't be too worried about it.

**Comment by dneto0** [comment]
To me, polyfilling the const case implies also polyfiling the runtime case.   It's bad to be inconsistent between const and runtime like that.

But if implementations polyfill the runtime case, we penalize performance for everybody. That's not good.

To me it's still a strong sign that the underlying shader languages don't support the edge0 > edge1 case.

**Comment by greggman** [comment]
> it's still a strong sign that the underlying shader languages don't support the edge0 > edge1 case.

They do support as evidenced by the massive amount of real world usage.

Can't we just polyfill the runtime case on devices that don't support it if such a device exists? We have various workarounds for other things. Why not this one?
