### ISSUE TITLE
WebgGPU: the case for Reversed Depth Range

### ISSUE THREAD

**Issue by Kuranes** [gpuweb/gpuweb#497]
Reversed Depth Range is a great trick to get better precision on Z buffer, just wanted to know if it's planned for webgpu or not.

It's an important tool in the rendering tool set, and still missing it in next gen graphics API would be sad.

Previously: https://github.com/KhronosGroup/WebGL/issues/2197
(since then DX12 and vulkan, and metal happened, so maybe need to re-check answers)

If it's not planned, please make sure to update the documentation/specification accordingly, 
as https://gpuweb.github.io/gpuweb/#render-pass-encoder doesn't state if
condition ```minDepth < maxDepth``` is mandatory in "setViewPort"

**Comment by Kangz** [comment]
Initial [tests](https://dawn-review.googlesource.com/c/dawn/+/13600) make it seem that it doesn't consistently work on D3D12 and Metal. Sometimes flipping the depth range does the same as not flipping, and other times it breaks the depth testing in weird ways.

**Comment by kainino0x** [comment]
That would be really unfortunate. I think many of us were assuming we would be able to support it.

**Comment by kvark** [comment]
Exactly! I would say, we do support it unless proven otherwise.
@Kangz could you shed more light on the issues you are seeing?

**Comment by magcius** [comment]
Flipping minDepth and maxDepth in setViewPort isn't reversed depth and likely won't lead to increased precision. The gain you get from reversed depth is that *floating point has more precision values closer to 0.0 than 1.0*. And the far plane is where most of your Z fighting should occur, so it makes sense to place the far plane at 0.0.

In order to do this, you *have* to modify the vertex shader, which is doing all of its math in limited-precision floats, to use this mapping. This means that it really can't be done after the projection math is done, since the precision is lost by this point.

The depthRange viewport call is about the mapping of clip-space depth to viewport depth. Clip space depth, in modern APIs, is specified in the range 0...1, and in OpenGL, in range -1...1. This is why reversed depth really doesn't work on OpenGL, despite having glDepthRange and a viewport depth range of 0...1. The precision that matters happens, including the perspective divide, is done on clip coordinates.

**Comment by Kuranes** [comment]
Yes, in gl it's with arb_clip_control, gl_DepthRangedNV and a custom far clipping plane. 

Issue is about How/Where we can achieve the same results in webgpu  ?

( As linked above, If you need more details on how it works and results it gives  https://developer.nvidia.com/content/depth-precision-visualized, http://dev.theomader.com/depth-precision/ )

**Comment by magcius** [comment]
WebGPU already uses a clip-space with a depth range of 0...1, which is the equivalent of what glClipControl would do. When you update your projection matrices to use this clip space, update it to use a reverse-depth projection matrix, as described by your above blog posts. glDepthRangedNV is an extension from a long time ago and is pretty obsolete.

If you are using gl-matrix, I filed an issue to adapt the API for this: toji/gl-matrix#369

You can also do this as a transformation on top of an existing perspective projection matrix. For a perspective matrix designed for OpenGL's symmetrical -1...1 clip space, this is just negating the depth remap components of the projection matrix:

```ts
m[2][2] = -m[2][2];
m[2][3] = -m[2][3];
```

For a perspective matrix designed for Direct3D's 0...1 clip space, you need to subtract 1 from the near depth range value.

```ts
m[2][2] = -m[2][2] - 1.0;
m[2][3] = -m[2][3];
```

Orthographic matrices have a different depth remap component, and thus require a different adjustment. I worked it out on paper a few weeks ago for the D3D case:

```
// The typical orthographic depth remap from N-F range to 0-1 range is a basic lerp:
//   Z = (p.z-N) / (N-F)
// This breaks down into:
//   Z = 1/(N-F)*p.z + (-N/(N-F))*p.w
// We want:
//   Z = 1 - ((Z-N) / (N-F))
// Which works out to:
//   Z = -1/(N-F)*p.z + (N/(N-F) + 1)*p.w
// Negate the p.z term, negate and add 1 to the p.w term
m[2][2] = -m[2][2];
m[2][3] = -m[2][3] + 1.0;
```

**Comment by Kuranes** [comment]
Thanks a lot for the detailed answer solutions

**Comment by kainino0x** [comment]
This repo is for WebGPU, not WebGL. I don't think WebGL supports reversed depth: https://github.com/KhronosGroup/WebGL/issues/2197
