### ISSUE TITLE
Compat: Disallow usage of depth textures with non-compare sampling functions.

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#4970]
All sampling operations on shadow samplers require depth ref in GLSL 3.1, i.e. they are all compare operations as defined by our spec.

> For shadow forms (the sampler parameter is a shadow-type), a depth comparison lookup on the depth
texture bound to sampler is done as described in section 8.19 “Texture Comparison Modes” of the
OpenGL ES Graphics System Specification. See the table below for which component specifies Dref. The
texture bound to sampler must be a depth texture, or results are undefined. If a non-shadow texture call is
made to a sampler that represents a depth texture with depth comparisons turned on, then results are
undefined. If a shadow texture call is made to a sampler that represents a depth texture with depth
comparisons turned off, then results are undefined. If a shadow texture call is made to a sampler that does
not represent a depth texture, then results are undefined.

_from Section 8.9 Texture Functions of https://registry.khronos.org/OpenGL/specs/es/3.1/GLSL_ES_Specification_3.10.withchanges.pdf_

Sparked from https://github.com/gfx-rs/wgpu/pull/6529#issuecomment-2473669114.

**Comment by kainino0x** [comment]
@SenorBlanco

**Comment by greggman** [comment]
I think I'm missing what's undefined that's currently allowed in compat?

|                       | texture_2d/3d<f32> with depth | texture_depth_?? |
| --------------------- | ----------------------------- | ---------------- |
| sampler filtering     |       validation error        | validation error |
| sampler non-filtering |        ok                     |    ok            |
| sampler comparison    |       validation error        |    ok            |


> All sampling operations on shadow samplers require depth ref in GLSL 3.1,

Yes, shadow-sampler = `sampler_comparison` which can only be used with function that take a depth_ref. sampler_compare is only compatible with `textureSampleCompare`, `textureSamplerLevelCompare`, and `textureGatherCompare` all if which require a `sampler_comparison`

|                              | `sampler`             | `sampler_comparison` |
| ---------------------------- | --------------------- | -------------------- |
| `textureSample`              |        ok             | compile error        |
| `textureSampleBias`          |        ok             | compile error        |
| `textureSampleGrad`          |        ok             | compile error        |
| `textureSampleLevel`         |        ok             | compile error        |
| `textureSampleCompare`       | compiler error        | ok                   |
| `textureSampleLevelCompare`  | compiler error        | ok                   |
| `textureGather`              |        ok             | compile error        |
| `textureGatherCompare`       | compiler error        | ok                   |

> The texture bound to sampler must be a depth texture, or results are undefined.

This is validated, only `texture_depth_??` can be used with a `textureXXCompare` function

> If a non-shadow texture call is made to a sampler that represents a depth texture with depth comparisons turned on, then results are undefined. 

This case is a WGSL error. You can't use `sampler_comparison` with a non-shadow texture call

> If a shadow texture call is made to a sampler that represents a depth texture with depth
comparisons turned off, then results are undefined.

This case is validated out. A shadow texture call (`textureXXXCompare`) requires a `sampler_comparison`

> If a shadow texture call is made to a sampler that does not represent a depth texture, then results are undefined.

This case is validated out. A shadow texture call (`textureXXXCompare`) requires a `texture_depth_??`

**Comment by teoxoy** [comment]
Currently the spec allows usage of non-filtering samplers with `texture_depth_*`. Example:

```wgsl
@must_use fn textureSample(t: texture_depth_2d,
                           s: sampler,
                           coords: vec2<f32>) -> f32
```

As far as I understand that's not possible in GL.

**Comment by greggman** [comment]
Which part of the OpenGL spec above forbids that?

> If a non-shadow texture call is made to a sampler that represents a depth texture with depth comparisons turned on, then results are undefined.

a non-shadow texture call (your example) can't be made with "depth comparisons turned on". you can only pass `sampler` to `textureSample` so comparisons are not turned on.

**Comment by greggman** [comment]
Ok, I found the place that forbids it here

> ## OpenGL ES 3.1 section 11.1.3.5 Texture Access
>
> These requests must be consistent; the results of a texture lookup are undefined if any of the following conditions are true:
> * The sampler used in a texture lookup function is not one of the shadow sampler types, the texture object’s base internal format is `DEPTH_COMPONENT`
or `DEPTH_STENCIL`, and the TEXTURE_COMPARE_MODE is not `NONE`.
> * The sampler used in a texture lookup function is one of the shadow sampler types, the texture object’s base internal format is `DEPTH_COMPONENT` or `DEPTH_STENCIL`, and the `TEXTURE_COMPARE_MODE` is `NONE`.
> * The sampler used in a texture lookup function is one of the shadow sampler types, and the texture object’s base internal format is not `DEPTH_COMPONENT` or `DEPTH_STENCIL`.
> * The sampler used in a texture lookup function is one of the shadow sampler types, the texture object’s internal format is `DEPTH_STENCIL`, and the `DEPTH_STENCIL_TEXTURE_MODE` is not `DEPTH_COMPONENT`.

**Comment by teoxoy** [comment]
> Which part of the OpenGL spec above forbids that?
> 
> > If a non-shadow texture call is made to a sampler that represents a depth texture with depth comparisons turned on, then results are undefined.
> 
> a non-shadow texture call (your example) can't be made with "depth comparisons turned on". you can only pass `sampler` to `textureSample` so comparisons are not turned on.

It seemed to me that all sampling functions that accept `sampler*Shadow` expect a depth reference either as a separate argument or as the last component in the `P` vector in the GLSL spec. So I thought all `sampler*Shadow` need to have depth comparisons turned on.

> The results of a texture lookup are undefined if any of the following conditions are true:
>
> - The sampler used in a texture lookup function is one of the shadow sampler types, the texture object’s base internal format is `DEPTH_COMPONENT` or `DEPTH_STENCIL`, and the `TEXTURE_COMPARE_MODE` is `NONE`.

Good find!

**Comment by kainino0x** [comment]
> * → **The sampler used in a texture lookup function is one of the shadow sampler types, the texture object’s base internal format is `DEPTH_COMPONENT` or `DEPTH_STENCIL`, and the `TEXTURE_COMPARE_MODE` is `NONE`.**

I believe this is saying: if you sample using a shadow sampler, but you forget to `glTexParameter(target, GL_TEXTURE_COMPARE_MODE, GL_COMPARE_REF_TO_TEXTURE)`, that's UB. (and vice versa for non-shadow samplers)

In practice what that means is you can't use both a shadow sampler _and_ a non-shadow sampler with a texture inside the same draw call.

> > If a non-shadow texture call is made to a sampler that represents a depth texture with depth comparisons turned on, then results are undefined.
> 
> This case is a WGSL error. You can't use `sampler_comparison` with a non-shadow texture call
> 
> > If a shadow texture call is made to a sampler that represents a depth texture with depth
> > comparisons turned off, then results are undefined.
> 
> This case is validated out. A shadow texture call (`textureXXXCompare`) requires a `sampler_comparison`

I believe these two sentences are also saying the same thing - talking about the texture parameters.

**Comment by teoxoy** [comment]
> > * → **The sampler used in a texture lookup function is one of the shadow sampler types, the texture object’s base internal format is `DEPTH_COMPONENT` or `DEPTH_STENCIL`, and the `TEXTURE_COMPARE_MODE` is `NONE`.**
> 
> I believe this is saying: if you sample using a shadow sampler, but you forget to `glTexParameter(target, GL_TEXTURE_COMPARE_MODE, GL_COMPARE_REF_TO_TEXTURE)`, that's UB. (and vice versa for non-shadow samplers)
> 
> In practice what that means is you can't use both a shadow sampler _and_ a non-shadow sampler with a texture inside the same draw call.

I think this is fine actually, `TEXTURE_COMPARE_MODE` can be set on the sampler as well and the spec says:

> If a sampler object and a texture object are simultaneously bound to the same texture unit, then the sampling state for that unit is taken from the sampler object (seesection 8.2).

**Comment by greggman** [comment]
I want to confirm that we decided to "Disallow usage of depth textures with non-compare sampling functions" in compat

I ask because I see that case failing for `texureGather(texture_depth_xxx)` in our compat implementation and disallowing it would solve the issue.

**Comment by kainino0x** [comment]
> > If a sampler object and a texture object are simultaneously bound to the same texture unit, then the sampling state for that unit is taken from the sampler object (seesection 8.2).

Ahh, that's great, and makes sense. I've well and truly forgotten how separate sampler/texture objects worked in ES 3.

**Comment by kainino0x** [comment]
> I want to confirm that we decided to "Disallow usage of depth textures with non-compare sampling functions" in compat

That was my understanding of the meeting. (but again I am a bit out of my depth)

**Comment by teoxoy** [comment]
> > > If a sampler object and a texture object are simultaneously bound to the same texture unit, then the sampling state for that unit is taken from the sampler object (seesection 8.2).
> 
> Ahh, that's great, and makes sense. Seems I've well and truly forgotten how OpenGL ES 3 / WebGL 2's separate sampler/texture objects work.

Coming from the newer APIs it is confusing especially that those settings have the same name for both textures and samplers.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-11-20#compat-disallow-usage-of-depth-textures-with-non-compare-sampling-functions-4970">GPU Web WG 2024-11-20 Atlantic-time</a></summary>

* TT: Kai also mentioned it's even more general than this. If you want 2 bindings, one doing sampler comparison and one with normal sampling, can't have that either.
* KN: said that yesterday, but realized that we can't do that anyway. We're binding a combined sampler/texture anyway (I think). Think there's no problem here. Already a rule that says, each texture can only be used with 1 sampler for this reason.
* CW / GT: right.
* CW: it's actually that you can't use multiple different views of a texture in the same draw/dispatch.
* SW: issue #935 (?) in the proposal.
* CW: could we bind the "compare" version of the sampler instead?
* SW: we do have placeholder samplers we bind. Think this might work.
* GT: the failing tests are not failing because of udnefined behavior. I gave an example - if you use textureSample and generate GLSL for it, it's undefined behavior per the spec.
* SW: I need to look at this more. Revisit later?
* KN: my understanding - you use comparison sampler but don't set comparison mode on the texture, and vice versa, it doesn't work.
* KG: and there's no way to combine the texture/sampler differently in 2 different places. ES 3.0, you can't allow using textureSample on a depth texture sampler, if you also used it in the same draw call with a different sampler.
* CW: because it's a texture parameter.
* GT: different problem. Issue is that it doesn't work with even one sampler.
* KN: isn't that because you haven't updated the texture parameter?
* GT: you have sampler2DShadow, if not set to compare, it's undefined behavior.
* KG: saying you can't generate a bindgroup with both of those.
* GT: we have tests that do this.
* KG: GLES spec says you can't rely on that.
* GT: correct. GLES spec says it can't be used. WebGPU spec says it can be used.
* KG: agree that we have to make a spec change.
* KN: I was wrong, thought we had a restriction that we don't have.
* SW: we need to prevent - if we don't already - (does the aspect handle this?) - 
* KG: if you think impls can handle this internally, interested to see.
* SW: 2 binding points can't do different things.
* GT: the issue doesn't require 2 samplers. It only requires one.
* KG: right now you can have 1 shadow sampler, can call textureSample on it and textureShadowSample on it. No way to implement that in GLES.
* KN: in WGSL those are 2 different sampler types.
* KG: can call textureSample on a depth texture today. Remove that in Compat?
* SW: sounds like something we need to forbid in the shader.
* KG: yes, in Compat you wouldn't have overloads that take texture_depth. Get rid of half the overloads.
* SW: or, allow only one in a shader.
* KG: goes against the intent of the spec.
* KN: seems similar to what we do for filtering.
* CW: in Compat - is it true you can bind a depth texture to texture_2d, f32?
* GT: yes. As long as you mark it NEAREST filtering.
* SW: NEAREST applies to Core too.
* CW: for this reason - think we can say, texture_depth, you can't use textureSample on it any more. If you need to, you can bind it as a texture_2d, f32.
* (nods all around)
* CW: I vote for the simple solution, remove the overload. Decide at shader creation / bind group layout time.
* SW: that's when you set the GL state on the texture to one or the other?
* CW: yes.
* KN: have to do that lazily, at draw calls.
* SW: but it's the type of binding you use to know which mode to use.
* KN: this is fine, think both impls are possible. Let's do the simpler thing and see what happens. If apps don't port easily, we can reconsider and do something more advanced.
* CW: any concerns?
* (none)
* CW: OK, let's go in this direction. Resolve this issue.

</details>
