### ISSUE TITLE
Does WGSL intentionally permit duplicate global diagnostic filters?

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#4976]
Is it really intentional that multiple global diagnostic directives with the same triggering rule are permitted atop a WGSL module?

In the WGSL spec, I can see that:

- [§4.2. Global Diagnostic Filter](https://gpuweb.github.io/gpuweb/wgsl/#global-diagnostic-directive) does not mention anything about forbidding duplicates.

- [§11.6. diagnostic](https://gpuweb.github.io/gpuweb/wgsl/#diagnostic-attr) does forbid duplicates, but specifically refers to "diagnostic attributes", which would seem to exclude global directives.

Maybe I'm just not seeing the rationale, or I haven't found the discussion, but it seems weird to me that duplicates would be tolerated in one place but forbidden in the other. Because of the way the spec is structured, I think there's some chance this was just an oversight.

**Comment by alan-baker** [comment]
Generally directives can be duplicated (I believe) under the assumption that it is easier for code generators (in JS for example) to just append them together without trying to de-duplicate because they are required at the start of the shader. For example, enable directives can be duplicated. That aspect seems unnecessary for attributes.

**Comment by dneto0** [comment]
That's my thinking too.

Tint does allow duplicate global diagnostic filters if they don't conflict.

That said, [Diagnostic filtering](https://gpuweb.github.io/gpuweb/wgsl/#diagnostic-filtering) ends with a definition of 'nearest enclosing diagnostic filter' and asserts:

> Because affected ranges nest, the nearest enclosing diagnostic is unique, or does not exist.

That's not quite right. You can have truly duplicate global filters; they "nest" each other.

**Comment by jimblandy** [comment]
Okay, I'm satisfied. We can close this. We might want to consider a note somewhere, since it seemed inconsistent and potentially accidental to me.

**Comment by dneto0** [comment]
@jrprice pointed out:

> This test covers conflicting diagnostic directives:
https://github.com/gpuweb/cts/tree/327fb7b053d9667904ac45b8e5d33d6e6392b023/src/webgpu/shader/validation/parse/diagnostic.spec.ts#L153-L162

> It checks that conflicting diagnostic directives are allowed only when their severities are the same.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐11‐19-Minutes#does-wgsl-intentionally-permit-duplicate-global-diagnostic-filters--issue-4976">WGSL 2024-11-19 Minutes</a></summary>

* Milestone?
* JB : Happy to close this, since my q was answered. No action necessary.
* **Resolved: Closed**

</details>
