### ISSUE TITLE
Can depth24plus/depth24plus-stencil8 array texture be sampled

### ISSUE THREAD

**Issue by coding-001** [gpuweb/gpuweb#499]
It's very useful for shadow map.
```
const depthTexture = device.createTexture({
  size: {
    width: 1024,
    height: 1024,
    depth: 1,
  },
  format: 'depth24plus',
  arrayLayerCount: 4,
  usage: GPUTextureUsage.OUTPUT_ATTACHMENT | GPUTextureUsage.SAMPLED,
});
commandEncoder.beginRenderPass({
  colorAttachments: [{
    attachment: undefined,
    loadValue: [1, 1, 1, 1],
  }],
  depthStencilAttachment: {
    attachment: depthTexture.createView({
      arrayLayerCount: 1,
      baseArrayLayer: index,
      dimension: '2d',
    }),
    depthLoadValue: 1.0,
    depthStoreOp: 'store',
    stencilLoadValue: 0,
    stencilStoreOp: 'store',
  },
});
```

**Comment by kvark** [comment]
Yes, it should be sample-able. What makes you ask? Does it not work in some implementation?

**Comment by Kangz** [comment]
It definitely doesn't work in Chromium's implementation. But also I'm not sure WebGPU has enough to make it work at the moment. We don't have a way to express `shadowSampler2D` as a `GPUBindGroupLayoutBinding`: `GPUTextureComponentType.Float` is probably not enough because it doesn't encode the `shadow` part of `shadowSampler2D`. I think this warrants further investigation in this group on how to make depth-sampling work.

**Comment by kvark** [comment]
@Kangz I don't understand your concern (yet). From the point of view of the shader, it's just a 2D array texture, like any other texture, of type `GPUTextureComponentType.Float`. The texture binding point doesn't need to know about comparison sampling - that's the responsibility of the sampler object that is bound separately.

**Comment by Kangz** [comment]
Nevermind, coming from an OpenGL and GLSL background, I thought depth textures needed to have a specific type to be able to be used for `SampleCmp`. I think the only format that may be sampleable is `depth32float` since it is the only depth format guaranteed sampleable in Vulkan (and D16_UNORM but we don't have that).

So we'd need to add validation rules that the other formats aren't sampleable, and in Dawn / Chromium we should implement sampling of "depth32float" which produces a validation error at the moment.

**Comment by kvark** [comment]
So theoretically we may see a platform where there is no depth format that is both sample-able and renderable (to match our Depth24Plus requested with the appropriate usage flags), but I don't think it's a realistic scenario to expect, although more investigation/stat-gathering is needed.

Anyway, this starts to fall into a general "what can a format do" question that we need to keep clarifying in the spec and investigations. There are no concerns around "array" part here as far as I can see.

**Comment by coding-001** [comment]
@Kangz Thanks a lot. Workaround: use 'r16float' color attachment texture, write z to it.
```
this.shadowTexture = this.device.createTexture({
  size: {
    width: this.width,
    height: this.height,
    depth: 1,
  },
  format: 'r16float',
  // eslint-disable-next-line no-bitwise
  usage: GPUTextureUsage.OUTPUT_ATTACHMENT | GPUTextureUsage.SAMPLED,
  arrayLayerCount: cascadedCount,
});
```

```
layout(location = 0) out float fragColor;

void main () {
  fragColor = gl_FragCoord.z;
}
```

**Comment by anuding** [comment]
> @Kangz Thanks a lot. Workaround: use 'r16float' color attachment texture, write z to it.
> 
> ```
> this.shadowTexture = this.device.createTexture({
>   size: {
>     width: this.width,
>     height: this.height,
>     depth: 1,
>   },
>   format: 'r16float',
>   // eslint-disable-next-line no-bitwise
>   usage: GPUTextureUsage.OUTPUT_ATTACHMENT | GPUTextureUsage.SAMPLED,
>   arrayLayerCount: cascadedCount,
> });
> ```
> 
> ```
> layout(location = 0) out float fragColor;
> 
> void main () {
>   fragColor = gl_FragCoord.z;
> }
> ```

seems not working now,  it says "The format of the texture view used as depth stencil attachment is not a depth stencil format",  any ideas?

**Comment by Kangz** [comment]
We haven't implement it in Chromium yet.

**Comment by anuding** [comment]
oh, I know what coding-001's Workaround is: 
The "shadowTexture" is a color attachment with only z write into it, not a depth-stencil attachment. This adds one more draw call to render depth texture. I didn't see it clearly before, sorry.
