### ISSUE TITLE
Shaders transpilation to Metal.

### ISSUE THREAD

**Issue by AdamRobertsEF** [gpuweb/gpuweb#5]
Metal has an advantage that it runs on both the GPU and CPU, giving a performance edge.

If GPUWeb transpilated non-metal shaders into Metal on the client; there would be a performance increase. Another option is a development tool, that can convert any shader language to Metal, the second option would be my preference, as it wouldn't give any performance hit to the client.

**Comment by othermaciej** [comment]
Probably the final shader language won't be Metal Shader Language. Whatever is chosen will probably be transpired to whatever is the native shader language for the API in question, just as ANGLE translates OpenGL shader language. However, this is more of an implementation issue than an issue for the spec.

**Comment by AdamRobertsEF** [comment]
If Apple open sourced Metal, it could be the final shader language. That would be faster than Apple porting it to Windows, Linux, and Android. Plus, it would make Metal be adopted faster, across iOS and Mac, and increase the number of games ported to Mac.

It's not essential, purely optimisation. JIT shader translation to the fastest API on the target machine would work well also.

**Comment by grorg** [comment]
Metal Shading Language is C++11 with some defined annotations. If we exposed that to the Web, the validation would be quite difficult. For one thing, we'd have to disallow pointer arithmetic, or work out a way to constrain it. Probably not impossible, but tricky.

As for the benefit of CPU and GPU support, it definitely helps that you can `#include` your Metal headers in your C++ code. But I don't see how that helps on the Web (other than cross compilation). Instead, if the shader can expose any parameters/structures to JavaScript via an API, the implementation can create its own JS classes to wrap the shader structures.

**Comment by AdamRobertsEF** [comment]
How about this process:

Browser implements Metal.Framework
Javascript code calls a browser function to initialize shader and passes it the shader type and shader.
Browser passes this to Metal Framework
If the shader isn't a Metal shader the Metal Framework converts shader into a Metal shader. — Metal.Framework JIT compiles the shader and passes a CALayer back to the browser, along with any parameters/structures that are to be used for manipulating the shader.

Equivalent implementations in other desktop and mobile OS's.

**Comment by grorg** [comment]
We can't requite a Metal implementation, since it is only available on macOS and iOS devices.

I'm not sure I understand your proposal, but I think that much of what you suggest is available today with various shader translation tools. Google's prototype implementation accepted SPIR-V and used an open source tool to convert that into Metal Shading Language.

So, if we split your suggestion into two parts, we get:

1. require the use of a shading language that can be converted into different platform shading languages
2. use Metal Shading Language

I believe everyone agrees with 1. It's an absolute requirement.

But we are nowhere near part 2 yet. There is a chance that the community would be happy with a C++ form language, and maybe MSL is acceptable. C++ has the benefit of being a well-known language, but the downside of being a huge language (templates, operator overloading, etc). This would require all browsers to include a C++ compiler, like clang+llvm. And then there is validation of shader content.

So I think it's much more likely that the community will agree on an IR of some form, that can be generated from whatever language the application wants, and translated to the system shading language.

I'm going to close this issue for the moment, but we'll consider it a vote for MSL and appreciate the request. We can keep the discussion going, but I think we need to gather shading language requirements first.
