### ISSUE TITLE
What's the best way to clear buffer used only be GPU

### ISSUE THREAD

**Issue by coding-001** [gpuweb/gpuweb#531]
This buffer is only used by GPU in two compute pass:
pass A writes data to it, pass B reads data.
I want to clear this buffer to zero before pass A in every frame, what's the best way?

**Comment by Kangz** [comment]
The best way to do this at the moment is to use a compute shader, or to have do a copy from an already zeroed out buffer.

**Comment by coding-001** [comment]
@Kangz Thanks a lot.

**Comment by kvark** [comment]
@Kangz I think there is a room for discussion here. Clearing a buffer is something many people would need to do. Metal doesn't have facilities, but Vulkan has `vkCmdFillBuffer` and DX12 has `ClearUnorderedAccessViewUint` (which admittedly comes with limitations). Overall, it sounds like it should go into "want something, but can't figure out how" bin.

**Comment by Kangz** [comment]
Agreed that filling buffer is something we might want in the API but this issue seemed to be asking about what's in the API at this point. Agreed with having a bin for such things, I'm not sure what it would live though. Maybe a meta issue?

**Comment by coding-001** [comment]
I can live with buffer copy(yes, you need two buffers, what a waste).
BTW, how to clear buffer in compute shader?
Something like this?
https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/computecullandlod/cull.comp#L86

**Comment by magcius** [comment]
You shouldn't need atomics. If you have a thread group size of 32, then you'd want something like: `for (int i = 0; i < bufferSize; i += 32) buffer[SV_DispatchThreadID + i] = 0;`

**Comment by kvark** [comment]
Code from our implementation of `vkCmdFilBuffer` - https://github.com/gfx-rs/gfx/blob/f999b5295ca30dc38f33b0a4770a31d50138687c/src/backend/metal/shaders/fill.metal#L14

**Comment by coding-001** [comment]
@magcius @kvark Thanks a lot. So I need another compute shader to clear buffer(I'm thinking do it in PassA, but seems like it isn't possible for my case, I think the atomic is used to make sure it is zeroed before any writing):
Pass 0(Clear) -> Pass A(Write) -> Pass B(Read)

**Comment by jeremyong** [comment]
I randomly found this issue searching for something completely different, but figured I'd leave a comment in case it's useful for anyone. A common pattern is that you have a shader that performs some computation, expected zeroed data which is used as scratch. The key is that this shader can finish its work _and then re-zero_ the data afterwards. In other words, after the initial zero-initialization, you'd simply dispatch your compute shader or whatnot every frame, it would use the zeroed scratch buffer, then publish the results elsewhere while also cleaning up the scratch space. As for the initial zeroing, it's worth mentioning that in the case of D3D12, committed resources or newly allocated pages are zero-initialized unless you pass the `D3D12_HEAP_FLAG_CREATE_NOT_ZEROED` flag, in which case the page _might_ not be zeroed in the event the memory was used by a different process. Beyond that and the `ClearUnorderedAccessViewUint` method already mentioned, the most common approach for the initial zero initialization of the buffer is to use a compute shader. The main takeaway though is that usually you can structure your code so that the "zeroing" part doesn't happen each frame as a dedicated clear (which imposes additional barriers/bubbles in your pipeline).
