### ISSUE TITLE
Write-only storages?

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#542]
Something that came out of #541 discussion by the editors, it would be interesting to explore the need for write-only usage flags and binding types for texture/buffer storages. Here are the reasons for it:
  - As #513 investigation shows (thanks @Jiawei-Shao!), the write-only use case has lower hardware requirements than read-write, at least on D3D12 and Metal.
  - SPIR-V already has [separate decorators](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_a_id_access_qualifier_a_access_qualifier) for `NonWritable` and `NonReadable` storage resources. Metal shading language also has [write access](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) that is separate from `read_write`.
  - on the API side, at least in D3D12 there is a clear separation with write access requiring an UAV (unordered access view), while read access requiring and SRV (shader resource view).
  - `STORAGE_READ` and `STORAGE_WRITE` would be cleaner than `READONLY_STORAGE` and `STORAGE`, also more in line with existing `MAP_READ` and `MAP_WRITE`

If we go for it, we'd need to consider both `STORAGE_WRITE` usage flags and `writeonly-storage-buffer`/`writeonly-storage-texture` binding types.

**Comment by Kangz** [comment]
I'm worried about the explosion of enums because going this route we'll eventually have the following binding types:

  - `readonly-storage-texture`
  - `writeonly-storage-texture`
  - `readwrite-storage-texture`
  - `readonly-storage-buffer`
  - `writeonly-storage-buffer`
  - `readwrite-storage-buffer`

Along with corresponding usages. Wouldn't it be simpler to say that for both textures and buffers:

 - `GPUXUsage.STORAGE` usage implies `GPUXUsageSTORAGE_READ`
 - The binding points are are `readonly-storage-X` and `storage-X`
 - In vanilla WebGPU we require that `storage-texture` bindings be annotated with `writeonly` but that restriction will be lifted in an extension, allowing for true storage textures?

**Comment by kvark** [comment]
I'm not worried about the binding types, tbh, we already have a few dimensions they can differ. Adding something like `access` isn't drastically changing the picture:
```webidl
enum GPUStorageAccess {
  "none",
  "read",
  "write",
  "read-write"
}

dictionary GPUBindGroupLayoutBinding {
    required unsigned long binding;
    required GPUShaderStageFlags visibility;
    required GPUBindingType type;
    GPUTextureViewDimension textureDimension = "2d";
    GPUTextureComponentType textureComponentType
 = "float";
    GPUStorageAccess storageAccess = "none"; // <--- look here
    boolean multisampled = false;
    boolean hasDynamicOffset = false;
};
```

Storage resources are tricky, racey, and there is no intent to make them look like they are a piece of cake.

> In vanilla WebGPU we require that storage-texture bindings be annotated with writeonly but that restriction will be lifted in an extension, allowing for true storage textures?

If we do this, we'd be cutting off an ability to have write-only texture storages once the extension is on. That doesn't sound good, am I misunderstanding your idea?

**Comment by Kangz** [comment]
> If we do this, we'd be cutting off an ability to have write-only texture storages once the extension is on.

The texture being used write-only is a property of the shader and not required for:

 1. The creation usage because a writable texture in the driver is always also readable. (even in D3D12 that has a difference between SRV and UAV, a UAV texture is free to also have as SRV [citation needed]).
 1. The barriers generated in the implementation: writes need to be ordered after previous reads or writes, so barriers are the same as what's needed for read-write.
 1. Point 2) shows that the `GPUBindGroupLayout` doesn't need to make the difference between `writeonly` and `readwrite`

**Comment by kvark** [comment]
Note that this happened for textures already.

**Comment by Kangz** [comment]
In the light of #745 maybe it makes sense to have all six combinations of `[read-|write-|]storage-[texture|buffer]`.

**Comment by kvark** [comment]
I think we can close this. The only unclear bit is whether write-only buffer storage bindings make sense, and I think the case for this is fairly weak.
