### ISSUE TITLE
Zero-sized buffers?

### ISSUE THREAD

**Issue by bbernhar** [gpuweb/gpuweb#546]
Is it legal to create a zero-sized buffer? For example, what is the expected result of `bufferDesc.size = 0`?

Note: D3D12 does not allow "zero-sized" buffers and Vulkan seems driver-specific (may reject). Not certain of Metal. IIRC, WebGL validates for non-zero sizes at creation-time.

**Comment by kainino0x** [comment]
background: On any backend that doesn't support it (probably all of them), we'd need to fake it: don't actually create an object in the backing API, and then validate that it's never actually used. If there are places we would need to provide the object to the API (not sure, since it wouldn't be valid to actually use it anyway), we could provide some dummy object that we hold onto globally in the backend.

**Comment by kvark** [comment]
To add to that answer: in general, we are forced to have the *actual* buffer size being larger in some cases than the requested size. For example, a mappable buffer that happens to be placed in non-coherent memory needs to be rounded up to the non-coherent atom size (in Vulkan) anyway.

With this context, having one more case where we'd do that (if the requested size is 0) doesn't change anything drastically, so my preference would be to handle that internally instead of forbidding it.

**Comment by Kangz** [comment]
[We talked about zero-sized resources briefly at the New Orleans F2F](https://docs.google.com/document/d/1HD-9cKjuQDqOoi5rQ8oLCfuw2AHJR-3BC8IeLziKnuY/edit#bookmark=id.o3bm2fys1i6a) but didn't reach a strong consensus. I think it's fine to have 0-size buffers, however 0-sized texture is a bit more difficult to reason about.

**Comment by litherum** [comment]
Clamping for OOB accesses doesn't work for zero-sized buffers.

**Comment by Kangz** [comment]
Unfortunately I think we are going to have to do validation for the size of buffers on draw/dispatch :(. What should happen when you use 64k of a UBO in a shader but bind a 4byte range of a buffer? We could maybe clamp memory on each access, but I worry this will have a large GPU execution cost, and would prevent drivers from generating instructions that load 16bytes of memory at once.

**Comment by kvark** [comment]
Is clamping advantageous over zeroing? If we mask what we load based on the index, the driver could still be able to load the larger (i.e. 16 bytes) chunks from the buffer.

**Comment by kainino0x** [comment]
> Clamping for OOB accesses doesn't work for zero-sized buffers.

Zero sized buffers can't even be created in some backends. I think we'd stub them out with small nonzero-sized buffers and that would allow clamping if you can clamp at the necessary granularity.

I agree the problem of UBOs being too large for their bindings (which still affects zero-sized or fake-zero-sized buffers) is more of a concern.

**Comment by kvark** [comment]
Discussed this with the editors. We think it's fine to have zero-sized buffers, since the implementation can simply create a backing buffer that's larger (and it needs to do so in general), and you can see valid use cases for this.

For zero-sized bindings, an investigation is needed to see:
  - whether zero sizes are allowed, in which backends
  - what alignment/minimum size requirements are in the backends
  - whether there are operations that don't rely on the range at all, i.e. getting the size of the buffer from the shader.

**Comment by kainino0x** [comment]
One general issue with buffers that we round-up in size: If WGSL has a way to check the size of dynamically-sized buffer bindings (OpArrayLength, I think), we want to return the actual buffer size and not the rounded-up buffer size.

**Comment by kvark** [comment]
@kainino0x 
I raised that concern on the editor call, but now looking at the [spec](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpArrayLength) I'm not seeing it explicitly stated that the length is computed from the buffer size. I'd assume it to consider the range of the binding instead, i.e. [VkDescriptorBufferInfo.range](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDescriptorBufferInfo.html) passed to `vkUpdateDescriptorSets`.

**Comment by kainino0x** [comment]
That's a good point, and I think you're right.
It's probably a non-issue if we can pass un-rounded binding ranges to Vulkan.
(Metal, and possibly D3D12, require us to feed this data in ourselves anyway, so it's a non issue there.)

**Comment by kvark** [comment]
@litherum @RafaelCintron any concerns with moving forward with this?
It wasn't clear if everybody agreed on supporting the zero-sized buffers (independently of zero-sized bindings, which we still need to discuss).
Note the use case I described in https://github.com/gpuweb/gpuweb/issues/686#issuecomment-613071621 kind of requires both.

**Comment by Kangz** [comment]
This was discussed in the [2020-04-13 meeting](https://docs.google.com/document/d/1U2KOkl1azfnmqhdhqMdyVNPD_3glYh61cw8lZu-8RpU/).

**Comment by Kangz** [comment]
This was discussed in the [2020-05-19 meeting](https://docs.google.com/document/d/1HhovwbdGT6jqNd0GdFgbLn1HUcPzNSRibLv9euLMOhA). Conclusion is:

> CW: do we want 0 sized buffers or do we still need to discuss them.
> JG: I'd like to have them and if they're onerous, remove them.
> MM: agreed.

So I think we can close this with consensus that we want 0-sized buffers, unless we later decided they cause too many problems.
