### ISSUE TITLE
[wgsl] Consider a preprocessor

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#568]
It is common practice for WebGL content to use the GLSL preprocessor to specialize a shader. Given that WGSL doesn't have to support any existing content, it seems conceivable that we could design a preprocessor which doesn't have as many shortcomings as other preprocessors.

**Comment by Joshua-Ashton** [comment]
Specialization constants would be a better idea.

**Comment by litherum** [comment]
I made an investigation [here](https://github.com/gpuweb/WSL/issues/1)

**Comment by nicebyte** [comment]
wouldn't that be counterproductive to the goal of being _trivially_ convertible to spir-v?

**Comment by litherum** [comment]
I suppose it depends how trivial the preprocessor is 😄

**Comment by nicebyte** [comment]
i was alluding to the idea that a preprocessor/macro system that is not rife with footguns is necessarily non-trivial :)

**Comment by Kangz** [comment]
Do we have examples of well-known preprocessor apart from the C / GLSL preprocessor? That's the only one I know of, and I had to fix at least a dozen issues in ANGLE's GLSL preprocessor after I started fuzzzing it. The problem with the preprocessor is that it works at the tokenization level which adds a lot of complexity to the spec and implementation.

Instead, maybe we could let developers handle preprocessing themselves, it's not too hard to write a basic string preprocessor if you know your usecase ([here's a simple one I wrote](https://github.com/Kangz/WebGLFluid/blob/master/lib/glExtras.js#L53) to have a form of `#include`). Babylon.js already does [their own preprocessing](https://github.com/BabylonJS/Babylon.js/tree/master/src/Engines/Processors) of GLSL before giving it to WebGL (example of a [shader](https://github.com/BabylonJS/Babylon.js/blob/master/src/Shaders/pbr.fragment.fx)).

However to support developers making their own preprocessor I think it might be useful to have the equivalents of `#line` and `__LINE__`, and maybe a `#file` so that compilation error locations are reported faithfully.

**Comment by dj2** [comment]
@litherum from the investigation link, it sounded like specialization constants was the way to go? Are you suggesting a preprocessor because HLSL doesn't have specialization constants?

**Comment by litherum** [comment]
I’m just suggesting a preprocessor because one has already been proven valuable in GLSL on the web. Existing widespread prevalence of a feature is evidence it’s worth considering.

**Comment by dj2** [comment]
I guess I'd have few questions to that:

1- is it used because it's there? like, if it wasn't there would it be getting requested?
2- is it used because non-web shaders used it?
3- are there better ways to do it in the web environment?  As @kangz pointed out doing this in JS maybe a better level to do it and then pass the processed shader to WebGPU.

My initial reaction would be to hold off on any kind of preprocessor until we've got running WGSL code in the browser and we can see how people are using it. Then we can figure out if the right place for it is in JS as a module or in WGSL as a builtin.

**Comment by magcius** [comment]
GLSL's preprocessor is a bit bizarre. It doesn't support any advanced C preprocessor techniques, like token pasting, it's pretty limited to basically `#define` and `#ifdef`. Even the `#if defined()` syntax is not supported. And there's no way to specify defines to the compiler, outside of string concat `#define`.

But since the `#version 300 es` declaration must come first, and I believe extensions must come first (for WebGL 2), shader compilation pipelines have to be very particular about their string concatenation. At that point, it's more useful to write your preprocessor toolchain.

Not to mention bugs in implementations. For instance, it's illegal to have `attribute` in pixel shaders, so it might be tempting to do `#ifdef FRAGMENT_SHADER   attribute foo;  #endif`, but this breaks on several Android implementations.

I have found it extremely minimally useful.

**Comment by othermaciej** [comment]
Could ifdefs be sufficiently supported by optimizing if statements ar compile time? I guess the main shortcoming is that you can’t have an if statement outside a function body.

Various languages have more sophisticated macro systems than the C preprocessor, for example Scheme’s hygienic macro facility. But these are harder to apply to C-sequel languages.

**Comment by dj2** [comment]
If the basic preprocessing is all moved up to JS we just need to support a few things like #line directives which makes the whole thing a lot simpler.

**Comment by Joshua-Ashton** [comment]
I don't see why a preprocessor has to be a part of the language at all. The user can implement their own preprocessor in JS and #line or whatever can be put in on their end using some form of comment. If you're wanting to be "bijective" to SPIR-V then it's best not to tack on features that are not representable in SPIR-V.

> Could ifdefs be sufficiently supported by optimizing if statements ar compile time? I guess the main shortcoming is that you can’t have an if statement outside a function body.

Yes, branches that are always true/false will get optimized away everywhere that has a Vulkan driver. (see: spec constants)

> Not to mention bugs in implementations. For instance, it's illegal to have attribute in pixel shaders, so it might be tempting to do #ifdef FRAGMENT_SHADER attribute foo; #endif, but this breaks on several Android implementations.

Hence why parsing source code is hard and you should take in a bytecode representation... Adding a preprocessor on top really does not help at all.

**Comment by litherum** [comment]
The next step in this issue is probably for someone (perhaps me? volunteers welcome) to come up with a proposal for a specific, well-defined preprocessor, so we can debate the merits of a particular preprocessor, rather than debating preprocessors in general.

**Comment by jdashg** [comment]
Proposals welcome, but my preference right now is for no preprocessor. 

Coincidentally, I spent a bunch of time last week dealing with fixing a regression in the goop of Firefox's WebGLSL preprocessor, and adding stricter tests to the WebGL CTS to prevent further regressions here.

**Comment by dneto0** [comment]
This is sugar we don't need.  Do it in a layer above shader ingestion.

One of the reasons Apple (@litherum himself) wanted a text based language was the ease with which shaders could be glued together by the application code.

From https://webkit.org/blog/9528/webgpu-and-wsl-in-safari/ :

> Babylon.js creates these complex shading algorithms by stitching together snippets of shader source code at run-time. This way, Babylon’s shaders are tuned at run-time to the specific type of content the application contains. Since WSL is a textual language like GLSL, this kind of workflow can be accomplished simply with string concatenation.

So go ahead and spec a new "specific, well-defined preprocessor".  But put it in a library function in the web page, not intertwined with shader ingestion.


The WGSL spec currently inherits the specialization-constant mechanism from SPIR-V (and corresponding mechanism in Vulkan).  If WebGPU wants it, it's right there to be used.  If not, we can remove that by policy (no "spec_id" attribute).

**Comment by pjoe** [comment]
Just wanna explain the usecase for a preprocessor, or  any other tech that can help deal with shader variations, seen from a devs PoV:

Even though nowadays we mostly use a single PBR shader (or maybe a few: metallic/specular/unlit/etc.), that one shader has different options like:

- Is it using normal maps? If not, no need to deal with TBN matrix, etc.
- Are tangents present in the vertex data? If not try to generate in the shder
- Is texture X present (albedo, occlusion, roughness, metalness, normal, etc.)? If not, no need to make texture read and following calculations.

Why would you wanna have models without e.g. normal map? Think LoD - if you have a scene with large amount of models you can optimize performance by simplifying the ones furthest away, and that could include dropping textures like normal map.

Another situation is those node based shader editors, like https://nme.babylonjs.com/.

All these options end up resulting in a huge number of combinations of the same shader code, thus requiring many compilations (at least if using a classic preprocessor). Point being: compilation should be fast - or handling of these variations should happen at a later stage somehow.

Anyway just some input 😄

**Comment by Joshua-Ashton** [comment]
All of the problems you described can be solved via. spec constants.

**Comment by grorg** [comment]
Discussed at [2020-03-10 Teleconference](https://docs.google.com/document/d/10yBasmrNdgvvd44KWC5a3ZQGzjJCjUBoqzZdByC_u7Y/)

**Comment by grorg** [comment]
The resolution was to take a "wait and see" approach, encouraging people to write preprocessing tools in JavaScript.

The exception is possibly some language affordance for #line-like directives, in order to have compatible error reporting from transpiled input.

**Comment by pjoe** [comment]
Just for reference, our shader code is full of stuff like:
```glsl
varying vec3 vNormal;
#if !defined(HAS_NORMALS)
    #define NO_NORMALS_WIRE_SOLID
    uniform bool uIsWire;
#endif
#if defined(HAS_TANGENTS) && defined(USE_TANGENTS)
    varying vec3 vTangent;
    varying vec3 vBinormal;
#endif
```

And even `#include` inside `#ifndef`:

```glsl
    #ifndef IS_PICKING_PASS
        float furShadow = furTex.b * vFurShadowFactor + vFurBaseShade;
        gl_FragColor.xyz = gl_FragColor.xyz * vFurShade.xyz * furShadow + vFurSpec * furShadow;
        
        #include <tonemapping_fragment>
    #endif
```

**Comment by litherum** [comment]
> "wait and see" approach

This indicates the issue shouldn't be closed.

**Comment by johnkslang** [comment]
> GLSL's preprocessor is a bit bizarre. It doesn't support any advanced C preprocessor techniques, like token pasting, it's pretty limited to basically #define and #ifdef. Even the #if defined() syntax is not supported. And there's no way to specify defines to the compiler, outside of string concat #define.

Almost all of this entire statement is simply not true.  GLSL's preprocessor is almost the same one in C++, which is uses as the normative reference.  It includes token pasting.

**Comment by johnkslang** [comment]
All these are true:

- Writing real shader code will pretty much demand having a preprocessor.
- The C++ class of preprocessors is notoriously full of portability issues.
- The thing that crosses the API boundary almost by definition cannot have such a thing.

It's just another way of saying the real authoring will occur in existing (or possibly novel HLLs), while what crosses the API boundary will be an IR (either SPIR-V or a text language of similar/equivalent level).

**Comment by Kangz** [comment]
> Almost all of this entire statement is simply not true. GLSL's preprocessor is almost the same one in C++, which is uses as the normative reference. It includes token pasting.

I think the GLSL ES preprocessor which is what's in WebGL doesn't support token-pasting. The GLSL ES spec (all versions) say:

> There are no number sign based operators (e.g. no # or #@), no ## operator, nor is there a sizeof operator.

> It's just another way of saying the real authoring will occur in existing (or possibly novel HLLs), while what crosses the API boundary will be an IR (either SPIR-V or a text language of similar/equivalent level).

+1, and it's likely we're going to have WGSL text-based preprocessors on the application side. That was one of the arguments put forward for having a textual shading language.

**Comment by Kangz** [comment]
Is this ok to close? I think it's clear WGSL will not have a preprocessor, at least not for v1.

**Comment by kdashg** [comment]
I'm going to dare to close this, for this current chapter of the discussion.

**Comment by wrightwriter** [comment]
This is needed so much, it's depressing not having it built in.

**Comment by theb1rd** [comment]
Need file and line directives at the very least, unless there's already some hook to manipulate error reporting? I'm willing to write my own preprocessor but accurate error line reporting is the bare minimum needed.

Production shaders tend to include a lot of utility code, same as in any other language. I'm already knee deep in copy-pasted utility functions and I've barely started on my project.

**Comment by greggman** [comment]
Putting in your own utility snippets is trivial code

```js
const insertSnippets = (wgsl, snippets) => 
    wgsl.replace(/#include\s+"(.*?)"/g, (_, name) => snippets[name]);

const snippets = {
  mult2: `fn mult2(v: f32) -> f32 { return v * 2.0; }`,
  div2: `fn div2(v: f32) -> f32 { return v / 2.0; }`,
};


const wgsl = `
#include "mult2"
#include "div2"

...
`;

console.log(insertSnippets(wgsl, snippets));
```

three.js has been doing this years. 

https://github.com/mrdoob/three.js/blob/e8ad12d2fa4611665713e4a984c5b00374613159/src/renderers/shaders/ShaderLib/meshphysical.glsl.js#L32

And, you're free to make it as simple or as complicated as you want. 

* Want to go fetch the snippets off the net? Change your `insertSnippets` to fetch and cache them. 
* Want it to `import` them? Change it to call `import(url)`. 
* Want it to be recursive? Make it recursive. 
* Want it to happen at build time? Put it in your build process.
* Want it to have a meta-language to do code gen? Add it.
 
It's far better to let you do this then be stuck with something missing the features your particular situation needs.

File and line directives are also something your preprocessor can easily handle on its own. You know what code you put in, translate it back.

Here's an example proof of concept: https://jsgist.org/?src=cb4acc6a854a7176e88af7e6a145130d

**Comment by theb1rd** [comment]
Sure, but the line numbers of error messages will report the location of the error in the preprocessed result, rather than the source file. Hence the need for file and line directives.

I suppose one could save out the preprocessed result for cross-referencing the error messages, but that's a huge pain.

Am I missing something?

**Comment by parasyte** [comment]
I don't think you are necessarily missing anything. @greggman's suggestion is pragmatic [^1] though string interpolation is not powerful enough to address the need for source mapping. You might consider parsing an AST that you inject other AST segments into. That can preserve line and column (and type!) information at every level through the transformation.

[^1]: My interest in this thread is also the "I would rather not write all of this myself" variety _iff_ something else were to come along and make it easy to write dynamic shaders in a way that other developers will be familiar with. A bit of anti-NIH, you might say.

**Comment by theb1rd** [comment]
Is this the thing I would use to make that work?
![image](https://github.com/gpuweb/gpuweb/assets/25933139/49a36341-abd0-442a-ba96-0a4370612fa6)

**Comment by greggman** [comment]
The example I posted maps the error messages back to the the line numbers in the snippet

**Comment by magcius** [comment]
I do think a line/file annotation is a relatively small addition that would make the error reporting flow a lot simpler.

**Comment by theb1rd** [comment]
Thanks greggman, I see how that's working now.

Note to future travelers, GPUDevice.push/popErrorScope() and GPUShaderModule.getCompilationInfo() are the ingredients you need to hook the error message reporting to manipulate the line numbers.

A simple file/line directive would be lot more discoverable than this approach, but this will suffice for me.

**Comment by greggman** [comment]
> I do think a line/file annotation is a relatively small addition that would make the error reporting flow a lot simpler.

I don't think it's needed, nor is it desirable. One reason is, you can lie to the compiler. Now suddenly it spews nonsense about which lines came from where. As it is, it reports on exactly what you gave it which gives you all the tools you need to translate back. You can go to the actual code you passed it, and you can go to your translation, and your translation's translation, etc...  If you've got a pipeline that's HLSL->SpirV->WGSL (some people have this), then you currently have all the tools to need to see errors at the WGSL level, and the SpirV level, and the HLSL level.  If you add line/file annotation, at least one of those levels disappears, possibly 2.

As another precedent, I'm pretty sure neither v8, nor SpiderMonkey, nor JavaScriptCore support source maps. The source map support is all built externally in the browser's devtools. I think the same would be best for WebGPU. Keep the core a "core" and build on top whatever you want.

**Comment by magcius** [comment]
> One reason is, you can lie to the compiler. Now suddenly it spews nonsense about which lines came from where. 

To me, that's like saying you can lie about the object label and call your forward pipeline "Deferred Pipeline", so we should exclude object labels. Yes, the line/file hints are only as helpful as you make them. That's fine.

>  If you've got a pipeline that's HLSL->SpirV->WGSL (some people have this), then you currently have all the tools to need to see errors at the WGSL level, and the SpirV level, and the HLSL level. If you add line/file annotation, at least one of those levels disappears, possibly 2.

That's true, the structured error message data is already much nicer than WebGL. That said, as you've experienced, there's currently a bug causing duplicate error messages to be logged. As much as I'd love to trust that that WebGPU bug will be fixed, I'm coming off of 6 years of experience with WebGL 2 where zero thought was put into the debugging experience, so apologies if I seem a little skeptical. Case in point, there appears to be a sourceMap field in the shader compilation that Dawn completely ignores.

> As another precedent, I'm pretty sure neither v8, nor SpiderMonkey, nor JavaScriptCore support source maps. The source map support is all built externally in the browser's devtools.

v8 appears to support source maps -- that is, if I run `console.log(new Error().stack)`, then I see stack frames from my original files, rather than the bundled version. Without that, I would get `bundle.js:6123423`, and debugging would be unusable. I might be worried about similar cases -- some logging string deep inside Dawn only gives me the line numbers and no structured data back. But if we can guarantee that all such messages come back as structured data, and that we have the ability to suppress their natural output in favor of something we display ourselves, that's fine to me.

**Comment by greggman** [comment]
> > One reason is, you can lie to the compiler. Now suddenly it spews nonsense about which lines came from where.
> 
> To me, that's like saying you can lie about the object label and call your forward pipeline "Deferred Pipeline", so we should exclude object labels. Yes, the line/file hints are only as helpful as you make them. That's fine.

The difference is one is info that's essential (the actual place the error happened). From that you can translate to a line/file. Without that you don't get to where the actual error happened. An analogy would be debugging assembly vs source. You start with assembly (the truth) and you layer on top source level debugging. Same here. With the true info you can get to your fake info. With only your fake info you can't back to the truth.

> 
> > If you've got a pipeline that's HLSL->SpirV->WGSL (some people have this), then you currently have all the tools to need to see errors at the WGSL level, and the SpirV level, and the HLSL level. If you add line/file annotation, at least one of those levels disappears, possibly 2.
> 
> That's true, the structured error message data is already much nicer than WebGL. That said, as you've experienced, there's currently a bug causing duplicate error messages to be logged. As much as I'd love to trust that that WebGPU bug will be fixed, I'm coming off of 6 years of experience with WebGL 2 where zero thought was put into the debugging experience, so apologies if I seem a little skeptical. Case in point, there appears to be a sourceMap field in the shader compilation that Dawn completely ignores.
> 

So by adding more work to their plate you expect them to get more done? You have a solution today (example provided above).

The sourceMap is intentionally ignored. It's put there so there's a standard place to find it if some tool wants to use it. It'd be easy to provide a wrapper that uses it.
