### ISSUE TITLE
Consider adding sugar for familiar loop constructs

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#569]
The `loop { continue { } }` control flow construct of WGSL isn't present in an other language that I know of and makes writing simple loops more verbose than familiar for-loops. We should consider adding sugar for example:

```
for (<init-statement>; <condition-expr>; <continue-statement>) {
    <body-statements>
}
```

could be desugared to

```
{
    <init-statement>
    loop {
        break if <condition-expr>;
        <body-statements>
        continue {
            <continue-statement>;
        }
    }
}
```

**Comment by Triang3l** [comment]
Does the continuation block depend only on values known at the point of initialization, or also on values created in the loop body? If the latter is the case, such sugar would fundamentally increase compilation complexity probably (unless the continuation is just pushed to a stack in an unprocessed way in the beginning of the loop, and will be only inserted and processed in the end).

**Comment by Kangz** [comment]
I believe that the continuation block in the `loop { continue { } }` construct would be able to use variables declared in the `loop { }`. I'm not sure I understand what the increase in complexity would be though.

**Comment by dj2** [comment]
We'd have to be careful here if we also look at Lexical Scoping #559 as the scope for the `init-statement` is different in the two constructs. We'd have to say that the for `init-statement` is scoped to the surrounding block, not the function?

**Comment by Triang3l** [comment]
@Kangz I mean, the general rule, if I understand correctly, is that things **below** in the code depend on things **above** in the code. Yes, this would work like a `#define for(init, break, continue, body)` that just reorders things on source text level — but I think if we start reordering anything at all and visually inverting dependencies for convenience, we're going to open a Pandora's box, eventually creating a preprocessor possibly more complex than the core, adding things like `break`/`continue`/`return` expanding into `if`/`else` just because why not, there's a precedent for breaking SSA, and getting another GLSL in the end that is pain to compile properly across different vendors. It's either nothing or whatever.

**Comment by litherum** [comment]
If we're going to do this, I'd also advocate for `while() { }` and `do { } while()`. Bonus points if we can not have a required semicolon after the do/while loop.

**Comment by dj2** [comment]
I don't think we need `while` or `do while` as those can easily be written with either `for` or `loop` as we have now.

**Comment by othermaciej** [comment]
They could be, but it wouldn't be idiomatic or natural to write them that way. If we have `unless` as syntactic sugar, surely these much more common loop constructs are at least as justified.

**Comment by dj2** [comment]
Adding more constructs just for the sake of having them makes the language larger, and introduces more chances for discrepancies between browsers. Given while and do are easy to write, adding them just adds complexity.

**Comment by litherum** [comment]
I’d be willing to trade unless for do/while.

**Comment by litherum** [comment]
GitHub says `while` is used 387M+ times in code, and `unless` is used 270M+ times in code.

**Comment by othermaciej** [comment]
And [`for` is more popular](https://github.com/search?q=for&type=Code) than either. But all these results are polluted by false positives, showing up in comments or function names.

**Comment by jdashg** [comment]
I think we can talk about the sugaring benefits of `for`, but `while (X) {` is literally `loop { if (!X) break;`, which is IMO totally reasonable.

`for (A; B; C) { D }` is more complicated, including (generally in other languages) two anonymous lexical scopes:
```
{
  A
  loop {
    if (!(B)) break;
    {
      D
    }
    continuing { C }
  }
}
```

That said, the one people'll hit in the first five minutes isn't so bad, though on the verbose side:
```
let x : u32 = 0;
for (let i : i32 = 0; i < 4; i += 1) {
  x += texture(...);
}
```

```
let i : u32 = 0;
let x : u32 = 0;
loop {
  if (i >= 4) break;
  x += texture(...);
  continuing {  i += 1; }
}
```

Not great not terrible. Verbose, but pretty clear. `continuing` is going to be weird, but in this context it's pretty clear what it's for. We'll *need* a warning here if they don't put the `i` update in the continuing block. (is this an error?)

**Comment by jdashg** [comment]
(oops, that's not a useless assignment, but rather it'll just be missed by any earlier continue branches)

**Comment by damyanp** [comment]
If this is strictly sugar, does it need to be part of the spec'd language at all?  There's an increase in complexity here that I worry could lead to divergent implementations.  If we expect most WGSL to be generated from some other language then it is likely that this sugar is rarely exercised.

**Comment by dneto0** [comment]
The Turing programming language has loop/end loop.   And "Exit when <condition>"

https://en.wikipedia.org/wiki/Turing_(programming_language)

```
 var n: int
 loop
      put "Please input an integer: " ..
      get n
      exit when n >= 0
      put "Input must be a non-negative integer."
 end loop
```

**Comment by dneto0** [comment]
I agree with @damyanp 

We don't need the sugar. 

If you want sugar, put in the icing on top, via translations like TypeScript over JavaScript.

**Comment by othermaciej** [comment]
That syntax in the Turning language is not like `loop`/`continuing` because there is no equivalent to the `continuing` block. `exit when` just looks like a conditional break, not a separator for a distinct increment block. 

If we can add a more familiar syntax that obsoletes `loop`/`continuing`, that's no net increase in complexity. 

I'd argue that using an unprecedented[1] and mysterious loop syntax fails the human writable / human readable criteria that the group agreed on. The adopted draft even suggested it would be discussed. Let's discuss it in good faith and have some reasonably objective way to determine pros and cons.


[1] maybe only near-unprecedented, I can't prove there's no such language ever.

**Comment by dj2** [comment]
`loop/continuing` maybe unfamiliar but that doesn't make it non-human writable or readable. I've written and read it several times.

Adding `for` as mentioned in the spec was never as a _replacement_ for `loop/continuing` it's explicitly called out as desugaring _to_ `loop/continuing`.

**Comment by othermaciej** [comment]
I'm realizing that I don't really understand what `continuing` does, and the spec doesn't really explain.

How is this example in the spec:

```
const a : i32 = 2;
var i : i32 = 0;
loop () {
  break if (i >= 4);

  a = a * 2;

  continuing { 
    i = i + 1;
  }
}
```

differ from this?

```
const a : i32 = 2;
var i : i32 = 0;
loop () {
  break if (i >= 4);

  a = a * 2;

   i = i + 1;
}
```

I'd expect both of these to leave the value of `i` at 4, and the value of `a` at 16.

Indeed, in C, a for loop desugars to a while loop like this:

```
int32_t a = 2;
int32_t i = 0;
while (i < 4) {
   a = a *2;
   i = i + 1;
}
```

There's no need for a distinct block for the increment. So I don't get what the extra block is actually doing.

**Comment by othermaciej** [comment]
Like, it might matter if WGSL had a `continue` statement that jumped straight to `continuing`, but it doesn't.

**Comment by dj2** [comment]
If you don't have any `continue` statements it is equivalent. If you had:

```
const a : i32 = 2;
var i : i32 = 0;
loop () {
  continue if (i < 4);
  break if (i > 10);

  a = a * 2;

  continuing { 
    i = i + 1;
  }
}
```

It isn't the same as you jump over the `a = a * 2;` in the continue case and jump to the continuing block.

**Comment by dj2** [comment]
WGSL does have a `continue` statement and it does jump to `continuing`.

**Comment by othermaciej** [comment]
I see. I expected it to be documented in the Loops section of the spec but I guess that is still under constrictuon.

So simple loops don't need to use `continuing` at all unless they actually use `continue`, thus making the spec example weird in a completely unnecessary way. In summary we have a fundamental loop construct consisting of four keywords `loop`/`continuing`/`continue`/`break` needed to emulate other loop types. I'm not seeing the language complexity savings here. The `continuing` block is only necessary to implement the `for` loops of other languages, but presents the same functionality in an obfuscated way.

Also worth noting, `break if` requires negating the loop condition relative to the norm for loops in other languages.

**Comment by dj2** [comment]
Please see https://github.com/gpuweb/gpuweb/issues/579#issuecomment-596039499 for discussion of the `continuing` block.

**Comment by dneto0** [comment]
> I see. I expected it to be documented in the Loops section of the spec but I guess that is still under constrictuon.

Yes, it's definitely under construction. There are holes in many other ways too. (E.g. type checking rules are only started.  We shared it as soon as we could.

> So simple loops don't need to use continuing at all unless they actually use continue, thus making the spec example weird in a completely unnecessary way.

Yup.  Granted.  And that seems to have caused a lot of concern.

The way to think loops is:
* there is one loop construct:  `loop { ... }`  repeatedly execute the body unless interrupted (see next).
* there are two ways to exit a loop:  `return` (which exits the function), and `break` (which exits the function, branching to the statement after the end-brace on  the loop
   * (Let's not talk about kill/discard for now.)
* the `continue` statement is used with `continuing`:   A continue statement is associated with its nearest enclosing loop L.  That loop L must have a continuing construct.  Executing that continue statement is a forward branch to that continuing construct.
* the continuing construct is special:  You can't have a return or kill/discard in it. The only way to exit the continuing construct is to `break` as the last statement.  (But otherwise you can have generic nested control flow)

**Comment by dneto0** [comment]
I should post a PR for WGSL to explain all that.

**Comment by grorg** [comment]
Discussed at [2020-03-10 Teleconference](https://docs.google.com/document/d/10yBasmrNdgvvd44KWC5a3ZQGzjJCjUBoqzZdByC_u7Y/)

**Comment by kainino0x** [comment]
> * The only way to exit the continuing construct is to `break` as the last statement.

How restrictive is this? Is it literally just:
```
continuing {
  ...
  break;
}
```
or can the break be more complex, such as `break if ...;` or `if (...) { break; }`?

(I was thinking that was necessary for do-while, but do-while never needs a `continuing` block.)

**Comment by litherum** [comment]
Familiar loop constructs are one of the highest-priority items for Apple because it significantly aids readability/writability with very little implementability concerns.

A few notes on familiarity:
1. It's impossible to use WGSL without _also_ using another language. It's fair to expect authors of WGSL to have familiarity with _some_ other programming language. Every successful language I can think of has some way of describing a loop that doesn't require a `break` statement to stop the loop.
2. When discussing APIs that are well-behaved-by-default, I have formulated the argument as being "concerned about new programmers." This may have led to some miscommunication, which I regret and apologize for. We're concerned about programmers who are new to WebGPU, rather than people who have never programmed before in their lives.
3. WGSL as it stands today re-uses many concepts from existing human-writable languages, including parts of Rust, Typescript, Javascript, C++, GLSL, and others. Regardless whether it was intentionally designed this way, WGSL does, in fact, take strides towards familiarity.

We're hoping the group can agree on _some_ sugar on top of loops. Ideally, this would be all of 1) `for` loops, 2) `while` loops, and 3) `do while` loops. However, we're willing to compromise here - we'd be happy with picking just one of the above, or even something new like `foreach` loops. We're just looking for _something_ to make loops easier to write for authors. To us, additional sugar for loop constructs is more important than the weird keywords added for round-trippability with SPIR-V (I'm looking at you, `continuing`).

**Comment by dj2** [comment]
How about we start with adding `for` loops on top of `loop {continuing{}}` this is already mentioned in the spec as a proposed desugaring. The `for` would be:

```
for(initializer; condition; statement) {
  body_statements
}
```

 and would desugar to:

```
initializer
loop {
  if (!condition) { break; }

  body_statements
  continuing {
    statement
  }
}
```

**Comment by jdashg** [comment]
I think all devs are familiar with `loop` (née `while (true)`), `break`, and `continue`, so I think our primitive building blocks here are great.

I mentioned before that the conversion of `while` to `loop+if+break` is trivial: https://github.com/gpuweb/gpuweb/issues/569#issuecomment-593271924
The same is true of `do-while`, which I never loved the syntax of anyway.

The strongest sugaring argument is therefore for a classic `for`:
```
for (STATEMENT A; EXPRESSION B; EXPRESSION C) {
  body_statements
}
```
...which I would pedantically desugar as:
```
{
  A;
  loop {
    if (!(B)) { break; }
    body_statements
    continuing { C; }
  }
}
```

I think our job defining and implementing the language is simpler without this desugaring, but I'm only weakly against it.

**Comment by jdashg** [comment]
I am more strongly against `C` being one or more `STATEMENT`s, and also firmly against comma operators. If devs want those complexities, step up into an explicit `loop` construction.

**Comment by RobinMorisset** [comment]
I see this as kind of spectrum with several possible levels of sugaring.

1) The current situation with loop and continuing

2) We could easily replace loop by a while loop, since 'while(cond) { X }' is identical to 'loop { break unless cond; X }' and 'loop { X }' is identical to 'while(true) { X }'.
Replacing loop by while in such a way would both be trivial for compilers and in my view would make the language significantly more readable and familiar to programmers.
Please note that this would require 'continuing' to be allowed in while loops, but I don't see any problem with that.

3) We could add a for loop, with 'for(A;B;C) { X }' de sugaring to '{A; while(B) { X; continuing { C }}}' (as noted by Jeff 2 comments above this one).
This would be purely sugar, and thus also trivial to implement.
Please note that B would have to be an expression (to end in a while), whereas A and C would have to be statements (assignment is a statement, not an expression in WGSL).

4) A further proposal that was made earlier is to completely get rid of the continuing keyword by allowing multiple statements in the increment of the for loop, possibly through a block statement or through a form of a comma operator that can separate statements.
Then instead of emitting 'loop { X; continuing {Y}}' compilers could emit 'for (;;{Y}) { X }'.

My goal with this comment is to gather all of the proposals in one place (hopefully I did not forget any), to make it clearer what the equivalences are between the different syntaxes, and to show that it is a broad spectrum with no requirement to go all the way in one direction or the other.
We feel that adding at least some form of while or for loop to the language would be a significant improvement to its readability.

**Comment by kvark** [comment]
Thanks @RobinMorisset !
I don't think (4) is on the same sugar spectrum: unlike other points, it limits the expressiveness of a language. I.e. unable to have that:
```
loop {
  const color = texture(...);
  ...
  continuing {
    my_buffer[5] = color;
  }
}
```

FWIW, my slight preference is to follow the original design by @dj2 : have loop+continuing as well as purely sugared `for()` with simple statements.

**Comment by litherum** [comment]
> it limits the expressiveness of a language

It doesn't.

There are two possible ways to accomplish this:
1. Directly state in the spec that `{Y}` in @RobinMorisset's example is scoped "as-if" it came at the end of the loop body, or
2. Require authors to promote `color` in your example to a `var`, hoist its declaration above the loop, and change `const color = ` in the body to just `color = `.

The performance/correctness effects of 2, if there are any, have not been demonstrated (yet).

**Comment by kvark** [comment]
I find (1) counter-intuitive (i.e. it ruins lexical ordering), and (2) makes me worrisome: it may have effects that are hard to catch in perf tests (i.e. are all all the drivers expected to turn such var into an ID internally?). I wonder if @dneto0 has an idea.

**Comment by othermaciej** [comment]
It seems likely that drivers consuming SPIR-V would perform SSA canonicalization on ingestion, which would indeed convert the var back to an id. We could probably find out if they do or not through a combo of testing and asking experts.

Or if they do not, a browser engine that ingests WGSL could perform SSA canonicalization before emitting SPIR-V. This could be one of the Canonicalization rules that @dneto0 has proposed.

Personally, I think we should do (2) and (3) from Robin's spectrum ASAP, and then evaluate whether we can do (4). (2) and (3) clearly will not impact either expressiveness or performance.

**Comment by dj2** [comment]
Using a `while` with `continuing` is close enough to current languages but just different enough to cause more confusion than a new keyword. The `loop` keyword is different enough that adding `continuing` doesn't have the expectations of how it should work.

As I've said previously, sugaring `for` on top of `loop/continuing`  is already in the spec as proposed and would be simple to move from proposed to included.

**Comment by dneto0** [comment]
Just catching up here.

I think some considerations have been lost along the way.  Particularly:

* the code to compute the condition and the update clauses could include function calls
* those called functions could have very complex control flow graphs.
* I don't know of a single GPU compiler that does *not* fully inline the entry point and its call tree, bottoming out at compiler builtins.

So for example if you start with this in HLSL/GLSL:
  
      int helper() { ... very complicated code ... }
      int stepper() { ... very complicated code... }
      ...
       for (int a =0; helper(a)< n ; a += stepper() ) {
             body
      }

Then you get arbitrarily complex condition evaluation and aribtrarily complex update code. 

This is not so far-fetched for compute applications over irregular domains.  e.g. work-stealing patterns.  For some reason GCD calculation also comes to mind. Hey, let's throw in bitcoin mining too, why not.


With these patterns in mind:
* a comma operator-like construct; or sequence-of-statements construct is not powerful enough to capture the computation for *either* the condition or the update clauses
* trying to place the update clause into the top, and trying to also have it access values defined in the regular part of the body is overly complex and weird.  I appreciate the effort to put more options on the table, but it goes way beyond traditional languages and breaks all sorts of programming culture and expectations about scoping.

Looking at Robin's taxonomy:

1.   Current WGSL proposal with loop and optional continuing construct handles the complex case.

2.   We can't just use a while loop because it doesn't accommodate inlined arbitrarily complex condition code without also duplicating it or outlining it (inverse of inlining).  (Myles already indicated elsewhere the complexity of out-lining is too high.)  Fundamentally the whlie(cond) is doing two things: (a) computing the condition and (b) choosing whether to escape the loop based on the computed condition result. But (a) might be too complex to fit the while() syntax.

3. is a proposal to add "for" as sugar.

4. is a proposal to add comma-operator or some kind of block syntax.  I address this above, arguing it is inadequate.

@kvark already noted the ability of the code in the continuing block to use a value X defined in the body.  That's *one* of the reasons why we propose putting the continuing block at the end, so that normal scoping rules apply, without the need to artificially hoist variables. Basically what you wrote is what you get, exactly without further complication.  (And devs are asking us to keep our flows as simple as possible.)

There's a caveat to this ability to use the identifier.  For example:

      loop  {
          if (cond) { continue; }
          const step : i32 = ....;
          continuing { 
              // invalid to use "step" here because the continue branch bypasses
              // the declaration of "step".
              i = i + step; 
         }
      }

This kind of error should be familiar to programmers because C compilers catch the following error:

```c
$ cat a.c
int moo(int c) {
  switch(c) {
     int y= 8;
    case 0:
     return y;
  }
  return 0;
}
$ g++ -c a.c 
a.c:4:5: error: cannot jump from switch statement to this case label
    case 0:
    ^
a.c:3:10: note: jump bypasses variable initialization
     int y= 8;
         ^
1 error generated.

``` 

The *other* reason we propose to put the continuing block at the end is that it means when reading the code, the only time you scan _backward_ in the text is for a loop backedge.  This is _easier_ to understand, and more welcoming to new programmers.  A "continue" statement is a _forward_ branch in the CFG, and that matches the top-to-bottom order of the code as proposed for WGSL.
I mentioned this in a meeting a couple of weeks ago, but wanted to capture it in writing here.

**Comment by dneto0** [comment]
I find it really weird that there is so much debate about all this right now when nobody has _written_  or _read_ very much code using WGSL as it is.   It sure feels like a green eggs and ham situation.

**Comment by RobinMorisset** [comment]
I feel confused about your comment that the complexity of the condition can prevent the use of 'while'. What exactly is the problem with 'while(cond) {}', and why is it not a problem for 'loop {break unless(cond);}' ? In both cases we have a potentially arbitrarily complex condition, and in both cases it has an impact on control-flow.
I really did not expect my option 2 (replacing 'loop' by 'while') to be particularly controversial, and I'd like to understand exactly why it is not harmless syntactic sugar in your view. I can get the argument that having a for loop with exotic scoping rules might confuse programmers (although thanks to the lack of variable shadowing it would simply accept strictly more programs than the traditional rule), but simple while loops are something that almost every programmer is completely familiar with, and this does not require any weird scoping, or any non-trivial implementation work either as far as I can tell.

**Comment by othermaciej** [comment]
Surely the best time to debate syntax details is before a lot of code has been written in the language, not after.

**Comment by jdashg** [comment]
We shouldn't always to fix problems before we agree that they're problems, and not everyone agrees that no-for-loops is a problem. It's definitely different, but a bunch of us don't think it's that onerous to do without them.
Given that these here are backwards-compatible syntactic sugars, can't we try writing code for now without these sugars, and see how bad our sugar withdrawal really is?

**Comment by dneto0** [comment]
>  What exactly is the problem with 'while(cond) {}', and why is it not a problem for 'loop {break unless(cond);}' ? In both cases we have a potentially arbitrarily complex condition, and in both cases it has an impact on control-flow.

Thanks for your patience waiting for my reply.

With  `while (cond-expr) { .. }` the computation of the entire condition must occur in an expression-evaluation context.  That could include function calls. 
It's overwhelmingly common for GPU compilation to do full inlining, and I want to be able to map that fully-inlined code back to WGSL, so in general I have to do out-lining: synthesize a function that I can then call from the condition expresssion in the while.

In the `loop { .... break unless (cond-expr);  }` case, the evaluation can be done before the conditional break statement:

         loop  {
                  ... evaluate condition-expr ...  // arbitrary statements which may have been inlined.
                  const cond_expr : bool = result-of-last-step-in-evaluation
                  break unless (cond_expr);
                 ...
         }

So in the interplay between `loop` and conditional-break, I get all the expressiveness I need to exactly capture programmer intent, precisely because of the decoupling of loop construct from the break-from-the-loop construct.

**Comment by othermaciej** [comment]
For cases where the condition evaluation can't be an expression due to previous inlining, the above could be generated as `while (true)` with a conditional `break`. The "replace `loop` with `while`" proposal does not entail removing `break`.

Out-lining is also an option that may produce more readable output, but it would just be a possible quality-of-implementation issue for a toolchain producing WGSL.

Meanwhile, human programmers could write more natural `while` loops if they choose. 

It's really surprising that this is controversial, `while (true)` is exactly equivalent to `loop`, so there can't be any possible loss of expressiveness from Robin's item (2).

**Comment by dj2** [comment]
It's the addition of `continuing` to `while` that I have an issue with. It takes something familiar and throws in something unfamiliar. Users expect the know how `while` works and then there is something strange when they see `continuing`. With `loop` you don't know how it works so the `continuing` doesn't cause the same issue as they have to learn how the whole construct works.

**Comment by krogovin** [comment]
My two cents: If WGSL is meant to be written by people, it is a really *good idea* in my opinion to make the shading language have the loop constructs that other languages have. For plenty of of folk, myself included, `for`, `while` and `do while` are oodles more readable and more understandable than the equivalent `loop` construct of WGSL. They are more readable and understandable because the existing shading languages have them. The `continuing` construct is just weird and non-obvious what it does when one comes from the already existing shading languages.

On the other hand, if WGSL is not meant to be human writable, then it does not matter.

However, the current goal states for it to be a programming language written by people, so...

**Comment by grorg** [comment]
This was discussed at the [2020-04-28 meeting](https://docs.google.com/document/d/1zUMz2oU5ovhxK_qx4MB8wKFZbOmOdOXU-LPLkrLl9go/).

**Comment by dj2** [comment]
In discussion at the 2020-04-28 WGSL weekly we narrowed down to four options. Please post your order of preference for these options below so we can gage interest.

1. `loop` without any desugaring for `for`
2. `loop` with `for` desugar
3. `while(condition)` with `for` desugar
4. `while(condition)` without any desugaring for `for`

**Comment by dj2** [comment]
For me: 2, 1, 3, 4

**Comment by othermaciej** [comment]
Out of those, my preference order would be: 3,2,4,1

This list of options has dropped the possibility of getting rid of the `continuing` keyword entirely. However, that seems possible to do as a follow-on, if we find a viable way for `for` to substitute efficiently for SPIR-V constructs that would compile to `continuing`. So seems fine to table that issue for now.

**Comment by RobinMorisset** [comment]
For me, from most preferred to least: 3, 4, 2, 1.

**Comment by Kangz** [comment]
I'd say 2, 1, 3, 4 but if you think a `while` loop is important, it could be sugar on top of `loop-continuing` along with `for`. In which case my first vote would be 2 + (`while` loop desugar).

**Comment by othermaciej** [comment]
> It's the addition of `continuing` to `while` that I have an issue with. It takes something familiar and throws in something unfamiliar. Users expect the know how `while` works and then there is something strange when they see `continuing`. With `loop` you don't know how it works so the `continuing` doesn't cause the same issue as they have to learn how the whole construct works.

I'd like to note for the record that I don't agree with this reasoning.

First, I think it's worth noting that most loops converted from SPIR-V will not need a `continuing` block. It's only needed when, in the original source language, the author had a `for` loop with a `continue` statement. In the common case of no `continuing`, seeing `while` will clearly be more familiar to readers than a `loop`. 

For the minority of loops that truly need a `continuing` block, seeing the `continuing` keyword will inevitably be a moment of brief confusion. The author will probably not have seen such a thing and will have to look it up in reference materials. Also using the unfamiliar `loop` keyword is unlikely to reduce the confusion. It will just mean there are two strange keywords that the reader needs to look up. If compilers always output `loop`, then it's likely the reader will first encounter `loop` without continuing, so the two moments of mystery would not even be close in time. In the case where `continuing` can appear in `while`, most `while` loops will seem familiar, and the reader can look up `continuing` when and if they hit it.

There's also human-written loops, which should never need a `continuing` block because authors would use `for` in the cases where its useful (assuming we provide `for`).

Summary: only one unfamiliar keyword is better for familiarity than two unfamiliar keywords.

**Comment by litherum** [comment]
Best ==> 3, then a tie for 4 and 2, then 1 <== Worst

**Comment by litherum** [comment]
I think there are a couple points that haven't been made yet, that I'd like to bring up.

1. The "well-behaved by default" argument applies here. Having a loop that, by default, spins forever will hint, or maybe even encourage, authors to write poorly-behaved programs. The default behavior shouldn't be [this](https://twitter.com/matiasgoldberg/status/1254450769010536449). It should be harder to get that behavior than to get good behavior.
We have a chance to build in behaviors like "don't loop forever" directly into the language. This is a classic case of choosing a design which encourages good behavior.

2. Theoretical purity has the least weight in the W3C's [priority of constituencies](https://dev.w3.org/html5/html-design-principles/#priority-of-constituencies).

**Comment by kvark** [comment]
Preference: 2, 1, 4, 3

**Comment by litherum** [comment]
Also: https://twitter.com/Litherum/status/1255231418294308865

**Comment by kainino0x** [comment]
The options on the twitter poll seem to be different from the ones here? (no loop+for)

**Comment by krogovin** [comment]
Coming form the point of view of a *USER*: my strong preference: 3 best, 2 & 4 tied (but in truth not good really) and 1 the worst.

In truth, the entire loop construct is really *weird* when coming from other high level shading languages. From the point of view of programming for WGSL, it makes way more sense, in my opinion, to have the standard constructs of `while`, `for` and the less used `do while`. The loop construct with the default behavior of looping forever is far from ideal as a *USER* of the language.

Some of this comes back to other issues, but I think the working group needs to decide consistently: if WGSL is meant for people to read and write or for tools to read and write. If the former, then it needs to have all the goodies that the base line of the other current high level shading languages have. If the latter, then this working group, or the w3c, need to enlarge the charter to include tools and libraries for WGSL manipulations.

From where I sit, it looks like it is trying to be both but succeeding in neither. The truth is that going for both is likely going to fail, but going for one will succeed. Indeed, the loop construct is great for making libraries and tools, but awful for a human. That simple. Other parts of the language also fall into that category when compared to other shading languages.

**Comment by dneto0** [comment]
Preference: 2, 1, 3, 4

**Comment by damyanp** [comment]
Most -> Least: 1, 4, 2, 3

**Comment by johnkslang** [comment]
FYI, coming at this fresh, very much from a C/C++ language background, and not to fast too like new syntaxes:

I really liked the `continuing` block.  Grasping where C's for 3rd subexpression really goes is still an issue for experienced programmers when complex things happen there or with modifying the inductive variable in the loop.  Seeing it explicitly in the right place looks quite useful.

**Comment by grorg** [comment]
This was discussed at the [2020-05-05 meeting](https://docs.google.com/document/d/1K2H59am7yLj_DBv0lfuz7g52NNyF4xcQpBs1NNnhk8g/)

**Comment by grorg** [comment]
Resolution: a "loop" with "continuing", and a simple "for"

**Comment by grorg** [comment]
(Meant to add the keyword, not close the issue)

**Comment by litherum** [comment]
If we're going to have `for` loops and no `while` loops, we should make sure we spec it such that `for (;cond;) { ... }` works.

**Comment by othermaciej** [comment]
@grorg can you expand on what “simple” means in the group’s resolution? Does it refer to not adding new constructs like comma, does it mean restrictions on what type of statements may be present in the loop syntax, or is it something else entirely?

**Comment by johnkslang** [comment]
Here's a list to consider:

- can you declare a new variable or not, in the init-statement?
- if so, what are the limitations?
  * How complicated can the declaration be?
  * is the ` = initializer` part required or optional?
  * when does the new name come into (and go out of) scope?
- can you declare a new variable or not, in the condition-expression?
- if so, what are the limitations?
  * How complicated can the declaration be?
  * is the ` = initializer` part required or optional?
  * when does the new name come into (and go out of) scope?
- what exactly can a `<continue-statement>` [sic] be?
  * it should not even be a "statement", it should be an expression (only the init-statement is as statement)

(C++ has different sets of rules for the two parts, partly driven by them being *statement* versus *condition*.)

About scoping, where are the errors in this, if any?

```
let x : i32 = 0;
for(let x : f32 = f32(x); let x : bool = x < 5.0; ++x) ++x;
```

An early response showed (incorrectly, I believe) nested scoping such that you'd have 3 `x`, but there are lots of choices for exactly where each `x` goes in and out of scope.

**Comment by kainino0x** [comment]
IIUC about the currently-agreed-upon for-loops:
1. condition-expression, being an expression, should not allow variable declarations. (If this isn't immediately true, we should make it true.)
2. init-statement and continue-statement are single statements only, so semicolons wouldn't be valid there.

BTW, I'm pretty sure we tentatively agreed that our lexical scoping wouldn't allow shadowing (but would allow same names in sibling contexts)

**Comment by kainino0x** [comment]
Also, *defining* it as syntax sugar should resolve these questions.
