### ISSUE TITLE
[wgsl] SPIR-V support

### ISSUE THREAD

**Issue by L-as** [gpuweb/gpuweb#570]
I don't see the need to make a whole new human-readable textual shading language, when one could just use SPIR-V; there are a lot of issues with using a textual format in addition to just disrupting the ecosystem, some of which are also seen in ECMAScript, as seen here: https://github.com/tc39/proposal-binary-ast/blob/master/README.md

In order to not disrupt the current ecosystem, it might be better to support SPIR-V, or some subset of SPIR-V to make it safe to use on the web.

**Comment by L-as** [comment]
FWIW it would be better even if it was just another binary format for shaders.

**Comment by TheSpydog** [comment]
> FWIW it would be better even if it was just another binary format for shaders.

I’m not sure about this. One huge advantage of SPIRV is that basically every shader language already compiles to it. This would be thrown away if a new binary format was invented just for WebGPU.

I’d personally much rather have a new high-level shading language than a brand new binary format. If I’m going to have to rewrite my shader pipeline anyway, I’d rather write in a language designed for human writability. (Not saying that WGSL exactly meets that goal, though.)

**Comment by dj2** [comment]
If you have concerns/suggestions for the writability of WGSL, please file bugs. We're actively designing the language.

**Comment by L-as** [comment]
Adding unnecessary complexity to the language will just increase the probability of conflicting and buggy implementations IMHO.

@TheSpydog 
> I’m not sure about this. One huge advantage of SPIRV is that basically every shader language already compiles to it. This would be thrown away if a new binary format was invented just for WebGPU.
> 
> I’d personally much rather have a new high-level shading language than a brand new binary format. If I’m going to have to rewrite my shader pipeline anyway, I’d rather write in a language designed for human writability. (Not saying that WGSL exactly meets that goal, though.)

I honestly don't get this argument. WGSL shouldn't be for humans, since people will most likely just use a tool to convert from something else. Existing programs aren't going to rewrite their shaders in this new language for no reason. In addition, SPIR-V isn't going to lose its value if WGSL was just binary; if SPIR-V and WGSL were isomorphic (or close), you'd have no problems at all, since you can use all the existing tools.

**Comment by Aransentin** [comment]
How about an official extension to support SPIR-V directly? If it'll get wide enough de facto support some applications (e.g. games) might be able to target SPIR-V-capable browsers only. It'd be nice for early demos as well before wgsl tooling has been developed.

**Comment by litherum** [comment]
> WGSL shouldn't be for humans, since people will most likely just use a tool to convert from something else.

What evidence do you have for this, specifically in the context of the web? Currently, the only accepted language by WebGL is a human-writable language, and there are tons of [examples](https://www.khronos.org/opengl/wiki/OpenGL_Shading_Language), [tutorials](http://www.lighthouse3d.com/tutorials/glsl-tutorial/), and [playgrounds](https://www.shadertoy.com) for it. It's common practice for web pages to [stitch](https://github.com/BabylonJS/Babylon.js) together shaders at runtime using string concatenation.

The state of the art for web shaders is already human-writable, and there is demonstrable evidence that it both A) works and B) is widely used.

**Comment by Joshua-Ashton** [comment]
> What evidence do you have for this

The fact you're trying to make what is essentially a SPIR-V representation in some Rust styled syntax and SPIR-V wasn't designed for humans to write shaders in.

The "language WebGL uses" is GLSL, which is designed to be a human-readable, programmer-friendly language, moreso than some IL (which is what WGSL appears to be more like...) If you want some way of mapping SPIR-V 1:1 to a text language, it's not going to be pleasant to write with, ever. The learning curve is just too steep for beginner shader programmers to learn it, and it's so different and weird that no-one experienced will bother learning and writing for it.

Nobody is going to write WGSL by hand simply because it is so esoteric -- basic concepts such as loops become weirdly over-complicated (`continuing`, etc); not to mention `regardless` and `unless` and everything is incredibly verbose.

There was a big push for WebAssembly recently over JS, etc and now we're just like going back in time back to text representations of things again? It makes no sense...

At this point you may as well just drop it and take in `spirv-dis`, if you want a text-based representation for JS, or just binary blobs (or both!)

> The state of the art for web shaders is already human-writable

GLSL isn't state of the art. Please don't call it such.

> It's common practice for web pages to stitch together shaders at runtime using string concatenation.

Okay, then they can just compile glslang or whatever compiler frontend they want to WebAssembly and stitch together a decent language at runtime.

WGSL is just a massive feature creep.

**Comment by dj2** [comment]
We know the `continuing` construct is awkward. There is a proposal to add a `for` #569 for that explicit purpose. The `continuing` is specifically to support SPIR-V, but most users would write a `for` loop. We don't expect `regardless` to ever show up in hand written code, but it can be generated from SPIR-V constructs. The `unless` is seen in other languages such as Ruby and is just a shorthand for `if (! a)` you can say `unless (a)`.

What is it about the language that you find so unpleasant to write with? Is it the `<>`? Something else? Can you please file bugs so we can discuss those specific rough bits instead of vague it's unpleasant comments?

Shipping a WASM compiler is a heavy burden.

**Comment by autumnontape** [comment]
@Joshua-Ashton I wouldn't be so hard on the irregularities WGSL takes on from its goal of being mostly bijective with SPIR-V. As others have said, features like `regardless` and `continuing` aren't intended for hand-written code.

I agree with you that WGSL doesn't need to exist in the first place, but what the language will look like if it does exist is a separate conversation. When you call out features like `continuing` specifically without proposing alternatives, you're essentially making the case that mapping cleanly onto SPIR-V shouldn't be a priority for WGSL. If a structured, text-based WebGPU shader language is taken as a given and you want to use SPIR-V for your WebGPU application, WGSL's current direction is about as advantageous as it can be. If there are wrinkles, remember that the spec has only existed very briefly.

**Comment by autumnontape** [comment]
I suspect a lot of the backlash against WGSL has been powered by existing resentment about Apple vetoing SPIR-V in WebGPU, as well as rejecting Vulkan on their platforms before that. It's very frustrating for a developer to watch a vendor hamstring technologies for capital-related reasons that are of no concern to anyone else.

**Comment by othermaciej** [comment]
> there are a lot of issues with using a textual format ... some of which are also seen in ECMAScript, as seen here: https://github.com/tc39/proposal-binary-ast/blob/master/README.md

I don't think that study holds up. They compared to the SpiderMonkey parser, at the time, one of the slowest JavaScript parsers. And they compared to a binary AST parser that didn't do validation, hardly a fair comparison. Once you add validation, this proposal is likely no faster than a very fast JavaScript parser, like JavaScriptCore's.

Beyond that, these JS-specific results need not generalize, as demonstrated by Apple's [WSL prototype](https://webkit.org/blog/9528/webgpu-and-wsl-in-safari/). In that demonstration, gzip'd size was smaller and compile time was faster for a textual language compared to binary SPIR-V (and that's comparing to an implementation that didn't do validation, at least at the time). It might be that a binary format specially designed to be fast to parse and validate, and to be compact, could beat a text format, but it doesn't seem like SPIR-V is it.

**Comment by litherum** [comment]
I think the ship has already sailed on this issue (at least as its formulated in the OP). I propose we close this issue as "no change."

**Comment by Joshua-Ashton** [comment]
Is this an out of season April Fool's joke?

**Comment by Kangz** [comment]
It isn't. The group decide to pursue WGSL. If you have specific concerns about the language please file bugs. Note that "not being SPIR-V" isn't a specific concern.

**Comment by Leopard1907** [comment]
Thank you , i'm glad Apple dictated this standart to working group successfully. 

Standarts should be enforced by companies like Apple as they want them to be. Thanks for the choosing sensible way.
