### ISSUE TITLE
[WGSL] WGSL needs a plan for expansion

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#600]
I expect WGSL will evolve over time to incorporate new functionality.

We should make a plan to accommodate that growth.

For example:

* Account for potential conflict between keywords introduced in a future version of WGSL, vs. identifiers used in today's shaders.  Maybe use namespace mechanism?
* Account for new data types, e.g.  IEEE 16bit float, potentially other exotic floating points type like bfloat16.  This can impact type derivation / typechecking.
* Will we require shaders to declare their own version or extensions?  This is one approach to accommodating the keyword-conflict issue.  GLSL chose this path.

**Comment by dneto0** [comment]
On the new-scalar types front, the WGSL draft reserves the token `f16` for IEEE 16-bit float, and `bf16` for bfloat16.   But I'm pretty sure we can't see far enough to reserve everything we will need.

**Comment by atg** [comment]
It's a good idea to require a version directive as the first line of the file. This is beneficial not just for the compiler but also for humans. As well as making it easier to make breaking changes in the future (such as adding new reserved words), explicit versioning also avoids a Python/Swift style situation where you look at a source file and can't tell exactly what version of the language it was written for.

As the intention is to have JS do preprocessing, you'll want to permit multiple version directives in the same shader, while I don't think it's feasible to have the compiler switch versions halfway through compilation, the compiler should at least validate that all version directives in a compilation unit are for the same version.

It occurs to me if code is being preprocessed by JS, the first line in a header file (with the version directive) in a file may not be at the top level when it's glued together into a compilation unit - it could be inside a function or even a type declaration. Given that, the version directive should be something akin to a line comment rather than a declaration.

More generally, some linecomment-like syntax should be reserved for compiler directives, e.g. pragmas, etc.

**Comment by dj2** [comment]
I think it would be the preprocessors job to emit the version directive, if we have one, in the correct spot and to emit it only once.

**Comment by atg** [comment]
In that case you have to careful in adherence to semver, because validating that multiple versions match will be hardcoded into preprocessors, so it needs to be a simple calculation.

**Comment by magcius** [comment]
The version directive shouldn't be there just for yucks. It is *only* necessary if we choose to break backwards compatibility and older source text is not easily upgradable to newer versions, which might be a hard sell to this group.

If we add new functionality in a backwards-compatible manner, then we would not need a version directive in-band. The important thing is letting the user of WebGPU query whether newer features are supported, which is better exposed directly from the API.

**Comment by dneto0** [comment]
Ok, so that's one axis:
- in-band declaration (like #version in the shader in GLSL) makes it less ambiguous to determine what you're looking at.  Validation can be more self-contained.
- out-of-band declaration (like compiler option, e.g. a shader model flag, as I understand it) reduces the visual noise

Another option is namespacing.  E.g. reserving a "std::"-like namespace for things that can be captured by a name, e.g. a type, a builtin, potentially other things.

The problem also presents itself when releasing experimental support for a new feature.  Is there enough consensus in the web platform about how best to do this?

**Comment by grorg** [comment]
Discussed at [2020-03-17 meeting](https://docs.google.com/document/d/1WMQ_qRHM4R1BrrCm5Wdx_8ERdLem5jZG9kP65kXHC78/)

**Comment by jdashg** [comment]
General sentiment from the meeting is for in-band declaration.

**Comment by litherum** [comment]
## Goals

- Minimize the above breakage (ideally to 0)
- Don’t require authors to qualify every single symbol they use from the standard library

## Option 1: Plug our ears

Do nothing. Just swallow the fact that if we add functions to the standard library, we may break programs.

In reality, this probably isn’t as bad as it sounds. This is what HLSL does today (I think?). Also, the default Xcode template for MSL has using metal; in it, so if you create your MSL sources using the default Xcode template, this is also how MSL works today.  Also, this is how Javascript works, though Javascript has more flexible feature detection facilities than WGSL.

Function overload rules will probably let most functions coexist with functions of the same name in the standard library. Though new types don’t get this benefit.

In the long term, this option probably isn’t sufficient, as we’ll probably want to let authors create their own modules with their own namespaces.

## Option 2: Do it like C++

Philosophy: Let authors opt-in to dangerous-yet-convenient mode. If they do it, they run the risk of their program breaking in the future. But they don’t have to qualify everything.

A few pieces:

- Add a new production to the grammar that looks like namespace ident { … }. Unlike C++, we could disallow nested namespaces, so we just have two levels - global and non-global (just to keep it simple).
- All standard library symbols are inside the wgsl namespace.
- Like C++, names within the current namespace or an outer namespace don’t have to be qualified. Names in sibling namespaces or descendent namespaces need to be qualified. So standard library functions would be called like wgsl::abs(…).
- To satisfy the second goal, add a using keyword which adds a namespace to the symbol search path, as in C++.
  - Authors can use this if they don’t want to qualify standard library functions. However, if they say using wgsl; then they run the risk of having their program break in a future version of the language.
  - Like option 1, this probably isn't as bad as it sounds, because function overload rules will probably let most functions coexist with functions of the same name in the standard library. Though new types don’t get this benefit.

## Option 3: Parse the standard library in a special mode

If the author writes a symbol that collides with the standard library, the author’s symbol wins, every time.

In order to handle complicated function overload resolution (which will almost assuredly come in the future), we’d have to make any author-created symbol shadow every symbol in the standard library with the same name.

It allows the author to do something that we may wish to discourage - intentionally overriding a preexisting standard library function. Maybe they don’t like how max() is implemented in the standard library, and they want to implement it themselves, for the entire program. I could see arguments on both sides - letting authors do this may be considered a benefit, or be considered a detriment, depending on where you’re standing.

Again, this option probably wouldn’t be sufficient in the long term. Eventually, we’ll probably want to let authors create their own modules with their own namespaces.

## Option 4: Version the standard library

Have authors do things like `#import wgsl 12;` to import the 12th version of the standard library. For all `n`, version `n` of the standard library is a strict superset of version `n-1`. This versioning would affect only the standard library, not the whole language (unlike GLSL).

Also, add a property on the `GPUDevice` which exposes which version of the WGSL standard library is supported by the implementation, so authors can determine which code to deliver to the browser.

Again, this option probably wouldn’t be sufficient in the long term. Eventually, we’ll probably want to let authors create their own modules with their own namespaces.

## Recommendation

We have a slight preference for option 4, because it's the only one that actually solves the problem and doesn't involve special parsing modes.

**Comment by kainino0x** [comment]
> Also, add a property on the `GPUDevice` which exposes which version of the WGSL standard library is supported by the implementation, so authors can determine which code to deliver to the browser.

Would we put this in the GPUDeviceDescriptor and require browsers to enforce lower versions for better portability? (Since it's a browser compatibility problem, and not a hardware compatibility problem, it's not obvious.)

Since it's a browser-global thing, perhaps it should go on `GPU` (`navigator.gpu`) instead of the device or adapter.

**Comment by magcius** [comment]
There's also Option 5: Require that the user qualify everything. This is what SPIR-V (and other ingestion formats) do. It's effectively free from a toolchain perspective, and has the benefit of allowing forward-compatibility.

Until there is a **strong** need to allow unqualified references, I recommend this option, and it can easily upgrade to any of the four options above.

**Comment by grorg** [comment]
Discussed at the [2020-06-23 Virtual F2F meeting](https://docs.google.com/document/d/1WI9PzwXy39fFHuZLUnEQtSplwfmFaZ2oVb0gXJsA2P4/)

**Comment by kainino0x** [comment]
## Option 6

No import-all statement (C++ `using`).
Only allow `using { a, b } from std;`.

(6a) All of the builtin functions are namespaced by default. E.g. `using { sin, min, reverseBits } from std;`, `sin()`, `min()`, `reverseBits()`. Overly verbose.
(6b) Some of the builtin functions are namespaced by default. E.g. `sin()`, `min()`, `std::reverseBits()`. Probably acceptable verboseness.

## Option 7

(This is basically an idea that was previously discussed in a WGSL meeting and issue, I just don't remember when/where or whose idea it was, sorry.)

Have a `navigator.gpu.maxWGSLVersion` which just tells you what version of WGSL is available.

(7a) All of the builtin functions are namespaced by default. E.g. `std::sin` or `std::min`. Slightly more verbose for not much benefit.
(7b) Some of the builtin functions are namespaced by default. E.g. `sin`, `min`, `std::reverseBits`. Only very core functions are in scope by default.

New functions can be added to `std` without breakage (see below).
*Also* provide namespaces for things that get added later, e.g. `std11`, `std12`.
`std` can be defined as something like `namespace std { using std10; using std11; using std12; }`

Allow C++-style `using` statements for `using std11;` or `using std12;` or `using userDefinedNamespace;` but NOT for those built-in namespaces (e.g. `std::`). **Guarantee that we never add functions to `std11` et al.**

```
let y = sin(x);
let z = std11::fancySin(x);
```
or
```
using std11;
let y = sin(x);
let z = fancySin(x);
```

**Comment by magcius** [comment]
> Have a navigator.gpu.maxWGSLVersion which just tells you what version of WGSL (or more specifically, its standard library?)

Yes, we need a mechanism that lets you know what new WGSL features you are allowed to use. Part of this difficulty is that if someone wants to support new built-ins, there's an awkward transition period where the new versions are not fully rolled-out, and have to support fallbacks anyway. Either engines will handle this on the client by dynamically switching their shaders, or they'll just continue to use the old shader versions.

**Comment by kainino0x** [comment]
It also makes an easy way for web developers say "Please upgrade your web browser" as soon as the version hits stable on all the browsers they want to support and they want to remove support for older ones (rather than version detecting each browser separately).

**Comment by dneto0** [comment]
First, I don't want to forget the issue of versioning basic language features _aside_ from things that look like library calls.
For example, to accommodate the multi-level break idea that @jdashg  suggested once. 

For language-level things, I'd like to see an in-band declaration such as `require wgsl 5;`.  Maybe this is the same mechanism for declaring features.  (Perl gets a lot of mileage out of `use v5.6.1;` as an in-bad compile-time check right at the top of the module)


About supporting library evolution, I'd like to point out that the draft proposal *already* has an import directive that maps a stringly-named package into a user-specified namespace.  This is a working solution.  Why not keep it? Sure, fuss over partitioning functionality into namespaces, but the mechanism is there and works fine.


That aside, my guiding principles are: 

* never unexpectedly stomp on the user's namespace
* new semantics requires a new spelling
* less specialness is better
* support incremental evolution

By those criteria:

* option 1 is out: Stomps on namespace. 
* option 2 is ok.  Has complexity with "using"
* option 3 is out: complex rules to avoid stomping on namespace.  People will get confused, and you're inviting incompatibilities due to the complexity.
* option 4 is barely ok.  But it invites accidents where I upgrade a version number for one reason but then accidentally have a completely unrelated piece of functionality conflict with a new "standard" thing.
* option 5 is ok. Works always, and is clear.
* option 6a is ok.  Explicit opt-in per imported name
* option 6b invites confusions about "when do I need a qualifier vs. not". 
* option 7a is ok.   Explicit works.  Promise of frozen stdXYZ avoids accidental stompage.
* option 7b is like 7a, but invites same confusion as 6b.

For me option 5 is a clear winner _for an MVP_
The burden of typing 5-6 more characters to access a library function is low.  `w3c::sin` is not too much to type.

At the outside, I'd consider doing 7a.  I like the idea of versioned iteration of the standard packages.

I'd also want us to consider breaking up functionality into smaller chunks.  From the breakdown in https://github.com/gpuweb/gpuweb/issues/667#issuecomment-648322728  I think it's useful to think of trigonometry as separate from bit-manipulation.   For example, we might want to offer a distinct feature of "more accurate trig for HPC".
I'm not a *huge* fan of catchall "std" or "wgsl" namespaces.

**Comment by kainino0x** [comment]
+1 for option 5 for MVP.

**Comment by dneto0** [comment]
Discussed during the [2020-08-25 meeting](https://docs.google.com/document/d/13lWCWtooVE1kT6TGta16gM-dDXjRdUKt9KG_9cTcTkY/edit#heading=h.hp3f2zbslxr9) in relation to #1018

**Comment by dneto0** [comment]
During the August 25 meeting I mentioned that GPU API clients already have diverging requirements for accuracy of math functions like sine and cosine.

An example is OpenCL C where the default math library is high accuracy but possibly slower, because HPC and traditional "scientific" computing are a key target market.  However, the standard als has native_cos, native_divide, native_log and others which are lower accuracy (and faster) versions that I presume are targeted to rendering applications and therefore similar to the versions found in OpenGL.

I think namespacing is a nice way to address this user requirement.

**Comment by litherum** [comment]
I wish there was a way we could do this such that browsers wouldn't have to keep around `n` old versions of the compiler, one for each version of the language.

**Comment by dneto0** [comment]
@litherum  wrote (in #1404)

> In #600 it seems we've coalesced around the first line of the shader being something like #version foobar (like GLSL). Will we use a similar mechanism for opting into shading language extensions?

I don't read that from the above.  Specifically, the requirement that it be the **first line** of the shader.  
I'd resist that: it has been shown to be a pain for folks generating code.     

Earlier I gave the example of ` require wgsl 5;` as following a pattern that works well in Perl.
In Perl you can place that declaration / statement *anywhere*, and it means "I need a Perl version _at least_ this high".  So it's also cumulative.  That makes it easy for code generators and people to use.
(I can't remember if it's limited to being at module scope. That's the only place I've seen it.)

**Comment by kvark** [comment]
I like the idea of compose-ability that @dneto0 brought.
At the same time, I don't like introducing new syntax for version checks, be it perly `require wgsl 5` or C-ly `#version Xxx`.
Could we consider a scheme were top-level items can just be decorated? We already have the decorations on top-level items, we could just piggy back on them:
```
[[lang_version(1)]]
fn my_tricky_function() {}
```

**Comment by dneto0** [comment]
Here's a proposal for a minimal way to tag code as needing a new feature:


* Add ‘enable’ statement at module scope.  It names a feature (beyond WGSL 1.0) that might be used in the _remainder of the source module._
      * Why before first use:  A parser should not have to deal with syntax/features it does not understand. It can fail at an unrecognized 'enable'.
      * Why not at the start?   Allow a code snippet to self-declare what it needs; but then make it easier to concatenate such snippets.
* Redundant enable statements are permitted.
* The statement does not have to appear at the start:  makes it easier to glue together portions.
* To keep it flexible, use something like rules for naming attributes and their parameters (I haven’t cross-checked this with current grammar):

```
enable_stmt:
      ENABLE LEFT_PAREN  enable_param_list RIGHT_PAREN SEMICOLON

enable_param_list : 
        enable_param
        enable_param_list COMMA enable_param

enable_param:
     IDENT
     const_literal
```

Validation: 
* First attribute must be an identifier: that’s the name of the feature (or change the grammar to enforce this)
        * Can accommodate namespacing this way.
* W3C maintains registry of standardized extensions
       * Reserve ‘wsgl’ for use by standardized WGSL features?
* createShaderModule rejects any feature that the implementation or attached device does not understand.  Fail early principle.

Examples

        enable(f16);

Or:

	enable(wgsl,f16);


Example of a non-standarized extension:

	enable(chromium,wacky);

We can have feature bundles, e.g. WGSL 2 could be defined as a set of other enables:

	enable(wgsl,2);

**Comment by ben-clayton** [comment]
> The statement does not have to appear at the start: makes it easier to glue together portions.

If features change the language in a non-backwards incompatible way, would it make sense to push / pop this? Then you can glue together portions knowing there's no enabled-leakage between them.

**Comment by ben-clayton** [comment]
Having just said this, having later code rely on an enabled feature that has since been disabled is asking for trouble. So maybe forget what I said.

**Comment by dneto0** [comment]
Discussed in the F2F [2021-02-22](https://docs.google.com/document/d/1Csyz-MF9u2iw7WmjENTCr4BUbxnTgPk9l0u7ux6DSL4/edit)

**Comment by dneto0** [comment]
Feedback I heard:
- don't bother with trying to namespace 'wgsl'.  This committee decides what extensions exist in WGSL, and standardizes them.  Conflict with outside actors is their problem.  Don't force extra writing for standard path.
- thought that `enable(foo,bar)` was a declaration of two features, not one parameterized feature.
- suggest a flat namespace: no parameterization

So I think we can get by with this simplified form:

* Add ‘enable’ statement at module scope.  It names a feature (beyond WGSL 1.0) that might be used in the _remainder of the source module._
* Redundant enable statements are permitted.
* The statement does not have to appear at the start:  makes it easier to glue together portions.

Grammar:
```
enable_stmt:
      ENABLE IDENT SEMICOLON
```

Validation:
* An enable statement is not a declaration.  The identifier is not added to any scope, and does not conflict with any other identifier in the WGSL program.
* It must only appear at module scope.

**Comment by litherum** [comment]
Re: what kinds of things should be shading language extensions

I would understand the position of "nothing should be a shading language extension and everything should be a device extension instead." I would also understand the position of "there are shading language extensions and there are are device extensions too, but they are different sets; and maybe some feature has to appear in both sets because Vulkan requires you to enable it at device creation time but oh well we just have to live with that okay." I don't, however, understand the position of "every shading language extension needs a parallel device extension."

At the VF2F today, @jdashg described how the author wants to know whether or not their shader source code is acceptable before they run it. However, that's exactly what compilation is - a pre-pass to tell the developer if their source code can be used or not. We already have a pre-pass; we shouldn't need a second pre-pass on top of our existing pre-pass.

**Comment by jdashg** [comment]
That would be a departure from a ton of prior art in this space for extension discoverability. (WebGL, GL, Vulkan, less directly D3D)
Please reconsider how quickly you dismiss this. What you propose is just not how things are done by almost anyone, and I am worried when you don't see this as a warning.

I want to collaborate more here and I'm happy to talk about the success we've had with this approach as both clients of GL and implementors of WebGL.

(But I don't appreciate the "just because" glibness)

**Comment by litherum** [comment]
This issue seems to be covering different things:
- Namespaces
- Extensions (to the shading language)

I propose we separate these out into their own issues. It seems like we've made progress on namespaces above, but then the conversation seemed to veer into extensions.

(See also: https://github.com/gpuweb/gpuweb/issues/777)

**Comment by magcius** [comment]
> At the VF2F today, jdashg described how the author wants to know whether or not their shader source code is acceptable before they run it. However, that's exactly what compilation is - a pre-pass to tell the developer if their source code can be used or not. We already have a pre-pass; we shouldn't need a second pre-pass on top of our existing pre-pass.

Wait, I don't quite get this. If I have shaders that can optionally use three extensions, I need some way of knowing *which* extensions are enabled, preferably from the browser API side. Or are you recommending that libraries parse the error output from compilation and recompile based on that?

**Comment by krogovin** [comment]
I admit that I prefer a simple way (that is essentially what GLSL does):
- First line of a shader **MUST** declare what version of shading language is in use
- Enabling shader extensions must come immediately after the version declaration.

This gives that a what a shader wants/requires is at the very start and guarantees that shaders wrote today work tomorrow. It is expected that a WebGPU application would check the properties of the WebGPU device to make sure that the version and shaders it feeds to WebGPU the device can do.

**Comment by dneto0** [comment]
Discussed in [2022-05-24 meeting](https://docs.google.com/document/d/1j9ydd9faXxRyUb7CPTmFzCTu1k0QFDAmP4dIft3t4y4/edit#heading=h.i8otupagxzv0)

This bug is addressed well enough for now.
- WGSL has the 'enable' directive, and
- We're considering namespaces for post-v1.  #777

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-24-minutes#wgsl-wgsl-needs-a-plan-for-expansion--issue-600--gpuwebgpuweb--github">WGSL meeting minutes 2022-05-24</a></summary>



* MM: Can be closed?
* KG: Think we’re satisfied with this, we have a plan?
* DN: Yes, was to prod discussion and i think we’re far enough along with what we have until we have a concrete thing that’s different. So, close.


</details>
