### ISSUE TITLE
[wgsl] Redundant [[layout]] decorations in addition to [[offset]] decorations

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#621]
In #561 it was agreed that we would keep the [[offset]] decorations in (pending user feedback).

Without [[layout]], the set of valid manual-layouts for a struct is the union of the layout rules allowed in that place, i.e.:

- Check if it works with std430, if yes :+1:
- Check if it works with std140, if yes :+1:
- Otherwise :-1:

(Note it's not certain whether std430 will be allowed for uniform blocks. Some Vulkan devices can't support it.)

AFAIU: Explicit [[layout]] would essentially allow authors to choose among the available layouts (which right now is only 1 or 2 layouts, possibly depending on context).

**Comment by jdashg** [comment]
I would prefer devs explicitly ask for (and, by doing so, document) what they want, but I do agree that it seems easy to test all (2) possible layout constraints.

**Comment by damyanp** [comment]
Can you elaborate on why adding this additional layer of validation is useful for WebGPU developers?  

I note that the current spec does not contain the strings "std140" or "std430".  I think I'd find it easier to be brought on board with these proposals if we first got these concepts into WGSL. As it is now, I feel we've skipped past a bunch of investigations and spec changes to get to the point where's it is somehow obvious that adding this redundant decoration is important for developers.

**Comment by dj2** [comment]
So, there are several layout formats in Vulkan. Two of them are STD140 and STD430, by default UBOs are STD140 and SSBOs are STD430. You can see the rules for the layouts at [1]. STD140 can waste a lot of space due to the padding rules around floats, STD430 removes some of those padding restrictions.

The original plan was the `offset` would mean we don't have to mention STD140 or STD430 as you'd just tell us what you want and it'd be good to go. This falls down a bit in that it can be hard to figure out what those offset values should be. So, as Jeff mentioned above, adding something like `layout std140` as an annotation on the struct could allow us to have the developer put the annotation but leave off the `offset`s. Then the compiler would detect the offsets are missing, error out but the error message can use the annotation to calculate all the common offsets the developer would have to enter.

The benefit of having the offsets explicitly in the shader is when I'm writing my code to put the data into my buffer I can see explicitly what the shader is expecting and I won't accidentally forget to pad something like a float array by the extra 12 bytes.


1- https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf#page=159

**Comment by damyanp** [comment]
> The benefit of having the offsets explicitly in the shader [...]

I think we've resolved that we're going to have the offsets explicitly in the shader.

> the compiler would detect the offsets are missing, error out but the error message can use the annotation to calculate all the common offsets the developer would have to enter.

So this is solely for tooling purposes? Why does the developer care about STD140 or STD430? If they don't care about the layout enough that they're asking the compiler to figure it out for them why wouldn't they just want the compiler to pick the most optimal one?

**Comment by dj2** [comment]
The layout the compiler picks has to match the layout they're using when they put the data into their buffer. So, if the compiler picks one, they won't know how much padding to use between elements when writing into the data buffer.

**Comment by damyanp** [comment]
I think we're misunderstanding each other.

The proposed scenario for where specifying STD140 or STD430 is helpful is for when the developer wants the compiler to tell them what offsets to use in an error message.

I'm saying, that in this case why would the developer care which of STD140 or STD430 is used here?  At this point the dev is already saying "I don't know how my buffer should be arranged, please tell me".  So why is important that they pick STD140 or STD430 here?

**Comment by dj2** [comment]
Ahh, so you're saying, we can leave off the `layout std140` and if they don't put in `offsets` we output an error that says something like you left the offsets blank, maybe try these ones. And, we just pick one that makes sense?

That works for me.

**Comment by kainino0x** [comment]
I opened this issue for discussion, not strongly arguing for it right now. Sorry, I forgot to explain the main use case (helpful error messages) in my issue.

I am inclined to agree that it's okay if the error messages always suggest the std430 layouts (or std140 for uniform buffers if we have that restriction, which I think we do), or whatever is the most reasonable layout we can support across the backend APIs for that binding point.

**Comment by damyanp** [comment]
Do we have enough information to know which binding point the struct will be used with?

**Comment by kainino0x** [comment]
If not at shader module creation time, then should have enough info at pipeline creation time, since those bindings will have to be defined by that point.

**Comment by kainino0x** [comment]
It looks similar to validation with explicit layouts, anyway. If we had explicit std140/std430 annotations we would have to validate that they're valid for the binding points they're used for. Instead we validate that the offsets are okay for the binding point, and if they're not we suggest offsets for that binding point.

**Comment by damyanp** [comment]
Yes.  This is something where we'll need to do explicit spec work to ensure that these rules are covered explicitly in the spec.

**Comment by kvark** [comment]
Can we just have that `[[layout]]` instead of either offsets or spans - https://github.com/gpuweb/gpuweb/pull/1339?

**Comment by kainino0x** [comment]
I'm pretty sure this is obsolete.
