### ISSUE TITLE
Task: Define order of execution

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#663]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

Consider

```WGSL
a(b(), c());
```

or

```WGSL
const x = a() + b() * c();
```

We need to define the order that `a()`, `b()`, and `c()` happen in. In general, we need to define the order of every operation.

We should research how other languages (perhaps Java, C#, Rust, HLSL, GLSL) do it, and just copy them.

**Comment by dj2** [comment]
The precedence is in the grammar but hasn't been translated into the spec, it was added at the last minute to have for the face to face. The precedence rules for `a() + b() * c()` match those in GLSL which, I believe, match those of C. They just need to be translated into the spec.

**Comment by dneto0** [comment]
> We need to define the order that a(), b(), and c() happen in. In general, we need to define the order of every operation.

It's not 100% clear to me that it has to be a total order.

In the cases you gave, the ones that might have indeterminate order are value-producing expressions. Each of them can have side effects.   When a developer wants to enforce an ordering, they can sequence them by making each its own statement and then sequencing the statements.
e.g.:
 
       const b_val : (whatevertype) = b();
       const c_val:  (whatevertype2) =  c();
       a(b_val, c_val);

Enforcing a total order may constrain the compiler into making lower performing code than it otherwise would have (which I think is why C++  has indeterminate ordering).

FYI.  SPIR-V's program order is total, and described here: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#memory-model-program-order  Being low level, its expressions are already one-step-at-a-time.  _One_ avenue for providing a total ordering for WGSL is to define the mapping from WGSL to SPIR-V.


Secondly, floating point arithmetic in graphics shaders normally assumes --fast-math rules.   This affects order of operations, particularly: + and * are associative, and * distributes over +.

**Comment by litherum** [comment]
> _One_ avenue for providing a total ordering for WGSL is to define the mapping from WGSL to SPIR-V.

This would be a great way to achieve the goal. +1

I hear you about performance, but multiple behaviors for a single program is an anti-pattern for any web spec. In particular, we've bent over backward in the WebGPU spec to reduce/eliminate places where behavior can diverge across implementations. Historically, divergent behaviors have led to non-dominant browsers having to reverse engineer dominant browsers' behavior, which is not something we'd like to repeat again.
