### ISSUE TITLE
Task: Variable scoping is under-defined

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#666]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

There isn't much in the spec about variable scoping. It needs to be filled-out.

**Comment by dj2** [comment]
What were you looking for outside what's in https://gpuweb.github.io/gpuweb//wgsl#scoping ?

Currently there aren't a lot of scoping rules as there is no lexical scoping.

**Comment by RobinMorisset** [comment]
For example it says "The variable is visible at any scoping level which comes after the variable declaration in the source code", but I could not find a definition of "after". From what I've heard you say in the calls, it is supposed to be based on dominators, but when searching for 'dom' I only found the glossary.
For another example I can't see anything about the scoping for parameters. I expect them to be equivalent to a function-scoped variable, and in particular to conflict with their names (since shadowing is not allowed by the language), but could not find it written anywhere.

I realize it may seem pedantic, but having such things written down in the spec can help implementers make sure they're not forgetting anything, and is likely to be especially helpful when writing the test suite.

**Comment by dj2** [comment]
In WGSL, the variable was visible after it's definition. Yes, params are function scoped, there are no shadow variables, so their names have to be unique over that function and the globals.

**Comment by dneto0** [comment]
Linking to #1472 and #1556
