### ISSUE TITLE
Task: Uniformity

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#669]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

The spec needs to include uniformity rules.

**Comment by kainino0x** [comment]
Handy link to @RobinMorisset's uniformity analysis proposal on the mailing list, which is I think the one agreed after the (Mountain View?) F2F. Not sure if this is the latest version, though.
https://lists.w3.org/Archives/Public/public-gpu/2019Jul/0000.html

**Comment by RobinMorisset** [comment]
It is the last version so far, I plan on adapting it to WGSL syntax once it is less in flux. I don't expect any kind of difficulty, it should be straightforward.

**Comment by kvark** [comment]
Also related to #264 and #340

**Comment by kvark** [comment]
@dneto0 @RobinMorisset can we have more clarification on what exactly *uniform* are we trying to enforce here?

There are uniform buffers, and that kind of "uniform" is per draw call. But that's not the uniform we actually need to enforce, if I understand correctly, since that would be overly strict.

**Compute** shaders only care about uniformity within a group, or a sub-group. Since we don't have the latter yet, and the "group" level is more conservative, my understanding is that we would be using that definition of "uniform" (as in - "workgroup uniform") for the analysis of compute entry points.

**Fragment** shaders only care about uniformity within the polygon/triangle. I.e. the derivatives are constant across the polygon, and they should be valid as long as all the invocations within the polygon reach them at the same moment.

Here is a note from [this document](https://www.khronos.org/opengl/wiki/Sampler_(GLSL)#Non-uniform_flow_control) about SPIR-V that I read as supporting the view I'm presenting:
>  SPIR-V provides has a more generous definition of uniform control flow. Normally, what is considered dynamically uniform is an expression which has the same value in all invocations within the same group, with "the same group" being "within a rendering command". However, for the purposes of defining when implicit derivatives are available, SPIR-V makes "the same group" be all invocations within a Primitive being rendered, which is a much smaller scope. This would mean that the gl_PrimitiveID input variable would be considered uniform for the purposes of determining derivative availability, even though it is not normally dynamically uniform. Note that the GLSL 4.60 specification does not state this. However, hardware that can run OpenGL 4.6 can also run Vulkan, and therefore it may use the more generous definition

As a consequence of this, branching on a "flat" interpolated value should be considered uniform control flow (for the purposes of our validation of derivatives). This is a little bit controversial, since the link I provided indicates that the very same case would not be considered uniform in GLSL (but it looks like SPIR-V does consider it uniform). However, I'd like to stress on importance of this for a number of use cases. Imagine a mega-fragment-shader doing this:
```glsl
flat in int some_flag;
if (some_flag) {
  do_one_thing();
} else {
  do_other_thing();
}
```

We'd want both `do_one_thing()` and `do_other_thing()` to be accepted for uniform control flow. The user may want to sample with different texture coordinates there, since these can be completely unrelated paths. At the same time, the user would want to make a draw call containing a mix of different `some_flag` values, and it should be fine as long as each primitive gets a constant flag. We use this general pattern in WebRender, although without sampling textures in those paths, so this case is not entirely theoretical.

Finally, for the **vertex** shaders the uniformity may be most controversial (i.e. per-draw-call or per-instance), but thankfully we don't need to care about this too much, since vertex shaders have neither workgroup barriers or derivatives. So it looks like the analysis isn't even needed for them?

**Comment by kvark** [comment]
@alan-baker commented in https://github.com/gpuweb/gpuweb/pull/1571:
> Vulkan defines invocation group as workgroup if that is a defined concept, otherwise it is the command. See https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#shaders-scope-command
>    For shaders without defined workgroups, this set of invocations forms an invocation group as defined in the SPIR-V specification.
> SPIR-V only defines uniform control flow (i.e. divergence and reconvergence) in terms of invocation groups. See https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#UniformControlFlow.

SPIR-V spec appears to be incomplete then. It is indeed talking about reconvergence only within an invocation group, but it *does* use the notion of divergence within smaller scopes, such as the derivative group:
> Texturing instructions in the Fragment Execution Model that rely on an implicit derivative won’t be moved into control flow that is not known to be **uniform control flow within each derivative group**.

Where the derivative group is clearly bound by the current primitive:
> The set of invocations collectively processing derivatives, which is at most as large as a single point, line, or triangle, including any helper invocations, as defined by the client API.

So it appears to me that `if (my_flat_interpolated_value)` could still be considered "uniform" for the purposes of our control flow analysis (in fragment entry points), since it doesn't diverge within the derivative group.

**Comment by alan-baker** [comment]
The spec isn't incomplete, it just has fewer guarantees than you'd like I think. Derivatives are ok if the performed within control flow that is uniform within a derivative group, but the spec doesn't guarantee how derivative groups will reconverge so, yes, there is limited utility.

I do agree that for the purposes of derivatives that a flat interpolated input could be considered uniform for the analysis. I cannot think of a situation where that would be violated that would not be caught by the analysis, but I need to spend more time reviewing the uniformity analysis to sure.

If subgroups are introduced in the future though the flat interpolated value would not be uniform at the subgroup level.

**Comment by kvark** [comment]
To be precise, if I understand correctly, the case you are talking about is:
```
loop {
  if (quad_uniform_1) {
    // (1) a valid place to get derivatives
    break;
  }
  if (non_uniform_1) {
     // (2) obviously not a valid place for derivatives
  }
  // (3) is it a valid place for derivatives?
};
```
If we do a naive quad-uniformity scope analysis, then the (3) would be considered quad-uniform. But since the re-convergence is guaranteed only at the subgroup level, the code at (3) will not re-converge yet (after branching of (2)), and thus can't be quad-uniform. Am I close?
