### ISSUE TITLE
Task: Define short circuiting for && and ||

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#675]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

```WGSL
if (a() && b()) {
    ...
}
```

We need to define the situations where `b()` gets executed.

**Comment by dneto0** [comment]
Follow C's rule:  
- a() is evaluated.  
- if a() evaluates to false, then the whole expression evaluates to false, and b() is not executed
- if a() evaluates to true, then evaluate b() and the whole expression evaluates to the result of evaluating b()

**Comment by krogovin** [comment]
What are the precise conventions in Metal shading language and HLSL? I ask because for MS-Windows and MacOS the shaders will be converted to those, so if their convention is different (the main issue being for image-load-store), then the conversion process will have to turn

`if (a() && b()) {
    ...
}`

into

`if(a()) {
    if(b()) {
   }
}`

and in general will require writing about more branching code ... and excessive branching code can make driver compiler backends quite grouchy and if too deep, even fail.

**Comment by dneto0** [comment]
Some further investigation:

HLSL:
  -   && and || are not short-circuiting.  [Reference](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-operators#boolean-math-operators):

   - > Unlike short-circuit evaluation of &&, ||, and ?: in C, HLSL expressions never short-circuit an evaluation because they are vector operations. All sides of the expression are always evaluated.

   - > Boolean operators function on a per-component basis. This means that if you compare two vectors, the result is a vector containing the Boolean result of the comparison for each component.

GLSL
 -   && and || are short-circuiting, and only operate on scalar boolean operands.

SPIR-V 
  - OpLogicalAnd operates on scalar and vector bool.  It is not short-circuiting.

MSL
  - && and || operate on booleans and vector-of-bool (I think?):
  - > "The logical operators [and (&&), or (||)] act upon two operands that are Boolean
expressions. The result is a scalar or vector Boolean."
  - The rest of MSL is supposed to be based on C++14, which has short-circuiting behaviour.   I don't know what that does for the vector-of-bool case.


Currently, the WGSL spec has:
 - bool and scalar form
  - not short-circuiting.


I like the idea of having a short-circuiting operation and a vector logical-and.  But it seems non-sensical to have the vector-form short-circuit.  It seems a bad idea to have one form short circuit and the other one not.

So this ended up being more subtle than I had anticipated.

**Comment by dj2** [comment]
Tint currently implements `&&` and `||` as short-circuiting. It was my original intention to update the WGSL spec to make them not use `OpLogicalAnd` and `OpLogicalOr` and to make them short circuit, but I didn't bet there before we opened the spec.

**Comment by dneto0** [comment]
We could do the following:
- Define && and || over scalars, and make it short-circuiting
- Allow & to operate on bool scalar and bool vector, with vector evaluation being point-wise.  (This is what would map to && in HLSL for the vector case)
     - Note that in C++, & only operates on integral operands.

**Comment by johnkslang** [comment]
> SPIR-V

> OpLogicalAnd operates on scalar and vector bool. It is not short-circuiting.

I don't think short circuiting is a thing to be one way or another at the SPIR-V level.  The evaluation is not done by `OpLogicalAnd`, it was done earlier by other instructions.

This is the heart of what's going on with the HLLs, so pretty relevant.  For an HLL operating on scalars, short-circuiting is a choice, for an HLL operating on vectors it is not a choice, and for SPIR-V the choice is non-existent.  (Glslang correctly sorts all this out for the HLLs and SPIR-V.)

**Comment by johnkslang** [comment]
Also of note is types allowed to operate on.  GLSL does not do implicit type promotion from numerics to Boolean:

- `&&` requires Boolean input
- `&` requires numeric input

You could argue short-circuiting is an HLL feature, and doesn't belong in an IR like WGSL, but I think it's just a choice to make.

However, I don't see too much choice that `&&` operates on Booleans (like GLSL).

So, endorsing https://github.com/gpuweb/gpuweb/issues/675#issuecomment-654470724 but, think you also want to be explicit (and tight) about the types allowed as well.

**Comment by grorg** [comment]
Discussed at the [2020-07-07 meeting](https://docs.google.com/document/d/1jiRiUAEBkG1UPFZTTeEx81HCXlrTeucCrfATIFBhzzI/).

**Comment by jdashg** [comment]
We decided to adopt https://github.com/gpuweb/gpuweb/issues/675#issuecomment-654470724.
