### ISSUE TITLE
C-like declaration order

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#677]
We've heard from a few developers that they actually use the same source on both GL and DX. They get away with it by just doing things like `#define vec4 float4` and their source is simple enough that it just works. We should consider allowing the same kind of solution in WGSL.

Loop sugar would be helpful in this regard too: https://github.com/gpuweb/gpuweb/issues/569

**Comment by litherum** [comment]
See also: https://github.com/gpuweb/gpuweb/issues/593

**Comment by Jasper-Bekkers** [comment]
> We should consider allowing the same kind of solution in WGSL.

We (games industry as a whole) is desperately trying to move away from doing things like this for as much as we can by relying on a standardized IL fwiw.

**Comment by dneto0** [comment]
I'm against this proposal.  (Didn't some CG members spend 2.5 years arguing that the web was so special that it deserved its own bespoke shader language?)

If macros have taken those developers this far, more macros might help them get further.

Off the top of my head:

```
#if LANG==WGSL
#define I32 i32
#define ARG(name,type) name : type
#define FUNDEF1(ret,name,arg)  fn name(arg) -> ret
#elseif LANG==GLSL
#define I32 int
#define ARG(name,type) type name
#define FUNDEF1(ret,name,arg) ret name(arg)
#endif
```

Example usage:

      FUNDEF1(I32,foo,ARG(a,I32))

**Comment by dneto0** [comment]
Sorry, I should withdraw the backward-looking parenthetical statement.

**Comment by kvark** [comment]
I think trying to suite ISVs who generate backend shaders by preprocessing would put us in an entirely different spot than we are today. This wasn't a design constraint at any point, other than a consideration for Apple's experiments with WebHLSL.
We just want a language that will be easy to specify correctly (so, borrowing SPIR-V semantics) and yet potentially writable with a text editor. Can we *not* blow this feature scope by trying to mimic HLSL/GLSL, which we considered unacceptable for WebGPU?

**Comment by krogovin** [comment]
I disagree with much of the above; having the syntax ordering that same as current shading languages will give me more chances to reuse existing shader code instead of rewriting shaders.

>  I don't think that this is necessary. We should expect ISVs who have an existing GLSL/HLSL codebase to use a compiler from GLSL to HLSL to WGSL rather than use preprocessor tricks to generate the WGSL.

This is only feasible for applications whose shaders are generated at build time. For applications where shaders are assembled at run time, this then necessitates the application including such a pseudo-compiler.

At any rate, I cannot even see a reason what a different syntax for structure and function declarations even gives to the developer story.

**Comment by grorg** [comment]
Discussed at the [2020-04-14 meeting](https://docs.google.com/document/d/1bdIA5GS0yMDXcHZ0U_CtxYp6jLfJqVlGPBgcQ0aOEkc/).

**Comment by grorg** [comment]
(playing ping pong with the meeting label)

**Comment by grorg** [comment]
Opinions from at least @dneto0 and @jdashg were expressed in the meeting and will be added here.

**Comment by jdashg** [comment]
I think especially with type inference, it's nice to see `const foo = bar + 1;`.
I think it's cleaner as `(const|var) IDENT (: IDENT)?`, whereas it's `const? auto|IDENT IDENT` in C++ish, and `(const? IDENT)|auto IDENT` with `const` instead of `const auto`.

I think it's going to be harder to have polyglot shaders include WGSL for other reasons, so making variable declarations more polyglot friendly is not very compelling to me. (They are still possible as dneto pointed out)

**Comment by krogovin** [comment]
Here is my point of view.

A shading language that is too different from existing shading languages is *MAJOR* barrier. The current code base I am working on has over 8000 lines of hand written shader code that is assembled together at run time to mix and match various shader functionality. This is actually a pretty common practice. Through macro-functions and a sprinkling of machine generated code, I can support many of the variants of GLSL, HLSL and Metal SL. The reason being that they are all quite similar in syntax. Now, we get to WGSL: the syntax for declaring structs and functions is very different. Hiding this behind macros is untractable. How functions are declared is also horribly different. The ideas to make WGSL share more in spirit with JS move it further from the current shading languages. The vast majority of complaints about parsing being harder for the more traditional languages I do not buy for the simple reason that the ability to parse these languages at run time is already a solved problem with a number of open source solutions.

There are a number of possible solutions that might be quite attractive to everyone. One solution is this:
have WGSL be its own language with a syntax independent from existing shading languages. However, also allow WGSL to accept subsets of other shading language (with what features exposed well defined and branching, dFdx/y, discard and sampling conventions the same as WGSL). Keep in mind that if WGSL ends up being the only shading language that is too different from all others, that means applications that generate shaders at run time will inflate by a quite large amount to have something to covert their shaders to WGSL. That solution is quite bad, not just from the code bloat but also that a fair number of those translators will be semi-unreliable (being generated in house too often) and also take a fair amount of developer time to deal with an issue that should never have existed.

**Comment by dj2** [comment]
The problem being, the function declarations are just the tip of an iceberg. The builtin and location assignment are different in WGSL. Variable declarations are different. How arrays, and pointers are declared is different. Loops are different. How your workgroup size is specified for a compute shader is different.

Using macros to rewrite your shaders would mean everything would need to be re-done to match GLSL, HLSL or MSL. At which point, you may as well have used one of those languages, and that was rejected by the group.

Yes, you can change the parser around to work in a c like order. Yes it is harder to parser as there is ore ambiguity. That means the parser is more complicated which means there are more areas for divergence between implementations.

If you're building shaders at runtime you always have the option of compiling to SPIR-V and then using one of the tools being developed to convert from SPIR-V to WGSL. I believe Naga is planning on providing that option, and Tint is currently working on SPIR-V to WGSL. Naga is Rust, Tint is C++, in both cases they could probably be compiled to WASM to be used online.

**Comment by krogovin** [comment]
Just so we are clear what the proposal is for ISV's to do:

1. Add to the application payload a GLSL, HLSL, or MetalSL to SPIR-V compiler, as for example from the Khronos tool chain
2. Application does the string operations as usual to assemble it shaders and then feeds them to the compiler added to the application payload
3. Somehow make sure that the SPIR-V created by the Khronos tool-chain will be convertible to WGSL correctly. This is non trivial because the Khronos tool chain generates SPIR-V using the full blown SSA and CFG where as the SPIR-V that WGSL is convertible from uses OpLoad/OpStore and no SSA. Naturally it is possible (or ideally likely) that those tools will handle correctly the SSA and CFG stuff to WGSL.  

Then, the browser will take that WGSL, convert it back to SPIR-V (for Vulkan native target) using OpLoad/OpStore which it will in turn convert through a Khronos tool to an SSA shader (hopefully).

This is excessive conversion to put it mildly and I would not at all be surprised that eventual shader fed to Vulkan for the SPIR-V case will be far from optimal. The end result HLSL and MetalSL shaders will be next to impossible to read. I shudder to think how I would ever be able to optimize the shaders in question either. The situation with the current 3D API's makes it hard, but not impossible. The approach above makes it beyond hellishly difficult.

Going this route makes application code unnecessarily bloated (by a great DEAL), risks shader performance all in the name of WGSL having a different syntax than the shading languages found in any of the 3D API's. Not just the declaration order, but that the syntax and constructs of WGSL being so different than the other current-in-use shading languages does not serve developers at all.

I really think the working group needs to go back and think on its direction of WGSL. What it looks like to me is that initial vision of using SPIR-V was good but rejected and what was left... was the worst of all possible worlds.

I am not the first and I will not be the last to bemoan using a different shading language with such a radically different syntax. To put it mildly, the approach of WGSL jeopardizes my ability to port work to WebGPU .

**Comment by dj2** [comment]
Even if WebGPU accepted SPIR-V you would still need to do 1-3. You have to bundle the SPIR-V compiler. You have to concatenate the strings and you have to compile to SPIR-V. You then have to make sure the SPIR-V is WebGPU SPIR-V and not Vulkan SPIR-V as WebGPU would use a restricted subset of SPIR-V probably using SPIR-V Tools optimizer.

I don't understand what `SPIR-V that WGSL is convertible from uses OpLoad/OpStore and no SSA` means. You can pass SPIR-V that uses SSA into the SPIR-V -> WGSL conversion and it should work (it's still being written which is why I say should).

**Comment by dneto0** [comment]
(Not trying to address the most recent comments).

At some point I said that C declarations are harder to read because of excessive lookahead requirements.  During the meeting @litherum stated that was because of the "*" part of C declarations.  That's not the only thing.  For example, array declarations:

      int a, b[12];

In this fragment, the type of `b` is assembled from the tokens `int` and `[12]`, separated by `b` itself and by an entirely unrelated identifier.

The proposed syntax for WGSL has a very regular sublanguage for types, where a type is fully specified by tokens that _appear contiguously_.  This buys you readability, and it simplifies everyone's tooling.  It also gives you a value-constructor syntax for free, e.g.
    
      u32(12)
      arr<i32,3>(1,2,3)  
      arr<i32,5>()    // an array of 5 zeros, if the proposal from #685 is followed

**Comment by kvark** [comment]
@krogovin 

Thank you for your feedback! I share a lot of concerns you have, but I think aligning with C is not a solution to them.

> The grammars for the various shading languages, for example GLSL and HLSL already exist and have open source implementations for their parsing.

GLSL parsing in the drivers is notoriously bad, and HLSL was designed for off-line parsing to begin with. Just because C grammar is parsable doesn't mean that we can't opt into something simpler that we can parse faster with less code.

> This is non trivial because the Khronos tool chain generates SPIR-V using the full blown SSA and CFG where as the SPIR-V that WGSL is convertible from uses OpLoad/OpStore and no SSA

WGSL today has `const` (which is analogous to SSA) and `var`, so going SPIR-V -> WGSL -> SPIR-V will fully preserve SSA. Having this route being simple and effective is one of the goals for us (at least, for a large part of us), see https://github.com/gpuweb/gpuweb/issues/692 .

> The end result HLSL and MetalSL shaders will be next to impossible to read.

I think this needs more evidence. Conversion from SPIR-V to these have been explored by SPIRV-Cross. It's not perfect, but I was able to read it. I think we can do better, even. TODO: attach "boids.metal"

> The approach above makes it beyond hellishly difficult.

Do you expect it to be more difficult than optimizing *any* shader pipeline that's based on SPIR-V? Please elaborate.

**Comment by krogovin** [comment]
Let me reiterate what I would need to do to support WGSL as proposed: I would need to bundle with the web-app the code to do the sequence: (GLSL/HLSL/MetalSL)-Like --> Something(Likely SPIR-V) --> WGSL. That is a significant conversion sequence with quite a bit of code.

My use case and issues are far from unique. It is seem dubious, at best, to have many applications have as part of their payload the above code to do this whereas it makes more sense for that to be shared. Since it is the web, sharing means implemented by a browser.

> Do you expect it to be more difficult than optimizing any shader pipeline that's based on SPIR-V? Please elaborate.

The fewer steps between the source shader and what the driver consumes the better chance I have of fixing shaders and working around hardware and compiler backend bugs in drivers. I have encountered enough hardware and driver bugs (none of which came from parsing) from shader compilers to distrust thicker and thicker stacks.

The shader example you gave, boids.metal.txt is much simpler than the shaders I am dealing with: its control flow is relatively simple and it is in control flow that shader compilers most often slip-up. 

Even conceding the point that the conversion makes debugging more painful (which my gut reaction is that it is going to make it more painful), many developers will need to either port their shaders to WGSL or add several megabytes to their web application code just because the syntax is SO much different than the other shading languages.

Lastly:

> GLSL parsing in the drivers is notoriously bad, and HLSL was designed for off-line parsing to begin with.

This I do not buy as a valid reason. I can name three open source implementation of GLSL parsing off the top of my head that are rock solid. Ironically one of them is in ANGLE which is used a great deal in browsers already and the other is part of the SPIR-V toolchain both of these use the traditional lex & yacc way to realize the syntax tree from the shader source. The third I know of, Mesa, also use the lex & yacc front magic. In truth the real hard part of the current WGSL proposal is not the parsing (even if it was C-like), but all the shenanigans needed to do the OpStore/OpLoad to SSA conversion needed to make a reasonably well performing shader.Additionally, I can see issues in that the current WGSL's loop construct will make it tricker (though admittedly not impossible) for driver shader compilers to unroll loops.

All I am requesting is to make the syntax more like that which is already ubiquitous for shaders to dramatically reduce porting pain and/or reduce web application pay load and dependency size.

**Comment by dj2** [comment]
> Let me reiterate what I would need to do to support WGSL as proposed: I would need to bundle with the web-app the code to do the sequence: (GLSL/HLSL/MetalSL)-Like --> Something(Likely SPIR-V) --> WGSL. That is a significant conversion sequence with quite a bit of code.

You'd still have to do this with SPIR-V. You have to go (GLSL/HLSL/MetalSL)-Like -> SPIR-V -> WebGPU SPIR-V.

> Since it is the web, sharing means implemented by a browser.

There is lots of sharing on the web that isn't in the browser, things like React, jQuery, backbone, etc.

>  but all the shenanigans needed to do the OpStore/OpLoad to SSA conversion needed

At least in the WGSL->SPIR-V case, for Tint, this will be done by SPIRV-Opt which is the same conversion code used to optimize SPIR-V from GLSLang.

> I can see issues in that the current WGSL's loop construct will make it tricker (though admittedly not impossible) for driver shader compilers to unroll loops.

If you see issues with the current constructs please file issues.

**Comment by krogovin** [comment]
> There is lots of sharing on the web that isn't in the browser, things like React, jQuery, backbone, etc.

The size of these and that they are in JS makes it more natural and OK to have them again and again as part of a application payload.

> You'd still have to do this with SPIR-V. You have to go (GLSL/HLSL/MetalSL)-Like -> SPIR-V -> WebGPU SPIR-V.

I thought my previous replies made this obvious why this is a much bigger issue on a web-application. For a native app, bundling the tools to do GLSL/HLSL/MetalSL)-Like -> SPIR-V  is essentially a one-time download/install of the native application. On the other hand, for a web-app that code needs to be downloaded and recompiled (more or less) each time the web page is visited. Such code bloat significantly slows down web-app startup.  Another really important point for native: there is no platform that requires one to feed shaders as SPIR-V. Indeed, for the main platforms that support Vulkan (namely MS-Windows and Android), they also Direct3D and GL. On the Apple side (i.e. iOS and MacOS), one can deploy MetalSL in source form for run time assembly as well.

Going further, the tools from Khronos, especially the GLSL--> SPIR-V side, are made to be incorporated into applications with headers giving a very stable interface. Indeed, part of the charter of Khronos is to provide a tool chain, SDK and libraries to handle that SPIR-V is not meant to be hand generated. In contrast the W3C and the WebGPU have nothing like that in their charter. Instead, we have hopes, not guarantees or promises, that the libraries made by the browser vendors (specifically Mozilla and Google) to help implement WebGPU will be also useable by developers (especially the WASM side of it) to do shader generation. However, those promises are going to become quite thin because one of WGSL's goal is to be a human readable an writeable language which in turn weakens the  need for such a tool chain.

Now return to the main point: by making the WGSL more like the other shading languages in syntax, a developer can avoid risk and the need for additional code in their application. All that I am asking for is to have the syntax similar to existing shading languages. I am not asking for GLSL, HLSL or MetalSL; just a language that is similar in syntax to the -three- already existing languages. Worse, I have not seen a single convincing argument that this different syntax is better for **users** of WGSL. All I have for response is that it is easier to parse. That is not a good reason considering that the parsing is still at easy level (given that there are multiple open source parsers for them and that parsers for such language syntax have been around for decades). On flip side, by making the syntax so different, in order for a developer to avoid rewriting their shaders they will need code to do that parsing anyways. Be it from promises (with no guarantees) that a library used to implement WebGPU will have it or another dedicated tool chain, we will still need to have such parsers. Again, better that the browser has that implementation.

Much better to avoid the entire fiasco and just make the shading language syntax like the others and allow developers to do what they have been doing before.

**Comment by Jasper-Bekkers** [comment]
>Now return to the main point: by making the WGSL more like the other shading languages in syntax, a developer can avoid risk and the need for additional code in their application. 

This has significant overhead for larger applications in the AAA games space where compiling the massive amounts of shaders takes up valuable load time. This is why in vulkan we settled on offline compiled binary IL in SSA form. That way we can send the binary blob into the driver and have it churn through it quickly, even without having to restructurize control flow.

WebGPU at the moment is proposing a Frankenstein model that sits directly in-between what you want and what AAA needs.

At the moment everybody is pasting text shaders together; the path everybody is working towards is building tooling to be able to do that on an IL level instead since pasting text together has significant overhead and is quite error prone, having a more structured model around IL manipulation that is identical for SPIRV and the WebGPU-frankenshader model is where is should be headed. We have also long forgone the days of pasting JavaScript together and calling eval on it, so why expect the same to be applicable for a GPU?

> Much better to avoid the entire fiasco and just make the shading language syntax like the others and allow developers to do what they have been doing before.

This unfortunately isn't very forward looking and incurs real, multi hour, performance overhead that we would like to spare our users from.

**Comment by krogovin** [comment]
For my use cases, it is highly impractical to ship all shader combinations possibilities, the combinatoric explosion is immense. Indeed, many AAA games actually do ship a massive library of compiled shaders and for some engines (though many do not suffer from this), they find themselves with tens to hundreds of megabytes of compiled shader payload. On native this is ok, but on the web needing to download such shaders be it all at once (horrible startup times) or first use (massive stutter) is not to be taken lightly.

The other approach it to implement a massive uber-shader, which carries a significant performance overhead (even if the branching within the uber is non-divergent per draw-call).

> This unfortunately isn't very forward looking and incurs real, multi hour, performance overhead that we would like to spare our users from.

There is a pretty simple way out of this, especially for applications not suffering from a combinatoric explosion, have WebGPU accept two different ways to specify a shader: a human readable shading language (ideally similar in syntax to existing shading languages) and also accept shaders compiled to an IL. This is the model that Direct3D follows and brings the best of both worlds together.

**Comment by Jasper-Bekkers** [comment]
> For my use cases, it is highly impractical to ship all shader combinations possibilities, the combinatoric explosion is immense

This is the exact same problem for AAA ;- but it can easily result in 50MB+ shader databases after compression.

> There is a pretty simple way out of this, especially for applications not suffering from a combinatoric explosion, have WebGPU accept two different ways to specify a shader: a human readable shading language (ideally similar in syntax to existing shading languages) and also accept shaders compiled to an IL. This is the model that Direct3D follows and brings the best of both worlds together.

I'd be super OK with this, I still think runtime compiled shaders are a mistake to make (shader compilation easily takes several milliseconds), but at least this way it's not a mistake everyone is forced to make.

**Comment by krogovin** [comment]
FWIW, every driver still does a quite heavy compile nasty job in Vulkan with SPIR-V. There are loads of optimizations that can only be carried out after lowering and what is best for control flow is quite subtle. Compounding the issue is that because 3D graphics is so competitive (which is actually a good thing really), IHV's will do what they can to squeeze out a few extra percentage points in performance. Sometimes they do things they should not do either 😄 

On native for PC's this is semi-solvable by allowing an application to save the binary blobs of pipeline object; in truth nearly every driver does this for an application though their shader caches.

**Comment by jdashg** [comment]
Support for binary blob reuse (same-machine warm-load) is something we intend to support eventually. (Portable IRs don't really solve that)

One of the side-effects of how we're designing WGSL is that, though it's text-based, any binary-IR concatenation/linking you'd do would have a analogous viable text-IR concatenation/linking transform you could use instead. (not to mention that you can also do the transform in spir-v before translation to wgsl)

**Comment by litherum** [comment]
> allowing an application to save the binary blobs of pipeline object

We have to be careful of the security guarantees of the web. We can't let authors circumvent bounds checks by modifying one of these binary blobs.

**Comment by Jasper-Bekkers** [comment]
> > allowing an application to save the binary blobs of pipeline object
> 
> We have to be careful of the security guarantees of the web. We can't let authors circumvent bounds checks by modifying one of these binary blobs.
> 

That seems like a solved problem, all image decoders, and other binary parsers such as the ones for WASM deal with this just fine.

> (This could be accomplished by having the browser do it instead of the website, thereby not adding any new API surface. This also could potentially be accomplished by signing the binary with a public/private key pair.)

And they deal with it without having to sign the binaries, so I'd really don't see why you would want it for bounds checking. Also it seems completely counter to having an open web.

**Comment by kainino0x** [comment]
> On native for PC's this is semi-solvable by allowing an application to save the binary blobs of pipeline object; in truth nearly every driver does this for an application though their shader caches.

> That seems like a solved problem, all image decoders, and other binary parsers such as the ones for WASM deal with this just fine.

I think(?) we're talking about vendor/driver-proprietary blobs, which cannot be standardized and validated.

If anyone wants to continue this conversation, would you mind filing a new issue? This is off-topic.

**Comment by Jasper-Bekkers** [comment]
> WGSL today has const (which is analogous to SSA) and var, so going SPIR-V -> WGSL -> SPIR-V will fully preserve SSA. Having this route being simple and effective is one of the goals for us (at least, for a large part of us), see #692 .

This seems like a bit of an odd design choice. Surely, as soon as there's /one/ `var` in there, all of the SSA niceness (see why you'd want it, here: https://www.youtube.com/watch?v=_ilAL-1-moA) goes out of the window. Either this would need to be a per-shader attribute, or this should just be SSA by default. But even then seems like the ultimate design-by-committee compromise.

**Comment by kainino0x** [comment]
`var` directly exposes a concept present in SSA IRs (alloca, "stack-allocated" memory, in LLVM). It's a memory location from which you can load and store SSA values.

@kvark had a thread somewhere about having an explicit syntax required to load from a `var` into a SSA value, though I can't find it anymore.

**Comment by kvark** [comment]
It was #622

**Comment by CrazyPython** [comment]
#888

**Comment by CrazyPython** [comment]
People expect web applications to boot quickly. Remember that when suggesting application developers ship shader compilers in the browser.

**Comment by CrazyPython** [comment]
> The builtin and location assignment are different in WGSL. Variable declarations are different. How arrays, and pointers are declared is different. Loops are different. How your workgroup size is specified for a compute shader is different.

That can be handled using `#ifdef` sections. Still, the core matrix transform logic is the same across all compilation targets.

**Comment by krogovin** [comment]
> That can be handled using #ifdef sections. Still, the core matrix transform logic is the same across all compilation targets.

This is somewhat true, but not without producing code that is terribly macro laced with nasty hard to read macros. The other shading languages declare variables C-style "type v1, v2, ..vN;" where as WGSL has a very different syntax. The consequence is that having a macro to declare variables will get ugly faster. In contrast the layout() stuff is more macro friendly.

That is just declaring variables. So many other things are so different that trying to hide behind macro's becomes nearly intractable. The truth is that if one wants to have common shaders for WebGPU and other 3D API's one will need to have in one's application a something that coverts to WGSL.

FWIW, the situation with WGSL is going to make my work much more difficult because of its very different syntax. However, it looks like the decision is set in stone and people with projects across web and other native platforms are either going to rewrite their shaders or add to the application the  ugly of a shader converter to their web application. Plenty of folks decried this syntax, but their voices lost. Sighs.

As far as speed goes, the issue won't be the conversion of shaders, since the browser need to covert WGSL to something native anyways; the real issue is that a web application needs to also have its application code to covert to WGSL which will make the JS JIT or WebAssembly JIT work on that much more code.

**Comment by dj2** [comment]
This was discussed at the [WGSL meeting on 2020-07-21](https://docs.google.com/document/d/17mqJR40z325U_jftDBxOYAjbzdFxKCQiIUXDEI8d9k4/edit#). The summary being, there are positives and negatives on both sides of this debate.

 * Pro: There are existing shaders folks would like to reuse
 * Con: We have momentum with the current language, implementations are moving forward
 * Con: Currently syntax aligns us more with languages like Rust and Swift.
 * Con: Easier to introduce parsing ambiguities.

Taking that into considering we're continuing with the direction we have which is the more Swift/Rust like syntax and will not be revising the grammar to have a c-like declaration order.
