### ISSUE TITLE
Portability concern about adapter extensions and limits

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#684]
The current API model is `GPUAdapter` exposing limits and extensions, and in `GPUDeviceDescriptor` the user can opt into higher-than-standard limits by providing these structures.

The use case I'm worried about is people just passing the `GPUAdapter` capabilities straight into `requestDevice` regardless of which they need. Why this is concerning: developers tend to use more capable machines. They can easily hit a situation where something that works on their machine suddenly doesn't work on a user machine. This is a portability problem by definition.

Perhaps, if we just make it a little bit less straightforward to request *all* the limits and extensions (for example, have an API requesting a single limit/extension), then dev wouldn't be encouraged to do the wrong thing here.

(spawned from a Matrix discussion)

**Comment by kainino0x** [comment]
We've talked about this a few times before, here are the options I remember:

- Make the output of adapter.limits/adapter.extensions incompatible with the GPUDeviceDescriptor fields (but I think we've found the "right" design here already, at least for extensions, and don't think we should change it for this)
- Add an extension for "lose on creation for testing" (which could actually be useful), so you'd have to at least filter that out. Would have to do something silly for limits though.
- Generate a warning if everything is enabled or set to max limit

**Comment by jdashg** [comment]
I feel like WebGL showed that it's not an area of concern, and hypothetical issues here haven't generally shown up in practice in the years and years of shipped WebGL content.
It might be possible to do better, but that's premature optimization to me.
Novel hypotheticals would need to address what's different about WebGL or other APIs that may cause them to not have these hypothetical issues.
But I feel like our time is better spent on more pressing issues.

**Comment by jdashg** [comment]
To be clear, super within their rights for any UA to issue warnings about any content they perceive/suspect to deserve it.

This is common in WebGL. Firefox even warns if you try to render-to-float without explicitly requesting that extension. (the float-RTT extension is implicitly enabled (where supported) when float-textures are requested)

**Comment by kvark** [comment]
@jdashg 
> But I feel like our time is better spent on more pressing issues.

That time argument. Regardless of when this will be looked at, it's good to have it filed and tracked. We had multiple discussions on the topic, and somehow no single place to get a record of them.

> I feel like WebGL showed that it's not an area of concern, and hypothetical issues here haven't generally shown up in practice in the years and years of shipped WebGL content.

Not only this is surprising, but also contradicts @kainino0x 's input (from Matrix):

> we definitely see content that is authored against desktop and then ends up not working on mobile, or authored against whatever mobile hardware the developer has on hand and not working on iOS

**Comment by jdashg** [comment]
I'll note that I did include "generally" there! :)

If we steel-man what I said:
> I feel like WebGL showed that it's not an area of concern, and hypothetical issues here haven't generally caused serious problems in practice in the years and years of shipped WebGL content.

I stand by this remark.

Specifically, most of the portability problems WebGL had with mobile was caused by mis-steps during specification (render to float) for which we already have careful require-getExtension protections on. Others were deliberate ambiguities coming to us from native specs, such as precision of DEPTH_COMPONENT16 or whether RGB8 is renderable. More protections would not have helped, and we got through these problems fairly cleanly.

I am not strongly concerned about these problems today, and as such I am not strongly concerned about going further in addressing these problems in new APIs.

It's fine to keep track of it, and I'm happy to restrict further discussion to this issue, as opposed to it repeatedly coming up on Matrix, where I feel compelled to respond repeatedly.

**Comment by kainino0x** [comment]
Editors discussion: We think we should add a field on GPUDeviceDescriptor like "allowNonDefaultCapabilities" (defaulting to false) that you have to set in order to use higher limits. That way you can pass-through limits and extensions if you really want to, but there's a bit of code where you confirm that it wasn't an accident.

**Comment by kvark** [comment]
We sorta came to this simultaneously with @kainino0x , and I'm very happy about this outcome. Name `allowNonDefaultCapabilities` is subject to bikeshed ;) Overall, seems like a very small and non-intrusive change that resolves my concern about portability.

**Comment by kainino0x** [comment]
@jdashg WDYT of this proposal?

**Comment by kainino0x** [comment]
More or less resolved to accept `allowNonDefaultCapabilities` (name open to bikeshed).

However this is blocked on #495, which adds GPUAdapter.limits in the first place.

**Comment by jdashg** [comment]
It feels like busywork to add this req, but it's tolerable. :)
