### ISSUE TITLE
Anisotropic clamping for SamplerDescriptor

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#696]
We have the anisotropic extension string, but no associated API to set the clamp.
I wonder how this will be specified: just adding a member to `SamplerDescriptor` may look like this is a part of the core spec.

**Comment by kainino0x** [comment]
nit: The `"anisotropic-filtering"` extension string was a placeholder extension string; since then we added a real extension `"texture-compression-bc"` so removed the placeholder. Obviously we should add back the extension (with actual support) though.

My proposal with "extensions" is still to include them in the core spec, rename them as "capabilities" or "features", and come up with some way to clearly demarcate them in the spec so that you can tell they're optional.

Note also that the [error conventions](https://github.com/gpuweb/gpuweb/blob/master/design/ErrorConventions.md), as currently stated, mean the API should reject any usage of an extension if it's not available.

> If any object in A contains any key that is not core or part of an enabled extension: Error must be synchronous.
> 
> This is explicitly made more strict than the usual WebIDL dictionary binding rules.

Unfortunately it is currently unimplemented in the spec and not implementable directly in WebIDL.

For portability (between browsers), it's necessary to have either this rule, or a replacement one that says:

> All dictionary members from extensions must be optional and have type WebIDL type `any`. This makes using them valid, and behave the same, if either unsupported by the browser or not enabled on the device. Type checking rules must be defined in the specification such that they apply only when the extension is enabled on the device.

**Comment by kainino0x** [comment]
You added the "for meeting" label; what do you want to discuss?

**Comment by kvark** [comment]
Basically, get everyone's :+1: for adding it to the WebIDL.

**Comment by kainino0x** [comment]
Resolution: move anisotropic filtering to core, but make it a hint. If the device doesn't support anisotropic filtering, then it just won't happen.

Consider adding a query (maybe later?) that reports either 1 or 16(+?) for the max anisotropy.

**Comment by jdashg** [comment]
2020-06-15 Meeting: Let's add a maxAnisotropy value to samplers, and a maxAnisotropy limit(? query?) (likely only ever 16 or 1), but *not* to validate that the former is less than the latter.

**Comment by kvark** [comment]
I don't think there is a consensus on exposing the limit/query. Made a proposed API PR in #864 without them.
