### ISSUE TITLE
Implicit conversion to bool?

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#733]
It's extraordinarily common in programming languages for to use the logical negation operator on non-booleans, as well as to generally implicitly convert values to bool:
```
const foo = u32(0x10);
const bar = f32(0.0);
if (foo && !bar) {
```

One idea that came up for WGSL in #727 was to merge the logical and bitwise negation operators, and in the context of that, whether or not we implicitly convert to bool.

However, in the example above, if we have `!bar` as a bitwise negation, *and* we have implicit bool(u32) conversion for conditionals, then the behavior is subtly different from what most people expect.

This issue covers whether we coerce non-bool to bool.

**Comment by johnkslang** [comment]
You will almost certainly want the error checking that comes along with doing negation this way:

- `!` for logical
- `~` for bitwise
- `-` for numeric

Assuming that, also note that both GLSL and SPIR-V manage quite well with not inserting unrequested implicit conversions from non-logical to logical types just because the wrong operator was accidentally used.  Instead, you get an error.

This helps both with mistakes and with being consistent about no-implicit conversions being a hard fast rule versus a rule that gets implemented for slightly different subsets of operations in different front-ends.

**Comment by litherum** [comment]
Coercing scalars to bools only really makes sense for pointers, where 0 is a sentinel value. It doesn't really make sense with floats at all, since floating-point equality comparison is rarely what authors want. I'd be happy with no implicit conversion to bool.

**Comment by kvark** [comment]
> It's extraordinarily common in programming languages for to use the logical negation operator on non-booleans, as well as to generally implicitly convert values to bool

I wouldn't call this extraordinary common. It's also [not always appreciated](https://dev.to/squelart/avoid-c-implicit-conversions-from-bool-14l5) in C land either.

**Comment by grorg** [comment]
This was discussed at the [2020-05-05 meeting](https://docs.google.com/document/d/1K2H59am7yLj_DBv0lfuz7g52NNyF4xcQpBs1NNnhk8g/)

**Comment by jdashg** [comment]
Resolved to forbid implicit conversions to bool, including for conditional expressions. Conditional expressions must be boolean, and a non-boolean type would be a type error.

We note also that we may want a bool(T) value-cast, but that it's somewhat orthogonal here, since we can already value-cast manually by doing `foo_int != 0`.

**Comment by jdashg** [comment]
The door is still open here for adding implicit conversion to bool in response to feedback at a later point, but the resolution here is that it'd be nice to completely forbid implicit conversions initially.
