### ISSUE TITLE
WGSL should have a shuffle builtin function

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#748]
WGSL should have the analog of OpenCL C's "[shuffle2](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/shuffle.html)" where the selector mask is a compile-time constant (or literal vector).
This has a close analog in LLVM IR in as "shufflevector" and in SPIR-V as OpVectorShuffle.
The operate on vectors as values, not as a vector-valued variable (storage).

Assuming v is a 4-element vector, Glslang implements v.xz = foo in SPIR-V as the following:

 %initial = load from v
 %newvalue = OpVectorShuffle %v_type %initial %foo 4 1 5 3
 OpStore %v %newvalue

**Comment by dneto0** [comment]
The shuffle primitive can be implemented on top of vector indexing as follows:

Original WGSL:

      const v : vec4<f32> = ...
      const w : vec2<f32> = ...
      const result : vec4<v32> = shuffle(v, w, vec4<i32>(4,1,5,3));
          // alternate spelling:     shuffle(v,w, 4,1,5,3);

This would translate to MSL:
      float4 v = ...
      float2 w = ...
      int4 mask = ...;
      float4 result = float4(
             ( (mask.x < v[mask.x] : w[mask.x-4] ),
             ( (mask.y < v[mask.y] : w[mask.y-4] ),
             ( (mask.z < v[mask.z] : w[mask.z-4] ),
             ( (mask.w < v[mask.w] : w[mask.w-4] ) );

That magic4 everywhere is the number of elements of the first vector v.

**Comment by dneto0** [comment]
Alternately, that implementation can be done more vector-like when you have a `select` function like OpenCL does: https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/select.html

**Comment by litherum** [comment]
Why not use the same syntax as HLSL and MSL and GLSL and say `v.wwxz` instead?

**Comment by johnkslang** [comment]
To clarify my up-thumbing, I like the idea of WGSL having shuffle making it more like other IRs, while still mapping it to HLL swizzles.

I also think shuffles are a good way to get the constants 1.0 and 0.0 in the mix for WGSL, while it's the HLLs that might get things like `v.zyx1`.

**Comment by litherum** [comment]
Having a function call where the arguments have to be compile-time constants seems like a mistake.

1) I'm sure it will lead to author's confusion, where it looks like a function call, but it can't accept certain values. Not even certain types of values, but certain values themselves.
2) The call can be used as an lvalue???

It's not a function call, and we shouldn't treat it as such. Using `v.wwxz` instead is just as expressive, and would solve the above problems.

**Comment by dneto0** [comment]
> Having a function call where the arguments have to be compile-time constants seems like a mistake.

Understood.

> Using v.wwxz instead is just as expressive, and would solve the above problems.

It's about combining elements from two input vectors.  That's where it gets awkward as a swizzle.

**Comment by dneto0** [comment]
Not a proposal, just wanting to generate ideas.

Instead of:

      shuffle(firstvec, secondvec, 4,1,5,3)

some alternates include magic overloads using digits:

     shuffle_4153(firstvec, secondvec);

using capital letters to indicate taking from the second vector:

      shuffle_XyYz(firstvec, secondvec);

**Comment by dneto0** [comment]
Could also be related to https://github.com/gpuweb/gpuweb/issues/737

For example (rewriting the sample from above):

     var result : vec4<f32>; // defaults to a null value of all 0 components.
     result.yw = firstvec.yz;  // sets the components taken from the first vector.
     result.xz = secondvec.xy; // sets the components taken from the second vector.

What bums me about this one is that it requires a variable because of the update to the value.  I'd really want this expressible in a single expression.

**Comment by dneto0** [comment]
If we have the OpenCL select primitive https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/select.html then we can write it as a selection of swizzles.

Same example:

    select(firstvec.xyxz, secondvec.xxyx, vec4<i32>(0,-1,0,-1))

The last arg of select doesn't have to be literals or constants.
In this incarnation some of the swizzled slots go unused. and I've filled them with 'x'.

**Comment by dneto0** [comment]
The nice thing about the select-of-swizzles is that its a plain expression: no implied loads or stores even for a naive interpretation / implementation.  Given there are no side effects, the implementation can do the work of detecting that the last arg is a constant vector and do a peephole transform to get to a direct implementation as a vector shuffle.

So maybe I only really need select.  Select is useful in its own right as a way to collapse away control flow on values when you don't need short-circuiting behaviour.

**Comment by dneto0** [comment]
I see that MSL has a select builtin, where the 3rd operand is boolean scalar or boolean vector.  That would work too.

**Comment by johnkslang** [comment]
In GLSL, that's `mix(vector-x, vector-y, bool-vector)`:

> For a component of a that is false, the corresponding component of x is returned. For a
component of a that is true, the corresponding component of y is returned

But, these are less general than swizzles and shuffles because they can't change the location of a component.

**Comment by johnkslang** [comment]
> shuffle_XyYz(firstvec, secondvec);

Something like that looks attractive.  I think you shouldn't special case the tokenizing/parsing to short-circuit the function name.  But, there would be 9 + 9^2  + 9^3 + 9^4 = 7,380 possible spellings.  Rather, how about a string argument, in addition to supporting the numeric arguments?

```
shuffle(v1, v2, "XyYz")
```
Some examples:

```
r-value v1.yyzx -> shuffle(v1, v1, "yyzx")

v = vec4(0, 0, 0, 1);
v.zyx = normal.xyz;
->
v = shuffle(vec4(0,0,0,1), normal, "ZYXw");

vec4 v;
v.zy = vec2(1, 1);
->
v = shuffle(v, vec2(1,1), "_ZY_");
```

A key thing that might not be obvious about "syntactic sugar" removal here is that it did not only remove syntactic sugar, but it also removed the whole concept of an l-value swizzle, which is greatly simplifying in the language, yet saying you want a vector from "ZYXw" in the shuffle is pretty clear, and even more clear for more complex HLL sequences.

You can use "_" in the string for a "don't care" or "undef", which is why my computation had 9s in it.

**Comment by othermaciej** [comment]
`select()` is more appealing than `shuffle()` as originally proposed here, since it can be a real function.

Not clear that it's any easier to compile to efficient code than the form involving a variable, particularly if its last argument doesn't have to be a constant.

If we do need a special direct way to express a swizzle of multiple inputs, this is probably best done as special syntax that does not look like a function call.

```
const result : vec4<i32> = vec4<i32>(w.x, v.x, w.y, v.w);
```

I think this compares favorably in readability to the original:
```
const result : vec4<v32> = shuffle(v, w, vec4<i32>(4,1,5,3));
```

Or even:
```
select(firstvec.xyxz, secondvec.xxyx, vec4<i32>(0,-1,0,-1))
```

**Comment by johnkslang** [comment]
Right, the simplest building blocks are just component selection and constructors.  Can even remove the letters and use number indexes.  (Your example is hard to express simply in an HLL swizzle, but there are lots of others that would look almost the same that are simply expressed as a swizzle.)

However, it's a bit lossy.  With every other level in the stack understanding something about swizzle/shuffle, including hardware, it's a bit sad to lose it in WGSL by breaking it all the way down to individual component extractions and then rearranging them with constructors.

Rather, I think we are looking for something closer to 1:1 between HLL and SPIR-V ops.  That is, things similar to your example are potentially one HLL statement, potentially one SPIR-V shuffle, but if really done by breaking out 4 components and then reassembling them, turns into 5 SPIR-V instructions.  The round trip to SPIR-V should be more direct than that.

**Comment by johnkslang** [comment]
> shuffle(v, w, vec4<i32>(4,1,5,3))

Can WGSL have built-in symbols for numbers (assuming no preprocessor for #define), so that this could be written this following way?

`shuffle(v, w, vec4<i32>(s2x, s1y, s2y, s1z))`

Also, a related side subject, has WGSL considered `(..., ..., ...)` as a vector constructor, instead of having the almost useless comma operator?  It's explicit typing as the arguments must match.  Then, you get

`shuffle(v, w, (s2x, s1y, s2y, s1z))`

**Comment by othermaciej** [comment]
The intent of what I wrote is that it's a recognized pattern compiled to a shuffle op for SPIR-V (and the most efficient choices we can find for other languages). I don't think we need a construct that's 1:1. Regular swizzling is already not entirely 1:1 with SPIR-V. I think we should look for clear syntax that is easy to understand and easy to compile to efficient code for all of our target shader languages (SPIR-V, MSL, HLSL/DXIL). The indirection of a `shuffle` vector, or of  the need to do irrelevant swizzling for `select`, if anything seem harder to optimize, since the compiler must recognize that it should not actually construct the vector or create the intermediate swizzles for a `select` in case of constants.

Incidentally, with bare parens as a vector constructor, it seems to me `(w.x, v.x, w.y, v.w)` is even better for conciseness and clarity than `shuffle(v, w, (s2x, s1y, s2y, s1z))`.

**Comment by kainino0x** [comment]
If I'm understanding correctly (from John's comment) `mix` (MSL's `select`) represents a different thing. I'm pretty sure `mix` is mostly used when the selection vector is dynamically computed (at least for the non-boolean overloads, which represent lerp). For cases where you don't need to swizzle, and know, locally at authoring time, I agree `vec4<i32>(w.x, v.y, w.z, v.w)` is a good syntax. However `vec4<i32>(s[0] ? v.x : w.x, s[1] ? v.y : w.y, s[2] ? v.z : w.z, s[3] ? v.w : w.w)` isn't.

Anyway, I think something more than `vec4<i32>(w.x, v.x, w.y, v.w)` is needed for `shuffle` as the former can't really be dynamic.

**Comment by litherum** [comment]
There has been some good discussion in this thread.

A few points:

1. Clearly, both `shuffle()` and `select()` are both representable with vector constructors. A theoretical WGSL -> SPIR-V compiler could pattern-match vector-constructors and determine "oh, all the fields in this vector constructor are just re-ordered fields in this other vector" and emit the SPIR-V shuffle instruction. I don't think there have been any arguments in this thread about the infeasibility of this. Similarly, if authors write `v.xz = vec2(0, 1)`, there's no question what the WGSL -> SPIR-V compiler would produce.
2. Even though they are representable using existing methods, there may still be a case for them if there is author convenience or demand. However, I see authors using `v.xz = vec2(0, 1)` and I don't see authors saying `v = shuffle2(v, vec2(0, 1), vec4(4, 1, 6, 3))`. It took concentration and maybe 30 seconds for me to write the latter, where I could write the former as fast as I can type. I think it's a tough case to make that authors actually want `shuffle2()` _instead of_ assignable multi-letter LHS fields.
3. If we want to add a new function to the standard library, either `mix()` or `select()` or both, sure, that seems reasonable. What doesn't seem reasonable is to add something that looks like a function but isn't, or a class of functions that are only differentiated by capitalization.
4. I don't think it has been demonstrated in this thread why `shuffle2()` is actually _better_ than assignable multi-letter LHS fields. It's not more powerful, as @othermaciej shows. It's not more intuitive to authors, as demonstrated by its lack of usage in existing code. It's not faster, as I (hope I've) described above in this post.

**Comment by johnkslang** [comment]
> I don't think there have been any arguments in this thread about the infeasibility of this.

It's a reasonable analysis that has to get added.  I pointed out, for example, that what could be 1 instruction in an HLL, 1 instruction in WGSL, and 1 instruction in SPIR-V temporarily gets blown up to 5 instructions in WGSL.  That blow up followed by analysis to re-collapse is worth staying aware of.

**Comment by litherum** [comment]
> gets blown up to 5 instructions in WGSL

If we add assignable multi-letter LHS fields to WGSL, `v.xz = vec2(0, 1)` stays 1 instruction in WGSL.

**Comment by othermaciej** [comment]
WGSL doesn't have instructions, it has statements and expressions. All of the proposals here involve an expression with multiple sub-expressions, which would have to be recognized by the compiler to optimize certain cases.

I do think it makes sense to add library functions for mixing/shuffling/selecting in cases where the selection vector is dynamic, if that's actually a common use case.

**Comment by johnkslang** [comment]
The issue was to add shuffle.

My reading of the goals, which need some PRs merged and some tidying, but still what I get from them is that WGSL should basically have lossless bidirectional conversion with SPIR-V, hence wanting a shuffle.

HLLs can easily map swizzles to shuffles, and then conversions to/from WGSL/SPIR-V can easily preserve the shuffles.

So, I think that means we should add shuffles.

Now, once you have that, it can be another topic what other things to also add.

**Comment by kainino0x** [comment]
> 1. Clearly, both `shuffle()` and `select()` are both representable with vector constructors.

`shuffle()` with dynamic swizzling is not practically representable with vector constructors. But realistically, not sure whether anyone needs that.

**Comment by othermaciej** [comment]
"Lossless bidirectional conversion" is not the standard that the CG agreed on. It's ok for different WGSL to map to the same SPIR-V.

This issue is not unrelated to swizzles; it was filed as a fork of https://github.com/gpuweb/gpuweb/issues/737 , an issue proposing lvalue swizzles, as an alternative to lvalue swizzles. It seems like more awkward syntax for the same thing, so I think comparison is valid. (I addition, if it's a truly general library function special-cased for constant control vector, it requires a special compiler analysis to the same degree as other, more convenient syntax.)

**Comment by johnkslang** [comment]
> shuffle() with dynamic swizzling is not practically representable with vector constructors. 

SPIR-V shuffle also does not use dynamic indexes.  For my part, I've only been discussing literal indexes.

> "Lossless bidirectional conversion" is not the standard that the CG agreed on. It's ok for different WGSL to map to the same SPIR-V.

Right, both are true, and not contradictory.  I did not mean to imply SPIR-V -> WGSL ->SPIR-V, or WGSL -> SPIR-V -> WGSL should get the same original result.  I meant it is similar enough at the operation level that what was expressed is non-lossy.

**Comment by grorg** [comment]
Discussed at the [2020-06-02 meeting](https://docs.google.com/document/d/1oGLtkcioUv-a4Fg6c5WgXxxeGo-Ut7IQd6_Y_XNK-Dc).

**Comment by dneto0** [comment]
In the meeting:
- Agreed to close this for now, and propose a "select" function under a new issue
- Get experience with translations, to see if complexity is burdensome. Revisit if necessary.

**Comment by dneto0** [comment]
Closing for now.  Revisit if experience shows we need this.
