### ISSUE TITLE
Add .rgba aliases to .xyzw

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#754]
Just like MSL, GLSL, and HLSL have, you should be able to say `myColor.rg` instead of `myColor.xy`.

**Comment by dj2** [comment]
GLSL has `stpq` for texture coordinates, does that exist in MSL and HLSL as well?

This is actually supported by Tint already but I now realize it isn't in the spec.

**Comment by jdashg** [comment]
Strong vote for rgba, weak vote against stpq.

**Comment by kvark** [comment]
I'd prefer having a single consistent way of swizzling (i.e. with "xyzw01"). There is no need to have all the bells and whistles here. I remember looking at the code which used both xyz and rgb, and I found it very confusing.

**Comment by johnkslang** [comment]
But, if you're dealing with colors (red, green, blue, and alpha), it's a bit confusing to refer to them as x, y, z, and w.

Texture coordinates are maybe less important, but they are notationally s, t, r, and q, but GLSL uses p instead of r, to avoid collision with red.

In case it's not known, GLSL has a rule that you can't mix the different kinds, so if someone accidentally uses, say, texcoord.str, they'll get a compile time error, rather than a silent .sts swizzle.

This is also trivial to implement.  (Far simpler than including 0 and 1, if you want to be consistent about ROI.)

As an IR, xyzw is fine.  If any aiming for human writable for real shaders, you'll want to deal with color.

**Comment by kvark** [comment]
> if you're dealing with colors (red, green, blue, and alpha), it's a bit confusing to refer to them as x, y, z, and w.

My mental model is that the concept of "color" is higher level to the shaders. OpenGL deprecated `gl_FragColor` a while ago. Shaders today operate on some data vectors all the time. Whether this particular vec4 it sampled from a texture is a normal, an atlas offset, a color, or something else, is all higher level semantics that doesn't have to be represented by the language grammar.

**Comment by johnkslang** [comment]
It is a very common idiom to declare this in a fragment shader:

```
out vec4 color;  // what will soon be shown on the screen, as a color
```

And, of course if you sampled a normal map, you'd deal with than in some `normal.xyz`, but if you sampled a color image, you'd deal with `color.rgb`.  Typically, the color paths can deal with lower precision than the geometry paths.

If you saw a shader with a mix of rgb and xyz and thought that was confusing, it could we be to fully understand what was happening would be much more confusing if it was only expressed as xyz.

Well, if the argument is "to keep this a simple IR" I agree.  If the argument is "color is no longer a useful abstraction in shader writing", that really seems quite off, given that a fragment shader's job is to figure out what color to up on the screen, and calling green `y` does not seem very clear.

**Comment by johnkslang** [comment]
Actually, on the "to keep this a simple IR", why use xyzw either?  SPIR-V uses 0, 1, 2, and 3, and uses shuffle instead of swizzle.  That might make more sense.  Or maybe `.0123` as proxy for all of `.xyzw`, `.rgba`, and `.stpq`.

The two positions that seem rational to me are:

1. it's an IR, use numbers and shuffles; swizzle flavors are complicating sugar
1. it's a shading language, use swizzles, colors, and geometry to properly express shading

**Comment by othermaciej** [comment]
These aliases seem useful and pretty low cost in terms of language complexity.

**Comment by kainino0x** [comment]
From a programmer perspective I'm in favor of (non-mixed) .xyzw and .rgba. I really don't think .stpq/strq/uvst are that useful, especially since there are so many different inconsistent namings, and .xyzw is perfectly understandable when used in texture-coordinate contexts.

**Comment by litherum** [comment]
Resolution: Add `.rgba` aliases, explicitly forbid mixing these with `.xyzw`, but allowing `.rgba` multi-letter swizzles in the same way that .xyzw multi-letter swizzles are allowed.

**Comment by grorg** [comment]
Discussed at the [2020-05-26 meeting](https://docs.google.com/document/d/1KuWVqle7kNaQgjcPxk_iqBZYCbgP9yIg_Ek7t7D8k3w/).
