### ISSUE TITLE
validation rules for resource usage tracking

### ISSUE THREAD

**Issue by Richard-Yunchao** [gpuweb/gpuweb#769]
Recently I am working on validation rules for resource usage tracking. Basically, multiple reads upon the same resource (buffer/texture) is allowed, but read and write, or multiple writes upon the same resource is not allowed. But a few issues/details need to be clarified: 
1. overwritten bindings, unused/invisible bindings, see the discussion at #657 
2. usage tracking for buffer should be done per the entire buffer, and usage tracking for texture should be done per each subresource. So reading from one part of a buffer and write into another part of the buffer is not allowed, while reading from a level/layer of a texture and write into another level/layer of the texture is allowed. 
3. Resource usage tracking for render should be done per each pass, while resource usage tracking for compute should be done per each dispatch call. This means that write into one buffer/texture in one draw, and then read from that buffer/texture in another draw in the same pass is not allowed in render. But it is allowed between dispatch calls in compute. 
4. Multiple writes upon the same resource is not allowed, but there are exceptions: race condition about multiple writes for storage buffer/texture is allowed for render. Further question is: how about race condition about multiple writes for storage buffer/texture for **compute**? 
5. All validation rules should work on corresponding APIs (SetBindGroup, SetVertexBuffer, DrawIndirect, etc)  via both direct commands and commands in bundle. 

Rules 2 - 4 are somehow discussed at [Usage Validation Rules] (https://github.com/gpuweb/gpuweb/blob/master/design/UsageValidationRules.md) . But that document was written 2 year ago. I'd like to clarify all these details, and maybe write some text in spec if needed.

**Comment by Kangz** [comment]
Answering based on what we discussed in the group and described in the spec, or UsageValidationRules.md when unspecified. We should detail these in the spec: people using Chromium or Dawn get confused because they don't see the rules anywhere (and UsageValidationRules.md is not very detailed), so they just accept that whatever Dawn is doing is WebGPU's behavior (which is wrong).

 1. See discussions in #657, I think people are mostly in agreement.
 1. Correct.
 1. Correct.
 1. Correct for render passes. For dispatches I believe that in San Diego we discussed resource aliasing in compute shaders as part of the programming model and agreed it would be good to prevent aliasing. However I'm not sure how practical it is on the API side, so I'd like to discuss this more.
 1. I'm not sure I understand. But in general (for validation and execution) render bundles should act as if they were inlined in the render pass.

**Comment by kvark** [comment]
The usage validation rules were given a basic spec in #557. It adds "#programming-model-synchronization" section and answers your questions, as far as I'm aware.

**Comment by kainino0x** [comment]
@Richard-Yunchao is this resolved?

**Comment by Richard-Yunchao** [comment]
Not sure.  I am writing tests in CTS for this right now. I will take another look into the spec at the same time. @kainino0x

**Comment by Kangz** [comment]
I think this is solved. @Richard-Yunchao wrote a lot of tests and didn't come back with feedback that the spec needed fixing. Closing.
