### ISSUE TITLE
Forbid --x

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#801]
The grammar allows for unary negation, e.g. `y = -x;`. 

```
unary_expression
  : singular_expression
  | MINUS unary_expression
...
```

This seems like `--x` would result in the same value as `x`. However, we may want to add the `--` prefix in the future, so we should forbid this construction for now.

**Comment by litherum** [comment]
(If an author really wants this, for some reason, they could save the intermediate result in a const, or they could use parentheses.)

**Comment by johnkslang** [comment]
They could also use spaces (in the normal/standard way).

Note a minor interaction with literals, where `-5.` should be two tokens, not one, `--5` should also be the two tokens `--` (if reserving that) and `5.`.

You can take it further, which might be important:

`a--5.`  should be parsed as `a`, `--`, `5.` (grammar error), not `a`, `-`, `-5.'

`a---5.`  should be parsed as `a`, `--`, `-`, `5.`

`a----5.`  should be parsed as `a`, `--`, `--`, `5.`

`a-----5.`  should be parsed as `a`, `--`, `--`, `-`, `5.`

Etc.

It would be best for the user if you make the grammar recognize `++` and `--` the normal expected way, and then give a semantic error in the productions "increment and decrement operators are reserved for future use", rather than just giving a syntax error.

**Comment by litherum** [comment]
> `a---5`. should be parsed as `a`, `--`, `-`, `5`.

Why not `a`, `--`, `-5`?

**Comment by johnkslang** [comment]
Because that means you can't write `a-5` as an expression which is really bizarre.  Unless you introduce white space into your *grammar* which is even more bizarre.

Doing it the normal way doesn't have these downsides.

**Comment by dneto0** [comment]
I endorse @johnkslang's suggestion of adding tokens ++ and --  to WGSL and erroring out with a helpful message.

**Comment by jdashg** [comment]
I'm half inclined to allow `a--5` => `a - -5` but let implementations warn about a AstNegate(AstNegate(AstNode)) pattern, where `a = --a` => `a = a` (Conosle Warning: `--foo` interpreted as `-(-foo)`. WGSL has no unary inc/decrement)
I don't think there's a world where we would choose not to add unary inc/decrement now, but *do* want it later.
As an example, --5 is 5 in Python.

**Comment by jdashg** [comment]
Resolved: Reserve `--` and `++` in the grammar.

**Comment by litherum** [comment]
Discussed on [today's call](https://docs.google.com/document/d/1YcpsnMS7ioeaJi4qPN1rBnYDgyQxEcudjUfyKmmq4Ik/edit?usp=drive_web&ouid=111152535986139863792).

**Comment by kvark** [comment]
Alternative suggestion from https://github.com/gpuweb/gpuweb/pull/1458#issuecomment-785394656 - just require parethesis on the unary +/- just like we do on comparison and equality in https://github.com/gpuweb/gpuweb/pull/1111#issuecomment-705039742. This would make `--x` never result in `x`.
