### ISSUE TITLE
[wgsl] Define interpolation decorations/qualifiers

### ISSUE THREAD

**Issue by frzi** [gpuweb/gpuweb#802]
[SPIR-V](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Decoration) defines the following decorations for input and output: _Noperspective_, _Flat_, _Centroid_ and _Sample_. (_Patch_ only being accessible in tessellation execution mode)

One may consider placing these next to the `in` and `out` qualifier of a `var`, like so:
```
[[location 0]] var<out, no_perspective> texCoords : vec2<f32>;
[[location 1]] var<out, flat> color : vec2<f32>;
```

Though according to SPIR-V they're also applicable to individual struct members. Perhaps next to the location/offset decoration would be a better place:
```
[[location 0, no_perspective]] var<out> texCoords : vec2<f32>;
[[location 1, flat]] var<out> color : vec2<f32>;

type Vertex = struct {
  [[offset 0, no_perspective]] position : vec3<f32>;
  [[offset 16, flat]] color : vec4<f32>;
}
```

**Comment by kvark** [comment]
Thank you for filing this!
I believe the issue needs more investigation on:
  - which interpolation qualifiers are supported on which platforms?
  - what is the validation, i.e. do they have to match between VS and FS, and what happens with Centroid/Sample in this case?
  - how are the i/o structs supported in HLSL and MSL?

Also, I'd like us to consider exposing the decoration as  `[[interpolate xxx]]` instead of having each interpolation variant as a separate decoration.

**Comment by alan-baker** [comment]
I've been looking into interpolation attributes and would propose the following for MVP.

# Proposal

 WGSL should be able to specify interpolation attributes on fragment shader inputs that are **not** builtin variables nor integral types. The syntax of the attribute is:

`[[interpolation(perspective[, sampling])]]`

`perspective` must be one of:
* `perspective` - Interpolation is perspective correct. This is the default value.
* `no_perspective` - Interpolation is linear, non-perspective correct.
* `no_interpolation` - No interpolation is performed.

`sampling` must be one of:
* `center` - Interpolation is performed at the center of the pixel. This is the default value.
* `centroid` - Interpolation is performed within the fragment and samples covered by the primitive. This value may be the same for all samples in a primitive.
* `sample` - Interpolation is performed per sample. The fragment shader is invoked once per sample when this attribute is applied.

Integral inputs must not have an interpolation attribute specified. Integral inputs are always set to no_interpolation.

`sampling` must not be specified if `perspective` is `no_interpolation`.

Interpolation attributes do not contribute to shader interface matching.

## Mapping

| Perspective | Modifier | SPIR-V Decorations | HLSL Qualifiers | MSL Attributes
|-------------|---------|---------------------|-----------------|---------------
| perspective | center | *none* | *none*<sup>1</sup> | *none*<sup>2</sup>
| perspective | centroid | Centroid | centroid<sup>1</sup> | centroid_perspective
| perspective | sample | Sample | sample<sup>1</sup> | sample_perspective
| no_perspective | center | NoPerspective | noperspective | center_no_perspective
| no_perspective | centroid | NoPerspective and Centroid | noperspective and centroid | centroid_no_perspective
| no_perspective | sample | NoPerspective and Sample | noperspective and sample | sample_no_perspective
| no_iterpolation | | Flat | nointerpolation<sup>3</sup> | flat

1. The linear qualifer may optionally be specified.
2. The center_perspective attribute may optionally be specified.
3. May be omitted on integral types.

# Survey

## Vulkan (SPIR-V)

Interpolation attributes do not participate in interface matching. Vulkan supports:
* Flat (no interpolation)
* NoPerspective (linear interpolation)
* Perspective (default, there is no decoration for this)

Additionally, Vulkan supports the following modifiers (ignored if Flat, mutually exclusive)):
* Centroid
* Sample

Interpolation decorations can only be applied to variables or members of structures. It additionally restricts them with the following VU:
>The Flat, NoPerspective, Sample, and Centroid decorations must not be used on variables with storage class other than Input or on variables used in the interface of non-fragment shader entry points

This boils down to fragment inputs only; however, there may be effects on vertex outputs in the pipeline (see shader clipping outputs). 

Integer inputs must be decorated with Flat.

Flat interpolation uses the same value of the input for all fragments in a triangle.

If neither Centroid nor Sample is decorated, the input value may be interpolated anywhere in the fragment that value may be used for all samples in the fragment. 

If Centroid is decorated, a single value may be assigned for the input for all samples, but the value must be interpolated within both the fragment and primitive (including all samples covered by the primitive). The location may differ for neighbouring fragments resulting in a lower accuracy derivative than if non-centroid interpolation were used.

If Sample is decorated, a separate value must be assigned to that variable for each covered sample in the fragment, and that value must be sampled at the location of the individual sample.

The spec is ambiguous about whether the decoration can be applied to builtins; however, glslang errors out if you redeclare a builtin variable with an interpolation qualifier. Also many of the builtins don't make sense with certain types of interpolation.

## D3D (HLSL)

HLSL provides the following modifiers:
* Linear (default, no decoration in SPIR-V)
* Centroid (must be combined with linear or noperspective, exclusive with Sample)
* Nointerpolation (Flat in SPIR-V)
* Noperspective
* Sample (can be combined with linear or noperspective, exclusive with Centroid)

Interpolation modifiers can be applied to structure members or function parameters of both vertex outputs and pixel shader inputs. GLSL does not allow builtins to be redeclared with interpolation qualifiers (only layout qualifiers).

Integers must use nointerpolation.

Centroid causes interpolation between samples within the covered area of the pixel.

Sample causes the pixel shader to execute per sample instead of per pixel.

## Metal (MSL)

Metal provides the following attributes:
* center_perspective (default)
* center_no_perspective
* centroid_perspective
* centroid_no_perspective
* sample_perspective
* sample_no_persepective
* flat

Attributes can only be applied to fragment shader inputs (or members of input structs).

Integers must use flat.

Position can only use center_no_perspective. This is interesting as it is the only mention in any spec I can find of applying interpolation qualifiers to builtins.

Center variants cause sampling at the center of the pixel.

Centroid variants cause sampling to be both within the sample and the centroid of the pixel.

Sample variants cause the fragment shader to be invoked per sample. Interpolation occurs at the sample location.

**Comment by kvark** [comment]
Thank you for investigation @alan-baker !
Doesn't any of the APIs require that the outputs have matching interpolation qualifier to the inputs? I recall that being the case somewhere.
The proposal looks reasonable. I'd just want to suggest slightly different names:

> **perspective** - Interpolation is perspective correct. This is the default value.
**linear** - Interpolation is linear, non-perspective correct.
**flat** -  No interpolation is performed.

... because otherwise it looks like this: "Let's specify colors as `red`, `non-red`, `non-blue`", which seems like a weird way to define stuff.

**Comment by alan-baker** [comment]
GLSL specifically calls out that interpolation qualifiers can mismatch between stages and that fragment inputs override any other specification. This bears out in Vulkan only allowing them on fragment inputs. MSL also seems to only allow them on fragment inputs. It wasn't entirely clear to me in HLSL if vertex and pixel shader qualifiers must match.

**Comment by dneto0** [comment]
I also prefer:  perspective, linear, flat

**Comment by dneto0** [comment]
Another naming thing: Maybe `interpolate` instead of `interpolation`?     I don't know if we have a style guide about attributes being more adjective-like rather than verb-like.

**Comment by alan-baker** [comment]
I didn't want linear because HLSL uses linear for perspective that seemed confusing. I think none over flat could be ok too. Flat doesn't really conjure anything for me and requires understanding some of the underlying implementations.

That said, I don't have strong opinions on names.

**Comment by kvark** [comment]
I think it's ok that there is a small conflict with HLSL, provided that:
  - "linear" is by default on HLSL, so people aren't really thinking about that name or knowing it exists
  - "linear" in WGSL will be an explicit opt-in. Since people don't generally opt into the defaults, seeing "linear" would make one alert and aware that something is non-trivial here.
  - I don't know how this name makes sense in HLSL SM4 (subjective!)

**Comment by alan-baker** [comment]
@pow2clk is this proposal (fragment inputs only) ok from a D3D perspective? I'm not entirely clear on the purpose of interpolation qualifiers on vertex outputs in HLSL.

**Comment by pow2clk** [comment]
The qualifier needs to match between vertex and fragment shader stages for the sake of packing rules

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-06-Minutes#wgsl-define-interpolation-decorationsqualifiers--issue-802--gpuwebgpuweb">WGSL meeting minutes 2021-04-06</a></summary>

*   Has some discussion over naming.
*   And question for D3D about interpolation qualifiers on vertex outputs.
*   AB: Was question for microsoft: can interp decorations happen on just VS? GR? Do they have to match, can they be just on the VS?
*   AB: I think Metal is FS input only
*   MM: If Metal needs on VS output, we might need to require them there too.
*   GR: Will get an answer for d3d
*   AB: Will start writing it up
*   GR: vertex `nointerpolation` qualifiers must match between vertex outputs and fragment inputs in D3D
</details>

**Comment by kvark** [comment]
@pow2clk could you shed more light on how the qualifier affects the packing rules? E.g. do the packing rules distinguish between "center" and "centroid"?
