### ISSUE TITLE
Texture usage validation constraints

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#808]
If there are any constraints about what the usage flags for texture creation can be, they need to be documented in the spec.

**Comment by Kangz** [comment]
Of note, Dawn's [Format.cpp](https://source.chromium.org/chromium/chromium/src/+/master:third_party/dawn/src/dawn_native/Format.cpp;l=103) should be a superset of what's possible because every disallowed usage stems from a limitation of one of the target APIs. It could help get a headstart on the investigation.

**Comment by Kangz** [comment]
The texture format table has been added with valid usages per format. There are also additional rules in `createTexture` validation. Closing.
