### ISSUE TITLE
Should storageTextureFormat be ignored or undefined for other binding types?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#829]
If a binding's type is not a storage-texture type, should we:
- ignore storageTextureFormat (currently specced, I think)
- require storageTextureFormat to be `undefined`

Equivalent question for the rest of the fields in GPUBindGroupLayoutEntry.

cc:
https://github.com/gpuweb/cts/pull/203#discussion_r434071915
https://github.com/gpuweb/gpuweb/pull/618#pullrequestreview-375649689
@kvark @JusSn

**Comment by kvark** [comment]
I vaguely recall a similar discussion back in the day, where @Kangz (correct if I'm wrong, please!) expressed the argument that the user may re-use the same structure at different times, and so they'd have some leftover fields that are supposedly unused, and it would be annoying if we require them to be undefined.

I think that second option - require `undefined` - is better, since it brings clarity to the expectations, i.e. if you are reading the code and you are seeing `storageTextureFormat: Something`, you don't need to look for the relevant binding type to guess if this field is used or not.

**Comment by Kangz** [comment]
It sounds like something that I could have said but I can't recall for sure. I agree that the second option looks better.
