### ISSUE TITLE
Buffer usage wierdness

### ISSUE THREAD

**Issue by krogueintel** [gpuweb/gpuweb#855]
Looking at the spec, WebGPU is doing a same-ish weird thing where a buffer, which is just a bunch of bytes, needs to have its usage declared and static for its entire lifetime. Is there a reason for this?

Secondly, there is also this:

> If descriptor.usage contains MAP_READ then the only other usage it may contain is COPY_DST.
> If descriptor.usage contains MAP_WRITE then the only other usage it may contain is COPY_SRC.

which means to get the results of a compute means one needs to then issue a copyBufferToBuffer() from the write buffer of the compute result to a buffer that is made with "MAP_READ|COPY_DST". If the compute shader has a significant output means it needs to be copied to a buffer and then that buffer is readable.

**Comment by Kangz** [comment]
> Is there a reason for this?

Yes, the bunch of bytes need to be placed in the correct memory pool with the correct alignment for the operations allowed by the usages. If you happen to add more usages after creation, implementations might have to copy the buffer to a new allocation, which would add unpredictable costs to some operations. (also some memory pools are more expensive than others, and HW bugs require workarounds for specific usages).

> which means to get the results of a compute means one needs to then issue a copyBufferToBuffer() from the write buffer of the compute result to a buffer that is made with "MAP_READ|COPY_DST". If the compute shader has a significant output means it needs to be copied to a buffer and then that buffer is readable.

That's correct. The reason is that depending on your hardware, there can be different types of memory visible by the GPU, and mappable memory can be slower for the GPU to access. If you were to do compute calculations in mappable memory with a discrete GPU, perf would be much slower than if you did it in non-mappable memory. To avoid this performance footgun, WebGPU forces mappable memory to only be used for uploads / downloads. This might later be extended to allow less copies if you are on a UMA system.

**Comment by krogueintel** [comment]
From my point of view, I can see just setting all bits except the map-able bits as up for all but the buffers written or read by the CPU. There is no references that doing so would have performance impact.

If there are situations where having different bits up or down is much more expensive or not, or for that matter triggers HW work-arounds, it would be ideal that the specification or a linked document enumerates this.

One of the big point of the explicit API's (Metal, Vulkan and D3D12) from which WebGPU is modeled and one of the big reasons behind it was for predictable performance. At this point, there is nothing in any text anywhere to hint that enabling more or less flags will impact performance. As a gentle suggestion, I hope that there will be text to which the specification links on this issue.

**Comment by Kangz** [comment]
> At this point, there is nothing in any text anywhere to hint that enabling more or less flags will impact performance. As a gentle suggestion, I hope that there will be text to which the specification links on this issue.

IMHO that shouldn't be in the main spec, but instead in a "best practices" document.

Of course the best practices will be to set only the usage flags you require, as additional usage flags can add overhead. For buffers setting `VERTEX` might cause some Intel Vulkan driver to force the usage of a smaller memory pool (to w/a a HW bug), and for textures setting `STORAGE` could prevent compression and increase memory traffic.

**Comment by krogovin** [comment]
Yes, that is right, there is a vertex-fetch cache bug on some Intel GPU's where the leading 32-bits of the 64-bit address are ignored forcing that the GPU (virtual) address needs to be in the first 4GB of GPU virtual address space.
