### ISSUE TITLE
How to read 64-bits integter from GPUBuffer?

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#866]
Currently [ArrayBuffer](https://gpuweb.github.io/gpuweb/#GPUBuffer-getMappedRange) has no Uint64Array/Int64Array type. If we want to read int64 or uint64 data from GPUBuffer such as timestamp query results, how can we do that?

In ECMA 2020, there is a [BigInt64Array](https://tc39.es/ecma262/2020/#sec-typedarray-objects)/[BigUint64Array](https://tc39.es/ecma262/2020/#sec-typedarray-objects) for that, but it's not supported on Safari ([compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigUint64Array)).

**Comment by kainino0x** [comment]
Without BigInt there is no JS number type that can hold a 64-bit integer. If you expect the value to be within the MAX_SAFE_INTEGER range of JS's number type (f64) you can store it as a number. Otherwise you have to store it in JS as two numbers (each in the 32 bit range) and manipulate it with custom arithmetic.

Without BigInt64Array/BigUint64Array (or DataView.getBigInt64/getBigUint64), in order to read a 64-bit value from an ArrayBuffer you must use Int32Array/Uint32Array, fetch two values, and combine them together. e.g. `a * 0x1_0000_0000 + b` (but be aware that this will lose precision for values beyond MAX_SAFE_INTEGER).

**Comment by magcius** [comment]
I encourage WebGPU to be the catalyst that gets Safari to fix https://bugs.webkit.org/show_bug.cgi?id=190800
