### ISSUE TITLE
Out of memory handling for GPUBuffer mapping

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#872]
Depending on the target platform, GPUBuffer mapping may be implemented using one or more buffer allocations. There may be a single allocation which is addressable both by JavaScript and the GPU, or there may be multiple allocations where the WebGPU implementation inserts copies between intermediate staging allocations to allow JavaScript to read/write GPU data. The implementation may need to use intermediate staging allocations if `VK_EXT_external_memory_host` or `ID3D12Device3::OpenExistingHeapFromFileMapping method` is not available.

Today, creating a `GPUBuffer` may generate an asynchronous out-of-memory error if allocation of the buffer fails. **Proposal:** Because on some platforms, the mapping itself is one or more additional allocations, it should be permissible for mapping the buffer to fail due to an out-of-memory error. If an out of memory error occurs, then `GPUBuffer.getMappedRange` returns `null` (or perhaps an empty ArrayBuffer).

Returning the error in `GPUBuffer.getMappedRange` means that the call to `GPUBuffer.mapAsync` **must** have succeeded. i.e. it should not be possible to have an out-of-memory error *both* on buffer creation *and* on buffer mapping, because OOM on buffer creation means the `mapAsync` promise would reject and the call to `getMappedRange` would be invalid.

**Alternatives:**
 - Reject the `mapAsync` Promise. This doesn't feel quite right because calling `mapAsync` signals the intent to map a buffer, but the script doesn't actually receive the mapped buffer allocation until calling `getMappedRange`. Further, the script may request `getMappedRange` for a smaller portion than the range passed into `mapAsync`. The implementation may defer allocation until the call to `getMappedRange`.
 - Throw an exception in `getMappedRange`. Exceptions usually indicate a programming error due to invalid usage of the API. An out-of-memory condition is not invalid usage of the API.

**Comment by kvark** [comment]
> The implementation may defer allocation until the call to getMappedRange.

Hmm, that sounds suspicious to me. I think the point of having a range in `mapAsync` is to allow the implementation to manage memory, and `getMappedRange` becomes only responsible for invalidation/flushing of the memory that's ready by then.

With that in mind, I think it would make more sense to reject the `mapAsync` promise right away.

**Comment by austinEng** [comment]
There is also the `mapAtCreation` flag, so you would be able to call `getMappedRange` synchronously.

Also some other details around that. If the implementation fails to allocate the mapping if `mapAtCreation == true`, is the entire buffer considered an error? Or can you continue to use it if the GPU allocation succeeds?

**Comment by austinEng** [comment]
This was discussed in the [06/24 VF2F](https://docs.google.com/document/d/1uv0LiQB2gAFbUEU3qx2-Sgsv6r3fEKMvnifbFoRbvmw/edit).

We concluded:
 - If separate allocations are needed, `device.createBuffer` should create both allocations. An OOM error on either would make the buffer an error buffer. Subsequent calls to `mapAsync` would reject the `Promise`
 - If `mapAtCreation == true`, if it is impossible to allocate staging memory, or even CPU-side fallback, then `device.createBuffer` should throw `RangeError`
- Staging allocations may also fail for `GPUQueue.writeBuffer` and `GPUQueue.writeTexture`. Implementations are encouraged to chunk uploads into smaller chunks to make it work. If this also fails (it should be rare), OOM errors should be surfaced using the asynchronous error scopes mechanism.

**Comment by kainino0x** [comment]
> * If `mapAtCreation == true`, if it is impossible to allocate staging memory, or even CPU-side fallback, then `device.createBuffer` should throw `RangeError`

I think this should behave the same way as ArrayBuffer allocation OOM. Which, at least in some cases, is a content process crash. In practice I'm still not sure we will ever really want to expose this error case non-crashily, but we can leave the option in the spec.

> * Staging allocations may also fail for `GPUQueue.writeBuffer` and `GPUQueue.writeTexture`. Implementations are encouraged to chunk uploads into smaller chunks to make it work. If this also fails (it should be rare), OOM errors should be surfaced using the asynchronous error scopes mechanism.

More specifically I think we should never have to worry about running out of staging memory, since chunking should always work. (If it doesn't, there are memory pressure issues not caused by the writeBuffer call, and a content process crash would probably be appropriate). IIRC we said asynchronous errors would probably only/mostly occur on failure to allocate memory on the GPU process side (maybe some kind of gpu memory allocation for staging). And in practice, again, a crash (device loss) might be more appropriate in this situation if its frequency is low.

**Comment by austinEng** [comment]
> I think this should behave the same way as ArrayBuffer allocation OOM. Which, at least in some cases, is a content process crash. In practice I'm still not sure we will ever really want to expose this error case non-crashily, but we can leave the option in the spec.

(In Chrome,) ArrayBuffer allocation fails with `RangeError` which is exactly what is suggested. Though I suppose there could be two failure modes:
 1. where the browser can't actually make an ArrayBuffer that large (the JS engine cannot address it) - `RangeError`
 2. the system is actually out of memory and can't make even a small ArrayBuffer - very uncommon, probably crash

**Comment by kainino0x** [comment]
I believe RangeError only happens in that first case. In the spec I think we should allow RangeError for an implementation-specific max size on any mappable buffer, and in Chrome we should set that to the same value as the ArrayBuffer limit.

Possibly the spec should also allow a (possibly different) implementation-specific max size for non-mappable buffer creation, that also throws RangeError.

**Comment by kainino0x** [comment]
Basically I think real OOMs should hopefully be relatively rare and should behave like real OOMs in JS - probably generally process crash. Then the page isn't expected to handle them. Perhaps we should have opt-ins for fallible allocations beyond regular create buffer.

**Comment by magcius** [comment]
From personal experience writing a large WebGL 2 app, a significant number of client-reported errors are OOMs or seemingly related issues. I currently don't handle them and let them crash. Within the last 25 days, visitors have experienced a total of 378 OOMs, an average about 16 a day. Judging by my analytics, it seems that 1% of my users hit an OOM of some sort.

This might very well be my fault. While I have added leak checking to try and detect places I do not clean up GL resources, I cannot guarantee that I have caught all issues. However, based on this experience I don't expect OOMs to be rare.

**Comment by kainino0x** [comment]
In this case I'm talking about CPU memory OOMs - GPU memory allocations are already fallible and recoverable in WebGPU. Does that data include CPU OOMs?

**Comment by austinEng** [comment]
I don't think that we should make the page crash if there's a way we can unify the OOM error into the existing error mechanisms. This way we don't have additional surface that developers have to check around.

In the F2F we came to the conclusion that `device.createBuffer` would throw an exception as it was the best way of having a synchronous error that prevents you from calling `buffer.getMappedRange` (because the mapping is not available). I forget why we had the exception on `createBuffer` instead of `getMappedRange`. It could have been because we were thinking about the API in terms of the old `createBufferMapped` function.

I failed to propose another option, which I now feel is better: `device.createBuffer` with `mapAtCreation==true` generates an asynchronous OOM error and makes the buffer internally an error. Since allocation failed for this buffer, `getMappedRange` can return some dummy CPU-side array buffer for the mapping. Errors here would do whatever normal ArrayBuffer allocation failure does.

This makes the buffer OOM happen in the same way that non-mappedAtCreation OOM occurs so developers only have to worry about that one place. `getMappedRange` failure would be more rare, particularly because it only actually allocates additional memory when the buffer creation fails (otherwise it gives you a pointer to the existing allocation).

This is effectively how errors already work in the spec today but encodes the idea that `mapAtCreation==true` means the mapping allocation **must** happen alongside buffer creation, and not at some later point, so that `getMappedRange` nearly never fails.

**Comment by kainino0x** [comment]
> I don't think that we should make the page crash if there's a way we can unify the OOM error into the existing error mechanisms. This way we don't have additional surface that developers have to check around.

I think I agree, but if apps want to respond to memory pressure by freeing resources, they need to know whether to free gpu or cpu resources.

Agree about making OOM asynchronous for createBuffer with mapAtCreation, and having the dummy allocation match normal ArrayBuffer allocation. Allocating the dummy buffer lazily (on getMappedRange) sort of makes sense since it gives the app an opportunity to check for errors first, but if apps were going to do that they would probably just use createBuffer+mapAsync. So probably fine to allocate the dummy buffer up front (on createBuffer with mapAtCreation).

If allocated up front, is there any case under which getMappedRange can fail? It seems to make most sense for it to be infallible (or nearly so - crash if it fails for some obscure reason like failure to allocate the ArrayBuffer wrapper object).

**Comment by kainino0x** [comment]
We had marked this "Needs Specification" but we had a bunch of discussion since then. Is there discussion to be had in the meeting (and if so, can we distill it)?

**Comment by kainino0x** [comment]
Resolution: Do Austin's proposal, requiring dummy buffers on mappedAtCreation failure and making getMappedRange infallible. Implementations should avoid weird failures (like shmem page allocation failures) as much as possible through synchronous flushing (or I guess triggering GC if that's possible?).

To be considered: an extra bit of information on the GPUOutOfMemoryError that indicates what kind of OOM occurred (e.g. GPU or CPU), so that applications can know what kind of resources to try to free up. Avoids adding complexity for applications that don't want to handle the extra complexity.

**Comment by kainino0x** [comment]
I'm pretty sure we don't want to try to expose OOM types yet so I'm just going to punt that, and convert this to editorial for the first thing.
