### ISSUE TITLE
Invariant qualifier

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#893]
Shader optimizers can cause exact bit results of computations to vary slightly depending on how the stars align. This can mess up algorithms that run multiple passes on the same geometry. All algorithms that involve a depth compare function of "equal" will probably fall into this problem.

We should add an `invariant` qualifier to the language to solve this problem. This qualifier indicates that the same local operation must produce consistent results, even if the global environment has changed.

MSL [has](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#//apple_ref/doc/uid/TP40014364) this qualifier today on vertex function outputs (section 5.2.3.3 Vertex Function Output Attributes). GLSL [has](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Invariance_qualifiers) (essentially) the same thing. HLSL [seems not to](https://github.com/KhronosGroup/glslang/issues/1911) have it?

**Comment by magcius** [comment]
`precise` is similar in practice to `invariant` in HLSL, and I wouldn't be surprised if drivers interpreted precise and invariant to be the same.

**Comment by johnkslang** [comment]
In GLSL, `precise` and `invariant` are specifically different, to solve different problems.  But, it is a confusing space, and the words are horribly named:

`invariant`:  same expression gets evaluated the same way in two different compilation units, so that the result is the same when the input variables have the same values.

`precise`: expressions are further invariant under permutation of symmetric operands.

`invariant` is needed when you evaluate the same vertex expression in multiple passes and want the vertices to line up in exactly the same spot.  Input values aren't subject to permutation, they're just need to be treated the same way.  The compiler uses canonical transforms to avoid different compilation units from being optimized differently.

`precise` is needed when using tessellation and from one patch to the next, to avoid cracking when the inputs to expressions get permuted.  The compiler needs to lower with operations that are symmetric (e.g., a * b == b * a, and some deeper implications of that).

In practice this often means `precise` cannot take advantage of asymmetric multiply-and-add, while `invariant` can.  But, it's not limited to that specific example.

**Comment by kvark** [comment]
@litherum this seems useful, thank you for filing!

Metal only supports that on `[[position]]`. Do we need to have it configurable, even?
Would it be a valid choice for us to always enforce this on the vertex-output position in all backends that have means to do so?

**Comment by johnkslang** [comment]
Yeah, I'd imagine that, lacking tessellation shaders, just having an `invariant Position` output from the vertex stage is like at least 95% of what's useful.

**Comment by jdashg** [comment]
So long as all our APIs support either `invariant` or `precise`, and `precise` is stricter than `invariant`, we can implement `invariant` everywhere.
Surprising to me that MSL doesn't support it generally, so I guess that ties our hands a bit.

**Comment by grorg** [comment]
Discussed at the [2020-08-11 meeting](https://docs.google.com/document/d/1YcpsnMS7ioeaJi4qPN1rBnYDgyQxEcudjUfyKmmq4Ik/). 

We nearly resolved on adding the things supported by all shading languages but deferred a final decision to next meeting.

**Comment by jdashg** [comment]
We have consensus that we need to be able to have `invariant` mode, but @kvark wants to explore/consider making it opt-out instead of opt-in.

**Comment by kvark** [comment]
I believe it would make more sense for WebGPU to make the "variance" to be an opt-in rather than opt-out, given that by default it can produce unexpected results and behave non-portably. With something like an "optimized" qualifier, users that depend on the non-trivial computations of `gl_Position` to be fast can still have that, but the regular users get portable behavior by default.

**Comment by kvark** [comment]
Also worth noting that defaulting to "invariant" internally is future-compatible, and would allow us to consider either "invariant" or "variant" keywords after MVP.

**Comment by dneto0** [comment]
Discussed in the [2020-08-18 meeting](https://docs.google.com/document/d/1P7XNQ760P5yONHTkhGAlP-AA2VpggNDGMGHaGAE2tn0/edit)

* Still agree we need the concept
* Debated which way the default should go

**Comment by dneto0** [comment]
I also have a concern that we need to be clear about which expressions are affected.

For example, if a given variable must be invariant then we need clear language that:
- any value written to the variable must be invariantly computed
- any expression feeding into an invariantly computed value must itself be invariantly computed
- recursively, any value feeding an invariantly computed expression must be invariantly computed
- any condition affecting control flow determining whether an invariantly computed expression is evaluated must itself be invariantly computed
- traced all the way back to "primary inputs" which are:
     - values loaded from variables in any storage classes except private and function
     - function parameters  (i.e. don't propagate invariance across function boundaries)

**Comment by dneto0** [comment]
Regarding which way the default should be, I'm mostly sympathetic with @jdashg that this is not a place where WebGPU needs to innovate.  Knowing to apply an invariance attribute should be part of the skill base of "graphics programming".

I feel stronger about that after I reviewed the [Metal language manual](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf).

Particularly:
- The -fpreserve-invariance compiler option must be supplied, otherwise the invariance attribute is ignored.  (For iOS 14.0 and macOS10.16 (supporting Metal 2.3)
   - prior to that it was a "best effort analysis". 
   - "This is replaced with a conservative invariant model where the compiler marks operations that doesn’t go into an invariant calculation."  (This is still not clear or precise enough to my liking.)
- The "invariant" attribute is available since Metal 2.1.  I don't know the ecosystem well enough to know if that covers all devices WebGPU would be targeting.   If the functionality is not available then that's a strong hint that it shouldn't be the default in WGSL.

**Comment by kvark** [comment]
> If the functionality is not available then that's a strong hint that it shouldn't be the default in WGSL.

If something isn't available, it can't be non-default either, unless it's an extension.
So the question is, really, what is the behavior of Metal 2.0 and lower (since it doesn't have the qualifier):
  - if it always trys to make the output position invariant, that's a strong sign that we should consider doing the same
  - if it doesn't care about invariance, then we can't have the "invariant" qualifier in the core spec, since it's not implementable on these platforms

**Comment by dneto0** [comment]
I don't understand the Metal ecosystem well enough:  What versions of Metal exist on shipped devices?


* The [main Metal page](https://developer.apple.com/metal/) doesn't mention Metal versions.
* I would guess that Metal versions updates are tied to OS updates, but, for example, the [iOS 13 updates page](https://support.apple.com/en-us/HT210393#13) doesn't mention Metal at all.
* When already running on a device, there's a version detection feature, see [here](https://developer.apple.com/documentation/metal/mtldevice/detecting_gpu_features_and_metal_software_versions)  but that doesn't help me before getting there.

So it's a mystery to me.

**Comment by kainino0x** [comment]
Apple tries very hard to prevent devs from thinking about the existence of old versions of Metal, to the extent that the only released versions of Metal have been "Metal", "Metal 2", and "Metal". On the API side, this actually makes sense: newer versions of the SDK can target older versions of the OS, so instead you're supposed to look at the API documentation to see what OS version any given entry point is available on.

This doesn't work for the shading language, because it isn't an Objective-C API. I suspect this is why Metal Shading Language *does* have version numbers. The latest is [Metal Shading Language Specification Version 2.3](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf), but Apple also deletes old copies of the shading language spec so you have to go find them on [other sites](https://web.archive.org/web/*/https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf). I have a folder full of old Metal PDFs, but:

> No part of this publication may be reproduced, stored in a retrieval system, or transmitted, in any form or by any means, mechanical, electronic, photocopying, recording, or otherwise, without prior written permission of Apple Inc., with the following exceptions: Any person is hereby authorized to store documentation on a single computer or device for personal use only and to print copies of documentation for personal use provided that the documentation contains Apple’s copyright notice.

So.

---

Anyway, I think it's a very safe guess that in Metal 1, it's always non-invariant. I've found that often when something is underspecified in Metal, it does the same thing OpenGL did.

**Comment by kainino0x** [comment]
(I forgot to say, I don't know the answer the question of what MSL versions are supported on what devices.)

**Comment by grorg** [comment]
Discussed at the [2020-08-18 meeting](https://docs.google.com/document/d/1P7XNQ760P5yONHTkhGAlP-AA2VpggNDGMGHaGAE2tn0/edit#). No resolution - waiting for feedback from @litherum

**Comment by kainino0x** [comment]
@grorg @litherum to figure out what MSL versions are supported on what OSes, so we can figure out our min MSL target is. We haven't been able to figure out where the documentation is.

**Comment by kainino0x** [comment]
I think I found it:
https://developer.apple.com/documentation/metal/mtllanguageversion?language=objc
Look at the "Availability" info for each member of the enum.

MSL | macOS | iOS
--- | --- | --- |
1.0 | none | 9.0+
1.1 | 10.11+ |  9.0+
1.2 | 10.12+ | 10.0+
2.0 | 10.13+ | 11.0+
2.1 | 10.15+ | 12.0+
2.2 | 10.15+ | 13.0+
2.3 | 11.0+ | 14.0+

**Comment by grorg** [comment]
Discussed at [2020-09-01 meeting](https://docs.google.com/document/d/1oss59oRXn0XyCe-xe9-Wkud8dwfmET70VuMDdOou2t0/).

**Comment by kainino0x** [comment]
Invariant doesn't appear in MSL until MSL 2.2, which is macOS 10.15+/iOS 13.0+. The PDF says "Since Metal 2.1" but since Metal no longer has versions, and those versions SDK versions and not OS versions, I'm going to assume that that means the same thing as "macOS 10.15 or iOS 13.0".

**Comment by kainino0x** [comment]
So assuming we can't require 10.15/13.0 for WebGPU, we can't guarantee invariance in core. @litherum says prior to the addition of the keyword, invariance is always off.

**Comment by grorg** [comment]
Discussed at the [2020-10-19 Virtual F2F](https://docs.google.com/document/d/1NejOIbytIBVw_fgMmGdX6ZL7Owz_X72xzZf9nZ-0aaE/).

**Comment by kvark** [comment]
@litherum does compiling with "-fno-fast-math" makes the vertex shader invariant?

**Comment by jdashg** [comment]
We had a good discussion in the [2020-12-15 meeting](https://docs.google.com/document/d/18m1m5aCtrR0noQJowWpecvT62H5qqrcrfNkkF6csxrM/edit#heading=h.l0sp3is87ddi) and one tentative path forward for us is:
* Specify `invariant` as a core part of WebGPU
* Have an Errata (Erratum?) that on certain older MacOS versions, it might not always be invariant (with the understanding that it will Just Work Anyways the vast majority of the time)
  * Sunset that support when we get the chance (We're only shipping next year, after all!)
* Have tests to try to catch varying invariant behavior, but with waivers for test failures there due to our known errata

If we remembered right, this is likely a problem for Gecko and Blink, but not Webkit, since Webkit does not expect to support WebGPU on these older MacOS versions. (Gecko and Blink generally support these older versions for longer)

In a couple years, these older MacOS versions will quietly sunset, and we'll be left with a core API and ecosystem that supports `invariant` guarantees.

**Comment by jdashg** [comment]
There was loose consensus for trying this, though it'd be good to hear from @grorg or back-from-vacation @litherum.

I'll repeat my note from the meeting: It would be a real miss to not support `invariant` in a 2020 graphics API at all.

**Comment by litherum** [comment]
I filed rdar://73894808 for backporting MSL features to older OSes (as per discussion at https://docs.google.com/document/d/1uYQArq9a9VqtVmLVRHOYTGUgXfDPmIR3qG9kjqOK8BY/edit#heading=h.sl2ae04kqx2h)

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-02-02-Minutes#invariant-qualifier-893">WGSL meeting minutes 2021-02-02</a></summary>


*    JG: This fell off the wagon. Had loose consensus. Not sure if MM had time to look.
*   MM: So idea is we have a feature that just doesn’t work sometimes on some hardware
*   JG: very rarely doesn't work and eventually the hardware goes away
*   MM: Seems unsatisfying.
*   DM: Is it hardware getting better or software in MSL case?
*   MM: I believe software
*   DM: And you’re aggressive at updating the software
*   MM: We don't’ ship safari to old iOS versions. We do ship webkit on old macs. I thought this was just an iOS problem, not mac.
*   JG: Think this is a metal issue.
*   KN: It’s a mac issue.
*   MM: Question is if the set of mac versions which have this keyword extend back further than webkit supports. Chrome and firefox may ship on older versions.
*   KN: It’s before 10.15 so not super old.
*   JG: Thought is if you don’t have an invariant commitment from metal, if you follow the invariant rules, and pretend even if not labeled. Suspect we’ll generally get invariant behaviour even on systems which don’t support it. In my mind, far enough down this could be an errata. Occasionally, on some OS’s there isn’t actually a commitment here. If this is just a Chrome and Firefox and Edge thing we just have to make sure they’re all happy to implement with this issue in it.
*   MM: From our point of view, this is great.
*   JG: Great, others?
*   DN: The alternative is you don’t get webgpu
*   MM: There is a middle option which is make it an extension
*   JG: Think that's unsatisfying.
*   DM: MM, don’t you allow shaders to be compiled (... missed …). If you could provide a portable compiler for us to include we could support on old systems. Then we don't’ depend on macos version when building shaders
*   KN: Not tied to SDK, pretty sure it’s tied to the OS.
*   MM: There is a frontend and backend compiler. The backend compiler is a daemon running on the machine. This is a feature both front and backend need to know about. Can ask the metal team but expect it to be impossible.
*   DM: I thought the backend was LLVM and LLVM knows how to do this and the frontend just needs to tell it.
*   MM: Webkit is one of the rare things that ships a new version of framework to old MacOS. Can ask.
*   JG: In the meantime, can we try to put `invariant` into the language and revisit if there are issues? 
*   RC: How to do on non-metal ios?
*   JG: Do your best. Invariant has to follow uniform control flow guarantees?
*   DN: You don’t fiddle with the order of operations and associated operations.
*   JG: Rules we have to follow, we’d be enforcing on the application and I believe if we enforce the rules, then not marking the code as precise, likely to just work. Otherwise, there are whole rendering systems that wouldn’t work. Think Metal decided they need stronger guarantees. So, we’d be falling back on the old way of not obviously doing anything that changes the order of ops. \
MM: I thought HLSL had a keyword?
*   JG: In HLSL yea.
*   TR: We have precise which isn’t the same but at least as good as. So we can be conformant. 
*   MM: GLSL has the same thing so SPIR-V does. Use the keyword and it works. Metal only some versions have the keyword. So Metal is only issue
*   KN: OPen question about fno-fast-math.
*   JG: DM had a question for MM about if f-no-fast-math makes vertex shader invariant.
*    MM: Think the answer is the trick would not work, but don't’ know for certain
*   JG: Agree trick is not guaranteed to work
*   KN: Agree.
*   MM: Resolve approved?
*   JG: Yes resolved needs spec.
</details>
