### ISSUE TITLE
[wgsl] num_workgroups translation for MSL and HLSL

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#920]
Looking at the various builtins in WGSL, the conversion of most of them to HLSL and MSL are convertable. For the `num_workgroups` builtin, I don't see the equivalent in HLSL. In MSL, it looks like it would convert to `grid_size` but I'm not totally sure.

From the SPIR-V spec: `NumWorkgroups` -- `Number of workgroups in GLCompute or Kernel Execution Models`.

From the MSL spec: `grid_size` -- `The maximum size of the grid over which compute threads that read per-thread stage-in data are launched.` (There are various other MSL builtins which seem similar, so this may not be the correct equivalent.)

Is there an equivalent HLSL semantic or do we need to remove `num_workgroups`?

**Comment by pow2clk** [comment]
There is no such builtin in HLSL. It could be passed in through a cbuffer of course, but it's not free.

**Comment by dj2** [comment]
Discussed at the [WGSL 2020-07-21 meeting](https://docs.google.com/document/d/17mqJR40z325U_jftDBxOYAjbzdFxKCQiIUXDEI8d9k4/edit#heading=h.1gfbnysf5cku) with the resolution to remove `NumWorkgroups` for now and file an issue to revisit after MVP.

This will need to be emulated in HLSL and it is an open question if there will be other things which also need to be emulated which would help amortize the cost.

**Comment by Kangz** [comment]
Note that emulating this builtin in HLSL gets complicated for indirect dispatches because the number of workgroups isn't know on the CPU. I can see two ways of emulating them but they're both eww:

 - Bind the indirect buffer as a root CBV so that the shader can read the num workgroup from it. Alignment constraints on UBOs might require passing an extra root constant that acts as an offset into the 256byte chunk of the UBO.
 - We're probably going to do compute-shader based validation that indirect dispatches don't exceed the maximum number of workgroups. On D3D12 we could turn indirect dispatches into an indirect command that sets 3 root constants for num_workgroup and another one that does the dispatch. The validation compute shader would expand the indirect dispatch into the data for these two commands.

Anyways both are quite involved so +1 on deferring post-MVP.

**Comment by dneto0** [comment]
I'm taking this issue, to remove this from WGSL in MVP.
