### ISSUE TITLE
Zero-sized mapAsync and getMappedRange

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#948]
Should a mapping size of 0 be allowed in mapAsync? Should a range size of 0 be allowed in getMappedRange?
In the latter case, it would mean returning an ArrayBuffer of size zero - but that's probably fine.

I sort of snuck in validation that getMappedRange size shouldn't be zero in a revision of #908. We should make sure to agree on it.

cc @kvark @Kangz

**Comment by austinEng** [comment]
I don't see a strong reason to disallow 0. We do allow zero-sized buffers because
 1. it's not hard for the implementation to implement
 2. it saves users from having to special case the zero case if their framework is computing the desired size from some inputs

**Comment by kvark** [comment]
>it's not hard for the implementation to implement

As long as we have that^, it's fine. After the group decided to require the `minBufferBindingSize` to be non-zero (because of that one element of unbound arrays), we changed the internal API to use `NonZeroU64` for sizes. So for us it may now be somewhat annoying to get that `mapAsync/getMappedRange` plumbing going.

**Comment by Kangz** [comment]
> So for us it may now be somewhat annoying to get that mapAsync/getMappedRange plumbing going.

I'm not sure why `NonZeroU64` makes it complicated, can't you use `u64` for the mapped size? Also it should be possible to catch that the size is zero and return an empty `ArrayBuffer`.
