### ISSUE TITLE
Should the spec mention location aliasing?

### ISSUE THREAD

**Issue by iraiter2** [gpuweb/gpuweb#956]
In [\<section 20.1.1\>](https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/chap21.html#fxvertex) of the Vulkan spec there is a paragraph explaining:

"Location aliasing is causing two variables to have the same location number. Component aliasing is assigning the same (or overlapping) component number for two location aliases. Location aliasing is allowed only if it does not cause component aliasing. Further, when location aliasing, the aliases sharing the location must all have the same SPIR-V floating-point component type or all have the same width integer-type components."

Similarly, the GLSL wiki explains use-cases for location aliasing in the "Interface components" section [\<here\>](https://www.khronos.org/opengl/wiki/Layout_Qualifier_(GLSL)#Interface_components). Mainly it seems to be useful for putting data into unused space, such as when passing a buffer full of mat2's (which internally are represented as vec4's, leading to 4 unused floats per mat2).

Are these limits something we should specify in the WebGPU or WGSL specs?

**Comment by kainino0x** [comment]
I think WGSL decided not to have components as part of the binding rules, so I don't think it's possible?

**Comment by johnkslang** [comment]
After subtracting out component aliasing, the question for a single WGSL shader should be whether two different input variables to the vertex shader can have the same location.  This was useful in desktop GLSL when any specific shader invocation only used a subset of inputs, none of which aliased, yet there were tight resource limits for the total of all data getting fed into the vertex shader.

I suspect WebGPU does not need this ability and should simply say that for a given active set of shader stages, there is no location aliasing.

This is more likely a WebGPU rule than a WGSL rule because it interacts with feeding vertex data into the vertex shader.

**Comment by kainino0x** [comment]
Vulkan's "location aliasing" sounds to me like this:

```glsl
layout (location=0) in float x;
layout (location=0) in float y;
// or
layout (location=0, component=0) in float x;
layout (location=0, component=1) in float y;
```
which would not appear on the API side (there's only one vertex attribute feeding into location 0).
-- am I misreading it?

On the API side we can (and do) disallow trying to stuff multiple pieces of data into the same location.

**Comment by austinEng** [comment]
Yes, this is my understanding as well. It also shouldn't stop you from having two distinct locations, but still aliasing the buffer data that's bound to them. We have a test in Dawn that this works.

**Comment by kvark** [comment]
So it sounds like we don't get to have the location aliasing at all.
Interestingly, it's related to #889, where the conclusion so far is that we *can* have binding aliasing.

**Comment by grorg** [comment]
Discussed at [2020-09-01 meeting](https://docs.google.com/document/d/1oss59oRXn0XyCe-xe9-Wkud8dwfmET70VuMDdOou2t0/).

**Comment by dneto0** [comment]
I agree this is already resolved:

- WGSL/WebGPU does not have the concept of specifying a  "component" index. There are just location numbers
- WGSL's pipeline inputs and outputs are specified as entry point arguments and entry point return (respectively).  I think this change was made after this bug was originally filed.    This simplifies the analysis.
- WGSL gives the rules, which implies no overlap among inputs, and (implicitly) no overlap among outputs.  See https://gpuweb.github.io/gpuweb/wgsl/#input-output-locations    
       -  Note that WGSL is slightly more restrictive than that: there are no overlaps among members of the same structure
       - and structs used on pipeline IO can't have members that are themselves structures.
       - Note that the return type specification of an entry point is either a single vector, scalar, or I/O shareable structure, and with the above rules, there are guaranteed to be no overlaps.

Closing.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-24-minutes#should-the-spec-mention-location-aliasing--issue-956">WGSL meeting minutes 2022-05-24</a></summary>



* AB: We forbid all such things. It’s a static error to have overlapping locations. Don’t think you can do this. 
* KG: **Looks like we resolved**
* DN: This dates back to when we declared module scoped variables. Since all entry point param and return now it’s all localized.


</details>
