### ISSUE TITLE
"Either" attachment load and store ops

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#97]
## Context

Every API with render targets has at least the following load ops:

 - Load, where the initial value of the pixel in the renderpass will be loaded from memory
 - Clear, where they will be set to a constant value
 - Don't care, where they can be any value and the app will overwrite the value anyway

Likewise every API has at least the following store ops:

 - Store, where the value is written to memory
 - Discard, where the stored value is undefined (and can just not be written)
 - Resolve, for multisample attachments (although it is part of the subpass description in Vulkan)

"Clear", "Don't care" and "Discard" are extremely important on tiler GPUs because they allow skipping memory operations are the beginning and end of render passes and save a lot of power on mobile platforms.

(side note: Vulkan resolve attachments are part of pipeline compatibility, this will be mildly annoying)

## Proposal 1

"Don't care" is undefined value, which we don't want so WebGPU could expose only "Clear" which on mobile GPUs usually happen inside the tile memory and is super cheap.

"Discard" is undefined value too but "Store" is really expensive. Instead we could have a "StoreZero" which acts as if it stores zeroes in the memory, but actually discards and clears lazily the next time the texture is used. If the next time the texture is used as loadOp "Clear" with zeroes, then that counts as a lazily clear and is cheap!

So the way to make transient attachments efficient would be to loadOp "Clear" with zeroes and "StoreZero" at the end.

## The issue with proposal 1

Proposal 1 would work great on tilers who can clear in the tile cache, but what about immediate-mode GPUs or tiler GPUs without an explicit tile cache? For these "Clear" zero and "StoreZero" could cause the following to happen:

 - The texture is clear to zero outside the render pass
 - The render pass starts, loading pixel values (no tile-cache clearing)
 - The render pass ends, storing pixel values (no discard)

This would be even worse than "Load" and "Store" because an additional clear happens.

## Proposal 2

Have the following load ops:

 - Load
 - Clear
 - LoadOrClearZero where all pixel values will start at zero, or all pixel values will start at the previously stored value.

Have the following store ops:

 - Store
 - StoreZero
 - StoreOrStoreZero where all pixels get zero stored (lazily) or all pixels get stored the final value.

Using LoadOrClearZero and StoreOrStoreZero will allow the WebGPU implementation to choose the optimal load and store ops based on the underlying hardware without exposing them but few differences for the application.

**Comment by kvark** [comment]
Both proposals don't appear ideal, although I don't have an alternative in mind right now.

> Instead we could have a "StoreZero" which acts as if it stores zeroes in the memory, but actually discards and clears lazily the next time the texture is used.

This would only work for deferred recording. If we are recording the command buffer online, we need to know which store operation to specify when doing a pass (well, ideally, ahead of time even).

And if you do record later, how would this optimization be different for non-tilers? It seems like it would equally apply, so the issue raised about the stores is addressed.

> The texture is clear to zero outside the render pass
> This would be even worse than "Load" and "Store" because an additional clear happens.

On AMD clearing a whole layer of a target is super cheap, nothing at all to be concerned about. I'd expect Intel and NVidia to also have this workflow optimized.

**Comment by Kangz** [comment]
> This would only work for deferred recording. If we are recording the command buffer online, we need to know which store operation to specify when doing a pass (well, ideally, ahead of time even).

StoreZero is always translated to a discard. It is just that the next use of the resource will have to clear it. Likewise newly created resources are "as if" they are filled with zeroes but are actually lazy-cleared.

> On AMD clearing a whole layer of a target is super cheap, nothing at all to be concerned about. I'd expect Intel and NVidia to also have this workflow optimized.

Agreed and proposal 1 is more attractive in term of API design than 2 because it is 100% well specified. We should ask these ISVs what they think about it.

**Comment by kvark** [comment]
> It is just that the next use of the resource will have to clear it.

That's what I'm referring to. If the next use of the resource is as a render pass attachment, it's obvious we can use the clear op. But more likely we'll see it used in a bind group, in which case we don't want to issue an out-of-pass clear operation.

**Comment by Kangz** [comment]
If it is StoreZero then the hope is that the application will reuse it next time as an attachment. You are likely to need an SCB before each pass to insert the correct vkPipelineBarrier anyway so I'm not sure what the issue is with inserting a clear there.

**Comment by kvark** [comment]
I'm interested in this particular case:
  1. user doesn't care about the store op, or wants it to be zeroed out (so "Zero" is specified)
  2. user then uses the resource for reading afterwards

If we treat "Zero" as Don'tCare (as Proposal 1 suggests), we'd have to then force-clear the resource before letting it being used. This may be slow on Metal, since we can only clear it by starting a dummy renderpass.

What I'm thinking is that this use case doesn't make much sense for the user to do. So why don't we just forbid it? In this case, we know that the resource will be used by another render pass, and we can decide what to do with it in `LoadOp` then. So we don't even need the "Zero" semantics and just call it "Don'tCare", matching the native APIs.

### Proposal 3:
  - expose "StoreOp::DontCare"
  - track render target subresources for whether they are valid or not. We still have to do this regardless of Proposal 3, so it's not an extra overhead.
  - forbid using the subresource for reading if it's in that invalid state (by issuing an error and turning the command buffer into null internally). Note that this also applies to resources just created.
  - allow the implementation to actually use "DontCare" store on the native APIs
  - if the user *does* need to clear to zero, they should do it themselves

**Comment by litherum** [comment]
Proposal 2 is problematic because of the behavior difference between mobile and desktop. We would prefer a solution that is well-defined everywhere.

Proposal 3 is okay, but the extra bookkeeping is something of a pain.

We're not sure how often the noted problem with proposal 1 would actually occur in practice. Because of that, we'd prefer pursuing proposal 1 for the MVP, and if it turns out our assumptions are incorrect or we get lots of pushback, we can then pursue proposal 3.

**Comment by Kangz** [comment]
> Proposal 2 is problematic because of the behavior difference between mobile and desktop. We would prefer a solution that is well-defined everywhere.

Understood that Proposal 2 is less attractive because it allows one bit of variation between implementations.

Going with proposal 1 for now sounds ok, and we can gather feedback from desktop IHVs. Note that the implementation complexity of 1 and 3 is the same, because in 1 would need to track invalidated subresources to clear them lazily and in 3 we need to track them to perform validation.

**Comment by kvark** [comment]
@litherum 
> Proposal 3 is okay, but the extra bookkeeping is something of a pain.

I want to expand on what @Kangz said. The actual difference is not bookkeeping, it's how we react on the user not doing the work: Proposal 1 says we need to clear, Proposal 3 says we need to signal an error, and user has to clear the surface themselves.

The benefit of Proposal 1 is that we can clear "just in case" and this is non-controversial from the user point of view. For example, they issue 2 copies into the surface (that is supposed to have DontCare results), which in sum cover the whole surface, so technically it's a valid initialization. In Proposal 1 an insufficiently intelligent implementation (III) would just clear before the first copy, and it would be slower than expected but acceptable. In Proposal 3 we'd need to specify that the implementation errors out on the first copy, which can raise the user's eyebrown :)

To be fair, I don't think this controversy affects real-world cases much. In the worst case, the user will see this error in development and just clear the surface themselves - the same thing as implementation in Proposal 1 would do, but more explicit (so that they are aware of the cost) and involving a bit less work on the implementation side. That's the main reason why I believe Proposal 3 is better for both the user and the implementation.

**Comment by RafaelCintron** [comment]
If the bookkeeping and maintenance is the same, Proposal 3 seems like the right thing to do for API ergonomics and performance.

**Comment by Kangz** [comment]
Going back to what we discussed in the last meeting: here we're deciding how to handle partially initialized resources (if we consider discard as uninitializing the resource). Proposal 1) says that uninitialized resources are transparently initialized to zero with the expectation that implementation will lazy clear. Proposal 3) says the application has to do the initializing and the implementation validates only initialized resources are used.

Let's look at what happens in the combination of `{Proposal 1, Proposal 3} x {Initialized, Unintialized}`.

```cpp
// R is the resource we're looking at, SR is the subresource of R the application is looking to use

// Pseudo code for proposal 1
if (R.unintialized(SR)) {
  R.clear(SR);
}

// Pseudo code for proposal 3
if (R.uninitialized(SR)) {
  R.clear(SR);
}

// Proposal 1 and 3, initialized case.

// Implementation code, returns false, nothing else happens
if (R.uninitialized(SR))

// Proposal 1, unintialized case

// Implementation code, returns true
if (R.unintialize(SR))
  // Implementation code, can either be sumbitting an immediate clear or
  // changing the loadOp to Clear
  R.clear(SR); 

// Proposal  3, uninitialized case

// Application code that has to happen to avoid errors, either immediate clear or
// changing the loadOp to Clear
R.clear(SR)
// Implementation code, returns false, nothing else happens
if (R.uninitialized(SR))
```

Hopefully the snippet above shows that the CPU and GPU costs of proposal 1 and 3 are the exact same. Given this proposal 1 seems better:

 - It reduces the amount of code for the application as well as the cognitive overhead
 - It is easier to spec with "resources start cleared" and a note saying implementation are likely to lazy-init. Proposal 3 would be a lot more words.
 - The implementation's complexity is roughly the same between proposal 1) and 3)
 - There is less state in the API that can trigger validation errors.
 - Proposal 1) is less explicit than proposal 3) though and some very advanced applications might want to know when the clear happens (but they can issue it themselves if they really care)

**Comment by kvark** [comment]
Sorry @Kangz I don't find the code snippet clear. Right at start you got:
```cpp
// Pseudo code for proposal 3
if (R.uninitialized(SR)) {
  R.clear(SR);
}
```
In proposal 3 we don't clear uninitialized resources, we require the user to do it.

> // Application code that has to happen to avoid errors, either immediate clear or
// changing the loadOp to Clear

The point is - application code knows better when the texture should be cleared. Say, imagine the scenario:
  1. render pass with an attachment X left in Don'tCare/StoreZero state
  2. something else is done here
  3. texture of attachment X is being used in a bind group

The WebGPU implementation in Proposal 1 would have to start a dummy render pass (on Metal, in particular) to clear that image before it's used in a bind group. The user, when they discover the validation error, would just change the `StoreOp` of the original pass, and this would be faster in terms of GPU cost, cleaner from the user perspective.

> Hopefully the snippet above shows that the CPU and GPU costs of proposal 1 and 3 are the exact same. 

Not in general case. See my example above.

> The implementation's complexity is roughly the same between proposal 

Roughly the same, albeit Proposal 3 is slightly lighter: both need to validate, but Proposal 3 doesn't need to work around.

> It reduces the amount of code for the application as well as the cognitive overhead

I don't think it's a good idea to try having applications not knowing what they are doing. Cognitive overhead is the _opposite_ IMO: they would have to think about not only what their code does, but also what the WebGPU implementation does lazily, and when.

> There is less state in the API that can trigger validation errors.

It's not a clear win to me: do we really want to avoid validation errors at the cost of making the implementation behavior less obvious to the user?

**Comment by Kangz** [comment]
>  Right at start you got:

Sorry I did a wrong copy paste. I fixed it to say `GenerateError() instead.`

> The user, when they discover the validation error, would just change the StoreOp of the original pass, and this would be faster in terms of GPU cost, cleaner from the user perspective.

Can you describe what would have happened on the GPU in that case with proposals 1 and 3? I don't see what additional GPU cost there is. The GPU cost would actually be worse if the application changed the `storeOp` to `Store` vs having a "discard + clear" happen.

**Comment by kvark** [comment]
> Can you describe what would have happened on the GPU in that case with proposals 1 and 3?

In Proposal-1 the implementation would have to clear the resource *out of pass*, which is most heavy on Metal. In Proposal-3 the user clears it *in the last pass* or rewrites the code to actually make sense :).

> I don't see what additional GPU cost there is. The GPU cost would actually be worse if the application changed the storeOp to Store vs having a "discard + clear" happen.

Right, if the user wanted to read from a resource that they didn't write in the last pass where it was an attachment, then "Store" would be slower than "discard + clear". However, this is more likely to be a logical error in the user code, since the operation barely makes any sense. Seeing the validation error allows the user to reconsider, and they may end up clearing the resource them selves, or they may actually do a completely different fix at a level not accessible to our implementation (i.e. not bind this resource group in the first place).

**Comment by kainino0x** [comment]
Re: Proposal 3

JG pointed out that "uninitialized" textures and "discarded" render target are the same and should be in the same state. So they should both be "implicitly zeroed" or "can only be used in clear usage".

**Comment by jdashg** [comment]
Current rough consensus is:
Load, Clear
And:
Store, DiscardToZero

DiscardToZero over Discard to make the semantic behavior obvious.

Load, as an implementation detail, might clear lazily-zeroed resources (including DiscardToZero results) prior to load/use.

Making load-from-uninitialized a validation error is interesting to me still, but we should try to simultaneously propose the equivalent change for uninitialized resources.

**Comment by Kangz** [comment]
Closing. We added the "clear" store op, that was later renamed to "discard"
