### ISSUE TITLE
Support .length() for runtime-sized arrays

### ISSUE THREAD

**Issue by iraiter2** [gpuweb/gpuweb#989]
To implement clamping on buffer access, we could use a .length() property on arrays. SPIRV supports this via OpArrayLength so it should work on all platforms.

**Comment by kvark** [comment]
> SPIRV supports this via OpArrayLength so it should work on all platforms.

SPIR-V is only used in the Vulkan backend. Other backends need to figure out how to get those dynamic array lengths.

**Comment by iraiter2** [comment]
Ah yes, I meant this is working in SPIRV-Cross. On any platform that doesn't implement this directly, we can pass the array lengths as a separate structure.

**Comment by dj2** [comment]
This seems like it would be easier to just always pass the length in a separate structure instead of special casing vulkan?

**Comment by Kangz** [comment]
> This seems like it would be easier to just always pass the length in a separate structure instead of special casing vulkan?

I don't think so, because it is Metal that's special here:

 - In SPIR-V (and Vulkan) there is `OpArrayLength` that allows getting the length of the unsized array.
 - In HLSL (and D3D12) there is `[RW]ByteAddressBuffer. GetDimensions()` that allows getting the length in bytes of the UAV and computing the unsized array length (with a subtraction and a division). (note that it doesn't work for root UAVs so we'll need something special in that rare case).
 - In MSL there is nothing.

**Comment by dj2** [comment]
We don't have the `.` notation for calling things and we decided not to go that route for the texture calls. So, maybe something like `length(runtime_array)`? or even `array_length` to be explicit?

**Comment by kainino0x** [comment]
fyi `length()` is an overloaded term: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/length.xhtml

**Comment by grorg** [comment]
Discussed at the [2020-08-18 meeting](https://docs.google.com/document/d/1P7XNQ760P5yONHTkhGAlP-AA2VpggNDGMGHaGAE2tn0/edit#)

Resolution: Add an `arrayLength()` global function that only works on runtime-sized arrays.
